### ISSUE TITLE
Error using sequential on faster-rcnn to get regional proposal network object features

### ISSUE THREAD

**Issue by nithinraok** [pytorch/vision#1001]
I’m trying to use pretrained FasterRCNN network provided in torchvision.
``` model=torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)```
```model.eval()```
```model([image_tensor]) ```
working perfectly fine but when I use sequential to stop at intermediate layers like this
```model2=nn.Sequential(*list(model.children())[:-2])```
to use until RPN network I’m getting error when passing a image as show below
```TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not tuple```

So then, I tried to inherit nn.module and implement based on [Generalized RCNN](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/generalized_rcnn.py) and [faster-rcnn.py](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/faster_rcnn.py) as shown [here](https://github.com/nithinraok/VisualQuestion_VQA/blob/master/common_resources/rpn_test_2.ipynb) but instead of Kx2048 features I'm getting 862x4. feature vector.

**Comment by fmassa** [comment]
The trick `model2=nn.Sequential(*list(model.children())[:-2])` doesn't work for all types of models, and in particular won't work for `faster-rcnn`.

The output of the RPN returns a list of proposals, which are in the format `[N, 4]`, as you obtained.
What are you looking to obtain instead? The activation maps?

**Comment by Nithin-Koluguri-Bose** [comment]
I'm looking to obtain object-centric image features (output of region proposal network) whose size is 2048xK which functions as pretrained features for VQA. Reference to paper [bottom-up](https://arxiv.org/pdf/1708.02711.pdf)

**Comment by nithinraok** [comment]
I'm sorry if my understanding of network is wrong but I'm looking to obtain object-centric image features (output of region proposal network) whose size is 2048xK which functions as pre-trained features for VQA. Reference to paper [bottom-up](https://arxiv.org/pdf/1708.02711.pdf)

**Comment by fmassa** [comment]
You might want to get the output of the `roi_pool` from the `roi_heads`, which gives you, for each proposal, the cropped feature maps at the locations specified by the proposals. Then, you can  apply your network to those cropped features to obtain your encodings

**Comment by nithinraok** [comment]
Thanks @fmassa . It worked now I am able to get all top features and subselect on them. One last piece advice, As I see I followed different approach to build model, I am guessing loading state dict would be different than usual. If its that case, is there any resource I can follow to load the model later from state dict. Thanks

**Comment by fmassa** [comment]
One easy option is to load the full pre-trained model, and pass to your class the attributes of this model. Might be the simplest approach

**Comment by nithinraok** [comment]
Sure. Thanks so much 👍 💯

**Comment by fmassa** [comment]
No worries! Let us know if you have any other comment / feedback

**Comment by YoussefSaadYoussef** [comment]
Hi @fmassa 
How can I get the output of the roi_pool?

**Comment by fmassa** [comment]
@YoussefSaadYoussef one easy way is to add a hook to get the output
```python
outputs = []
hook = model.roi_heads.box_roi_pool.register_forward_hook(
    lambda self, input, output: outputs.append(output))
res = model(inputs)
hook.remove()
print(outputs[0])
```

**Comment by YoussefSaadYoussef** [comment]
Thanks a lot for your response @fmassa 
the hook returned 1000 region proposals but  I would like to return the features only for the regions or boxes which selected at the end. specifically the mean-pooled convolutional features from these regions which have dimension D of 2048

**Comment by fmassa** [comment]
In this case, I would recommend adding the hook in the `model.backbone`, and then computing the pooling yourself. Something like
```python
outputs = []
hook = model.backbone.register_forward_hook(
    lambda self, input, output: outputs.append(output))
res = model(inputs)
hook.remove()
selected_rois = model.roi_heads.box_roi_pool(
    outputs[0], [r['boxes'] for r in res], [i.shape[-2:] for i in inputs])
print(selected_rois)
```

**Comment by ananthpn** [comment]
Thanks much @fmassa your solution works so well for me. I used this in my application and am posting here your code wrapped as a function for any one who may have a similar requirement:

![Screenshot from 2020-02-21 12-57-14](https://user-images.githubusercontent.com/1320935/75013221-c2a4ae00-54a9-11ea-900f-d22142d5d3bf.png)

**Comment by fmassa** [comment]
Great @ananthpn let us know if you have further questions

**Comment by hfaghihi15** [comment]
@fmassa how can we transform the result of the selected ROIs to the 2048 vector size using just the first layer of the pre-trained network.

**Comment by hfaghihi15** [comment]
Hi 
I am dealing with the same issue and I am trying to get the 2048 vector representations out of this pre-trained model. I used the code you introduced here to get the ROICs but I am wondering how to get the actual representations with this approach.  Can you help me @fmassa?

**Comment by fmassa** [comment]
@hfaghihi15 which 2048 vector representation are you talking about? It all depends on which layer of the model you want to get it from, and with the approach pasted by @ananthpn you can get the output of any layer that you want

**Comment by SilverLiningSL** [comment]
Hi @fmassa 
How am I supposed to get top-K features from the 1000-feature feature map? Thx

**Comment by fmassa** [comment]
The solution from https://github.com/pytorch/vision/issues/1001#issuecomment-589532923 probably do what you want

**Comment by SilverLiningSL** [comment]
> The solution from [#1001 (comment)](https://github.com/pytorch/vision/issues/1001#issuecomment-589532923) probably do what you want

Thank you!

**Comment by gorjanradevski** [comment]
> In this case, I would recommend adding the hook in the `model.backbone`, and then computing the pooling yourself. Something like
> 
> ```python
> outputs = []
> hook = model.backbone.register_forward_hook(
>     lambda self, input, output: outputs.append(output))
> res = model(inputs)
> hook.remove()
> selected_rois = model.roi_heads.box_roi_pool(
>     outputs[0], [r['boxes'] for r in res], [i.shape[-2:] for i in inputs])
> print(selected_rois)
> ```

Hey @fmassa, I need one clarification. Based on your code, does this mean that the outputs (region proposals) from the `RegionProposalNetwork` are in the original image sizes? Because in your code snippet, you provide the `proposals` in the original image size, i.e., the predicted and postprocessed ones, to the `box_roi_pool` module. Finally, I also had a look at the docstring of the forward method of `MultiScaleRoIAlign` and it states that
>boxes (List[Tensor[N, 4]]): boxes to be used to perform the pooling operation, in
                (x1, y1, x2, y2) format and in the image reference size, not the feature map
                reference.

which is inline with your code snippet. The reason for asking is because on [#1477 (comment)](https://github.com/pytorch/vision/issues/1477#issuecomment-544880821) you mentioned 
>the boxes should be in the same format as what we consider in the RPN

which in that context doesn't seem to be "the original image size". Please let me know in case I need to be more specific.

**Comment by parseh123** [comment]
Hi
I need to extract a 1024-D feature vector from the "torchvision.models.detection.fasterrcnn_resnet50_fpn" network and from the "fc6" layer for each detected object. I used the code of which is given below. With this method, for example, in an image that detects 48 boxes, 1000 feature vectors are extracted from the "fc6" layer for all proposal regions. How can I get the vector corresponding to the detected objects?

**Comment by parseh123** [comment]
@fmassa

**Comment by clarkkent0618** [comment]
Hi, how can i get all the proposal region features?  @fmassa

**Comment by clarkkent0618** [comment]
Hi, how you set the value of K? @SilverLiningSL
