### ISSUE TITLE
ImportError: DLL load failed on Windows

### ISSUE THREAD

**Issue by Jonas1312** [pytorch/vision#1018]
I have a `dll load failed the specified module could not be found` error when importing torchvision

PyTorch stable 1.1:
```
C:\Windows\system32>python -m pip install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp37-cp37m-win_amd64.whl
Collecting torch==1.1.0 from https://download.pytorch.org/whl/cu100/torch-1.1.0-cp37-cp37m-win_amd64.whl
  Using cached https://download.pytorch.org/whl/cu100/torch-1.1.0-cp37-cp37m-win_amd64.whl
Requirement already satisfied: numpy in c:\python37\lib\site-packages (from torch==1.1.0) (1.16.4+mkl)
Installing collected packages: torch
Successfully installed torch-1.1.0

C:\Windows\system32>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchvision
>>> exit()
```
Nightly:
```

C:\Windows\system32>python -m pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
Looking in links: https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
Collecting torch_nightly
  Using cached https://download.pytorch.org/whl/nightly/cu100/torch_nightly-1.1.0.dev20190612-cp37-cp37m-win_amd64.whl
Installing collected packages: torch-nightly
Successfully installed torch-nightly-1.1.0.dev20190612

C:\Windows\system32>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\torchvision\__init__.py", line 1, in <module>
    from torchvision import models
  File "C:\Python37\lib\site-packages\torchvision\models\__init__.py", line 11, in <module>
    from . import detection
  File "C:\Python37\lib\site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "C:\Python37\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "C:\Python37\lib\site-packages\torchvision\ops\__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "C:\Python37\lib\site-packages\torchvision\ops\boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: DLL load failed: La procédure spécifiée est introuvable.
>>>
```

**Comment by Jonas1312** [comment]
Any idea @peterjc123 ?

**Comment by peterjc123** [comment]
How did you try to install torchvision?

**Comment by Jonas1312** [comment]
`pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp37-cp37m-win_amd64.whl`

**Comment by peterjc123** [comment]
> @peterjc123 BTW, I think windows nightly builds haven't been updated to 1.2.0

It's nothing special. I'll need to update that in the `pytorch/builder` repo.

Would you please use something like `lucasg/Dependencies` to find the missing DLLs?

**Comment by zemelLeong** [comment]
I have same problem
> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\Python36\lib\site-packages\torchvision\__init__.py", line 1, in <module>
    from torchvision import models
  File "G:\Python36\lib\site-packages\torchvision\models\__init__.py", line 11, in <module>
    from . import detection
  File "G:\Python36\lib\site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "G:\Python36\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "G:\Python36\lib\site-packages\torchvision\ops\__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "G:\Python36\lib\site-packages\torchvision\ops\boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: DLL load failed: 找不到指定的模块。

**Comment by peterjc123** [comment]
I think I know the reason. It's because caffe2 and torch get merged now, so one DLL could not be found anymore. You'll have to rebuild torchvision to fix this.

**Comment by Jonas1312** [comment]
@peterjc123 
I'm not sure if it's exactly what you wanted: ![Capture](https://user-images.githubusercontent.com/15847892/59553005-40b1cc00-8f8f-11e9-9860-266203a69a74.PNG)

**Comment by peterjc123** [comment]
@Jonas1312 Not needed anymore. See what I said in the last post.

**Comment by zemelLeong** [comment]
![image](https://user-images.githubusercontent.com/26835087/59970785-fb018e80-95a0-11e9-982e-07a91972a12c.png)

I fixed by this.
https://pytorch.org/get-started/locally/

**Comment by peterjc123** [comment]
@zemelLeong Yes, installing stable version is also a workground if you don't use `pytorch-nightly`.

**Comment by newmluser** [comment]
can you please suggest me what is the stable version

**Comment by zemelLeong** [comment]
![image](https://user-images.githubusercontent.com/26835087/60379161-77441800-9a60-11e9-8ac7-1123619f437a.png)
pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-win_amd64.whl
pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-win_amd64.whl
https://pytorch.org/get-started/locally/

**Comment by newmluser** [comment]
Thank you. I used conda ..

**Comment by zemelLeong** [comment]
cuda10：conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
cuda9：conda install pytorch torchvision cudatoolkit=9.0 -c pytorch
none cuda：conda install pytorch-cpu torchvision-cpu -c pytorch

**Comment by plammens** [comment]
> I think I know the reason. It's because caffe2 and torch get merged now, so one DLL could not be found anymore. You'll have to rebuild torchvision to fix this.

So we have to build the latest `torchvision` from source, as in `python setup.py install` from master?

**Comment by fmassa** [comment]
@plammens yes, that seems to be the case. But we might need to make some modifications in torchvision so that this works, see https://github.com/pytorch/vision/issues/1075

**Comment by anemes** [comment]
I am encountering the same issue with `conda install pytorch torchvision cudatoolkit=10.0 -c pytorch`

```
C:\ProgramData\Anaconda3\lib\site-packages\torchvision\ops\boxes.py in <module>()
      1 import torch
----> 2 from torchvision import _C
      3 
      4 
      5 def nms(boxes, scores, iou_threshold):

ImportError: DLL load failed: The specified module could not be found.
```

**Comment by peterjc123** [comment]
@anemes Yes, that's because we didn't upload torchvision 0.4.0 for Windows. I'll tell you when it's ready.

**Comment by fmassa** [comment]
@peterjc123 now that the new Windows binaries are available, can we close this?

**Comment by peterjc123** [comment]
Yes, please.

**Comment by colin-byrneireland** [comment]
conda install pytorch torchvision cudatoolkit=10.0 -c pytorch worked for me.
I'm using latest version on anconda for windows, thks for th workaround.

**Comment by AlexLabram** [comment]
Contra @fmassa's comment, I'm not seeing any windows binaries for torchvision 0.4.0.  As of time of posting, the [webpage](https://pypi.org/project/torchvision/0.4.0/#files) has wheels for macosx and manylinux only, not win_amd64 (my system), and pip is not having any more luck.  So I'm still SOL when it comes to using torchvision.

Apologies if this bug report is the wrong place to raise this; I'm not sure what the etiquette is for dev-ops issues.

**Comment by fmassa** [comment]
@AlexLabram wheels are available for windows according to the comments in #1399

**Comment by AlexTS1980** [comment]
Git this problem with pytorch 1.7.1 and torchvision 0.4.1 and 0.3.0.

**Comment by mravunni** [comment]
same issue Got this problem with pytorch 1.7.1 and torchvision 0.4.1 and 0.3.0.

from torchvision import _C as C
ImportError: DLL load failed: The specified module could not be found.
