### ISSUE TITLE
[BUG] can't work with cpu

### ISSUE THREAD

**Issue by LXYTSOS** [pytorch/vision#1022]
In `references/detection/utils.py` line 212: `memory=torch.cuda.max_memory_allocated() / MB))`. It works fine under the GPU environment, then I train a model with pytorch-cpu, exception occurs: `AssertionError: Torch not compiled with CUDA enabled`. When I trace the error I found the code in `references/detection/utils.py`: `memory=torch.cuda.max_memory_allocated() / MB))`, when you run `torch.cuda.max_memory_allocated()` in a CPU version it will gives you that error.

**Comment by pmeier** [comment]
Fixed by @LXYTSOS in #1023.

**Comment by fmassa** [comment]
Thanks for the fix @LXYTSOS
