### ISSUE TITLE
Build error on Windows10

### ISSUE THREAD

**Issue by Jonas1312** [pytorch/vision#1029]
```
C:/Python37/lib/site-packages/torch/include\THC/THCNumerics.cuh(203): error: more than one operator "<" matches these operands:
            built-in operator "arithmetic < arithmetic"
            function "operator<(const __half &, const __half &)"
            operand types are: c10::Half < c10::Half

C:/Python37/lib/site-packages/torch/include\THC/THCNumerics.cuh(204): error: more than one operator "<=" matches these operands:
            built-in operator "arithmetic <= arithmetic"
            function "operator<=(const __half &, const __half &)"
            operand types are: c10::Half <= c10::Half

C:/Python37/lib/site-packages/torch/include\THC/THCNumerics.cuh(205): error: more than one operator ">" matches these operands:
            built-in operator "arithmetic > arithmetic"
            function "operator>(const __half &, const __half &)"
            operand types are: c10::Half > c10::Half

C:/Python37/lib/site-packages/torch/include\THC/THCNumerics.cuh(206): error: more than one operator ">=" matches these operands:
            built-in operator "arithmetic >= arithmetic"
            function "operator>=(const __half &, const __half &)"
            operand types are: c10::Half >= c10::Half

C:/Python37/lib/site-packages/torch/include\THC/THCNumerics.cuh(207): error: more than one operator "==" matches these operands:
            built-in operator "arithmetic == arithmetic"
            function "operator==(const __half &, const __half &)"
            operand types are: c10::Half == c10::Half

C:/Python37/lib/site-packages/torch/include\THC/THCNumerics.cuh(209): error: more than one operator "!=" matches these operands:
            built-in operator "arithmetic != arithmetic"
            function "operator!=(const __half &, const __half &)"
            operand types are: c10::Half != c10::Half

6 errors detected in the compilation of "C:/Users/Jonas/AppData/Local/Temp/tmpxft_000018c4_00000000-8_nms_cuda.cpp4.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1\\bin\\nvcc.exe' failed with exit status 2

```
Compiler version: `Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\`

**Comment by fmassa** [comment]
What's your PyTorch version?
Can you try using a very recent nightly?

also, cc @peterjc123

**Comment by Jonas1312** [comment]
```
>>> torch.__version__
'1.1.0.dev20190614'
```

**Comment by peterjc123** [comment]
Use the packaging scripts here: https://github.com/pytorch/vision/tree/master/packaging#windows-1.

**Comment by peterjc123** [comment]
Or you can set the env var `NVCC_FLAGS`. https://github.com/pytorch/vision/blob/master/packaging/windows/cuda100.bat#L39

**Comment by Jonas1312** [comment]
Thanks!

**Comment by GeneralJing** [comment]
> Or you can set the env var `NVCC_FLAGS`. https://github.com/pytorch/vision/blob/master/packaging/windows/cuda100.bat#L39

the link page is gone. can you reply it again？

**Comment by peterjc123** [comment]
> > Or you can set the env var `NVCC_FLAGS`. https://github.com/pytorch/vision/blob/master/packaging/windows/cuda100.bat#L39
> 
> the link page is gone. can you reply it again？ @peterjc123

https://github.com/pytorch/vision/blob/v0.4.0/packaging/windows/cuda100.bat#L39

**Comment by GeneralJing** [comment]
thank you for your reply. i met the error of this type when i compile another project.
components/spconv_cpp/src/maxpool.cu(238): error: more than one operator "==" matches these operands:
            built-in operator "arithmetic == arithmetic"
            function "operator==(const __half &, const __half &)"
            operand types are: c10::Half == c10::Half
          detected during:
            instantiation of "void spconv::maxPoolBwdGenericKernel<T,Index,NumTLP,NumILP>(const T *, const T *, const T *, T *, const Index *, const Index *, int, int) [with T=c10::Half, Index=int64_t, NumTLP=16, NumILP=4]" 
/home/idriver/CLionProjects/components/tensorview/include/tensorview/mp_helper.h(16): here
            instantiation of "F tv::detail::mp_for_each_impl(tv::mp_list<Ts...>, F &&) [with Ts=<float, double, c10::Half>, F=lambda [](auto)->auto]" 
/home/idriver/CLionProjects/components/tensorview/include/tensorview/mp_helper.h(49): here
            instantiation of "F tv::mp_for_each<L,F>(F &&) [with L=tv::mp_list<float, double, c10::Half>, F=lambda [](auto)->auto]" 
/home/idriver/CLionProjects/components/tensorview/include/tensorview/torch_utils.h(83): here
            instantiation of "void tv::dispatch_torch<Ts...,F>(c10::ScalarType, F &&) [with Ts=<float, double, c10::Half>, F=lambda [](auto)->auto]" 
/home/idriver/CLionProjects/components/tensorview/include/tensorview/torch_utils.h(98): here
            instantiation of "void tv::DispatchTorch<T<Args...>>::operator()(c10::ScalarType, F &&) [with T=tv::mp_list, Args=<float, double, c10::Half>, F=lambda [](auto)->auto]" 
even i set the NVCC_FLAGS, it still occurs error. can you give me some advice?

**Comment by GeneralJing** [comment]
solved. thanks.
