### ISSUE TITLE
MaskRCNN: Inconsistency between documentation and output

### ISSUE THREAD

**Issue by Adityav2410** [pytorch/vision#1047]
As per mask RCNN documentation,  the predicted masks have the shape: 
masks (Tensor[N, H, W]):

however as per the tutorial, https://colab.research.google.com/github/pytorch/vision/blob/temp-tutorial/tutorials/torchvision_finetuning_instance_segmentation.ipynb#scrollTo=M58J3O9OtT1G, 
and the results/output i see from the model, the masks have the shape: [N, 1, H, W]

The masks are predicted as [N, 1, H, W]
i.e. i output masks have 4 dim, whereas documentation has 3dim..

**Comment by fmassa** [comment]
Yes, this is a problem with the documentation.

Could you send a PR fixing it?
