### ISSUE TITLE
option for pretrained model for vgg net is not available.

### ISSUE THREAD

**Issue by lanpa** [pytorch/vision#106]
I installed torchvision today with conda on a new machine and found that the argument for pretrained vgg models is not available now. But the corresponding option for resnet is still there.

An older version of torchvision installed on Mar 7th works fine.

![image](https://cloud.githubusercontent.com/assets/2005323/23947699/e9c12712-09ba-11e7-93d9-b45013dadde8.png)

**Comment by soumith** [comment]
This will fix it for you
```
pip install https://github.com/pytorch/vision/archive/master.zip
```

**Comment by recastrodiaz** [comment]
I had to run ```pip uninstall torchvision``` first, but otherwise working as expected.
