### ISSUE TITLE
Ignore hidden files in datasets.ImageFolder?

### ISSUE THREAD

**Issue by lopuhin** [pytorch/vision#109]
For example, OS X likes to create ``.DS_Store`` files and they confuse ``datasets.ImageFolder`` (more precisely, the ``find_classes`` function) - it thinks this is one of the classes. Maybe it makes sense to ignore hidden files when determining classes that are present in a folder, what do you think? This particular case can also be solved if only directories were considered, not sure if it's ok to just skip regular files.

**Comment by lopuhin** [comment]
Although with #100 it is maybe less important

**Comment by daavoo** [comment]
I found the same problem.

This is fixed in this commit: https://github.com/pytorch/vision/commit/c0a6cfe186301a1733fb926f3a0da89b3283523c

But this is not included in 0.1.7 release. Installing from source includes the commit and solve the problem

**Comment by lopuhin** [comment]
Ah, so it's fixed already, great!
