### ISSUE TITLE
RandomErasing is buggy

### ISSUE THREAD

**Issue by Zhaoyi-Yan** [pytorch/vision#1094]
@zhunzhong07 @fmassa 
https://github.com/pytorch/vision/blob/master/torchvision/transforms/transforms.py#L1256-L1263

Here, you assume that `img_h < img_w` implictly, which is true for most images. However, for some images `img_h > img_w`.
``` python
if h < img_h and w < img_w:
```
This line of code equals to:
```
h/w <(ratio0~ratio1)/(scale0~scale1)
```
where the right falls in the range of (ratio0/scale1,  ratio1/scale0), here is (0.9, 16.7). Then when `h` is more than 17 times of `w`, the loop runs forever.

If the user sets custom ratio and scale,  this may happen more frequenently. At least, more checks are deserved to add. Or maybe give warnings if this probablity is high.

**Comment by zhunzhong07** [comment]
Thanks for your question. I think your inference is not correct.

`h/w <(ratio0~ratio1)/(scale0~scale1)` is not correct.

```
h = int(round(math.sqrt(erase_area * aspect_ratio)))
w = int(round(math.sqrt(erase_area / aspect_ratio)))

=>>
h/w = sqrt(erase_area * aspect_ratio / (erase_area / aspect_ratio)) = aspect_ratio

=>>
h/w is in the range of (ratio[0], ratio[1]) The default is (0.3, 1/0.3)
```
Thus. h/w is unrelated to the scale.

**Comment by Zhaoyi-Yan** [comment]
@zhunzhong07  Hi, please try `img_h = 300, img_w = 5`, then you know the loop will run all the time.

**Comment by zhunzhong07** [comment]
@Zhaoyi-Yan Thanks for your pointing out. In such strict image size (img_h/img_w=60), I think you should set ratio[1] to a large value. You could set ratio according to the size of your own image dataset.

**Comment by zhunzhong07** [comment]
@Zhaoyi-Yan I think it would be better if we change
`while True:` to `for attempt in range(100):` and return the original image?

**Comment by Zhaoyi-Yan** [comment]
Give a warning if it satisfies `if h < img_h and w < img_w:`  with low probablity(less than a threshold).   Give an error and correponding instruction if  `if h < img_h and w < img_w:`  never happens.

**Comment by fmassa** [comment]
@zhunzhong07 
> I think it would be better if we change
while True: to for attempt in range(100): and return the original image if there are no sufficient h and w selected?

This sounds good to me, but I think we can try for a few (say 10) iterations only, to keep things reasonably fast.

**Comment by zhunzhong07** [comment]
@fmassa Thanks for your suggestion. I will modify the code and create a PR.

**Comment by zhunzhong07** [comment]
#1095 Fixed here.

**Comment by fmassa** [comment]
Fixed via https://github.com/pytorch/vision/pull/1095
