### ISSUE TITLE
Error import dynamic module

### ISSUE THREAD

**Issue by buoyancy99** [pytorch/vision#1096]
I am compiling torchvision from source today. The installation seems fine but the following code gives me error. I am compiling in virtual env with python 3.6. The error is replicated across all of my devices. Also is there an estimation when torchvision_nightly will be back?

`import torch
from torchvision.models.detection import maskrcnn_resnet50_fpn

model = maskrcnn_resnet50_fpn(pretrained=True)
model.eval()
input_shape = (3, 300, 300)
x = torch.rand(input_shape)
model_input = [x]
out = model(model_input)`
The error is 

`  File "/home/boyuan/Projects/experiment/env/lib/python3.6/site-packages/torchvision/extension.py", line 12, in _lazy_import
    from torchvision import _C as C
ImportError: dynamic module does not define module export function (PyInit__C)`

**Comment by fmassa** [comment]
What version of PyTorch are you using?
Also, did you do `python setup.py clean` before rebuilding torchvision?

**Comment by buoyancy99** [comment]
> What version of PyTorch are you using?
> Also, did you do `python setup.py clean` before rebuilding torchvision?

I am using pytorch 1.1 on the official website with cuda10. I tried setup.py clean and it did not work.

**Comment by fmassa** [comment]
@buoyancy99 can you try switching to the `v0.3` branch and compiling to see if it works for you?

**Comment by buoyancy99** [comment]
> @buoyancy99 can you try switching to the `v0.3` branch and compiling to see if it works for you?

I tested the branch and it worked on the same piece of code

**Comment by fmassa** [comment]
Ok, I think TorchVision master is not compatible with PyTorch 1.1 anymore, and you'd need a nightly version of PyTorch so that it works.
