### ISSUE TITLE
Hi, is transforms do not implemented yet?

### ISSUE THREAD

**Issue by SeongJinAhn** [pytorch/vision#1102]
there are not codes implementing defining self.transforms

**Comment by pmeier** [comment]
I have no idea where you getting at. Can you elaborate on what you mean?

**Comment by SeongJinAhn** [comment]
Hmm... I have two questions
1.
there are not the code line such that
self.transforms = transforms.
Then how can it work?
2.
I'm curious that why only in sbd.py code only use transforms and not use transform, target_transform?

there are no parameters self.transform, self.target_transform
only this code is. 

is there any reason?

**Comment by fmassa** [comment]
@SeongJinAhn `self.transforms` replace `self.transform` and `self.transform_target`, and is implemented in the base class https://github.com/pytorch/vision/blob/487c9bf4b7750e779fac31c35d930381baa60a4a/torchvision/datasets/vision.py#L14-L26

If you are looking for joint transforms implementation, they are not in torchvision library, but in the reference scripts for now, see https://github.com/pytorch/vision/blob/master/references/segmentation/transforms.py for example
