### ISSUE TITLE
Having pre-built binaries for c++ side

### ISSUE THREAD

**Issue by ShahriarSS** [pytorch/vision#1122]
Hi @soumith is it a good idea to have pre-built binaries for torchvision's c++ side?

**Comment by soumith** [comment]
not at this time. we need to wait to see who will use it.

**Comment by soumith** [comment]
basically, release engineering is expensive, so we should commit to binaries only when we see significant value to offset the expense (here expense != money, we have only 1.5 people who know release engineering and they only commit < 10% of their time towards it)
