### ISSUE TITLE
nms_cuda RuntimeError

### ISSUE THREAD

**Issue by lizhen2017** [pytorch/vision#1135]
torchvision 0.3.0
pytorch 1.1
  auto order_t = std::get<1>(scores.sort(0, /* descending=*/true));
  auto dets_sorted = dets.index_select(0, order_t);
index_select break down.

RuntimeError: invalid argument 3: Index is supposed to be an empty tensor or a vector at /pytorch/aten/src/THC/generic/THCTensorIndex.cu:536

Thanks for your help!

**Comment by fmassa** [comment]
when does this error happen? Can you share an example script that reproduces the problem?

**Comment by lizhen2017** [comment]
@fmassa 
The dim of the score tensor in python is (N, ), C++ API get a (N, 1) score tensor, and then the sort function got the order_t (N, 1), so, index_select function broke down. I just use it normally. And I change the code like this, it worked. 
  auto order_t = std::get<1>(scores.sort(0, /* descending=*/true));
  order_t = order_t.squeeze(-1);
  auto dets_sorted = dets.index_select(0, order_t);

**Comment by fmassa** [comment]
How are you using the code? Is it entirely in the C++ API of torch? I don't yet understand, could you explain a bit more?

**Comment by lizhen2017** [comment]
Just using python. I debug it in the cuda code, and I found that score's dim change from [N] to [N, 1]
box [N, 4], score[N]
keep = nms(boxes=bbox, scores=score, iou_threshold=self.nms_thresh)

**Comment by lizhen2017** [comment]
Sorry, I make a big mistake. I checked my score tensor in RPN, it's [N, 1], before, I just checked score tensor in rcnn, sorry about that.
Thanks for your help. Maybe I could close this issue.

**Comment by fmassa** [comment]
@lizhen2017 note that we also have faster r-cnn models directly available in torchvision now.
