### ISSUE TITLE
Reference detection script help

### ISSUE THREAD

**Issue by gaussiangit** [pytorch/vision#1136]
Any quick way to write mask rcnn detection results from reference detection scripts in coco json format ?

**Comment by fmassa** [comment]
You can concatenate the individual results from https://github.com/pytorch/vision/blob/bbd363ca2713fb68e1e190206578e600a87baf90/references/detection/coco_eval.py#L38 (which are for only batch of images) over all images, and then save it in json.

**Comment by gaussiangit** [comment]
Perfect. Thank you :

**Comment by gaussiangit** [comment]
@fmassa I am using pretrained mask rcnn model and writing results on coco val2017. Under segm iou_type counts section seem to give incorrect results for all the batches. I get strange strings someo thing like this for counts.
__gRY43W=3L2O2N001O001O0O2O2N1N3N1O1O1O1O00000000001O01O00001O010O0000000O101O000O100O1O2N1O101N1O1O1O1O100O1O101NZfZ3'

 Can you tell me what could be wrong ?

**Comment by gaussiangit** [comment]
@fmassa Mask rcnn has RLE encoded segmentation results and coco eval script only supports RLE as of now, can not directly write RLE based results to json ? Is there better way than converting the segm results ?

**Comment by fmassa** [comment]
The RLE masks are encoded in https://github.com/pytorch/vision/blob/bbd363ca2713fb68e1e190206578e600a87baf90/references/detection/coco_eval.py#L111-L116

I suppose this is what you meant?

**Comment by gaussiangit** [comment]
Yes exactly. When I start writing with encoded counts in JSON, it throws error. I tried with ascii 
 _rle["counts"] = rle["counts"].decode("ascii")_  , but did not work. I am not sure how can I write RLE encoded segmentation results.

**Comment by fmassa** [comment]
@gaussiangit just call with `rle["counts"].decode('utf-8')`, does that not work?

What is the error you are getting?

**Comment by gaussiangit** [comment]
@fmassa TypeError: Object of type 'uint32' is not JSON serializable

**Comment by fmassa** [comment]
you are probably missing one conversion step. Try converting the numpy arrays into a list via `rle.tolist()` or something like that.

The code as it currently stands work fine on Python3, so just try debugging a bit further, it's probably a simple fix on your side.
