### ISSUE TITLE
Problem with current transforms.Scale implementation

### ISSUE THREAD

**Issue by daavoo** [pytorch/vision#114]
The current [Scale implementation](https://github.com/pytorch/vision/blob/master/torchvision/transforms.py#L94) accepts as argument a single integer `size`, and rescales the image making `size` the new size of the smaller edge.

This results in a `RuntimeError: inconsistent tensor sizes` when the Scale transform is used on datasets containing images where the smaller edge is not always the same. 

Is transforms.Scale only intended for datasets where the image shape is consistent??

As an example, the dataset of this [Kaggle competition](https://www.kaggle.com/c/intel-mobileodt-cervical-cancer-screening) contains images of varying sizes, wich shows the problem with the current implementation:
```python
d = "/train/Type_1/"
s = Scale(300)
for i in os.listdir(d):
    img = Image.open(d+i)
    print("Original: {}".format(img.size))
    resized = s(img)
    print("Resized: {}".format(resized.size))
```
```
Original: (3096, 4128)
Resized: (300, 400)

Original: (4128, 3096)
Resized: (400, 300)
```
An raises the previously mentioned error when you try to use the Scale transform as follows:
```python
train_set = ImageFolder(train_path, 
                        transform=Compose([Scale(300),
                                           ToTensor()
                                          ]))
train_loader = DataLoader(train_set, 
                          batch_size=8, 
                          shuffle=True)
for i, (images, labels) in enumerate(train_loader):
    images = Variable(images)
    labels = Variable(labels)

RuntimeError: inconsistent tensor sizes at /data/users/soumith/miniconda2/conda-bld/pytorch-cuda80-0.1.10_1488757768560/work/torch/lib/TH/generic/THTensorMath.c:2548
```

Right now I'm using my own version of the Scale transform:

```python
class Reshape(object):
    """ Rescales the input PIL.Image to the given 'shape'.
    Parameters
    ----------
    shape : tuple of int
    interpolation: Default: PIL.Image.BILINEAR
    
    """

    def __init__(self, shape, interpolation=Image.BILINEAR):
        self.shape = shape
        self.interpolation = interpolation

    def __call__(self, img):
        
        return img.resize(self.shape, self.interpolation)
```

Should I pull request this as a new transform or is there an interesetst in rewriting Scale??

**Comment by soumith** [comment]
Usually, you would want to follow `Scale` with `CenterCrop` or `RandomCrop`.

When you have images of varying sizes, what is the behavior you want, do you want to ignore the apsect ratio and scale things?

Generally in neural network literature the scale + randomcrop is what is done.

**Comment by daavoo** [comment]
Oh. The scale + crop makes a lot more sense. 
I used to use keras and I thougth that reshaping was the usual procedure as I inspected the code in https://github.com/fchollet/keras/blob/master/keras/preprocessing/image.py#L330 .
I'll try the scale + crop "combo"

**Comment by ajwitty** [comment]
What about if I only want to resize images that are smaller than my desired input size? For example, is there way to reshape images that are smaller than 224x224 and ignore all others?
