### ISSUE TITLE
Is there a plan to add a registration mechanism to torchvision.models?

### ISSUE THREAD

**Issue by zhiqwang** [pytorch/vision#1143]
Hi,
As mentioned in the test scripts:

https://github.com/pytorch/vision/blob/c187c2b12d86c3909e59a40dbe49555d85b98703/test/test_models.py#L9

I want to know whether the registration mechanism is adding to `./torchvision/models/resnet.py` or somewhere like this?

**Comment by fmassa** [comment]
This is not yet 100% clear to me that it should be done.
But by registration mechanism I meant adding a way of retrieving all possible models from a particular category (say detection, or video). We currently have some hacks that yields everything under `torchvision.models` that are functions and do not start with an underscore, but this is fragile and might be better to consider a more robust way of doing this.
