### ISSUE TITLE
torchvision.transforms.ToTensor does not produce a 3D tensor from an RGB image

### ISSUE THREAD

**Issue by ksivaman** [pytorch/vision#1160]
When an RGB PIL image (3, x, y) is converted to Tensor, resulting shape should be:

> torch.size([3, x, y])
However, it is:
>torch.size([x, y])

**Comment by pmeier** [comment]
Your title states 
> from an RGB image

but your comment reads

> grayscale PIL image

Which one is correct? Could you please post some code of what you are doing? Please try this in the root folder of the `torchvision` repository.

```python
from os import path
from PIL import Image
from torchvision.transforms import ToTensor

pil_image = Image.open(path.join("test", "assets", "grace_hopper_517x606.jpg"))
print(pil_image.size, pil_image.mode)

transform = ToTensor()
tensor_image = transform(pil_image)
print(tensor_image.size())
```

Do you see the same output as below?

```
(517, 606) RGB
torch.Size([3, 606, 517])
```

**Comment by ksivaman** [comment]
Yes I do. I know what mistake I made. Thanks.
