### ISSUE TITLE
RandomCrop determinsm between torchvision versions

### ISSUE THREAD

**Issue by jhagege** [pytorch/vision#1165]
Hi, since I moved to torchvision==0.3.0 from 0.2.2, I cannot reproduce the same results in my experiments. 
I noticed the implementation of RandomCrop has changed. 
Is it possible to somehow use the previous implementation, still being in 0.3.0 version, to keep deterministic results ?
Thanks.

**Comment by fmassa** [comment]
As with PyTorch, we do not guarantee that the random transforms (and seeds) are the same between versions.

That being said, the randomness component in `RandomCrop` hasn't changed in 2 years, but we added a `pad_if_needed` argument (which is `False` by default) that could change the results.
If nothing in your code has changed, and only the torchvision version, then I'd say that the difference is not in `RandomCrop`, but somewhere else, as the implementation is basically the same.
