### ISSUE TITLE
Crush with LSUN dataset in testing

### ISSUE THREAD

**Issue by yanghuanflc** [pytorch/vision#117]
The lmdb file I download with LSUN dataset in testing was not named as category_[train/val/test]_lmdb which used in torchvision/datasets/lsun.py. It's named like test_lmdb without any categories.

One approach to solve this problem is replacing line #73 with an if statement like:
```
       	if classes != 'test':
                classes = [c + '_' + classes for c in categories]
        else:
        	classes = [classes]
```

**Comment by soumith** [comment]
thanks. fixed in master via https://github.com/pytorch/vision/commit/1b9304c0d5e79d88fe7cd9bacc39adb2df1e0c46
