### ISSUE TITLE
Inception class in GoogLeNet,wrong kernel size?

### ISSUE THREAD

**Issue by mattiaguerri** [pytorch/vision#1171]
In the GoogLeNet implementatoin, the inception class, in branch3 the kernel size of the second convolution is 3. Shouldn’t that be 5?

**Comment by TheCodez** [comment]
https://github.com/pytorch/vision/issues/906#issuecomment-493748030

**Comment by TheCodez** [comment]
@fmassa we should probably add a comment to the affected line as it seems to often lead to confusion.

**Comment by fmassa** [comment]
@TheCodez could you send a PR adding the comment?

**Comment by fmassa** [comment]
Closing as a duplicate of https://github.com/pytorch/vision/issues/906#issuecomment-493748030
Let's keep the discussion there
