### ISSUE TITLE
coco mask converting

### ISSUE THREAD

**Issue by IgorDavidyuk** [pytorch/vision#1195]
https://github.com/pytorch/vision/blob/4ec38d496db69833eb0a6f144ebbd6f751cd3912/references/detection/coco_utils.py#L170
Docs for MASK R-CNN claims that target should contain 'masks (``UInt8Tensor[N, 1, H, W]``)'
But the line of code above treats it like tensor with 3 dimensions. Catching errors.

**Comment by fmassa** [comment]
Good catch! This is indeed a bug in the documentation, and was introduced in https://github.com/pytorch/vision/pull/1089

I'm sending a PR fixing this
