### ISSUE TITLE
No ImageNet pretrained model of deeplabv3_resnet101

### ISSUE THREAD

**Issue by bityangke** [pytorch/vision#1223]
Thanks very much for the amazing repo. 
Why not provide ImageNet pretrained model of deeplabv3_resnet？
I believe it is very important for researchers who want to use torchvision seg models.
A pretrained model on 20 classes subset of coco is of very limited significance.

**Comment by fmassa** [comment]
Hi,

`deeplabv3_resnet101` is a semantic segmentation model. ImageNet is a dataset for image classification, so we do not have exactly the same setup there to be able to provide models for `deeplabv3_resnet101` trained end-to-end in ImageNet.

We do however accept a `pretrained_backbone` flag in the segmentation models https://github.com/pytorch/vision/blob/8635be94d1216f10fb8302da89233bd86445e449/torchvision/models/segmentation/segmentation.py#L19
which allows us to re-use the pre-trained weights from ImageNet in the `deeplabv3_resnet` model, and this is generally what is used for most research papers.

I'm closing this issue as I believe I have addressed your question, but let me know if you disagree.
