### ISSUE TITLE
Latest version nonexisting on windows

### ISSUE THREAD

**Issue by FilipAndersson245** [pytorch/vision#1228]
TorchVison is broken on Windows as the current version available is v0.3
This is using the new PyTorch v1.2.

**Comment by peterjc123** [comment]
There's no need to post these everywhere. I'll handle this.

**Comment by peterjc123** [comment]
They should be available now.

**Comment by fmassa** [comment]
@peterjc123 can we close this?

**Comment by peterjc123** [comment]
Yes

**Comment by fmassa** [comment]
Thanks @peterjc123 for all your help!
