### ISSUE TITLE
Missing blank space in bottom and right side of image generate using make_grid

### ISSUE THREAD

**Issue by yanghuanflc** [pytorch/vision#124]
There only has blank space on top and left side of the whole image generate using make_grid. The bottom and right side doesn't have a blank space. I think change line #68 in utils.py can fix this problem:
grid = tensor.new(3, height * ymaps, width * xmaps).fill_(0) ----->
grid = tensor.new(3, height * ymaps + padding, width * xmaps + padding).fill_(0)

**Comment by fmassa** [comment]
Can you send a Pull Request with a fix?

**Comment by yanghuanflc** [comment]
PR #129
