### ISSUE TITLE
Hard requirement of torch==1.2.0?

### ISSUE THREAD

**Issue by RomainSabathe** [pytorch/vision#1257]
Hello, I'm revisiting the dependencies for my project and I haven't done that in a long time. I have been using torch 1.1.0 for quite a while; I am confident my code works with it. However it seems like torchvision now requires torch 1.2.0. Here's the output from poetry (pipenv gave a more verbose but essentially same output):

```Using version ^0.4.0 for torchvision

Updating dependencies
Resolving dependencies... (0.1s)
                                                                                                                     
[SolverProblemError]                                                                                  
Because torchvision (0.4.0) depends on torch (1.2.0)                                                               
 and no versions of torchvision match >0.4.0,<0.5.0, torchvision (>=0.4.0,<0.5.0) requires torch (1.2.0).          
So, because my_project depends on both torch (=1.1.0) and torchvision (^0.4.0), version solving failed.  
```

Is this intended or is this a 'bug'? Am I missing something? Thanks.

**Comment by soumith** [comment]
this is not intended to be a bug. you can use torchvision 0.3.0 to use with pytorch 1.1.0

**Comment by Multihuntr** [comment]
The Pypi description for 0.4.0 still says:

> TorchVision requires PyTorch 1.1 or newer.

But if you have PyTorch 1.1 installed, then installing `pip install torchvision==0.4.0` with miniconda will remove PyTorch 1.1 and install PyTorch 1.2

**Comment by soumith** [comment]
whoops, the pypi description needs to be fixed.

**Comment by sbelharbi** [comment]
hi,
i am installing `pytorch 1.3.0` using `pip install torch torchvision`
i am getting `ERROR: torchvision 0.4.0 has requirement torch==1.2.0, but you'll have torch 1.3.0 which is incompatible.`

but,

it succeeds to install!
`Successfully installed torch-1.3.0 torchvision-0.4.0`
```sh
$pip freeze
...
torch==1.3.0
torchvision==0.4.0
...
```
in the [release note](https://github.com/pytorch/vision/releases/tag/v0.4.0) it says `Note: torchvision 0.4 requires PyTorch 1.2 or newer`

[pypi](https://pypi.org/project/torchvision/) says `TorchVision requires PyTorch 1.1 or newer.`

the doc issue mentioned above may be still going on.
thanks

**Comment by fmassa** [comment]
@soumith do you know how we update the pypi readme?

@sbelharbi if you install PyTorch 1.3.0, you need torchvision 0.4.1, or else you'll face import errors.
torchvision 0.4.0 works with PyTorch 1.2.0

**Comment by sbelharbi** [comment]
for now, quick import didn't raise an issue.
i'll try it out this week and see.
in case of issues, i'll downgrade to torch.1.2.0 and wait for torchvision.0.4.1.
thanks

```sh
In [1]: import torch

In [2]: import torchvision

In [3]: torch.__version__
Out[3]: '1.3.0'

In [4]: import torchvision.transforms.functional as TF

```

```sh
$ pip freeze | grep -w "torchvision"
torchvision==0.4.0
```

**Comment by sbelharbi** [comment]
first try leads to cuda incompatibility (requires cuda 10.1, i have 10.0). my fault.
i get torch.1.3.0 and torchvision.0.4.1 from [wheels](https://download.pytorch.org/whl/cu100/torch_stable.html).
thanks for the heads up.
```sh
torch==1.3.0+cu100
torchvision==0.4.1+cu100
```

**Comment by soumith** [comment]
@fmassa you upload a source distribution `python setup.py sdist`  and then `twine upload` the created file, then it will use the description etc. from setup.py to populate the README. If I remember correctly.

**Comment by Multihuntr** [comment]
It uses the `long_description` field from the `setup.py`, which uses your `README.rst`: https://github.com/pytorch/vision/blob/master/setup.py#L203

But I can see that that should have been updated as of v0.4.1? But it still says "TorchVision requires PyTorch 1.1 or newer." on pypi for `v0.4.1.post2`? Something weird is going on.

Btw; I looked this up when I came across this before (I was curious), and there's a giant thread of people complaining that you can't upload a new description without uploading the whole thing again: https://github.com/pypa/warehouse/issues/2170
