### ISSUE TITLE
ImageFolder hanging in wait state

### ISSUE THREAD

**Issue by FuriouslyCurious** [pytorch/vision#126]
Using imagefolder to load images for training, but it always seems to hang here:  Substituting "ImageFolder" with "CIFAR10" always works.

```
^CTraceback (most recent call last):
  File "train.py", line 291, in <module>
    main()
  File "train.py", line 132, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "train.py", line 157, in train
    for i, (input, target) in enumerate(train_loader):
  File "/conda3/envs/idp/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 168, in __next__
    idx, batch = self.data_queue.get()
  File "/conda3/envs/idp/lib/python3.5/queue.py", line 164, in get
    self.not_empty.wait()
  File "/conda3/envs/idp/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by soumith** [comment]
this is not information for us to figure out or fix the issue.
Can you give a small script to reproduce the issue?

**Comment by FuriouslyCurious** [comment]
Sure Soumith:

I tried out Amos' DenseNet and your ImageNet examples and replaced CIFAR10 dataset with ImageFolder dataset:

Original:

    trainLoader = DataLoader(
            dset.CIFAR10(root='cifar', train=True, download=True,
                         transform=trainTransform),
            batch_size=args.batchSz, shuffle=True, **kwargs)
        testLoader = DataLoader(
            dset.CIFAR10(root='cifar', train=False, download=True,
                         transform=testTransform),
            batch_size=args.batchSz, shuffle=False, **kwargs)

Modified:

    trainLoader = DataLoader(
        dset.ImageFolder(root='/home/FC/data/P/train',  transform=trainTransform),
        batch_size=args.batchSz, shuffle=True, **kwargs)
    testLoader = DataLoader(
        dset.ImageFolder(root='/home/FC/data/P/val',  transform=testTransform),
        batch_size=args.batchSz, shuffle=False, **kwargs)

But loading process hangs forever. Keyboard interrupt shows:

    ^CTraceback (most recent call last):
      File "train.py", line 291, in <module>
        main()
      File "train.py", line 132, in main
        train(train_loader, model, criterion, optimizer, epoch)
      File "train.py", line 157, in train
        for i, (input, target) in enumerate(train_loader):
      File "/conda3/envs/idp/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 168, in __next__
        idx, batch = self.data_queue.get()
      File "/conda3/envs/idp/lib/python3.5/queue.py", line 164, in get
        self.not_empty.wait()
      File "/conda3/envs/idp/lib/python3.5/threading.py", line 293, in wait
        waiter.acquire()
    KeyboardInterrupt

What should I do to resolve this?
Folder structure is following with 2048x2048 PNGs:

    /home/FC/Data/P
    -> train -> classes -> images.png
    -> val -> classes -> images.png

**Comment by FuriouslyCurious** [comment]
Closing - this was not an issue, but rather a change required to model in order to allow higher res images.

In case someone stumbles upon this issue through Google, here is a pointer on how to fix it:

https://discuss.pytorch.org/t/how-do-i-feed-higher-res-images-to-model-zoo-models/1442/2

**Comment by tsing90** [comment]
the same issue, my reason is the input image size is not the same as the model required!

**Comment by tsing90** [comment]
I have the same issue, but my reason is that the dataloader stuck in a loop which is my fault. so that the model cannot have input feeded.
