### ISSUE TITLE
Certificate issues with github in Python 2

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#1268]
Tests in Python2 are now failing with error
```
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```
see e.g., https://travis-ci.org/pytorch/vision/jobs/573261632

This is due to a change in github it seems, and has been worked around in PyTorch in https://github.com/pytorch/pytorch/pull/25042

A few possible solutions:
- change the download link in the test to use a different domain than github
- skip the test for Python2 for now
- use the unverified context trick from https://github.com/pytorch/pytorch/pull/25042, but this can lead to some vulnerabilities

I'd vote for trying out option 2 for now.

**Comment by kimishpatel** [comment]
@fmassa, it seems to be an issue on some of the py3 builds also (pytorch_linux_xenial_cuda9_cudnn7_py3_NO_AVX2_test , pytorch_linux_xenial_cuda9_cudnn7_py3_NO_AVX_NO_AVX2_test). Any suggestions?

**Comment by fmassa** [comment]
@kimishpatel those seem like PyTorch builds? I think they relate to torchhub, and maybe not torchhub? Could you point to those issues?
cc @ailzhang
