### ISSUE TITLE
Torchvision functional rotate should have a fill option

### ISSUE THREAD

**Issue by ginacode** [pytorch/vision#1277]
torchvision.transforms.functional.rotate should have a fill option, or something to let us choose black or white. Padding and random crop all have a fill option,

**Comment by ginacode** [comment]
Thank you! Although it is not necessary for my application, perhaps there should be a fill option on transforms.RandomRotation as well.

**Comment by pmeier** [comment]
The change for `transforms.RandomRotation` is already included in the PR.
