### ISSUE TITLE
Cannot compile from source after changing .data to Tensor.data_ptr

### ISSUE THREAD

**Issue by tgaddair** [pytorch/vision#1285]
Hey @ppwwyyxx, as part of Horovod's CI process, we build torchvision from source, but since #1262 was introduced we're seeing build failures of the form:

```
/tmp/pip-req-build-k0laem_f/torchvision/csrc/cpu/ROIAlign_cpu.cpp: In lambda function:
/tmp/pip-req-build-k0laem_f/torchvision/csrc/cpu/ROIAlign_cpu.cpp:409:45: error: expected primary-expression before '>' token
    input.contiguous().data_ptr<scalar_t>(),
```

See [this](https://buildkite.com/horovod/horovod/builds/1090#96b91131-0b3f-49be-98e7-6bc63844ecf4/6-4003) run in BuiltKite for more details.

Any idea as to what might be causing these build failures?

Thanks.

**Comment by ppwwyyxx** [comment]
torchvision master now has to be built with pytorch master, rather than pytorch stable.

**Comment by tgaddair** [comment]
I see.  Thanks for the response @ppwwyyxx.  Using `pip` with https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html, it looks like their nightly build is still pointing to `v1.2.0` (last built with Python 2.7 on August 5).  Using conda, are you working off of `v1.3.0`?

**Comment by soumith** [comment]
hey @tgaddair . Have you use `--pre`? Our command for nightlies has changed, please look at pytorch.org 

Now it is listed as:

```
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
```

**Comment by tgaddair** [comment]
Thanks @soumith, just tried it out and seems to be working.  I'll close this.
