### ISSUE TITLE
transforms.Resize()

### ISSUE THREAD

**Issue by machine52vision** [pytorch/vision#1294]
transforms.Resize(()) is based python image library(PIL)，But PIL's resize and opencv's resize results are inconsistent,Experiments show that there are bugs in resize of PIL.

**Comment by pmeier** [comment]
> Experiments show that there are bugs in resize of PIL.

If that is the case you should address them directly in the [`pillow` project](https://github.com/python-pillow/Pillow). We are not part of this development and simply _use_ `PIL` for the image I/O interface in python.

There is a motion to replace `PIL` (#1225, #1226), but its still in its infancy.

---

I've never worked with `opencv`, but I imagine it shouldn't be hard to create your own custom transfrom:

```python
from collections import Sequence


class OpenCVResize(object):
    def __init__(self, size, open_cv_params):
        assert isinstance(size, int) or isinstance(size, Sequence) and len(size) == 2
        # size = (height, width) if size is a Sequence
        self.size = size
        self.open_cv_params = open_cv_params

    def __call__(self, pil_image):
        return self.open_cv_to_pil(self.open_cv_resize(self.pil_to_open_cv(pil_image)))

    def pil_to_open_cv(self, pil_image):
        raise NotImplementedError

    def open_cv_to_pil(self, open_cv_image):
        raise NotImplementedError

    def open_cv_resize(self, open_cv_image):
        raise NotImplementedError
```

If you implement `pil_to_open_cv`, `open_cv_to_pil`, and `open_cv_resize` you have a drop-in replacement for `transforms.Resize()`

**Comment by fmassa** [comment]
We've now provided a tensor-based implementation for `Resize` which matches OpenCV results.
