### ISSUE TITLE
EMNIST download url changed

### ISSUE THREAD

**Issue by C-nit** [pytorch/vision#1296]
https://github.com/pytorch/vision/blob/26c9630bc7add88685400e54457203816c06e750/torchvision/datasets/mnist.py#L230

EMNIST url changed to 
`https://cloudstor.aarnet.edu.au/plus/s/ZNmuFiuQTqZlu9W/download`

**Comment by jtiscione** [comment]
Neither of these URLs is correct.

**Comment by fmassa** [comment]
@pmeier can you have a look?

The link in https://www.nist.gov/node/1298471/emnist-dataset doesn't work anymore (i.e., http://www.itl.nist.gov/iaui/vip/cs_links/EMNIST/gzip.zip) ?

**Comment by pmeier** [comment]
This is weird. At the time of creating the PR the link was working. Even the [official website of EMNIST](https://www.westernsydney.edu.au/bens/home/reproducible_research/emnist) lists this link. I'll look into it.

**Comment by C-nit** [comment]
I contacted the owner of the data and they are frustrated with their storage provider since the links broke twice now. He's looking for a better solution, so there might be a working official link in a few days again.

**Comment by pmeier** [comment]
@C-nit Please reopen this, if you get the new and official download link.

**Comment by Tabrizian** [comment]
EMNIST url still not working.

**Comment by fmassa** [comment]
@Tabrizian this has been fixed in master, and the fix is present in a nightly.

Note that the fix didn't get in the 0.4.2 release
