### ISSUE TITLE
Add ONNX tests to CircleCI

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#1326]
They are currently only being run in Travis. We should add something like https://github.com/pytorch/vision/blob/a91fe7221b55c55dbbc23c23aecf33d470a5c08e/.travis.yml#L51-L53 to CircleCI tests as well

**Comment by r-zenine** [comment]
Hi @fmassa , 

Here is a first fix for linux_wheel pipelines. 
https://github.com/pytorch/vision/pull/1950

Thanks

**Comment by fmassa** [comment]
Thanks for the PR @r-zenine !

I've added some comments, let me know what you think

**Comment by fmassa** [comment]
They have been added in https://github.com/pytorch/vision/pull/3144
