### ISSUE TITLE
MaskRCNN: ValueError: Does not understand character buffer dtype format string ('?')

### ISSUE THREAD

**Issue by tgkul** [pytorch/vision#1355]
I was trying to train MaskRCNN on my own dataset but I get this error every time during evaluation. Even if I try to train the model on PennFudanDataset from this [link,](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html) the same error occurs. Though the code works on provided [Colab](https://colab.research.google.com/github/pytorch/vision/blob/temp-tutorial/tutorials/torchvision_finetuning_instance_segmentation.ipynb)

My docker container has Python 3.5, Pytorch 1.2.0, Torchvision 0.4.0

@fmassa 
Can you help me figure out what could be the issue?

> Traceback (most recent call last):
  File "train.py", line 76, in <module>
    main()
  File "train.py", line 69, in main
    evaluate(model, val_data_loader, device=device)
  File "/root/miniconda3/envs/pytorch/lib/python3.5/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "../../lib/engine.py", line 95, in evaluate
    coco_evaluator.update(res)
  File "../../lib/coco_eval.py", line 38, in update
    results = self.prepare(predictions, iou_type)
  File "../../lib/coco_eval.py", line 66, in prepare
    return self.prepare_for_coco_segmentation(predictions)
  File "../../lib/coco_eval.py", line 113, in prepare_for_coco_segmentation
    for mask in masks
  File "../../lib/coco_eval.py", line 113, in <listcomp>
    for mask in masks
  File "/root/miniconda3/envs/pytorch/lib/python3.5/site-packages/pycocotools/mask.py", line 82, in encode
    return _mask.encode(bimask)
  File "pycocotools/_mask.pyx", line 137, in pycocotools._mask.encode
ValueError: Does not understand character buffer dtype format string ('?')

**Comment by fmassa** [comment]
This is an error in `pycocotools`.

I suspect it's a problem with you environment locale.

Try checking the `locale` in colab and in your system, it might be relevant.

Given that this is not a problem with torchvision, I'm closing this issue, but let me know if you think otherwise

**Comment by XuShoweR** [comment]
Did you resolve the problem, i also met this error.

**Comment by astronstar** [comment]
> Did you resolve the problem, i also met this error.

i meet now

**Comment by nicolasCruzW21** [comment]
in coco_eval
Use this 
```
rles = [
mask_util.encode(np.array(mask[0, :, :, np.newaxis], dtype=np.uint8, order="F"))[0]
for mask in masks
]
```
instead of 
```
        rles = [
            mask_util.encode(np.array(mask[0, :, :, np.newaxis], order="F"))[0]
            for mask in masks
        ]
```

**Comment by tolgaakar** [comment]
@nicolasCruzW21  I changed this line in coco_eval but i am still getting the same error. I am using Google Colab (python version 3.6.8), and I tried it with both PyTorch 1.2 and 1.3. 



> in coco_eval
> Use this
> 
> ```
> rles = [
> mask_util.encode(np.array(mask[0, :, :, np.newaxis], dtype=np.uint8, order="F"))[0]
> for mask in masks
> ]
> ```
> 
> instead of
> 
> ```
>         rles = [
>             mask_util.encode(np.array(mask[0, :, :, np.newaxis], order="F"))[0]
>             for mask in masks
>         ]
> ```

**Comment by fmassa** [comment]
@nicolasCruzW21 this fix is BTW present in torchvision since https://github.com/pytorch/vision/pull/1413 , and is available in a nightly release
