### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by ibtingzon** [pytorch/vision#1365]
I get the following error when I try to compile from source using `python setup.py install`. Any ideas on how to fix it? 
> installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying torchvision/version.py -> build/lib.linux-x86_64-3.7/torchvision
running build_ext
building 'torchvision._C' extension
gcc -pthread -B /home/issa/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/issa
/test/vision/torchvision/csrc -I/home/issa/test/env/lib/python3.7/site-packages/torch/include -I/home/issa/test/env/lib/python3.7/site-packages/torch/include/torch/
csrc/api/include -I/home/issa/test/env/lib/python3.7/site-packages/torch/include/TH -I/home/issa/test/env/lib/python3.7/site-packages/torch/include/THC -I/usr/local
/cuda/include -I/home/issa/test/env/include -I/home/issa/anaconda3/include/python3.7m -c /home/issa/test/vision/torchvision/csrc/vision.cpp -o build/temp.linux-x86_
64-3.7/home/issa/test/vision/torchvision/csrc/vision.o -O0 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/issa/test/vision/torchvision/csrc/vision.cpp:8:0:
/home/issa/test/vision/torchvision/csrc/ROIAlign.h:80:24: error: ‘torch::autograd::AutogradContext’ has not been declared
 using torch::autograd::AutogradContext;
                        ^~~~~~~~~~~~~~~
/home/issa/test/vision/torchvision/csrc/ROIAlign.h:84:58: error: expected template-name before ‘<’ token
 class ROIAlignFunction : public torch::autograd::Function<ROIAlignFunction> {
                                                          ^
/home/issa/test/vision/torchvision/csrc/ROIAlign.h:84:58: error: expected ‘{’ before ‘<’ token
/home/issa/test/vision/torchvision/csrc/ROIAlign.h:84:58: error: expected unqualified-id before ‘<’ token
error: command 'gcc' failed with exit status 1

**Comment by fmassa** [comment]
What are your GCC version and PyTorch versions? TorchVision requires a recent-enough PyTorch (newer than 1.2)

**Comment by ibtingzon** [comment]
GCC version is:
> gcc (Ubuntu 6.5.0-2ubuntu1~16.04) 6.5.0 20181026
Copyright (C) 2017 Free Software Foundation, Inc.

Pytorch version:
> Name: torch
Version: 1.2.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/issa/geoai-nbig/env/lib/python3.7/site-packages
Requires: numpy
Required-by: torchvision

**Comment by fmassa** [comment]
Yes, if you want to use torchvision from master you'll need a `nightly` release of PyTorch.

Alternatively, you can also install a binary from torchvision from version 0.4.0, which is compatible with PyTorch 1.2.

I'm closing this issue as it's expected to happen: torchvision master requires PyTorch newer than 1.2.

**Comment by korabelnikov** [comment]
@fmassa
I'm trying to build torchvision  version 0.4.0 against torch 1.2 and got same errror

gcc 5.4
arm64 (no possible binary packages)

**Comment by fmassa** [comment]
@korabelnikov what error did you get, if you got an error message containing something like
```
class ROIAlignFunction : public torch::autograd::Function {
```
then this means that you are using torchvision from master, and not from 0.4.0. I'd recommend you double-checking which version of torchvision you have cloned, and if you have checkout the 0.4.0 branch
