### ISSUE TITLE
Faced AttributeError: module 'torch.jit' has no attribute 'unused' when running GoogleNet

### ISSUE THREAD

**Issue by Huangxt57** [pytorch/vision#1383]
When I run the following code
```
import torch
model = torch.hub.load('pytorch/vision', 'googlenet', pretrained=True)
model.eval()
```
There are some mistakes and I encounter: 
`AttributeError: module 'torch.jit' has no attribute 'unused'`
And in `inception.py` line 168, there is `@torch.jit.unused`.
How can I solve this problem if I want to use your official implementation GoogleNet?

**Comment by fmassa** [comment]
Hi,

TorchVision master now requires a recent enough version of PyTorch.
One thing you can do is to use `torchvision.models.googlenet`, or update your PyTorch installation.

Also, see https://github.com/pytorch/hub/issues/55 for more discussion about this problem (which is in TorchHub, and not in torchvision).

As such, I'm closing this issue, but feel free to continue the discussion at that issue in torchhub

**Comment by Huangxt57** [comment]
Thank you very much~

**Comment by sdfs1231** [comment]
but i install latest version of pytorch and torchvision, this still happend

**Comment by fmassa** [comment]
@sdfs1231 You need to install a nightly version of PyTorch and torchvision.
Alternatively, next week we will be releasing a new stable version of both.
