### ISSUE TITLE
for training on custom dataset

### ISSUE THREAD

**Issue by vinayhpandya** [pytorch/vision#1386]
for training on custom dataset do i need to change its format which resembles like that of COCO or 
pascal

**Comment by pmeier** [comment]
Please provide more information so we can help you:

- Is it an image dataset?
- Is it an image detection dataset?
- Do you store the individual images on your drive or are they wrapped in some container?
- How does your training loop look like?

A good start is [this official tutorial](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html).

**Comment by fmassa** [comment]
Another great tutorial is https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html , which shows you how to adapt a custom dataset to instance segmentation, finetuning from a model pre-trained on COCO.

If you have further questions, please open a new issue with the information that @pmeier has outlined in his message.
