### ISSUE TITLE
Torchvision 0.4.0 has no wheels for win_amd64

### ISSUE THREAD

**Issue by AlexLabram** [pytorch/vision#1399]
Configuration:
- Windows 10 Enterprise (64-bit)
- python 3.7.4
- pip 19.2.3

I'm trying to resolve issue #1018 on my system by upgrading from Torchvision 0.3.0 to 0.4.0.  However, attempting to run `pip install torchvision` in an admin console just leaves me with v0.3.0.

On investigation, PyPI currently only has `macosx` and `manylinux` wheels for this version (see page [here](https://pypi.org/project/torchvision/0.4.0/#files)).  I understand my system would fall under `win_amd64`.

Please can the relevant wheels be built and uploaded.

**Comment by peterjc123** [comment]
They are able to be installed using the steps on pytorch.org.
As for the reason why they are not hosted on PyPI, maybe @soumith can tell you more details.

**Comment by peterjc123** [comment]
I am going to close this because the statement on the topic is not true.

**Comment by AlexLabram** [comment]
Hi @peterjc123.  Thanks, the more detailed `pip install` command given on the PyTorch page worked.  Apologies for not picking up on this myself; I've never had to use pip's `--find-links` option before.

I'd be interested to hear (e.g. from @soumith) if there's a reason the wheels didn't make it as far as PyPI, but that's no longer a blocking issue for me.

**Comment by soumith** [comment]
we have an issue with binary sizes on pypi. The pypi team has generously given us an increment to ship our wheels, but out windows wheels are larger than that limit.
