### ISSUE TITLE
Variable input resolutions for ResNets

### ISSUE THREAD

**Issue by macaodha** [pytorch/vision#140]
The current implementation of the ResNet models has a fixed [7x7 average pooling](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L110) layer before the final FC  layer.

If this was changed to `nn.AdaptiveAvgPool2d(1)` it would allow for variable sized input batches (e.g. like the 320x320 batches used at test time in the 'Identity Mappings in Deep Residual Network' paper)? Although I'm not sure if this will incur a performance hit?

**Comment by fmassa** [comment]
This has been implemented in https://github.com/pytorch/vision/pull/643
