### ISSUE TITLE
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor builtins.ModuleNotFoundError: No module named 'torchvision.models'; 'torchvision' is not a package

### ISSUE THREAD

**Issue by swathipai13** [pytorch/vision#1414]
Have tried all of the methods. The torch vision is installed successfully.Some attachments that say.
![Screenshot from 2019-10-04 17-09-49](https://user-images.githubusercontent.com/28557076/66204998-dd78b080-e6c9-11e9-943a-cc8efbe7cd55.png)
Need help. Any other way only torch vision models can be installed?

**Comment by fmassa** [comment]
Hi,

You are following the wrong installation instructions. You installed a very old version of torchvision (0.1.8), which doesn't have those models (and uninstalled 0.4 on the way)

I'd recommend doing
```
pip uninstall torchvision
```
and then follow the instructions in https://pytorch.org/get-started/locally/
```
pip install torchvision
```

**Comment by swathipai13** [comment]
Hi,

tried that. Still the same error!

"from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
builtins.ModuleNotFoundError: No module named 'torchvision.models';
'torchvision' is not a package"

**Comment by swathipai13** [comment]
Hi,

tried that. Still the same error!

"from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
builtins.ModuleNotFoundError: No module named 'torchvision.models';
'torchvision' is not a package"

**Comment by swathipai13** [comment]
open #1414

**Comment by swathipai13** [comment]
Even tried for the latest torch vision. 

pip install torchvision==0.4

**Comment by fmassa** [comment]
Can you do `torchvision.__version__`? This will probably indicate that you are using an older version.

You probably have a conflict in your system, and the solution is to remove all instances of torchvision that you currently have, and re-install.

**Comment by swathipai13** [comment]
so here is an attachment. I am using latest version of torch vision
![Screenshot from 2019-10-04 20-21-10](https://user-images.githubusercontent.com/28557076/66217229-89c79080-e6e4-11e9-9a80-61729da87a3a.png)
, under packages.

**Comment by swathipai13** [comment]
Reopened #1414

**Comment by fmassa** [comment]
This doesn't mean that your installation is using the latest version of torchvision.

Can you do
```
conda uninstall torchvision
pip uninstall torchvision
pip uninstall torchvision
```
and try installing again? That is most probably a conflict with your install.

I'll keep the issue open due to your request, but I've just now re-compiled torchvision and everything works fine

**Comment by swathipai13** [comment]
This worked! Thank you! I guess I myself had to close it!
![upload](https://user-images.githubusercontent.com/28557076/66230914-dae67d00-e702-11e9-941d-663610df19cb.png)

**Comment by swathipai13** [comment]
-

**Comment by feiyangsuo** [comment]
Say, may you tell which version of torchvision are you using? I'm with the same problem now.

**Comment by fmassa** [comment]
@feiyangsuo detection models are available in the 0.3.0 version of torchvision, and last released version is 0.6.0.

Installation instructions can be found in https://pytorch.org/get-started/locally/

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
torchvision version is 0.6.1

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
import torchvision.optim as optim
ModuleNotFoundError: No module named 'torchvision.optim'

**Comment by jiajunhua** [comment]
Thanks in advance. how to fix the problem????????????????????????????????????????????????????????????????????????????????????????????

**Comment by jiajunhua** [comment]
Need help.

**Comment by jiajunhua** [comment]
Need help

**Comment by jiajunhua** [comment]
Need help

**Comment by jiajunhua** [comment]
Need help

**Comment by feiyangsuo** [comment]
> import torchvision.optim as optim
> ModuleNotFoundError: No module named 'torchvision.optim'

```from torch import optim```
since ```torchvision``` has no ```optim``` module.
BTW, pls don't repeat a question for such many times, which may get others hard to find answers to their question

**Comment by jiajunhua** [comment]
> > import torchvision.optim as optim
> > ModuleNotFoundError: No module named 'torchvision.optim'
> 
> `from torch import optim`
> since `torchvision` has no `optim` module.
> BTW, pls don't repeat a question for such many times, which may get others hard to find answers to their question

Sorry, thanks. The problem has been fixed in last night.

**Comment by teddylegessemunea** [comment]
Uninstall torch, torchvision, and torchaudio. Then install the packages from preview(Nightly) from the following link https://pytorch.org/get-started/locally/

> pip uninstall torch torchvision torchaudio

> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu117 --no-cache-dir
