### ISSUE TITLE
Found possible security issue. How should I report it?

### ISSUE THREAD

**Issue by le1nux** [pytorch/vision#1415]
I found a possible security issue in this repository.
How would you like me to share it with you? 

Best regards
Max

**Comment by fmassa** [comment]
Thanks for opening this issue.

Let me discuss with @soumith first and then I'll get back to you.

**Comment by fmassa** [comment]
Can you send me an e-mail to `[my-github-username]@fb.com`, where you replace `[my-github-username]` with my user name?

**Comment by le1nux** [comment]
Sure. I just sent you the email.

**Comment by fmassa** [comment]
Discussed this on e-mail.
