### ISSUE TITLE
[suggestion] ResNet to subclass Sequential?

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/vision#143]
It would be simpler to remove last layers and keeping names without having to construct a new Sequential and calling `add_module`

**Comment by fmassa** [comment]
Could you expand on your suggestion? It's not clear for me what you mean, do you want the full resnet model features to be in a sequential?

**Comment by vadimkantorov** [comment]
I was suggesting that the `features` part of the ResNet model should be easily operable.

Currently to strip off the classifier (AvgPool, view and fc) and to preserve the names of submodules (`layer1`, `layer2`, etc) one has to reconstruct a Sequential.

One way would be creating a field `features` (with `layer1`, `layer2`, etc as its submodules).
Another may be subclassing `ResNet` class from `Sequential` and calling a base constructor with the list of submodules (though it may require working around absence of `View` module).

**Comment by fmassa** [comment]
Closing this as it's been a while, this change would be BC-breaking for a lot of users and subclassing ResNet is the approach we currently recommend.
