### ISSUE TITLE
command line to train FCN and DeepLab

### ISSUE THREAD

**Issue by a-maci** [pytorch/vision#1443]
What are the command lines to train the segmentation (`FCN` and `DeepLabV3`) networks to accuracy mentioned in torchvision website (63.7 and 67.4 IoU).

**Comment by a-maci** [comment]
Also, when running the training script with default parameters, I get this error:
```
model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)
AttributeError: type object 'SyncBatchNorm' has no attribute 'convert_sync_batchnorm'
```

**Comment by fmassa** [comment]
Hi,

Sorry for the delay in replying.

Here are the commands I used
```
python -m torch.distributed.launch --nproc_per_node=8 --use_env train.py --lr 0.02 --dataset coco -b 4 --model fcn_resnet101 --aux-loss
```
for `fcn_resnet101` and
```
python -m torch.distributed.launch --nproc_per_node=8 --use_env train.py --lr 0.02 --dataset coco -b 4 --model deeplabv3_resnet101 --aux-loss
```
for `deeplabv3_resnet101`.

About your error, it looks like you are not using a recent enough version of PyTorch? What's your PyTorch version? It should be at least 1.2.

**Comment by isalirezag** [comment]
@a-maci can you know with what code you're going to use that command line? which dataset? where is the file for train.py?

**Comment by a-maci** [comment]
Coco dataset with train.py in references/segmentation folder.

**Comment by fmassa** [comment]
Thanks for raising this up again @isalirezag , I'm updating the README in https://github.com/pytorch/vision/pull/1864 with the commands for training the model
