### ISSUE TITLE
Question and help ??

### ISSUE THREAD

**Issue by daydayfun** [pytorch/vision#1445]
**Discuss:**
If  want to push Bert models and weights  into a ptytorch repository, which is best,  pytorch/text ??

**Comment by pmeier** [comment]
Since BERT is a model for natural language processing (NLP) tasks you could head over to [`torchtext`](https://github.com/pytorch/text). I'm not familiar with their guidelines for contributing models and weights, so it is best you ask your question there.

**Comment by daydayfun** [comment]
thanks for youe help
