### ISSUE TITLE
torchvision.io.read_video() giving memory error

### ISSUE THREAD

**Issue by anandijain** [pytorch/vision#1446]
I have a video file that is 480 x 640, 20 fps, and 20400 frames. 

I get a memory error trying to read the video using no endpoints.
I was wondering if there was a way of using `io.read_video()` that returns a DataLoader or is able to work without loading everything into tensors at once. 

Ideally, I can load in as much as possible each time I `read_video()`. 
It seems a little cumbersome to have to try to find the point in the video that doesn't throw a memory error, and then iterate over that to get each sections of video that I want.

Code and error:
```
>>> vid = tv.io.read_video(fn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/.local/lib/python3.6/site-packages/torchvision/io/video.py", line 200, in read_video
    vframes = torch.as_tensor(np.stack(vframes))
  File "/home/username/.local/lib/python3.6/site-packages/numpy/core/shape_base.py", line 423, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out)
MemoryError
```

Does anyone else have a solution to this?

Thanks!

**Comment by fmassa** [comment]
@anandijain you are trying to load a big video in memory, and it doesn't fit your CPU memory.

You can try using `VideoClips` to return non-overlapping clips of fixed size https://github.com/pytorch/vision/blob/ed5b2dc3a5e7411d8b40cc7e526e151983e99cf9/torchvision/datasets/video_utils.py#L45-L69 here is an example:
```python
from torchvision.datasets.video_utils import VideoClips
video_clips = VideoClips([video_path], clip_length_in_frames=32, frames_between_clips=32)
```
This is what is used internally in the video datasets to return a Dataset compatible with DataLoader:

https://github.com/pytorch/vision/blob/ed5b2dc3a5e7411d8b40cc7e526e151983e99cf9/torchvision/datasets/kinetics.py#L50-L78

(don't bother about the arguments starting with a `_`, they are private).

So this should be fairly easy to do once you use `VideoClips`. But a note of warning: you'll drop the last frames of the video with this approach, if they are not divisible by 32 (in this example).
