### ISSUE TITLE
AttributeError: 'collections.OrderedDict' object has no attribute 'parameters

### ISSUE THREAD

**Issue by mobassir94** [pytorch/vision#1452]
i was trying to use deeplabv3_resnet50, this model is producing ordereddictionary which is state file and not model that stores weight,so i don't understand how to solve this issue,i saw this stackoverflow post : https://stackoverflow.com/questions/49941426/attributeerror-collections-ordereddict-object-has-no-attribute-eval but it doesn't help much,anyone please help,thanks

**Comment by pmeier** [comment]
Actually, the answer over at StackOverflow explains it fairly well.

> It is not a model file, instead, this is a state file. In a model file, the complete model is stored, whereas in a state file only the parameters are stored. So, your OrderedDict are just values for your model. You will need to create the model and then need to load these values into your model. 

You need to do something like this

```python
from torchvision.models.segmentation import deeplabv3_resnet50

model = deeplabv3_resnet50()
model.load_state_dict(state_dict)
```

where `state_dict` is the `OrderedDict` with the stored weights.

**Comment by fmassa** [comment]
Following @pmeier comment, one more thing is that the output of `deeplabv3_resnet` is an `OrderedDict`, so you can just extract the output that you want
```
from torchvision.models.segmentation import deeplabv3_resnet50

model = deeplabv3_resnet50(pretrained=True)
output = model(input)

print(output['out'])
```
