### ISSUE TITLE
Conda pytorch channel package verison is 0.2.2

### ISSUE THREAD

**Issue by d-colwell** [pytorch/vision#1455]
When running the command 

`conda install torchvision -c pytorch`

on windows 10, python 3.7.3, i get the following notification.

`The following NEW packages will be INSTALLED:
  torchvision        pytorch/noarch::torchvision-0.2.2-py_3`

I previously had version 0.4 installed, but was trying to upgrade to make use of pytorch 1.3

**Comment by soumith** [comment]
can you try `conda install torchvision -c pytorch -c conda-forge`.

@peterjc123 reports that I need to fix the install commands

**Comment by d-colwell** [comment]
That worked. Also managed to finally get pytorch 1.3 updated. Thanks @soumith

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/pytorch.github.io/commit/7491668f14ce6def1e882b091a3c597de92c4bf1

**Comment by d-colwell** [comment]
@soumith this behavior seems to be reasserting itself. Install from pytorch and conda-forge channels are now back at version 0.2.2

**Comment by d-colwell** [comment]
Ignore the above, it was to do with having python version 3.7 installed, which doesnt work with torchvision0.4.1

**Comment by fmassa** [comment]
@d-colwell we will be releasing a new version of torchvision today or tomorrow.
@peterjc123 do we need to fix something for the Windows binaries?

**Comment by peterjc123** [comment]
No, I don't think so.

**Comment by soumith** [comment]
@d-colwell afaik we have torchvision binaries for python 3.7 + Windows. So something else is going on.
