### ISSUE TITLE
Missing 0.4.1 release for provided wheels

### ISSUE THREAD

**Issue by daniel-j-h** [pytorch/vision#1458]
Hey folks I just upgraded my pytorch installation to 1.3 and had a look at torchvision, too.

I can find 0.4.1 releases on

https://download.pytorch.org/whl/cpu/torch_stable.html

e.g. https://download.pytorch.org/whl/cpu/torchvision-0.4.1%2Bcpu-cp36-cp36m-linux_x86_64.whl

but I can neither find a release here on Github releases, nor a proper git tag for v0.4.1.

Could you create a push a v0.4.1 git tag.

Or is there a reason it there are v0.4.1 wheels but not a v0.4.1 release?

**Comment by fmassa** [comment]
@daniel-j-h The 0.4.1 release is a dummy release for torchvision binaries to be compatible with PyTorch 1.3.
It doesn't actually bring any of the new features from torchvision master (except for a single bugfix).

We are planning on cutting a new release of torchvision in the next few weeks.

cc @soumith if we should cut a dummy release on GitHub.

**Comment by fmassa** [comment]
Discussed with @soumith about it, we will be publishing a new torchvision GitHub release

**Comment by sclarkson** [comment]
Any update here? Even just tagging the release without adding release notes would be helpful.

**Comment by fmassa** [comment]
Just created a new release tag in https://github.com/pytorch/vision/releases/tag/v0.4.1
