### ISSUE TITLE
module 'torchvision' has no attribute '__version__' at torchvision 0.4.1

### ISSUE THREAD

**Issue by daisuke834** [pytorch/vision#1459]
Module 'torchvision' has no attribute '__version__' at torchvision 0.4.1
```
>>> import torch
>>> torch.__version__
'1.2.0'
>>> import torchvision
>>> torchvision.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torchvision' has no attribute '__version__'
```

**Comment by pmeier** [comment]
How did you install `torchvision`? Via the [official instructions](https://pytorch.org/get-started/locally/) works fine for me. Also note that `torch == 1.3.0` is the curretn stable version.

**Comment by daisuke834** [comment]
@pmeier 
Thank you for your replying. I installed torchvision via dockerfile including:
```
RUN /miniconda3/bin/pip install \
    torch==1.2.0 \
    torchvision==0.4.1
```
I am using Torch 1.2.0 intentionally due to a compatibility issue of Torch 1.3 to my applications.

**Comment by daisuke834** [comment]
Humm. When I installed torch 1.3.0 and torchvision 0.4.1 in my Macbook without docker, this issue didn't happen as well.
I am not sure which of docker, hardware difference or Torch version (1.2.0 vs 1.3.0) is causing this issue.

**Comment by fmassa** [comment]
@daisuke834 note that the only reason why we have torchvision 0.4.1 is to make it compatible with PyTorch 1.3, so if you want to use PyTorch 1.2, I'd recommend installing torchvision 0.4.0

So I believe you have a version incompatibility problem here.

**Comment by daisuke834** [comment]
@fmassa 
Thank you for your reply.
Okay, I will keep using torchvision 0.4.0 as far as I use PyTorch 1.3.

**Comment by fmassa** [comment]
Ok, I'm closing the issue then, let me know if you have other questions

**Comment by daisuke834** [comment]
@fmassa 
Thank you!

**Comment by Tclz** [comment]
thank you. this method works
