### ISSUE TITLE
Cannot load torchvision pretrained model

### ISSUE THREAD

**Issue by Exlsunshine** [pytorch/vision#1473]
* Error
Got error message `urlopen error 11001` when trying to load torchvision model which hasn't been downloaded before.

* Environment
torch==1.3.0+cpu
torchvision==0.4.1+cpu
Python 3.6.6
Windows 10

* Issue diagnose
I can run the following code successfully, `a.py`:
```
from urllib.request import urlopen
urlopen(https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth)
```
But I cannot execute the following, `test_b.py`:
```
import torchvision
def test_foo():
    torchvision.models.alexnet(pretrained=True)
```
it keeps telling me openurl error 11001, but if I import the `openurl` manually:
```
import torchvision
from urllib.request import urlopen
def test_foo():
    torchvision.models.alexnet(pretrained=True)
```
the code runs successfully everytime.

so I suppose there are import errors in this file `Python\Python36\Lib\site-packages\torch\hub.py`, there are some imports that might be messed up:
```
if sys.version_info[0] == 2:
    from urlparse import urlparse
    from urllib2 import urlopen  # noqa f811
else:
    from urllib.request import urlopen
    from urllib.parse import urlparse  # noqa: F401
```

**Comment by fmassa** [comment]
Thanks for the report!

@Exlsunshine can you try doing something like
```python
model = torch.hub.load('pytorch/vision', 'alexnet', pretrained=True)
```
and report back if it works as expected? You might need to delete the downloaded file.

This seems weird, @ailzhang it looks like there might be something unexpected happening with hub download function.

**Comment by ailzhang** [comment]
@fmassa the command works for me on pytorch/torchvision master on a linux machine. I don't have a windows machine now so we'll wait for @Exlsunshine's reply to see whether that works. 
I don't recall any changes with download function recently except we make it a public API.

**Comment by Exlsunshine** [comment]
> Thanks for the report!
> 
> @Exlsunshine can you try doing something like
> 
> ```python
> model = torch.hub.load('pytorch/vision', 'alexnet', pretrained=True)
> ```
> 
> and report back if it works as expected? You might need to delete the downloaded file.
> 
> This seems weird, @ailzhang it looks like there might be something unexpected happening with hub download function.

it seems find, I got the following output:
```
>>> import torch
>>> model = torch.hub.load('pytorch/vision', 'alexnet', pretrained=True)
Downloading: "https://github.com/pytorch/vision/archive/master.zip" to C:\Users\guyan/.cache\torch\hub\master.zip
>>>  
```

**Comment by fmassa** [comment]
@Exlsunshine if using `torch.hub.load` worked for you, I'm puzzled, because it uses the same underlying download function as torchvision. Not sure where the issue might be :-/

**Comment by Exlsunshine** [comment]
> @Exlsunshine if using `torch.hub.load` worked for you, I'm puzzled, because it uses the same underlying download function as torchvision. Not sure where the issue might be :-/

Actually it's even more stranger, the code is not always failed to execute, sometimes it works, and sometimes not:
```
import torchvision
def test_foo():
    torchvision.models.alexnet(pretrained=True)
```

**Comment by fmassa** [comment]
@Exlsunshine I'm not sure how to debug this further. Maybe it was a connection issue?

**Comment by Exlsunshine** [comment]
> @Exlsunshine I'm not sure how to debug this further. Maybe it was a connection issue?

Maybe, I am in a company network. But anyway, I find a workaround by adding `from urllib.request import urlopen` manually.

**Comment by fmassa** [comment]
Ok. Given that we can't reproduce the problem and there is a workaround solution, I'll consider that there is no follow-up required on our side.
If you manage to nail down the problem a bit more, please let us know

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
