### ISSUE TITLE
Use your own proposal method for object detection?

### ISSUE THREAD

**Issue by manoja328** [pytorch/vision#1477]
Hi all, 

Is there an easy way to use your own proposal methods like **egeboxes or selective search for Object Detection.** If  it can be easily plugged in the whole object detection pipeline that would be awesome. Thanks. @fmassa

**Comment by fmassa** [comment]
Hi,

You'll need to write your own version of the `RPN` and replace `model.rpn` with it.
Here is a quick example on how you could do it (warning: untested):
```python
class MyProposals(nn.Module):
    def forward(self, images, features, targets=None):
        # compute the proposals
        proposals = my_proposal_generator(images)
        losses = {}
        return proposals, losses

model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model.rpn = MyProposals()
```

**Comment by manoja328** [comment]
Thanks. BTW, I  basically did the same thing just before you replied.

**Comment by manoja328** [comment]
Hi. Thanks for taking time to write the demo code. I have a related question. I kept everything else same and only change the RPN and use the official object detection tutorial ( I  verified the official version on the  code gave around 65% mAP). I used edgeboxes to get the proposals as follows. But I am not getting even comparable mAP. Mine is around 3-4 percent  for VOC 2007.  Do you have any idea where things could have gone wrong / which area should I be debugging? Thanks.
```class FakeRegionProposalNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        with open("datasets/edboxes_voc07_2000_new.pkl","rb") as f:
            self.edgeboxes = pickle.load(f)


    def forward(self, images, features, targets=None):
        
        if self.training and targets is None:
            raise ValueError("In training mode, targets should be passed")

        num_images = len(images.tensors)
        device = images.tensors.device     
              
        proposals = []
        for idx in range(num_images):
            image_id = '{0:06d}'.format(targets[idx]['image_id'].item())
            box = self.edgeboxes[image_id]
            box = torch.Tensor(box).float().to(device)
            proposals.append(box)

        boxes = proposals
        losses = {}
        return boxes, losses````

**Comment by fmassa** [comment]
Maybe you might need to perform some fine-tuning before, because the offsets from fast r-cnn expect proposals from the RPN, which have different distribution than the proposals from edge box?

**Comment by manoja328** [comment]
I still dont understand what you are trying to say here.
```
        if isinstance(features, torch.Tensor):
            features = OrderedDict([(0, features)])
        proposals, proposal_losses = self.rpn(images, features, targets)
        detections, detector_losses = self.roi_heads(features, proposals, images.image_sizes, targets)
        detections = self.transform.postprocess(detections, images.image_sizes, original_image_sizes)
```
Should it not just work if i replace the line 3 and use boxes from edgeboxes?

**Comment by manoja328** [comment]
I think I know why the model was not working. Its because of the scaling. our edgeboxes have co-ordinates from original images but  before line 3 internally each images are resscaled. So now the features position and box co-ordinates do not match. I suppose if i scale boxes accordingly then it should work just fine.

**Comment by fmassa** [comment]
Yes, the boxes should be in the same format as what we consider in the RPN

**Comment by gorjanradevski** [comment]
@manoja328 did you figure out how to the scale the bounding boxes from your custom RPN, before feeding them to the `RoIHeads` module?

**Comment by manoja328** [comment]
Ya i did. You can find the code in my repo.

**Comment by manoja328** [comment]
Here is the link:
https://github.com/manoja328/voc_detection/blob/master/train.py

**Comment by gorjanradevski** [comment]
Thanks for the help, I appreciate it!
