### ISSUE TITLE
Changing all the raw asserts to self.assert in tests

### ISSUE THREAD

**Issue by surgan12** [pytorch/vision#1483]
As pointed out by @fmassa here in #1465. We could switch the existing asserts to the self.assert version of it.

This could be a simple first issue for people to start with.

**Comment by fmassa** [comment]
I would recommend sending small-sized PRs, changing a single file / a few hundred lines at a time, to make reviewing easier.

**Comment by ekagra-ranjan** [comment]
@PyExtreme this could also be a good starting point for you :)

**Comment by PyExtreme** [comment]
Hi @ekagra-ranjan , would love to take it. Also, I have started to work on Adding Scriptable Transforms issue mentioned here at #1375 . Specifically, I am working on Grayscale Part and hopeful to complete by this week(Parallely understanding the codebase as well).

I will start on working it as soon as I finish the above mentioned task.

**Comment by PyExtreme** [comment]
Hi @ekagra-ranjan , this issue has already been picked. Thanks for letting me about it. I have started working on #1375 and that also looks very interesting.

Thank you

**Comment by frgfm** [comment]
The last PRs should cover all the remaining bare `assert` in the tests!

**Comment by fmassa** [comment]
Fixed by @frgfm , thanks a lot!
