### ISSUE TITLE
Conda installer should enforce Pillow 4.0.0.

### ISSUE THREAD

**Issue by benlundell** [pytorch/vision#151]
Installing PyTorch and torchvision via conda forces a downgrade from Python 3.6.1 to Python 3.6.0. But using Pillow 4.1.0 with Python 3.6.0 causes an error, as [Pillow 4.1.0 was built with Python 3.6.1](https://github.com/python-pillow/Pillow/issues/2479#issuecomment-292252147). The offending [bug is in Python](https://bugs.python.org/issue29943), not PyTorch, torchvision, or Pillow. However, the conda installer could be updated to require Pillow 4.0.0 if it requires Python 3.6.0.

**Comment by soumith** [comment]
i see. The offending bug is indeed in python (which is why I had to require python 3.6.0 and rebuild my binaries.

The next pytorch release this week, I'll make it explicitly require 3.6.1

**Comment by hugovk** [comment]
By the way, there's a new Pillow 4.1.1 release due out soon that works around the Python 3.6.0/1 bug, and should be installable on both. 

Keep an eye on: https://github.com/python-pillow/Pillow/issues/2492

**Comment by hugovk** [comment]
Pillow 4.1.1 is now out https://github.com/python-pillow/Pillow/issues/2492 with a fix https://github.com/python-pillow/Pillow/pull/2493 for https://github.com/python-pillow/Pillow/issues/2479.

**Comment by benlundell** [comment]
@hugovk thanks for keeping tabs on this. @soumith has the release happened? If so, then I'll test and close. If not, it sounds like another option would be to require Pillow 4.1.1.

**Comment by soumith** [comment]
the release has happened yesterday for pytorch. i haven't cut a new release for torchvision itself, I can enforce pillow >= 4.1.1
