### ISSUE TITLE
Simplify / improve test_ops

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#1528]
[`test_ops.py`](https://github.com/pytorch/vision/blob/master/test/test_ops.py) implements tests for the C++ operators in torchvision.
Given that `torchvision.ops` contain dedicated CPU / CUDA implementations, they need to test for correctness on both CPU and GPU, comparing that the outputs are the same. Plus, they also implement backward computation for most ops (except NMS, which is fine as is), which means that we also need to test the gradients.

In its current form, most tests in `test_ops.py` have a lot of duplicate code between each test, with generally just a few lines changing between the tests. We should see if there are things we can factorize to reduce code duplication and improve maintanability.
We should also stop hard-coding values for the gradients / outputs, and we should instead rely on `gradcheck` to perform this checking.
Plus, TorchScript support is now handled as an extra check for each op https://github.com/pytorch/vision/blob/f612182c1530eda53d65d6db92e3150e650c1ec1/test/test_ops.py#L191-L195 but more consistency could be better.

Ideally, we would have a simpler set of tests, which still has the same coverage for contiguous / non-contiguous / CPU / CUDA / forward / backward, which has less redundancy.
How to approach this? We could have a base test class that defines all we want to test, and each operator test inherits from it.

cc @pedrofreire for visibility

**Comment by pedrofreire** [comment]
I'd be happy to have a look on this :)

**Comment by fmassa** [comment]
@pedrofreire go for it!

**Comment by fmassa** [comment]
Fixed via https://github.com/pytorch/vision/pull/1551
