### ISSUE TITLE
The output of features is 512*7*7,why we still need AdaptiveAvgPool2d here to make the output size 7*7 output diamension 

### ISSUE THREAD

**Issue by shenlinyao** [pytorch/vision#1534]
https://github.com/pytorch/vision/blob/13b35ffaa5167f3713ea7a53c43395d90b3a7cbc/torchvision/models/vgg.py#L44

**Comment by fmassa** [comment]
Because some times you might want to pass images of different sizes, but still want the final classifier to work.
See https://github.com/pytorch/vision/pull/643 and linked issues for more context
