### ISSUE TITLE
[Request] ResNet v2 and ResNext models and pretrained weights?

### ISSUE THREAD

**Issue by wangg12** [pytorch/vision#154]
Is there any plan to provide these models with pretrained weights?

**Comment by lucasb-eyer** [comment]
If it helps, I have implemented the basic blocks for both [in my toolbox](https://github.com/lucasb-eyer/lbtoolbox/blob/master/lbtoolbox/pytorch.py#L61) and you can use them as-is for building networks. I don't have the capacity and to train them on imagenet though...

**Comment by Cadene** [comment]
I build a pytorch-vision like library for pretrained convents.
https://github.com/Cadene/pretrained-models.pytorch

You can find a sequential version of ResNeXt101 models with pretrained weights ported from torch7.

**Comment by fmassa** [comment]
We've added ResNeXt to torchvision, but ResNetv2 didn't really caught up with the community so we won't be adding it
