### ISSUE TITLE
DeprecationWarning in torchvision/datasets/lsun.py with python 3.8

### ISSUE THREAD

**Issue by ThomAub** [pytorch/vision#1541]
With the new release of python 3.8 some new DeprecationWarning are poping. `DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working`

Is it resonable to submit a PR to fix it ?

**Comment by fmassa** [comment]
I believe this has been fixed in latest torchvision by https://github.com/pytorch/vision/pull/1417

Can you double-check?

**Comment by ThomAub** [comment]
Yes it is fixed with this PR :) 
Sorry for the inconvenience.

**Comment by fmassa** [comment]
No worries, thanks for opening the issue!

**Comment by GeJulia** [comment]
Since this week I'm facing a similar issue when using torchvision/transforms. `DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working` Is there already a PR for fixing?

**Comment by fmassa** [comment]
@GeJulia what version of torchvision are you using?

**Comment by GeJulia** [comment]
I'm using torchvision 0.2.1 with python 3.7.9.
