### ISSUE TITLE
Stuck when training video model with multi-node training

### ISSUE THREAD

**Issue by jc-hou** [pytorch/vision#1550]
I'm trying to train the video model in https://github.com/pytorch/vision/blob/master/references/video_classification/train.py
with multi-node training (2 nodes, 4 gpu each).
I got socket timeout error on node 1 (node 0 is the master node) so I added three flag msg in the code to see where I got stuck:
(in the train_one_epoch method)
```python
    for video, target in metric_logger.log_every(data_loader, print_freq, header):
        start_time = time.time()
        print("flag1")
        video, target = video.to(device), target.to(device)
        print("flag2")
        output = model(video)
        print("flag3")
        loss = criterion(output, target)
```
The output log on node 0 is here
[issue_output_node0.txt](https://github.com/pytorch/vision/files/3800683/issue_output_node0.txt)
 and log on node 1 is here
[issue_output_node1.txt](https://github.com/pytorch/vision/files/3800684/issue_output_node1.txt)
. (print all rank + NCCL_DEBUG=INFO).
In the end of the log we see the 4 processes on node 0 got stuck at flag1, and the 4 processes on node 1 got stuck at flag2. Then node 1 got 'RuntimeError: Socket Timeout' and I quit the code.

If I set non_blocking=True:
```python
    for video, target in metric_logger.log_every(data_loader, print_freq, header):
        start_time = time.time()
        print("flag1")
        video, target = video.to(device, non_blocking=True), target.to(device, non_blocking=True)
        print("flag2")
        output = model(video)
        print("flag3")
        loss = criterion(output, target)
```
All the 8 processes got stuck at flag2, then socket timeout error occur again on node 1.

So the problems is probably why the program got stuck at line ```output = model(video)``` .
The original code runs successfully on single node (4 gpu).

environments:
torch version:  1.3.0 (conda)
torchvision version:  0.5.0a0+9cdc814 (from source)
NCCL version 2.4.8+cuda9.2

Thanks!

**Comment by fmassa** [comment]
Hi @jc-hou 

How are you running the training script for each one of the machines? I suspect that it might be a problem with the configuration of the distributed setup on the different machines.

**Comment by jc-hou** [comment]
Hi @fmassa  thank you for the comment. 
On node 0, I run it with:
```
python -m torch.distributed.launch --use_env --nproc_per_node=4 --nnodes=2 --node_rank=0 \
--master_addr="192.168.9.79" --master_port=1234 train.py -b 24 --clip-len 16 \
--clips-per-video 5 --epochs 15 --output-dir ../checkpoint/multi_node \
--data-path /data/stars/user/jhou/Test/pytorch_test/data_loader/fake_data/10_sample_full_class/kinetics400/ \
--cache-dataset --sync-bn --pretrained --world-size 8 --model r3d_18
```
On node 1:
```
python -m torch.distributed.launch --use_env --nproc_per_node=4 --nnodes=2 --node_rank=1 \
--master_addr="192.168.9.79" --master_port=1234 train.py -b 24 --clip-len 16 \
--clips-per-video 5 --epochs 15 --output-dir ../checkpoint/multi_node \
--data-path /data/stars/user/jhou/Test/pytorch_test/data_loader/fake_data/10_sample_full_class/kinetics400/ \
--cache-dataset --sync-bn --pretrained GTX 1080 Ti--world-size 8 --model r3d_18
```
