### ISSUE TITLE
Can KeypointRCNN also detect objects that do not need to be predicted with keypoints?

### ISSUE THREAD

**Issue by anuar12** [pytorch/vision#1557]
As far as I understand keypoints would be computed for all the box classes (apart from background) in Keypoint-RCNN. I need to do object detection and keypoint prediction at the same time, however keypoints should only be predicted for one class. Does current version support this? 

If not, I would need to modify some of the code in FasterRCNN and KeypointRCNN as far as I understand but in principle it is possible, right?

**Comment by JasperShian** [comment]
Your keypoint rcnn just inferences predicted boxed rather than keypoints? if true, why don't you use faster rcnn instead of keypoint rcnn?

**Comment by fmassa** [comment]
Hi,

`KeypointRCNN` only has the person class. Thus, it only computes keypoints for the person class as well.

If you want to detect multiple objects and keypoints for a single object, then you'll need to either pass two detectors, or modify keypoint rcnn to handle this situation.
