### ISSUE TITLE
No longer able to build in Docker

### ISSUE THREAD

**Issue by iarspider** [pytorch/vision#1566]
Hi!

We were able to build torchvision 0.3.0 w/cuda in docker container, which doesn't have access to NVidia GPU. However when building 0.4.1 we get the following error:
```
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

Is there a way to build torchvision without "NVidia driver"?

**Comment by iarspider** [comment]
This is how we build Torch:
```
export USE_NINJA=1
export USE_MKLDNN=0
export CUDA_HOME=/path/to/cuda
python setup.py install --prefix=/install/torch
```

This is how we build Torchvision:
```
export LD_LIBRARY_PATH=/install/torch/lib/pythonX.Y/site-packages/torch/lib
export FORCE_CUDA=1
export CUDA_HOME=/path/to/cuda
python setup.py install --prefix=/install/torchvision
```

**Comment by fmassa** [comment]
Hi,

I don't have much experience with docker, and I'm not what has changed that could break things for you compared to 0.3.0.

Can you try building torchvision from master branch?

**Comment by iarspider** [comment]
Hi,

same problem with "master" (commit 681c6c1) version of torchvision.

**Comment by ahirner** [comment]
Solved by supplying `TORCH_CUDA_ARCH_LIST`, otherwise `cpp_extension.py` tries to dynamically determine ARCH. See [trace](https://github.com/pytorch/vision/files/4023917/tv_trace.txt) if `TORCH_CUDA_ARCH_LIST` is not supplied for 0.4.2 and pytorch 1.3.1.

You may want to check out our custom builds [here](https://github.com/MoonVision/moonbox-docker).

**Comment by fmassa** [comment]
@ahirner can you send a PR fixing the docker in torchvision?

Also, cc @seemethere for awareness

**Comment by iarspider** [comment]
Worked for me, thanks @ahirner !

**Comment by ahirner** [comment]
I think the error only pertains custom builds not current wheels? We don't use them either so it would be good to repro the case with official builds and open a new issue if it is @fmassa
