### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by zhu2014yi** [pytorch/vision#1588]
Anybody know how to train a pretrain model(etc mobile net v2 in pysot ) ?

**Comment by fmassa** [comment]
@zhu2014yi commands for training a mobilenet v2 in PyTorch on ImageNet can be found in https://github.com/pytorch/vision/tree/master/references/classification#mobilenetv2

This is the exact same code that we used to obtain the pre-trained weights for MobileNetV2 that are available in the modelzoo

**Comment by zhu2014yi** [comment]
> @zhu2014yi commands for training a mobilenet v2 in PyTorch on ImageNet can be found in https://github.com/pytorch/vision/tree/master/references/classification#mobilenetv2
> 
> This is the exact same code that we used to obtain the pre-trained weights for MobileNetV2 that are available in the modelzoo

thanks
