### ISSUE TITLE
EMNIST dataset download links both invalid

### ISSUE THREAD

**Issue by AghiadHaloul** [pytorch/vision#1589]
Using 
`EMNIST_train = torchvision.datasets.EMNIST(root='./data/datasets/EMNIST',
            split='balanced',
            train=True,
            download=True)`

returns the following errors:
>     Downloading https://cloudstor.aarnet.edu.au/plus/index.php/s/54h3OuGJhFLwAlQ/download to .\data\datasets\EMNIST\EMNIST\raw\emnist.zip
>     Failed download. Trying https -> http instead. Downloading http://cloudstor.aarnet.edu.au/plus/index.php/s/54h3OuGJhFLwAlQ/download to .\data\datasets\EMNIST\EMNIST\raw\emnist.zip
>     .....
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
>     urllib.error.HTTPError: HTTP Error 503: Service Unavailable

The data sources need updating.  Alternative links [(here)](https://discuss.pytorch.org/t/emnist-in-torchvision-datasets-returning-http-error-503-service-unavailable/61177/2?u=aghiadhaloul) were provided on PyTorch forum.

**Comment by surgan12** [comment]
The link has been fixed
Please refer [https://github.com/pytorch/vision/issues/1296#issuecomment-553536079](this)

**Comment by fmassa** [comment]
Closing following @surgan12 comment
