### ISSUE TITLE
How to feed negative samples during Faster R-CNN training

### ISSUE THREAD

**Issue by kkirtac** [pytorch/vision#1598]
Hi all,
I have lots of non-annotated images in my training set, where there is no object of interest but there are couple other objects that should be interpreted as part of background. Is there any way I can provide background (negative) samples explicitly in my dataloder? 
I tried to set a single fake bounding box with label zero for those non-annotated images, and set my num_classes as 3, i.e., I have 2 objects and background, and then performed transfer learning,

`model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True,
                                                                 pretrained_backbone=False)`
`in_features = model.roi_heads.box_predictor.cls_score.in_features`
`model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)`

 But I received a crash at `/torchvision/models/detection/roi_heads.py", line 34, in fastrcnn_loss`
`sampled_pos_inds_subset = torch.nonzero(labels > 0).squeeze(1)`

I think this is happening because I have fed some images with only label zero, i.e., with no positive bbox.
Is there any workaround for that purpose?

**Comment by fmassa** [comment]
We currently do not support feeding images without annotations during training.
A workaround for that is to filter beforehand all the training images that do not have annotations, like we do in
https://github.com/pytorch/vision/blob/537f0df79c464983dc1f32b8697dbc42d3f4872b/references/detection/coco_utils.py#L106-L143

**Comment by rronan** [comment]
Hi,
Do you plan to support these negative samples during training? By filtering the images beforehand, I get  a lot of false positive detections during inference, when the input image in empty.
Without this feature I need a second model to classify empty images, sharing the same backbone (or you think of another workaround?).
Thanks

**Comment by ferna11i** [comment]
Hi @fmassa ,

Thanks for pointing out the code which we can use to filter the images that do not contain the object of interest.
Out of curiosity does this mean, the images in the test/validation sets that have only negative samples i.e. no objects will also be elimiated from the test/validation set?

**Comment by iantimmis** [comment]
+1 Would love a solution for this as well.

**Comment by fmassa** [comment]
This will be fixed once https://github.com/pytorch/vision/pull/1911 gets merged

**Comment by FiReTiTi** [comment]
Hi,
I also have the same issue. I've filtered the empty (no object to detect) images, but it's highly problematic as it create an over-segmentation.
Indeed, I have tricky images containing object like patterns that I cannot use for training, and as a result these false object are all detected during testing.
Is there any work-around while waiting for the fix?

**Comment by fmassa** [comment]
@FiReTiTi the fix (for Faster R-CNN for now, not for Mask R-CNN, Keypoint R-CNN) has been merged in master

**Comment by FiReTiTi** [comment]
@fmassa good to know, thanks.

**Comment by fmassa** [comment]
This is fixed now for Mask R-CNN and Keypoint R-CNN, thanks to https://github.com/pytorch/vision/pull/1911 and https://github.com/pytorch/vision/pull/2069, and will be present in the next release of torchvision next week

**Comment by FiReTiTi** [comment]
Thank you very much!

**Comment by ferna11i** [comment]
Thank you!
Great work!

**Comment by FiReTiTi** [comment]
@fmassa: I haven't seen a new torchvision release. Pip still propose version 0.5.0

**Comment by fmassa** [comment]
@FiReTiTi the release will be today

**Comment by amirhesamyazdi** [comment]
Thank you all for support. Can anyone unequivocally confirm the following?

1- Can we explicitly empty images (no object) to Faster R-CNN family and DETR by simply adding the empty images in our coco format json file (so we have many extra entries in images) but then NO entry in annotations. Meaning there is nothing added with those image_id s. 

2- I was thinking of adding an empty annotation covering area of 0 or a full annotation covering everything and label it as empty class explicitly but if the former can work, it would be easier and much better. 

Can anyone confirm for sure that if I do it the first way, the model will in fact incorporate those images into loss calculation? I know it adds more background imbalance, but sometimes you gotta do what you gotta do to reduce false alarms. 

Appreciate your help.

**Comment by nursenaaksu** [comment]
hi 

> Thank you all for support. Can anyone unequivocally confirm the following?
> 
> 1- Can we explicitly include empty images (no object) in Faster R-CNN family and DETR by simply adding the empty images in our coco format json file (so we have many extra entries in images) but then NO entry in annotations. Meaning there is nothing added under annotations[] with those image_id s.
> 
> 2- I was thinking of adding an empty annotation covering area of 0 or a full annotation covering everything and label it as empty class explicitly but if the former can work, it would be easier and much better.
> 
> Can anyone confirm for sure that if I do it the first way, the model will in fact incorporate those images into loss calculation? I know it adds more background imbalance, but sometimes you gotta do what you gotta do to reduce false alarms.
> 
> Appreciate your help.

hi ı have same issue, can anyone have an idea for this situation

**Comment by amirhesamyazdi** [comment]
> This is fixed now for Mask R-CNN and Keypoint R-CNN, thanks to #1911 and #2069, and will be present in the next release of torchvision next week

Dear @fmassa , Could you please verify that this also fixed for DETR? Can we add negative samples with no annotation in DETR? I have asked this question in detail in the bottom of this thread and someone else seconded my question so We really appreciate your reply and as always. Thank you.

**Comment by tugcekeskin** [comment]
> > This is fixed now for Mask R-CNN and Keypoint R-CNN, thanks to #1911 and #2069, and will be present in the next release of torchvision next week
> 
> Dear @fmassa , Could you please verify that this also fixed for DETR? Can we add negative samples with no annotation in DETR? I have asked this question in detail in the bottom of this thread and someone else seconded my question so We really appreciate your reply and as always. Thank you.

We are definitely at the same point. I am trying to do Fracture/Non-fracture bone detection in my project. There are 4 different classes for Fracture case and they have annotations. For Non-fracture case, there is no annonation and consists of "jpg" files. I don't know how to include Non-fracture case in dataset. Any ideas?

**Comment by tugcekeskin** [comment]
> > This is fixed now for Mask R-CNN and Keypoint R-CNN, thanks to #1911 and #2069, and will be present in the next release of torchvision next week
> 
> Dear @fmassa , Could you please verify that this also fixed for DETR? Can we add negative samples with no annotation in DETR? I have asked this question in detail in the bottom of this thread and someone else seconded my question so We really appreciate your reply and as always. Thank you.

We are definitely at the same point. I am trying to do Fracture/Non-fracture bone detection in my project. There are 4 different classes for Fracture case and they have annotations. For Non-fracture case, there is no annonation and consists of "jpg" files. I don't know how to include Non-fracture case in dataset. Any ideas?

**Comment by tugcekeskin** [comment]
> > This is fixed now for Mask R-CNN and Keypoint R-CNN, thanks to #1911 and #2069, and will be present in the next release of torchvision next week
> 
> Dear @fmassa , Could you please verify that this also fixed for DETR? Can we add negative samples with no annotation in DETR? I have asked this question in detail in the bottom of this thread and someone else seconded my question so We really appreciate your reply and as always. Thank you.

We are definitely at the same point. I am trying to do Fracture/Non-fracture bone detection in my project. There are 4 different classes for Fracture case and they have annotations. For Non-fracture case, there is no annonation and consists of "jpg" files. I don't know how to include Non-fracture case in my dataset. Any ideas?

**Comment by carsumptive** [comment]
Hi, I'm working through the same issue more or less. I think that I'm just uncertain if the codebase was updated since the PR mentioned earlier -- running FasterRCNN gives me an error thrown by GeneralizedRCNN calling my [0,0,0,0] box "degenerate" because it does not have positive dimensions. Does anyone know the workaround for this that the PR was proposing?

**Comment by Kosta404** [comment]
> Hi, I'm working through the same issue more or less. I think that I'm just uncertain if the codebase was updated since the PR mentioned earlier -- running FasterRCNN gives me an error thrown by GeneralizedRCNN calling my [0,0,0,0] box "degenerate" because it does not have positive dimensions. Does anyone know the workaround for this that the PR was proposing?
> 
> PR #1911 does not fix this issue, as far as I can tell, and it seems that PR #2240 was implemented in part because of that. It's a bit weird to me though that some people seem to be saying that this feature works. Thoughts?

Hi, @carsumptive 
Did you manage to fix the problem somehow?

**Comment by Kosta404** [comment]
Hello, @fmassa
If I provide [0.0, 0.0, 0.0, 0.0] boxes I get the error `ValueError: All bounding boxes should have positive height and width. Found invalid box [0.0, 0.0, 0.0, 0.0] for target at index 1.` 
So the problem doesn't seem to be solved. Would you kindly re-open an issue again?

**Comment by FiReTiTi** [comment]
@Kosta404 This issue was open to be able to submit empty images, not bounding boxes of null dimensions.
Can you filter out such boxes?

**Comment by Kosta404** [comment]
> @Kosta404 This issue was open to be able to submit empty images, not bounding boxes of null dimensions. Can you filter out such boxes?

I don't need to filter them, I create them on purpose on empty images, to create "Negative samples".

**Comment by amirhesamyazdi** [comment]
There are both a **proper** (section 3.4.1) and a **hacky** (sections 3.4.2) solution for this proposed in this paper: https://www.mdpi.com/1779590

 To feed negative samples during Faster R-CNN training if the version does not support  samples with no objects.

**Comment by kb1ooo** [comment]
Just use yolo where negative samples can be incorporated easily
