### ISSUE TITLE
ResNet identity (line 55) mustn't be mutable

### ISSUE THREAD

**Issue by Abolfazl-Mehranian** [pytorch/vision#1599]
The identity variable in line 55 is mutable
    def forward(self, x):
        identity = x

It must be immutable as follows:

    def forward(self, x):
        identity = 1*x

**Comment by pmeier** [comment]
Why do you think so? If I'm not mistaken no inplace operation is performed on `identity` and thus `x` is never changed inplace:

https://github.com/pytorch/vision/blob/8aec85deb447d415abc0788d8dc301a727cc69fb/torchvision/models/resnet.py#L57-L73

Additionally, if we go through with your proposal, it would be clearer to do

```python
identity = x.clone()
```

than a multiplication by one.

**Comment by Abolfazl-Mehranian** [comment]
Oh, my mistake, you are right. x is never changed. it was another implementation, with similar residual conenction that x was getting changed hence identitiy.

**Comment by fmassa** [comment]
Thanks for helping out @pmeier !
