### ISSUE TITLE
License for pretrained weights?

### ISSUE THREAD

**Issue by jcjohnson** [pytorch/vision#160]
Do you have any particular license under which the pretrained model files are released?

We want to modify (i.e. port to TensorFlow) and redistribute (i.e. use for [CS 231N](http://cs231n.stanford.edu/)) the weights files from this repo; is this permissible?

**Comment by soumith** [comment]
pick a license and amend the readme files. fine by me.

**Comment by ezavarygin** [comment]
I am also interested to know under what license the weights were released. I ported the VGG model weights from PyTorch to Keras and now wonder which license I should use.
Is it just BSD as for the ```torchvision``` package?

**Comment by fmassa** [comment]
@ezavarygin probably yes
