### ISSUE TITLE
DeprecationWarning of imp

### ISSUE THREAD

**Issue by moskomule** [pytorch/vision#1607]
Hi, I got the following DeprecationWarning. [`imp`](https://docs.python.org/3/library/imp.html) is now deprecated and is recommended to move to `importlib` instead.

```
 /home/xxx/.miniconda/lib/python3.7/site-packages/torchvision/io/video.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
```

**Comment by fmassa** [comment]
Thanks for opening the issue!

We can change it to `importlib`, but probably after Jan 2020, when we will be dropping support for Python 2.

PRs welcome!

**Comment by moskomule** [comment]
I understand. Thanks.

**Comment by fmassa** [comment]
Let's keep the issue open, as this is something that we will be doing anyway very soon
