### ISSUE TITLE
Question about converting custom dataset to coco api

### ISSUE THREAD

**Issue by kangkang59812** [pytorch/vision#1617]
https://github.com/pytorch/vision/blob/a44d55d87ba3628ac79292fdcaead7fb98fc130b/references/detection/coco_utils.py#L163

If the box is [3,10,6,20](xyxy format),the converted box should be [3,10,4,11]. I think this code should be added 1. Because there are 4 pixels between [3,6] and 11 pixels between [10,20]. It actually computes the pixels in grid.
May be the original computation of the area need to do this as well. Such as this tutorial, https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html
`area = (boxes[:, 3] - boxes[:, 1]) * (boxes[:, 2] - boxes[:, 0])`

**Comment by fmassa** [comment]
Hi,

This has been discussed in https://github.com/pytorch/vision/pull/826#issuecomment-481714113 , and the addition of `+1` was removed from torchvision, and we consider box coordinates in terms of continuous coordinates, in which case the `+1` is not necessary.

Let me know if you have further questions
