### ISSUE TITLE
Addition of WIDER Face Dataset to Datasets

### ISSUE THREAD

**Issue by gtamba** [pytorch/vision#1627]
I was wondering if there were any plans on adding the WIDER Face dataset (since it's certainly a better standard than CelebA) or any interest in having one contributed. The privatization of ImageNet URLs definitely makes the future of fetching data via Dataset a bit murky but it is definitely a handy bit of code to have when you aren't working on the same machine/instance. 

The images are hosted publicly on Google Drive and do not require any user agreement before use from what I can see. 

cc @pmeier

**Comment by jgbradley1** [comment]
I second this request. Whether or not a dataset can be downloaded automatically, there is still a lot of value to standardizing access to the dataset. People can still pass in a `root` path directory to a local copy.

**Comment by jgbradley1** [comment]
I have written and tested a WIDERFace Dataset [here](https://github.com/jgbradley1/vision/blob/add-widerface-dataset/torchvision/datasets/widerface.py). Nearly ready to open a PR for review.

**Comment by pmeier** [comment]
Closed in #2883.
