### ISSUE TITLE
load voc dataset fail in windows

### ISSUE THREAD

**Issue by XuVision** [pytorch/vision#1636]
can't find file or directory.
i think it is caused by path join:
offical:
`os.path.join('D:\datasets','VOCdevkit/VOC2012')`
will get 'D:\\datasets\\VOCdevkit/VOC2012'
this one below will be ok:
`os.path.join('D:\datasets','VOCdevkit','VOC2012')`

**Comment by fmassa** [comment]
Oh, good catch!

This should be fixed by #1641
