### ISSUE TITLE
datasets.FashionMNIST function is broken in nightly

### ISSUE THREAD

**Issue by develooper1994** [pytorch/vision#1642]
Hello I am using torchvision==0.5.0.dev20191205
If i use datasets.FashionMNIST downloads but whenever iterates throws an error. FashionMNIST also doesn't responde after rerun the code. I can't see "Files already downloaded and verified".
Note: I have tried CIFAR10 and it works fine.
That is traceback;
TypeError                                 Traceback (most recent call last)
<ipython-input-8-c1d11bf45533> in <module>
      1 # obtain one batch of training images
      2 dataiter = iter(train_loader)
----> 3 images, labels = dataiter.next()
      4 images = images.numpy() # convert images to numpy for display
      5 

~\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py in __next__(self)
    344     def __next__(self):
    345         index = self._next_index()  # may raise StopIteration
--> 346         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    347         if self._pin_memory:
    348             data = _utils.pin_memory.pin_memory(data)

~\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py in fetch(self, possibly_batched_index)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py in <listcomp>(.0)
     42     def fetch(self, possibly_batched_index):
     43         if self.auto_collation:
---> 44             data = [self.dataset[idx] for idx in possibly_batched_index]
     45         else:
     46             data = self.dataset[possibly_batched_index]

~\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py in __getitem__(self, index)
     95 
     96         if self.transform is not None:
---> 97             img = self.transform(img)
     98 
     99         if self.target_transform is not None:

~\Anaconda3\lib\site-packages\torchvision\transforms\transforms.py in __call__(self, img)
     68     def __call__(self, img):
     69         for t in self.transforms:
---> 70             img = t(img)
     71         return img
     72 

~\Anaconda3\lib\site-packages\torchvision\transforms\transforms.py in __call__(self, img)
   1001         angle = self.get_params(self.degrees)
   1002 
-> 1003         return F.rotate(img, angle, self.resample, self.expand, self.center, self.fill)
   1004 
   1005     def __repr__(self):

~\Anaconda3\lib\site-packages\torchvision\transforms\functional.py in rotate(img, angle, resample, expand, center, fill)
    727         fill = tuple([fill] * 3)
    728 
--> 729     return img.rotate(angle, resample, expand, center, fillcolor=fill)
    730 
    731 

~\Anaconda3\lib\site-packages\PIL\Image.py in rotate(self, angle, resample, expand, center, translate, fillcolor)
   2003             w, h = nw, nh
   2004 
-> 2005         return self.transform((w, h), AFFINE, matrix, resample, fillcolor=fillcolor)
   2006 
   2007     def save(self, fp, format=None, **params):

~\Anaconda3\lib\site-packages\PIL\Image.py in transform(self, size, method, data, resample, fill, fillcolor)
   2297             raise ValueError("missing method data")
   2298 
-> 2299         im = new(self.mode, size, fillcolor)
   2300         if method == MESH:
   2301             # list of quads

~\Anaconda3\lib\site-packages\PIL\Image.py in new(mode, size, color)
   2503         im.palette = ImagePalette.ImagePalette()
   2504         color = im.palette.getcolor(color)
-> 2505     return im._new(core.fill(mode, size, color))
   2506 
   2507 

TypeError: function takes exactly 1 argument (3 given)

**Comment by develooper1994** [comment]
I am returning to stable

**Comment by develooper1994** [comment]
Also MNIST throws an error. What is going on?

**Comment by fmassa** [comment]
@develooper1994 this error is thrown from inside Pillow, so I would expect that you might have to update Pillow to a newer version.

Can you tell us the results of `import PIL; print(PIL.__version__)` that you have?

**Comment by develooper1994** [comment]
I am using lastest version of pillow currently.
pillow==6.2.1.
I back to stable.
I know it is not releated to this topic but I should say. PLEASE CHANGE the background of torchvision from pillow to torch. Whenever use mnist with gpu, it is extremly slow. Lots of people struggling with that. Make it fast and simple. I tried Pytorch/example and it is still slow.

**Comment by fmassa** [comment]
> I back to stable

Do you have a snippet that can reproduce this error? I would like to understand where the problem is

>  know it is not releated to this topic but I should say. PLEASE CHANGE the background of torchvision from pillow to torch. Whenever use mnist with gpu, it is extremly slow. Lots of people struggling with that. Make it fast and simple. I tried Pytorch/example and it is still slow.

This is already happening and is in the works, but let's not go off-topic

**Comment by develooper1994** [comment]
Unfortunately I changed the version to stable and I have started the long run.
"This is already happening and is in the works, but let's not go off-topic" -> Thanks. It is good to know.

**Comment by develooper1994** [comment]
I don't know how but it working now. I installed lasted version to debug butnow working. There isn't error. Also it it faster on cpu 16.74s/it i7-5960x
torch.__version__ == '1.4.0.dev20191206'
torchvision.__version__ == '0.5.0.dev20191207'

**Comment by fmassa** [comment]
Thanks for letting us know.
