### ISSUE TITLE
Meta file not found or corrupted. 

### ISSUE THREAD

**Issue by Esaada** [pytorch/vision#1645]
## To Reproduce

```
import torchvision.datasets as datasets
input_transform = None

imagenet = datasets.ImageNet("path2imagenet", split="val", transform=input_transform, target_transform=None, download=False)
```

Gives error:
> Traceback (most recent call last):
  File "test_imagenet.py", line 4, in <module>
    imagenet = datasets.ImageNet("path2imagenet", split="val", transform=input_transform, target_transform=None, download=False)
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/imagenet.py", line 56, in __init__
    wnid_to_classes = self._load_meta_file()[0]
  File "/usr/local/lib/python3.6/dist-packages/torchvision/datasets/imagenet.py", line 108, in _load_meta_file
    "You can use download=True to create it.")
RuntimeError: ('Meta file not found or corrupted.', 'You can use download=True to create it.')

## Expected behavior

 Expected behavior? load ImageNet and not break.

## Environment
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0

## Additional context
I tried download=true, didn't work, but this doesn't matter since I don't want to download the dataset as I already have one.
Thanks.

**Comment by pmeier** [comment]
For a description of what the `meta.bin` file is, see my [comment in #1646]()

To create it in `torchvision==0.4.0` you need to place the devkit archive in the root folder and set `download=True` when instantiating the `ImageNet` dataset. Basically this section of the download code has to be executed:

https://github.com/pytorch/vision/blob/a263704079d9d35db8b0966a65ec628d28998bce/torchvision/datasets/imagenet.py#L69-L80

Of course you can also perform these steps manually to create the meta file.

**Comment by zhangyizhong17** [comment]
The same error occurred in my code.

**Comment by zhangyizhong17** [comment]
The same error occurred in my code. I was trying to use the torchvision to load the imagenet datasets downloaded by myself. The key problem is that the format of the self downloaded datasets do not match the given datasets. We have to make our own meta.bin by ourselves just like the one provided in the package.

**Comment by fmassa** [comment]
We will be soon releasing a new version of torchvision, which will fix this error for you.

Alternatively, you can install torchvision from a nightly release.

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
