### ISSUE TITLE
What is the meta.bin file used by the ImageNet dataset?

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#1646]
[Comment from @kanonjz in #1457](https://github.com/pytorch/vision/pull/1457#issuecomment-562807954)

> I downloaded imagenet myself and used `parse_val_archive` to prepare the folders, but got an error below. What is the `meta.bin`? I didn't find it in the imagenet.
> 
> `The meta file meta.bin is not present in the root directory or is corrupted. " "This file is automatically created by the ImageNet dataset.`

**Comment by pmeier** [comment]
`meta.bin` is a binary file which holds 2 things:

1. A `dict` with a mapping from the WordNet IDs (wnids) to human-readable classes.
2. A list of the `wnid` of each validation image.

The `meta.bin` file is created by executing the `parse_devkit_archive` function:

https://github.com/pytorch/vision/blob/598b61d93357139cec558af6eff38a77ac60cabc/torchvision/datasets/imagenet.py#L105-L113

Note that this requires `scipy` to be installed.

---

@kanonjz To resolve your error you have 2 options:
1. Download the devkit archive and parse it with the function mentioned above to generate the `meta.bin` file.
2. The `parse_val_archive` function only tries to load the `wnids` from the `meta.bin` file if none are given to it. If you have a list, try passing it like this:

```python
parse_val_archive(..., wnids=my_wnid_list)
```

**Comment by kanonjz** [comment]
Thanks!!

**Comment by pmeier** [comment]
@kanonjz Is your problem resolved? If yes, I'm going to close this issue.

**Comment by kanonjz** [comment]
@pmeier Yes!

**Comment by fmassa** [comment]
Thanks @pmeier for helping out with this issue!
