### ISSUE TITLE
a MemoryError and subprocess.CalledProcessError during eval in object-dection

### ISSUE THREAD

**Issue by kangkang59812** [pytorch/vision#1652]
![F52DF77A-83B1-4AEB-A7BD-A35EE2EBFAF0](https://user-images.githubusercontent.com/12228641/70422131-30922980-1aa6-11ea-9865-b31ba097555b.png)

I use the [provided code](https://github.com/pytorch/vision/blob/master/references/detection/train.py) to train my datasets. When I evaluate, the MemoryError and subprocess.CalledProcessError happened.

When I use the below command
`python -m torch.distributed.launch --nproc_per_node=2 --use_env ./train/detection_train.py --test-only`, this error happened.

While this command
` python ./train/detection_train.py --test-only` works well. I think there is something wrong with distributing during eval.

**Comment by fmassa** [comment]
I think you might be running out of CPU memory. When we use two GPUs for evaluating, we also require twice as much CPU memory for some internal things (namely transferring the evaluation results).

Can you check if this is the case?

**Comment by kangkang59812** [comment]
It costs about 27G memory when evaluating using distributing , while 32G is my ability..
