### ISSUE TITLE
Question regarding only bbox

### ISSUE THREAD

**Issue by gaussiangit** [pytorch/vision#1669]
https://github.com/pytorch/vision/blob/bce17fddd4da744e23512b8e224d085818e6d921/references/detection/coco_utils.py#L231
``
What if there are only bbox annotations and no segmentation available at all?!

**Comment by fmassa** [comment]
Just create your own instance of a dataset, which only contains the bounding boxes, and use it instead.

Here is an example on how to change the dataset to your own needs https://github.com/pytorch/vision/issues/1097#issuecomment-508917489
