### ISSUE TITLE
[proposal] Add ability to reorder classes for ImageFolder and DatasetFolder

### ISSUE THREAD

**Issue by Daemonhost** [pytorch/vision#1674]
This ability would be very useful to me. Here's an example:
```python
data1 = ImageFolder(root='root1/', class_to_idx={'dog': 0, 'cat': 1})
data2 = DatasetFolder(root='root2/', loader=loader, class_to_idx={'dog': 0, 'cat': 1})
```
Currently the only way to do this is to rename the corresponding class folders, which isn't always convenient.

I could add a pull request if you think that this is a good feature.

**Comment by fmassa** [comment]
Can't you have a `target_transform` which performs the remapping for you? I don't think that this needs a special argument in the class constructor for that.

**Comment by Daemonhost** [comment]
Yes, and then you could change `class_to_idx` attribute, if it is used later in the code, though then it wouldn't be consistent with class indices in `samples` and `targets` attributes. You could also manually change `samples`, `targets`, and `class_to_idx` attributes, but, I think, having a constructor argument would be better.

**Comment by fmassa** [comment]
The way I see this, if we have a `target_transform` that remaps the indices, we should also use the `target_transform` to get back the `class_to_idx`.
```python
img, tgt = dataset[10]
tgt_name = target_transform.idx_to_class[tgt]
```

One of the reasons why I would rather not have a `class_to_idx` argument in the constructor is that it enforces that you know beforehand what are the classes in your dataset, which for now is discovered automatically by the folders in your path.

**Comment by Daemonhost** [comment]
I meant that this should be an addition, not a replacement for the current behavior, i.e. it should still discover classes automatically if `class_to_idx=None` (which would be the default value).

I see your point about using the transform to get class names. Maybe it is best to keep things as is.

**Comment by fmassa** [comment]
I think we can achieve the similar behavior (and probably more, if we want to fuse classes together) with a custom `target_transform`. As such, I'm closing the issue but let me know if you disagree.

**Comment by dwSun** [comment]
It is confusing to use **target_transform** to achieve this, especially when I already have a pre-defined order of classes.
