### ISSUE TITLE
The complie problem of torchvision 0.5

### ISSUE THREAD

**Issue by Banyueqin** [pytorch/vision#1698]
![image](https://user-images.githubusercontent.com/32731721/71402185-36bc0480-2667-11ea-9e2a-9d83a6f254b0.png)
After complie torchvision 0.5,when import torchvision, it will cause the problem of the above picture.

**Comment by fmassa** [comment]
Hi,

Thanks for the report.

I can't reproduce this so I believe this has been fixed with the latest master version of PyTorch and torchvision.

Can you try updating them and re-opening the issue if the problem still persists?

**Comment by Banyueqin** [comment]
Thanks, when updating with the latest master version torchvision, there is no problem.
