### ISSUE TITLE
'train_one_epoch' gives error while using COCO annotations

### ISSUE THREAD

**Issue by madiltalay** [pytorch/vision#1699]
I am using the COCO dataset for training with annotations available at the COCO website.
While using the code from: [https://github.com/pytorch/vision/blob/master/references/detection/engine.py](url), I get an error:

> AttributeError: 'list' object has no attribute 'items'

for the code snippet:
`targets = [{k: v.to(device) for k, v in t.items()} for t in targets]`

Further digging into the issue, I find that the 'targets' I receive from the 'for loop':
`for images, targets in metric_logger.log_every(data_loader, print_freq, header):`

are in tuple format, with length equal to the batch_size.
Moreover, each item in this tuple is a list, and each list consists of seven dictionaries containing the annotation information.
When I apply this code to an individual object, it works fine:
```
target = targets[0]
obj_1 = target[0]
dict_1 = [{k: v for k, v in obj_1.items()}]
```
So I suppose the code might be written as follows:
`targets = [[{k: v for k, v in obj.items()} for obj in target] for target in targets]`

Can you guys please confirm this and provide help in this regard?

**Comment by fmassa** [comment]
Hi,

The `targets` should be a list of dictionaries, which is what is returned by the DataLoader after using this `collate_fn` https://github.com/pytorch/vision/blob/07cbb46aba8569f0fac95667d57421391e6d36e9/references/detection/utils.py#L237-L238 for the dataset https://github.com/pytorch/vision/blob/07cbb46aba8569f0fac95667d57421391e6d36e9/references/detection/coco_utils.py#L89-L101

So I suppose something is missing in your version of the training script. Can you try running the training code from https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html (check the Google Colab notebook in the top), it should work as expected, and I think it will help you find the error.

Let me know if you have further questions

**Comment by dquadro** [comment]
Hi, i'm using a COCO Dataset and have the same problem.
