### ISSUE TITLE
Errors with COCO targets

### ISSUE THREAD

**Issue by madiltalay** [pytorch/vision#1701]
I am using the COCO dataset for training with annotations available at the COCO website.
I use this dataloader:
`train_dataloader = torch.utils.data.DataLoader(train_dataset, batch_size=1, shuffle=True, num_workers=4, collate_fn=collate_fn)
`

Running one iteration:
`image, target = next(iter(train_dataloader))`
gives 'image' and 'target' of type 'tuple'

To convert the 'target' into the desired type (list of dicts), I use:
`target = [[{k: v for k, v in obj.items()} for obj in t] for t in target]`

Now when I run:
`loss_dict = model(image,target)`
It gives:

> /usr/local/lib/python3.6/dist-packages/torchvision/models/detection/transform.py in resize(self, image, target)
     73             return image, target
     74 
---> 75         bbox = target["boxes"]
     76         bbox = resize_boxes(bbox, (h, w), image.shape[-2:])
     77         target["boxes"] = bbox
TypeError: list indices must be integers or slices, not str

I try to play around:
```
new_target = {} 
new_target['boxes'] = [t['bbox'] for t in target[0]] 
new_target['labels'] = [t['category_id'] for t in target[0]] 
new_target = [new_target]
```
And it gives another error:

> /usr/local/lib/python3.6/dist-packages/torchvision/models/detection/transform.py in resize_boxes(boxes, original_size, new_size)
    135     ratios = tuple(float(s) / float(s_orig) for s, s_orig in zip(new_size, original_size))
    136     ratio_height, ratio_width = ratios
--> 137     xmin, ymin, xmax, ymax = boxes.unbind(1)
    138     xmin = xmin * ratio_width
    139     xmax = xmax * ratio_width
AttributeError: 'list' object has no attribute 'unbind'

Can anyone please help?

**Comment by fmassa** [comment]
Hi,

I think this error is related to https://github.com/pytorch/vision/issues/1699#issuecomment-571991699

You shouldn't convert the target via
```python
target = [[{k: v for k, v in obj.items()} for obj in t] for t in target]
```
Instead, the target is already in the correct format in the code, and shouldn't be changed, so just do
```python
image, target = next(iter(train_dataloader))
loss_dict = model(image, target)
```
