### ISSUE TITLE
'loss_dict' error from 'train_one_epoch'

### ISSUE THREAD

**Issue by madiltalay** [pytorch/vision#1707]
Navigating through the code in 'train_one_epoch', running this line:
`loss_dict = model(image,targets)`
gives the error:

> 397         # RPN uses all feature maps that are available
--> 398         features = list(features.values())
    399         objectness, pred_bbox_deltas = self.head(features)
    400         anchors = self.anchor_generator(images, features)
AttributeError: 'tuple' object has no attribute 'values'

Can anyone help?

**Comment by fmassa** [comment]
Related to https://github.com/pytorch/vision/issues/1699 and https://github.com/pytorch/vision/issues/1701

Sorry for the delay in replying, I was on holidays.

**Comment by XtianCarlosQ** [comment]
Hi, to solved this issue is requiered to list the images too:

```
images,targets = next(iter(train_loader))
images = list(image for image in images)
targets = [{k: v for k, v in t.items()} for t in targets]
output = model(images,targets)   # Returns losses and detections
```
