### ISSUE TITLE
[Question] Isn't setting align_corners=True a more popular choice in segmentation models?

### ISSUE THREAD

**Issue by voldemortX** [pytorch/vision#1708]
In DeepLabV3 codes, when an upsampling layer is used, the **align_corners** argument is set as **False** :
https://github.com/pytorch/vision/blob/d2c763e14efe57e4bf3ebf916ec243ce8ce3315c/torchvision/models/segmentation/_utils.py#L25
https://github.com/pytorch/vision/blob/d2c763e14efe57e4bf3ebf916ec243ce8ce3315c/torchvision/models/segmentation/_utils.py#L31
https://github.com/pytorch/vision/blob/d2c763e14efe57e4bf3ebf916ec243ce8ce3315c/torchvision/models/segmentation/deeplabv3.py#L62

But researchers in the semantic segmentation field usually set this as **True** based on a common understanding that this will bring performance improvement(however small).

**Comment by fmassa** [comment]
Hi,

Using `align_corners=False` actually make the results of the interpolation match the results of OpenCV and TensorFlow, so I would expect that using `align_corners=False` would be expected.

Do you have any references of researchers setting it to `True` elsewhere?

**Comment by voldemortX** [comment]
Well, it's more like an insider trick that is used by lots of people to get better performance at corners, and it is becoming a norm.
e.g. 
https://github.com/jfzhang95/pytorch-deeplab-xception/blob/9135e104a7a51ea9effa9c6676a2fcffe6a6a2e6/modeling/deeplab.py#L31

https://github.com/speedinghzl/pytorch-segmentation-toolbox/blob/765941f8ce61390f78ecd94f155a121539be5108/networks/deeplabv3.py#L92

https://github.com/XiaLiPKU/EMANet/blob/b7d7ce0a46d4f17964a5551150742efd6ab6585b/dataset.py#L35

**Comment by fmassa** [comment]
I wonder if this is done on purpose or is just an artifact that the error message, which reads
```
Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
```

We would need to run some trainings with both `align_corners=False` and `align_corners=True` in order to see if there is any significant performance difference, before we consider making any changes.

**Comment by voldemortX** [comment]
I agree more trainings are necessary.
As I really don't have much resources myself, I only conducted training 3 times on each setup with mixed precision training and without COCO pretraining on [this](https://github.com/voldemortX/DeeplabV3_PyTorch1.3_Codebase), and the average mIoU for `align_corners=False` & `align_corners=True` is 76.45% & 76.69% respectively, but it still could be just a coincidence since the training process is stochastic.
Looking forward for your training results.

**Comment by fmassa** [comment]
Thanks for the numbers you reported! A 0.2% mIoU difference is very probably just within noise, so I wouldn't expect it to really make that much of a difference. But as you said, I should still run a few trainings just to make sure

**Comment by mthrok** [comment]
Hi @voldemortX 

@fmassa and I conducted the experiments regarding this.
We trained 3 models each for `align_corners=True` and `align_corners=False`, and we did not see difference.

## Result

align_corners | True | True | True | | False | False | False  
-- | -- | -- | -- | -- | -- | -- | --
Global Correct | 92.5 | 92.5 | 92.8 |   | 92.5 | 92.6 | 92.4
Mean IoU | 67.6 | 67.3 | 67.8 |   | 67.6 | 67.8 | 67.2

## Environment

**Comment by fmassa** [comment]
Thanks for the investigation @mthrok !
