### ISSUE TITLE
finetuning inception_v3

### ISSUE THREAD

**Issue by stormchasingg** [pytorch/vision#1710]
finetuning resnet18 as
train: `models.resnet18(pretrained=True)`
val:   `models.resnet18()`
But while finetuning inception_v3 as above, I got poor result. The valuation must be
val:   `models.inception_v3(pretrained=True)`
I spent much time stucking here..

**Comment by fmassa** [comment]
Hi,

I have never been able to train / finetune inceptionV3, nor do transfer learning with it.

The pre-trained weights have been converted from TensorFlow, and might have required external data / intermediate classifiers to be able to train it properly.

I would recommend using ResNet / ResNeXt models, which are well understood and give good results.
