### ISSUE TITLE
Enquiry on Implementation of RandomHorizontalFlip (in transforms.py from references folder)

### ISSUE THREAD

**Issue by riven314** [pytorch/vision#1720]
I am a bit confused by the implementation RandomHorizontalFlip defined [here](https://github.com/pytorch/vision/blob/master/references/detection/transforms.py). Note the following snippet extracted:
```
class RandomHorizontalFlip(object):
    def __init__(self, prob):
        self.prob = prob

    def __call__(self, image, target):
        if random.random() < self.prob:
            height, width = image.shape[-2:]
            image = image.flip(-1)
            bbox = target["boxes"]
            bbox[:, [0, 2]] = width - bbox[:, [2, 0]]
            target["boxes"] = bbox
```

should ```bbox[:, [0, 2]] = width - bbox[:, [2, 0]]``` be ```bbox[:, [1, 3]] = width - bbox[:, [3, 1]]``` instead?  
Let original bounding box be ```[xmin, ymin, xmax, ymax]``` and image have size ```(height, width)```.  After horizontal flip, the bounding box location should be ```[xmin, width - ymax, xmax, width - ymin]```.  
(Please correct me if I have something wrong)

**Comment by Lucas-Steinmann** [comment]
After horizontal flip, the bounding box location should be ``[width - xmax, ymin, width - xmin, ymax]``.

The x-axis corresponds to the width of the image, while the y-axis corresponds to its height.
Maybe the confusion arises from the issue that the shape of the image is in a different order (height/y first) than the box coordinates (x first).

**Comment by fmassa** [comment]
@Lucas-Steinmann answer is correct, thanks Lucas for the help!
