### ISSUE TITLE
Command lines to train video classification networks

### ISSUE THREAD

**Issue by a-maci** [pytorch/vision#1722]
There are 3 video classification networks in torchvision (ResNet 3D 18, ResNet MC 18 and Res 2+1 D). _What are the command lines to train each of these networks?_

_Also, any pointers on how to prepare the Kinetics-400 dataset?_ 
Link to Kinetics 400 in https://deepmind.com/research/open-source/kinetics leads to few csv files -- what to do with these files and prep the data to feed the training scripts?

**Comment by a-maci** [comment]
Any update on this?

**Comment by fmassa** [comment]
We've added the command-lines in https://github.com/pytorch/vision/tree/master/references/video_classification, on 8 nodes with 8 GPUs each (for a total of 64 GPUs)
