### ISSUE TITLE
resnet_fpn_backbone("resnext101_32x8d", True)    error

### ISSUE THREAD

**Issue by cl2227619761** [pytorch/vision#1725]
when using resnet_fpn_backbone("resnext101_32x8d", True), there is error in loading stat_dict for ResNet

**Comment by fmassa** [comment]
I believe this has been fixed in latest nightly with https://github.com/pytorch/vision/pull/1728.

Please let us know if you still face this error

**Comment by cl2227619761** [comment]
> I believe this has been fixed in latest nightly with #1728.
> 
> Please let us know if you still face this error

Fixed! thank you so much!
