### ISSUE TITLE
How to use Resnet to deal with one channel input through pytorch.hub ?

### ISSUE THREAD

**Issue by PhilWallace** [pytorch/vision#1732]
I did this to load the Resnet model, and since my input contains only one channel, the model does not work.

`model = torch.hub.load('pytorch/vision:v0.4.2', 'resnet18', pretrained=True)`

I know how to modify the 'resnet.py' file to satisfy my demands, but that means I must include the modified 'resnet.py' file in my project, which may be unnecessary. It will be a lot better if the model can be loaded simply from pytorch.

Anyone has solutions? Thanks a lot.

**Comment by fmassa** [comment]
Hi,

The current best solution is to convert your input image to have 3 channels.

This can be accomplished with something like
```python
# input is a 4d tensor of
# [N, 1, H, W] shape
input = input.repeat(1, 3, 1, 1)
```
and then feed it directly to your model.

Given it's very simple to adapt a pipeline for 1-channels images, we won't currently be adding support for configuring the number of input channels in the input.
