### ISSUE TITLE
ImageNet dataset duplicated label

### ISSUE THREAD

**Issue by GeondoPark** [pytorch/vision#1734]
In the imagenet dataset, there is a duplicated label "crane".
The same wording is used, but one mean a bird and the other mean a crane used in construction.
When I observe the imagenet.py code, it seems that the two labels are unintentionally merged into one. Because class_to_idx is made into a dictionary, and the class is str.

However when we use ImageFolder dataset, the labels are made with folder name, so they avoid merging the labels.

**Comment by fmassa** [comment]
Hi,

Thanks for opening the issue! Is this still an issue, in which case we should re-open the issue?
