### ISSUE TITLE
MaskRCNN Issue Export to ONNX

### ISSUE THREAD

**Issue by peasant98** [pytorch/vision#1740]
When I try to to export a torchvision MaskRCNN model to RCNN, I get, 
`/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py:769: UserWarning: ONNX export failed on custom operator torchvision::_new_empty_tensor_op because torch.onnx.symbolic_opset11._new_empty_tensor_op does not exist. Have you registered your symbolic function with torch.onnx.register_custom_op_symbolic(symbolic_name, symbolic_fn)?`

I noticed this file (https://github.com/pytorch/vision/blob/master/torchvision/ops/_register_onnx_ops.py) and was wondering when support for `_new_empty_tensor_op` will occur. Thanks!

**Comment by fmassa** [comment]
Hi,

This will be fixed in https://github.com/pytorch/vision/pull/1733

But note that it might be preferable to pass an input which is valid to the ONNX exporter, as there are still some rough edges with the ONNX exporter for Mask R-CNN, see https://github.com/pytorch/vision/issues/1741

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
