### ISSUE TITLE
 module 'torchvision' has no attribute 'ops'

### ISSUE THREAD

**Issue by omizonly** [pytorch/vision#1751]
torchvision. ops implements operators that are specific for Computer Vision. Those operators currently do not support TorchScript. Performs non-maximum suppression (NMS) on the boxes according to their intersection-over-union (IoU)

output[image_i] = pred[torchvision.ops.boxes.batched_nms(pred[:, :4], pred[:, 4], c, iou_thres)]

AttributeError: module 'torchvision' has no attribute 'ops'

[https://github.com/ultralytics/yolov3/blob/master/utils/utils.py](url)

can anyone please help me to bypass this problem?

**Comment by fmassa** [comment]
Hi,

You are using an old version of torchvision. `ops` is available since version 0.3.0.
You can check your version by doing `torchvision.__version__`.

You can update to a newer version of torchvision (and PyTorch) following the instructions in https://pytorch.org/get-started/locally/
