### ISSUE TITLE
[Update Request] Release v0.5.0 still versioned as v0.5.0a0

### ISSUE THREAD

**Issue by yashnv** [pytorch/vision#1755]
[Here](https://github.com/pytorch/vision/blob/v0.5.0/setup.py#L33)

**Comment by fmassa** [comment]
This should have been fixed in https://github.com/pytorch/vision/pull/1717

@soumith did you build the binaries from the branch in #1717 ?

**Comment by soumith** [comment]
yes that's how i built it

**Comment by soumith** [comment]
that line is irrelevant, as we reset the version here: https://github.com/pytorch/vision/blob/v0.5.0/setup.py#L44
