### ISSUE TITLE
Nightly build failure on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/vision#1756]
Starting from Jan.11, the nightly build started to fail. (commit: 61763fa)
See https://dev.azure.com/pytorch/778b86d3-09b9-4636-a34b-315646862684/_apis/build/builds/18418/logs/122.

**Comment by fmassa** [comment]
I suspect the failure in torchvision is due to a change somewhere in PyTorch, because there has been no changes in torchvision C++ files since then that could potentially be the culprit.

**Comment by peterjc123** [comment]
https://github.com/pytorch/vision/blob/master/torchvision/csrc/vision.cpp#L20 Maybe we should add a `PyInit__C` function here?

**Comment by fmassa** [comment]
Maybe, but I wonder what has changed since https://github.com/pytorch/vision/pull/1348 , so because CI was passing back then.
Could you try sending a PR to see if it fixes it?

**Comment by asears** [comment]
Doesn't look like Windows version has been published to pypi?  https://pypi.org/project/torchvision/0.5.0/#files

Last release appears to be
https://pypi.org/project/torchvision/0.4.1/#files

**Comment by peterjc123** [comment]
@asears Your issue doesn't seem to be related to mine. Would you please open a new one?

**Comment by asears** [comment]
Added #1774

**Comment by peterjc123** [comment]
Well, I think I figured out what happened here. It was caused by the removal of the static library `_C.lib` at the PyTorch side in https://github.com/pytorch/pytorch/pull/31161. Before that change is merged, building `torchvision._C` uses the init function `PyInit__C` from PyTorch, which is actually not correct. We should define our own version of that.

**Comment by fmassa** [comment]
Thanks a lot for the investigation and the fix @peterjc123 !

**Comment by egbertn** [comment]
This error still happens, when activating pytorch...

Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch._custom_ops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch' has no attribute '_custom_ops'

The code that is generatated when creating a wheel for pytorch vision, uses torch._custom_ops which should be, I understand, torch._C?

torchvision-0.15.0%2B0b41ff0-cp38-cp38-linux_aarch64.whl#sha256=ad8d24697eb2bfdcf4f4a7205433b0b66fa47723162040952e748b1cd8966955
