### ISSUE TITLE
README out of date re: torch compatibility

### ISSUE THREAD

**Issue by dataframing** [pytorch/vision#1762]
Under the README's [Installation section](https://github.com/pytorch/vision#installation) it states:

> TorchVision requires PyTorch 1.2 or newer.

This doesn't seem to be true as of 0.5.0. In a clean environment:

```bash
$ pipenv --python 3.7
$ pipenv install torchvision
$ pipenv graph
torchvision==0.5.0
  - numpy [required: Any, installed: 1.18.1]
  - pillow [required: >=4.1.1, installed: 7.0.0]
  - six [required: Any, installed: 1.14.0]
  - torch [required: ==1.4.0, installed: 1.4.0]  <<< Strict requirement: torch==1.4.0
```

This seems related to https://github.com/pytorch/vision/issues/1257. Is this intended? Thanks.

**Update:** it seems like this is intended as per https://github.com/pytorch/vision/pull/1717. Maybe that PR should also update the README?

**Comment by fmassa** [comment]
Yes, the README is outdated, it now requires PyTorch 1.4 or newer. Can you send a PR improving the README?

**Comment by dataframing** [comment]
@fmassa Sure thing! I've opened #1767. Thanks 👍

**Comment by fmassa** [comment]
Fixed via https://github.com/pytorch/vision/pull/1767 , thanks @dataframing for the fix!
