### ISSUE TITLE
When building with CUDA, parts of the codebase are built with -O0

### ISSUE THREAD

**Issue by zou3519** [pytorch/vision#1769]
Please correct me if I'm wrong, but I was reading the setup.py for torchvision and it looks like when it is compiling with CUDA on, any cpu code is compiled with -O0
https://github.com/pytorch/vision/blob/f922916091dcc2cd71135681d1ddc1a530a872e6/setup.py#L106-L118 .

Why is this the case?

**Comment by fmassa** [comment]
@zou3519 great question! I've asked myself the same question in https://github.com/pytorch/vision/commit/684c064c237da67ba24a24ac7e1212a56fd4a9fe#r33631158
@soumith any thoughts?

**Comment by soumith** [comment]
seems like a bug, please remove

**Comment by zou3519** [comment]
https://github.com/pytorch/vision/pull/1770 fixes this

**Comment by fmassa** [comment]
Fixed via https://github.com/pytorch/vision/pull/1770, tha is Richard for sending the fix!
