### ISSUE TITLE
I need torchvision.layer (0.2.0, branch layers), but '_C' not found

### ISSUE THREAD

**Issue by Dustray** [pytorch/vision#1771]
There is no '\_C' in torchvision\\\_\_init___.py
How to run it?
# Error: 
 File "C:\Users\Vivinia\Desktop\vision\torchvision\layers\nms.py", line 2, in <module>
    from torchvision import \_C
ImportError: cannot import name '\_C' from 'torchvision' (C:\Users\Vivinia\Desktop\vision\torchvision\\\_\_init___.py)

**Comment by fmassa** [comment]
`_C` has been replaced by a PyTorch custom op. Update your torchvision install to 0.5.0 and things should work fine

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
