### ISSUE TITLE
MobileNet's `x = x.mean([2, 3])` operation should be replaced by `nn.AdaptiveAvgPool2d((1,1))`

### ISSUE THREAD

**Issue by talcs** [pytorch/vision#1773]
Hello,

I've recently dealt with exporting trained MobileNet-V2 models from Pytorch to ONNX (and then to Keras). 

Background: 

* `x = x.mean([2, 3])` is actually a `GlobalAveragePooling2D` operation.
* It is performed in the MobileNet-V2 `forward()` method.
* The abstract  `GlobalAveragePooling2D` operation exists in ONNX and in Keras.
* `nn.AdaptiveAvgPool2d((1,1))` is a way to mimic this operation in Pytorch.

Why it should be changed:

* `.mean([2,3])` is not abstract, as it assumes that the dimension ordering is BCHW (In TF, it is BHWC).
* Pytorch's ONNX exporter translates the  `x = x.mean([2, 3])` operation to `ReduceMean` with explicit dimension indices.
* Meanwhile, it translates `nn.AdaptiveAvgPool2d((1,1))` to `GlobalAveragePooling2D`, which is abstract and prevents errors related to dimension ordering.

Tests:
* Replacing the explicit mean operation by the abstract one will keep the model backward compatible.
* I can testimony from my own experience that models that I have saved with the original MobileNet-V2 implementation still worked (the same) when I loaded their weights to a model that called the adaptive avg pooling layer instead of the explicit mean operation.

Thanks.

**Comment by fmassa** [comment]
Hi,

Thanks for opening the issue and for the discussion!

Among the points you mentioned, I think that the one that convinced me the most is the dimension ordering NHWC <-> NCHW. We are still working on supporting other memory layouts in PyTorch, but I think this is a fair point.

Can you send a PR changing the `x.mean([2, 3])` with `AdaptiveAvgPool2d(1)`?

**Comment by talcs** [comment]
Thank you for the response!

If additional memory layouts are going to be available, then using the abstract operation is definitely the correct choice over explicit, hardcoded dimension indices.

I'm not very familiar with the issue system. How can I open a PR as you're asking?

**Comment by fmassa** [comment]
Fixed via #1838
