### ISSUE TITLE
Pytorchvision 0.5.0 not published to pypi or Conda for Windows

### ISSUE THREAD

**Issue by asears** [pytorch/vision#1774]
The integration with PIL 7.0 VERSION API change is breaking some dependencies. I can see these are fixed in Linux / Mac releases.

Doesn't look like Windows version has been published to pypi? https://pypi.org/project/torchvision/0.5.0/#files

Last release appears to be
https://pypi.org/project/torchvision/0.4.1/#files

References #1759 #1712 #1718 #1726

**Comment by peterjc123** [comment]
cc @soumith

**Comment by peterjc123** [comment]
It is published to Anaconda Cloud, but not PYPI.
https://anaconda.org/pytorch/torchvision
https://pypi.org/project/torchvision/0.5.0/#files

**Comment by soumith** [comment]
The windows version of torchvision (and pytorch) were never uploaded to PyPI. The Windows PyTorch version exceeds the binary size limits, and hence we cant upload it.
Because torchvision depends on the pytorch package, it wont make sense to upload just the torchvision Windows package to PyPI, as a `pip install` will surely fail.

I suggest that in your requirements.txt you add something like this:

```
-f https://download.pytorch.org/whl/torch_stable.html
torch===1.4.0
torchvision===0.5.0 
```

**Comment by asears** [comment]
@soumith can someone request a package increase and deploy to pip?  Could this issue be reopened as it's still not published to PyPI.

It was previously deployed to pip so size limitation shouldn't be an issue.

**Comment by soumith** [comment]
Okay, I am wrong in the sense that, I didn't notice that we pushed 0.4.1 Windows binaries to torchvision pip -- we shouldn't have.
If we shouldn't have, but we did, might as well do 0.5.0.

I've uploaded torchvision 0.5.0 to PyPI now, and updated our release runbook to do so in the future.

the `torch` package which `torchvision` depends on will not be uploaded for Windows, until if and when we figure out a size issue and we have more people working on Windows.

**Comment by asears** [comment]
What's the current size / limit?  How many people do you need working on Windows? 👎 

The size request can be done here.
https://github.com/pypa/warehouse/issues

See
https://github.com/pypa/packaging-problems/issues/245
https://github.com/pypa/packaging-problems/issues/86

Thanks for fixing up torchvision!

**Comment by soumith** [comment]
the size limit right now is 750MB, and we already asked for way too much, compared to everyone else. If you see pypa/packaging-problems, you will find issues that I filed. The windows binaries are larger than 750MB

**Comment by peterjc123** [comment]
Actually, when I inspected the package carefully, most of the size is taken up by the CUDA DLLs, which is nearly 400M. So if pypi provides a global package for cudatoolkit like conda, then the size of our Windows package can be greatly decreased. Alternatively, we may do it on our own and create a new package called `torch-deps` and move all the dependencies (like CUDA) into it. What do you think? @soumith @ezyang

**Comment by soumith** [comment]
yes, CUDA and NVIDIA refuse to provide one, I asked them several times.

**Comment by soumith** [comment]
`torch-deps` which only includes our DLLs is not okay. We dont have license to redistribute DLLs separately, we can only redistributed them with our package's binary bits.

**Comment by soumith** [comment]
the third way is not possible, as it's not clear that we will have a user-writeable folder available after the wheel is installed

**Comment by peterjc123** [comment]
> yes, CUDA and NVIDIA refuse to provide one, I asked them several times.

That's so sad. I think that's the best option for this problem. CUDA itself is free and public. I don't see the reason why they don't want to do this. DLL-only Libraries like MKL are already available, so it is also acceptable at the PyPI side.

**Comment by 1enn0** [comment]
Hello everybody!

Not sure, whether this is the correct place for my question but I'll give it a shot.

I'm wondering about the deployment strategy to PyPI for Windows. I'm aware that the "official" way of installing PyTorch is through [https://download.pytorch.org/whl/torch_stable.html](https://download.pytorch.org/whl/torch_stable.html).

I noticed the wheel for the win/cpu build of the main `torch` package [is available](https://pypi.org/project/torch/#files) on PyPI, while the win wheels for `torchvision` and `torchaudio` packages are not (see [here](https://pypi.org/project/torchvision/#files) and [here](https://pypi.org/project/torchaudio/#files)).

Judging from the filesizes for the other platforms, the PyPI binary size constraint should not be an issue for either package (<15 MB).

Is there a reason for why `torchvision` and `torchaudio` are not pushed to PyPI?
