### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by barrh** [pytorch/vision#1780]
I've noticed that when `pip install torch torchvision` with Python v3.8, the following is installed: torch v1.4, torchvision v0.2.2.post3.
Trying to install v0.5 of torchvision specifically fails for no matching distribution found.
"ERROR: Could not find a version that satisfies the requirement torchvision==0.5 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3)
ERROR: No matching distribution found for torchvision==0.5"

Any reason not to publish Python3.8 compatible build for 0.5?

**Comment by pmeier** [comment]
From the list of available versions, it seems we stopped supporting `python3.8` last year (somewhere between `torchvision==0.2.2` in Feb 2019 and `torchvision==0.3.0` in May 2019). I don't think there is anything special about `torchvision==0.5.0` not supporting it. If you have a look at the [official installation instructions](https://pytorch.org/get-started/locally/) `python3.8` is not listed as an option. I always thought that means it is not supported. What I find strange is that apparently `pip3.8` can install `torch==1.4.0`. 

@fmassa Should we support `python3.8` as `torch` does or is this some unintended feature on their side?

**Comment by fmassa** [comment]
We still have some build issues with Python 3.8, which haven't been fixed yet, but once they are we will provide packages for those, see https://github.com/pytorch/vision/pull/1731

**Comment by fmassa** [comment]
We now have CI support for Python 3.8 in #1731 and binaries as well thanks to https://github.com/pytorch/vision/pull/1717

**Comment by chiragraman** [comment]
This still seems to be an issue on MacOS (10.15.1):

Running `conda install torchvision=0.5.0 -c pytorch -c conda-forge` yields the following :

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - torchvision=0.5.0 -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.8.0
```
I believe that the 3.8.0 binaries were released on the pytorch channel for all platforms, is that not so?

**Comment by fmassa** [comment]
@chiragraman thanks for the report, indeed it seems that we are missing OSX builds for Python 3.8.

@seemethere could you have a look? From https://anaconda.org/pytorch/torchvision/files we are missing Python 3.8 binaries for OSX

**Comment by seemethere** [comment]
Taking a look right now

**Comment by seemethere** [comment]
Issue should now be resolved, closing.
