### ISSUE TITLE
Contribution: select classes in UCF101 dataset

### ISSUE THREAD

**Issue by dvolkhonskiy** [pytorch/vision#1791]
Hello. 

I would like to contribute to your repository. I want to add the opportunity to select classes to load for the UCF101 dataset.

What do you think of this feature?

cc @pmeier @bjuncek

**Comment by bjuncek** [comment]
Is there a strict need for this? 
My understanding is that we're trying to maintain only baseline popular datasets here.

This seems like something which might be more suited for (an example) a few-shot dataset library?

cc @fmassa thoughts?

**Comment by bjuncek** [comment]
Closing as inactive, added to a tracker for future reference
