### ISSUE TITLE
Excessively long initialization time for Inception3

### ISSUE THREAD

**Issue by os-gabe** [pytorch/vision#1797]
Creating an instance of the `Inception3` class via `torchvision.models.inception_v3(pretrained=False)` or `torchvision.models.Inception3()` takes several minutes to complete.

It appears that all of the time is being spent here [here](https://github.com/pytorch/vision/blob/28b7f8ae219ede3cef93100251bfff75a9a53644/torchvision/models/inception.py#L111).

I believe this may be related to some change in scipy perhaps as I do not think this model used to take so long to instantiate.

**Comment by os-gabe** [comment]
I confirmed that rolling scipy from `1.4.1` back to `1.3.1` causes the issue to go away.

So this is not strictly a torchvision bug but it does mean that `Inception3` becomes somewhat unusable for people who upgrade scipy or install the current version from pip.

**Comment by fmassa** [comment]
@os-gabe one alternative, given that we don't really train inception from scratch, would be to remove the custom initialization based on scipy.

That would be a breaking change though.

**Comment by os-gabe** [comment]
Here is the scipy issue for reference https://github.com/scipy/scipy/issues/11299

**Comment by os-gabe** [comment]
@fmassa what if the `Inception3` constructor took in an keyword argument to skip the random initialization? If the flag defaulted to `False` wouldn't this maintain backwards compatibility? This seems like a fairly nice solution in general since the random initialization is not needed when we just plan to load weights anyway.

**Comment by fmassa** [comment]
Yeah, we could do something similar to what we do in VGG https://github.com/pytorch/vision/blob/e130c6cca88160b6bf7fea9b8bc251601a1a75c5/torchvision/models/vgg.py#L26
with `init_weights`. Can you send a PR for inception?

**Comment by fmassa** [comment]
Fixed with https://github.com/pytorch/vision/pull/1832

**Comment by mingjunlie** [comment]
Is this released?

**Comment by os-gabe** [comment]
There hasn't been a release since this change was merged. I'm curious to know when the next release is planned for.

**Comment by mingjunlie** [comment]
I had very bad time to debug problem related to this issue.

**Comment by fmassa** [comment]
Next release for torchvision will happen in a couple of weeks. But the underlying problem is with scipy, so the "fix" we use in torchvision is to skip the default initialization if the user specifies it.
