### ISSUE TITLE
An abstract class for all transforms

### ISSUE THREAD

**Issue by chsasank** [pytorch/vision#181]
Shouldn't there be a base class for all transforms like `torch.utils.data.Dataset`? 

It can be:

```python
class Transform(object):
    def __init__():
        pass

    def __call__():
        raise NotImplementedError
```

This makes transforms transparent and easy to refer in other functions like `Compose`.

**Comment by alykhantejani** [comment]
Transforms don't necessarily have to be classes though, they can be any [callable](https://docs.python.org/3.3/library/functions.html#callable) (i.e. functions + classes)

**Comment by fmassa** [comment]
Given the discussions in #230, I'm not sure there is a need to an abstract class. I'm closing this issue, but let me know if you think otherwise and we can re-open it.
