### ISSUE TITLE
Is it better to create directory before save images in utils.save_image?

### ISSUE THREAD

**Issue by nmhkahn** [pytorch/vision#182]
Hi.
Same as the title, is it better to create directory before save images?
In current version, `utils.save_image` code looks like below
```python
im = Image.fromarray(ndarr)
im.save(filename)
```
However, I think it is more convenient if this function handle the case which specified directory is not exists.
```python
im = Image.fromarray(ndarr)

import os
directory = os.path.dirname(filename)
if not os.path.exists(directory):
    os.makedirs(directory)
im.save(filename)
```
Any ideas?
Thanks.

**Comment by fmassa** [comment]
I'd say it might be better to be explicit and let the user create the folder himself. This might be less error-prone on the user side.

BTW, your snippet has a problem, as if `filename='tst.png'`, it would first create a directory called `tst.png`, and then would try to save the image, potentially leading to errors.

**Comment by fatalfeel** [comment]
os.makedirs('directory', 0o777, exist_ok=True)
==>substutite to
if not os.path.exists(directory):
    os.makedirs(directory)
