### ISSUE TITLE
Pre-built wheels unexpectedly changed their hashes in the last days

### ISSUE THREAD

**Issue by daniel-j-h** [pytorch/vision#1839]
When using pip to install the pre-build torchvision wheels you can specify a `--hash` option to let pip verify the wheel's integrity. The hash can be computed e.g. via `pip hash *.whl`.

I noticed the cpu and gpu wheel hashes for torchvision 0.5.0 on Python 3.6 changing in the last days.

https://download.pytorch.org/whl/cpu/torchvision-0.5.0%2Bcpu-cp36-cp36m-linux_x86_64.whl

```
-          --hash=sha256:12a5d92dca112cfbfb6c2a4225fa2c281f77b0ae22e7b2c6cb80d7b2daa04b1e           \
+          --hash=sha256:ae3686f57a56c71ee7cc001bb067b3ebb246f1d6abc8b9023f7d7d043a4f8b83           \
```

https://download.pytorch.org/whl/cu101/torchvision-0.5.0-cp36-cp36m-linux_x86_64.whl

```
-          --hash=sha256:fea3d431bf639c0719afff5972eb568ebe143eba447c1c8bb491c7dfb0025ed6       \
+          --hash=sha256:df994daf1b04a183779538022fb4345b66364fccf66b33e1095ae8d4955a5406       \
```

This is unexpected and I would like to understand what the cause of the hash change is. Did you folks re-publish with slightly different wheels? Or what happened here?

**Comment by fmassa** [comment]
@soumith do you know what might have happened?

**Comment by soumith** [comment]
@daniel-j-h this is expected but accidental. We were building Python 3.8 binaries a few days after 1.4.0 release, and we inadvertently triggered all builds. Our build system is non-deterministic, and hence the hashes changed. The functionality in the wheel didn't actually change.

@seemethere and I will make sure this doesn't happen again, by making sure if we have any post-release builds, they happen with a bumped version.

**Comment by soumith** [comment]
to be clear, the hashes only changed for the wheels in https://download.pytorch.org/whl/ and not for the wheels on https://pypi.org/project/torch/

**Comment by daniel-j-h** [comment]
Thanks for the explanation! :bow:
