### ISSUE TITLE
Document the "scipy" extra

### ISSUE THREAD

**Issue by IRDonch** [pytorch/vision#1842]
Torchvision's `setup.py` defines a `scipy` extra that pulls in the `scipy` dependency that is needed by some of Torchvision's modules. This lets you use `torchvision[scipy]` as an argument to `pip install`, which is good, since it's a way to explicitly state that you're installing SciPy as a dependency of Torchvision.

However, this extra doesn't seem to be documented anywhere, so it's unclear whether doing `pip install torchvision[scipy]` is officially supported. It would be nice if this was documented in the README or elsewhere.

**Comment by fmassa** [comment]
I agree. We haven't documented scipy (or `pycocotools`) because they are not hard-requirements, and only a few functions of torchvision depends on them.

But it might be good to document that somewhere, maybe in the functions that use them?

Can you send a PR improving the documentation?

**Comment by nvs-abhilash** [comment]
@fmassa I have created a PR #1966 for this issue. Please let me know if anything else is required.
