### ISSUE TITLE
CMake scripts not working on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/vision#1845]
It reports that `python37.lib` is not found during linking. Maybe we need to do sth like `find_package(python)` to find out the path of the python library.

**Comment by fmassa** [comment]
@bmanga could you have a look at this?

**Comment by bmanga** [comment]
@fmassa sure, I'll look into it.
@peterjc123 can you list the steps you executed? Did it happen when you were using the cmake config file?

**Comment by peterjc123** [comment]
@bmanga https://discuss.pytorch.org/t/building-torchvision-c-api-from-source/68281/2?u=peterjc123

**Comment by bmanga** [comment]
I have set up the project on windows and I also found another problem: Some cmake script, somewhere, sets`cudart_static.lib` to be in the non-existent `...\CUDA\v10.1\...` directory, while I have v10.2 installed. I had to manually adjust that in the generated msvc solution, but I'm not sure yet what the fix should be.

The python issues comes from [pybind11](https://github.com/pybind/pybind11/blob/master/tools/FindPythonLibsNew.cmake), which is unable to find the python3 lib on windows.
`find_package (Python3 COMPONENTS Development)` seems to solve the issue, but I will also test it on linux before creating a PR.

**Comment by bjliuzp** [comment]
> @bmanga
> Steps: https://discuss.pytorch.org/t/building-torchvision-c-api-from-source/68281/2?u=peterjc123

@peterjc123 
Hello, I can successfully compile the cpu version by following the above steps, but the following error is displayed when compiling the CUDA version. What should I do?
win10 + VS2017 + Libtorch1.4.0 + TorchVision0.5.0

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_37,code=\"sm_37,compute_37\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include\torch\csrc\api\include -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files (x86)\pybind11\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -Xcompiler="/EHsc -Zi -Ob0" -Xcompiler "/wd 4819"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc141.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\DeformConv_cuda.obj "F:\0_deep_learning_project\02_pytorch\001_learning\software\torchvision\vision-0.5.0\torchvision\csrc\cuda\DeformConv_cuda.cu"”已退出，返回代码为 1。	torchvision	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.1.targets	764	
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_37,code=\"sm_37,compute_37\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include\torch\csrc\api\include -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files (x86)\pybind11\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -Xcompiler="/EHsc -Zi -Ob0" -Xcompiler "/wd 4819"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc141.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\PSROIAlign_cuda.obj "F:\0_deep_learning_project\02_pytorch\001_learning\software\torchvision\vision-0.5.0\torchvision\csrc\cuda\PSROIAlign_cuda.cu"”已退出，返回代码为 1。	torchvision	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.1.targets	764	
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_37,code=\"sm_37,compute_37\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include\torch\csrc\api\include -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files (x86)\pybind11\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -Xcompiler="/EHsc -Zi -Ob0" -Xcompiler "/wd 4819"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc141.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\ROIAlign_cuda.obj "F:\0_deep_learning_project\02_pytorch\001_learning\software\torchvision\vision-0.5.0\torchvision\csrc\cuda\ROIAlign_cuda.cu"”已退出，返回代码为 1。	torchvision	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.1.targets	764	
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_37,code=\"sm_37,compute_37\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include\torch\csrc\api\include -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files (x86)\pybind11\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -Xcompiler="/EHsc -Zi -Ob0" -Xcompiler "/wd 4819"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc141.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\nms_cuda.obj "F:\0_deep_learning_project\02_pytorch\001_learning\software\torchvision\vision-0.5.0\torchvision\csrc\cuda\nms_cuda.cu"”已退出，返回代码为 1。	torchvision	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.1.targets	764	
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_37,code=\"sm_37,compute_37\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include\torch\csrc\api\include -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files (x86)\pybind11\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -Xcompiler="/EHsc -Zi -Ob0" -Xcompiler "/wd 4819"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc141.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\ROIPool_cuda.obj "F:\0_deep_learning_project\02_pytorch\001_learning\software\torchvision\vision-0.5.0\torchvision\csrc\cuda\ROIPool_cuda.cu"”已退出，返回代码为 1。	torchvision	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.1.targets	764	
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_37,code=\"sm_37,compute_37\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_61,code=\"sm_61,compute_61\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64" -x cu  -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include -IF:\0_deep_learning_project\02_pytorch\003_software\1.4.0\libtorch\cuda\release\include\torch\csrc\api\include -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"C:\Program Files (x86)\pybind11\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -Xcompiler="/EHsc -Zi -Ob0" -Xcompiler "/wd 4819"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc141.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\PSROIPool_cuda.obj "F:\0_deep_learning_project\02_pytorch\001_learning\software\torchvision\vision-0.5.0\torchvision\csrc\cuda\PSROIPool_cuda.cu"”已退出，返回代码为 1。	torchvision	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.1.targets	764

**Comment by bmanga** [comment]
@peterjc123 can you check if #1850 fixes your issue with `python37.lib`?

**Comment by fmigneault** [comment]
> I have set up the project on windows and I also found another problem: Some cmake script, somewhere, sets`cudart_static.lib` to be in the non-existent `...\CUDA\v10.1\...` directory, while I have v10.2 installed. I had to manually adjust that in the generated msvc solution, but I'm not sure yet what the fix should be.
> 
> The python issues comes from [pybind11](https://github.com/pybind/pybind11/blob/master/tools/FindPythonLibsNew.cmake), which is unable to find the python3 lib on windows.
> `find_package (Python3 COMPONENTS Development)` seems to solve the issue, but I will also test it on linux before creating a PR.

Funny enough, I'm having the opposite behaviour  on my side (such that I got 10.1 installed and 10.2 somehow finds its way to the generated solution) (see #1865).

I also question if `pybind11` actually needs to be enforced at all? 
I'm looking into using *only* the C++ API and having to compile and "plug" `pybind11` just so that the dependencies are fulfilled even though I won't even use them is not that great.

**Comment by bmanga** [comment]
> Funny enough, I'm having the opposite behaviour on my side (such that I got 10.1 installed and 10.2 somehow finds its way to the generated solution) (see #1865).

That's very strange, but at least now I'm more confident it's not a setup issue on my part.
> I also question if `pybind11` actually needs to be enforced at all?
> I'm looking into using _only_ the C++ API and having to compile and "plug" `pybind11` just so that the dependencies are fulfilled even though I won't even use them is not that great.

@fmigneault That's what  #1850 implements. It is currently marked as WIP because I was waiting on independent confirmation that it indeed fixes the problem on windows. If you don't mind giving it a try, please let me know if it works for you :)

**Comment by peterjc123** [comment]
According to @fmigneault, it should be working with this PR.

**Comment by bmanga** [comment]
@peterjc123 Thanks!
