### ISSUE TITLE
Pillow Version 7.0.0 ValueError image is wrong mode

### ISSUE THREAD

**Issue by clkotnik** [pytorch/vision#1846]
I had a program running for awhile that used Image.resize(size) with defaults for other parms.  I installed the program on a new system with Pillow installed as default version 7.0.0.  The resize failed with Value Error image is wrong mode.

I removed Pillow and forced version 6.2.1 to install and the program works as before.

**Comment by pmeier** [comment]
What version of `torchvision` are you using. The release of `pillow=7.0.0` broke `torchvision==0.4.2` (#1714), but it should be fine for the latest release (`torchvision==0.5.0`). If that is not the case, please post a small example how to reproduce your error.

**Comment by clkotnik** [comment]
I do not use torchvision.

Here is a simplified example:

> import numpy as np
> from PIL import Image
> imgdata = np.array( [[484, 451, 481, 465, 488, 442],
>  [823, 897, 971, 920, 855, 908],
>  [758, 919, 854, 920, 850, 854],
>  [840, 873, 950, 893, 872, 881],
>  [937, 940, 835, 879, 895, 774],
>  [841, 914, 867, 886, 922, 952]]).astype(np.uint16)
> 
> pimg = Image.fromarray(imgdata)
> scale_factor = 0.5
> size = tuple((np.array(pimg.size) * scale_factor).astype(int))
> newim = pimg.resize(size)
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-1-5c0c4827f11b> in <module>
>      12 scale_factor = 0.5
>      13 size = tuple((np.array(pimg.size) * scale_factor).astype(int))
> ---> 14 newim = pimg.resize(size)
> 
> e:\program files\python37\lib\site-packages\PIL\Image.py in resize(self, size, resample, box, reducing_gap)
>    1871                 )
>    1872 
> -> 1873         return self._new(self.im.resize(size, resample, box))
>    1874 
>    1875     def reduce(self, factor, box=None):
> 
> ValueError: image has wrong mode
> 
>

**Comment by clkotnik** [comment]
Sorry, I seem to have drifted from Pillow to pytorch within github.  Please disregards, I posted this to Pillow.
