### ISSUE TITLE
Required range is confusing in torchvision.utils.save_image

### ISSUE THREAD

**Issue by chinglamchoi** [pytorch/vision#1847]
https://discuss.pytorch.org/t/float-vs-int-in-torchvision-utils-save-image/68596

**Comment by pmeier** [comment]
From the [referenced community](https://discuss.pytorch.org/t/float-vs-int-in-torchvision-utils-save-image/68596) post by @chinglamchoi:

> I predict a binary segmentation mask using an array with values 1 and 0, multiply this by 255, and try to save the resulting array as an image. However, I’m getting the following error:

```
Traceback (most recent call last):
File “test.py”, line 71, in
torchvision.utils.save_image(predicted, path_ + idx[0])
File “C:\Users\CCL\Anaconda3\lib\site-packages\torchvision\utils.py”, line 107, in save_image
ndarr = grid.mul(255).add_(0.5).clamp_(0, 255).permute(1, 2, 0).to(‘cpu’, torch.uint8).numpy() RuntimeError: result type Float can’t be cast to the desired output type Int
```
> Here is my code:

```python
mask_pred = net(img)
predicted = torch.sigmoid(mask_pred) > 0.5
predicted = torch.tensor(predicted, dtype=torch.int32)*255
torchvision.utils.save_image(predicted, path_ + idx[0])
```

> I’m using torch version 1.4.0 and torchvision version 0.5.0. The above code works on torch v1.1.0 and torchvision v0.3.0.

**Comment by pmeier** [comment]
The native "image data type" for `torchvision` is a `torch.FloatTensor` within the range `[0.0, 1.0]`. In your example this means you can eliminate the casting you performed and simply cast it to `torch.float`.

```python
mask_pred = net(img)
predicted = torch.sigmoid(mask_pred) > 0.5
# predicted = torch.tensor(predicted, dtype=torch.int32)*255
predicted = predicted.float()
torchvision.utils.save_image(predicted, path_ + idx[0])
```

Here is a minimal working example:

```python
import torch
import torchvision

mask_pred = torch.randn(3, 1, 256, 256)
predicted = (torch.sigmoid(mask_pred) > 0.5).float()
torchvision.utils.save_image(predicted, "test_segmentation.png")
```

**Comment by fmassa** [comment]
Thanks for the help @pmeier !

**Comment by addisonklinke** [comment]
Why not have `save_image` accept both `float[0.0, 1.0]` and `uint8[0, 255]` and check the tensor's `.dtype` attribute to determine which one applies?

**Comment by andrewsalim101** [comment]
On my condition, turning it into float fix the problem. I use this code

`import torchvision.transform.functional as cvF
from torchvision.utils import save_image

img = cvF.convert_image_dtype(img)

save_image(img, "img.jpg")`

**Comment by andrewsalim101** [comment]
`print("halo w")`

**Comment by chenin-wang** [comment]
The official documentation explains.
https://pytorch.org/vision/stable/transforms.html#range-and-dtype
