### ISSUE TITLE
training FCN and DeepLab for segmentation

### ISSUE THREAD

**Issue by isalirezag** [pytorch/vision#1848]
does PyTorch provide steps on how to use the deeplab or fcn for training a segmentation task?
if it already exists, where I can find it?

**Comment by voldemortX** [comment]
I believe you'll probably find what you need in the reference folder of this repo [here](https://github.com/pytorch/vision/tree/master/references/segmentation).

**Comment by fmassa** [comment]
Sending a PR improving the documentation so that the reference training scripts are more visible would be great!
