### ISSUE TITLE
pretrain models for FCN and DeepLabV3

### ISSUE THREAD

**Issue by isalirezag** [pytorch/vision#1853]
Is it possible to provide the pretrain weight for deeplabv3 and FCN?
right now when i do:
`model = torchvision.models.segmentation.fcn_resnet50(pretrained=True)`
I receive this:

> NotImplementedError: pretrained fcn_resnet50_coco is not supported as of now

**Comment by fmassa** [comment]
Hi,

We do provide pre-trained weights, but for now only for ResNet 101 backbone.

Could you try that one instead?

**Comment by isalirezag** [comment]
@fmassa 
Thanks for your reply.
I tried it. Resnet101 works fine, however, I cannot use it due to memory limitation.
Do you think that it would be possible to provide the weights for resnet 50 as well?

**Comment by fmassa** [comment]
I could look into it after ECCV deadline, but I won't have bandwidth before that unfortunately :-/

**Comment by isalirezag** [comment]
I understand. Thank you @fmassa

**Comment by isalirezag** [comment]
@fmassa Just a gentle reminder regarding the pretrained models for FCN50 and Deeplabv3 :)

**Comment by Gijs-Koot** [comment]
@isalirezag, if you are, like me, using a 4GB card and cannot start training because indeed calculating the gradients for the whole network is too much, you can train only the classifier part or the last layers of the backbone, that will work with 4GB.

**Comment by fmassa** [comment]
@mthrok could you have a look into this?

**Comment by mthrok** [comment]
I just launched the trainings for both `fcn_resnet50` and `deeplabv3_resnet50`.

**Comment by fmassa** [comment]
Let's keep the issue open until the new models are uploaded to torchvision

**Comment by mthrok** [comment]
We got the following result;


| Model  | Mean IoU | Global Accuracy |
| ------------- | ------------- | ------------- |
| fcn_resnet50  | 60.5  | 91.4 |
| deeplabv3_resnet50  | 66.4 | 92.4 |

We are preparing for the model release.

**Comment by seyeeet** [comment]
@mthrok can you tell me where i can find the pretrained models? right now I get an error when I want to load the pretrained version. I'm using the recent torch and torchvision.
![image](https://user-images.githubusercontent.com/62394093/80982156-eb75e780-8df8-11ea-81d6-655dc372ecc2.png)

**Comment by fmassa** [comment]
@seyeeet you need a nightly version of torchvision for that, it is not available in the 0.6.0 release

**Comment by seyeeet** [comment]
@fmassa is there a way to install   torchvision_nightly in conda?

**Comment by fmassa** [comment]
@seyeeet installation instructions are in https://pytorch.org/get-started/locally/

```
conda install pytorch torchvision -c pytorch-nightly
```

**Comment by haichaoyu** [comment]
Hi @mthrok , thanks for the pretrained models. What testing script did you use to get mIoU 66.4 with deeplabv3_resnet50? I used [this](https://github.com/pytorch/vision/blob/master/references/segmentation/train.py#L58) and got mIoU 65.3.

**Comment by mthrok** [comment]
Hi @haichaoyu 

I used the same function/script and the evaluation was performed while I was training the model.

You can see the training logs bellow; (the numbers are at the very bottom)
 -  [FCN](https://gist.github.com/mthrok/ab4f7213dcca8a25ebdc345a7ae36660)
 -  [DeepLabV3](https://gist.github.com/mthrok/afd23e9a5e30b07241cbfff186fe0563)

I used the most recent release version of PyTorch and Torchvision that were available in April 2020, so I believe they were Pytorch 1.4.0 and Torchvision 0.5.0.

**Comment by haichaoyu** [comment]
@mthrok Thanks. I changed DataParallel to single gpu and use batch size 1. The accuracy is 66.4 now.

**Comment by claudiotancredi** [comment]
> We got the following result;
> 
> Model	Mean IoU	Global Accuracy
> fcn_resnet50	60.5	91.4
> deeplabv3_resnet50	66.4	92.4
> We are preparing for the model release.

@mthrok I'm currently working on deeplabv3_resnet50 for Cityscapes and I have a few questions:

1. is your mIoU, 66.4, with pretraining? If so, what can I expect from a model without pretraining? Because I'm working on deeplabv3_resnet50 without pretraining and I'm getting a mIoU around 60%, do you think it could be correct?
2. in the original paper, authors reached a mIoU of 75% and more, why is your mIoU lower than this result? 
3. do you think that the mIoU of 75% can be reached only with pretrained weights?

Thank you.
