### ISSUE TITLE
FasterRCNN ground truth boxes reference system

### ISSUE THREAD

**Issue by Robylyon93** [pytorch/vision#1856]
Hi,
I'm trying to train a FasterRCNN on a custom dataset.
I have the ground truth bounding boxes in the [x1, y1, x2, y2] format, where:
- 0 <= x1 <= x2 <= H
- 0 <= y1 <= y2 <= W
- `H, W = img.shape` with img being loaded with cv2
With numpy, if I extract `img[x1:x2, y1:y2]`, it's the correct portion of the image.
Now, this seems to me the right way of formatting the boxes, since the documentation says:
> boxes (``FloatTensor[N, 4]``): the ground-truth boxes in ``[x1, y1, x2, y2]`` format, with values
          between ``0`` and ``H`` and ``0`` and ``W``

However, the network doesn't seem to be learning anything during training.
Instead, if I switch x1 with y1, x2 with y2, the network starts working properly.
It seems to be a reference system problem.
What am I missing? It feels like there is an easy explanation to this problem.

Thanks in advance!

**Comment by fmassa** [comment]
From your message:

> - 0 <= x1 <= x2 <= H
> - 0 <= y1 <= y2 <= W

Note that `x` should be between 0 and width, and `y` between 0 and height. It seem that you have switched the coordinates.

Indeed, from your message

> With numpy, if I extract img[x1:x2, y1:y2]

which means that actually, your `x` corresponds to what we note as `y`, and vice versa. We generally do `img[y1:y2, x1:x2]` instead..

Let me know if you have further questions

**Comment by Robylyon93** [comment]
Thanks for the answer!
But isn't it counterintuitive to have the coordinated formatted that way?
I mean, you access the portion of the image using `img[y1:y2, x1,x2]`, with `0 <= y1 <= y2 <= H (rows)` and `0 <= x1 <= x2 <= W (columns)`, so you first have rows, then the columns.
I cannot understand why bounding box format should be `[col0, row0, col1, row1]`, which is ordered the opposite way.
Also, as I mentioned in the first message, the docs say:
> boxes (``FloatTensor[N, 4]``): the ground-truth boxes in ``[x1, y1, x2, y2]`` format, with values between ``0`` and ``H`` and ``0`` and ``W``

which I interpret as "rows go before columns".

**Comment by fmassa** [comment]
we can change the way it's phrased in the documentation to read
> boxes (FloatTensor[N, 4]): the ground-truth boxes in [x1, y1, x2, y2] format, with values between 0 and W and 0 and H

if it makes things clearer to you. Could you send a PR?

**Comment by Robylyon93** [comment]
I think it's clearer, thanks a lot!
I'll send a PR. :)
