### ISSUE TITLE
Is there a backbone implementation of Xception?

### ISSUE THREAD

**Issue by songyuc** [pytorch/vision#1860]
Hi, guys,
I want to know if there is a backbone implementation of Xception?

Any answer or idea will be appreciated!

**Comment by fmassa** [comment]
Hi,

torchvision does not provide an Xception implementation, but we do provide other models that perform comparably (or even better), like ResNeXt.

You can find an implementation of Xception in https://github.com/Cadene/pretrained-models.pytorch/tree/master/pretrainedmodels/models
