### ISSUE TITLE
Two CUDA memory issues with Faster/Mask R-CNN

### ISSUE THREAD

**Issue by AlexTS1980** [pytorch/vision#1867]
1) When using CUDA10: 
`RuntimeError: /pytorch/torch/csrc/jit/fuser/cuda/fused_kernel.cpp:202: a PTX JIT compilation failed
`
I solved it by switching to CUDA9.0, but then another one pops up:
2) `RuntimeError: CUDA out of memory. Tried to allocate 54.00 MiB (GPU 0; 14.73 GiB total capacity; 13.64 GiB already allocated; 27.88 MiB free; 279.23 MiB cached)

`
The don't point to a specific error, so I can't track it. Also some applications using Mask/Faster R-CNN actually work correctly. What can I do?

**Comment by fmassa** [comment]
Hi,

Is this when using the torchscripted version of maskrcnn?

The models in faster rcnn use a lot of memory, specially during training, so it would be good to know what you are trying to do (training / inference) so that we know a bit more what the problem is.

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
