### ISSUE TITLE
It seems there is no upsampling operations in the implementation of Deeplabv3?

### ISSUE THREAD

**Issue by songyuc** [pytorch/vision#1869]
Hi, guys,
I am learning about the the implementation of Deeplabv3 today,
and I find that it seems, there is no upsampling operations in deeplabv3.py,
so where is the upsampling operations of Deeplabv3 model?

Any answer or idea will be appreciated!

**Comment by fmassa** [comment]
Hi,

The upsampling is present in the base class, see https://github.com/pytorch/vision/blob/819b2e9f39648711ab06562fc8f03ad001cf10be/torchvision/models/segmentation/_utils.py#L25

Let us know if you have further questions!
