### ISSUE TITLE
Unexpected behavior of torchvision.ops.nms

### ISSUE THREAD

**Issue by viniciusarruda** [pytorch/vision#1870]
Following the example below and looking the nms [source code](https://github.com/pytorch/vision/blob/e2a8b4185e2b668b50039c91cdcf81eb4175d765/torchvision/csrc/cpu/nms_cpu.cpp), I expected a `NaN` error, as the intersection and union will be zero.

    import torchvision  # torchvision==0.5.0+cpu
    import torch        # torch==1.4.0+cpu

    boxes = [[0.0, 0.0, 1.0, 1.0],
             [2.0, 1.0, 1.0, 2.0]]

    boxes = torch.tensor(boxes)
    scores = torch.tensor([1., 0.5])

    keep = torchvision.ops.nms(boxes, scores, 0.7)

If this same example is used with [this](https://github.com/rbgirshick/fast-rcnn/blob/master/lib/utils/nms.py) nms implementation (removing the +1 from the source code to be equivalent to the torchvision implementation), it raises a `NaN` error as expected.

Am I missing something ?
Thanks.

**Comment by fmassa** [comment]
Hi,

Why would you expect a NaN in the implementation (which I would consider as a problem in the implementation)? Note that we don't clamp the area to be > 0, which makes it robust to degenerate boxes like in your case, see https://github.com/pytorch/vision/blob/e2a8b4185e2b668b50039c91cdcf81eb4175d765/torchvision/csrc/cpu/nms_cpu.cpp#L21

I'm closing the issue as such, but let me know if you have further questions!

**Comment by viniciusarruda** [comment]
Hi, 

Thanks for the reply, unfortunately I still have my doubt.
Let's track my doubt:

https://github.com/pytorch/vision/blob/e2a8b4185e2b668b50039c91cdcf81eb4175d765/torchvision/csrc/cpu/nms_cpu.cpp#L21

considering the boxes provided when I opened the issue, after the above line:

    (1.0 - 0.0) * (1.0 - 0.0) -> areas[0] == 1.0    (next, instanced as iarea)
    (1.0 - 2.0) * (2.0 - 1.0) -> areas[1] == -1.0   (next, instanced as areas[j])

then, following the code below:

https://github.com/pytorch/vision/blob/e2a8b4185e2b668b50039c91cdcf81eb4175d765/torchvision/csrc/cpu/nms_cpu.cpp#L55-L63

    auto xx1 = std::max(0.0, 2.0); -> 2.0
    auto yy1 = std::max(0.0, 1.0); -> 1.0
    auto xx2 = std::min(1.0, 1.0); -> 1.0
    auto yy2 = std::min(1.0, 2.0); -> 1.0

    auto w = std::max(0.0, 1.0 - 2.0); -> 0.0
    auto h = std::max(0.0, 1.0 - 1.0); -> 0.0

    auto inter = 0.0 * 0.0;                -> 0.0
    auto ovr = 0.0 / (1.0 + (-1.0) - 0.0);  -> 0.0/0.0  -> ??? # Here is my doubt!

I made [this](https://gist.github.com/viniciusarruda/e1e3c3bf1096b9f404fa2caac83288d5) gist with two implementations, the first is a numpy version based on [this](https://github.com/pytorch/vision/blob/e2a8b4185e2b668b50039c91cdcf81eb4175d765/torchvision/csrc/cpu/nms_cpu.cpp) implementation and the second in [this](https://github.com/rbgirshick/fast-rcnn/blob/master/lib/utils/nms.py) implementation withou the `+1` to be consistent.
Note the code output at the end of the file in the comments. 
For the first code, it outputs `RuntimeWarning: invalid value encountered in double_scalars` and `keep = [0, 1]`. For the second code, it outputs ` RuntimeWarning: invalid value encountered in true_divide` and `keep = [0]`. 
The `torchvision.ops.nms()` outputs `keep = [0, 1]` as the first example and no warning or error is raised. 
Is the warning being silenced or am I still missing something?

Thanks.

**Comment by fmassa** [comment]
Thanks for the detailed example.

Indeed, the IoU between those boxes is `nan`. In C++, `0.f / 0.f` is a well-defined operation for floating points, and it doesn't raise an error (nor warning, it would be too expensive).
As such, in the following part, `nan > threshold` is always `False`, and the code continues.

There are a few options here:
- raise an error if the user pass degenerate boxes -- could lead to bad user experience?
- gracefully handle degenerate boxes, by removing them in the nms -- could be unintuitive as they do not satisfy the nms condition
- gracefully handle degenerate boxes, keeping them -- the current behavior in torchvision

IMO, I think that the current default behavior is fairly reasonable. Do you have an use-case where it is actually not the case?

**Comment by viniciusarruda** [comment]
Now I got the point!

Sure, I agree that gracefully handling degenerate boxes by keeping them is the best solution.

I'm sorry for lengthening this issue, I am already satisfied with the answer, but I found some answers ([here](https://stackoverflow.com/questions/42926763/the-behaviour-of-floating-point-division-by-zero) and [here](https://stackoverflow.com/questions/4745311/c-division-by-0)) that contradict and confused me regarding the behavior of dividing by zero.

I tested this code (consider `a`, `b` and `c` as intersections of certain boxes):

    #include <iostream>
    int main()
    {
        double a = 1.0 / 0;
        double b = -1.0 / 0;
        double c = 0.0 / 0;
        std::cout << (a > 0.7); // 1
        std::cout << (b > 0.7); // 0 
        std::cout << (c > 0.7); // 0
        std::cout << a << b << c; // +inf -inf -nan
    }

(I was wondering about the negative `NaN` and [this](https://stackoverflow.com/questions/21349847/positive-vs-negative-nans) question justifies it)

Despite the `c++` code above shows that `+inf` can produce a true value, the case where the intersection is positive and the union is zero is impossible to occur.
Also, if a given box is degenerate, its intersection with other box regardless if it is great or degenerate becomes zero, yielding a zero IoU.
So, regardless of the behavior of C++ in this case, the behavior of this implementation is always to keep the degenerate boxes and, due to the back-propagation and optimization procedure, this cases are encouraged to disappear (at least in the Fast/Faster R-CNN IMO), justifying that gracefully handling degenerate boxes by keeping them is the best solution.

**Comment by fmassa** [comment]
Your reasoning seems correct, and looks like the behavior of division-by-zero might not be specified in the C++ standard, but is instead compiler-dependent. Good to know :-)
