### ISSUE TITLE
`aligned` flag in ROIAlign

### ISSUE THREAD

**Issue by zsef123** [pytorch/vision#1871]
In [Detectron2](https://github.com/facebookresearch/detectron2), they got the `alignd` flag in ROIAlign.

It's about pixel shift, More details in [docstring](https://github.com/facebookresearch/detectron2/blob/master/detectron2/layers/roi_align.py#L51)

Are you planning on going forward about this flag?
Or can I PR?

**Comment by fmassa** [comment]
I think adding a `aligned` flag to `RoIAlign` makes sense and would be a good contribution.

Also, ccing @ppwwyyxx and @rbgirshick as they might be interested in having those available in torchvision

**Comment by rbgirshick** [comment]
I think it would be great to add this feature to torchvision. Then I think we should be able to switch to using it in D2 instead of a custom implementation.
