### ISSUE TITLE
Shouldn't have a `+1` in the NMS implementation for the boxes width/height computation ?

### ISSUE THREAD

**Issue by viniciusarruda** [pytorch/vision#1872]
The standard is to have a bounding box defined as quoted [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/utils/boxes.py#L23).

But in the NMS [source code](https://github.com/pytorch/vision/blob/e2a8b4185e2b668b50039c91cdcf81eb4175d765/torchvision/csrc/cpu/nms_cpu.cpp), there is no `+1` when computing the areas and intersection values. This also leaves a bug in the case of getting `union = 0`, raising a `NaN` error when computing the `iou`.

If the code is correct, what am I missing ? Shouldn't the [documentation](https://pytorch.org/docs/stable/torchvision/ops.html#torchvision.ops.nms) explain this better ?

Thanks.

**Comment by bmanga** [comment]
Same in the [cuda implementation](https://github.com/pytorch/vision/blob/e2a8b4185e2b668b50039c91cdcf81eb4175d765/torchvision/csrc/cuda/nms_cuda.cu#L17).

**Comment by fmassa** [comment]
Hi,

Great questions!

We have answered those questions in https://github.com/pytorch/vision/pull/826#issuecomment-481714113 .

We handle `NaN` in the implementation by not clamping the area to zero, but if you do find an example where this fails please let us know!

Let us know if you have further questions!

**Comment by bmanga** [comment]
@fmassa I think it would make sense to specify in the documentation (or somewhere) that (x1, y1) is inclusive and (x2, y2) is not. That would be simpler than trying to pin it as working with continuous coordinates IMO (that's what OpenCV also does).

**Comment by fmassa** [comment]
@bmanga I think we can reference in the documentation the discussion thread in the attached link I sent, this way users have the full picture.

**Comment by bmanga** [comment]
@fmassa Agreed, a quick explanation + link would be good. I can create a PR if you'd like.

**Comment by fmassa** [comment]
Yes please!
