### ISSUE TITLE
So, what is the meaning for DeepLabHead in deeplabv3.py

### ISSUE THREAD

**Issue by songyuc** [pytorch/vision#1878]
Hi guys,
I am implementing the deeplabv3+, imitating the pattern of deeplabv3.py,
but I don't quite understand the meaning for DeepLabHead,
so do I need to put the upsampling operations in the DeepLabHead?

Any answer and idea will be appreciated!

**Comment by fmassa** [comment]
Hi,

In current implementation, the upsampling is done outside of `DeepLabHead`, see https://github.com/pytorch/vision/blob/819b2e9f39648711ab06562fc8f03ad001cf10be/torchvision/models/segmentation/_utils.py#L25

Let us know if you have further questions~

**Comment by songyuc** [comment]
@fmassa , hi, Fancisco.
Thanks sincerely for your guides!
