### ISSUE TITLE
Torchvision NMS description

### ISSUE THREAD

**Issue by sharifza** [pytorch/vision#1883]
I think here should be  `boxes with IoU >= iou_threshold`. Is this only a documentation typo and the cuda function called here is actually correctly implemented?

https://github.com/pytorch/vision/blob/bf8595798eaccbaffb6c04db11406426eb1b3800/torchvision/ops/boxes.py#L22

**Comment by sharifza** [comment]
I just noted that this was not the master branch. My bad.

**Comment by fmassa** [comment]
Yes, this has been fixed in https://github.com/pytorch/vision/pull/1614 , thanks for the report!
