### ISSUE TITLE
Pre-trained segmentation models can't load state dicts

### ISSUE THREAD

**Issue by devanshuDesai** [pytorch/vision#1891]
<img width="1024" alt="Screen Shot 2020-02-16 at 7 51 57 PM" src="https://user-images.githubusercontent.com/37163544/74622526-07b99080-50f6-11ea-8483-bc891aeb5f3a.png">

**Comment by MrGrayCode** [comment]
You have specified `num_classes=512` in the function whereas the pretrained FCN-Resnet101 model only has 21 classes. This causes the error.

If you wish to use transfer learning on some other dataset you could load the pretrained model first and then modify the last couple of layers according to your task.

**Comment by fmassa** [comment]
Exactly as @MrGrayCode described, thanks @MrGrayCode for the help! This is the standard behavior for all models in torchvision.

Let us know if you have further questions
