### ISSUE TITLE
Can I use the IntermediateLayerGetter function for my customized backbone network?

### ISSUE THREAD

**Issue by songyuc** [pytorch/vision#1894]
Hi, guys,
I am reimplementing DeepLabV3+ model these days,
and I need to return some of the intermediate layers from my customized backbone network, 
and I found the `IntermediateLayerGetter` function with the similar effect.
So I am wondering if I can use  the `IntermediateLayerGetter` function to get the intermediate layers from my customized backbone?

Any idea or answer will be appreciated!

**Comment by fmassa** [comment]
Hi,

I believe we have answered your question in https://github.com/pytorch/vision/issues/1895#issuecomment-590911388

Let us know if you have further questions and sorry for the delay in replying!
