### ISSUE TITLE
Why the inplace in the ReLU in deeplabv3.py is not set True?

### ISSUE THREAD

**Issue by songyuc** [pytorch/vision#1900]
Hi guys,
I am reproducing DeepLabV3+ these days, and I learning about the code of [deeplabv3.py](https://github.com/pytorch/vision/blob/2f64dd90e14fe5463b4e5bd152d56e4a6f0419de/torchvision/models/segmentation/deeplabv3.py).
And I found that some ReLUs in this code don't use "inplace = True", like,
```python
def __init__(self, in_channels, atrous_rates):
        super(ASPP, self).__init__()
        out_channels = 256
        modules = []
        modules.append(nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU()))

        rate1, rate2, rate3 = tuple(atrous_rates)
        modules.append(ASPPConv(in_channels, out_channels, rate1))
        modules.append(ASPPConv(in_channels, out_channels, rate2))
        modules.append(ASPPConv(in_channels, out_channels, rate3))
        modules.append(ASPPPooling(in_channels, out_channels))

        self.convs = nn.ModuleList(modules)

        self.project = nn.Sequential(
            nn.Conv2d(5 * out_channels, out_channels, 1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(),
            nn.Dropout(0.5))
```
So what is the consideration of not using "inplace = True" here?

Any answer or idea  will be appreciated!

**Comment by fmassa** [comment]
Hi,

Sorry for the delay in replying.

We could have used in-place ReLU, there is no particular reason why we haven't used it.

Let us know if you have further questions!
