### ISSUE TITLE
A weird problem: "No module named 'torchvision.models'; 'torchvision' is not a package"

### ISSUE THREAD

**Issue by TengFeiHan0** [pytorch/vision#1912]

**Comment by fmassa** [comment]
Let us know if you are still facing issues. This probably means that you had some issues installing torchvision, or that you were using the wrong environment, which didn't contain torchvision

**Comment by TengFeiHan0** [comment]
@fmassa Hi, I didn't solve above problem, the original problem I posted at [here](https://discuss.pytorch.org/t/no-module-named-torchvision-torchvision-is-not-a-package/70811) , after that, I choose to make image augmentation via opencv. 

As for this question, every time I try to solve this problem, I will create a virtual envs and test the versions of pytorch and torchvision. everything was OK.
