### ISSUE TITLE
Missing new line in the docstring

### ISSUE THREAD

**Issue by cijad** [pytorch/vision#1921]
## 📚 Documentation

There is a missing new line in the docstring for `torchvision.transforms.functional.crop`.
Source code link: [https://pytorch.org/docs/stable/_modules/torchvision/transforms/functional.html#crop](https://pytorch.org/docs/stable/_modules/torchvision/transforms/functional.html#crop)
![pytorch_before_PR](https://user-images.githubusercontent.com/8884008/75461442-1704cd80-5983-11ea-9430-bc6df033b8d5.png)

**Comment by fmassa** [comment]
Fixed with #1922 thanks @cijad!
