### ISSUE TITLE
module 'torchvision' has no attribute '__version__' [0.4.2]

### ISSUE THREAD

**Issue by duskybomb** [pytorch/vision#1925]
## To Reproduce

1. `print("Torchvision Version: ",torchvision.__version__)`

AttributeError: module 'torchvision' has no attribute '__version__'

## Environment

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): pytorch: 1.3.1, torchvision: 0.4.2
 - OS (e.g., Linux): Ubuntu 19.10
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): conda
 - Python version: 3.7
 - CUDA/cuDNN version: 1.01

**Comment by fmassa** [comment]
Hi,

Can you try updating to version 0.5.0, and also update PyTorch to 1.4.0?

This works for me locally.

I'm closing the issue, but let us know if this still persists for you on the last version.
