### ISSUE TITLE
Support for different pooling options with Faster R-CNN

### ISSUE THREAD

**Issue by FHellmann** [pytorch/vision#1926]
I've been trying to setup a Faster R-CNN network to detect lesions on CT images.

Therefor I wanted to use the FasterRCNN class which is provided by torchvision. However, I've noticed that the framework is very great except for the supported pooling (roi_box_pooling). The pooling only allows a [MultiScaleRoIAlign](https://github.com/pytorch/vision/blob/master/torchvision/models/detection/faster_rcnn.py#L168). Is it possible to use the MultiScaleRoIAlign for any use-case?

I wanted to setup my network like it is described in this [project](https://github.com/chenyuntc/simple-faster-rcnn-pytorch):
![Diagram](https://github.com/chenyuntc/simple-faster-rcnn-pytorch/blob/master/imgs/model_all.png?raw=true)

That's my idea so far:
```python
class BoxHead(torch.nn.Module):
    def __init__(self, vgg):
        super(BoxHead, self).__init__()
        self.classifier = torch.nn.Sequential(*list(vgg.classifier._modules.values())[:-1])

    def forward(self, x):
        x = x.flatten(start_dim=1)
        x = self.classifier(x)
        return x

# VGG16 backbone
vgg = vgg16(pretrained=True)
backbone = vgg.features[:-1]
for layer in backbone[:10]:
    for p in layer.parameters():
        p.requires_grad = False
backbone.out_channels = 512

box_head = BoxHead(vgg)

# RPN - Anchor Generator
anchor_generator = AnchorGenerator(sizes=((8, 16, 32),), aspect_ratios=((0.5, 1.0, 1.5),))

# Head - Box RoI pooling
roi_pooler = MultiScaleRoIAlign(featmap_names=['0'], output_size=7, sampling_ratio=2)

# Faster RCNN - Model
model = FasterRCNN(
    backbone=backbone,
    min_size=224, max_size=224,
    rpn_anchor_generator=anchor_generator,
    box_roi_pool=roi_pooler,
    box_head=box_head,
    box_predictor=FastRCNNPredictor(4096, num_classes=2)
)
```

**Comment by fmassa** [comment]
Hi,

You can use `MultiScaleRoIAlign` with a single scale (as in your illustration). There is an example on how to do it in the Object Detection tutorial, check https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html#modifying-the-model-to-add-a-different-backbone

**Comment by FHellmann** [comment]
@fmassa thank you!

The implementation does work but the detection of the lesions never reached more than 0.12 for the box score. However, I also experience some trouble with the GPU support of this model. Even though I activate the cuda mode with ‘model.to(cudadevice)’ or ‘model.cuda()’ the call is not passed through to all sub-modules of the Faster R-CNN model. That results in the model running on the CPU very slowly. I even tried to pass the move of the models to cuda through, which worked by calling them after the model was setup and called the previous mentioned methods. Anyway, the result remains the same. I can see on my task manager, that the application allocates GPU memory and the tensors device is ‘cuda:0’, but never executes anything on the cuda cores. Any ideas?

**Comment by fmassa** [comment]
Hi,

Training Faster R-CNN takes a long time, so maybe you might need more iterations before you can see it working well.

Also, I'm not sure I understand the CPU / CUDA problem you mentioned. If your code was able to run on the CPU, then all its modules were on CPU because PyTorch doesn't do automatic device casting.
