### ISSUE TITLE
The kernel size of third branch of Inception module of GoogLeNet

### ISSUE THREAD

**Issue by avalonliberty** [pytorch/vision#1927]
Hi - I was reading the model of your GoogLeNet implementation, and I found that third branch of Inception module has a kernel size 3 instead of 5. I believe that this is an typo since the argument is 5x5red and 5x5 as well.

**Comment by pmeier** [comment]
Duplicate of #906. @fmassa I'll send a PR with a code comment later, since it appears that has never been done.

**Comment by cpuhrsch** [comment]
Closed due to duplicate
