### ISSUE TITLE
Summary of TorchScript and ONNX support

### ISSUE THREAD

**Issue by MLaurenceFournier** [pytorch/vision#1930]
Hi,
Is there a summary somewhere of the current state of support for TorchScript and ONNX by the models in this repo? A complete summary would include the version of support for both CPU and GPU.

I'm mostly interested in FasterRCNN but I got confused looking around the related issues. I suppose a general summary could save time to other end users.

**Comment by fmassa** [comment]
Hi,

TorchScript is supported for all models of torchvision, including Faster R-CNN and Mask R-CNN.

For ONNX, all models are also supported, with the caveat that for Faster R-CNN (and Mask/Keypoint R-CNN) your input shouldn't change the dimensions / batch size after it has been exported. This limitation is currently being worked on.

Let us know if you need any further information.

**Comment by MLaurenceFournier** [comment]
Thank you!

Do you know since which version that support is provided? Personally, I'm still using version 0.4.2.

**Comment by fmassa** [comment]
@MLaurenceFournier this is supported since version 0.5.0, see the release notes https://github.com/pytorch/vision/releases
