### ISSUE TITLE
torchvision.io.video.read_video pts units for video only

### ISSUE THREAD

**Issue by tmabraham** [pytorch/vision#1931]
If the `pts_unit='pts'` for the function `torchvision.io.video.read_video` we get a warning:

    The pts_unit 'pts' gives wrong results and will be removed in a follow-up version. 
    Please use pts_unit 'sec'.

Looking through an [earlier issue](https://github.com/pytorch/vision/issues/1221) regarding this, the usage of `pts` is only wrong if accurate AV sync is needed. So does that mean if I only care about the video content and not the audio (which is the case for many problems like video classification), then will it be fine to use `pts`? I ask because often we are concerned about only taking a certain number of frames, and using `pts` allows us to do that without loading in the whole video first. 

If the usage of `pts` is only wrong if AV sync is desired, then should that be made clear in the documentation and in the warnings? Also, shouldn't the `pts` option still be available in future versions, while `sec` could be the new default?

**Comment by bjuncek** [comment]
@tmabraham yeah - all the models were trained using `pts` and in principle there is nothing wrong with it if you don't care about seeking into a particular parts of the video and accurate AV sync (and if you do, you're probably using `read_video` function which has `pts_unit` option).


We trained all benchmark models using the `pts` and the results are comparable to the benchmarks. 

I believe @fmassa was planning to make `sec` the default at some point for 0.5 release but it got lost amongst other tasks.

**Comment by tmabraham** [comment]
@bjuncek Thanks for the clarification. To confirm, the 'pts' option will not be removed in a future release?

**Comment by bjuncek** [comment]
My understanding is that it will remain as is, the only thing to change will be the default option.

**Comment by tmabraham** [comment]
@bjuncek Sounds good. Thanks!
