### ISSUE TITLE
error

### ISSUE THREAD

**Issue by buxpeng** [pytorch/vision#1933]
Sorry to bother you here,I saw your comment at maskrcnn-benchmark, and I encountered the following error, even using boxlist[[0]] is the same error, can you help me please? Thank you!
![image](https://user-images.githubusercontent.com/53242456/75760743-bc98b200-5d72-11ea-800f-a6cc055db20b.png)

**Comment by fmassa** [comment]
Hi,

This is an error in `maskrcnn-benchmark`, and not in `torchvision`.

But to answer your question, you can probably workaround this limitation by doing
```python
bbox[[0]]
```
instead of
```python
bbox[0]
```

**Comment by buxpeng** [comment]
sorry，I used it wrong，Can you help me？my torch is 1.0 no use cuda ,The code I run is here： https://github.com/facebookresearch/vilbert-multi-task/blob/master/script/extract_features.py
![image](https://user-images.githubusercontent.com/53242456/75943938-5bd3bb80-5ed1-11ea-9c2d-1127162b46c2.png)

**Comment by fmassa** [comment]
You should open an issue in https://github.com/facebookresearch/vilbert-multi-task/ most probably, as it's not related to torchvision, and I'm not sure I'd be able to help you with your question (I've never seen that repo before)
