### ISSUE TITLE
torchvision.models.detection.fasterrcnn_resnet50_fpn has loss_rpn_box_reg exploding to nan after evaluation

### ISSUE THREAD

**Issue by dsandii** [pytorch/vision#1934]
## 🐛 Bug / Misuse?
I'm attempting to use `torchvision.models.detection.fasterrcnn_resnet50_fpn` on a custom dataset, following along with the [Detection Finetuning Tutorial](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html) where applicable.

However, I consistently have an issue where the loss of `loss_rpn_box_reg` appears to rapidly explode, but _only_ after the first epoch has completed **(edit: the culprit now appears to be the call to the evaluation function).**

I've ruled out every annotation / dataloading issue I can think of (no boxes w/ non-positive dims or out-of-bounds coords, etc).
I've also (hopefully) ruled out issues with the RPN by following the steps to replace the `AnchorGenerator` and `RPNHead` outlined in #978 
```
    rpn_anchor_generator = AnchorGenerator(sizes=config.RPN_ANCHOR_SIZES,
                                           aspect_ratios=config.RPN_ANCHOR_ASPECT_RATIOS)
    rpn_head = RPNHead(in_channels=model.backbone.out_channels,
                       num_anchors=rpn_anchor_generator.num_anchors_per_location()[0])
    model.rpn.anchor_generator = rpn_anchor_generator
    model.rpn.head = rpn_head
```

And, if it's relevant, replaced the `RoIHeads` box predictor:
```
    box_predictor = FastRCNNPredictor(in_channels=model.roi_heads.box_predictor.cls_score.in_features,
                                      num_classes=len(dataset_util.ClassLabelEnum) + 1)
    model.roi_heads.box_predictor = box_predictor
```
I've also been tinkering with my choice of optimizer & scheduler as well as trying to drastically lower LR or change batch size, just to see if anything seems to impact it (to no avail).

Below is a stack trace of this behavior on a small dummy subset. The behavior is similar on the full dataset, with `loss_rpn_box_reg` apparently exploding to `nan` shortly after the first epoch.
```
Epoch: [0]  [0/5]  eta: 0:00:03  lr: 0.001254  loss: 4.8643 (4.8643)  loss_classifier: 3.7656 (3.7656)  loss_box_reg: 0.0778 (0.0778)  loss_objectness: 0.6919 (0.6919)  loss_rpn_box_reg: 0.3290 (0.3290)  time: 0.7243  data: 0.1862  max mem: 2508
Epoch: [0]  [4/5]  eta: 0:00:00  lr: 0.005000  loss: 2.9177 (3.2553)  loss_classifier: 1.8250 (2.1365)  loss_box_reg: 0.1284 (0.1319)  loss_objectness: 0.6914 (0.6905)  loss_rpn_box_reg: 0.3255 (0.2964)  time: 0.4570  data: 0.0405  max mem: 2776
Epoch: [0] Total time: 0:00:02 (0.4618 s / it)
creating index...
index created!
Test:  [0/5]  eta: 0:00:01  model_time: 0.0841 (0.0841)  evaluator_time: 0.0014 (0.0014)  time: 0.2295  data: 0.1396  max mem: 2776
Test:  [4/5]  eta: 0:00:00  model_time: 0.0819 (0.0821)  evaluator_time: 0.0007 (0.0008)  time: 0.1168  data: 0.0296  max mem: 2776
Test: Total time: 0:00:00 (0.1209 s / it)
Averaged stats: model_time: 0.0819 (0.0821)  evaluator_time: 0.0007 (0.0008)
Accumulating evaluation results...
DONE (t=0.01s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
Epoch: [1]  [0/5]  eta: 0:00:03  lr: 0.005000  loss: 17.6448 (17.6448)  loss_classifier: 0.4119 (0.4119)  loss_box_reg: 0.0663 (0.0663)  loss_objectness: 0.6992 (0.6992)  loss_rpn_box_reg: 16.4674 (16.4674)  time: 0.6068  data: 0.1749  max mem: 2776
Loss is nan, stopping training
{'loss_classifier': tensor(0.4476, device='cuda:0', grad_fn=<NllLossBackward>), 'loss_box_reg': tensor(0.0805, device='cuda:0', grad_fn=<DivBackward0>), 'loss_objectness': tensor(0.6914, device='cuda:0', grad_fn=<BinaryCrossEntropyWithLogitsBackward>), 'loss_rpn_box_reg': tensor(nan, device='cuda:0', grad_fn=<DivBackward0>)}
```

Could I be horribly misusing the model API or incorrectly setting any hparams? This is my first time really working with `torch` & `torchvision` in-depth, so any and all suggestions are hugely appreciated.

## Environment
Bare-metal + conda environment, single GPU set-up.
 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): **1.4.0 / 0.5.0**
 - OS (e.g., Linux): **Ubuntu 18.04**
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): **pip (from pypi) in a conda environment**
 - Python version: **3.6.9**
 - CUDA/cuDNN version: **Driver's CUDA version 10.2, environment's cudnn==7.6.0 (build==cuda10.1_0), cudatoolkit==10.1.243**
 - GPU models and configuration: **GTX 1080Ti**

**Comment by dsandii** [comment]
After further experimenting, this appears to actually only happen after running an evaluation step exactly as outlined in the tutorial.
`engine.evaluate(model, valid_loader, device=device)`
This doesn't make much sense to me, but I'll be looking into it.

**Comment by dsandii** [comment]
Could this be some low-level CUDA issue with multiprocessing and/or moving modules between CPU and GPU caused by my environment?

I was able to train a model w/o training-time evaluation and the results look good, so everything otherwise looks right.

**Comment by dsandii** [comment]
I've encountered what could be a related issue (there seems to be some overlap):

When trying to trace my checkpoint for export using `torch.jit.trace(model, image)` it fails with the following stack trace which seems to indicate some intermediate RPN tensors are on the CPU:

```
/home/dakoda/anaconda3/envs/torch/lib/python3.6/site-packages/torch/tensor.py:461: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
Traceback (most recent call last):
  File "/home/dakoda/PycharmProjects/dev_torch_detection_base/utility/export.py", line 23, in <module>
    export_model_trace(CKPT_PATH, IMG_PATH)
  File "/home/dakoda/PycharmProjects/dev_torch_detection_base/utility/export.py", line 15, in export_model_trace
    traced = torch.jit.trace(model, image)
  File "/home/dakoda/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 882, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/dakoda/anaconda3/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1034, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "/home/dakoda/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/dakoda/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/dakoda/anaconda3/envs/torch/lib/python3.6/site-packages/torchvision/models/detection/generalized_rcnn.py", line 70, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/dakoda/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/dakoda/anaconda3/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/dakoda/anaconda3/envs/torch/lib/python3.6/site-packages/torchvision/models/detection/rpn.py", line 472, in forward
    boxes, scores = self.filter_proposals(proposals, objectness, images.image_sizes, num_anchors_per_level)
  File "/home/dakoda/anaconda3/envs/torch/lib/python3.6/site-packages/torchvision/models/detection/rpn.py", line 379, in filter_proposals
    top_n_idx = self._get_top_n_idx(objectness, num_anchors_per_level)
  File "/home/dakoda/anaconda3/envs/torch/lib/python3.6/site-packages/torchvision/models/detection/rpn.py", line 359, in _get_top_n_idx
    r.append(top_n_idx + offset)
RuntimeError: expected device cuda:0 but got device cpu

Process finished with exit code 1
```

To be sure, I iterated through my model's named params to ensure none weren't on GPU, and nothing seemed wrong.

**Comment by fmassa** [comment]
Hi @dsandii,

Sorry for the delay in replying.

So, my first guess would be that the learning rate that you are setting is too high. This doesn't happen for the first epoch because we do learning rate warmup in the first epoch, but the second epoch already sees the full learning rate.

If that's not the issue, and your dataset is properly setup (all boxes are valid), then I don't know what else it would be, but I'm pretty sure it's probably one of the above.

Let me know if you have further questions, but for now there doesn't seem to be anything actionable on our side, so I'm closing the issue.

**Comment by dsandii** [comment]
@fmassa Thanks for replying. However, I don't believe it's your first guess is the problem.

As I mentioned above, if I comment out the evaluation I'm able to train the model just fine, and it appears to converge quite beautifully actually. The results look really good.

So I'm not convinced the LR or other hparams are the culprit. The `loss_rpn_box_reg` _only_ seems to start exploding after I allow `engine.evaluate(...)` to run.
