### ISSUE TITLE
Comments for anchor generator class

### ISSUE THREAD

**Issue by SohamTamba** [pytorch/vision#1937]
## 🚀 Feature
Add comments to the AnchorGenerator class.

## Motivation

Make the code easier to understand through commenting.

## Pitch

I suggest we add comments to the AnchorGenerator class to make the code easier to understand.

## Additional context

I'm trying to train a network for object detection and spent quite a few hours trying to understand the [Anchor Generator Class](https://github.com/pytorch/vision/blob/b2e95657cd5f389e3973212ba7ddbdcc751a7878/torchvision/models/detection/rpn.py#L31). If the community is interested, I could add comments to the class to make it easier to understand. This would reduce the difficulty of contributing to PyTorch.

**Comment by fmassa** [comment]
Yes please! If you could add more comments it would be great!
