### ISSUE TITLE
Change `transform` to `data_transform`, and add the `both_transform` argument to all datasets.

### ISSUE THREAD

**Issue by acgtyrant** [pytorch/vision#196]
http://pytorch.org/docs/0.1.12/torchvision/datasets.html#torchvision-datasets says:

> transform - a function that takes in an image and returns a transformed version
> common stuff like ToTensor, RandomCrop, etc. These can be composed together with transforms.Compose (see transforms section below)
> target_transform - a function that takes in the target and transforms it. For example, take in the caption string and return a tensor of word indices.

However, if we change `transform` to `data_transform`, it will be more matched to `target_transform`. And they are not enough, for example, we can not use only RandomHorizontalFlip for data while the target is coordinates for object detecion, we have to flip data and target at the same time, so it is useful if we add `both_transform` as the new arguments for all datasets.

```
def __init__(self, ...,
        data_transform=None, target_transform=None, both_transform=None):
    ...

def __getitem__(self, index):
    ...
    if self.data_transform is not None:
        data = self.data_transform(data)

    if self.target_transform is not None:
        target = self.target_transform(target)

    if self.both_transform is not None:
        data, target = both_transform(data, target)

    return data, target
```

**Comment by alykhantejani** [comment]
Hi @acgtyrant there is currently a discussion in #230 discussing how best to extend the transforms to handle these cases. 

@fmassa perhaps we should close this and focus the conversation on #230?

**Comment by fmassa** [comment]
Closing and redirecting the discussion to #230.
