### ISSUE TITLE
addition of computer generated reality dataset to torchvision

### ISSUE THREAD

**Issue by vainaijr** [pytorch/vision#1962]
## 🚀 Feature

in the current scenario, all the datasets that torchvision has are of physical reality, there is no dataset of computer generated reality, I think a bit more priority needs to be given to computer generated reality dataset.

## Motivation

computer generated reality resolution is doubling, so people spend more and more time in such realities, for example, game reality or watching animated movie.
so, we can predict that datasets of the future would be of these computer generated realities.

## Pitch

atleast one such dataset should be added to torchvision.
I do not suggest any specific dataset, but I think there should be atleast one, and keep increasing number of computer generated reality datasets in the upcoming years.

**Comment by pmeier** [comment]
In general, we only feature datasets (and models) that have established themselves as standard for their specific case and are widely used. 

I'm not familiar with the datasets you are describing, which makes it hard to assess if its worth to add them. Please provide some links for such datasets and in the same breath citations for prominent papers of this field that use them.
