### ISSUE TITLE
ImageFolder is not working with grayscale images.

### ISSUE THREAD

**Issue by dlmacedo** [pytorch/vision#198]
Dear friends,

It appears that ImageFolder is not working with grayscale images.

For example, I tried to load using ImageFolder the MNIST in png format using CUDA and I got the following error: 
 
> Traceback (most recent call last):
>   File "train.py", line 406, in <module>
>     main()
>   File "train.py", line 181, in main
>     cnn(args.epochs, train_loader, val_loader, model, criterion, optimizer, experiment)
>   File "train.py", line 216, in cnn
>     training_time += train(train_loader, model, criterion, optimizer, epoch)
>   File "train.py", line 276, in train
>     output = model(input_var)
>   File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/dlm/code/deeplearninglab/sem/models/lenet5.py", line 35, in forward
>     x = self.features(x)
>   File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 59, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 64, in forward
>     input = module(input)
>   File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 237, in forward
>     self.padding, self.dilation, self.groups)
>   File "/home/dlm/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 40, in conv2d
>     return f(input, weight, bias)
> RuntimeError: CUDNN_STATUS_BAD_PARAM

**Comment by alykhantejani** [comment]
@dlmacedo sorry for the delayed response. 

Judging by the stack trace, I'm not sure this is an issue with data loading. However, to address your question: `ImageFolder` doesn't load gray images  by default as it converts images to `RGB`. However, if you want
