### ISSUE TITLE
Deformable convolutions for Equirectangular projected images

### ISSUE THREAD

**Issue by palver7** [pytorch/vision#1987]
## 🚀 Feature
PyTorch/TorchVision implementation of EquiConvs, a deformable convolution tailored to process [equirectangularly projected images](https://en.wikipedia.org/wiki/Equirectangular_projection), that is images produced by 360 degrees cameras. 

## Motivation
With 360 degrees cameras or videos, one can capture a spherical 360 degree view, which then is projected to a 2D screen. One of the projection used is the equirectangular projection. This projection introduces distortions near the the edges (top, bottom, left and right) and corners. These distortions can cause unwanted results when these images are processed by ordinary convolutional neural networks.

One of the attempts to rectify this problem is the [EquiConvs by C.Fernandez et, al ](https://arxiv.org/abs/1903.08094) which has been implemented for TensorFlow. EquiConvs was based on and a type of deformable convolution that can take into account the edge and corner distortions of equirectangular projection. The main difference from deformable convolution is that the offsets for the convolution kernel was not learned but fixed according to the relation between the equirectangular images and the spherical images. Because of this, only a simple modification from the  existing deform_conv.py is needed to implement EquiConvs for pytorch and torchvision.  

![diff std deform equirect](https://user-images.githubusercontent.com/42964197/76726909-1fcc1080-6785-11ea-954b-fa429ede717a.png)

## Pitch
360 degree image processing are useful for Robotics and VR, in addition to owners of the 360 cameras.  Neural networks should be able to process them as well as ordinary perspective images. There are several proposals to do this; in addition to the work by C. Fernandez et. al.  there are related works such as [mapped convolutions](https://arxiv.org/abs/1906.11096) and [Kernel Transformer Networks for Compact Spherical Convolution](https://arxiv.org/abs/1812.03115), which indicates active research in this area.  

## Additional context
EquiConvs enable spherical and equirectangular image processing. 

![spherical and equirectangular](https://user-images.githubusercontent.com/42964197/76726877-0aef7d00-6785-11ea-9a1a-b2fd8d85f97b.png)

**Comment by fmassa** [comment]
Hi,

Thanks for the nice explanation, it was very clear!

If I understand it correctly, there is no need to change `DeformConv2d` in torchvision to implement this.

All you need is a function that maps the input into the offsets following the distortion rules that you want, and pass this to `DeformConv2d` I believe.

Here is one (toy) example:
```python
class MyDeformConv(DeformConv2d):
    def compute_offset(self, input):
        h, w = input.shape[-2:]
        grid_w, grid_h = torch.meshgrid(torch.arange(w), torch.arange(h))
        # dummy offsets
        offsets = torch.stack([grid_w.sin(), grid_h.cos()], dim=0)
        # also need to handle batch
        return offsets

    def forward(self, input):
        return super().forward(input, self.compute_offset(input))
```

Let me know what you think, but I believe for now this can live in user code, as it also probably requires having a way to handle the spherical images (which is not currently handled by torchvision).
As such I'm closing the issue but let me know if you think differently.

**Comment by vlordier** [comment]
@fmassa the computation of offsets creates a huge overhead : I am thinking to pre-compute them, using, say a LUT-like approach.
How would you do this ?
