### ISSUE TITLE
Undefined reference to PSROIAlign_forward_cpu

### ISSUE THREAD

**Issue by two-names** [pytorch/vision#1992]
Hi! I want to achieve Inference of the script mask rcnn model on C++.
Following the instructions "Make maskrcnn scriptable" I've install TorchVision and Torch from source.
In Cmake of my application:
find_package(TorchVision REQUIRED)
find_package(Torch REQUIRED)
In cpp:
#include <torch/script.h>
#include <torch/torch.h>
#include <torchvision/vision.h>
#include <torchvision/PSROIAlign.h>

After that I make my example_appp, but got some error:
"In function PSROIAlign_forward(at::Tensor const&, at::Tensor const&, float, int, int, int)': /usr/local/include/torchvision/PSROIAlign.h:32: undefined reference to PSROIAlign_forward_cpu(at::Tensor const&, at::Tensor const&, float, int, int, int)'
CMakeFiles/example-app.dir/example-app.cpp.o: In function PSROIAlign_backward(at::Tensor const&, at::Tensor const&, at::Tensor const&, float, int, int, int, int, int, int, int)': /usr/local/include/torchvision/PSROIAlign.h:76: undefined reference to PSROIAlign_backward_cpu(at::Tensor const&, at::Tensor const&, at::Tensor const&, float, int, int, int, int, int, int, int)'"

What the main reason of the error could be?

**Comment by fmassa** [comment]
@bmanga do you know what the problem might be?

**Comment by bmanga** [comment]
Hi @two-names, did you also do the following in your CMakeListst.txt?
```
target_link_libraries(yourtarget PUBLIC TorchVision::TorchVision)
```

**Comment by two-names** [comment]
Hi @bmanga !
`
project(custom_ops)
set(OpenCV_DIR /opencv-3.4.5/build/install/share/OpenCV/)
find_package(OpenCV REQUIRED)
set(Torch_DIR /torch_install_dir/share/cmake/Torch/)
find_package(Torch REQUIRED)
set(TorchVision_DIR /vision_install_dir/share/cmake/TorchVision/)
find_package(TorchVision REQUIRED)
find_package(Python3 COMPONENTS Development)
add_executable(example-app example-app.cpp)
target_link_libraries(example-app "${TORCH_LIBRARIES}" Python3::Python)
set_property(TARGET example-app PROPERTY CXX_STANDARD 14)
`

I installed 'torch' and 'vision' from repository with DCMAKE_INSTALL_PREFIX:
/vision_install_dir
/torch_install_dir

**Comment by bmanga** [comment]
Can you try changing
```
target_link_libraries(example-app "${TORCH_LIBRARIES}" Python3::Python)
```
to
```
target_link_libraries(example-app PRIVATE "${TORCH_LIBRARIES}" TorchVision::TorchVision Python3::Python)
```
And see if that fixes the fixes the problem?

**Comment by two-names** [comment]
It works!!!
@bmanga , thank you for your help!!!

**Comment by bmanga** [comment]
@two-names no problem :)
Can you close the issue given that it's fixed?

**Comment by fmassa** [comment]
Thanks a lot @bmanga for the help!

What about adding some more documentation on how to build / link projects using torchvision from C++?

**Comment by bmanga** [comment]
@fmassa no worries, I'm happy to help :)
The linking part is covered in the README, but I'm sure a tutorial/self-contained example would help a lot. I can dedicate some time to it this weekend.
Do you have any preferences / ideas on the format?

**Comment by fmassa** [comment]
I think a self-contained example would be a great starting point, we can think about tutorials afterwards.
