### ISSUE TITLE
torchvision_finetuning_instance_segmentation notebook error

### ISSUE THREAD

**Issue by Azer-ai** [pytorch/vision#2014]
Hi

When running pytorch fine tuning instance segmentation tutorial on google colab  I get the error below:

TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    116     try:
--> 117         num = operator.index(num)
    118     except TypeError:

TypeError: 'numpy.float64' object cannot be interpreted as an integer

I would like to use this code as a base for my custommed dataset.

Any advice would be appreciated.

**Comment by wk5ovc** [comment]
Try reinstall pycocotools
``` python
pip install cython
pip install -U 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'
```

**Comment by Azer-ai** [comment]
Hi wk50ovc,

I just ran the tutorial and it worked. Just  a question  were there any changes in the coco repository that caused the issue?

Thanks  for your help : D

**Comment by fmassa** [comment]
Hi @Azer-ai ,

Yes, this was a change in numpy that broke pycocotools, and has been fixed in https://github.com/cocodataset/cocoapi/pull/354 , that's why updating pycocotools fixes it.

**Comment by fmassa** [comment]
And thanks @wk5ovc for the help!
