### ISSUE TITLE
Remove six dependency

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#2015]
Now that we have transitioned to Python3-only, I believe we can remove the uses of `six` and instead use standard libraries / functions from python3.

We should also remove `six` from CI and builds.

**Comment by pmeier** [comment]
I could take that up. As I've never worked with Python2, is there anything that I need to know before I start?

**Comment by fmassa** [comment]
Thanks @pmeier !

I think it should pretty much just be replacing things like
```
from six import ...
```
with the corresponding function in Python3. Let me know if you stumble in any specific issue
