### ISSUE TITLE
Update the doc theme to pytorch_sphinx_theme?

### ISSUE THREAD

**Issue by hologerry** [pytorch/vision#2024]
## 📚 Documentation
The Documentation config in `docs` use the sphinx default theme which is not consistent to pytorch.org website, the build output is not as elegant as the website version.

Website version:
<img width="1491" alt="Screen Shot 2020-03-27 at 18 34 48" src="https://user-images.githubusercontent.com/11660168/77747533-cfdd2b80-7059-11ea-89b7-32f117e5053d.png">

Built version(on Dash):
<img width="1192" alt="Screen Shot 2020-03-27 at 18 33 42" src="https://user-images.githubusercontent.com/11660168/77747558-d9ff2a00-7059-11ea-88cb-7c6b601cb4f7.png">

`PyTorch` on Dash:
<img width="1203" alt="Screen Shot 2020-03-27 at 18 34 19" src="https://user-images.githubusercontent.com/11660168/77747588-e5eaec00-7059-11ea-98d9-4c3ddd697b68.png">

`torchtext` on Dash:
<img width="1201" alt="Screen Shot 2020-03-27 at 18 35 16" src="https://user-images.githubusercontent.com/11660168/77747740-1f235c00-705a-11ea-8403-ce623a96d50b.png">

Could you please update the theme config as `torchtext` or `PyTorch`?

**Comment by fmassa** [comment]
Thanks for opening the issue!

@jlin27 could you have a look?

**Comment by brianjo** [comment]
I'll do a branch pr for this in a few minutes. :)

**Comment by brianjo** [comment]
Here's my PR. Only tested locally. https://github.com/pytorch/vision/pull/2031

**Comment by fmassa** [comment]
Fixed by @brianjo in #2031
