### ISSUE TITLE
Clean up nvcc arch TODO

### ISSUE THREAD

**Issue by xkszltl** [pytorch/vision#2026]
## Bug

https://github.com/pytorch/vision/blob/d45a77d414082bf5ccbf65355354f583d43a40c0/packaging/pkg_helpers.bash#L59-L61

This PR seems landed.
Should we verify and drop TODO?

The current case is, without this line, on non-CUDA machine with `FORCE_CUDA=1`, torchvision will fail to build because torch.cuda.init() will check for cuda device and raise exception.
It can be worked around by setting `TORCH_CUDA_ARCH_LIST` manually, but would be great if we can pick it up from pytorch installation automatically.

**Comment by fmassa** [comment]
Yes, I think this could probably be cleaned up.

ccing @seemethere for thoughts

**Comment by NicolasHug** [comment]
@xkszltl I believe that https://github.com/pytorch/vision/pull/3399 will close this issue, but I'm not sure I understand your use-case:

> The current case is, without this line, on non-CUDA machine with FORCE_CUDA=1, torchvision will fail to build because torch.cuda.init() will check for cuda device and raise exception.

Isn't this expected? I actually get that error with or without the mentioned line.

**Comment by xkszltl** [comment]
Since it is from too long ago, I don't remember all the details. Probably I mean force_cuda is to force build with it, not run with it, but some arch-detection code need to run with it to check? The ultimate goal is to make sure torchvision (with cuda support for running in production machine, not build machine) can build on a cpu-only machine upon a cuda-enabled pytorch
