### ISSUE TITLE
Why does only ToTensor handle numpy arrays?

### ISSUE THREAD

**Issue by hasnainv** [pytorch/vision#204]
Out of all the classes in transforms.py, only ToTensor handles numpy arrays. 
It would be much smoother if all classes handle numpy arrays.

I can make a PR if this is something you guys can accept.

**Comment by alykhantejani** [comment]
Most of the transforms (if not all) handle `PIL` Images, which is a wrapper around numpy arrays. The `ToPILImage` transform can convert a numpy array to an Image and then it would be compatible with all of the transforms.

**Comment by alykhantejani** [comment]
I think it would be better to keep the data wrapped as an `Image` for as long as possible as then we can utilize some metadata such as colorspace etc. We can also then use built in mehtods on the `Image` type to do things like resize or scaling. 

If your data is in numpy format, I suggest adding the `ToPILImage` transform to the start of your `Compose` and this will then convert it correctly for you.

**Comment by fmassa** [comment]
I second what @alykhantejani said, you can seamlessly convert from PILImage to numpy arrays and vice versa, while PILImages have more information about the image (colorspace for example).
