### ISSUE TITLE
Animated dataset

### ISSUE THREAD

**Issue by vainaijr** [pytorch/vision#2042]
Why do PyTorch add no animated dataset?

**Comment by vainaijr** [comment]
I created one issue here, https://github.com/pytorch/vision/issues/1962, I mean addition of computer generated avatar, reality, in general, this includes,

1) Animated character faces
2) Avatars from game reality
3) Avatars from animated movie
4) Computer generated reality non animate objects, like furniture, trees

I ask because resolution of computer generated avatar, reality keep doubling (like 2k to 4k to 8k and so on), while physical reality stay same, that is physical reality objects do not increase in pixel density at the same rate as computer generated reality, so computer generated reality becoming comparable (and beyond) to physical reality fast.
For example,
![image](https://user-images.githubusercontent.com/43755000/78166116-45486200-7487-11ea-8929-f145f4a55d24.png)
so, we see, computer generated avatar like,
![image](https://user-images.githubusercontent.com/43755000/78166189-5b562280-7487-11ea-9b9c-cf56ca19a754.png)
in 2020, and this resolution only doubling.

But in the current state, all datasets in PyTorch of physical reality, no computer generated reality dataset.

**Comment by pmeier** [comment]
@vainaijr In https://github.com/pytorch/vision/issues/1962#issuecomment-597716435 I've requested

> I'm not familiar with the datasets you are describing, which makes it hard to assess if its worth to add them. Please provide some links for such datasets and in the same breath citations for prominent papers of this field that use them.

From what I understand from your above comment, is that there is no such dataset and in turn no research papers that can use them. Thus, I now understand your question now as this: 

> Why doesn't PyTorch **create** a dataset for animated or computer generated images?

The answer is simple: PyTorch does not create any dataset. We don't even host them. `torchvision` "merely" provides an interface for prominent datasets in order to use them conveniently together with `torch`. See the [Disclaimer on Datasets at the bottom of our README](https://github.com/pytorch/vision/blob/master/README.rst):

> [`torchvision`] is a utility library that downloads and prepares public datasets. We do not host or distribute these datasets, vouch for their quality or fairness, or claim that you have license to use the dataset. 

If you want a dataset with the properties you mention, for now you have to compile it yourself. If you have done that it is still [not ready to be included in `torchvision`](https://github.com/pytorch/vision/issues/1962#issuecomment-597716435):

> In general, we only feature datasets (and models) that have established themselves as standard for their specific case and are widely used.

If you achieved this, please fulfill my request at the top of this comment and we will happy to assist you adding the dataset to `torchvision`.

---

@fmassa I think we should close this and keep the discussion in #1962.

**Comment by vainaijr** [comment]
I sorry to not include any link, I create same issue in torchvision, and PyTorch,
so one of them could be closed, I search and found following datasets,
some of these have copyright issues, and require specific permissions to use the dataset,
but I list all that I found, I think atleast one or two computer generated reality dataset
should be added to torchvision in 2020.

Dataset                    Link

Anime related              https://github.com/deeppomf/DeepLearningAnimePapers 
                                     https://www.kaggle.com/mylesoneill/tagged-anime-illustrations

Video Game Driving         https://www.kaggle.com/kmader/labeled-video-game-driving

Pokemon Images             https://www.kaggle.com/vishalsubbiah/pokemon-images-and-types

Comic dataset                  http://ebdtheque.univ-lr.fr/                                  

Cartoon Set                      https://google.github.io/cartoonset/
                                         https://google.github.io/cartoonset/download.html

The IIIT-CFW dataset       https://cvit.iiit.ac.in/research/projects/cvit-projects/cartoonfaces

Simpson Faces                 https://www.kaggle.com/kostastokis/simpsons-faces

Comic Book Images         https://www.kaggle.com/cenkbircanoglu/comic-books-classification

WebCaricature                 https://cs.nju.edu.cn/rl/WebCaricature.htm

Caricature dataset            https://github.com/QianyiWu/Caricature-Data

Bitmoji dataset                 https://arxiv.org/pdf/1704.05693.pdf (could not find link for image, only 
                                         find paper)

**Comment by pmeier** [comment]
> I sorry to not include any link, I create same issue in torchvision, and PyTorch,
so one of them could be closed,

Please do that.

---

Thanks for the links!

> some of these have copyright issues, and require specific permissions to use the dataset,
but I list all that I found

As long as they are publicly accessible and the license does not outright forbid the usage, I don't think this is a problem since we only provide an interface.

> I think atleast one or two computer generated reality dataset should be added to torchvision in 2020.

Since you seem to have more experience than we do in this field, please choose most prominent of them and provide links to research papers that use them.

**Comment by vainaijr** [comment]
I consider these two factor,

1) resolution, or how good dataset look
2) what do computer learn from dataset

I think one dataset, that satisfies both of these criteria is 

Cartoon Set | https://google.github.io/cartoonset/, https://google.github.io/cartoonset/download.html
-- | --

it has paper also, https://arxiv.org/pdf/1711.05139.pdf

Computer learn to superimpose an animated avatar over biological avatar through this dataset, plus computer need to learn to capture facial expression just like biological avatar do, so that animated avatar do same facial expression. It advance research in this direction.

(https://cs.nju.edu.cn/rl/WebCaricature.htm, this one also appear similar, with paper in their site)

One more field would be a comic dataset, to enable computer to comprehend comic. Because no computer in 2020 able to give a summary of comic, or read text through panels in correct order, or detect images in comic. It kind of need to have a neural network that do text reading, image classification, panel detection, all combined, so it need research.

http://www.manga109.org/en/, this one comic dataset with their publications, http://www.manga109.org/en/publication.html, and this, http://ebdtheque.univ-lr.fr/, with publications, http://ebdtheque.univ-lr.fr/references/.

Other dataset that I included link for, are kind of similar, or computer learn similar thing from them.

**Comment by fmassa** [comment]
So, I think we should break down exactly what are the things that you are looking to achieve -- the fact that you are interested in cartoon images is an artifact of the problem that you want to solve.

You raised three points: super-resolution (for which datasets can be trivially written for it based on ImageFolder), the second is (if I understand correctly) style transfer (which can also be easily written), and the third is image-to-text (similarly to CocoCaptions).

I think that the most complicated setup for style transfer which relates to the dataset is how you sample your data in minibatches.

I think just adding a new dataset won't bring you much closer to solving the problem -- as I said, the dataset is generally easy to write and adapt to new cases, and there doesn't seem to be a standard dataset for those tasks yet, so I would not see it fit for torchvision for now.

As such, I'm closing this issue but let me know if you disagree.
