### ISSUE TITLE
Faster/Mask R-CNNN works on mobile (Android)?

### ISSUE THREAD

**Issue by hachreak** [pytorch/vision#2050]
## ❓ Questions and Help

Hi everybody,
I was trying understand if I can make object detection on Android but it's not really clear if I can do it.
The most recent comments that I found are these ones: 

- https://discuss.pytorch.org/t/support-torchvision-ops-nms-on-mobile-cpu/69627/2

- https://github.com/pytorch/vision/issues/1943#issuecomment-597624674

Can somebody confirm it? 
If not, maybe we can leave the issue open until vision is ready for mobile?
Thanks :smile:

**Comment by jjbouza** [comment]
I'm also interested in this

**Comment by fmassa** [comment]
It is not yet supported, but it is in the plans to be supported in follow-up releases of PyTorch

**Comment by lothlorien13** [comment]
Is it currently supported?

**Comment by ValerianGonnot** [comment]
@lothlorien13 No, it is still not supported in Pytorch 1.7.0

**Comment by fmassa** [comment]
@ValerianGonnot note that once we merge (which should be soon) https://github.com/pytorch/vision/pull/2897 torchvision detection models will be supporting Android

**Comment by fmassa** [comment]
The next release of torchvision (which will be released in ~1 month) will have support for Android for faster rcnn / mask rcnn.

Here is a demo app to show how to do it https://github.com/pytorch/vision/tree/master/android/test_app
