### ISSUE TITLE
`make_grid(img, padding=0)` generates unwanted black lines.

### ISSUE THREAD

**Issue by lanpa** [pytorch/vision#206]
label_img = torch.rand(100, 3, 32, 32)
    x = torchvision.utils.make_grid(label_img, nrow=10, padding=0)
    label_img = torch.rand(1, 3, 32, 32)
    x = torchvision.utils.make_grid(label_img, nrow=10, padding=0)

`x.size()` will be [3, 321, 321], [3, 33, 33] respectively.
There are additional black line on the top and on the left of the result image.

**Comment by fmassa** [comment]
Fixed by #248
