### ISSUE TITLE
Hope Yolo model can be added in pretrained models

### ISSUE THREAD

**Issue by merisgong208** [pytorch/vision#2074]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by fmassa** [comment]
Hi,

We are planning on adding RetinaNet to the models soon, but there is currently no plans for YOLO.
Note that both RetinaNet and YOLO are single-stage methods, but RetinaNet is more accurate so should cover more cases (given a fixed backbone).

The PR adding RetinaNet can be found in https://github.com/pytorch/vision/pull/1697

As such, I'm closing this issue but let me know if you disagree.

**Comment by merisgong208** [comment]
Thank you very much.
