### ISSUE TITLE
Provide functionality to get labels from label numbers when using datset.ImageFolder

### ISSUE THREAD

**Issue by codeBedouin** [pytorch/vision#208]
For one of my application I had to go from class number to actual label. For this I had to go and read the actual code of ImageFolder to figure out the directories are sorted alphabetically. I will like to contribute to  the code to provide a hook which returns a dictionary  which provides mapping from class number to label name. 
Is is fine ?

**Comment by fmassa** [comment]
We currently have access to [`class_to_idx` and `classes`](https://github.com/pytorch/vision/blob/master/torchvision/datasets/folder.py#L102). In your specific case, `classes` contains the mapping you are looking for.
