### ISSUE TITLE
Does vision cpp api support half cuda precision ?

### ISSUE THREAD

**Issue by Edwardmark** [pytorch/vision#2082]
Does vision cpp api support half cuda precision ?
I see that in the CMakelist.txt, it used flags as -D__CUDA_NO_HALF_OPERATORS_.
https://github.com/pytorch/vision/blob/master/CMakeLists.txt#L10

**Comment by bmanga** [comment]
Currently the cuda code fails to compile if that flag is not passed. I don't remember the exact reason why though, but I think it had to do with ambiguous overloads.

**Comment by Edwardmark** [comment]
@bmanga so could the torchvison cpp code run with fp16 input?

**Comment by bmanga** [comment]
If you mean user code, I think the answer is that you can use fp16 in your own code, but the moment you pass the data to torchvision code it will be converted to fp32, so it won't perform native 16bit operations.
I could be very wrong though, I haven't personally tried that.

**Comment by fmassa** [comment]
I believe it should work with half types, but please let us know if that isn't the case.

**Comment by Edwardmark** [comment]
@fmassa @bmanga Hi, 
I use half tensor in dets and scores to do nms:
cout << c_bboxes << endl;
cout << c_scores << endl;
torch::Tensor keep = nms(c_bboxes, c_scores, 0.3);
But it gives the following output:
 0.4980  0.2432  0.0919  0.1073
 0.4978  0.2426  0.0928  0.1094
 0.4966  0.2424  0.0934  0.1096
 0.4980  0.2428  0.0935  0.1099
 0.4976  0.2430  0.0946  0.1110
 0.4973  0.2441  0.0930  0.1113
 0.4978  0.2439  0.0928  0.1109
[ CUDAHalfType{7,4} ]
 0.0218  0.9780
 0.0638  0.9360
 0.0842  0.9155
 0.0025  0.9976
 0.0034  0.9966
 0.0030  0.9971
 0.0061  0.9937
[ CUDAHalfType{7,2} ]
terminate called after throwing an instance of 'std::runtime_error'
  what():  invalid argument 3: Index is supposed to be an empty tensor or a vector at /pytorch/aten/src/THC/generic/THCTensorIndex.cu:419
Aborted (core dumped)

Why is that? Is that because of the compiler option  flags as -D__CUDA_NO_HALF_OPERATORS_ ?
Could you have a try and help me out? Thanks.

Best, 
Edward.
