### ISSUE TITLE
How to use torchvision.ops.nms in cpp?

### ISSUE THREAD

**Issue by Edwardmark** [pytorch/vision#2089]
How to use torchvision.ops.nms in cpp?
What should I include and how to call the funciton? Any doc?

**Comment by fmassa** [comment]
We don't yet have full documentation for it, but here are a few links that give information on how to do it https://github.com/pytorch/vision/pull/1407#issuecomment-562734481 https://github.com/pytorch/vision/pull/1407#issuecomment-562096191

It would be great to have it summarized in the `examples/` folder, a PR would be awesome
Also, ccing @chauhang

**Comment by fmassa** [comment]
An example is now available in https://github.com/pytorch/vision/blob/master/test/tracing/frcnn/test_frcnn_tracing.cpp
