### ISSUE TITLE
New release or use master?

### ISSUE THREAD

**Issue by danqing** [pytorch/vision#209]
Hi,

Is the recommended way to use vision installing from master? I have a similar issue as #169, which apparently multiple other people have encountered. It seems to be fine in master.

The last release is 4 months old. When installing via conda (or pip - although pytorch doesn't play nicely with pip), only the released version is installed.

Also, it will be very helpful if master can be a different version. Now since master and the last release are on the same version, "upgrading" won't work.

**Comment by fmassa** [comment]
A new release of PyTorch will be soon released, and will contain a number of new features. It should be out next week I suppose.

**Comment by danqing** [comment]
Can we also make sure master and the latest release have different version numbers?
