### ISSUE TITLE
Error when installing using official command

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/vision#2098]
## 🐛 Bug

```
ERROR: torchvision 0.6.0 has requirement torch==1.5.0, but you'll have torch 1.6.0.dev20200413 which is incompatible.
```

## To Reproduce

Go to: https://pytorch.org/get-started/locally/ and copy-paste the command provided:

```
pip install numpy
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu101/torch_nightly.html
```

**Comment by fmassa** [comment]
Thanks for opening this issue!

This should (hopefully) be fixed with https://github.com/pytorch/vision/pull/2102
