### ISSUE TITLE
Where to download torchvision0.5.1 .whl files

### ISSUE THREAD

**Issue by 300LiterPropofol** [pytorch/vision#2101]
Hi,
I would like to download the torchvision 0.5.1 version but I cannot find a source to download the .whl file.
It is not in pypi.org nor in pytorch.org, nor anaconda.org.

I have proxy issues on my computer so I can not use pip command, I need to download the .whl file first.
Can you help me by giving an address of the 0.5.1 version? or some other hint to solve this? Thank you.

**Comment by fmassa** [comment]
Hi,

The 0.5.1 version of torchvision (which has been renamed to 0.6.0) has not been officially released yet, and is in testing phase.

It will be made available next week in the official pytorch channels

I'm closing the issue as such, but let us know if you have further questions
