### ISSUE TITLE
I can't load mobilenet  under version 0.5.0

### ISSUE THREAD

**Issue by lunasdejavu** [pytorch/vision#2106]
## To Reproduce

1.a =models.mobilenet()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
## Expected behavior
load the mobilenet model, but I can find  mobilenet module in dir(torchvision.models)

## Environment
ubuntu16.04
torchvision version 0.5.0
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0):
 - OS (e.g., Linux):
 - How you installed PyTorch / torchvision (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Gokkulnath** [comment]
@lunasdejavu You are trying to call a module as such. The correct way of instantiating a model is

> from torchvision.models import MobileNetV2     
model=MobileNetV2(**params)

**Comment by lunasdejavu** [comment]
> @lunasdejavu You are trying to call a module(.py file) as such. The correct way of instantiating a model is
> 
> > from torchvision.models import MobileNetV2
> > model=MobileNetV2(**params)

I want to call mobilenetv1 not mobilenetv2, 
the result of `dir(models) `shows there are two different  mobilenet models here.
` ['AlexNet', 'DenseNet', 'GoogLeNet', 'GoogLeNetOutputs', 'Inception3', 'InceptionOutputs', 'MNASNet', 'MobileNetV2', 'ResNet', 'ShuffleNetV2', 'SqueezeNet', 'VGG', '_GoogLeNetOutputs', '_InceptionOutputs', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_utils', 'alexnet', 'densenet', 'densenet121', 'densenet161', 'densenet169', 'densenet201', 'detection', 'googlenet', 'inception', 'inception_v3', 'mnasnet', 'mnasnet0_5', 'mnasnet0_75', 'mnasnet1_0', 'mnasnet1_3', 'mobilenet', 'mobilenet_v2', 'quantization', 'resnet', 'resnet101', 'resnet152', 'resnet18', 'resnet34', 'resnet50', 'resnext101_32x8d', 'resnext50_32x4d', 'segmentation', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'shufflenetv2', 'squeezenet', 'squeezenet1_0', 'squeezenet1_1', 'utils', 'vgg', 'vgg11', 'vgg11_bn', 'vgg13', 'vgg13_bn', 'vgg16', 'vgg16_bn', 'vgg19', 'vgg19_bn', 'video', 'wide_resnet101_2', 'wide_resnet50_2']`

**Comment by Gokkulnath** [comment]
I think we dont have mobilenetv1 in torchvision.models.
P.S:  Also i believe that whatever you see in that list includes all the submodule filenames that are located under the models directory. See here: [Link ](https://github.com/pytorch/vision/tree/1e27b533490d5b375c4656d2dd67961baaa1dced/torchvision/models) 

you can also look into the source of mobilenet here:  [mobilenet.py](https://github.com/pytorch/vision/blob/master/torchvision/models/mobilenet.py).

**Comment by fmassa** [comment]
@Gokkulnath is correct, we don't provide MobileNetV1 models, only V2.

Also, the way I would recommend for calling the model would be the following:

```python
model = torchvision.models.mobilenet_v2(pretrained=True)
```

As such, I'm closing the issue but let us know if you have further questions
