### ISSUE TITLE
Error in exporting Mask-RCNN to onnx format

### ISSUE THREAD

**Issue by ResByte** [pytorch/vision#2111]
## 🐛 ONNX export of Mask-RCNN results in KeyError: '_new_empty_tensor_op'

Following the guide(https://github.com/pytorch/vision/releases) to export Mask-rcnn with resnet-50 backbone, there was error. Details of this as  :

**versions**
```
PyTorch version: 1.5.0a0+3bbb36e
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 418.87.00
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.3.2
[pip] numpy==1.18.1
[pip] pytorch-transformers==1.1.0
[pip] torch==1.5.0a0+3bbb36e
[pip] torchtext==0.4.0
[pip] torchvision==0.6.0a0
[conda] magma-cuda101             2.5.1                         1    local
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] msgpack-numpy             0.4.3.2                  py36_0  
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.18.1           py36h94c655d_0  
[conda] numpy-base                1.18.1           py36h2f8d375_1  
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.5.0a0+3bbb36e          pypi_0    pypi
[conda] torchtext                 0.4.0                    pypi_0    pypi
[conda] torchvision               0.6.0a0                  pypi_0    pypi
```

**code:**
```python
model_tv = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
model_tv.eval()
torch.onnx.export(model_tv, torch.rand(1,3,300,300), "mask_rcnn_r50_fpn.onnx",
                  do_constant_folding=True,
                  opset_version=11  # opset_version 11 required for Mask R-CNN
                  )
```

**error log:**

```shell
KeyError                                  Traceback (most recent call last)
<ipython-input-5-83afd8e59ef2> in <module>
      2 torch.onnx.export(model_tv, torch.rand(1,3,300,300), "mask_rcnn_r50_fpn.onnx",
      3                   do_constant_folding=True,
----> 4                   opset_version=11  # opset_version 11 required for Mask R-CNN
      5                   )

/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets)
    153                         do_constant_folding, example_outputs,
    154                         strip_doc_string, dynamic_axes, keep_initializers_as_inputs,
--> 155                         custom_opsets)
    156 
    157 

/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets)
     65             example_outputs=example_outputs, strip_doc_string=strip_doc_string,
     66             dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs,
---> 67             custom_opsets=custom_opsets)
     68 
     69 

/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, propagate, opset_version, _retain_param_name, do_constant_folding, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size, custom_opsets, add_node_names)
    465                                                         example_outputs, propagate,
    466                                                         _retain_param_name, val_do_constant_folding,
--> 467                                                         fixed_batch_size=fixed_batch_size)
    468 
    469         # TODO: Don't allocate a in-memory string for the protobuf

/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py in _model_to_graph(model, args, verbose, training, input_names, output_names, operator_export_type, example_outputs, propagate, _retain_param_name, do_constant_folding, _disable_torch_constant_prop, fixed_batch_size)
    335     graph = _optimize_graph(graph, operator_export_type,
    336                             _disable_torch_constant_prop=_disable_torch_constant_prop,
--> 337                             fixed_batch_size=fixed_batch_size, params_dict=params_dict)
    338 
    339     if isinstance(model, torch.jit.ScriptModule) or isinstance(model, torch.jit.ScriptFunction):

/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py in _optimize_graph(graph, operator_export_type, _disable_torch_constant_prop, fixed_batch_size, params_dict)
    150         torch._C._jit_pass_erase_number_types(graph)
    151 
--> 152         graph = torch._C._jit_pass_onnx(graph, operator_export_type)
    153         torch._C._jit_pass_lint(graph)
    154 

/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py in _run_symbolic_function(*args, **kwargs)
    184 def _run_symbolic_function(*args, **kwargs):
    185     from torch.onnx import utils
--> 186     return utils._run_symbolic_function(*args, **kwargs)
    187 
    188 

/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py in _run_symbolic_function(g, n, inputs, env, operator_export_type)
    769                               "torch.onnx.register_custom_op_symbolic(symbolic_name, symbolic_fn)?"
    770                               .format(ns, op_name, opset_version, op_name))
--> 771             symbolic_fn = sym_registry.get_registered_op(op_name, ns, opset_version)
    772             attrs = {k: n[k] for k in n.attributeNames()}
    773             return symbolic_fn(g, *inputs, **attrs)

/opt/conda/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py in get_registered_op(opname, domain, version)
     92         warnings.warn("ONNX export failed. The ONNX domain and/or version are None.")
     93     global _registry
---> 94     return _registry[(domain, version)][opname]

KeyError: '_new_empty_tensor_op'
```

**Comment by fmassa** [comment]
@neginraoof could you have a look?
This type of issues have showed up in the past and have been fixed, but looks like @ResByte is using a recent enough version of PyTorch / TorchVision

**Comment by neginraoof** [comment]
Sure. Export for _new_empty_tensor_op has been enabled in: https://github.com/pytorch/vision/pull/1733
@fmassa  Do you know how can I check if this commit is in torchvision 0.6.0a0 ?

**Comment by qianxi0617** [comment]
@neginraoof Same original issue here. Nightly built torch and torchvision dev20200414 solved  _new_empty_tensor_op. But it occurred a new one: `Exporting the operator prim_Uninitialized to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator. `

**Comment by wangjunfeng90214** [comment]
My system is ubuntu 16.04,
torch and torchvision version as below:
torch.__version__
Out[5]: '1.5.0+cu101'
torchvision.__version__
Out[6]: '0.6.0+cu101'

~$ nvidia-smi
Mon May 11 11:20:04 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:01:00.0  On |                  N/A |
| 35%   60C    P0    62W / 250W |    724MiB / 12192MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1321      G   /usr/lib/xorg/Xorg                           427MiB |
|    0      3958      G   compiz                                       116MiB |
|    0      5483      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files   175MiB |
+-----------------------------------------------------------------------------+

~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

cuda version:
~$ cat /usr/local/cuda/version.txt
CUDA Version 10.0.130

cudnn version:
~$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 4
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

and I have met the same problem when I run the Mask R-CNN demo in the https://pytorch.org/docs/stable/torchvision/models.html#object-detection-instance-segmentation-and-person-keypoint-detection , I have met the same problem:
RuntimeError: Exporting the operator prim_Uninitialized to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.
How can I fix the issue?

**Comment by BlakeXiaochu** [comment]
Same problem, is there any workaround?

**Comment by tsaizhenling** [comment]
same issue here

**Comment by guangdongliang** [comment]
same issue here, can anyone give some advice about "operator prim_Uninitialized" ?

**Comment by fmassa** [comment]
cc @neginraoof @lara-hdr can you please have a look?

**Comment by neginraoof** [comment]
Thanks for reporting this.
I believe this issue is resolved as part of https://github.com/pytorch/vision/pull/2215

Torchvision nightly build should work now.
I just tested the repro code:

model_tv = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
model_tv.eval()
torch.onnx.export(model_tv, torch.rand(1,3,300,300), "mask_rcnn_r50_fpn.onnx",
                  do_constant_folding=True,
                  opset_version=11  # opset_version 11 required for Mask R-CNN
                  )

And export was successful.
To run this model with ONNX Runtime, please try ONNX Runtime 1.3.0.
Thanks.

**Comment by ResByte** [comment]
Thanks @neginraoof @fmassa , It works now. you may close the issue.
