### ISSUE TITLE
torchvision 0.6.0 not support windows?

### ISSUE THREAD

**Issue by 300LiterPropofol** [pytorch/vision#2130]
Hi,

I found you just released torchvision on pypi and anaconda.org, but I didn't find the .whl file for windows.
Are you going to release the file that support windows? since torch 0.5.0 still supports windows.
Or 0.6.0 will not support windows and there will be no further release on it.

It will be great to know since I am working on a only windows environment.
Thank you

**Comment by pmeier** [comment]
You can find all `wheel`s for the stable versions [here](https://download.pytorch.org/whl/torch_stable.html). For windows

- CUDA 9.2: [`py35`](https://download.pytorch.org/whl/cu92/torchvision-0.6.0%2Bcu92-cp35-cp35m-win_amd64.whl), [`py36`](https://download.pytorch.org/whl/cu92/torchvision-0.6.0%2Bcu92-cp36-cp36m-win_amd64.whl), [`py37`](https://download.pytorch.org/whl/cu92/torchvision-0.6.0%2Bcu92-cp37-cp37m-win_amd64.whl), [`py38`](https://download.pytorch.org/whl/cu92/torchvision-0.6.0%2Bcu92-cp38-cp38-win_amd64.whl)
- CUDA 10.1: [`py35`](https://download.pytorch.org/whl/cu101/torchvision-0.6.0%2Bcu101-cp35-cp35m-win_amd64.whl), [`py36`](https://download.pytorch.org/whl/cu101/torchvision-0.6.0%2Bcu101-cp36-cp36m-win_amd64.whl), [`py37`](https://download.pytorch.org/whl/cu101/torchvision-0.6.0%2Bcu101-cp37-cp37m-win_amd64.whl), [`py38`](https://download.pytorch.org/whl/cu101/torchvision-0.6.0%2Bcu101-cp38-cp38-win_amd64.whl)
- CUDA 10.2: [`py35`](https://download.pytorch.org/whl/cu102/torchvision-0.6.0-cp35-cp35m-win_amd64.whl), [`py36`](https://download.pytorch.org/whl/cu102/torchvision-0.6.0-cp36-cp36m-win_amd64.whl), [`py37`](https://download.pytorch.org/whl/cu102/torchvision-0.6.0-cp37-cp37m-win_amd64.whl), [`py38`](https://download.pytorch.org/whl/cu102/torchvision-0.6.0-cp38-cp38-win_amd64.whl)
- CPU: [`py35`](https://download.pytorch.org/whl/cpu/torchvision-0.6.0%2Bcpu-cp35-cp35m-win_amd64.whl), [`py36`](https://download.pytorch.org/whl/cpu/torchvision-0.6.0%2Bcpu-cp36-cp36m-win_amd64.whl), [`py37`](https://download.pytorch.org/whl/cpu/torchvision-0.6.0%2Bcpu-cp37-cp37m-win_amd64.whl), [`py38`](https://download.pytorch.org/whl/cpu/torchvision-0.6.0%2Bcpu-cp38-cp38-win_amd64.whl)

**Comment by 300LiterPropofol** [comment]
Thank you very much! It is really helpful!
For whoever upcoming, to successfully use the torchvision 0.6.0, torch 1.4.0 is not enough, you need to install the newest version torch 1.5.0 which is released at the same time as torchvision 0.6.0.

refer to this issue: https://github.com/pytorch/vision/issues/1827

**Comment by fmassa** [comment]
Thanks @pmeier for the help!
