### ISSUE TITLE
Making ASPP-Layer in DeepLab more generic

### ISSUE THREAD

**Issue by ArashJavan** [pytorch/vision#2136]
## 🚀 Feature
At the moment in the ASPP-Layer defined [here](https://github.com/pytorch/vision/blob/c031e2875bafe633cc163fb2bfe6c61f2f23285e/torchvision/models/segmentation/deeplabv3.py#L65) the number of output channels is predefined as a constant, which is good for DeepLab but not if someone else - like me ;) , want to use it in another project, where another out-channel Nr. is required.

Also the number of "atrous rates" is fixed to three, which also could be sometime more or less dpeending on the notwork. Again these fixed values may make sense in DeepLab-Model but not necessarily in other type of model, which in my case is applied on Lidar data. 

that means something like this would be at least IMO better:

```
class ASPP(nn.Module):
    def __init__(self, in_channels, atrous_rates, out_channel=256):
        super(ASPP, self).__init__()
        modules = []
        modules.append(nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU()))
        
        rates = tuple(atrous_rates)
        for rate in rates:
             modules.append(ASPPConv(in_channels, out_channels, rate))
      
        modules.append(ASPPPooling(in_channels, out_channels))
      
        self.convs = nn.ModuleList(modules)

        self.project = nn.Sequential(
            nn.Conv2d(5 * out_channels, out_channels, 1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(),
            nn.Dropout(0.5))

```

**Comment by vincentqb** [comment]
This looks reasonable to me, and is backward compatible. Do you want to open a pull request for this?

**Comment by ArashJavan** [comment]
Ok, thank, yes i will open a poll req.

**Comment by fmassa** [comment]
Fixed via https://github.com/pytorch/vision/pull/2174
