### ISSUE TITLE
nvcc fatal : unknown option 'openmp'

### ISSUE THREAD

**Issue by LI-Wen-Jiang** [pytorch/vision#2147]
@peterjc123 In order to use in C++ API of torchvision in Windows , I ran into a problem during my installation. And I am trying to build the C++ API on Windows 10 with CUDA 10.1 for Visual Studio 2019.
### Environment
PyTorch version: 1.4
CUDA : 10.1
OS: Windows10
CMake version: version 3.17.1
Python version: 3.7
libtorch:1.4_cu101_release

When I execute code `cmake -DCMAKE_PREFIX_PATH="D:/vision/libtorch" -DCMAKE_INSTALL_PREFIX="D:/torchvision" -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -DWITH_CUDA=ON ..` ,it works right. I get the following documents:
![image](https://user-images.githubusercontent.com/50292434/80302890-4f882280-87df-11ea-80cd-f743a23b2f90.png)

I click the file"INSTALL.vcxproj",and go to visual studio,I changed the mode to release, and start debuging. In this step ,I met a problem:"nvcc fatal : unknown option 'openmp'"

`"D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_35,code=\"sm_35,compute_35\" --use-local-env -ccbin "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64" -x cu  -ID:\vision\libtorch\include -ID:\vision\libtorch\include\torch\csrc\api\include -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I"D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\include" -I"D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -openmp -Xcompiler="/EHsc -Ob2"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc142.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\ROIPool_cuda.obj "D:\vision\torchvision\csrc\cuda\ROIPool_cuda.cu"`

In the above command, an flag "openmp" appears ,and nvcc doesn't how to meet it.

**Comment by wk5ovc** [comment]
Move all nvcc flags to Xcompiler like this `-Xcompiler="/EHsc -Ob2 /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj /openmp"`, also change `-openmp ` to `/openmp `, no build error occured, didn't known why.

**Comment by xuezu29** [comment]
I met the same problem. Have you solved it? thanks！

**Comment by xuezu29** [comment]
> Move all nvcc flags to Xcompiler like this `-Xcompiler="/EHsc -Ob2 /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj /openmp"`, also change `-openmp ` to `/openmp `, no build error occured, didn't known why.

It works for me . Thanks.

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
