### ISSUE TITLE
difference between transform & target_transform?

### ISSUE THREAD

**Issue by isalirezag** [pytorch/vision#215]
Can you please explain the difference between transform & target_transform?
I understand that we usually use transform for doing changes to our images, but target_transform is still unclear for me? what is exactly used for? can we use that for images? the definition of it says: a function that takes in the target and transforms it, but it is not clear to me what it exactly means

**Comment by Cadene** [comment]
Lets say you want to apply some data augmentations over a dataset of images with their segmentation masks. If you rotate the image to the left with transform, you would have to rotate the mask the left as well. That's the point of target_transform.

**Comment by isalirezag** [comment]
cannot we just rotate both of them via transform?

**Comment by alykhantejani** [comment]
@isalirezag currently the `transform` of the datasets only takes the input as an argument, hence the need for both a `transform` and a `target_transform`. However, there is a discussion in #230 to extend transforms to handle both input and target together. 

cc @fmassa I think we can close this.

**Comment by eduardo4jesus** [comment]
> Lets say you want to apply some data augmentations over a dataset of images with their segmentation masks. If you rotate the image to the left with transform, you would have to rotate the mask to the left as well. That's one of the point of target_transform.

It took me a while to understand this explanation. So, I just want to highlight a term that @Cadene mentioned that should be in kept in mind in order to understand it right away.

For classification problems, the `target` are labels. Thus, `target_transforms` wouldn't make sense.
However, for segmentation problems, in which we have **segmentation masks** as `targets`, it totally make sense.

**Comment by fmassa** [comment]
@eduardo4jesus I wouldn't say that `target_transforms` doesn't make sense for classification problems.
One could for example want to merge labels into common categories during training (say, via some sort of taxonomy), and the `target_transform` could be used for that.

**Comment by eduardo4jesus** [comment]
@fmassa. (Wow) That is true! Thank you so much. I hadn't thought about that usage!

**Comment by SmallPigPeppa** [comment]
Thank you a lot!!! very helpful answer

**Comment by andrew-miao** [comment]
@fmassa Cool! Thank you for your informational answer!

**Comment by chenfengshijie** [comment]
Very useful answer!

**Comment by brando90** [comment]
what is an example of what the target transform should be for a classification problem?

**Comment by EddieAy** [comment]
@fmassa  Thank you for your informational answer

**Comment by hanli435** [comment]
very helpful.thank you a lot!!
