### ISSUE TITLE
Cannot train deeplabv3_resnet50 with batch size of 1

### ISSUE THREAD

**Issue by christian-rauch** [pytorch/vision#2151]
## To Reproduce

1. train a `deeplabv3_resnet50`
1. call `forward` with tensor of shape: `torch.Size([1, 3, 240, 320])` (batch with single colour image)
1. receive error message: `ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])`

## Expected behavior

Training should conduct as with `torch.Size([2, 3, 240, 320])` (batch size 2 and up).

## Environment
```
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.5.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.6.0
[conda] Could not collect
```

## Additional context

Training with batch size of 1 is probably uncommon but there is no technical reason why this should not be possible and the error message is rather cryptic and unhelpful.

**Comment by fmassa** [comment]
This is expected, because we use BatchNorm in the backbone, which doesn't work for batch sizes of 1.

If you want to train with batch_size of 1, you should change the backbone (or the normalization in resnet) to not use BatchNorm.

**Comment by fmassa** [comment]
It would be great if we could improve the error message in a more meaningful way though, so I'm open to suggestions
