### ISSUE TITLE
engine.py error while following tutorial

### ISSUE THREAD

**Issue by EMCP** [pytorch/vision#2167]
## 📚 Documentation

I have found this library via the examples at https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html

I ran the google colab and that successfully finished.. however when I go to copy `master` from here and use it locally I am getting an error..

Engine.py line 
![image](https://user-images.githubusercontent.com/3691722/80714967-f9c0bc80-8af5-11ea-8d17-1d8f1278a69d.png)

![image](https://user-images.githubusercontent.com/3691722/80715039-14933100-8af6-11ea-89ee-894b769723f7.png)

Error

```
    train_one_epoch(model, optimizer, training_data_loader, device, epoch, print_freq=model_conf["hyperParameters"]["display"])
  File "/home/emcp/Dev/git/EMCP/faster-rcnn-torchvision/model_components/model/engine.py", line 27, in train_one_epoch
    images = list(image.to(device) for image in images)
  File "/home/emcp/Dev/git/EMCP/faster-rcnn-torchvision/model_components/model/engine.py", line 27, in <genexpr>
    images = list(image.to(device) for image in images)
AttributeError: 'Image' object has no attribute 'to'
``
seems to be an image did not load perhaps ?

**Comment by EMCP** [comment]
When I look at my DataLoader it seems to be giving correct items

```
(<PIL.Image.Image image mode=RGB size=2880x1880 at 0x7F06E2CCAAD0>, [{'id': 847, 'image_id': 3135, 'category_id': 6, 'segmentation': [[90.0, 36.0, 2874.8, 35.7, 2880.0, 40.1, 2880.0, 1795.3, 2875.3, 1800.0, 3.6, 1799.7, 0.4, 1795.5, 0.2, 41.2, 6.1, 35.7, 90.0, 36.1]], 'area': 5080276, 'bbox': [0.0, 36.0, 2880.0, 1764.0], 'iscrowd': False, 'color': '#d5e47c', 'metadata': {}}, {'id': 848, 'image_id': 3135, 'category_id': 7, 'segmentation': [[666.9, 1799.9, 2239.9, 1800.0, 2245.7, 1805.4, 2246.0, 1879.8, 634.8, 1879.9, 634.2, 1805.9, 639.4, 1799.9, 667.3, 1800.2]], 'area': 128892, 'bbox': [634.0, 1800.0, 1612.0, 80.0], 'iscrowd': False, 'color': '#6c3ee0', 'metadata': {}}])
```

**Comment by fmassa** [comment]
@EMCP You need to feed a `torch.Tensor` to the model. Your Dataset is returning a PIL Image, that's why it's not working. We convert the PIL Image into a torch Tensor in the dataset (via the `transform`.

**Comment by EMCP** [comment]
big thank you.. Feels like I'm almost there then with it

**Comment by EMCP** [comment]
Should I open one more ticket if I have an issue... I had tried to use a different model in my local copy (resnet101) but this was basically not working.. so scrapped off that and went with the pretrained model from the demo...  Now seeing `Loss is nan, stopping training`

```
/home/emcp/anaconda3/envs/pytorch_150/lib/python3.7/site-packages/torch/nn/functional.py:2854: UserWarning: The default behavior for interpolate/upsample with float scale_factor will change in 1.6.0 to align with other frameworks/libraries, and use scale_factor directly, instead of relying on the computed output size. If you wish to keep the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn("The default behavior for interpolate/upsample with float scale_factor will change "
/opt/conda/conda-bld/pytorch_1587428266983/work/torch/csrc/utils/python_arg_parser.cpp:756: UserWarning: This overload of nonzero is deprecated:
	nonzero(Tensor input, *, Tensor out)
Consider using one of the following signatures instead:
	nonzero(Tensor input, *, bool as_tuple)
Loss is nan, stopping training
{'loss_classifier': tensor(2.9877, device='cuda:0', grad_fn=<NllLossBackward>), 'loss_box_reg': tensor(0., device='cuda:0', grad_fn=<DivBackward0>), 'loss_objectness': tensor(17.7084, device='cuda:0',
       grad_fn=<BinaryCrossEntropyWithLogitsBackward>), 'loss_rpn_box_reg': tensor(nan, device='cuda:0', grad_fn=<DivBackward0>)}

``

**Comment by kotchwane** [comment]
I'm having the exact same issue here... Could you be more precise about what needs to be changed? I checked 10 times, I did not miss one step from the tutorial.

**Comment by kotchwane** [comment]
Okay, I found it. While doing the tutorial, I had commented these lines, inside PennFudanDataSet, because the created problems for early testing :

`if self.transforms is not None:
            img, target = self.transforms(img, target)
`
Un-commenting these solved the issue (and, of course, led to a new one).

What I had not realized earlier in the tutorial, and led me to wrongly comment those two lines, is that you can easily test the PennFudanDataSet by calling it with None as a second argument:
`dataset = PennFudanDataset('PennFudanPed', None)`
