### ISSUE TITLE
Duplicated function channel_shuffle()

### ISSUE THREAD

**Issue by xkszltl** [pytorch/vision#2193]
## 🐛 Bug

Get the following error when compiling today with pytorch master.
This should be a recent regression as I was able to do the same in Apr.

```
../torchvision/csrc/models/shufflenetv2.cpp:83:33: error: call of overloaded 'channel_shuffle(at::Tensor&, int)' is ambiguous
../torchvision/csrc/models/shufflenetv2.cpp:10:15: note: candidate: 'at::Tensor vision::models::channel_shuffle(at::Tensor, int64_t)'
/usr/local/include/ATen/Functions.h:8045:22: note: candidate: 'at::Tensor at::channel_shuffle(const at::Tensor&, int64_t)'
```

## Environment

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): master/master
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja+gcc-8
 - CUDA/cuDNN version: 10.2

## Additional context

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/5203025/81291560-8e9a5b80-909c-11ea-92f7-d6131b4ea773.png">

**Comment by zhangguanheng66** [comment]
Could you add a code snippet to reproduce the error?

**Comment by xkszltl** [comment]
@zhangguanheng66 I think it's unnecessary.
This is simply a compile error saying you have 2 definition of channel_shuffle():

- One is in pytorch (ATen) probably from this commit during last week: https://github.com/pytorch/pytorch/commit/df31ddbd98fa06ece235033438d13eb7c93c420e
- The other is the one in the `shufflenetv2.cpp`.

Since there're `using namespace at` everywhere, even in `.h`, within this repo, it's not surprising to have ambiguity.

Suggest to be more specific by using `::vision::models::channel_shuffle`, and it possible, check pytorch version and use theirs when available.

**Comment by fmassa** [comment]
Thanks for opening this issue!

Can you send a PR fixing the implementation in torchvision to use the `::vision` namespace?

**Comment by xkszltl** [comment]
@fmassa PR sent
