### ISSUE TITLE
DenseNet memory_efficient mode appears subtly broken since torchscript changes

### ISSUE THREAD

**Issue by rwightman** [pytorch/vision#2221]
## 🐛 Bug

I was working with DenseNet recently, I noticed memory_efficient training was faster than with the flag disabled (unexpected), and it wasn't training very well at all, also errors from checkpoint fn about args not having required_grad=True set.

I believe #1342 subtly broke the checkpointing by wraping inputs in an extra layer of container

densenet.py:53
``` 
    def call_checkpoint_bottleneck(self, input):
        # type: (List[Tensor]) -> Tensor
        def closure(*inputs):
            return self.bn_function(*inputs)

        return cp.checkpoint(closure, input)
```

should be

```
    def call_checkpoint_bottleneck(self, input):
        # type: (List[Tensor]) -> Tensor
        def closure(*inputs):
            return self.bn_function(inputs)  # remove *

        return cp.checkpoint(closure, *input)  # add *
```
## To Reproduce

Train any densenet network with `memory_efficient=True`

## Environment

Any

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): 1.4
 - OS (e.g., Linux): any

**Comment by rwightman** [comment]
Note, I didn't test my fix with torchscript so I may have broken that, my fix results in the inputs pasted to bn_function being a tuple instead of the annotated list type

**Comment by fmassa** [comment]
@rwightman can you send a PR fixing this? This should be fine with torchscript, because we skip torchscript for that function (it doesn't support `checkpoint`.

Also, would there be another test we could add that would catch this? IIRC we already have a test for the checkpoint behavior, but maybe it is missing some corner cases

**Comment by rwightman** [comment]
@fmassa sure, I'll get a PR in for that, will take a look at the model in broken state again and see if any tests come to mind...

**Comment by rwightman** [comment]
Below will fail when the checkpointing isn't working properly... (or equivalently some of the model parameter grad attr are None after backward)
```
>>> m = densenet121(pretrained=True, memory_efficient=True)
>>> num_params = sum([x.numel() for x in m.parameters()])
>>> m(torch.randn(4, 3, 224, 224)).mean().backward()
>>> num_grad = sum([x.grad.numel() for x in m.parameters() if x.grad is not None])
>>> assert num_params == num_grad
```
