### ISSUE TITLE
Error compiling torchvision for Windows

### ISSUE THREAD

**Issue by laizewei** [pytorch/vision#2233]
win10 x64  SDK 10.0.18362.0  ,visual studio 2019 16.5.5,   torchvision 0.6.0 , cuda 10.2

-------------------------------------------------------------------------
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe"  --use-local-env -ccbin "D:\vs2019\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64" -x cu  -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include" -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I"D:\software\cudnn-10.2-windows10-x64-v7.6.5.32\cuda\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -openmp -Xcompiler="/EHsc -Ob2"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc142.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\DeformConv_cuda.obj "C:\Users\william\Downloads\vision-0.6.0\vision-0.6.0\torchvision\csrc\cuda\DeformConv_cuda.cu"”已退出，返回代码为 1。	torchvision	D:\vs2019\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets	764	
----------------------------------------------------------------------------
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe"  --use-local-env -ccbin "D:\vs2019\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64" -x cu  -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include" -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I"D:\software\cudnn-10.2-windows10-x64-v7.6.5.32\cuda\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -openmp -Xcompiler="/EHsc -Ob2"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc142.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\nms_cuda.obj "C:\Users\william\Downloads\vision-0.6.0\vision-0.6.0\torchvision\csrc\cuda\nms_cuda.cu"”已退出，返回代码为 1。	torchvision	D:\vs2019\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets	764	
---------------------------------------------------------------------
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe"  --use-local-env -ccbin "D:\vs2019\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64" -x cu  -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include" -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I"D:\software\cudnn-10.2-windows10-x64-v7.6.5.32\cuda\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -openmp -Xcompiler="/EHsc -Ob2"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc142.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\PSROIAlign_cuda.obj "C:\Users\william\Downloads\vision-0.6.0\vision-0.6.0\torchvision\csrc\cuda\PSROIAlign_cuda.cu"”已退出，返回代码为 1。	torchvision	D:\vs2019\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets	764	
-------------------------------------------------------------------------
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe"  --use-local-env -ccbin "D:\vs2019\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64" -x cu  -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include" -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I"D:\software\cudnn-10.2-windows10-x64-v7.6.5.32\cuda\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -openmp -Xcompiler="/EHsc -Ob2"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc142.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\PSROIPool_cuda.obj "C:\Users\william\Downloads\vision-0.6.0\vision-0.6.0\torchvision\csrc\cuda\PSROIPool_cuda.cu"”已退出，返回代码为 1。	torchvision	D:\vs2019\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets	764	
--------------------------------------------------------------
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe"  --use-local-env -ccbin "D:\vs2019\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64" -x cu  -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include" -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I"D:\software\cudnn-10.2-windows10-x64-v7.6.5.32\cuda\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -openmp -Xcompiler="/EHsc -Ob2"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc142.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\ROIAlign_cuda.obj "C:\Users\william\Downloads\vision-0.6.0\vision-0.6.0\torchvision\csrc\cuda\ROIAlign_cuda.cu"”已退出，返回代码为 1。	torchvision	D:\vs2019\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets	764	
-------------------------------------------------------------
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3721	命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe"  --use-local-env -ccbin "D:\vs2019\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64" -x cu  -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include" -I"C:\Users\william\Downloads\libtorch-win-shared-with-deps-1.5.0\libtorch\include\torch\csrc\api\include" -I"C:\Program Files\NVIDIA Corporation\NvToolsExt\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include" -I"D:\software\cudnn-10.2-windows10-x64-v7.6.5.32\cuda\include" -ID:\Python\Python37\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static /Z7 /EHa /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -openmp -Xcompiler="/EHsc -Ob2"    -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -DWIN32 -D_WINDOWS -DNDEBUG -DNOMINMAX -D__CUDA_NO_HALF_OPERATORS__ -DAT_PARALLEL_OPENMP=1 -D"CMAKE_INTDIR=\"Release\"" -Dtorchvision_EXPORTS -D_WINDLL -D_MBCS -Xcompiler "/EHsc /W3 /nologo /O2 /Fdtorchvision.dir\Release\vc142.pdb /FS /Zi  /MD /GR" -o torchvision.dir\Release\ROIPool_cuda.obj "C:\Users\william\Downloads\vision-0.6.0\vision-0.6.0\torchvision\csrc\cuda\ROIPool_cuda.cu"”已退出，返回代码为 1。	torchvision	D:\vs2019\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 10.2.targets	764

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
