### ISSUE TITLE
transforms.Compose with custom transforms

### ISSUE THREAD

**Issue by skrish13** [pytorch/vision#225]
In one of my custom transforms I take more than just the img/sample as input, this won't work with `transforms.Compose` as it's` __call__()` takes only 1 input. Any thoughts on getting a fix for this? Would be interested in making a PR if you guys would want it.

**Comment by alykhantejani** [comment]
Hi @skrish13 there is currently a discussion happening in [this issue](https://github.com/pytorch/vision/issues/230) about how to evolve the transforms to allow for these use cases. I think we're close to a new design so hopefully this will be supported soon.

cc @fmassa I think we can close this issue as it is essentially a duplicate of #230

**Comment by fmassa** [comment]
Closing it and redirecting the discussion to #230.

**Comment by skrish13** [comment]
Yup, following that discussion as well. Thanks. 

PS: Easy workaround for anyone facing issues like this: Just create your own Compose to mimic the flow you want, its pretty simple anyways.
