### ISSUE TITLE
cuda10.0 support for torchvision6

### ISSUE THREAD

**Issue by feihuidiqiu** [pytorch/vision#2250]
I try to install torchvision6-cu100 with pip but failed, I can only find  the cu92 and cu101 version,  is there no support for cuda10.0 ?

**Comment by fmassa** [comment]
Similarly to PyTorch, torchvision dropped support for CUDA 10.0, and only support CUDA 9.2 and CUDA 10.1 and 10.2 in latest releases.

You can still compile torchvision on CUDA 10.0 and it should work, but it is not officially supported anymore.
