### ISSUE TITLE
Avoid `using namespace at` in the header file?

### ISSUE THREAD

**Issue by ShawnZhong** [pytorch/vision#2255]
## 🐛 Bug

Some header files have `using namespace at` at the top level, which contaminates the file that included it, increasing the chance of name collision. 

https://github.com/pytorch/vision/blob/d88d8961ae51507d0cb680329d985b1488b1b76b/torchvision/csrc/empty_tensor_op.h#L8

https://github.com/pytorch/vision/blob/57c789f893950331daf2721d08a7367a261317e1/torchvision/csrc/PSROIPool.h#L71

https://github.com/pytorch/vision/blob/57c789f893950331daf2721d08a7367a261317e1/torchvision/csrc/ROIPool.h#L71

https://github.com/pytorch/vision/blob/57c789f893950331daf2721d08a7367a261317e1/torchvision/csrc/DeformConv.h#L91

https://github.com/pytorch/vision/blob/57c789f893950331daf2721d08a7367a261317e1/torchvision/csrc/ROIAlign.h#L92

**Comment by fmassa** [comment]
Thanks for the bug report and the fix!
Fixed in https://github.com/pytorch/vision/pull/2257
