### ISSUE TITLE
Occlusion Transformation [Request]

### ISSUE THREAD

**Issue by hendrycks** [pytorch/vision#226]
Two papers this week confirm that data augmentation with occlusion has a large effect size (unlike techniques like rotation or color scaling).
https://arxiv.org/pdf/1708.04896v1.pdf
https://arxiv.org/pdf/1708.04552v1.pdf
I think this is powerful enough to add.

**Comment by alykhantejani** [comment]
This seems like it would be easy to add. @fmassa do you think this is something that would be valuable to a wide enough audience? If so I can send a PR

**Comment by hendrycks** [comment]
Here is example code for the tougher occlusion algorithm.

```python

class Occlude(object):
    def __init__(self, p=0.5, s_min=0.02, s_max=0.04, r_min=0.3):
        self.p = p  # erasing probability
        self.s_min = s_min
        self.s_max = s_max
        self.r_min = r_min
        self.r_max = 1./r_min

    def __call__(self, tensor):
        if np.random.uniform() > self.p:
            return tensor
        while True:
            Se = np.random.uniform(self.s_min,self.s_max) * 32 * 32
            re = np.random.uniform(self.r_min, self.r_max)
            He, We = np.sqrt(Se * re), np.sqrt(Se/re)
            xe, ye = np.random.uniform(0,32), np.random.uniform(0,32)
            if int(xe + We) <= 32 and int(ye + He) <= 32:
                tensor[:, int(ye):int(ye + He), int(xe):int(xe + We)].fill_(np.random.uniform())
                return tensor
```

**Comment by fmassa** [comment]
I'm unsure about adding support for such a transform for the moment.
There are many possible ways of parametrizing random occlusions, and there will always be missing cases.
I think it is easier to let the user implement their occlusion transform themselves.
I'm closing this issue, but we can revisit/reopen if you disagree.
