### ISSUE TITLE
Additional param in `torchvision.ops.nms` to set max no. of bounding boxes to return.

### ISSUE THREAD

**Issue by PseudoCodeNerd** [pytorch/vision#2275]
#### `torchvision.ops.nms(boxes, scores, iou_threshold)` --> `torchvision.ops.nms(boxes, scores, max_output_size, iou_threshold)`
Where:

- `max_output_size:` A scalar integer `Tensor` representing the maximum number of boxes to be selected by non max suppression.
## Motivation
Often, we only like a certain number of bounding boxes even after non-max suppression. This parameter accomplishes just that by returning selected indices from the `boxes` tensor of shape `[M]` where `M <= max_output_size`.

This is already implemented in Tensforflow [here](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/image/non_max_suppression).

**Comment by fmassa** [comment]
Hi,

I'm not sure it's necessary to add another argument to `nms` to specify the maximum number of boxes to return, as this can be accomplished very easily with indexing:
```python
keep = nms(boxes, scores, iou_threshold)[:max_output_size]
```
while being as efficient as if we added the parameter directly in C++. Indeed, this will return the `max_output_size` top scoring boxes after NMS, which is probably what one would want.

Given that this can be implemented efficiently with a couple of characters, I'm closing this issue as I believe it's not needed to add extra complexity, but please let me know if you disagree.

**Comment by PseudoCodeNerd** [comment]
Hey @fmassa ! Yes, I totally agree with you. In fact, I myself sliced, it that way in my code while doing object detection stuff.:smile: .I just thought that it'd be nice if there was similarity in modules of Tensorflow and PyTorch. If complexity is the case here then sure, this additional parameter can be avoided. 

Thank You.
