### ISSUE TITLE
Support new transform for converting PIL images into other mappings (RGBA for example)

### ISSUE THREAD

**Issue by KoreanJ** [pytorch/vision#2276]
## 🚀 Feature
When reading in data from a folder and using the ImageFolder class (for example), I'm requesting that an additional transform method be available for converting between color channel mappings. Namely, something of the form:
transforms.Convert('RGBA') - similar to what the PIL Image object uses to convert.

## Motivation
As found in the pil_loader function of folder.py, each image is read in as a PIL Image object and instantly converted into an RGB image. This is sub-optimal for my project since all of my images are in the RGBA format. Thus, having the option to transform each Image object would be extremely useful.

**Comment by pmeier** [comment]
Can't you slightly modify [`pil_loader`](https://github.com/pytorch/vision/blob/98aa805eb91e0378e118b654cf67c41ba2064e62/torchvision/datasets/folder.py#L152-L156) to fit your needs?

```python
from PIL import Image
from torchvision import datasets


def custom_pil_loader(path):
    with open(path, "rb") as f:
        img = Image.open(f)
        return img.convert("RGBA")


dataset = datasets.ImageFolder("/path/to/image/folder", loader=custom_pil_loader)
```

---

That being said, I'm fine with adding a `mode="RGB"` parameter to `pil_loader`:

```python
from PIL import Image
from torchvision import datasets


def pil_loader(path, mode="RGB"):
    with open(path, "rb") as f:
        img = Image.open(f)
        return img.convert(mode)


dataset = datasets.ImageFolder(
    "/path/to/image/folder", loader=lambda path: pil_loader(path, mode="RGBA")
)
```

@fmassa ?

**Comment by KoreanJ** [comment]
I did make this change for my project, but I assume I won't be the only one in the future who might want to read in images with an alpha channel. 

With the `mode="RGB"` change implemented, would I still be able to configure this without needing to directly modify any of pytorch's library source code? My project may be distributed and for those that download all dependencies, I'd rather not need to instruct them to directly modify any library code.

**Comment by pmeier** [comment]
@KoreanJ 

My second snippet in the above comment showcases that. If implemented how I imagined it, your call to `datasets.ImageFolder` would look like this in your project:

```python
from torchvision import datasets
from torchvision.datasets.folder import pil_loader

dataset = datasets.ImageFolder(
    "/path/to/image/folder", loader=lambda path: pil_loader(path, mode="RGBA")
)
```

**Comment by fmassa** [comment]
Closing following @pmeier comment.
