### ISSUE TITLE
search

### ISSUE THREAD

**Issue by kuyedie520** [pytorch/vision#2290]
想问一下该工程是这篇论文Grafted Network for Person Re-Identification的复现吗？在论文中看到这个链接不确定是不是。

**Comment by fmassa** [comment]
I don't speak chinese, but from Google translate, I got
> Would you like to ask whether the project is a reproduction of the paper Grafted Network for Person Re-Identification? Seeing this link in the paper is not sure.

We have not implemented Grafted Network for Person Re-Identification in torchvision
