### ISSUE TITLE
Video models pretrained weights on Kinetics 700

### ISSUE THREAD

**Issue by DAVEISHAN** [pytorch/vision#2296]
## 🚀 Feature
Please, add pre-trained weights for the Kinetics 700 dataset for video ResNet Models, Currently, only Kinetics 400 weights are available and it is a bit outdated now.

**Comment by bjuncek** [comment]
hi @DAVEISHAN 
This is a bit out of scope for TV, as we only provide benchmarks and minimal reproduction examples.

Please raise this issue in [Facebook's Video Model Zoo](https://github.com/facebookresearch/VMZ) repo - they should have data available (and perhaps even models ready).
