### ISSUE TITLE
 from torchvision.transforms import ImageOps ImportError: cannot import name 'ImageOps'

### ISSUE THREAD

**Issue by JsPassion** [pytorch/vision#2336]
cuda version 10.1
torch version 1.5.1
torchvision version 0.6.0
PIL version 5.2.0 

I have also tried installing Pillow version 6.1 and torchvision version 0.5.0 and torch 1.4.0 using both methods conda and pip. But the error persists. 
Kindly help!

**Comment by fmassa** [comment]
Can you try doing `from PIL import ImageOps`?

Also, can you paste the full error message that you get? It is not recommended to import `ImageOps` from torchvision, as it's a module from PIL that happens to be in the torchvision namespace.

**Comment by JsPassion** [comment]
Thank you. "from PIL import ImageOps" is working. 
The full trace is:
Traceback (most recent call last):
  File "./main.py", line 7, in <module>
    from data import get_dataset, DATASET_CONFIGS
  File "/home/js/DGR/data.py", line 4, in <module>
    from torchvision.transforms import ImageOps
ImportError: cannot import name 'ImageOps'

**Comment by fmassa** [comment]
This seems to be an issue in a codebase somewhere else than in torchvision, which relied on `ImageOps` being part of the public API of torchvision, which it isn't.

You can probably get this code working by changing to
```
from PIL import ImageOps
```
as the location of where we import `ImageOps` in torchvision has changed.

Given that this was relying on something which was not public, I'm closing this issue, but let us know if you have further questions
