### ISSUE TITLE
AttributeError: module 'torchvision.datasets' has no attribute 'USPS'

### ISSUE THREAD

**Issue by ChangweiXu** [pytorch/vision#2338]
## 🐛 Bug

When I was trying to use the USPS dataset with torchvision.datasets, the console gave me the error:

`AttributeError: module 'torchvision.datasets' has no attribute 'USPS'`

## To Reproduce

```
$ python3
>>> import torchvision as tv
>>> tv.datasets.USPS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torchvision.datasets' has no attribute 'USPS'
```

## Expected behavior

It should load the USPS dataset as shown in the documentation: [link](https://pytorch.org/docs/master/torchvision/datasets.html#usps).

## Environment

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): 1.5.1 / 0.6.1
 - OS (e.g., Linux): Win 10
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): `conda`
 - CUDA used to build PyTorch: 10.2
 - Python version: 3.7
 - CUDA version: 11.0
 - GPU models and configuration:
 - Any other relevant information:
```
[pip3] numpy==1.18.1
[pip3] torch==1.5.1
[pip3] torchvision==0.6.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              h74a9793_1
[conda] mkl                       2020.1                      216
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.1.0            py37h45dec08_0
[conda] mkl_random                1.1.1            py37h47e9c7a_0
[conda] numpy                     1.18.1           py37h93ca92e_0
[conda] numpy-base                1.18.1           py37hc3f5095_1
[conda] pytorch                   1.5.1           py3.7_cuda102_cudnn7_0    pytorch
[conda] torchvision               0.6.1                py37_cu102    pytorch
```

**Comment by pmeier** [comment]
`pip` releases seem fine. Just checked for `torch==1.5.1+cpu` and `torchvision==0.6.1+cpu`.

**Comment by fmassa** [comment]
The 0.6.1 release of torchvision [does contain USPS](https://github.com/pytorch/vision/tree/fe36f0663e231b9c875ad727cd76bc0922c9437b/torchvision/datasets), so my guess is that you might be using a different python environment for installation and execution.

If you do
```
import torchvision
print(torchvision.__version__)
```
I suspect it will print a different version than 0.6.1?

**Comment by ChangweiXu** [comment]
Bingo! That's where the problem is. Yes, the version of `torchvision` is `0.2.2`, because the default python used by the system is not the one installed by Conda. I removed the useless python and everything goes well.

Thank you all!
