### ISSUE TITLE
RandomResizedCrop aspect_ratio is wrong

### ISSUE THREAD

**Issue by SsnL** [pytorch/vision#2357]
https://github.com/pytorch/vision/blob/1a04d3c265679e1a508e7cd627006aaa9ef1ccfb/torchvision/transforms/transforms.py#L699-L714

Doc says that `ratio` is the range of the ratio of the ***original aspect ratio***, yet the sampling code implies that the range is just directly the crop aspect ratio.

**Comment by fmassa** [comment]
I agree the documentation can be improved to mention that the aspect ratio is associated with the aspect ratio of the crop before resizing.

PRs improving the documentation are welcome

**Comment by frgfm** [comment]
Hi @SsnL & @fmassa,

I just opened a fix suggestion in #2851 to close this issue!
