### ISSUE TITLE
Mismatch between the Pad documentation and actual implementation

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [pytorch/vision#236]
Hello,

When I read the documentation for the Pad transformation it clearly states that the pad argument can be a sequence. After trying all kind of types(numpy array, python list, python tuples) and constantly receiving assertion errors I decided to look at the code. It seems that the only allowed type is numbers and not sequences. Is the documentation is wrong or did I missed something ?

Thank you

**Comment by alykhantejani** [comment]
Hi @GuillaumeLeclerc 

Can you post a minimum working example showing this error, the following works for me (from master):
```Python
from PIL import Image
from torchvision.transforms import Pad
im = Image.open('tmp.jpg')
p = Pad((2,3, 4, 5))
out = p(im)
```
Granted, the docs say it accepts sequences, but it only accepts tuples for now. I will send a PR to fix this and make the docs a bit clearer.

**Comment by alykhantejani** [comment]
@fmassa this can be closed now as #239 is merged

**Comment by GuillaumeLeclerc** [comment]
I guess the issue was that I was not running the master branch (got it from pip). On my local version I had:

```python
assert isinstance(padding, numbers.Number)
```
and nothing else. So I was getting and assertion error. I will try to be more careful next time

**Comment by fmassa** [comment]
@GuillaumeLeclerc we will be cutting a new release soon so that installing from pip won't have this problem. Thanks for opening the issue!
