### ISSUE TITLE
Fix clang-format version

### ISSUE THREAD

**Issue by ezyang** [pytorch/vision#2372]
vision is clang-formatted via the default clang-format that is apt installed in CI. This is not friendly for users who are not using the exact distro in CI. We should fix a specific clang-format version and let people download clang format binaries on whatever platform they on.

This is implemented in pytorch/pytorch in tools/clang_format_all.py and related scripts. CC @suo @SplitInfinity

**Comment by datumbox** [comment]
Thanks for reporting this @ezyang. I stumbled upon this problem myself and I agree that we need to fix it. :)

First a summary of the situation: 
- **PyTorch**: As Edward pointed out, we use the [clang_format_all.py](https://github.com/pytorch/pytorch/blob/master/tools/clang_format_all.py) script to check the formatting. The script is responsible for downloading the right version of clang-format based on the OS, verifies its signature and stores it locally. Then it runs the formatter on a list of permitted directories (which unfortunately are [hardcoded](https://github.com/pytorch/pytorch/blob/master/tools/clang_format_all.py#L20)) and returns success/failure.
- **TorchVision**: Here we use the [run-clang-format.py](https://github.com/pytorch/vision/blob/master/travis-scripts/run-clang-format/run-clang-format.py) to check the formatting. Unlike on PyTorch, the formatter is installed via `apt` on cicleci's [config file](https://github.com/pytorch/vision/commit/d0b32a119ebe01b1ab846bf9266c2f114a6a4842#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R96-R97).



So it looks like we have a few options:
1. Copy PyTorch's scripts here and slightly adjust them to point to the right allowlisted directory.
2. Adjust slightly TorchVision's cicleci config file to download the clang-format binary that PyTorch uses.
3. Move the formatter scripts from PyTorch to a utils project, make scripts generic and available to all projects.

It would be great to eventually do the 3rd option but perhaps it's more realistic to fix this quickly by doing 1 or 2. Thoughts?

**Comment by SplitInfinity** [comment]
`clang_format_all.py` was introduced when there was semi-automatic formatting internally at Facebook as part of pre-commit hooks. Shortly after, Facebook began automatically formatting code internally (in allowlisted directories) every day with an automated job that runs `clang-format` and commits the result. Does `torchvision` use the same development model as `pytorch` (i.e. source of truth is inside Facebook and GitHub is more of a mirror). If so, perhaps we don't need to support `clang-format` externally at all?

**Comment by datumbox** [comment]
@SplitInfinity Currently for TorchVision it's the opposite. GitHub is the source of truth.

**Comment by fmassa** [comment]
To complement @datumbox point, torchvision now is in a mixed state where most of the development happens in GitHub, but we do have an internal sync via ShipIt but on a separate branch than master (named `fbsync`).
This means that for now we are both out of sync (commits added on both sides), and we might as well have lint differences due to the automatic formatting within FB.

**Comment by fmassa** [comment]
Fixed in #2872
