### ISSUE TITLE
NVCC_FLAGS not needed in pkg_helpers.bash anymore?

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#2377]
In `pkg_helpers.bash` and in a number of packaging files for Windows, we hard-code `NVCC_FLAGS` for different compute capabilities
https://github.com/pytorch/vision/blob/fa6af6d1e6f050d0a930e6f59894b7dd40aa869c/packaging/pkg_helpers.bash#L61
As mentioned in a comment by @ezyang in
https://github.com/pytorch/vision/blob/fa6af6d1e6f050d0a930e6f59894b7dd40aa869c/packaging/pkg_helpers.bash#L59-L60
hardcoding `gencode` was meant to be temporary until https://github.com/pytorch/pytorch/pull/23408 gets merged (which it has been).

Maybe it would be possible to do some cleanups in the repo today that those improvements in PyTorch have been made.

**Comment by ezyang** [comment]
Yes, let's remove them and see if things still work.
