### ISSUE TITLE
How to Change All BN layers to GN layers?

### ISSUE THREAD

**Issue by mobassir94** [pytorch/vision#2391]
i tried this : 

```
import torchvision.models as models
model  = models.resnet18()

#then this : 

for name, module in model.named_modules():
    if isinstance(module, nn.BatchNorm2d):
        # Get current bn layer
        bn = getattr(model, name)
        # Create new gn layer
        gn = nn.GroupNorm(1, bn.num_features)
        # Assign gn
        print('Swapping {} with {}'.format(bn, gn))
        setattr(model, name, gn)

print(model)
```

and it gives this error :

```
Swapping BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True) with GroupNorm(1, 64, eps=1e-05, affine=True)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-dc2f23e093cc> in <module>
      2     if isinstance(module, nn.BatchNorm2d):
      3         # Get current bn layer
----> 4         bn = getattr(model, name)
      5         # Create new gn layer
      6         gn = nn.GroupNorm(1, bn.num_features)

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in __getattr__(self, name)
    592                 return modules[name]
    593         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 594             type(self).__name__, name))
    595 
    596     def __setattr__(self, name, value):

AttributeError: 'ResNet' object has no attribute 'layer1.0.bn1'
```

**Comment by pmeier** [comment]
The problem you are facing stems from the fact that `getattr` and `setattr` only work on the direct children of an `nn.Module` while `nn.Module.named_modules()` recursively returns all sub-modules. 

You can try something like this:

```python
def get_layer(model, name):
    layer = model
    for attr in name.split("."):
        layer = getattr(layer, attr)
    return layer


def set_layer(model, name, layer):
    try:
        attrs, name = name.rsplit(".", 1)
        model = get_layer(model, attrs)
    except ValueError:
        pass
    setattr(model, name, layer)


for name, module in model.named_modules():
    if isinstance(module, nn.BatchNorm2d):
        # Get current bn layer
        bn = get_layer(model, name)
        # Create new gn layer
        gn = nn.GroupNorm(1, bn.num_features)
        # Assign gn
        print("Swapping {} with {}".format(bn, gn))

        set_layer(model, name, gn)

print(model)
```

`get_layer` and `set_layer` have the same signature as `getattr` and `setattr` but will handle the sub-modules for you.

**Comment by mobassir94** [comment]
@pmeier thank you a lot,i tried your code and it gave me no error!
can you pleace check if  my implementation has any bug for efficientnet-b0 bn to gn changing? 
here  is my code : 
```
for  i in range(0,len(model.enet._blocks)):
    try:
        print("...........found BN layer  so Replacing Bn0 with GN.........")
        gn0 = model.enet._blocks[i]._bn0.num_features
        model.enet._blocks[i]._bn0 = nn.GroupNorm(1,num_channels = gn0)
        print(model.enet._blocks[i]._bn0)
        
    except:
        print("BN layer Not  found!!")
        
    gn1 = model.enet._blocks[i]._bn1.num_features
    gn2 = model.enet._blocks[i]._bn2.num_features
    
    model.enet._blocks[i]._bn1 = nn.GroupNorm(1,num_channels = gn1)
    model.enet._blocks[i]._bn2 = nn.GroupNorm(1,num_channels = gn2)
    
    print(model.enet._blocks[i]._bn1)
    print(model.enet._blocks[i]._bn2)
  
gn0 = model.enet._bn0.num_features
gn1 = model.enet._bn1.num_features

model.enet._bn0 = nn.GroupNorm(1,num_channels = gn0)
model.enet._bn1 = nn.GroupNorm(1,num_channels = gn1)

model = model.to(device)

```

when  i try this code i see all bn layers changed to gn layers but surprisingly i see train loss is not nan but validation loss is nan and also model outputting nan.i get this error : ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

full error trace : 

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>

<ipython-input-17-b768044886f5> in val_epoch(loader, get_output)
     49     acc = (PREDS == TARGETS).mean() * 100.
     50 
---> 51     qwk = cohen_kappa_score(PREDS, TARGETS, weights='quadratic')
     52     qwk_k = cohen_kappa_score(PREDS[df_valid['data_provider'] == 'karolinska'], df_valid[df_valid['data_provider'] == 'karolinska'].isup_grade.values, weights='quadratic')
     53     qwk_r = cohen_kappa_score(PREDS[df_valid['data_provider'] == 'radboud'], df_valid[df_valid['data_provider'] == 'radboud'].isup_grade.values, weights='quadratic')

/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py in cohen_kappa_score(y1, y2, labels, weights, sample_weight)
    583     """
    584     confusion = confusion_matrix(y1, y2, labels=labels,
--> 585                                  sample_weight=sample_weight)
    586     n_classes = confusion.shape[0]
    587     sum0 = np.sum(confusion, axis=0)

/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py in confusion_matrix(y_true, y_pred, labels, sample_weight, normalize)
    266 
    267     """
--> 268     y_type, y_true, y_pred = _check_targets(y_true, y_pred)
    269     if y_type not in ("binary", "multiclass"):
    270         raise ValueError("%s is not supported" % y_type)

/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py in _check_targets(y_true, y_pred)
     79     """
     80     check_consistent_length(y_true, y_pred)
---> 81     type_true = type_of_target(y_true)
     82     type_pred = type_of_target(y_pred)
     83 

/opt/conda/lib/python3.7/site-packages/sklearn/utils/multiclass.py in type_of_target(y)
    282     if y.dtype.kind == 'f' and np.any(y != y.astype(int)):
    283         # [.1, .2, 3] or [[.1, .2, 3]] or [[1., .2]] and not [1., 2., 3.]
--> 284         _assert_all_finite(y)
    285         return 'continuous' + suffix
    286 

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
     58                     msg_err.format
     59                     (type_err,
---> 60                      msg_dtype if msg_dtype is not None else X.dtype)
     61             )
     62     # for object dtype data, we only check for NaNs (GH-13254)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').`

also can you please tell me  how to change those BN layers with Filter Response Normalization (FRN) layers in my model?

**Comment by pmeier** [comment]
@mobassir94 

> can you pleace check if my implementation has any bug for efficientnet-b0 bn to gn changing?

Please note that this issue tracker is not a help form and this issue will be closed. Our primary means of support is our [discussion forum](https://discuss.pytorch.org).

> i see train loss is not nan but validation loss is nan and also model outputting nan.

This indicates that most likely one of the following is happening:

- You validation data is corrupt and has `NaN` values from the start or
- you are handling training and validation differently.

I can't be more precise since apparently the conversion worked and the error trace you posted is unrelated to `torch` or `torchvision`. If you want to ask your question in the discussion forum, I suggest you compile a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) that shows your actual problem. Without one it is a lot harder to help you.

**Comment by mobassir94** [comment]
thanks @pmeier 
the two points you mentioned shouldn't be true in my case because same model works fine when i don't try to change bn with gn layers,i posted everywhere and got no  help,i will share my full model code here,if you can help me then i will be happy otherwise thank you a lot for providing your solution,here is my full code : 

```
from torch.nn.parameter import Parameter
def gem(x, p=3, eps=1e-6):
    return F.avg_pool2d(x.clamp(min=eps).pow(p), (x.size(-2), x.size(-1))).pow(1./p)
class GeM(nn.Module):
    def __init__(self, p=3, eps=1e-6):
        super(GeM,self).__init__()
        self.p = Parameter(torch.ones(1)*p)
        self.eps = eps
    def forward(self, x):
        return gem(x, p=self.p, eps=self.eps)       
    def __repr__(self):
        return self.__class__.__name__ + '(' + 'p=' + '{:.4f}'.format(self.p.data.tolist()[0]) + ', ' + 'eps=' + str(self.eps) + ')'

    
class enetv2(nn.Module):
    def __init__(self, backbone, out_dim):
        super(enetv2, self).__init__()
        self.enet = enet.EfficientNet.from_name(backbone)
        self.enet.load_state_dict(torch.load(pretrained_model[backbone]))

        self.myfc = nn.Linear(self.enet._fc.in_features, out_dim)
        self.enet._fc = nn.Identity()

    def extract(self, x):
        return self.enet(x)

    def forward(self, x):
        x = self.extract(x)
        x = self.myfc(x)
        return x

def train_epoch(loader, optimizer):

    model.train()
    train_loss = []
    bar = tqdm(loader)
    for (data, target) in bar:
        
        data, target = data.to(device), target.to(device)
        loss_func = criterion
        optimizer.zero_grad()
        logits = model(data)
        loss = loss_func(logits, target)
        loss.backward()
        optimizer.step()

        loss_np = loss.detach().cpu().numpy()
        train_loss.append(loss_np)
        smooth_loss = sum(train_loss[-100:]) / min(len(train_loss), 100)
        bar.set_description('loss: %.5f, smth: %.5f' % (loss_np, smooth_loss))
    return train_loss


def val_epoch(loader, get_output=False):

    #model.eval()
    val_loss = []
    LOGITS = []
    PREDS = []
    TARGETS = []

    with torch.no_grad():
        for (data, target) in tqdm(loader):
            data, target = data.to(device), target.to(device)
            logits = model(data)

            loss = criterion(logits, target)

            pred = logits.sigmoid().sum(1).detach().round()
            LOGITS.append(logits)
            PREDS.append(pred)
            TARGETS.append(target.sum(1))

            val_loss.append(loss.detach().cpu().numpy())
        val_loss = np.mean(val_loss)

    LOGITS = torch.cat(LOGITS).cpu().numpy()
    PREDS = torch.cat(PREDS).cpu().numpy()
    TARGETS = torch.cat(TARGETS).cpu().numpy()
    acc = (PREDS == TARGETS).mean() * 100.
    
    qwk = cohen_kappa_score(PREDS, TARGETS, weights='quadratic')
    qwk_k = cohen_kappa_score(PREDS[df_valid['data_provider'] == 'karolinska'], df_valid[df_valid['data_provider'] == 'karolinska'].isup_grade.values, weights='quadratic')
    qwk_r = cohen_kappa_score(PREDS[df_valid['data_provider'] == 'radboud'], df_valid[df_valid['data_provider'] == 'radboud'].isup_grade.values, weights='quadratic')
    print('qwk', qwk, 'qwk_k', qwk_k, 'qwk_r', qwk_r)

    if get_output:
        return LOGITS
    else:
        return val_loss, acc, qwk

model = enetv2("efficientnet-b0", out_dim=5)
model = model.to(device)

model.avg_pool = GeM()


for  i in range(0,len(model.enet._blocks)):
    try:
        print("...........found BN layer  so Replacing Bn0 with GN.........")
        gn0 = model.enet._blocks[i]._bn0.num_features
        model.enet._blocks[i]._bn0 = nn.GroupNorm(1,num_channels = gn0)
        print(model.enet._blocks[i]._bn0)
        
    except:
        print("BN layer Not  found!!")
        
    gn1 = model.enet._blocks[i]._bn1.num_features
    gn2 = model.enet._blocks[i]._bn2.num_features
    
    model.enet._blocks[i]._bn1 = nn.GroupNorm(1,num_channels = gn1)
    model.enet._blocks[i]._bn2 = nn.GroupNorm(1,num_channels = gn2)
    
    print(model.enet._blocks[i]._bn1)
    print(model.enet._blocks[i]._bn2)

gn0 = model.enet._bn0.num_features
gn1 = model.enet._bn1.num_features

model.enet._bn0 = nn.GroupNorm(1,num_channels = gn0)
model.enet._bn1 = nn.GroupNorm(1,num_channels = gn1)

model = model.to(device)
```

**Comment by mobassir94** [comment]
that same model works fine when i don't try to change  bn with gn layers like i did in last comments code,thank you a lot anyway for your massive help

**Comment by pmeier** [comment]
Don't see the following as rude, but rather as educational:

1. This is most likely not a bug, but a user error. There is no shame in that, but it simply does not belong in an issue tracker as stated above. Please ask you question in the discussion forum.
2. If you want others to help you, you need to provide a minimal example of the problem you are facing:
    1. It has to be self-contained. I need to be able to copy & paste it into my editor and should get the same results as you. Pay attention to `import`s. If you need data either generate some fake or provide it together with the question.
    2. It has to be stripped of any unnecessary details. That is, it should no include any line of code that is not used to reproduce your issue.

    Yes, I know that requires work, but you are expecting us to invest some time in your issue so we can expect the same from you.

If you follow my suggestions feel free to tag me in the question. I use the same handle @pmeier in the discussion forum.

**Comment by mobassir94** [comment]
@pmeier  sorry, this question was asked under "question and answer" section of github issues, so i think i have right to ask questions as it was not posted under "bug issues" section

sorry my dataset size is 400 GB,i don't know how to share the code that you can run in your machine without downloading that huge dataset,i just wanted you to check if any line of code from my solution is having bug or not but i understand you need to run and  check which is also difficult as the dataset size is huge,
sorry for wasting your time and thank you for helping me

**Comment by fmassa** [comment]
Hi,

I believe the original question has been answered (converting BN to GN), and now the issue is with getting NaN's during training on a script that we do not fully have, nor on data that we know about.
Note that if your model get's NaNs, there can be a lot of potential causes, one of them being a too large learning rate.

As @pmeier mentioned, we use GitHub issues to track bug reports or feature requests, and modeling issues are better suited for the discussion forums.

If you didn't have yet any reply there, please follow what @pmeier suggested, those are great advices.
