### ISSUE TITLE
save_image behavior

### ISSUE THREAD

**Issue by rtqichen** [pytorch/vision#24]
https://github.com/pytorch/vision/blob/master/torchvision/utils.py#L52

The `.mul(0.5).add(0.5)` in this line seems to be assuming that the input values are in [-1,1]? Isn't the Torch convention to use [0,1] for images?

**Comment by stepelu** [comment]
Personally, I vote for having a default behavior that assumes a range [0, 1] and doesn't normalize the image.
Doing otherwise would result in issues like the mentioned #41 and potentially introduce bugs difficult to spot (as the normalization is "silent").

**Comment by soumith** [comment]
This is fixed in master by removing the offset, but definitely having a range parameter would be quite useful!
