### ISSUE TITLE
ToPILImage assumes RGB for 3 channel ndarrays

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/vision#244]
I think the `ToPILImage` transform is great however, looking internally it seems it makes some assumptions about color spaces. i.e. if you pass a 3-channel ndarray to the transform it loads it tells PIL that this should be interpreted as `RGB`, however it could easily be `YCbCr`, `HSV` or `LAB` (these are the 3 channel formats [supported by PIL](http://pillow.readthedocs.io/en/3.4.x/handbook/concepts.html#concept-modes))

Additionally, there is [a PR](https://github.com/pytorch/vision/pull/189/files) to add `RGBA` support, assuming 4 channel ndarrays are `RGBA`, whereas PIL also supports `CMYK`.

Perhaps we should change the transform slightly, by allowing the `__init__` function to accept the image mode it should convert to (where the mode is a PIL `Image` mode)? Happy to send a PR for this if you think this is a good idea

**Comment by iacolippo** [comment]
I found myself needing this feature, so my opinion is positive about this change

**Comment by iammarvelous** [comment]
What about grey scale image (H*W) or a set of image stacked together (H*W*C) with C is an arbitrary number?

**Comment by fmassa** [comment]
I think this would be a nice feature to have. Assigning @alykhantejani for this task.

**Comment by fmassa** [comment]
Fixed via #300
