### ISSUE TITLE
Add testing for aligned flag in RoIAlign

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#2440]
RoIAlign with `aligned=True` doesn't currently have tests.
We should extend the testing for RoIAlign to take into account a few different cases, including https://github.com/pytorch/vision/pull/2438

**Comment by clemkoa** [comment]
Hey, I'd be happy to look into this if no else has already started.

**Comment by fmassa** [comment]
Hi,

Please go ahead @clemkoa !
