### ISSUE TITLE
Custom Weights for Pytorch Hub for yolo v5

### ISSUE THREAD

**Issue by sakshamjn** [pytorch/vision#2449]
Hello
Just wanted to know if there a way of import yolo v5 model using PyTorch Hub and then loading my custom weights on top of it.

**Comment by pmeier** [comment]
Hi @sakshamjn 

> Just wanted to know if there a way of import yolo v5 model using PyTorch Hub

If didn't miss anything, we currently do not provide a pre-trained model for YOLOv5 or any other YOLO variant for that matter.

 > and then loading my custom weights on top of it.

That begs the question why you would want to load a pre-trained variant first if you already have weights? How did you acquire them?

**Comment by sakshamjn** [comment]
The thing is I wanted to load the Yolo v5 model without using .yaml file during production. That's why I am looking for other options like PyTorch Hub.
And for the training part I took pre trained weights and on top of that I trained my custom model. But during deployment I want some better way to do so.

**Comment by pmeier** [comment]
@sakshamjn 

Its easy to create your own (possible untrained) model that is loadable with [`torch.hub`](https://pytorch.org/docs/stable/hub.html). In short you need a `hubconf.py` file where you define your model (say `yolo_v5`) in the top level of a GitHub repository. If you have that, you can simply do the following for production:

```python
import torch

model = torch.hub.load('sakshamjn/yolo_v5_repo', 'yolo_v5')

state_dict = torch.load("my_secret_weights.pth")
model.load_state_dict(state_dict)
```
