### ISSUE TITLE
Latest version number on PyPi is 0.1.9 but this repo only goes till 0.1.8

### ISSUE THREAD

**Issue by y0ast** [pytorch/vision#246]
https://pypi.python.org/pypi/torchvision mentions 0.1.9 (markup looks weird too).

However this repo only specifies 0.1.8 as latest: https://github.com/pytorch/vision/releases

What's the groundtruth? Is that PyPi version safe to use?

**Comment by alykhantejani** [comment]
The version was indeed bumped  in the `setup.py` [here](https://github.com/pytorch/vision/blob/master/setup.py#L9) it seems as though the release notes were forgotten.  cc @soumith

**Comment by soumith** [comment]
done https://github.com/pytorch/vision/releases/tag/v0.1.9

**Comment by soumith** [comment]
thanks to Aly for actually writing the release notes.
