### ISSUE TITLE
[IO] Add warning in torchvision.io if seeking for a pts out of the video. Silent error otherwise

### ISSUE THREAD

**Issue by JuanFMontesinos** [pytorch/vision#2460]
## 🚀 Feature
Add a warning/error when reading a video using `torchvision.io.read_video` and seeking for a timestamp which points out of the video.

## Motivation
Example:
I have a video which is 30s duration.
I ask video reader to load from t= 35 to t=50.
reader will silently fail to do so and will return the last frame of the video stream.

## Pitch

I want to add a simple warning/error to prevent that. Like: 
`BufferError('Video stream is trying to seek out of bounds. %s'video_path)`
Can be easily done by checking if max(pts)<seek_offset.   

Kindly suggested
Juan M

**Comment by bjuncek** [comment]
Yeah I think this makes sense short term.
Did you think of doing it on the python side? That would be convenient as one could shut them up in one place if they were annoying.

**Comment by JuanFMontesinos** [comment]
Do you mean in a PR? 
Sooo I don't think such a warning/exception would be annoying. Anyway if you set a wrong timestamp to seek, an error will be eventually thrown due to size mismatching in the dataloader.

**Comment by bjuncek** [comment]
Sorry for being unclear:
1. Yes I agree that would be useful, but, this would only really work post mortem. Getting duration from a video can be very unpredictable before we actually decode it. 
2.  Yes in a PR - I just wanted to make sure that the warning is issued in the python part of the VideoReader :)

**Comment by pmeier** [comment]
@JuanFMontesinos if you create a PR adding this, could you have a look at #2510 and fix this too if applicable?

**Comment by JuanFMontesinos** [comment]
Closing issue after PR.
