### ISSUE TITLE
couldn't import models from torchvision

### ISSUE THREAD

**Issue by Lothakim** [pytorch/vision#2461]
I was using the textbook **Deep-Learning-with-PyTorch** to get familiar with the pytorch. Here I tried to
`from torchvision import models`
but failed, the error message is
`module 'torch.jit' has no attribute '_script_if_tracing'`
I have no idea what's wrong. Please help, thank you

**Comment by pmeier** [comment]
Hi @Lothakim, what version of `torch` and `torchvision` are you using? If you are unsure please run

```python
import torch
import torchvision

print(torch.__version__)
print(torchvision.__version__)
```

**Comment by Lothakim** [comment]
> Hi @Lothakim, what version of `torch` and `torchvision` are you using? If you are unsure please run
> 
> ```python
> import torch
> import torchvision
> 
> print(torch.__version__)
> print(torchvision.__version__)
> ```

Thank you!
My `pytorch` version is 1.5.0, but I even couldn't `import torchvision`, with the same error message `module 'torch.jit' has no attribute '_script_if_tracing'`
I just cloned this repository yesterday, so I guess the `torchvision` is supposed to be up to date.

**Comment by fmassa** [comment]
For posterity, this error happens if your PyTorch version is not new enough.
