### ISSUE TITLE
Migrate ONNX tests to CircleCI

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#2494]
Currently the ONNX tests run on Travis CI as a last remnant whereas all other checks have been migrated to CircleCI. For the sake of uniformity we should also migrate these tests. I volunteer to have a got at this with a major disclaimer: I have never worked with ONNX and only very little with CircleCI so I'm maybe up for quite a ride. 

@fmassa could you tag in the people that might be able to help if I hit obstacles that I don't know how to get around?

**Comment by fmassa** [comment]
@neginraoof is our reference for all ONNX-related changes.

**Comment by fmassa** [comment]
Fixed in https://github.com/pytorch/vision/pull/3144
