### ISSUE TITLE
Number of anchors VS. number of aspect ratios.

### ISSUE THREAD

**Issue by fulkast** [pytorch/vision#2508]
https://github.com/pytorch/vision/blob/1aef87d01eec2c0989458387fa04baebcc86ea7b/torchvision/models/detection/faster_rcnn.py#L188

The line above seems to fetch, for each location, the number of aspect ratios of anchors (not multiplying by the number of different sized anchors).

**Comment by fmassa** [comment]
Hi,

In the current implementation, we assume that each feature map has the same number of reference anchors per location.

But we do take into account the number of different sized anchors, see https://github.com/pytorch/vision/blob/1aef87d01eec2c0989458387fa04baebcc86ea7b/torchvision/models/detection/rpn.py#L112

I believe I have answered your question, and as such I'm closing this issue, but let us know if you have further questions.
