### ISSUE TITLE
Resize sometimes fails

### ISSUE THREAD

**Issue by ag14774** [pytorch/vision#2517]
https://github.com/pytorch/vision/blob/300ef76d3b6e9c33c58cd124e5f5514a927cadf1/torchvision/transforms/functional_tensor.py#L589

The specific line above will sometimes cause the image to be returned unresized with no warning even when an explicit size (h,w) is given. This will also cause problems to the transform `RandomResizedCrop`.

**Comment by fmassa** [comment]
Thanks for the fix @ag14774 !
