### ISSUE TITLE
Different types of IoU

### ISSUE THREAD

**Issue by kennyFF92** [pytorch/vision#2545]
## 🚀 Feature

Implementation of 3 other types of IoU metric in torchvision.ops.boxes:
1. Generalized IoU
2. Distance IoU
3. Complete IoU

## Motivation

Since these metrics can lead to better results in some cases (object detection, etc.) it could be useful to have them natively implemented.

## Pitch

Users who need IoU computation can simply choose from 4 different implementation using the same inputs (e.g. two lists of boxes).

## Additional context

Mathematical details can be found here:
1. Generalized IoU: [Generalized Intersection over Union](https://giou.stanford.edu/)
2. Distance/Complete IoU: [Distance-IoU Loss: Faster and Better Learning for Bounding Box Regression](https://arxiv.org/abs/1911.08287)

**Comment by fmassa** [comment]
Hi,

This is a good request. I have seen benefits for Generalized IoU in the past, although for us Distance / Complete IoU didn't show any benefits.

From a number of citations perspective, I would say that we could currently add Generalized IoU to torchvision, and wait a bit more on Distance / Complete IoU to see if more people find it helpful.

**Comment by fmassa** [comment]
For information, here is [an implementation for Generalized IoU](https://github.com/facebookresearch/detr/blob/f4cdc542de34de771da8b9189742e5465f5220cd/util/box_ops.py#L40-L61) that fits the same API as the IoU from torchvision

**Comment by kennyFF92** [comment]
> 
> 
> For information, here is [an implementation for Generalized IoU](https://github.com/facebookresearch/detr/blob/f4cdc542de34de771da8b9189742e5465f5220cd/util/box_ops.py#L40-L61) that fits the same API as the IoU from torchvision

I already had an implementation and now I aligned it to the one you mentioned. I'd like to contribute with a pull request but I can't find a guide for contributing and I don't want to create too many problems

**Comment by fmassa** [comment]
For contributing, the standard guidelines apply:
- fork the repo and create a branch for the feature
- add tests and documentation
- send the pull request and make sure that all tests pass (including lint)

**Comment by oke-aditya** [comment]
Hello, @fmassa can I contribute to this issue?
I am new to contributing to torchvision but highly interested.
