### ISSUE TITLE
Functional affine documentation for Version 1.6.0 on torchvision.functional.transform.affine does not match code

### ISSUE THREAD

**Issue by Mut1nyJD** [pytorch/vision#2551]
## 📚 Documentation

If you check the documentation on pytorch.org go to Libraries torchvision/ transforms / functional transforms

https://pytorch.org/docs/stable/torchvision/transforms.html#functional-transforms

Look at torchvision.transforms.functional.affine
the documentation says under parameters:

img (PIL Image or Tensor) – image to be rotated.

But when you actually use a tensor as input using the official pywheel torchvision0.7cu101 package a tensor import is not supported  if you look at the source code torchvision/transforms/functional.py from the installed package, there is a line like this:

   if not _is_pil_image(img):
        raise TypeError('img should be PIL Image. Got {}'.format(type(img)))

Also that source code from the installed package for the function does not match the source link in the pytorch.,org online documentation

**Comment by fmassa** [comment]
Hi,

I think there might be an issue with the documentation, which is pointing to the master branch and not the 1.6.0 branch.

@jlin27 can you look into this?

**Comment by jlin27** [comment]
Looks like for the last release, the vision docs were pinned to master instead of release/0.7. I'll check if there is any issue reversing that and if not, re-build the docs based off of stable

**Comment by jlin27** [comment]
Rebuilt the docs and pushing out the release/0.7 vision docs in this PR: https://github.com/pytorch/pytorch.github.io/pull/458
