### ISSUE TITLE
broken link to documentation in readme

### ISSUE THREAD

**Issue by martinResearch** [pytorch/vision#2557]
## 🐛 Bug
 the link to the documentation in the readme file [http://pytorch.org/docs/master/torchvision/](http://pytorch.org/docs/master/torchvision/) is broken. It should be replaced by [https://pytorch.org/docs/stable/torchvision](https://pytorch.org/docs/stable/torchvision) I believe.

**Comment by vfdev-5** [comment]
This issue is probably related to https://github.com/pytorch/vision/issues/2551 
Instead of stable docs, master version is shown.

**Comment by fmassa** [comment]
cc @jlin27

**Comment by jlin27** [comment]
Looks like for the last release, the vision docs were pinned to master instead of release/0.7. I'll check if there is any issue reversing that and if not, re-build the docs based off of stable

**Comment by jlin27** [comment]
Rebuilt the docs and pushing out the release/0.7 vision docs in this PR: pytorch/pytorch.github.io#458
