### ISSUE TITLE
怎么去链接自己的PYTHON3

### ISSUE THREAD

**Issue by ts19970816** [pytorch/vision#2567]
ts@ts:~/opt/vision-master/build$ cmake -DCMAKE_PREFIX_PATH=/opt/libtorch-cxx11-abi-shared-with-deps-1.5.0/libtorch -DCMAKE_INSTALL_PREFIX=/where/to/install/torchvision -DCMAKE_BUILD_TYPE=Release ..
CMake Warning at CMakeLists.txt:13 (find_package):
  By not providing "FindPython3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python3" with any
  of the following names:

    Python3Config.cmake
    python3-config.cmake

  Add the installation prefix of "Python3" to CMAKE_PREFIX_PATH or set
  "Python3_DIR" to a directory containing one of the above files.  If
  "Python3" provides a separate development package or SDK, be sure it has
  been installed.

-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found cuDNN: v7.6.5  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ts/opt/vision-master/build

**Comment by fmassa** [comment]
Hi,

Please describe what you are trying to do and the problem you are facing. Given that there is no information in this issue that is actionable, I'm closing this issue.

For information, we recommend installing torchvision via conda / pypi using the information in https://pytorch.org/get-started/locally/
