### ISSUE TITLE
Circle CI is broken for Windows

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#2570]
## 🐛 Bug

Currently, CI is failing on `binary_win_conda_py3.8_cu102` test :

> PyTorch version auto detection failed
> No package found for CU_VERSION=cu102 and PYTHON_VERSION=3.8

https://app.circleci.com/pipelines/github/pytorch/vision/3519/workflows/c73b0f3d-9097-456f-b408-337a278a9c8c/jobs/198662/steps

cc @peterjc123 @nbcsm @guyang3532 @maxluk @gunandrose4u @smartcat2010 @mszhanyi

**Comment by nbcsm** [comment]
@guyang3532

**Comment by guyang3532** [comment]
This happened because the nightly build job failed and the packages were not uploaded to conda. It have been fixed by https://github.com/pytorch/builder/pull/487.

**Comment by vfdev-5** [comment]
@guyang3532 thanks for the info ! Yes, now Circle CI is passing. 

I'm closing the issue as resolved.

**Comment by fmassa** [comment]
Re-opening because this is happening again.

cc @peterjc123 is this because the nightly build job from Windows failed again? We should maybe try to find a way to overcome PyTorch nightlies being broken so that this doesn't affect us

**Comment by peterjc123** [comment]
@vfdev-5 Yes, but nightly jobs are naturely flaky. You may ask @seemethere to perserve the legacy packages (in Anaconda Cloud) if the new packages fail to generate.

**Comment by vfdev-5** [comment]
@seemethere cuda9.2 support was dropped in pytorch-nightly ? 

Probably, the tests here should be adapted to the change.

https://app.circleci.com/pipelines/github/pytorch/vision/3723/workflows/f4de1c00-c5ab-4c59-9942-be823c944d5b

**Comment by peterjc123** [comment]
@vfdev-5 I'll do this.
