### ISSUE TITLE
Travis CI is broken on onnx tests

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#2571]
## 🐛 Bug

Currently, Travis CI is failing on `test_onnx.py`

> E       onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Greater_1795:Greater(9)

https://travis-ci.org/github/pytorch/vision/jobs/716516509#L704

**Comment by fmassa** [comment]
@neginraoof can you have a look?

**Comment by vfdev-5** [comment]
@neginraoof could you please take a look why it is failling again : https://travis-ci.org/github/pytorch/vision/jobs/720634157#L716
Thanks !

**Comment by vfdev-5** [comment]
@neginraoof is something blocking to fix the onnx issues ? Currenlty, it remains Travis CI which is still failing...

**Comment by fmassa** [comment]
I think @neginraoof sent a fix to PyTorch in https://github.com/pytorch/pytorch/pull/43670 but it's pending to be merged

**Comment by vfdev-5** [comment]
Let's close the issue as solved : travis ci passes the failing onnx tests and pytorch/pytorch#43670 was merged.

**Comment by vfdev-5** [comment]
@neginraoof could you please update ort-nightly version in another PR as CI is failing now : https://travis-ci.org/github/pytorch/vision/jobs/737360863#L561 . Thanks !
