### ISSUE TITLE
NMS not available with CUDA backend in 0.7.0

### ISSUE THREAD

**Issue by vcarpani** [pytorch/vision#2575]
## 🐛 Bug

After converting a maskrcnn model torchscript and loading it in c++, with torchvision version 0.7.0 I get:
```
RuntimeError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. 'torchvision::nms' is only available for these backends: [CPU].
```

With torchvision 0.7.0-rc2 I do not have this problem, it looks to be related to the new `autocast` functionality.

## Environment

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): 1.6.0 / 0.7.0
 - OS (e.g., Linux): Arch Linux
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): packet manager (pacman) / built from source
 - Build command you used (if compiling from source): cmake FORCE_CUDA=ON && make $$ make install
 - Python version: 3.8
 - CUDA/cuDNN version: 11.0.2 / 8.0.0
 - GPU models and configuration: 2080Ti

**Comment by fmassa** [comment]
Hi,

Can you run it with CUDA on Python? Does this only happen when exporting the model to torchscript and running it in C++?

Maybe we need to change something in our CMake / C++ API so that this gets visible on C++ land.

cc @ezyang @mcarilli for thoughts

**Comment by vcarpani** [comment]
Hi, thanks for the quick response, I had the model running in python directly, but I did not try with python torchscript, I will test it later today

**Comment by vcarpani** [comment]
The following code works:
```
import torch
import torchvision
from PIL import Image
img = Image.open('./test_image.png').convert("RGB")
x = torchvision.transforms.ToTensor()(img)
model = torch.jit.load('./model.pt')
res = model([x.to(device="cuda")])
```

**Comment by ezyang** [comment]
The most obvious explanation is you didn't actually link against torchvision cuda libraries. You need to make sure you pass `-Wl,--no-as-needed` or something like that

**Comment by vcarpani** [comment]
This is my CMakeLists.txt right now:

```
find_package(Torch REQUIRED)
find_package(TorchVision REQUIRED)

add_library(${PROJECT_NAME}
	src/detection_model.cpp
)

target_link_libraries(${PROJECT_NAME}
	${TORCH_LIBRARIES}
	-Wl,--no-as-needed
	TorchVision::TorchVision
	-Wl,--as-needed
)

add_executable(server
	src/server/main.cpp
)

target_link_libraries(server
	${PROJECT_NAME}
)
```

I also tried adding `--whole-archive` and adding the same linker flags when linking the `server` executable to `${PROJECT_NAME}`

**Comment by fmassa** [comment]
Fixed with https://github.com/pytorch/vision/pull/2585
