### ISSUE TITLE
Calculate Training Accuracy on resnet152

### ISSUE THREAD

**Issue by FrostByteGER** [pytorch/vision#2578]
I'm trying to calculate training accuracy on resnet152, however
`loss_dict = model(images, targets)`
only contains loss values. 

Usually the model accepts only the images and the outputs are then passed to a loss function as well as used to calculate the accuracy. Calling it without the targets parameter results in:
`ValueError: In training mode, targets should be passed`

Sorry if this is the wrong place, I'm still quite a beginner.

**Comment by pmeier** [comment]
Hi @FrostByteGER 

this is an issue tracker and not a help form. Our primary means of support is our [discussion forum](https://discuss.pytorch.org/). As such I'm closing this issue.

---

> Usually the model accepts only the images and the outputs are then passed to a loss function as well as used to calculate the accuracy.

That is correct: 

https://github.com/pytorch/vision/blob/c547e5cbbf25e46870abb2e925b42c67c3367afc/torchvision/models/resnet.py#L219

Thus `loss_dict = model(images, targets)` is not a valid call if `model` is a `ResNet` variant from `torchvision`. Furthermore the `ValueError` is not raised by us. 

Together that implies you are using something else besides vanilla `torchvision`. You might want to include more details in future question so other have a better chance to help you.
