### ISSUE TITLE
Is this line reading 1GB chunk instead of 1MB as in comment?

### ISSUE THREAD

**Issue by wilburwu** [pytorch/vision#258]
https://github.com/pytorch/vision/blob/8648132c957a68e025d4c9bcfff14b3bc540c6af/torchvision/datasets/utils.py#L13

**Comment by soumith** [comment]
documentation of `read` says: `Read at most size bytes from the file`.

1024 * 1024 * 1024 bytes = 1MB

**Comment by wilburwu** [comment]
1024 bytes = 1KB
1024 * 1024 bytes = 1024 * 1KB = 1MB ?

**Comment by soumith** [comment]
oh you are right, it's reading 1GB

**Comment by soumith** [comment]
it's a bug!

**Comment by fmassa** [comment]
@wilburwu can you send a PR fixing it?

**Comment by wilburwu** [comment]
PR: #259
