### ISSUE TITLE
Support for torchvision.ops.nms on pytorch mobile

### ISSUE THREAD

**Issue by hal-314** [pytorch/vision#2581]
## ❓ Questions and Help

You can't deploy object detection models like yolo, FastRCNN, etc without nms op. There are several issues in the forum. https://discuss.pytorch.org/t/support-torchvision-ops-nms-on-mobile-cpu/69627 or in this repo https://github.com/pytorch/vision/issues/2050 . 

So, there is any eta for this? I want to use [YoloV5](https://github.com/ultralytics/yolov5) to detect objects with a smartphone. I have read the code and it seems to have a fairly straight forward implementation. So, I don't know why Pytorch Mobile can't find this operator.

**Comment by chenbohua3** [comment]
Same issue in pytorch1.6.0 / torchvision 0.7.0. Since nms is a widely used op in detection, this may be a urgent problem:)

**Comment by fmassa** [comment]
FYI we are actively working on getting this working on mobile for the next major release.

**Comment by HasnainRaz** [comment]
@fmassa Any updates regarding this? Scripting a model nms using pytorch 1.7.1 and torchvision 0.8.2 and running on iOS with Libtorch 1.7.1 still produces the same result.

Is there any update or relevant PR/ticket we can look at to keep track of the progress?

**Comment by zhiqwang** [comment]
I think that #2897 is aimed to resolve this problem.

**Comment by HasnainRaz** [comment]
#2897 appears to track the torchvision ops for android. Is there one that tracks something similar for iOS as well?

**Comment by zhiqwang** [comment]
Ops... I don't know either.

**Comment by fmassa** [comment]
@HasnainRaz we will also be looking into iOS for next release. We currently don't have an open PR for it yet though.

**Comment by fmassa** [comment]
iOS is supported as of https://github.com/pytorch/vision/pull/3582, and Android support has been added in the 0.9.0 release

**Comment by mzkaramat** [comment]
@fmassa, I've tested with compiling libtorch from source and with latest version from cocoapods, but still can't find torchvision::nms in iOS app. Am I missing some?

**Comment by fmassa** [comment]
@mzkaramat please check https://github.com/pytorch/vision/pull/3629 for an end to end example on how to build an iOS app which leverages `torchvision::nms` via Faster R-CNN

**Comment by mzkaramat** [comment]
Thanks!

**Comment by elb3k** [comment]
> @mzkaramat please check #3629 for an end to end example on how to build an iOS app which leverages `torchvision::nms` via Faster R-CNN

Thank you for a solution. But binaries from amazon is not available for x86_64 or even arm64.

**Comment by fmassa** [comment]
@elb3k we will be uploading the stable binaries in the next release.

In the mean time, you can get the nightlies from 
```
https://ossci-ios-build.s3.amazonaws.com/libtorchvision_ops_ios_nightly_build.zip
```

**Comment by elb3k** [comment]
> @elb3k we will be uploading the stable binaries in the next release.
> 
> In the mean time, you can get the nightlies from
> 
> ```
> https://ossci-ios-build.s3.amazonaws.com/libtorchvision_ops_ios_nightly_build.zip
> ```

Thank you. I ended up compiling torchvision with `LibTorch` cocoapads package. Will make pull request with cocoapads build package script.

**Comment by fmassa** [comment]
Hi,

We have some information on how to compile manually in https://github.com/pytorch/vision/blob/master/.circleci/unittest/ios/scripts/binary_ios_build.sh and https://github.com/pytorch/vision/blob/master/ios/build_ios.sh, let us know if further information is required

**Comment by elb3k** [comment]
> Hi,
> 
> We have some information on how to compile manually in https://github.com/pytorch/vision/blob/master/.circleci/unittest/ios/scripts/binary_ios_build.sh and https://github.com/pytorch/vision/blob/master/ios/build_ios.sh, let us know if further information is required

Hi, these were useful to create `LibTorch_vision_ops` package on cocoapods. I currently published from fork, once [PR](https://github.com/pytorch/vision/pull/3999) is accepted, main repo can publish on cocoapods.
