### ISSUE TITLE
Make transforms work on video tensor inputs or batch of images

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#2583]
## 🚀 Feature

Following https://github.com/pytorch/vision/issues/2292#issuecomment-671325017 and discussion with @fmassa and @bjuncek , this feature request is to improve the transforms module to support video inputs as `torch.Tensor` of shape `(C, T, H, W)`, where C - number of image channels (e.g. 3 for RGB), T - number of frames, H, W - image dimensions. 

Points to discuss:
- Convention for geometric transforms: 2 last dimensions are H, W ?
- Convention for color transforms: 1 dimension is color, like above `(C, T, H, W)` ?
  - should we also support `(T, C, H, W)` ?

**Comment by joakimjohnander** [comment]
The representation `(T, C, H, W)` is convenient when processing one frame at a time, such as in object tracking.

**Comment by fmassa** [comment]
@vfdev-5 I believe this can be closed now?

**Comment by vfdev-5** [comment]
@fmassa I thought to close it once we updated video classification ref example. But as you wish, otherwise I can create another one for that update.

**Comment by fmassa** [comment]
Ok, let's wait until we update the reference examples then before closing this one

**Comment by vfdev-5** [comment]
Close the issue as #2935 has been merged.
