### ISSUE TITLE
Torchvision installation in R-pi4 (32bit, armv7l)

### ISSUE THREAD

**Issue by AbhishekPokala** [pytorch/vision#2590]
### Installation Command
`sudo -E python3 setup.py install`

### Error Message
This was the error message I received.
> Building wheel torchvision-0.8.0a0+27278ec
> PNG found: False
> Running build on conda-build: False
> Running build on conda: False
> JPEG found: False
> running install
> running bdist_egg
> running egg_info
> writing torchvision.egg-info/PKG-INFO
> writing dependency_links to torchvision.egg-info/dependency_links.txt
> writing requirements to torchvision.egg-info/requires.txt
> writing top-level names to torchvision.egg-info/top_level.txt
> /usr/local/lib/python3.6/dist-packages/torch/utils/cpp_extension.py:340: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
>   warnings.warn(msg.format('we could not find ninja.'))
> reading manifest file 'torchvision.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> warning: no previously-included files matching '__pycache__' found under directory '*'
> warning: no previously-included files matching '*.py[co]' found under directory '*'
> writing manifest file 'torchvision.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-armv7l/egg
> running install_lib
> running build_py
> copying torchvision/version.py -> build/lib.linux-armv7l-3.6/torchvision
> running build_ext
> building 'torchvision._C' extension
> gcc-4.8 -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/abhishek/PySyftBuildFolder/vision/torchvision/csrc -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/include/python3.6m -c /home/abhishek/PySyftBuildFolder/vision/torchvision/csrc/vision.cpp -o build/temp.linux-armv7l-3.6/home/abhishek/PySyftBuildFolder/vision/torchvision/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
> gcc-4.8: error: unrecognized command line option ‘-Wdate-time’
> gcc-4.8: error: unrecognized command line option ‘-std=c++14’
> error: command 'gcc-4.8' failed with exit status 1

### System Details
`**uname -a**`

> Linux ubuntu 5.4.0-1015-raspi #15~18.04.1-Ubuntu SMP Fri Jul 10 09:25:12 UTC 2020 armv7l armv7l armv7l GNU/Linux

**Comment by bmanga** [comment]
Hi @AbhishekPokala, it seems like you need to upgrade your gcc version, 4.8 is too old.

**Comment by oke-aditya** [comment]
[Here](http://mathinf.com/pytorch/arm64/) are the wheels for Pi

**Comment by fmassa** [comment]
Hi,

I'm closing this issue following @bmanga comment that you might need to update CMake. Let us know if you have further issues.
