### ISSUE TITLE
Sorting out the datasets alphabetically

### ISSUE THREAD

**Issue by InCogNiTo124** [pytorch/vision#2608]
## 📚 Documentation

The datasets in torchvision documentations are listed in seemingly random order. I'd like to sort the dataset entries alphabetically to improve readability.

**Comment by fmassa** [comment]
Thanks for opening the issue!

Please feel free to send a PR sorting the datasets in alphabetical order. This should be changed in https://github.com/pytorch/vision/blob/master/docs/source/datasets.rst
