### ISSUE TITLE
ROCM version doesn't work

### ISSUE THREAD

**Issue by boniek83** [pytorch/vision#2621]
## 🐛 Bug
When trying to run ROCM accelerated version I get the following error:
`RuntimeError: t == DeviceType::HIP INTERNAL ASSERT FAILED at "/root/.local/lib/python3.6/site-packages/torch/include/c10/hip/impl/HIPGuardImpl.h":22, please report a bug to PyTorch.`

## To Reproduce

1. Build environment: https://gist.github.com/boniek83/86ea18dfcb557273354fe4fa6e0e226c
3. Run lab: https://github.com/timesler/facenet-pytorch/blob/master/examples/infer.ipynb
4. Error: https://gist.github.com/boniek83/1acdda728ae2bc1d06bf5464d6e9a719

Pytorch with rocm itself works:
```
import torch 
torch.cuda.is_available()

True
```
Everything works with CPU.
## Environment

https://gist.github.com/boniek83/9c0713d30673d14ad4acbac84e65d96e

 - ROCM/ROCK version: 3.5.0
 - GPU models and configuration: AMD Radeon VII

**Comment by pmeier** [comment]
Hi @boniek83, your issue seems a better fit for the [`torch` issue tracker](https://github.com/pytorch/pytorch/issues). @fmassa could you transfer it?

**Comment by fmassa** [comment]
Hi,

@pmeier if I understand correctly the issue is that PyTorch with ROCm works, but not torchvision. So I believe this issue should be in torchvision itself.

Tentative ROCm support was added in https://github.com/pytorch/vision/pull/1928, but given that we don't yet have ROCm CI, it might be possible that it is broken already.

ccing @iotamudelta @ashishfarmer who added initial ROCm support for torchvision.

**Comment by boniek83** [comment]
Learning and serving models with ROCM on pytorch (with torchserve with this fix: https://github.com/pytorch/serve/issues/403) works for me. Now only torchvision is giving me problems.

**Comment by pmeier** [comment]
My bad, I misinterpreted this.

**Comment by ashishfarmer** [comment]
Thank you @boniek83 . From the logs you attached, it does seem like an issue with finding HIP device on ROCm. I will investigate into this.
cc: @sunway513 @jeffdaily

**Comment by ashishfarmer** [comment]
Narrowed down the problem to NMS operator in torchvision on ROCm. It is reproducible with NMS test in torchvision itself. Looking further into it

**Comment by fmassa** [comment]
@ashishfarmer we have recently changed the registration mechanism in torchvision for a couple of ops, namely NMS and RoIAlign, see https://github.com/pytorch/vision/pull/2366 and https://github.com/pytorch/vision/pull/2384
