### ISSUE TITLE
CMakeFiles/example-app.dir/example-app.cpp.o：在函数‘ROIAlign_forward(at::Tensor const&, at::Tensor const&, double, long, long, long, bool)’中： example-app.cpp:(.text+0x179c)：对‘ROIAlign_forward_cuda(at::Tensor const&, at::Tensor const&, double, long, long, long, bool)’未定义的引用 CMakeFiles/example-app.dir/example-app.cpp.o：在函数‘ROIAlign_backward(at::Tensor const&, at::Tensor const&, float, int, int, int, int, int, int, int, bool)’中： example-app.cpp:(.text+0x18a7)：对‘ROIAlign_backward_cuda(at::Tensor const&, at::Tensor const&, double, long, long, long, long, long, long, long, bool)’未定义的引用 CMakeFiles/example-app.dir/example-app.cpp.o：在函数‘nms(at::Tensor const&, at::Tensor const&, double)’中： example-app.cpp:(.text+0x1eaa)：对‘nms_cuda(at::Tensor const&, at::Tensor const&, double)’未定义的引用 collect2: error: ld returned 1 exit status CMak

### ISSUE THREAD

**Issue by ts19970816** [pytorch/vision#2623]
## To Reproduce

CMakeFiles/example-app.dir/example-app.cpp.o：在函数‘ROIAlign_forward(at::Tensor const&, at::Tensor const&, double, long, long, long, bool)’中：
example-app.cpp:(.text+0x179c)：对‘ROIAlign_forward_cuda(at::Tensor const&, at::Tensor const&, double, long, long, long, bool)’未定义的引用
CMakeFiles/example-app.dir/example-app.cpp.o：在函数‘ROIAlign_backward(at::Tensor const&, at::Tensor const&, float, int, int, int, int, int, int, int, bool)’中：
example-app.cpp:(.text+0x18a7)：对‘ROIAlign_backward_cuda(at::Tensor const&, at::Tensor const&, double, long, long, long, long, long, long, long, bool)’未定义的引用
CMakeFiles/example-app.dir/example-app.cpp.o：在函数‘nms(at::Tensor const&, at::Tensor const&, double)’中：
example-app.cpp:(.text+0x1eaa)：对‘nms_cuda(at::Tensor const&, at::Tensor const&, double)’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/example-app.dir/build.make:122: recipe for target 'example-app' failed
make[2]: *** [example-app] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/example-app.dir/all' failed
make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

1.
1.
1.

## Environment

 - PyTorch / torchvision Version (e.g., 1.5.0 / 0.6.0):
 - OS ( ubtunu):
 - How you installed PyTorch / torchvision ( `pip`/source):
 - Python version:3.6.5
 - CUDA/cuDNN version:10.2/7.6.5
 - GPU models and configuration:1080ti
 - Any other relevant information:

**Comment by pmeier** [comment]
Hey @ts19970816, unfortunately I don't speak Chinese. Thus, it is hard to even know what you were trying to do. Could you please change the title to something more descriptive in English?

**Comment by KaiHoo** [comment]
Just a translation @pmeier 


"""
CMakeFiles/example-app.dir/example-app.cpp.o：In function ‘ROIAlign_forward(at::Tensor const&, at::Tensor const&, double, long, long, long, bool)’：
example-app.cpp:(.text+0x179c)：undefined reference to ‘ROIAlign_forward_cuda(at::Tensor const&, at::Tensor const&, double, long, long, long, bool)’
CMakeFiles/example-app.dir/example-app.cpp.o：In function ‘ROIAlign_backward(at::Tensor const&, at::Tensor const&, float, int, int, int, int, int, int, int, bool)’：
example-app.cpp:(.text+0x18a7)：undefined reference to ‘ROIAlign_backward_cuda(at::Tensor const&, at::Tensor const&, double, long, long, long, long, long, long, long, bool)’
CMakeFiles/example-app.dir/example-app.cpp.o：In function ‘nms(at::Tensor const&, at::Tensor const&, double)’：
example-app.cpp:(.text+0x1eaa)：undefined reference to ‘nms_cuda(at::Tensor const&, at::Tensor const&, double)’
collect2: error: ld returned 1 exit status
CMakeFiles/example-app.dir/build.make:122: recipe for target 'example-app' failed
make[2]: *** [example-app] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/example-app.dir/all' failed
make[1]: *** [CMakeFiles/example-app.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
"""

**Comment by vfdev-5** [comment]
I close this issue as it is missing details. @ts19970816 let us know if you have further questions in english. Thanks
