### ISSUE TITLE
MacOSX CI is broken

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#2629]
## 🐛 Bug

CircleCI tests of binary_macos_conda_py3.X_cpu are not passing : 

https://app.circleci.com/pipelines/github/pytorch/vision/3702/workflows/d3d14328-2f3c-40d8-9bf0-74b090867258

cc @seemethere

**Comment by fmassa** [comment]
I believe this was fixed with https://github.com/pytorch/vision/pull/2633
