### ISSUE TITLE
torchvision.transforms.Scale should be renamed to torchvision.transforms.Resize

### ISSUE THREAD

**Issue by trustswz** [pytorch/vision#264]
Scale/Rescale implies a change by a factor X

Scale(X) usually means that you change the intensity of the image from I to I*X or size of the image from S to S*X

However in pytorchvision, Scale, is defined as:
Desired output size. If size is a sequence like (h, w), output size will be matched to this. If size is an int, smaller edge of the image will be matched to this number. i.e, if height > width, then image will be rescaled to (size * height / width, size)

The above definition matches better the concept of resize in image processing instead of rescale. For more information please see the following link.

http://scikit-image.org/docs/dev/auto_examples/transform/plot_rescale.html

**Comment by alykhantejani** [comment]
Thanks for the issue @trustswz. I agree this naming is quite confusing. We could deprecate `Scale` in favor of resize and add deprecation warnings - wdyt @fmassa?

**Comment by fmassa** [comment]
Yes, let's deprecate `Scale` and add instead `Resize`

**Comment by alykhantejani** [comment]
Fixed in #274
