### ISSUE TITLE
Docs of some functions written are missing

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#2649]
## 📚 Documentation

A simple issue, Docs are missing on the torchvision website for following functions written in torchvision.

I guess we should add these docs on the webpage, as end-users will benefit from using these functions. 

Most people will not look at source code to find these functions but refer to docs.

Missing docs that I found

- [ ] Image reading functions [here](https://github.com/pytorch/vision/blob/master/torchvision/io/image.py)
We have docs for video io functions, so maybe image should too be there.

- [ ] Torchvision ops from [boxes.py](https://github.com/pytorch/vision/blob/master/torchvision/ops/boxes.py). Docs are added for NMS. but we are missing IoU, Box area and some classes. Partly fixed in #2642 

Please do let me know if some other docs or missing as well.

Also, I can raise a PR to fix these, please do let me know if it is needed!

**Comment by vfdev-5** [comment]
@oke-aditya thanks for reporting :) 

Concerning "Image reading functions", it is only `master` version and does not exist yet in the stable version, right ?

About torchvision ops from boxes.py, yes, seems like some docstrings are missing in https://pytorch.org/docs/stable/torchvision/ops.html which can be easily added.

So, yes, please, send a PR for fixing the docs for boxes.py.

**Comment by oke-aditya** [comment]
For image reading functions, docs do not exist for both, master as well as stable. 

Please verify once [io.rst](https://github.com/pytorch/vision/blob/master/docs/source/io.rst)

**Comment by vfdev-5** [comment]
Yes, you are right, docs for master version are also missing image reading functions. A PR for that could also help :)
