### ISSUE TITLE
Add CONTRIBUTING.md 

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#2651]
## 🚀 Feature

It is a good practice to have CONTRIBUTING.md file to describe some guidelines for open-source contributions.

TODO:
- [x] Version 1
- [x] complete section about how to add a new model
- [ ] complete section about how to add a new dataset

cc @fmassa

**Comment by oke-aditya** [comment]
Yes ! I was about to raise this Issue something in lines of [ignite](https://github.com/pytorch/ignite/blob/master/CONTRIBUTING.md) would be nice.

Most might struggle to build docs, format code with linting etc.

**Comment by fmassa** [comment]
Yes, that is a great thing to have.

I think we should clarify what are the criteria for adding new models / layers to torchvision, so that it's clear from the beginning.

@vfdev-5 if you could start with a first, more generic, draft of the CONTRIBUTING file we could iterate on it

Tagging @cpuhrsch @dongreenberg for thoughts.

**Comment by cpuhrsch** [comment]
We could also referece the [pytorch contribution guidelines](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md) with some additional torchvision specific guidance.

**Comment by vfdev-5** [comment]
TODO for this issue:
- [ ] complete section about how to add a new model
- [ ] complete section about how to add a new dataset

**Comment by datumbox** [comment]
@vfdev-5 Just a suggestion. Perhaps add in the list that the CONTRIBUTING.md v1 was added and there are 2 more pendings. I would also put this on the top of the ticket instead of the comments so that it's visible and it's tracked by Github checklists.

**Comment by vfdev-5** [comment]
Thanks, I agree !

**Comment by vfdev-5** [comment]
Let's close this issue and if needed open a specific one for new dataset addition
