### ISSUE TITLE
Image to Tensor data

### ISSUE THREAD

**Issue by beeqwe** [pytorch/vision#2652]
Library: **pytorch_java_only-1.6.0** 

I want to convert BufferedImage/File to Tensor data, is there some method or library for this?

Python solution:

```
image = Image.open(image_path)
image = image.convert('RGB') 
transform = Compose([ToTensor()])
image = transform(image)
image = image.view(1, 3, 64, 64).cuda()
output = my_model(image)
output = output.view(-1, self.quantity)
output = nn.functional.softmax(output, dim=1)
output = torch.argmax(output, dim=1)
output = output.view(-1, self.size)[0]
```

I need something like that for pytorch_java. I'm sorry if my question is stupid i'm newbee 

P.S: Thanks for reply

**Comment by fmassa** [comment]
Hi,

We dont provide a java interface for torchvision, and I have no experience with Java so I won't be able to help with this. I think you are in the right direction with `fromBlob`.
