### ISSUE TITLE
Cannot build C++ example

### ISSUE THREAD

**Issue by martingasser** [pytorch/vision#2653]
I'm on macOS. After building and installing torchvision, I tried building the C++ example and failed.

`
/Users/martin/devel/vision/examples/cpp/hello_world/main.cpp:3:10: fatal error: 'torchvision/models/resnet.h' file not found
#include <torchvision/models/resnet.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/hello-world.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/hello-world.dir/all] Error 2
make: *** [all] Error 2
`

Adding

`target_include_directories(TorchVision::TorchVision INTERFACE "${PACKAGE_PREFIX_DIR}/@CMAKE_INSTALL_INCLUDEDIR@")`

after

https://github.com/pytorch/vision/blob/190a5f8a32f9ae775d4379c55db7e2deb6eada6b/cmake/TorchVisionConfig.cmake.in#L34

or replacing the `target_link_libraries` command with

`
set_target_properties(TorchVision::TorchVision PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${PACKAGE_PREFIX_DIR}/@CMAKE_INSTALL_INCLUDEDIR@"
  INTERFACE_LINK_LIBRARIES "torch;Python3::Python"
)
`

and explicitly setting the `INTERFACE_INCLUDE_DIRECTORIES` property seems to fix the problem.

**Comment by fmassa** [comment]
@andfoy what do you think about extending your CMake CI job to also test the `hello_world` example from https://github.com/pytorch/vision/tree/master/examples/cpp/hello_world

**Comment by andfoy** [comment]
> what do you think about extending your CMake CI job to also test the hello_world example

Sure! We can include it

**Comment by martingasser** [comment]
Thanks!

I'm aware that it's a minor issue, but I can see that in `packaging/build_cmake.sh`, torchvision is installed to the standard location (`/usr/local`) and `CPLUS_INCLUDE_PATH` is set to `/usr/local/include` (which is not a standard include directory on macOS, while it is on Linux). Of course, that works for the CI job.

If the include path would be added as an interface dependency to the library target in the TorchVision cmake config (as described in my initial post), this would not be necessary and done by cmake automatically. It'd be also easier to install torchvision to any location. And the example would build as described in the `README.md` on macOS.

Should I open a PR?

**Comment by andfoy** [comment]
Hi @martingasser, thanks for this suggestion, we definitely need a way of installing libtorchvision into a non-standard location (conda environments for instance), please free to open a PR regarding this
