### ISSUE TITLE
Travis is skipping accimage tests

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/vision#268]
Looking at the job outputs from Travis i.e. [this one](https://travis-ci.org/pytorch/vision/jobs/277555954) it seems that 3 tests in `test_transforms` are being skipped - these are the `accimage` tests. 

I'm guessing `accimage` is not available on these machines - this is probably something we should fix.

**Comment by alykhantejani** [comment]
It's a bit complicated to build accimage and to get it installed as part of the travis job (which uses conda). 

I've opened an issue in the accimage repo asking for a pre-built package [here](https://github.com/pytorch/accimage/issues/9).

**Comment by fmassa** [comment]
We don't have Travis (nor accimage) tests anymore, closing this.
