### ISSUE TITLE
`video_reader` and `pyav` video backends producing slightly different results

### ISSUE THREAD

**Issue by bjuncek** [pytorch/vision#2681]
## 🐛 Bug

`read_video` and `read_video_timestamps` functions have different returns that depend on the backend.

## To Reproduce

```
import torchvision
torchvision.set_video_backend("video_reader")
tv_vr, _, _ = torchvision.io.read_video(video_path, pts_unit='sec')
torchvision.set_video_backend("pyav")
tv_av, _, _ = torchvision.io.read_video(video_path, pts_unit='sec')
for i in range(tv_vr.size(0)):
    print(i, torch.sum(tv_av[i,...]), torch.sum(tv_vr[i,...]), torch.equal(tv_vr[i,...], tv_av[i,...]))
```

Returns the following output. Please note that the results are not _different_, but _mismatched_. 

```
0 tensor(14241847) tensor(14241847) True
1 tensor(14268786) tensor(14295419) False
2 tensor(14295419) tensor(14268786) False
3 tensor(14270755) tensor(14270755) True
4 tensor(14378507) tensor(14521067) False
5 tensor(14521067) tensor(14378507) False
6 tensor(14077695) tensor(14326726) False
7 tensor(14326726) tensor(14077695) False
8 tensor(13952965) tensor(13965874) False
9 tensor(13965874) tensor(13952965) False
10 tensor(13848191) tensor(13998592) False
11 tensor(13998592) tensor(13848191) False
12 tensor(14239088) tensor(14259191) False
13 tensor(14259191) tensor(14239088) False
14 tensor(14315983) tensor(14333608) False
15 tensor(14333608) tensor(14315983) False
16 tensor(14053066) tensor(14343130) False
17 tensor(14343130) tensor(14053066) False
18 tensor(13956687) tensor(14154976) False
19 tensor(14154976) tensor(13956687) False
...
```

In `read_video_timestamps` there is only a discrepancy between the first value. Specifically:

```
torchvision.set_video_backend("pyav")
tv_av, _ = torchvision.io.read_video_timestamps(video_path, pts_unit='sec')

torchvision.set_video_backend("video_reader")
tv_vr, _= torchvision.io.read_video_timestamps(video_path, pts_unit='sec')

for i in range(len(tv_av)):
    print(float(tv_av[i]), float(tv_vr[i]))
```

on the output, the difference is noly in the first frame:
```
0.03333333333333333 0.06666666666666667
0.1 0.1
0.13333333333333333 0.13333333333333333
0.16666666666666666 0.16666666666666666
0.2 0.2
0.23333333333333334 0.23333333333333334
0.26666666666666666 0.26666666666666666
```

## Expected behavior

returning a sequence of the same sums, with the last value set to `True` for all frames, and all timestamps would be the same

## Environment

Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000

Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-10.2.89/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0a0+78ed10c
[conda] blas 1.0 mkl
[conda] cudatoolkit 10.2.89 hfd86e86_1
[conda] mkl 2020.2 256
[conda] mkl-service 2.3.0 py38he904b0f_0
[conda] mkl_fft 1.1.0 py38h23d657b_0
[conda] mkl_random 1.1.1 py38hcb8c335_0 conda-forge
[conda] numpy 1.19.1 py38hbc911f0_0
[conda] numpy-base 1.19.1 py38hfa32c7d_0
[conda] pytorch 1.6.0 py3.8_cuda10.2.89_cudnn7.6.5_0 pytorch
[conda] torchvision 0.7.0a0+78ed10c pypi_0 pypi

cc @bjuncek

**Comment by fmassa** [comment]
This might be due to pts not being sorted in the `video_reader` backend. Some videos in UCF101 or HMDB51 had this particularity. We perform this sorting in https://github.com/pytorch/vision/blob/8dfcff745a5bd2d4886716bf0deff8dcc8e75fed/torchvision/io/video.py#L165-L168 for the pyav backend

**Comment by QuantScientist** [comment]
Is there a full equivalent C++ example for reading video frames into torch::tensor and vice versa? 

Thanks,

**Comment by fmassa** [comment]
@QuantScientist no example in C++ yet, but you can use the `readVideo` function for this https://github.com/pytorch/vision/blob/8dfcff745a5bd2d4886716bf0deff8dcc8e75fed/torchvision/csrc/cpu/video_reader/VideoReader.cpp#L185-L207

**Comment by QuantScientist** [comment]
Thanks @fmassa ... a method with 21 parameters? while the python equivalent is `torchvision.io.read_video(filename, start_pts=0, end_pts=None, pts_unit='pts')`

Anyway, AFAIK this method does not return a frame by frame iterator. I do not wish to return 12,000 frames in one Tensor. 

Thanks,

**Comment by fmassa** [comment]
> a method with 21 parameters? while the python equivalent is torchvision.io.read_video(filename, start_pts=0, end_pts=None, pts_unit='pts')

I agree it's not a great signature, and that's why the python version is private.

> Anyway, AFAIK this method does not return a frame by frame iterator. I do not wish to return 12,000 frames in one Tensor

If you want to have a frame by frame iterator, you'll need to wait until https://github.com/pytorch/vision/pull/2683 gets merged (which should be soon).

**Comment by QuantScientist** [comment]
Thanks,
I am going to try this:
https://github.com/osai-ai/tensor-stream

**Comment by bjuncek** [comment]
Closed as it's fixed in subsequent bug fixes
