### ISSUE TITLE
Provide generic decode/read image io functions

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#2686]
## 🚀 Feature

Currently, `torchvision.io.image` module provides `read_png/jpeg` and `decode_png/jpeg` separate functions to read and decode images from files. They are not and will not be exposed publicly and the idea is to provide two generic methods like 
`read` and `decode` in order to handle both formats (png and jpeg): call internally `read_png` or `read_jpeg`

Maybe, we can inspire of how does the libraries like PIL to dispatch according to the input image format.

**Comment by oke-aditya** [comment]
This is PIL Implementation fo `Image.open()` This works for all imags and is generic.
Source code is [here](https://github.com/python-pillow/Pillow/blob/master/src/PIL/Image.py).


```
def open(fp, mode="r", formats=None):
    """
    Opens and identifies the given image file.
    This is a lazy operation; this function identifies the file, but
    the file remains open and the actual image data is not read from
    the file until you try to process the data (or call the
    :py:meth:`~PIL.Image.Image.load` method).  See
    :py:func:`~PIL.Image.new`. See :ref:`file-handling`.
    :param fp: A filename (string), pathlib.Path object or a file object.
       The file object must implement ``file.read``,
       ``file.seek``, and ``file.tell`` methods,
       and be opened in binary mode.
    :param mode: The mode.  If given, this argument must be "r".
    :param formats: A list or tuple of formats to attempt to load the file in.
       This can be used to restrict the set of formats checked.
       Pass ``None`` to try all supported formats. You can print the set of
       available formats by running ``python -m PIL`` or using
       the :py:func:`PIL.features.pilinfo` function.
    :returns: An :py:class:`~PIL.Image.Image` object.
    :exception FileNotFoundError: If the file cannot be found.
    :exception PIL.UnidentifiedImageError: If the image cannot be opened and
       identified.
    :exception ValueError: If the ``mode`` is not "r", or if a ``StringIO``
       instance is used for ``fp``.
    :exception TypeError: If ``formats`` is not ``None``, a list or a tuple.
    """

    if mode != "r":
        raise ValueError(f"bad mode {repr(mode)}")
    elif isinstance(fp, io.StringIO):
        raise ValueError(
            "StringIO cannot be used to open an image. "
            "Binary data must be used instead."
        )

    if formats is None:
        formats = ID
    elif not isinstance(formats, (list, tuple)):
        raise TypeError("formats must be a list or tuple")

    exclusive_fp = False
    filename = ""
    if isinstance(fp, Path):
        filename = str(fp.resolve())
    elif isPath(fp):
        filename = fp

    if filename:
        fp = builtins.open(filename, "rb")
        exclusive_fp = True

    try:
        fp.seek(0)
    except (AttributeError, io.UnsupportedOperation):
        fp = io.BytesIO(fp.read())
        exclusive_fp = True

    prefix = fp.read(16)

    preinit()

    accept_warnings = []

    def _open_core(fp, filename, prefix, formats):
        for i in formats:
            try:
                factory, accept = OPEN[i]
                result = not accept or accept(prefix)
                if type(result) in [str, bytes]:
                    accept_warnings.append(result)
                elif result:
                    fp.seek(0)
                    im = factory(fp, filename)
                    _decompression_bomb_check(im.size)
                    return im
            except (SyntaxError, IndexError, TypeError, struct.error):
                # Leave disabled by default, spams the logs with image
                # opening failures that are entirely expected.
                # logger.debug("", exc_info=True)
                continue
            except BaseException:
                if exclusive_fp:
                    fp.close()
                raise
        return None

    im = _open_core(fp, filename, prefix, formats)

    if im is None:
        if init():
            im = _open_core(fp, filename, prefix, formats)

    if im:
        im._exclusive_fp = exclusive_fp
        return im

    if exclusive_fp:
        fp.close()
    for message in accept_warnings:
        warnings.warn(message)
    raise UnidentifiedImageError(
        "cannot identify image file %r" % (filename if filename else fp)
    )

```

**Comment by vfdev-5** [comment]
@oke-aditya thanks for the info, but I'm not sure if we would like to use PIL for reading and decoding the data. Idea is see how PIL manages its png/jpeg specific readers and try to do something similar here...

**Comment by oke-aditya** [comment]
It might be better as you say, allowing native support through tochvision with that.

**Comment by QuantScientist** [comment]
What about C++, I would like to have the same in Libtorch.

**Comment by oke-aditya** [comment]
@QuantScientist I guess as vfdev-5 said this will be implemented in C++ only. I

**Comment by fmassa** [comment]
@QuantScientist we already have C++ implementation for image decoding functions.

@oke-aditya about using PIL, the idea is being able to have a C++-only implementation that works with torchscript, and PIL's C implementation is very tied to Python.

From the PIL implementation, it seems they [compute a `prefix`](https://github.com/pytorch/vision/blob/2801a76dd91a8b5c0f63e74e47b3697084f3af28/torchvision/io/image.py#L58-L65), which is [used to quickly check](https://github.com/python-pillow/Pillow/blob/c2367400fa8aab47d7752f3780681fced044f0d2/src/PIL/Image.py#L2909-L2917) if one format could be used for not.

Here is the implementation [for `jpeg`](https://github.com/python-pillow/Pillow/blob/5ce2fac3d6cfcf9af0f84502d9bd0c2dfcfcb398/src/PIL/JpegImagePlugin.py#L328-L330) and [for `png`](https://github.com/python-pillow/Pillow/blob/5ce2fac3d6cfcf9af0f84502d9bd0c2dfcfcb398/src/PIL/PngImagePlugin.py#L656-L657) for reference. Both formats seems to have a magic number header that could be used to perform the dispatching (although further investigation would be useful to see if there are no corner cases, as in PIL they have a `try: except` while loading).

**Comment by QuantScientist** [comment]
See here:
https://github.com/pytorch/vision/issues/2691

**Comment by QuantScientist** [comment]
So I wrote a small lib for it:
https://github.com/QuantScientist/PngTorch
