### ISSUE TITLE
Reading PNG/JPG images into a torch::tensor and saving a torch::tensor to PNG/JPG in C++ without OpenCV 

### ISSUE THREAD

**Issue by QuantScientist** [pytorch/vision#2691]
## 🚀 Feature

After integrating Siv3D with Libtorch (https://github.com/QuantScientist/Siv3DTorch) I am now trying to read and write images from and to Siv3D **in C++, not Python**. The way it works is:

## Motivation
In C++ I need to do the following:
1. An image is read from disk (usually using OpenCV which is easy but I am trying to avoid)
2. The image is converted to torch::tensor
3. A DL model is applied on the tensor
4. A tensor is returned from the model
5. The tensor is converted to an image for display/saving purposes.

This is one example where they used stb_image to this, avoiding the use of OpenCV.
https://github.com/prabhuomkar/pytorch-cpp/blob/master/utils/image_io/src/image_io.cpp

## Alternatives

For reference this is the OpenCV to Libtorch conversion utils which I use, I would like something very similiar:
```
at::Tensor matToTensor(cv::Mat frame, int h, int w, int c) {
    cv::cvtColor(frame, frame, CV_BGR2RGB);
    frame.convertTo(frame, CV_32FC3, 1.0f / 255.0f);
    auto input_tensor = torch::from_blob(frame.data, {1, h, w, c});
    input_tensor = input_tensor.permute({0, 3, 1, 2});

    torch::DeviceType device_type = torch::kCPU;
//    if (torch::cuda::is_available()) {
    device_type = torch::kCUDA;
//    }
    input_tensor = input_tensor.to(device_type);
    return input_tensor;
}

cv::Mat tensorToOpenCv(at::Tensor out_tensor, int h, int w, int c) {
    out_tensor = out_tensor.squeeze().detach().permute({1, 2, 0});
    out_tensor = out_tensor.mul(255).clamp(0, 255).to(torch::kU8);
    out_tensor = out_tensor.to(torch::kCPU);
    cv::Mat resultImg(h, w, CV_8UC3);
    // cv::Mat resultImg(h, w, CV_8UC1);
    std::memcpy((void *) resultImg.data, out_tensor.data_ptr(), sizeof(torch::kU8) * out_tensor.numel());
    return resultImg;
}

```
## Additional context

I found this:"https://github.com/pytorch/vision/blob/5e4a9f6d1a2bf85137f4826dbf76e4f25986f878/torchvision/csrc/cpu/image/readpng_cpu.cpp
however, could not get any useful method out of it. 

Thanks,

**Comment by fmassa** [comment]
Hi,

We have recently introduced a `decode_png` and `decode_jpeg` functions in C++, which are exposed to Python for image decoding.

Those methods take the raw read bytes from the image, pass them as a Tensor and get the returned result back.
So the recommended approach for reading images in C++ would be the C++ equivalent of
https://github.com/pytorch/vision/blob/2801a76dd91a8b5c0f63e74e47b3697084f3af28/torchvision/io/image.py#L58-L65

We don't yet have C++-only tests for this interface, but we could add them soon now that we have CMake-only tests.

About implementing image saving operations, this would be a good thing to have, but we haven't currently implemented it.
We would be glad to accept PRs adding it (including Python frontend)

cc @andfoy for thoughts.

**Comment by QuantScientist** [comment]
See this:
https://github.com/koba-jon/pytorch_cpp/issues/6

The author provided two methods based on png++ that I am going to test. 

```
#include <iostream>
#include <torch/torch.h>
#include <png++/png.hpp>

torch::Tensor ConvertRGBintoTensor(png::image<png::rgb_pixel> &image);
png::image<png::rgb_pixel> ConvertTensorintoRGB(torch::Tensor &tensor_);

int main(void){

    // Input PNG-image
    png::image<png::rgb_pixel> imageI("input.png");

    // Convert png::image into torch::Tensor
    torch::Tensor tensor = ConvertRGBintoTensor(imageI);
    std::cout << "C:" << tensor.size(0) << " H:" << tensor.size(1) << " W:" << tensor.size(2) << std::endl;

    // Convert torch::Tensor into png::image
    png::image<png::rgb_pixel> imageO = ConvertTensorintoRGB(tensor);

    // Output PNG-image
    imageO.write("output.png");

    return 0;
}

torch::Tensor ConvertRGBintoTensor(png::image<png::rgb_pixel> &image){
    size_t width = image.get_width();
    size_t height = image.get_height();
    unsigned char *pointer = new unsigned char[width * height * 3];
    for (size_t j = 0; j < height; j++){
        for (size_t i = 0; i < width; i++){
            pointer[j * width * 3 + i * 3 + 0] = image[j][i].red;
            pointer[j * width * 3 + i * 3 + 1] = image[j][i].green;
            pointer[j * width * 3 + i * 3 + 2] = image[j][i].blue;
        }
    }
    torch::Tensor tensor = torch::from_blob(pointer, {image.get_height(), image.get_width(), 3}, torch::kUInt8).clone();  // copy
    tensor = tensor.permute({2, 0, 1});  // {H,W,C} ===> {C,H,W}
    delete[] pointer;
    return tensor;
}

png::image<png::rgb_pixel> ConvertTensorintoRGB(torch::Tensor &tensor_){
    torch::Tensor tensor = tensor_.permute({1, 2, 0});  // {C,H,W} ===> {H,W,C}
    size_t width = tensor.size(1);
    size_t height = tensor.size(0);
    unsigned char *pointer = tensor.data_ptr<unsigned char>();
    png::image<png::rgb_pixel> image(width, height);
    for (size_t j = 0; j < height; j++){
        for (size_t i = 0; i < width; i++){
            image[j][i].red = pointer[j * width * 3 + i * 3 + 0];
            image[j][i].green = pointer[j * width * 3 + i * 3 + 1];
            image[j][i].blue = pointer[j * width * 3 + i * 3 + 2];
        }
    }
    return image;
}
```

**Comment by fmassa** [comment]
We will probably not rely on png++, but only on png, given that it is a very standard library which is present in many distributions.
As I said, we already have loading functionality for jpeg and png, relying on `libjpeg` and `libpng`, and using it from C++ should be straightforward.

**Comment by QuantScientist** [comment]
I wrote a small lib for it:
https://github.com/QuantScientist/PngTorch

**Comment by vfdev-5** [comment]
> I wrote a small lib for it:

still has OpenCV as dependency and  
```
target_link_libraries(${PROJECT_NAME} ${TORCH_LIBRARIES}  ${OpenCV_LIBRARIES} "${CMAKE_CURRENT_LIST_DIR}/lib/libpng/libpng16.lib" "${CMAKE_CURRENT_LIST_DIR}/lib/zlib/zlib.lib")
```
https://github.com/QuantScientist/PngTorch/blob/9475c8adc1f2eb1c3eb6534257af65e6b1de5cb0/CMakeLists.txt#L82

**Comment by QuantScientist** [comment]
> > I wrote a small lib for it:
> 
> still has OpenCV as dependency and
> 
> ```
> target_link_libraries(${PROJECT_NAME} ${TORCH_LIBRARIES}  ${OpenCV_LIBRARIES} "${CMAKE_CURRENT_LIST_DIR}/lib/libpng/libpng16.lib" "${CMAKE_CURRENT_LIST_DIR}/lib/zlib/zlib.lib")
> ```
> 
> https://github.com/QuantScientist/PngTorch/blob/9475c8adc1f2eb1c3eb6534257af65e6b1de5cb0/CMakeLists.txt#L82

Yes, it evaluated to an empty string, but you are right and I removed it.

**Comment by andfoy** [comment]
I think we could add encoding support for both jpeg an png directly on our C++ frontend, similar to what we have currently for decoding

**Comment by kkatsanos22** [comment]
> ## 🚀 Feature
> After integrating Siv3D with Libtorch (https://github.com/QuantScientist/Siv3DTorch) I am now trying to read and write images from and to Siv3D **in C++, not Python**. The way it works is:
> 
> ## Motivation
> In C++ I need to do the following:
> 
> 1. An image is read from disk (usually using OpenCV which is easy but I am trying to avoid)
> 2. The image is converted to torch::tensor
> 3. A DL model is applied on the tensor
> 4. A tensor is returned from the model
> 5. The tensor is converted to an image for display/saving purposes.
> 
> This is one example where they used stb_image to this, avoiding the use of OpenCV. https://github.com/prabhuomkar/pytorch-cpp/blob/master/utils/image_io/src/image_io.cpp
> 
> ## Pitch
> ## Alternatives
> For reference this is the OpenCV to Libtorch conversion utils which I use, I would like something very similiar:
> 
> ```
> at::Tensor matToTensor(cv::Mat frame, int h, int w, int c) {
>     cv::cvtColor(frame, frame, CV_BGR2RGB);
>     frame.convertTo(frame, CV_32FC3, 1.0f / 255.0f);
>     auto input_tensor = torch::from_blob(frame.data, {1, h, w, c});
>     input_tensor = input_tensor.permute({0, 3, 1, 2});
> 
>     torch::DeviceType device_type = torch::kCPU;
> //    if (torch::cuda::is_available()) {
>     device_type = torch::kCUDA;
> //    }
>     input_tensor = input_tensor.to(device_type);
>     return input_tensor;
> }
> 
> cv::Mat tensorToOpenCv(at::Tensor out_tensor, int h, int w, int c) {
>     out_tensor = out_tensor.squeeze().detach().permute({1, 2, 0});
>     out_tensor = out_tensor.mul(255).clamp(0, 255).to(torch::kU8);
>     out_tensor = out_tensor.to(torch::kCPU);
>     cv::Mat resultImg(h, w, CV_8UC3);
>     // cv::Mat resultImg(h, w, CV_8UC1);
>     std::memcpy((void *) resultImg.data, out_tensor.data_ptr(), sizeof(torch::kU8) * out_tensor.numel());
>     return resultImg;
> }
> ```
> 
> ## Additional context
> I found this:"https://github.com/pytorch/vision/blob/5e4a9f6d1a2bf85137f4826dbf76e4f25986f878/torchvision/csrc/cpu/image/readpng_cpu.cpp however, could not get any useful method out of it.
> 
> Thanks,

i am currently working on a yolov7 wrapper cpp program to read image from a camera on ros workspace .There is an issue with loading torch libraries, is there anyone who have worked an equivalent  project and has fixed it
