### ISSUE TITLE
CMake Error at /usr/local/share/cmake-3.18/Modules/FindPython/Support.cmake:615 (if):

### ISSUE THREAD

**Issue by xkszltl** [pytorch/vision#2701]
## 🐛 Bug

This is a recent issue.
```
CMake Error at /usr/local/share/cmake-3.18/Modules/FindPython/Support.cmake:615 (if):
  Syntax error in cmake code at

    /usr/local/share/cmake-3.18/Modules/FindPython/Support.cmake:615 

  when parsing string

    python${version_major}\.${version_minor}+([dmu]*)

  Invalid escape sequence \.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FindPython/Support.cmake:2756 (_python_get_version)
  /usr/local/share/cmake-3.18/Modules/FindPython3.cmake:389 (include)
  CMakeLists.txt:14 (find_package)


-- Configuring incomplete, errors occurred!
```

Given 3.18.3 is recently released (we use latest, was 3.18.2), we're not sure whether it's from torchvision or cmake.

## Environment

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): master/master
 - OS (e.g., Linux): CentOS 7 / Ubuntu 18.04
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake-3.18.3 + ninja + (gcc-9 from devtoolset-9/stock gcc-8)
 - Python version: Distro stock python3.
 - CUDA/cuDNN version: 11.0/8

**Comment by xkszltl** [comment]
Note pytorch was built just fine. Only torchvision has the issue.

**Comment by xkszltl** [comment]
Also filed the issue here in case it's caused by cmake bug: https://gitlab.kitware.com/cmake/cmake/-/issues/21223

**Comment by fmassa** [comment]
Could you try seeing if https://github.com/pytorch/vision/pull/2684 is the culprit, and if reverting it makes it work for you?

**Comment by xkszltl** [comment]
That's probably not the root cause.
CMake side found their regex bug in 3.18.3.

**Comment by xkszltl** [comment]
I tried their patch and works.

**Comment by xkszltl** [comment]
Meanwhile there's a hack to make it work in 3.18.3 without patching cmake.
The issue is there's `\.` which should be `\\.` instead.
Could you change this line to 3.1?
https://github.com/pytorch/vision/blob/662373f6057bb0d39eaf6e5fde3083639ed93af3/CMakeLists.txt#L1

That will set `CMP0053=New`, which makes the `\.` recognizable as `.` (escaped `.`), and matches everything in regex, including a dot in version.

**Comment by fmassa** [comment]
@xkszltl can you send a PR with the proposed fix, linking to this issue?

**Comment by xkszltl** [comment]
Sure, I thought you guys would just put it in whatever PR that comes next.
