### ISSUE TITLE
Test the model with an image

### ISSUE THREAD

**Issue by jiaerfei** [pytorch/vision#2711]
Hello
I compressed Mask R-CNN and finished the training,  but the checkpoint (.pth) is different from the regular one, what can I do if I want to load the checkpoint to Mask R-CNN to test its speed with a new image? Thank you!

**Comment by fmassa** [comment]
Hi,

You can use the `references/detection/train.py` to load a checkpoint and perform evaluation.
Here is the relevant code 
https://github.com/pytorch/vision/blob/81d764877523e491af03d3e37f6b295f9d8a6cbb/references/detection/train.py#L112-L121

Let us know if you have further questions!
