### ISSUE TITLE
quantized models googlenet and shufflenet not JIT scriptable

### ISSUE THREAD

**Issue by mikeseven** [pytorch/vision#2712]
Using torchvision 0.7.0 and pytorch 1.6.0 from conda.

#1949 doesn't solve the issue of aux=None in googlenet quantized model.
A solution is to add ```if submodule is not None:``` in line 2234 of ```torch.jit.__init__.py```

shufflenet_v2 JITing crashes with 
```Comparison exception: promoteTypes with quantized numbers is not handled yet; figure out what the correct rules should be, offending types: QUInt8 Float```
Only shufflenet_v2_x1_0 is usable, other versions have no URL

**Comment by fmassa** [comment]
@mikeseven could you send a PR fixing the bug you mentioned?

**Comment by mikeseven** [comment]
I'm not sure I did it correctly because it's only one line change but tons of lines against pytorch master
PR is #45472 in pytorch repo

**Comment by fmassa** [comment]
@mikeseven I think it would just be simpler / easier to send a PR to torchvision changing the implementation of GoogleNet / Inception quantized models to implement the patches from #1949 there.
The PR you sent to PyTorch targets branch 1.6.0, and we will most probably not be cutting a new release on top of the 1.6.0 branch.

**Comment by datumbox** [comment]
Fixed by #1974
