### ISSUE TITLE
What's the pretrained_settings for r2plus1d_18?

### ISSUE THREAD

**Issue by XinyuLyu** [pytorch/vision#2717]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
Hi,
I want to know the pretrained_settings for r2plus1d_18, which has not been implemented, including input_space,input_size,input_range,mean,std.  In pytorch.pretrainedmodels, they implement resnet152, vgg19_bn, inceptionv4 with those pretrained_settings, which are necessary for TransformImage to transform the image. If include pretrained_settings, it will be more user-friendly for r3d_18,mc3_18,r2plus1d_18 models to extract vidoe frame features.Many thanks!
![image](https://user-images.githubusercontent.com/33551398/94428918-1c015800-01c4-11eb-910d-bb4e39d9fd13.png)

cc @bjuncek

**Comment by bjuncek** [comment]
Hi @XinyuLyu, the parameters were as follows:
```
pretraining dataset: Kinetics 400 (June 2018 snapshot)
input_space: RGB
input_size: 16x112x112
mean=[0.43216, 0.394666, 0.37645]
std=[0.22803, 0.22145, 0.216989]
num_classes: 400
```


I will add README.md to the video classification models to make this clear :)

Thanks for your question,
Bruno

**Comment by XinyuLyu** [comment]
Thank you so much!!!

**Comment by fmassa** [comment]
Also note that those models were trained on 64 GPUs. Further details are in #2723
