### ISSUE TITLE
I think the Anchor generator have some problem when generate the anchors

### ISSUE THREAD

**Issue by dang-qi** [pytorch/vision#2719]
I think the code here has some problem

> for size, stride, base_anchors in zip(
            grid_sizes, strides, cell_anchors
        ):
https://github.com/pytorch/vision/blob/505cd6957711af790211896d32b40291bea1bc21/torchvision/models/detection/rpn.py#L124

It should be:

` for size, stride, base_anchors in zip(
            grid_sizes, strides, cell_anchors
        ):`
    `for base_anchors in cell_anchors:`
           `         do other stuff`

**Comment by dang-qi** [comment]
The code was correct. I just used it wrong. Sorry

**Comment by fmassa** [comment]
@dang-qi yes, I agree that the default can be misleading. I would be happy accept a PR improving the comments / changing the default in a BC-compatible way
