### ISSUE TITLE
fatal error: 'jpeglib.h' file not found

### ISSUE THREAD

**Issue by zcain117** [pytorch/vision#2724]
## 🐛 Bug

@andfoy @fmassa 
My team builds torch and torchvision from source using Google Cloud Build running `debian:stretch` base docker image. After #2696 was submitted, our builds started to fail with:
```
Step #1: [91mIn file included from /pytorch/vision/torchvision/csrc/cpu/image/jpegcommon.cpp:1:
Step #1: /pytorch/vision/torchvision/csrc/cpu/image/jpegcommon.h:7:10: fatal error: 'jpeglib.h' file not found
Step #1: #include <jpeglib.h>
Step #1:          ^~~~~~~~~~~
Step #1: [0m[91m1 error generated.
```

Is there something we should do now that #2696 was submitted to be able to build?
E.g. is it expected we should have to run `apt-get install libjpeg` or something similar?
And is there any way to build torchvision without needing to install new packages, e.g. by building without jpeg support?

## To Reproduce
```
function install_torchvision_from_source() {
  # Cannot install torchvision package with PyTorch installation from source.
  # https://github.com/pytorch/vision/issues/967
  git clone -b master https://github.com/pytorch/vision.git
  pushd vision
  python setup.py bdist_wheel
  pip install dist/*.whl
  popd
}
```

## Environment
Google Cloud Build running `debian:stretch` base docker image

**Comment by andfoy** [comment]
Hi @zcain117, thanks for opening this issue, this is a problem indeed with `jpegcommon.cpp`, I forgot to check for the `JPEG_FOUND` guard there

**Comment by andfoy** [comment]
@zcain117, does https://github.com/pytorch/vision/pull/2725 fixes this issue?

**Comment by zcain117** [comment]
Thanks for taking a look!
I think that would fix it. I'm looking into how I can force Google Cloud Build to check out pending code to try it, but the build takes over an hour to reach the failing point so it will be a while until I can tell if it works

**Comment by zcain117** [comment]
@andfoy LGTM! The build is still running but it's past the torchvision step so I think #2725 is a good fix

**Comment by andfoy** [comment]
@zcain117, great to hear that it works now!

**Comment by fmassa** [comment]
Thanks for raising this issue @zcain117 ! Should be fixed now, and we should add one CI in torchvision to catch those regressions in the future.
