### ISSUE TITLE
Isssue reagading documentattion

### ISSUE THREAD

**Issue by gujralsanyam22** [pytorch/vision#2733]

**Comment by gujralsanyam22** [comment]
UpdateReadme.md

**Comment by vfdev-5** [comment]
@gujralsanyam22 could you detail the issue with the documentation ?

**Comment by fmassa** [comment]
This is related to https://github.com/pytorch/vision/pull/2732

**Comment by gujralsanyam22** [comment]
Yes

**Comment by fmassa** [comment]
Closing following https://github.com/pytorch/vision/pull/2732#issuecomment-702021731
