### ISSUE TITLE
Has anyone successfully compiled the C++ API on Windows, including the cuda code?

### ISSUE THREAD

**Issue by thisisi3** [pytorch/vision#2752]
I have tried many versions of torchvision, none seems to work for me. (on Windows)
1, The old version 0.5.0 simply does not include cuda code into the build. 
2, Then I tried 0.6.0, it has the "-openmp" not support error. After a lot of searching and trying, I solved it by deleting one line in the torchvision.vcxproj.
3, 0.6.0 finally gets to compile, but it gives "unresolved external symbol" error if i want to use nms_cuda, according to this issue #2139, the cuda impl of operators are not included in torchvision.lib.
4, Then I tried the recent 0.7.0 tag and it gives "A single input file is required for a non-link phase when an outputfile is specified" error, this one (#2677) simply no one here knows how to solve it. Other resources suggests it might due to misplaced white space...

Could you point me to a version that works on Windows? Or simply no support for Windows?

cc @peterjc123 @nbcsm @guyang3532 @maxluk @gunandrose4u @smartcat2010 @mszhanyi

**Comment by peterjc123** [comment]
Sorry for not making it work. Please see me answer in https://github.com/pytorch/vision/issues/2677#issuecomment-703427649. And it will work out of box once https://github.com/pytorch/vision/pull/2754 is merged.
