### ISSUE TITLE
Add a .gitattributes file to fix line count of Jupyter notebook

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#2771]
## 🚀 Feature

Not exactly a Feature Request.
Jupyter notebooks lead to a lot of line count since GitHub does not render them properly. 
Adding new Jupyter notebooks will soon make this library with primary langauge of Jupyter very high. 
While this library is in python. This creates a misconception in first sight.

A neat workaround is to have a `.gitattributes` file as follows. Remove `#` Where suitable
```
# Jupyter notebook

# For text count
# *.ipynb  text

# To ignore it use below
# *.ipynb linguist-documentation
```

This is just a harmless addition. I guess it does not impact library.

**Comment by fmassa** [comment]
That sounds like a good addition to me. Can you open a PR adding this?

**Comment by vfdev-5** [comment]
> Adding new Jupyter notebooks will soon make this library with primary langauge of Jupyter very high.
> A neat workaround is to have a .gitattributes file as follows. Remove # Where suitable

Even with the PR merged, library is dominated by Jupyter notebook.

<img width="253" alt="Screen Shot 2020-11-17 at 15 50 26" src="https://user-images.githubusercontent.com/2459423/99405132-b3457a80-28ec-11eb-942d-1146b710d1f0.png">

**Comment by oke-aditya** [comment]
Probably that's because this keeps track of `git history`.
It actually works and is reduces the line count significantly.

**Comment by fmassa** [comment]
@oke-aditya let's ignore notebooks for this statistic counting, can you send a PR for that?

**Comment by oke-aditya** [comment]
Sure
