### ISSUE TITLE
Warning while generating Docs

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#2787]
## 🐛 Bug

When we generate docs (locally) there are small warnings.

## To Reproduce

Build the docs by doing following

1. `cd docs`
2. `make html`

![image](https://user-images.githubusercontent.com/47158509/95674764-22360200-0bd0-11eb-9d7b-6acc52f120bf.png)

## Expected behavior

Can we avoid these warnings? They look very minor fixes.

## Environment

 - PyTorch / torchvision Version: 1.6.0 / master
 - OS (e.g., Linux): Windows 10 
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `pip install . `
 - Python version: 3.6
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information:

## Additional context

Looks like its just formatting problems. Maybe good to patch fix

**Comment by fmassa** [comment]
Yes, please! A PR fixing those would be great. We currently don't have CI to test documentation building, but we should have one.

**Comment by oke-aditya** [comment]
I'm closing this PR as we modfied Sphinx #3290 warnings, Now we generate no such warning (only error which are caught in CI)
