### ISSUE TITLE
python_type_check CI is broken

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#2790]
This looks like an upstream change that broke CI, see https://app.circleci.com/pipelines/github/pytorch/vision/4305/workflows/9ae30f70-6fa0-419f-966b-8db2e249a12b/jobs/254769 for an example

The error we get is
```
torchvision/datasets/mnist.py:446: error:
Incompatible
return
value
type
(got
"GzipFile",
expected
"IO[Any]")

[return-value]
            return gzip.open(path, 'rb')
                   ^
Found 1 error in 1 file (checked 97 source files)
```

cc @seemethere @pmeier

**Comment by pmeier** [comment]
I'm on it.

**Comment by pmeier** [comment]
This is caused by [`mypy==0.790`](https://mypy-lang.blogspot.com/2020/10/mypy-0790-released.html) released two days ago. It includes python/typeshed@846d922df238d307a99347f74d91ccb362f876ad which amongst others makes the return types of the `gzip` module more precise.

**Comment by fmassa** [comment]
@pmeier so does this mean that using an older mypy will give type checking errors?

**Comment by pmeier** [comment]
It shouldn't, but I'm not sure. I'll check and get back to you.

**Comment by vfdev-5** [comment]
Just checked with mypy 0.780 on the master -> no issues
```
$ mypy --config-file mypy.ini
Success: no issues found in 97 source files
$ pip list | grep mypy
mypy                   0.780
$ git log -1
commit 610c9d2a063bf0695d4f1c3cc396f0c1f2c3a4af (HEAD -> master, origin/master)
Author: Adeel Hassan <AdeelH@users.noreply.github.com>
Date:   Mon Oct 12 13:53:17 2020 +0500

    remove hard coded value (#2793)
```

**Comment by fmassa** [comment]
awesome, thanks for checking!
