### ISSUE TITLE
libopencv_imgcodecs: undefined reference to `LIBTIFF_4.0'

### ISSUE THREAD

**Issue by jhacsonmeza** [pytorch/vision#2795]
## 🐛 Bug

After building TorchVision, I've tried to run the [C++ example](https://github.com/pytorch/vision/tree/master/examples/cpp/hello_world) and I get the following error:

```
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFWriteEncodedStrip@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFClose@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFGetField@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFWriteDirectory@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFReadEncodedTile@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFReadRGBATile@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFClientOpen@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFOpen@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFSetField@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
/usr/bin/ld: /usr/local/lib/libopencv_imgcodecs.so.4.4: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/model.dir/build.make:99: model] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/model.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

## To Reproduce

1. `cmake -DCMAKE_PREFIX_PATH="${HOME}/pytorch/torch;${HOME}/vision/torchvision" ..`
2. `cmake --build .`

In `CMakeLitsts.txt` I have:

```
cmake_minimum_required(VERSION 3.10)
project(hello-world)

# The first thing do is to tell cmake to find the TorchVision library.
# The package pulls in all the necessary torch libraries,
# so there is no need to also add `find_package(Torch)` here.
find_package(Torch REQUIRED)
find_package(TorchVision REQUIRED)

add_executable(hello-world main.cpp)

# We now need to link the TorchVision library to our executable.
# We can do that by using the TorchVision::TorchVision target,
# which also adds all the necessary torch dependencies.
target_compile_features(hello-world PUBLIC cxx_range_for)
target_link_libraries(hello-world TorchVision::TorchVision)
set_property(TARGET hello-world PROPERTY CXX_STANDARD 14)
```

It is necessary for me to add `find_package(Torch REQUIRED)` otherwise I get `fatal error: torchvision/models/resnet.h: No such file or directory`.

## Environment

- PyTorch / torchvision Version: (1.6.0a0+b31f58d / 0.7.0a0+78ed10c)
 - OS: Ubuntu 20.04
- Command used to install PyTorch/LibTorch: `USE_CUDA=1 USE_CUDNN=1 USE_OPENCV=1 python setup.py install`
- Command used to install TorchVision: `cmake -GNinja -DCMAKE_PREFIX_PATH=${HOME}/pytorch/torch -DCMAKE_INSTALL_PREFIX=${HOME}/vision/torchvision -DWITH_CUDA=on .. && cmake --build . --target install` 
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.0/8.0.2

## Additional context

I built LibTorch from source with `USE_OPENCV=1` and with an Anaconda environment. I have been working with with OpenCV and LibTorch without any problem. The problem is just with TorchVision that I recently tried to install it. I also built TorchVision with the same Anaconda environment that I used with LibTorch. I think it is worth to know that before of installing OpenCV, I installed libtiff with `sudo apt install libtiff-dev`.

**Comment by fmassa** [comment]
Hi,

I'm not sure why your OpenCV install is not picking libtiff.

We have CI that compiles and run the example, which was added in https://github.com/pytorch/vision/pull/2678, and you can see in `build_cmake.sh` the commands we used to compile and install torchvision example.

@andfoy do you happen to know what might be the issue?

**Comment by jhacsonmeza** [comment]
I think I found the problem. When I installed TorchVision I used a conda environment as Python3-dev is needed for built the library. But I found that I have `libtiff.so` in `/usr/lib/x86_64-linux-gnu` and also in `~/anaconda3/envs/myenv/lib`. Perhaps OpenCV and TorchVision are linking `libtiff.so` from different locations and that caused the problem.

I rebuilt TorchVision from another clean Anaconda environment and it worked without CUDA support. But when I compiled with CUDA support, I get this error `error while loading shared libraries: libc10_cuda.so: cannot open shared object file: No such file or directory`.

**Comment by zhiqwang** [comment]
> I rebuilt TorchVision from another clean Anaconda environment and it worked without CUDA support. But when I compiled with CUDA support, I get this error `error while loading shared libraries: libc10_cuda.so: cannot open shared object file: No such file or directory`.

```bash
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/libtorch/lib/
```

Hi @jhacsonmeza , this problem may be caused by missing of libs in `ldd` , you can check for this method as mentioned in [#2609](https://github.com/pytorch/vision/issues/2609#issuecomment-682380995)

**Comment by jhacsonmeza** [comment]
Hi @zhiqwang, thank you so much, it worked. Also, as you pointed in https://github.com/pytorch/vision/issues/2609#issuecomment-681911111 copying `libtorchvision.so` from `build` to `${CMAKE_INSTALL_PREFIX}/lib` works. Thank you again.
