### ISSUE TITLE
Pretrained VGG models

### ISSUE THREAD

**Issue by jcjohnson** [pytorch/vision#28]
Is there any plan for pretrained VGG models, especially VGG16 or VGG19? These are needed for style transfer; AlexNet and ResNets tend not to work as well in my experience.

**Comment by colesbury** [comment]
Yes, I'll train them this week or grab some weights from another framework.

**Comment by jcjohnson** [comment]
I've converted Karen Simonyan's VGG-16 and VGG-19 models here:

https://github.com/jcjohnson/pytorch-vgg

The converted models are available here:

VGG-16: https://s3-us-west-2.amazonaws.com/jcjohns-models/vgg16-00b39a1b.pth

VGG-19: https://s3-us-west-2.amazonaws.com/jcjohns-models/vgg19-d01eb7cb.pth

These are exact conversions of Karen's Caffe checkpoints, so they expect BGR images in the range [0, 255] with the BGR value [103.939, 116.779, 123.68] subtracted from each pixel; I suspect that this is different from the pretrained AlexNet and ResNets in the model zoo.

Feel free to add them to the model zoo if you want, but it would be convenient if all pretrained models used the same preprocessing.

**Comment by soumith** [comment]
nice. sam is training new ones (he finally got them to start converging on friday) and he wants to commit newly trained ones into the zoo.
He wants to do it for reproducibility, where the model definition in torchvision.models if trained from scratch, will be guaranteed to get to the same approx place as where the pre-trained model is.

**Comment by jcjohnson** [comment]
@soumith Having the official model zoo consist of things trained from scratch seems like a good policy. I was mostly just impatient and wanted to use VGG networks this weekend.

**Comment by skrish13** [comment]
Any idea when we can expect pre-trained models for VGG?

**Comment by colesbury** [comment]
I trained VGG, but got below state of the art results (I think due to the weight initialization). I'll try changing the weight initialization and retraining.

**Comment by HarshaVardhanP** [comment]
follow up : when can we expect VGG16 pretrained model ? Thanks

**Comment by soumith** [comment]
in a few more days, probably a week. @colesbury is training them again.

**Comment by colesbury** [comment]
Pre-trained VGG models are now available in master
