### ISSUE TITLE
Empty expected values on test_retinanet_resnet50_fpn

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#2810]
## 🐛 Bug

The Unit-test expected values of RetinaNet are empty and thus the test does not protect us from breaking the code.

## To Reproduce

```
>>> import torch
>>> expected = torch.load("./test/expect/ModelTester.test_retinanet_resnet50_fpn_expect.pkl")
>>> print(expected)
[{'boxes': tensor([], size=(0, 4), requires_grad=True), 'scores': tensor([], requires_grad=True), 'labels': tensor([], dtype=torch.int64)}]

```

## Expected behavior

Ensure we have some non-trivial expected values so that we detect it when the code breaks. @fmassa advised to try and find a way that does not involve download pretrained weights.

**Comment by vfdev-5** [comment]
@datumbox I wonder if this issue is exclusively for retinanet ?

**Comment by datumbox** [comment]
@vfdev-5 yes it is! Every other model is fine. :)
