### ISSUE TITLE
Inconsistent datatype from train_loader.dataset.train_data

### ISSUE THREAD

**Issue by iacolippo** [pytorch/vision#282]
I've noticed that the type of data contained in the data loaders are different from one dataset to another. For example

`data_loader.dataset.train_data` with CIFAR10 is a `np.array`, while with MNIST it is a `torch.Tensor`

Is this for some reason? 

I think it should be uniformed because I often write code which requires knowing something from the training data and if I want to write it for multiple dataset this is a bit inconvenient.

**Comment by alykhantejani** [comment]
hi @iacolippo - I don't theres a specific reason as to why the data is stored this way inside the datasets. AFAIK both formats are fine for the [default collate function](https://github.com/pytorch/pytorch/blob/833bedc77d645643462490080f37b6ef9b1d63c5/torch/utils/data/dataloader.py#L82) of the `DataLoader`. 

If you want to access data in a consistent format, one option is to pass the `transform=ToTensor()` to the dataset and access the elements via the `__getitem__` function (via `[]`). This will ensure you get a tensor version of the images back, as both datasets convert the internal representation to a PIL Image before passing it to the transforms.

**Comment by iacolippo** [comment]
Ok, that's reasonable, even though this asymmetry annoys my OCD 😄 Thank you. Closing.
