### ISSUE TITLE
Setting number of cores for python3 setup.py install

### ISSUE THREAD

**Issue by ylmzkaan** [pytorch/vision#2822]
Hi,

I am trying to build torchvision from source but when I run python3 setup.py install, it starts to use all 6 cores by default and eventually my machine goes out of memory. 

How can I limit the number of cores used during the build so that it consumes less RAM?

**Comment by vfdev-5** [comment]
Can you try to set `MAX_JOBS=X` to control that ?

**Comment by ylmzkaan** [comment]
> @ylmzkaan Can you try to set `MAX_JOBS=X` to control that ?

I tried that but it didnt help. Still builds with all cores.

**Comment by vfdev-5** [comment]
Can you confirm that if you do 
```
export MAX_JOBS=1
python setup.py install
```
You see `Using envvar MAX_JOBS (1) as the number of workers...` message while building C++ extensions ?

**Comment by ylmzkaan** [comment]
> Can you confirm that if you do
> 
> ```
> export MAX_JOBS=1
> python setup.py install
> ```
> 
> You see `Using envvar MAX_JOBS (1) as the number of workers...` message while building C++ extensions ?

I guess we got something. It says `Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)`

Any idea on how to not allow ninja to do that?

**Comment by vfdev-5** [comment]
Can please detail which torchvision version you build: master, a tag; what is your OS and full command to build it ?

**Comment by ylmzkaan** [comment]
I pulled the master branch and when I run python3 setup.py install to build it builds version torchvision-0.8.0a0+072d8b2 . I have python 3.6 installed. OS is ubuntu 16 running on nvidia drive px 2.

**Comment by vfdev-5** [comment]
OK, and if you run `export MAX_JOBS=1 && python3 setup.py install` you still see your above message ?

**Comment by ylmzkaan** [comment]
> OK, and if you run `export MAX_JOBS=1 && python3 setup.py install` you still see your above message ?

That is correct

**Comment by vfdev-5** [comment]
The messages like "Using envvar MAX_JOBS (1) as the number of workers..." or "Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)" are printed in pytorch:

https://github.com/pytorch/pytorch/blob/ecf63351bcdbba612bd3bd4b525c5ac105c12493/torch/utils/cpp_extension.py#L1479

And this should provide `-jN` cmd line arg to ninja. It worth to debug on your system why even setting the env var `MAX_JOBS` pytorch methods do not see it correctly. This is how it is expected from pytorch side.
```
    max_jobs = os.environ.get('MAX_JOBS')
    if max_jobs is not None and max_jobs.isdigit():
```

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
