### ISSUE TITLE
Add verbosity kwarg to downloading functions

### ISSUE THREAD

**Issue by fepegar** [pytorch/vision#2830]
## 🚀 Feature

Add a kwarg to controle verbosity of downloading functions.

## Motivation

For different reasons, I would like to control whether my code is allowed to print stuff. At the moment, functions such as `torchvision.datasets.utils.download_url` have multiple calls to `print`:

https://github.com/pytorch/vision/blob/a9c78f1b017d912fa9583ae6d93bff0a3807c29b/torchvision/datasets/utils.py#L46-L87

## Pitch

I would like to be able to control whether any messages are print. I can open a PR and add a `verbose=True` kwarg to these functions to control this behavior.

## Alternatives

Use `sys` to write a little hack to hide printed messages.

## Additional context

cc @pmeier

**Comment by mthrok** [comment]
I do not think it is a good idea to introduce a new argument for non-mission critical one. Instead, the library should use the proper logging mechanism that users can turn off on their side.
