### ISSUE TITLE
Missing docstring for make_dataset method

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#2841]
## 📚 Documentation

Public method `make_dataset` does not have a docsting:
https://github.com/pytorch/vision/blob/0467c9d74c9b34f91df905ed8cf8433de48d7fa5/torchvision/datasets/folder.py#L35-L42

It would be nice to add one.

cc @pmeier

**Comment by bjuncek** [comment]
I'm willing to pick that up if needed?

**Comment by fmassa** [comment]
Fixed via https://github.com/pytorch/vision/pull/2879
