### ISSUE TITLE
Can pretrained resnet-50 extract feature from a higher resolution picture?

### ISSUE THREAD

**Issue by Frank-Dz** [pytorch/vision#2850]
Can pre-trained ResNet-50 extract feature from a higher resolution picture?

Typically, when we use Resnet to extract features, we need to crop the image into  224 x 224 then pass the image to ResNet.

I want to know if we want a larger image( e.g. 720 x 720) to be processed, we have to modify the network and re-train the network? Can we directly use the original pre-train network? Is the quality of feature extraction guaranteed?

Thanks!

**Comment by fmassa** [comment]
Hi,

You can feed larger resolution images to resnets, and it should work ok without finetuning (although fine-tuning on higher resolution images will work even better).

This is what we generally do for the semantic segmentation and object detection models in torchvision, although they are fine-tuned.
