### ISSUE TITLE
Hello , i found a mismatch between the implemented torchvision.models.detection.backbone_utils.resnet_fpn_backbone() in github and what we get by installing via pip, the one in github is having returned_layer and extra_blocks as parameters but one we get by installign doesnt have any of these parameters,

### ISSUE THREAD

**Issue by akashprakas** [pytorch/vision#2878]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by akashprakas** [comment]
The one in github
def resnet_fpn_backbone(
    backbone_name,
    pretrained,
    norm_layer=misc_nn_ops.FrozenBatchNorm2d,
    trainable_layers=3,
    returned_layers=None,
    extra_blocks=None
):


The one i got after installation in ubuntu20.04,cuda10.2 is
def resnet_fpn_backbone(backbone_name, pretrained,
norm_layer=misc_nn_ops.FrozenBatchNorm2d, trainable_layers=3):

i needed the returned layers parameters so that i can control the layers returned

**Comment by fmassa** [comment]
Hi,

You need to install torchvision from a nightly version to be able to get the latest features from GitHub.

Check the installation instructions from https://pytorch.org/get-started/locally/ to install a nightly from pytorch and torchvision.

**Comment by akashprakas** [comment]
Thank you :)
