### ISSUE TITLE
Building Autoencoders

### ISSUE THREAD

**Issue by seyeeet** [pytorch/vision#2882]
## 📚 Documentation
can we have a toturial like this in pytorch
https://blog.keras.io/building-autoencoders-in-keras.html

**Comment by zhangguanheng66** [comment]
Transfer the issue here since this repo is more relevant.

**Comment by seyeeet** [comment]
just curious what kinda help is needed?

**Comment by vfdev-5** [comment]
@seyeeet which part of keras blog post you think to have as tutorial in pytorch ?

**Comment by seyeeet** [comment]
The whole page is useful, but I am specifically more interested in the representation parts and visualizations, I think there is already a lot of repos that cover the VAE part, but the visualization and representation (toward the end) can be really useful to have.

**Comment by vfdev-5** [comment]
@seyeeet there is also a tutorial on visualization with TensorBoard : https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html
Is it something like that you'd like to see ?

**Comment by seyeeet** [comment]
not really, the tsne part was my main focus tbh and how to change the parameters in vae to visualize the different latent space in the vae.

**Comment by seyeeet** [comment]
I am going to close this issue, I found that I can combine a vae code with the explanation that is provided [here](https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html)
thanks
