### ISSUE TITLE
Fill colors for tensor affine transforms

### ISSUE THREAD

**Issue by voldemortX** [pytorch/vision#2887]
## 🚀 Feature
Support fill color other than 0 for tensor affine transforms (rotate, affine).

## Motivation

It is important for pixel-wise tasks (e.g. segmentation) to have different fill color for ignored label (e.g. 255).

## Pitch

Different fill colors are supported for tensors like already supported for PIL images in affine transformations.
Specifically, for **rotate()** and **affine()** in transforms/functional_tensor.py.

## Alternatives

None at the moment.

## Additional context

The requested feature was not supported in the recently completed tensor/PIL unification process #2292 probably due to pytorch grid_sampler(), which is what the implementations based on, does not seem to support fill colors other than 0.

 @vfdev-5

**Comment by fmassa** [comment]
FYI it is possible to let torchvision implementation support different fill colors than 0 despite `grid_sample` limitations, by performing grid_sample twice (first on the image, second on a dummy mask), so that we can mask out the fill values and replace them with the user-input.

**Comment by voldemortX** [comment]
Yeah, it could be a good enough workaround for now.

**Comment by vfdev-5** [comment]
@voldemortX following @fmassa 's idea, it could be also possible to append this data mask to the image as additional channel and apply grid_sample once. We think that such solution can be added to torchvision. If you would like to work on that, it would be helpful 👍 .

**Comment by voldemortX** [comment]
I can try it out, but thinking more on it i'm a bit confused right now. shouldn't the easiest way be replacing the 0 afterwards?

**Comment by vfdev-5** [comment]
> shouldn't the easiest way be replacing the 0 afterwards?

What do you mean by replacing the 0 ?

**Comment by voldemortX** [comment]
Oh right, I understand now, the original image could have 0.

**Comment by voldemortX** [comment]
I can try it tomorrow or something (UTC-8), but I have not contributed any code before, is unit tests required for a patch like this?

**Comment by vfdev-5** [comment]
> I can try it tomorrow or something (UTC-8), but I have not contributed any code before, is unit tests required for a patch like this?

Sounds good ! Let me describe how I'd do that and put some links on the code to modify. Yes, tests are required. To start contributing, please read this [draft CONTRIBUTING guide](https://github.com/pytorch/vision/pull/2663/files).
Btw, if something is unclear in the guide feel free to comment out the PR. Thanks

**Comment by voldemortX** [comment]
> > I can try it tomorrow or something (UTC-8), but I have not contributed any code before, is unit tests required for a patch like this?
> 
> Sounds good ! Let me describe how I'd do that and put some links on the code to modify a bit later. Yes, tests are required. To start contributing, please read this [draft CONTRIBUTING guide](https://github.com/pytorch/vision/pull/2663/files).
> Btw, if something is unclear in the guide feel free to comment out the PR. Thanks

Ok, thanks.

**Comment by voldemortX** [comment]
Said feature is now supported.
