### ISSUE TITLE
About aux loss.

### ISSUE THREAD

**Issue by wangshihuang** [pytorch/vision#2888]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

Why add aux loss in deeplabv3 in the segmentation. What is the effect.

**Comment by vfdev-5** [comment]
Please, post this question to the discussion forum. Thanks.
