### ISSUE TITLE
can't download libtorch 1.4

### ISSUE THREAD

**Issue by omeryasar** [pytorch/vision#2889]
Hi I want to download libtorch 1.4 but there is no download link for it in official page and I can't find it when I search it on google. How can I download this specific version.

**Comment by vfdev-5** [comment]
@omeryasar try this : https://download.pytorch.org/libtorch/cu101/libtorch-cxx11-abi-shared-with-deps-1.4.0.zip

I close the issue as it is unrelated to torchvision project but more a question to pytorch.
