### ISSUE TITLE
How to change the num_classes from 1000 in vgg?

### ISSUE THREAD

**Issue by SunJJ1996** [pytorch/vision#2919]
I use
        model = vgg.vgg16(pretrained=True, progress = True, num_classes=10)
and use pretrained model     'vgg16': 'https://download.pytorch.org/models/vgg16-397923af.pth',
then, the error happend:
RuntimeError: Error(s) in loading state_dict for VGG:
	size mismatch for classifier.6.weight: copying a param with shape torch.Size([1000, 4096]) from checkpoint, the shape in current model is torch.Size([10, 4096]).
	size mismatch for classifier.6.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([10]).

when i use          model = vgg.vgg16(pretrained=True, progress = True, num_classes=1000)
error above not occur, but after seizing a long time, cuda out of memory.
so how can i fix these?

**Comment by vfdev-5** [comment]
@SunJJ1996 the error says that you can not use pretrained weights for the last fully-connected layer as they do not have same sizes:
- pretrained weights are for ImageNet with 1000 classes : size = 1000, 4096
- your layer has weights with size = 10, 4096

You can define a model with 1000 classes, load pretrained weights for 1000 classes and manually remplace the last layer:
```python
model = vgg.vgg16(pretrained=True, progress = True, num_classes=1000)
model.classifier[6] = nn.Linear(4096, 10)
```

**Comment by SunJJ1996** [comment]
> @SunJJ1996 the error says that you can not use pretrained weights for the last fully-connected layer as they do not have same sizes:
> 
>     * pretrained weights are for ImageNet with 1000 classes : size = 1000, 4096
> 
>     * your layer has weights with size = 10, 4096
> 
> 
> You can define a model with 1000 classes, load pretrained weights for 1000 classes and manually remplace the last layer:
> 
> ```python
> model = vgg.vgg16(pretrained=True, progress = True, num_classes=1000)
> model.classifier[6] = nn.Linear(4096, 10)
> ```

thank you for helping! but cuda also out of memory. 
RuntimeError: CUDA out of memory. Tried to allocate 12.20 GiB (GPU 0; 10.92 GiB total capacity; 800.47 MiB already allocated; 9.47 GiB free; 804.00 MiB reserved in total by PyTorch)
besides, i have two nvidia 1080ti, but it seems just use gpu0. 
i add this code above all :os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'
but it does not work

**Comment by vfdev-5** [comment]
>  cuda also out of memory.

@SunJJ1996 try to use smaller images

>  besides, i have two nvidia 1080ti, but it seems just use gpu0

You have to use DP/DDP for that:
- https://pytorch.org/docs/stable/nn.html#dataparallel-layers-multi-gpu-distributed

**Comment by SunJJ1996** [comment]
> > cuda also out of memory.
> 
> @SunJJ1996 try to use smaller images
> 
> > besides, i have two nvidia 1080ti, but it seems just use gpu0
> 
> You have to use DP/DDP for that:
> 
> * https://pytorch.org/docs/stable/nn.html#dataparallel-layers-multi-gpu-distributed

really thanks for reply. I change the I'mg_size from 640 to 320, then a new error occur
IndexError: too many indices for tensor of dimension 2
I don't know how to fix it

**Comment by vfdev-5** [comment]
@SunJJ1996 you have to check the shape of your `outputs` (File "/data2/sunjunjiao/CRAFT_scale/train.py", line 134, in train)
The error says that it is not 4D as it is required in the code `outputs[:, 0, :, :]`. 

Another option to keep your image size as 640 but able to put everything into 1 GPU is to reduce the batch size.

Let me close the issue as answered to the main question. For debugging questions, please use the forum: https://discuss.pytorch.org/ . Thanks
