### ISSUE TITLE
Cannot use Inception3 model created in previous version in PyTorch 1.6+ (Vision 0.7+)

### ISSUE THREAD

**Issue by Stehsegler** [pytorch/vision#2923]
## 🐛 Bug

I am completely new to PyTorch and currently familiarizing myself with a project someone else created (and which unfortunately is not open source so I cannot share any code or exported model). With this background, I hope my report is concise enough for you to reproduce my problem.

As far as I understand, model loading in PyTorch should be backwards compatible, i.e. I can use models created in earlier versions of PyTorch in later versions. However, for me this does not seem to be the case for an InceptionV3 network created somewhere around PyTorch 0.4 when I try to run inference with it in PyTorch 1.6 and 1.7 (Torch Vision 0.7.0 and 0.8.0, respectively).

## To Reproduce

1. Load Inceptionv3 model created in earlier PyTorch version (e.g. PyTorch 0.4) in PyTorch 1.6 or higher using `torch.load()`.
1. Switch to evaluation mode using `model.eval()`.
1. Run inference: `output = model(input)`.

Result: A `ModuleAttributeError` is thrown saying `'Inception3' object has no attribute 'maxpool1'`. Stack trace:
```
Traceback (most recent call last):
  *** project-specific call hierarchy cut out ***
    output = model(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/models/inception.py", line 199, in forward
    x, aux = self._forward(x)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/models/inception.py", line 143, in _forward
    x = self.maxpool1(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'Inception3' object has no attribute 'maxpool1'
```

## Expected behavior

Inference runs without errors.

## Environment

I'm using the docker image `pytorch/pytorch:1.7.0-cuda11.0-cudnn8-runtime`.

Output from the [environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py):
```
Collecting environment information...
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729096996/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip] numpy==1.19.2
[pip] torch==1.7.0
[pip] torchelastic==0.2.1
[pip] torchvision==0.8.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0  
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.2.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.7.0           py3.8_cuda11.0.221_cudnn8.0.3_0    pytorch
[conda] torchelastic              0.2.1                    pypi_0    pypi
[conda] torchvision               0.8.0                py38_cu110    pytorch
```

## Additional context

Judging from the functions in the stack trace, the presumed backwards incompatibility was probably introduced in the refactoring of the InceptionV3 module in #2287 as there was no `self.maxpool1` before.

In PyTorch 1.5.1 (Vision 0.6.1) and earlier, everything works fine.

Thank you in advance!

**Comment by vfdev-5** [comment]
@Stehsegler what do you load with `torch.load`, complete model and not its `state_dict`, right ? 
As maxpool does not contain any parameters, so the change introduced in #2287 should not impact stored weights.

**Comment by Stehsegler** [comment]
Thank you very much for your quick response! Yes, I was loading the complete model. Indeed, I got it up and running by exporting the `state_dict` from PyTorch 1.5.1 and importing that into PyTorch 1.7.0.

So does that mean backwards compatibility for model loading is only given for `state_dicts`, but not for complete models? Is that documented somewhere?

Comparing the `print()`ed models, it becomes obvious that four new layers have been added in between 1.5.1 and 1.7:

```
...
  (maxpool1): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
...
  (maxpool2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
...
  (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
  (dropout): Dropout(p=0.5, inplace=False)
...
```

This brings up a follow-up question: Do the added layers influence the behaviour of the NN in any way? Or more precisely, will models trained with the old behaviour yield reliable inference results in the new version?

**Comment by vfdev-5** [comment]
> So does that mean backwards compatibility for model loading is only given for state_dicts, but not for complete models? Is that documented somewhere?

@Stehsegler please see here : https://pytorch.org/docs/stable/notes/serialization.html

> This brings up a follow-up question: Do the added layers influence the behaviour of the NN in any way? Or more precisely, will models trained with the old behaviour yield reliable inference results in the new version, despite the additional layers?

Those added layers should not influence the behaviour in any way between versions. They are NOT additional as corresponding operations were present in previous version:
https://github.com/pytorch/vision/pull/2287/files#diff-092b74a41e40a59ea3e31d8341e753664c7edf3b45b2c75b7de3772b4ebd0157L139

**Comment by Stehsegler** [comment]
Thank you once again for your helpful support!

> @Stehsegler please see here : https://pytorch.org/docs/stable/notes/serialization.html

Well, that just says using `state_dict` is recommended for compatibility reasons, which is a rather general statement. Maybe the docs could be improved by adding something more specific with regard to inter-version/backwards compatibility.


> Those added layers should not influence the behaviour in any way between versions. They are NOT additional as corresponding operations were present in previous version:
> https://github.com/pytorch/vision/pull/2287/files#diff-092b74a41e40a59ea3e31d8341e753664c7edf3b45b2c75b7de3772b4ebd0157L139
> 
> More info about reproducibility : https://pytorch.org/docs/stable/notes/randomness.html

Thank you for the clarification. I was already aware of the restrictions with regard to reproducibility and just wanted to rule out the possibility of a systematic error.

I think this issue can be closed.

**Comment by fmassa** [comment]
@vfdev-5 I think it would be useful to add a note in the models documentation pointing to https://pytorch.org/docs/stable/notes/serialization.html and saying that we guarantee compatibility with serialized state-dict, but not if the model is entirely serialized.
