### ISSUE TITLE
Unable to build wheel for 0.8.1

### ISSUE THREAD

**Issue by choidongyeon** [pytorch/vision#2932]
## 🐛 Bug

I am unable to create a wheel from the v0.8.1 tag. I already have pytorch 1.7 installed.

## To Reproduce

1. `git checkout tags/v0.8.1 -b v0.8.1`
1. `python setup.py clean`
1. `python setup.py bdist_wheel --universal --plat-name=manylinux1_x86_64` or `python setup.py install`

The last few couple lines are:
```
/vision/torchvision/csrc/cpu/video/Video.cpp:337:68: error: converting to ‘std::tuple<at::Tensor, double>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = at::Tensor&; _U2 = double&; <template-parameter-2-3> = void; _T1 = at::Tensor; _T2 = double]’
   std::tuple<torch::Tensor, double> result = {outFrame, frame_pts_s};
                                                                    ^
error: command 'gcc' failed with exit status 1
```
A full log can be viewed here: [output_bdist_wheel.log](https://github.com/pytorch/vision/files/5456508/output_bdist_wheel.log).

I am able to build/install v0.7.0 and earlier versions, but am unable to build v0.8.0 and v0.8.1.

Any help would be appreciated. Thanks!

## Expected behavior

Creation of a 0.8.1 torchvision binary.

## Environment
```
python -m torch.utils.collect_env
Collecting environment information...
/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: version 3.5.1

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.7.0
[conda] mkl                       2019.4                      243    anaconda
[conda] mkl-include               2019.4                      243    anaconda
[conda] mkl-service               2.3.0            py36he904b0f_0    anaconda
[conda] mkl_random                1.1.0            py36hd6b4f25_0    anaconda
[conda] numpy                     1.16.4           py36h95a1406_0    conda-forge
[conda] torch                     1.7.0                    pypi_0    pypi
```

## Additional context

cc @bjuncek

**Comment by vfdev-5** [comment]
@choidongyeon thanks for the report. I could reproduce your issue inside docker container with Ubuntu 16.04 and gcc 5.4.0.

This should be related to gcc version as according to [C++ ref](https://en.cppreference.com/w/cpp/utility/tuple)
```
std::tuple<int, int> foo_tuple() 
{
  return {1, -1};  // Error until N4387
  return std::tuple<int, int>{1, -1}; // Always works
  return std::make_tuple(1, -1); // Always works
}
```

If we manually replace
```diff
//  std::tuple<torch::Tensor, double> result = {outFrame, frame_pts_s};
  std::tuple<torch::Tensor, double> result = std::make_tuple(outFrame, frame_pts_s);
```
we can build the package.

**Comment by vfdev-5** [comment]
@choidongyeon recently merged PR #2937 should fix the problem on the master. Please build torchvision from master instead of the tag 0.8.1 and feel free to reopen this issue if it still does not work for you. Thanks

**Comment by fmassa** [comment]
I think we will be building a 1.7.1 release for PyTorch in December, so we might as well have this fix be pushed to the new torchvision release being built (0.8.2).

cc @seemethere the process would be to send cherry-pick PRs to `release/0.8.0` branch?

**Comment by choidongyeon** [comment]
Thanks @vfdev-5 !
