### ISSUE TITLE
Add notes about serialization to models docs

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#2939]
## 📚 Documentation

Following https://github.com/pytorch/vision/issues/2923#issuecomment-719650811 

> it would be useful to add a note in the models documentation pointing to https://pytorch.org/docs/stable/notes/serialization.html and saying that we guarantee compatibility with serialized state-dict, but not if the model is entirely serialized.

**Comment by saswatpp** [comment]
Apologies for not discussing prior to sending a PR. I thought that the task was small enough. Okay so I wanted to know if this a fix is still necessary ? @vfdev-5
