### ISSUE TITLE
the divide mistake of  positive and negative samples

### ISSUE THREAD

**Issue by fanjunkai-code** [pytorch/vision#2943]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
When dividing positive and negative samples, the gt_boxes index that anchor matches to is 0 will be mistaken as negative samples
for matched_idxs_per_image in matched_idxs:  

> positive = torch.nonzero(matched_idxs_per_image >= 1).squeeze(1)  

> negative = torch.nonzero(matched_idxs_per_image == 0).squeeze(1)

**Comment by fmassa** [comment]
Hi,

Thanks for raising this question, it's a good question indeed.

The input to `BalancedPositiveNegativeSampler` is not actually the indices of the GT, but the labels themselves (with 0 being the background label), see https://github.com/pytorch/vision/blob/5b61a5c8f89348b14a63deb95d5ee7aea9507051/torchvision/models/detection/roi_heads.py#L585-L586
As such, the code properly takes into account the GT values irrespective of its index.

I believe I've answered your question, and as such I'm closing this issue but let us know if you have further questions
