### ISSUE TITLE
Add test for 1 and 4-channel images to test_to_tensor

### ISSUE THREAD

**Issue by alykhantejani** [pytorch/vision#295]
Currently, `test_to_tensor` only tests for 3-channel inputs but the transform can accept 1 and 4-channel images too. 

We should add some additional tests to [this function](https://github.com/pytorch/vision/blob/master/test/test_transforms.py#L250)

cc @geoffroeder this would be a good starting PR if you're keen

**Comment by geoffroeder** [comment]
@alykhantejani sounds good, I'll start working on this
