### ISSUE TITLE
Support for compute capability 8.6

### ISSUE THREAD

**Issue by batrlatom** [pytorch/vision#2958]
Hi, I have tried to compile torchvision for rtx3070 and cuda 11.0, but without any luck. The code I am using is:
```USE_CUDA=1 USE_CUDNN=1 USE_MKLDNN=1 TORCH_CUDA_ARCH_LIST="8.6" python setup.py install```

But I am getting error that this compute capability is not supported. How can I make it compile? Thanks

**Comment by ptrblck** [comment]
Compute capability 8.6 is supported in CUDA>=11.1, so you would need to update your local CUDA toolkit or compile with 8.0+PTX.

**Comment by fmassa** [comment]
@ptrblck does it mean that we don't need to do anything in particular in torchvision? Would you say we can close this issue?

**Comment by ptrblck** [comment]
@fmassa I don't think you need to change anything in `torchvision` to build with 8.6, as we are doing it in our containers with CUDA11.1 and 8.6 without any changes.
I think we can close this issue.

**Comment by batrlatom** [comment]
ok, thanks for the clarification

**Comment by vfdev-5** [comment]
@batrlatom as @ptrblck told me, to compile with `8.0+PTX`, you can set `TORCH_CUDA_ARCH_LIST="8.0+PTX"` with your current cuda 11.0

**Comment by batrlatom** [comment]
I was able to compile pytorch witch cuda 11.1 and everything works as it should. Thanks!
