### ISSUE TITLE
Add pathlib.Path support to read_image

### ISSUE THREAD

**Issue by Yura52** [pytorch/vision#2962]
When I try to pass an object of `pathlib.Path` to `torchvision.io.read_image`, I get:
```
RuntimeError: image::read_file() Expected a value of type 'str' for argument '_0' but instead found type 'PosixPath'.
Position: 0
Value: PosixPath('<SOME PATH>')
Declaration: image::read_file(str _0) -> (Tensor _0)
Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

Casting the object to `str` fixes the problem. It would be nice to support the usual set of "path-like" types as input (str, bytes, pathlib.Path, ...)

```
python==3.8.3
torch==1.7.0
torchvision==0.8.1
```

**Comment by vfdev-5** [comment]
@Yura52 thanks for the feature request. This seems reasonable, however there could be a blocker if we would like to use it with torchscript. We have to check.

**Comment by fmassa** [comment]
As @vfdev-5 mentioned, we would like to support `pathlib.Path`,  but it wouldn't support torchscript for `pathlib.Path`.

As you mentioned, this could be probably easily done by casting internally to `str` in

https://github.com/pytorch/vision/blob/32e57007d479c3b38e2e4d11ab216c49090a6eb3/torchvision/io/image.py#L61 and 
https://github.com/pytorch/vision/blob/32e57007d479c3b38e2e4d11ab216c49090a6eb3/torchvision/io/image.py#L74
and adding something like
```python
path = str(path)
```
before the function calls.

**Comment by vict0rsch** [comment]
Any news on this front?`

**Comment by LifeGains** [comment]
+1 support for this please

**Comment by NicolasHug** [comment]
I believe this was addressed by https://github.com/pytorch/vision/pull/8314
