### ISSUE TITLE
[DOC] Documentation for sigmoid focal loss

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#2970]
## 📚 Documentation

Sigmoid focal loss was added to torchvision, but I think docs are not generated for it

It was initalized in `init` as well [here](https://github.com/pytorch/vision/blob/v0.8.0/torchvision/ops/__init__.py#L11)

I think it's really minor fix, we might need `..autodoc::sigmoid_focal_loss` and it should be fine.

**Comment by fmassa** [comment]
A PR adding it would be great!
