### ISSUE TITLE
GPU CI fails since Python 3.9 installed

### ISSUE THREAD

**Issue by Licht-T** [pytorch/vision#2972]
## 🐛 Bug
GPU CI is expected running on Python 3.8, but the latest Miniconda installer tries to utilize Python 3.9. 

https://app.circleci.com/pipelines/github/pytorch/vision/4931/workflows/9e04b107-a5c0-4b85-b3e3-43ffa7a040b0/jobs/302026

## To Reproduce

1. Make PR and run CI

## Expected behavior

GPU CI passed

## Environment
None

## Additional context
None

cc @seemethere

**Comment by NicolasHug** [comment]
Thanks for the report @Licht-T , it looks like this issue has been fixed since then: https://app.circleci.com/pipelines/github/pytorch/vision/9150/workflows/5e911ca3-f0ef-409e-8437-d7b8649398c1/jobs/669225 is properly using 3.8.

I'll close the issue, thanks!
