### ISSUE TITLE
Add USPS and MNIST-M dataset

### ISSUE THREAD

**Issue by corenel** [pytorch/vision#298]
Hi, I am interested in adding USPS Dataset for digit classification, which commonly used in domain adaption.

I find [this repo](https://github.com/mingyuliutw/CoGAN_PyTorch/blob/master/src/dataset_usps.py) already implement it, and I modify it slightly [here](https://github.com/corenel/torchzoo/blob/master/torchzoo/datasets/usps.py) referring to the format of MNIST dataset. Could I make a pull request to add it in torchvision ?

BTW, I write a class for MNIST-M dataset [here](https://github.com/corenel/torchzoo/blob/master/torchzoo/datasets/mnistm.py) which consists of MNIST digits blended with random color patches from the BSDS500 dataset. That's also frequently used in domain adaption. But its code is heavily overlapping the original MNIST dataset except the downloading and dataset-making process. I'm wondering whether it's appropriate to add it directly to torchvision, or how to modify it.

Look forward to your suggestions and guidance.

**Comment by alykhantejani** [comment]
Hi @corenel sorry for the late response. Please send a PR with these and we can review in the PR.

Thanks
