### ISSUE TITLE
Travis CI broken - ONNX

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#3007]
## 🐛 Bug

Currently, Travis CI is broken and crashes on  `test/test_onnx.py .Fatal Python error: Aborted`

https://travis-ci.org/github/pytorch/vision/jobs/743793912#L722

cc @seemethere @neginraoof

**Comment by vfdev-5** [comment]
@neginraoof could you please take a look this issue ?

**Comment by fmassa** [comment]
FYI I'm removing TravisCI and temporarily removing ONNX tests in https://github.com/pytorch/vision/pull/3137.

They should be re-enabled in CircleCI

**Comment by spandantiwari** [comment]
@fmassa - just curious, is there a reason why ONNX tests cannot be ported along with other tests to CircleCI as part of your PR. https://github.com/pytorch/vision/pull/3137

**Comment by fmassa** [comment]
@spandantiwari they can be ported to CircleCI, I just didn't do it before because our reference for the ONNX CI up to now (which was TravisCI) has been failing with segfaults, and the failure was probably related to the ORT version being used.

**Comment by fmassa** [comment]
Fixed with https://github.com/pytorch/vision/pull/3144
