### ISSUE TITLE
Clean up and Document the io.image enhancements

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#3034]
PR #3024 introduced a few enhancements on the `io.image` methods used for reading JPEG and PNG images. The code changes were merged but there are a few nice-to-have improvements missing.

More specifically:
- [x] Provide better error messages for [JPEG](https://github.com/pytorch/vision/pull/3024#discussion_r527066925) and [PNG](https://github.com/pytorch/vision/pull/3024#discussion_r527093866) when a specific `ImageReadMode` value is not supported.
- [x] Ensure that `image_read_mode.h` has a new line at the [end of the file](https://github.com/pytorch/vision/pull/3024#discussion_r526710809).
- [x] [Replace](https://github.com/pytorch/vision/pull/3024#discussion_r527065253) the old `#define` with the newer `constexpr` expression at `image_read_mode.h`.
- [x] [Move the documentation](https://github.com/pytorch/vision/pull/3024#discussion_r527095264) of `ImageReadMode` values from the methods to the enum.

**Note:** `constexpr` might cause problems on Windows. If that's the case, try using const instead.

**Comment by Sid2697** [comment]
Hey! I was wondering if I could contribute to this issue, is there anyone already working on it?

**Comment by datumbox** [comment]
Hey @Sid2697, welcome!

Go for it. Looking forward to your PR.
