### ISSUE TITLE
In function `ROIPool_forward(at::Tensor const&, at::Tensor const&, double, long, long)':

### ISSUE THREAD

**Issue by wj1017090777** [pytorch/vision#3049]
https://github.com/pytorch/vision/issues/1849, i try this,but it cannot work. Please help me . Thanks a lot.

In function `ROIPool_forward(at::Tensor const&, at::Tensor const&, double, long, long)':
undefined reference to `ROIPool_forward_cuda(at::Tensor const&, at::Tensor const&, float, int, int)'

**Comment by wj1017090777** [comment]
I installed the C + + version of vison from the source code, but I didn't see the CUDA related things linked. Did I have any mistakes


### [  3%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/models/alexnet.cpp.o
[  7%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/models/densenet.cpp.o
[ 11%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/models/googlenet.cpp.o
[ 15%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/models/inception.cpp.o
[ 19%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/models/mnasnet.cpp.o
[ 23%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/models/mobilenet.cpp.o
[ 26%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/models/resnet.cpp.o
[ 30%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/models/shufflenetv2.cpp.o
[ 34%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/models/squeezenet.cpp.o
[ 38%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/models/vgg.cpp.o
[ 42%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/DeformConv_cpu.cpp.o
[ 46%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/PSROIAlign_cpu.cpp.o
[ 50%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/PSROIPool_cpu.cpp.o
[ 53%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/ROIAlign_cpu.cpp.o
[ 57%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/ROIPool_cpu.cpp.o
[ 61%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/image/image.cpp.o
[ 65%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/image/jpegcommon.cpp.o
[ 69%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/image/read_image_cpu.cpp.o
[ 73%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/image/read_write_file_cpu.cpp.o
[ 76%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/image/readjpeg_cpu.cpp.o
[ 80%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/image/readpng_cpu.cpp.o
[ 84%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/image/writejpeg_cpu.cpp.o
[ 88%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/image/writepng_cpu.cpp.o
[ 92%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/cpu/nms_cpu.cpp.o
[ 96%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/vision.cpp.o
[100%] Linking CXX shared library libtorchvision.so
[100%] Built target torchvision
###

**Comment by wj1017090777** [comment]
i use this to install.

cmake -DCMAKE_PREFIX_PATH=/usr/local/libtorch -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release [-DWITH_CUDA=ON] ..

**Comment by fmassa** [comment]
I suppose you have fixed your issue. Let us know if you have further problems

**Comment by wj1017090777** [comment]
Thank you for your concern.I successfully built C++ torchvison with cuda and successfully run mask_rcnn.
