### ISSUE TITLE
torchvision.utils.save_image() gives wrong shape of image.

### ISSUE THREAD

**Issue by zergzzlun** [pytorch/vision#307]
I used torchvision.utils.save_image() to save a torch float tensor, however I found that the shape of saved image was 4 pixel lager than the shape of the tensor in both height and width.

I load the image with torchvision.transforms.ToTensor() and nothing else, and then directly save it into a png image with torchvision.utils.save_image(). However it's still 4 pixel lager.

**Comment by alykhantejani** [comment]
Hi @zergzzlun,

the `utils.save_imge()` takes a parameter `padding` which is set to `2` by default, which explains the 4 pixels larger in each dimension. You can do one the following:

1. Set `padding=0` to your call to `save_image`
2. Use the `ToPILImage()` transform and call `save` on the returned `PIL.Image` i.e.:
```python
tensor = transforms.ToTensor()(...)
img = transforms.ToPILImage()(tensor)
img.save('output.png')
```

**Comment by zergzzlun** [comment]
Hi @alykhantejani ,
Thanks a lot!

**Comment by abdur4373** [comment]
Hi @alykhantejani 

I am using `save_image(out_norm_img.data, "output_image.jpg", padding=0)` but i am getting this error: 
grid.narrow(1, y*height+1+padding//2,height-padding)\
RuntimeError: start (1) + length (128) exceeds dimension size (128).
Any help please.
