### ISSUE TITLE
Improve the bounding boxes implementation

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#3072]
PR #2785 introduced a new utility to draw bounding boxes on images. The code changes were merged but there are a few nice-to-have improvements missing.

More specifically:
- [x] The unit-test `test_draw_boxes()` [uses PIL instead](https://github.com/pytorch/vision/pull/2785/files/1568b54b69cd274f1a02fc740054c9310dd77dd3#r531621316) of `write_image()` to save the image. We should use TorchVision's method instead. 
- [x] The implementation of the `draw_bounding_boxes()` initializes the text font within the loop which is [suboptimal](https://github.com/pytorch/vision/pull/2785/files/1568b54b69cd274f1a02fc740054c9310dd77dd3#r531623029). We should move it outside of the loop and initialize it once.

**Comment by oke-aditya** [comment]
Looks really minor fixes @datumbox can I take this up?

**Comment by datumbox** [comment]
@oke-aditya that would be great, looking forward to your PR. :)

**Comment by AdityaKhursale** [comment]
Hi @oke-aditya and @datumbox

Sorry I did not read that you guys have concluded assignee on this one already.
I am starting new on open source contributions. This one looked really good for the "good first issue". So, I have created PR for this one. 

You guys can decide which one to MR. @datumbox really thanks for accurate labels. This really helped me to understand the flow. Also, please have a look at the PR. Your review and feedback will help me a lot.

Thank you.

**Comment by oke-aditya** [comment]
No worries @AdityaKhursale this is open source and all are welcome to do pr. You can go ahead.

**Comment by AdityaKhursale** [comment]
> No worries @AdityaKhursale this is open source and all are welcome to do pr. You can go ahead.

Thank you @oke-aditya. Really appreciate.
