### ISSUE TITLE
[Feature request] Depend on Pillow-simd

### ISSUE THREAD

**Issue by bermanmaxim** [pytorch/vision#309]
[Pillow-simd](https://github.com/uploadcare/pillow-simd) seems quite faster than PIL, according to [pillow-perf](https://python-pillow.org/pillow-perf/).  Maybe depending on pillow-simd instead of pillow would be a good option for torchvision?

**Comment by alykhantejani** [comment]
Not sure we want to use a fork of Pillow (which itself is a fork of PIL). However, it's interesting as it appears to be a drop-in replacement so users can install this if they want and it *shouldn't* break anything in torchvision.

**Comment by apaszke** [comment]
Yes. Let's try to import Pillow-simd, and fall back to Pillow if this fails

**Comment by bermanmaxim** [comment]
That would be a good option, unfortunately the two packages have the same name so it's difficult to do a check at runtime (not like cPickle/pickle or similar). I don't now how to best handle this case in distutils dependencies.

**Comment by alykhantejani** [comment]
I think that is preferred, this way we don't have to do anything in the torchvision code and the user can just 
```bash
pip uninstall pillow
pip install pillow-simd
```
and it will just work

**Comment by apaszke** [comment]
Ah right. I thought the package name is different but apparently it's still `PIL`. Let's add a big recommendation in the README

**Comment by alykhantejani** [comment]
👍 I will add this to the README
