### ISSUE TITLE
VOCSegmentation transforms.ToTensor() not working

### ISSUE THREAD

**Issue by sirtris** [pytorch/vision#3093]
Hi, 
I want to use the VOCSegmentation dataset but I always get this error:

```
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'PIL.PngImagePlugin.PngImageFile'>
```
This is a code snippet to recreate the error
```python
transform=transforms.Compose([
                              transforms.Resize((256, 256)),
                              transforms.ToTensor()
                              ])

voc_train = VOCSegmentation(os.getcwd(), year='2012', image_set='train', transform=transform)
train_loader = DataLoader(voc_train, batch_size=64)

train_iter = iter(train_loader)
next(train_iter)
```

When I use the MNIST or CIFAR10 data set the code works as expected.
Is there something special about the `VOCSegmentation` data set?
Thanks

cc @vfdev-5

**Comment by vfdev-5** [comment]
@sirtris yes, `VOCSegmentation` is a dataset for semantic segmentation where the target is an image vs scalar for a classification task. Please, see reference example for segmentation: https://github.com/pytorch/vision/tree/master/references/segmentation and also note that torchvision transforms like `transforms.Resize` do not transform targets. For segmentation we provide only functional ops like `torchvision.transforms.functional.py` and here is an example on how to use them for the segmentation task: https://github.com/pytorch/vision/blob/master/references/segmentation/transforms.py

**Comment by sirtris** [comment]
Thanks using the different trnasorm functions solved it.

**Comment by abhishekstha98** [comment]
@sirtris can you explain how you fixed the issue, i am also stuck in the same problem.

**Comment by sirtris** [comment]
sorry that i didn't clarify that in the last answer. Unfortunately I can't remember what the problem was and how I solved it exactly.  
I would guess that I used one of the transforms  provided by the links above. Probably `PILToTensor()` instead of `transforms.ToTensor()`

**Comment by abhishekstha98** [comment]
@sirtris i am not understanding the solution, i am using transform.compose, for resize() and totensor() where and how should i use the piltotensor() it would be really helpful if you could elaborate

**Comment by sirtris** [comment]
Kind of hard for me to tell I haven't work with this for over a year now.  
I would guess that you can replace the `resize()` and `toTensor()` with the `PILToTensor()` class.
[Here](https://github.com/pytorch/vision/blob/main/references/segmentation/presets.py) is an example of how it can be done.  
Just make sure to import the right classes.

**Comment by li-plaintext** [comment]
@abhishekstha98
I resolved it like this:

```python
# Define the training and testing data
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()             
])

train_data = datasets.VOCSegmentation(root='./data', year='2009', image_set='train', download=False, transform=transform, target_transform=transform)
test_data = datasets.VOCSegmentation(root='./data', year='2009', image_set='val', download=False, transform=transform, target_transform=transform)
```

**Comment by tappyness1** [comment]
The segmentation part of the VOC dataset will be in PIL. 

```
training_data = datasets.VOCSegmentation(
    root=root,
    image_set ="train",
    download=download,
    transform=Compose([Resize((572, 572)),ToTensor()]),
    target_transform = Compose([Resize((388, 388)),PILToTensor()])
)
```
