### ISSUE TITLE
Additional video libraries needed to build from source

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#3101]
## 🐛 Bug

When building the current master from source as development version, the following additional libraries are needed:

- `libavcodec`
- `libavformat`
- `libswscale`

This not documented anywhere.

## To Reproduce

Make sure the libraries above are **not** installed on your system.

```sh
git clone https://github.com/pytorch/vision
cd vision
pip install -e .
```

## Expected behavior

If the libraries are not optional, this should be documented somewhere.

Cc @fmassa @andfoy 

cc @bjuncek

**Comment by fmassa** [comment]
They are meant to be optional, and we have some guards to avoid having to compile them in the library.

**Comment by pmeier** [comment]
Correction: the error only happens if you build the development version, i. e. use the `-e` flag. You can find the log dump [here](https://gist.github.com/pmeier/0f0fb5506607eb57726702c4280d39d4).

**Comment by andfoy** [comment]
@pmeier, could you please post here the apt instructions used to install FFmpeg without any of its dependencies?

**Comment by andfoy** [comment]
I think the problem is related to the development version of FFmpeg not being available, i.e., not installing libavcodec-dev, libavutil-dev, libswresample-dev

**Comment by andfoy** [comment]
Also, it seems that we should be checking for headers on `/usr/lib/*-linux-gnu` to verify that the headers are available on some Debian and Ubuntu vendors

**Comment by pmeier** [comment]
> could you please post here the apt instructions used to install FFmpeg without any of its dependencies?

Unfortunately, I can't. `ffmpeg` was installed by another package. I've looked at a list of `apt` packages that depend on `ffmpeg`. Some are packages I manually installed, but some seem to be native to Ubuntu 18.04.

Thus, I think `ffmpeg` is installed by default on a fresh Ubuntu installation, but I'm not sure.
