### ISSUE TITLE
_rgb2hsv has an unmentioned requirement of non-negative inputs

### ISSUE THREAD

**Issue by behxyz** [pytorch/vision#3110]
## 🐛 Bug

The way RGB to HSV transformation function [_rgb2hsv](https://github.com/pytorch/vision/blob/dab475720f116c42fc80e437b25496dfc94d2a8a/torchvision/transforms/functional_tensor.py#L577) handles NaN values only works if the input RGB image is non-zero. It is a reasonable (yet not documented) assumption since RGB image values are intensities and they are positive by definition. However, since this is part of a machine learning pipeline, RGB images might be normalized to other ranges, e.g. [-1, 1] before being fed to transformation that deal with HUE, e.g. `adjust_hue` or `transforms.ColorJitter`. 

It is not easy to make this function work for all sort of input values (since the global minimum value cannot be derived from a single image) but at least it is essential to explicitly mention this requirement and check for negative values.

## To Reproduce

1. Create an input 3-channel image where at least on of the pixels has zero value in one channel (for instance in R channel) and negative values in other channels (for instance G and B channel)
2. Feed this image to any function that deal with heu. The core function is [_rgb2hsv](https://github.com/pytorch/vision/blob/dab475720f116c42fc80e437b25496dfc94d2a8a/torchvision/transforms/functional_tensor.py#L577) but `adjust_hue` and `transforms.ColorJitter ` (with hue > 0) will call `_rgb2hsv` as well.

## Expected behavior
The output image should not have any `NaN` of `Inf` value.

## Environment

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): torch==1.7.0, torchvision==0.8.1
 - OS (e.g., Linux): Linix
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): `pip`
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration:
 - Any other relevant information:

**Comment by datumbox** [comment]
@behxyz Thanks for reporting.

All these colour adjustment transformations should be done before normalization. Though many of the transformations support it if RGB images are floats scaled from 0-1, there are others what don't. For example I'm currently working on brining AutoAugment in TorchVision and one of its operations, posterize, is applicable only when the image is uint8.

My advice is to move the normalization after those transformations to avoid unexpected behaviours.

**Comment by behxyz** [comment]
@datumbox I agree with you but the problem is that if someone reorders the transformations and first normalizes the image (for instance to [-1, 1]), there is no check and warning. The HSV-based transformation will be applied incorrectly and unless it hits a corner case (as described above), the bug remained hidden.

What I suggest is to add a simple check for any non-zero value in the input image to prevent such easy-to-make mistakes from going silently.

**Comment by datumbox** [comment]
@behxyz Thanks for the input. 

I can see how someone can hit the issue but I'm not sure adding warnings everywhere is the right way to go. If we add this on HSV we probably need to add this everywhere. Perhaps a better approach would be to update the documentation to make it clear that such transformations should happen before standardization. Thoughts?

**Comment by behxyz** [comment]
@datumbox, thanks for the insight.

 I hear what you are saying but it's only about this specific function (_rgb2hsv) that are being used under the hood in many other transformations. For instance consider `ColorJitter` transformation that is combination of four transformation (adjusting brightness, contrast, saturation, and hue). There is nothing wrong to use this transformation after normalization if hue=0 but if at some point someone wanted to bring "hue" in the game then she will not realize that she has done something wrong. The bug will go silently.

**Comment by datumbox** [comment]
> it's only about this specific function (_rgb2hsv)  that are being used under the hood in many other transformations.

Other transformations (under dev `invert`, `solarize` etc) will fail if someone passes negative values. I'm not convinced the solution is to put assertions everywhere. 

> There is nothing wrong to use this transformation after normalization if hue=0

It's important to keep in mind that we need to maintain a consistent API for all transformations. Even if one specific method does not have a problem others do and we need to factor this in.

> The bug will go silently.

The bug is not on the implementation but potentially on the documentation. We could potentially do a better job explaining to the users how to use the different transformations and in what order. If you are interested in sending a PR that improves the documentation on that matter, it would be great.

**Comment by adam-kral** [comment]
I just got this bug (and had to tediously trace it to _rgb2hsv or _hsv2rgb) when using ColorJitter.

I also had to inspect, why my image contained negative values. I did normalization after ColorJitter, so that was not that. However, I used bicubic interpolation, which can produce negative values (values outside its input range).
