### ISSUE TITLE
DatasetFolder incorrectly specifies required folder structure

### ISSUE THREAD

**Issue by rjbruin** [pytorch/vision#3130]
## 📚 Documentation

The documentation for [DatasetFolder](https://pytorch.org/docs/stable/torchvision/datasets.html#datasetfolder) specifies the following required folder organization:

```
root/class_x/xxx.ext
root/class_x/xxy.ext
root/class_x/xxz.ext

root/class_y/123.ext
root/class_y/nsdf3.ext
root/class_y/asd932_.ext
```

However, the [source code for DatasetFolder](https://pytorch.org/docs/stable/_modules/torchvision/datasets/folder.html#DatasetFolder) shows that `make_dataset()` uses `os.walk()` to discover the files in each class' folder. This means that any file within the class folder **or its subfolders** that passes `is_valid_file()` will be included. To me, this behavior was unexpected.

A more complete specification of the format could be:

```
root/class_x/xxx.ext
root/class_x/xxy.ext
root/class_x/[...]/xxz.ext

root/class_y/123.ext
root/class_y/nsdf3.ext
root/class_y/[...]/asd932_.ext
```

cc @pmeier

**Comment by pmeier** [comment]
Hi @rjbruin. Indeed you are correct. I think the easiest way is to adjust the documentation as you proposed. Do you want to submit a PR? If so ping me within that, so I can review.

**Comment by rjbruin** [comment]
Sure, I can make the PR. See #3131.
