### ISSUE TITLE
How can I install torchvision on Apple M1?

### ISSUE THREAD

**Issue by huwei1024** [pytorch/vision#3149]
How can I install torchvision on Apple M1?

**Comment by vfdev-5** [comment]
@huwei1024 could you install / build pytorch on this chip ?

**Comment by huwei1024** [comment]
I solved this problem.  I got torch and torchvision and numpy now. 

PyTorch version: 1.8.0a0+d7e8384
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Mac OSX 11.0.1 (arm64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.27)
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0.dev0+137.g91d9bbebc
[pip3] torch==1.8.0a0
[pip3] torchvision==0.9.0a0+4d3a309
[conda] Could not collect

**Comment by tgyhhh** [comment]
hei，bro，can you install torchvision now?

**Comment by huwei1024** [comment]
@tgyhhh yes

**Comment by tgyhhh** [comment]
请问在哪儿可以下载torchvision==0.9.0a0+4d3a309这个版本的torchvision呀0.0，您是不是下载的.whl文件进行本地安装的0.0

**Comment by huwei1024** [comment]
@tgyhhh  源码编译

**Comment by xh-hnu** [comment]
请问可以分享一下编译好的torchvision的whl文件吗？我自己编译老是出错

**Comment by xh-hnu** [comment]
@huwei1024

**Comment by huwei1024** [comment]
https://drive.google.com/drive/folders/1NYUNtg9wClimlOAdxrL6r5Nnhtur07ON?usp=sharing

@xh-hnu  你试试可不可以用吧

**Comment by xh-hnu** [comment]
@huwei1024 能安装，不过import之后就程序就被kill，不能用。T_T

**Comment by huwei1024** [comment]
@xh-hnu  自己编译吧 比较快的

**Comment by xh-hnu** [comment]
@huwei1024 🙏，已经可以了，测试了一下，pytorch同一个程序，v100跑完44s，m1 40s，性能还是可以的，你测试过吗，结果咋样？

**Comment by huwei1024** [comment]
@xh-hnu 还可以，我是非专业的

**Comment by LeoLiu1220** [comment]
> @xh-hnu 还可以，我是非专业的

怎么编译源码呢请问 刚装了miniforge用whl安装包装了torch 装torchvision怎么装呢
