### ISSUE TITLE
CIFAR Dataset docs do not include an entry for CIFAR100

### ISSUE THREAD

**Issue by jvmancuso** [pytorch/vision#315]
Seems pretty low priority, but there should probably be a note [here](http://pytorch.org/docs/master/torchvision/datasets.html#cifar) saying that there's a Dataset class for CIFAR100 that's identical to the CIFAR10 one.  Would be willing to do a quick PR if there are no objections.

**Comment by alykhantejani** [comment]
Hey @jvmancuso that'd be great - please send a PR :)
