### ISSUE TITLE
evaluate function in engine.py

### ISSUE THREAD

**Issue by mahtabbigverdi** [pytorch/vision#3150]
## To Reproduce

the evaluate function changes my data_loader_test.dataset.targets (boxes)
it changes boxes from (xmin, ymin, xmax, ymax) to (xmin, ymin, W, H)

## Expected behavior
Not changing the dataset

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0):
 - OS (e.g., Linux):
 - How you installed PyTorch / torchvision (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by vfdev-5** [comment]
@mahtabbigverdi thanks for reporting. Could you please give a minimal code snippet to understand the issue you experience and reproduce the issue.

**Comment by mahtabbigverdi** [comment]
I coded just like this link: https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html
 and I wrote my custom dataset exactly like the one in the link with a little difference and I read all targets in init function and my get_item function is this:

def __getitem__(self, idx):
        item = self.X[idx]
        target = self.targets[idx]
        return (item, targets)

But when I call evaluate function it changes the self.targets in dataset of dataloader changes and I think the cause of this problem is this line of code in evaluate function of engine.py

coco = get_coco_api_from_dataset(data_loader.dataset)

I changed this line to coco = get_coco_api_from_dataset(copy.deepcopy(data_loader.dataset)) and the problem solved!

**Comment by vfdev-5** [comment]
@mahtabbigverdi yes the following code: 
https://github.com/pytorch/vision/blob/2f1399e86309fa3c286771176c017fdfaf3ce00e/references/detection/engine.py#L80

adapts input dataset to MSCoco format to evaluate the model with pycocotools etc. Function `get_coco_api_from_dataset` does not alter the input dataset and for example for MSCoco val dataset input, datapoints remain the same:
```python
dataset_test, _ = get_dataset("coco", "val", get_transform(train=False), "/home/data1/MSCoco/")

test_sampler = torch.utils.data.SequentialSampler(dataset_test)

data_loader_test = torch.utils.data.DataLoader(
    dataset_test, batch_size=1,
    sampler=test_sampler, num_workers=4,
    collate_fn=utils.collate_fn)

dp = dataset_test[0]
print("0: ", dp[0].sum(), dp[1]["boxes"].sum())

dp = dataset_test[1]
print("1: ", dp[0].sum(), dp[1]["boxes"].sum())

from coco_utils import get_coco_api_from_dataset

coco = get_coco_api_from_dataset(data_loader_test.dataset)

dp = data_loader_test.dataset[0]
print("0: ", dp[0].sum(), dp[1]["boxes"].sum())

dp = data_loader_test.dataset[1]
print("1: ", dp[0].sum(), dp[1]["boxes"].sum())
```
gives
```
0:  tensor(333002.5938) tensor(26108.0820)
1:  tensor(501831.1562) tensor(1288.9900)
0:  tensor(333002.5938) tensor(26108.0820)
1:  tensor(501831.1562) tensor(1288.9900)
```

Let me close this issue as seems like you already solved your issue. Feel free to reopen if needed.
