### ISSUE TITLE
Restructure and clean up the video/video_reader C++ implementations

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#3155]
## 🐛 Bug

The C++ implementations of `video` and `video_reader` need to be refactored and cleaned up similar to #2998, #3051, #3094, #3097, #3135, #3163:
- [x] Rename C++ files, methods & variables according to [recommended naming conventions](https://google.github.io/styleguide/cppguide.html#General_Naming_Rules).
- [x] Move C++ code away from header files and into cpp files.
- [x] Ensure each cpp file has a separate header file with "public" functions.
- [x] Reduce unnecessary header inclusions. 
- [x] Add all internal functions in anonymous namespaces.
- [x] Sync variable names between the cpp files and their header files.

**Comment by fmassa** [comment]
For the `decoder` folder, I recommend leaving it unchanged and not performing any changes to its code.

My thinking was that we should instead make things a bit more organized in the sense that it now seems to be 3 different projects, but instead `decoder` is a generic abstraction around ffmpeg and the other two leverages `decoder` to expose ffmpeg functionality to Python.

My thinking was to re-structure those three libraries to instead have a more natural flow.

**Comment by datumbox** [comment]
@fmassa Sounds good. I've updated the issue description to reflect that.
