### ISSUE TITLE
Getting Error: NotADirectoryError: [WinError 267] The directory name is invalid. File and folder both are valid

### ISSUE THREAD

**Issue by manojrustagi79** [pytorch/vision#3168]
## 🐛 Bug

I am getting the following error 
Getting Error: NotADirectoryError: [WinError 267] The directory name is invalid. File and folder both are valid
I am using the following code:

# Load all image data
data_dir = os.getcwd()
folder_name = "train"
image_folders = os.path.join(data_dir, folder_name)
transform = transforms.Compose([transforms.Resize((512,512)), transforms.ToTensor()])
images = []
for file in os.listdir(image_folders):
    #print("1-->"+file)
    images.append(ImageFolder(os.path.join(image_folders, file), transform=transform))
datasets = torch.utils.data.ConcatDataset(images)

## To Reproduce
I have placed the files in the D:\MS_Program\DR\Code\train 
File Extension is . JPG 

1. Run the piece of code
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): 1.7.1
 - OS (e.g., Linux): Windows
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): Conda
 - Build command you used (if compiling from source):
 - Python version: Python 3.7.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by fmassa** [comment]
Closing as this looks like you are passing the path to the wrong location to your code.
