### ISSUE TITLE
torchvision/transform.py - to_tensor() - return type is not float

### ISSUE THREAD

**Issue by junghoon-kang** [pytorch/vision#317]
Hello there,

I was using **'I;16'** images to train my network and got the following error.
_Input type (Short) and weight type (Float) should be the same_

And I was wondering if **'I'** and **'I;16'** PIL image modes should also be converted into FloatTensor when we apply ToTensor() transform to the image.

I am sorry if this was intended.
I thought this was weird because, in **to_tensor()** method, every PIL image mode except **'I'**, and **'I;16'** gets converted into FloatTensor.

transform.py
from
`78: return img`
to
`78: return img.float()`

Thank you in advance for your time! :)

**Comment by alykhantejani** [comment]
Hi @junghoon-kang,

support for `I` and `I;16` in the `ToTensor` transform was added in [this PR](https://github.com/pytorch/vision/pull/122), the use case was for things like MRI images, where conversion from an int32 image to a float32 representation causes information to be lost. It's also important to note that calling `ToTensor` on `I` or `I;16` images will also do no rescaling of the range of the images. 

one work around, if you want float images is to explicitly call `.float` on the response, or convert your images after conversion to a pil image. These operations can also be made as a transform inside your `Compose`

**Comment by alykhantejani** [comment]
Closing this as a wont-fix for now. If you wish to discuss it further please comment on the issue or open a new one :)
