### ISSUE TITLE
Replace all torch.jit.annotations with typing annotations

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#3172]
## 🚀 Feature
The use of `torch.jit.annotations` was necessary to be compatible with Python 2, nevertheless now we only support Python 3. Thus we should replace all `torch.jit.annotations` with `typing` annotations.

Examples:
https://github.com/pytorch/vision/blob/83171d6ac95e6bf633bcba3fdd1606f1c8c6bf8b/torchvision/transforms/autoaugment.py#L6

https://github.com/pytorch/vision/blob/83171d6ac95e6bf633bcba3fdd1606f1c8c6bf8b/torchvision/transforms/functional.py#L12

There are more cases across the code-base. We should replace as many as possible.

**Comment by zhiqwang** [comment]
Hi @datumbox , I had submit a PR to fix this issue.
