### ISSUE TITLE
Vectorize the equalize transformation

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#3173]
## 🚀 Feature
The current implementation of the [equalize](https://github.com/pytorch/vision/blob/83171d6ac95e6bf633bcba3fdd1606f1c8c6bf8b/torchvision/transforms/functional_tensor.py#L1299-L1313) transformation is not vectorized. It processes each channel of each image of the batch using a for loop. This is done because the method uses internally the `torch.histc` which currently can't produce a histogram across a dimension.

https://github.com/pytorch/vision/blob/83171d6ac95e6bf633bcba3fdd1606f1c8c6bf8b/torchvision/transforms/functional_tensor.py#L1281-L1282

@fmassa proposed a workaround that trades memory for speed and achieves vectorization. Check https://github.com/pytorch/vision/pull/3123#discussion_r542385911 for the overview/context of the proposal.

To adopt his, a few addtional changes need to be made:
- The rest of the `_scale_channel()` needs to be adapted to vectorize the [remaining operations](https://github.com/pytorch/vision/blob/83171d6ac95e6bf633bcba3fdd1606f1c8c6bf8b/torchvision/transforms/functional_tensor.py#L1284-L1292).
- The `_equalize_single_image()` needs to be removed and the [stacking operation](https://github.com/pytorch/vision/blob/83171d6ac95e6bf633bcba3fdd1606f1c8c6bf8b/torchvision/transforms/functional_tensor.py#L1313) in `equalize()` need to be adapted.

cc @vfdev-5 @fmassa

**Comment by avijit9** [comment]
@datumbox Can I try to solve this one, if no one is working on it?

**Comment by datumbox** [comment]
Go for it @avijit9 !

**Comment by NicolasHug** [comment]
According to #3334, vectorizing the histogram computation seems to lead to a slow-down.
