### ISSUE TITLE
error: ‘constexpr’ call flows off the end of the function

### ISSUE THREAD

**Issue by xiaose26** [pytorch/vision#3175]
### envs
libtorch==1.7.1
vision == 0.8.2

### install
```bash
cmake _DWITH_CUDA=on ..
make
```
### errors
libtorch-cxx11-abi-shared-with-deps-1.7.1/libtorch/include/ATen/core/op_registration/infer_schema.h:120:16: error: ‘constexpr’ call flows off the end of the function
  constexpr auto returns = createReturns<ReturnType>::call();
                ^~~~~~~
make[2]: *** [CMakeFiles/torchvision.dir/build.make:518: CMakeFiles/torchvision.dir/torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/torchvision.dir/all] Error 2

i have test cxx11/cxx14/cxx17, cxx14 and cxx17 have the same error

cc @seemethere

**Comment by datumbox** [comment]
Thanks for reporting. 

Could you provide a few more details on what you are trying to do? 

If your target is to install the library from source, try doing:
`python setup.py install`

The above will compile the C++/CUDA files and install the library on your system. You might need additional libraries for specific parts (JPEG, PNG, etc). If that's the case, have a look at this [guide](https://github.com/pytorch/vision/blob/master/CONTRIBUTING.md).

**Comment by xiaose26** [comment]
i only want use torchvision C++ API,not python,have installed torch and torchvison with pip
set libtorch path in CmakeLists.txt as follow:
```cmake
set(Torch_DIR path/libtorch-cxx11-abi-shared-with-deps-1.7.1/libtorch/share/cmake/Torch)
```
then make as above,details error:
```bash
[ 73%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/ops/cpu/nms_kernel.cpp.o
[ 73%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/ops/cpu/ps_roi_align_kernel.cpp.o
[ 73%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/ops/cpu/ps_roi_pool_kernel.cpp.o
[ 73%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/ops/cpu/roi_align_kernel.cpp.o
[ 73%] Building CXX object CMakeFiles/torchvision.dir/torchvision/csrc/ops/cpu/roi_pool_kernel.cpp.o
[ 73%] Building CUDA object CMakeFiles/torchvision.dir/torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu.o
/libtorch-cxx11-abi-shared-with-deps-1.7.1/libtorch/include/torch/library.h:485:13:   required from ‘torch::Library& torch::Library::impl(Name, Func&&) & [with Name = const char*; Func = at::Tensor (&)(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, long int, long int, long int, long int, long int, long int, long int, long int, bool)]’
/home/xiaose/env/vision/torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu:1192:53:   required from here
/home/xiaose/env/libtorch-cxx11-abi-shared-with-deps-1.7.1/libtorch/include/ATen/core/op_registration/infer_schema.h:48:81: error: no matching function for call to ‘c10::detail::infer_schema::ArgumentDef::ArgumentDef(c10::TypePtr (*)())’
   return (
                                                                                 ^          
......
/libtorch-cxx11-abi-shared-with-deps-1.7.1/libtorch/include/ATen/core/op_registration/infer_schema.h:119:16: error: constexpr call flows off the end of the function
  constexpr auto arguments = createArguments<ParameterTypes>::call();
                ^~~~~~~~~
/libtorch-cxx11-abi-shared-with-deps-1.7.1/libtorch/include/ATen/core/op_registration/infer_schema.h: In instantiation of ‘constexpr std::array<c10::detail::infer_schema::ArgumentDef, sizeof... (Ts)> c10::detail::infer_schema::createArgumentVectorFromTypes(std::index_sequence<ns ...>) [with Ts = {at::Tensor}; long unsigned int ...Is = {0}; std::index_sequence<ns ...> = std::integer_sequence<long unsigned int, 0>]’:
libtorch-cxx11-abi-shared-with-deps-1.7.1/libtorch/include/ATen/core/op_registration/infer_schema.h:80:55:   required from ‘static constexpr std::array<c10::detail::infer_schema::ArgumentDef, sizeof... (Ts)> c10::detail::infer_schema::createReturns<std::tuple<_Tps ...>, void>::call() [with ReturnTypes = {at::Tensor}]’



```

**Comment by vfdev-5** [comment]
@xiaose26 It's a pytorch cuda related bug. I could also repro your issue. It is related to https://github.com/pytorch/pytorch/issues/47493 which was already fixed on the master and probably not yet selected into v1.7.1 stable release.

Possible, workaround is to 
1) build without CUDA support: `-DWITH_CUDA=off`
2) patch manually the fix to the header: libtorch/include/ATen/core/op_registration/infer_schema.h as [here](https://github.com/pytorch/pytorch/pull/47492/files)
3) or manually build libtorch from pytorch source 


@datumbox maybe we have to investigate why our CI does not catch it directly if we build upon stable libtorch.

**Comment by vfdev-5** [comment]
I close the issue as answered, @xiaose26 feel free to reopen if needed.
