### ISSUE TITLE
size in Scale function should be flip to conform the old scale function

### ISSUE THREAD

**Issue by YurongYou** [pytorch/vision#319]
https://github.com/pytorch/vision/blob/3990952f76df3d553dfb54a9600eafc44899e2bf/torchvision/transforms/transforms.py#L156

see https://github.com/pytorch/vision/blob/c5e52baa632878e2989d62d5888179f900b01c8b/torchvision/transforms.py#L165

**Comment by alykhantejani** [comment]
Hi @YurongYou the params to scale were flipped to be `(h,w)` as a breaking change, to be consistent with other transforms and the torch tensor format. See [this PR](https://github.com/pytorch/vision/pull/256) for more discussion on this.

**Comment by YurongYou** [comment]
Thanks!
