### ISSUE TITLE
model compatibility 

### ISSUE THREAD

**Issue by abrahamyan-lusine** [pytorch/vision#32]
Is there any way to transform pytorch model to caffe, or tensorflow?

**Comment by soumith** [comment]
We plan to add this over time, but at the moment there is no converter.
However, if you look at model.state_dict(), it is a simply python dict with the weights, and you can use this dict to manually copy over the weights to other frameworks.

**Comment by ypxie** [comment]
@soumith   It seems that model saved with `model.state_dict()` is not portable between different machines?  https://discuss.pytorch.org/t/erros-in-loadding-model-pth/2632/3
