### ISSUE TITLE
transform.ToPILImage does not work properly with RGBA

### ISSUE THREAD

**Issue by ahmedmagdiosman** [pytorch/vision#320]
The transform `ToPILImage` seems to force RGB when converting from an ndarray. Here's an example:

````
import numpy as np
import torchvision
from torchvision import  transforms
from skimage import io

toPil = transforms.ToPILImage()

image = io.imread('rand.png')

print (image.shape)
print (np.asarray(toPil(image)).shape)
````
`print (image.shape)
` returns (320, 480, 4),
`print (np.asarray(toPil(image)).shape)
` returns (320, 480, 3), 

I made sure the image works with PIL:
````
from PIL import Image
import torchvision
from torchvision import  transforms

toPil = transforms.ToPILImage()
toTens= transforms.ToTensor()

image = Image.open('rand.png')

print (image)
print(toPil(toTens(image)))
````
`print (image)` returns <pre><code> <PIL.PngImagePlugin.PngImageFile image mode=**RGBA** size=480x320 at 0x7F1E36F43D30></pre></code> 

`print(toPil(toTens(image)))` returns <pre><code> <PIL.Image.Image image mode=**RGB** size=480x320 at 0x7F1E567CD940> </pre></code> 

Visualizing the image makes it very clear that there's something wrong.
<img src="https://i.imgur.com/xDzPNu3.png" width="256">
<img src="https://i.imgur.com/OvMNvqg.png" width="300">

I don't think this is intended behavior. Can anyone confirm this?

**Comment by alykhantejani** [comment]
Hi @ahmedmagdiosman 

RGBA, and support for other PIL Image  modes was added recently to master. If you can build from source, this will fix your problem. We should release a new official version soon though

**Comment by ahmedmagdiosman** [comment]
Thanks! When do you think this will get pushed to the conda packages?

**Comment by alykhantejani** [comment]
@ahmedmagdiosman I think there are plans for a new release this week - so stay tuned!
