### ISSUE TITLE
TORCH_LIBRARY_FRAGMENT build error

### ISSUE THREAD

**Issue by helloyan** [pytorch/vision#3210]
## To Reproduce

1.sudo python3 setup.py install
2. vision/torchvision/csrc/vision.cpp:31:23: error: expected constructor, destructor, or type conversion before ‘(’ token

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch / torchvision Version (1.7.0 / 0.8.1):
 - OS (e.g., Linux): arm ubuntu 18.10
 - How you installed PyTorch / torchvision (`conda`, `pip`, source):  pytorch whl/vision source
 - Build command you used (if compiling from source):
 - Python version: 3.6.8
 - CUDA/cuDNN version:10.2
 - GPU models and configuration:
 - Any other relevant information:

**Comment by qyb** [comment]
checkout a specific version first
git checkout v0.8.2

**Comment by kureta** [comment]
switching to v0.8.2 did not help. here is my build environment:
```
PyTorch version: 1.8.0a0+7245d2c
Is debug build: True
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: 11.0.0
CMake version: version 3.19.2

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 455.45.01
cuDNN version: Probably one of the following:
/usr/lib/libcudnn.so.8.0.5
/usr/lib/libcudnn_adv_infer.so.8.0.5
/usr/lib/libcudnn_adv_train.so.8.0.5
/usr/lib/libcudnn_cnn_infer.so.8.0.5
/usr/lib/libcudnn_cnn_train.so.8.0.5
/usr/lib/libcudnn_ops_infer.so.8.0.5
/usr/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.8.0a0
[conda] Could not collect
```

**Comment by helloyan** [comment]
> checkout a specific version first
> git checkout v0.8.2

I use pytorch 1.7.0, so it should be torchvision 0.8.1,i back to 0.8.0, it compiled successful

**Comment by helloyan** [comment]
> switching to v0.8.2 did not help. here is my build environment:
> 
> ```
> PyTorch version: 1.8.0a0+7245d2c
> Is debug build: True
> CUDA used to build PyTorch: 11.2
> ROCM used to build PyTorch: N/A
> 
> OS: Arch Linux (x86_64)
> GCC version: (GCC) 10.2.0
> Clang version: 11.0.0
> CMake version: version 3.19.2
> 
> Python version: 3.9 (64-bit runtime)
> Is CUDA available: True
> CUDA runtime version: Could not collect
> GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
> Nvidia driver version: 455.45.01
> cuDNN version: Probably one of the following:
> /usr/lib/libcudnn.so.8.0.5
> /usr/lib/libcudnn_adv_infer.so.8.0.5
> /usr/lib/libcudnn_adv_train.so.8.0.5
> /usr/lib/libcudnn_cnn_infer.so.8.0.5
> /usr/lib/libcudnn_cnn_train.so.8.0.5
> /usr/lib/libcudnn_ops_infer.so.8.0.5
> /usr/lib/libcudnn_ops_train.so.8.0.5
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> 
> Versions of relevant libraries:
> [pip3] numpy==1.19.4
> [pip3] torch==1.8.0a0
> [conda] Could not collect
> ```
> 
> My CUDA version is 11.2.0. I don't know why the script couldn't get that.

maybe you could try this  https://github.com/yqlbu/jetson-packages-family "Set CUDA Path"

**Comment by helloyan** [comment]
doesn't resolve it,  any update?

**Comment by fmassa** [comment]
Hi,

If you want to compile torchvision from master, you need to have a recent enough nightly version of PyTorch installed in your system.

Let us know if with the latest PyTorch nightly you are not able to compile torchvision from source.

**Comment by helloyan** [comment]
it‘s my fault, i check the error version
