### ISSUE TITLE
Which paper is torchvision.ops.deform_conv2d from?

### ISSUE THREAD

**Issue by songyuc** [pytorch/vision#3233]
## 📚 Documentation

I want to know which paper [torchvision.ops.deform_conv2d](https://pytorch.org/docs/stable/torchvision/ops.html#torchvision.ops.deform_conv2d) is from, is it DCNv1 or DCNv2?

**Comment by datumbox** [comment]
@songyuc On latest master both! Check out this one:
https://github.com/pytorch/vision/blob/3d60f498e71ba63b428edb184c9ac38fa3737fa6/torchvision/ops/deform_conv.py#L23-L28

The v2 version was added recently.

**Comment by songyuc** [comment]
@datumbox , is there a implementation of DCNv2 using this op?

**Comment by datumbox** [comment]
Unfortunately we don't have an implementation of the DCNv2 network at TorchVision at the moment.

BTW feel free to reopen the ticket if you feel I closed it prematurely. :)

**Comment by songyuc** [comment]
@datumbox , do you have a plan to add it in torchvision?

**Comment by datumbox** [comment]
We don't have immediate plans but it's worth adding it to this ticket #2707 where we keep track requests. Or you can raise a separate issue to propose its addition. :)
