### ISSUE TITLE
Python 3.9 support on our CI

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#3241]
## 🐛 Bug

Currently no tests run on Python 3.9 on our CI. As we get closer and closer to the next release, we should turn them on and fix any possible issues.

cc @seemethere

**Comment by seemethere** [comment]
For reference this is the WIP PR for that, https://github.com/pytorch/vision/pull/3041

I haven't really had the bandwidth to actually do this all the way though, perhaps this should be handed off to someone with more bandwidth?

PR for `v0.8.X`: https://github.com/pytorch/vision/pull/3063

**Comment by datumbox** [comment]
@seemethere Thanks for the quick reply. Can we just cherrypick the commits in PR #3063 on master? Is there any known problem?

**Comment by datumbox** [comment]
Fixed by #3341
