### ISSUE TITLE
Exception using optimize_for_mobile on retinanet

### ISSUE THREAD

**Issue by ValerianGonnot** [pytorch/vision#3247]
## 🐛 Bug

When using torch.utils.mobile_optimizer.optimize_for_mobile on retinanet_resnet50_fpn, I get the following exception :
```
line 43, in optimize_for_mobile
 > optimized_cpp_module = torch._C._jit_pass_optimize_for_mobile(script_module._c, optimization_blocklist, preserved_methods)

RuntimeError: node->kind() == prim::GetAttr INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1603729096996/work/torch/csrc/jit/passes/freeze_module.cpp":22, please report a bug to PyTorch. Expected prim::GetAttr nodes
```
## To Reproduce

Code to reproduce the behavior:

```
import torch
import torchvision
from torch.utils.mobile_optimizer import optimize_for_mobile

model = torchvision.models.detection.retinanet_resnet50_fpn(pretrained=True)
model.eval()

traced_script_module = torch.jit.script(model)
traced_script_module_optimized = optimize_for_mobile(traced_script_module)
```

## Expected behavior

As there is an issue opened on the pytorch repo since the November 3rd but it hasn't got any attention and changing the model could be easier than fixing directly Pytorch, maybe it is worth a try.

## Environment

- PyTorch Version (e.g., 1.0): 1.7
- OS (e.g., Linux): Ubuntu 20.04
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source):
- Python version: 3.8.6
- CUDA/cuDNN version: CUDA 11,
- GPU models and configuration: GTX 1070

**Comment by eellison** [comment]
I think this is fixed on master

**Comment by ValerianGonnot** [comment]
Yes, indeed
