### ISSUE TITLE
get v0.8.1 branch compile out torchvision==0.9.0a0+7b9d30e

### ISSUE THREAD

**Issue by helloyan** [pytorch/vision#3267]
I clone the v0.8.1 branch and compiled it with pytorch 1.7.0,  but at last the compiled version is 0.9.0, does anything wrong?

**Comment by fmassa** [comment]
Hi,

If you checked out the commit corresponding to the 0.8.1 release (which should correspond to https://github.com/pytorch/vision/commit/45f960c5b18679ea42d7e5b4212f17483cdfd8af), you should have a version printed out corresponding to 0.8.0a+45f960c5 , see https://github.com/pytorch/vision/blob/45f960c5b18679ea42d7e5b4212f17483cdfd8af/setup.py#L32-L47

You are picking commit https://github.com/pytorch/vision/tree/7b9d30eb7c4d92490d9ac038a140398e0a690db6 , which was published after the 0.8.1 release and was on a nightly, where we had bumped the version to 0.9.0 already.

I believe this answers your question so I'm closing this issue, but let us know if you have further questions
