### ISSUE TITLE
Can we use DeeplabV3 in Salient Object Detection ?

### ISSUE THREAD

**Issue by duynguyen51** [pytorch/vision#3281]
Recently, I start doing more in Deep Learning in Semantic Segmentation. I can't figure DeepLabV3 is possible to apply in Salient Object Detection ?

**Comment by voldemortX** [comment]
@duynguyen51 I believe you can use DeepLabV3 or any segmentation models for salient object detection if you treat the SOD task as binary segmentation.

**Comment by duynguyen51** [comment]
Thanks, I'll find out in the root concept.
