### ISSUE TITLE
How to install torchvision to use video_reader backend?

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/vision#3283]
I simply installed torchvision from conda (as advertised on pytorch.org). But `torchvision.set_video_backend('video_reader')` prints `video_reader video backend is not available. Please compile torchvision from source and try again`. This should be mentioned in https://pytorch.org/docs/stable/torchvision/index.html#torchvision.set_video_backend and in torchvision README (including if the `video_reader` is temporarily not supported)

cc @bjuncek

**Comment by bjuncek** [comment]
Hi Vadim - thanks for raising this - I'll add this to the docs.

As for how to do it, you need to have FFMPEG installed and build torchvision from source. 
If you're using the latest master, I believe you need to add `NO_FFMPEG=False` flag as well (pls check[ this issue](https://github.com/pytorch/vision/issues/3188) for clarification).

**Comment by jamt9000** [comment]
This should work as a couple-liner to install 0.8.1 with video (if the right compiler versions are installed)

```.sh
conda install 'conda-forge::ffmpeg<4.3' 'pytorch::pytorch==1.7'
pip install 'git+https://github.com/pytorch/vision.git@v0.8.1'
```

**Comment by vadimkantorov** [comment]
+ I think this instruction should not just be in the docs, but some link to this instruction should be in the exception message about video_reader not available

**Comment by bjuncek** [comment]
>> I think this instruction should not just be in the docs, but some link to this instruction should be in the exception message about video_reader not available

Adding a specific instruction that relies on versions is a slippery slope as version change, and we are hoping to at some point even include correct ffmpeg packaged in neatly at some point. I think that for now, the comment that FFMPEG needs to be installed and that it needs to be built from source should be enough?

**Comment by vadimkantorov** [comment]
The important is to have a short URL to _some_ instruction. If it says it should be built from sources, it should be clear if only dynamic libraries are needed or includes as well. If they must be available from pkg-config; is it enough for libraries to be in LD_LIBRARY_PATH, or presence in LIBRARY_PATH is needed as well.

It could well be a conda install command, as long as ffmpeg in conda is kept relatively up to date.

**Comment by bjuncek** [comment]
The instructions for installing from source are in the main README and
I will add the FFMPEG binary requirement to the docs (it requires ffmpeg <4.3 which is not indicated well I think)."

> It could well be a conda install command, as long as ffmpeg in conda is kept relatively up to date.
That could work if we get the good ffmpeg recipe - I think we were planning to do something like this as packaging the binaries is a pain but I'm a bit lost on the details. I'm not sure who is maintaining the one you mentioned above; @andfoy do you have any idea?

**Comment by vadimkantorov** [comment]
> The instructions for installing from source are in the main README

"Make sure that it is available on the standard library locations," would be nice if it were a bit more verbose. Is pkg-config registration mandatory? Is only LD_LIBRARY_PATH sufficient? Is CPATH presence mandatory? etc

**Comment by vadimkantorov** [comment]
@fmassa this note is not very helpful and does not fix `But torchvision.set_video_backend('video_reader') prints video_reader video backend is not available. Please compile torchvision from source and try again. `

**Comment by vadimkantorov** [comment]
There are two issues IMO:
1. it should be clear what exactly are the the requirements for ffmpeg to be discovered by torchvision build scripts
2. this requirements / instructions should be directly pointed by the docs and by the exception message included
