### ISSUE TITLE
Using torchvision roi_align in libtorch c++ jit modules

### ISSUE THREAD

**Issue by natangold85** [pytorch/vision#3294]
## 🐛 Bug

Hi, I’m trying to use libtorch 1.7.1 to load a jit model that is created with pytorch 1.5.1 and torchvision 0.6.1.
This model is using torchvision::roi_align operator.
When running the model I get this error:

**Could not find any similar ops to torchvision::roi_align. This op may not exist or may not be currently supported in TorchScript.**

loading the model in pytorch is working fine.
Any idea why its not loading?
I need to install another package to my c++ env to be able to load this model?

## Expected behavior

load and forward the model successfully in libtorch

## Environment

libtorch version: 1.7.1

Collecting environment information...
PyTorch version: 1.5.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.2 LTS (x86_64)
GCC version: (Ubuntu 6.4.0-17ubuntu1) 6.4.0 20180424
Clang version: Could not collect
CMake version: version 3.18.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: Quadro P5000
Nvidia driver version: 418.87.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.17.2
[pip3] numpy-indexed==0.3.5
[pip3] numpy-quaternion==2019.10.3.10.26.21
[pip3] numpydoc==0.9.1
[pip3] pytorch3d==0.2.0
[pip3] torch==1.5.1
[pip3] torchvision==0.6.1
[conda] Could not collect

Thanks

**Comment by datumbox** [comment]
@natangold85 Could you install the torch nightly and retry using the latest master of TorchVision?

**Comment by natangold85** [comment]
Install libtorch nightly or pytorch nightly?

**Comment by fmassa** [comment]
libtorch nightly for building the C++, pytorch nightly together with torchvision nightly.

Also, please have a look at https://github.com/pytorch/vision/blob/master/test/tracing/frcnn/test_frcnn_tracing.cpp which shows how to get a torchscripted faster rcnn (with custom C++ ops like roi_align) to run in C++

**Comment by mthrok** [comment]
Also IIRC PyTorch does not guarantee the binary compatibility across PyTorch versions.
What happens if you re-create the JIT object with PyTorch 1.7.1 and TorchVision 0.8.1 and load it with libtorch 1.71 ?

**Comment by natangold85** [comment]
torchvision 0.8.1 is not supporting torch 1.7.1 as far as i understand. 
I installed updated torch which is torch 1.7.1 and torchvision 0.8.2 and i'm seeing the same crash.
will take look at link attached above and report the results.

**Comment by natangold85** [comment]
Hi @datumbox  
in your example you are including torchvision/vision.h and torchvision/ops/nms.h.
I don't have those files in my libtorch installation.
this is the only difference between us.
Is torchvision is not a part of the standard libtorch installation?
Do I need to install it separately if I want to use torchvision symbols in jit models?

**Comment by datumbox** [comment]
These files are part of TorchVision and it has to be installed separately. As Francisco explained you need to install libtorch, pytorch and torchvision nightly.

**Comment by natangold85** [comment]
Ok.
From his message i understood he meant python torchvision. 
That's what I asked in the initial post.
Will install torchvision and report
Thanks

**Comment by natangold85** [comment]
Hi @datumbox 
I installed torchvision and it didn't solved my problem. 
I narrowed my model to standalone roi_align model.
This is my python code to create the model:

from torchvision.ops import roi_align
import torch
from typing import Dict
class RoIAlign(torch.nn.Module):
  def __init__(self, aligned_height, aligned_width, spatial_scale):
    super(RoIAlign, self).__init__()
    
    self.aligned_width = int(aligned_width)
    self.aligned_height = int(aligned_height)
    self.spatial_scale = float(spatial_scale)
  
  def forward(self, features: torch.Tensor, rois: torch.Tensor) -> torch.Tensor:
    return roi_align(features, rois, (self.aligned_width, self.aligned_height), self.spatial_scale, 0)

class RoIAlignStandAlone(torch.nn.Module):
  def __init__(self, aligned_height, aligned_width, spatial_scale):
    super().__init__()
    self.aligned_width = int(aligned_width)
    self.aligned_height = int(aligned_height)
    self.spatial_scale = float(spatial_scale)
    
  def forward(self, inputs: Dict[str, torch.Tensor]) -> torch.Tensor:
    return torch.ops.torchvision.roi_align(inputs["feature"],  inputs["rois"], self.spatial_scale,
    self.aligned_width, self.aligned_height,
    0, False)

module = RoIAlignStandAlone(7, 7, 0.125)
sc = torch.jit.script(module)
torch.jit.save(sc, "/tmp/roi_align.pt")


This my cpp code to load the model:

#include <torch/script.h>
#include <torch/torch.h>
#include <torchvision/vision.h>
#include <torchvision/nms.h>
#include <torchvision/ROIAlign.h>


int main(int argc, char **argv)
{
  torch::jit::script::Module module;
  try {
    std::cout << "Loading model\n";
    // Deserialize the ScriptModule from a file using torch::jit::load().
    module = torch::jit::load("/tmp/roi_align.pt");
    std::cout << "Model loaded\n";
  } catch (const torch::Error& e) {
    std::cout << "error loading the model\n";
    return -1;
  } catch (const std::exception& e) {
    std::cout << "Other error: " << e.what() << "\n";
    return -1;
  }
  return 0;
}

you understand what i'm doing wrong here?
Thanks

**Comment by natangold85** [comment]
sorry for the indentation problem in the attached code

**Comment by natangold85** [comment]
Hi @datumbox , i'm attaching .py file and .cpp file.
the .py file is producing jit model and saving it to /tmp the .cpp is trying to load it.
can you please check it on your env? it will help a lot for our team to understand what is wrong in the torchvision operators in our env.

Thanks.


[test_torch_cpp.txt](https://github.com/pytorch/vision/files/5899320/test_torch_cpp.txt)
[roi_align_py.txt](https://github.com/pytorch/vision/files/5899321/roi_align_py.txt)

**Comment by datumbox** [comment]
@natangold85 I would suggest to have a look on the example provided at TorchVision repo:
https://github.com/pytorch/vision/tree/master/test/tracing/frcnn

Start using this setup and then try to adapt it to be closer to your script. This is going to help you debug whether the issue you face is related to your development env or something else.

**Comment by natangold85** [comment]
Thanks, I found the problem.
Apparently you need to dynamically load the torchvision symbols you are using in the jit model that you are loading.
Adding this line solved the linking issue to torchvision symbols:

`static auto registry =
            torch::RegisterOperators()
                    .op("torchvision::roi_align(Tensor input, Tensor rois, float spatial_scale, int pooled_height, int pooled_width, int sampling_ratio, bool aligned) -> Tensor", &roi_align);
`

BTW @datumbox these lines are missing from your example, so i'm not sure when i need to load the symbols and when not.
but for my model it worked only when i loaded them.

**Comment by JANGSOONMYUN** [comment]
> Thanks, I found the problem. Apparently you need to dynamically load the torchvision symbols you are using in the jit model that you are loading. Adding this line solved the linking issue to torchvision symbols:
> 
> `static auto registry = torch::RegisterOperators() .op("torchvision::roi_align(Tensor input, Tensor rois, float spatial_scale, int pooled_height, int pooled_width, int sampling_ratio, bool aligned) -> Tensor", &roi_align); `
> 
> BTW @datumbox these lines are missing from your example, so i'm not sure when i need to load the symbols and when not. but for my model it worked only when i loaded them.

Hi, could I look at your full code in c++?

My case does not use only roi_align, but also other 2 more different models (detection and recognition). 
Between 2 models, I used roi_align but I met the problem similar to your case. 

But I don't understand how to use RegisterOperators in your solution. So if you don't mind, please let me know how to use it or just let me see the code.

**Comment by natangoldgm** [comment]
@JANGSOONMYUN I'm sorry but I don't quite remember my solution.
All I remember is that I had to take slightly advance version from the libtorch 1.7.1 and torchvision 0.8.0
I needed to compile them myself because I needed to be compliant to pytorch 1.7.1.
In my source code after compiling the libraries I needed to add these includes and everything worked:
#include <torchvision/ops/nms.h>
#include <torchvision/vision.h>

I don't remember which tag I used and I don't know if in current pytorch and torchvision it will work.
