### ISSUE TITLE
Suppress output when loading cifar dataset

### ISSUE THREAD

**Issue by xuanqing94** [pytorch/vision#330]
Hi, could we suppress output("Files already downloaded and verified") because users often collect data from stdout and this message is a bit annoying when parsing log files.

**Comment by alykhantejani** [comment]
Hi @xuanqing94,

One way to avoid getting this message is to pass `download=False` to the constructor, then it won't even try to download (and subsequently tell you it already exists). 

Ideally, we should move all of these messages into a logger at a verbose level (using pythons logging library). Then the user can decide what handlers they want to attach and what log level they care about. 

Let me know if this solves your problem.

**Comment by xuanqing94** [comment]
Thanks @alykhantejani I know set download=False will work, just thinking about the verbose level as you explained.

**Comment by nitin-rathi** [comment]
You can comment the line that prints the message in file "/miniconda3/envs/pytorch/lib/python3.7/site-packages/torchvision/datasets/cifar.py".  To find the line you can search the string "Files already downloaded and verified" in the file.

**Comment by carlosgmartin** [comment]
I think there should be a flag for this.

**Comment by fmassa** [comment]
@carlosgmartin that's a good point, and we will keep it in mind for the future.

cc @pmeier @datumbox @NicolasHug @prabhat00155 We should think if we want to use `logging` for this in the future or not

**Comment by ash1rawtf** [comment]
@xuanqing94 
not logging, but it looks like the perfect solution:
```python
ROOT_DIR = "data"
DOWNLOAD = not (Path(ROOT_DIR) / datasets.CIFAR10.filename).is_file()
BATCH_SIZE = 32

train_dataset_default = datasets.CIFAR10(
    root=ROOT_DIR,
    train=True,
    transform=v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)]),
    target_transform=None,
    download=DOWNLOAD,
)
```
