### ISSUE TITLE
a question about  segmentation model loading

### ISSUE THREAD

**Issue by njzyxiong** [pytorch/vision#3322]
## ❓ Questions and Help
Why they are different？
### Please note that this issue tracker is not a help form and this issue will be closed.
![image](https://user-images.githubusercontent.com/32593161/106227085-8d5d2000-6223-11eb-9c66-fcb037faac92.png)

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

cc @vfdev-5

**Comment by njzyxiong** [comment]
I want to load fcn_resnet101, why it downloads resnet101?

**Comment by vfdev-5** [comment]
@njzyxiong by default, segmentation model setup ImageNet pretrained backbone, resnet101 in your case. If you would like to disable this, please set `pretrained_backbone=False`, but I agree that if `pretrained=True` we could automatically disable it.
