### ISSUE TITLE
deeplabv3 downloads resnet weights even with pretrained=False

### ISSUE THREAD

**Issue by makarr** [pytorch/vision#3357]
## 🐛 Bug

When instantiating a new deeplab model, the pretrained resnet weights are downloaded to cache.

## To Reproduce

`deeplab = models.segmentation.deeplabv3_resnet50(pretrained=False)`

Results in the following printed to stdout:

> Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /root/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth

## Expected behavior

The resnet weights should be initialized randomly instead of downloaded, with nothing printed to stdout.

## Environment

PyTorch version: 1.7.0+cu101
Is debug build: True
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.7.0+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.8.1+cu101
[conda] Could not collect

## Additional context

Looking at the source, it seems like this is intended as a feature.  Perhaps the `pretrained_backbone` flag in `_segm_model` could be exposed to the user.  For some domains the pretrained resnet weights are not helpful and are even a hindrance.

**Comment by oke-aditya** [comment]
Hi ! I guess this is fixed with #3322 on master :smile:  

On master, instantiating with `pretrained=True` will not download backbone weights, instead it will only download model trained over COCO dataset.

**Comment by makarr** [comment]
Hi @oke-aditya thanks for the head's up.  I guess I should have searched whether the issue had already been submitted.  I'll close.

**Comment by gonzrubio** [comment]
> Hi ! I guess this is fixed with issue #3322 by #3325 on master 😄
> 
> On master, instantiating with `pretrained=True` will not download backbone weights, instead it will only download model trained over COCO dataset.

Is it possible to initialize the model without trained backbone or trained model weights? I'm looking to train it from scratch.
