### ISSUE TITLE
discrepancies between TorchVisionConfigVersion.cmake to git branch

### ISSUE THREAD

**Issue by natangold85** [pytorch/vision#3358]
Hi
I'm compiling torchvision from source for cpp. i want to adjust torchvision to existing libtorch compilation.
My branch is **v0.8.2** but when installing the build directory the TorchVisionConfigVersion.cmake says the package version is 0.7.0.

i see this in the cmake file:

set(PACKAGE_VERSION "0.7.0")`

Any idea why?

**Comment by bmanga** [comment]
That's my fault for not keeping it up to date, sorry. I will fix it ASAP.
