### ISSUE TITLE
[Feature Request] Support functions as inputs to transformers to allow for better control of randomization

### ISSUE THREAD

**Issue by michalwols** [pytorch/vision#339]
So instead of having `RandomRotation` replace it with `Rotation` that could take `partial(np.random.normal, 0, 20)` or `partial(np.random.uniform, -20, 20)` as the degrees argument.

**Comment by alykhantejani** [comment]
Hi @michalwols,

you can now access the functions used for the transforms via the functional interface (in master). For example, see the `rotate` function [here](https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional.py#L529)

So if you wanted better control of the transforms + randomization you could create your own composite transform as a function which calls other functions i.e.

```python
def my_transform(img):
     img = F.rotate(np.random.normal(0, 20))
     img = F.center_crop((224, 224))
     return img
```

Is this the kind of control you were looking for?
