### ISSUE TITLE
Bug Report: No module named 'torchvision.models.mobilenetv2'

### ISSUE THREAD

**Issue by DemonsHunter** [pytorch/vision#3397]
## ❓ Questions and Help

Hi there, I encounter a bug when running this following line 

>>> import torch
>>> res = torch.hub.load('pytorch/vision', 'resnet50')

the error is:

-------------------------------------begin of error info---------------------------------

Using cache found in /root/.cache/torch/hub/pytorch_vision_master
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-21-55b890d7b167> in <module>()
      1 import torch
----> 2 res = torch.hub.load('pytorch/vision', 'resnet50')
      3 print(res)

5 frames
/root/.cache/torch/hub/pytorch_vision_master/hubconf.py in <module>()
     12 from torchvision.models.googlenet import googlenet
     13 from torchvision.models.shufflenetv2 import shufflenet_v2_x0_5, shufflenet_v2_x1_0
---> 14 from torchvision.models.mobilenetv2 import mobilenet_v2
     15 from torchvision.models.mobilenetv3 import mobilenet_v3_large, mobilenet_v3_small
     16 from torchvision.models.mnasnet import mnasnet0_5, mnasnet0_75, mnasnet1_0, \

ModuleNotFoundError: No module named 'torchvision.models.mobilenetv2'

-----------------end of error info------------------------------------------------
BTW, my environment is torch-1.7.1, torchvision-0.8.2, I also try to 
pip install torchvision.models.mobilenetv2
it turns out useless.

Grateful to hear any suggestions!

**Comment by datumbox** [comment]
TorchVision v0.8.2 [does not have a mobilenetv2 module](https://github.com/pytorch/vision/tree/v0.8.2/torchvision/models). This was introduced on the latest master when MobileNetV3 was added. Try installing the latest master.

**Comment by DemonsHunter** [comment]
Thank you for your suggestion, and then I try to update torchvision to the latest version 0.8.2.

>>> !pip install torchvision==0.8.2
Requirement already satisfied: torchvision==0.8.2 in /usr/local/lib/python3.6/dist-packages (0.8.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from torchvision==0.8.2) (1.19.5)
Requirement already satisfied: torch==1.7.1 in /usr/local/lib/python3.6/dist-packages (from torchvision==0.8.2) (1.7.1)
Requirement already satisfied: pillow>=4.1.1 in /usr/local/lib/python3.6/dist-packages (from torchvision==0.8.2) (7.0.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.6/dist-packages (from torch==1.7.1->torchvision==0.8.2) (3.7.4.3)
Requirement already satisfied: dataclasses; python_version < "3.7" in /usr/local/lib/python3.6/dist-packages (from torch==1.7.1->torchvision==0.8.2) (0.8)

after rebooting the process, I only to find it does not work!

>>> import torchvision
>>> torchvision.__version__
0.8.1+cu101

**Comment by datumbox** [comment]
Could you clarify what does not work? As I explained the change you discuss is NOT available on 0.8.2 but only on the nightly. If you want to access it now you should either install the latest master branch from github or the lats nightly.

**Comment by DemonsHunter** [comment]
Sorry for the unclear. I want to use this command:

> !pip install --upgrade torchvision

to update to the latest version, but it does not work, the version remains the same.

Or how can I install the  latest master branch from github, thanks a lot

**Comment by datumbox** [comment]
Please check out the [Contributing page](https://github.com/pytorch/vision/blob/master/CONTRIBUTING.md#development-installation) for instructions on how to install the latest branch.

I'll close the ticket since what you are experiencing is not a bug. You are just using the wrong version where the specific feature does not exist. If you have more concerns please let me know.
