### ISSUE TITLE
box_iou function can return nan value

### ISSUE THREAD

**Issue by developer0hye** [pytorch/vision#3404]
## 🐛 Bug

box_iou funcition in ops can return nan value. It needs "assert" like generalized_box_iou function.

## To Reproduce

```
import torch
import torchvision.ops as ops

box1 = torch.tensor([10, 40, 20, 20]).reshape(-1, 4)
box2 = torch.tensor([60, 50, 40, 40]).reshape(-1, 4)

iou = ops.box_iou(box1, box2) # return nan value
```

## Expected behavior

Return 0. or cause assert

## Environment

I tested on Google Colab.

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0):
 - OS (e.g., Linux):
 - How you installed PyTorch / torchvision (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by fmassa** [comment]
Hi,

This is related to https://github.com/pytorch/vision/issues/2582

Adding an assert is probably the best option here, although as @ppwwyyxx pointed out in https://github.com/pytorch/vision/issues/2582#issuecomment-680158318 an assert will incur a synchronization point and thus make training / evaluation slower.

**Comment by developer0hye** [comment]
@fmassa 

How about adding epsilon to denominator(inter/(union+eps))?
I agree with you, using assert will make training/evaluation slower. But, generalized iou function implemented with assert.

**Comment by fmassa** [comment]
@developer0hye yes, `generalized_iou` has an assert in it, but it is also much less used than `box_iou` (currently no models in torchvision use it).

I think it might be fine to add the assert to the code, but this perf hit is something we need to keep in mind.

**Comment by NicolasHug** [comment]
Thanks for the report @developer0hye ! This issue is very similar to https://github.com/pytorch/vision/issues/2582 and since solving https://github.com/pytorch/vision/issues/2582 will also solve this one (by introducing an assert statement), I'll close this one to keep things tidy. Cheers!
