### ISSUE TITLE
Paper behind Keypoint R-CNN implementation in torchvision

### ISSUE THREAD

**Issue by FraPochetti** [pytorch/vision#3430]
## 📚 Documentation

Hi team,
I can't seem to find the paper behind the [Keypoint R-CNN](https://pytorch.org/vision/0.8/models.html#keypoint-r-cnn) implementation in `torchvision`.
I'd like to better understand and study the architecture and I was looking for some support in the literature, please.
Thanks

**Comment by fmassa** [comment]
Hi,

Sorry for missing this. The paper is "Mask R-CNN" https://arxiv.org/abs/1703.06870 , see Section 5.

@prabhat00155 can you add an entry to the detection models with the paper references?
