### ISSUE TITLE
add EfficientNet for torchvision

### ISSUE THREAD

**Issue by WZMIAOMIAO** [pytorch/vision#3433]
## 🚀 Feature
Add EfficientNet models into torchvision module.

## Motivation
I very love this projects.
I noticed that in 2019 it was said that efficientnet models would be added. #980 
But up to now, there is no efficientnet models.
I'm looking forward to adding more new models to torchvision.

## Additional context
I refer to the official efficientnet model of tensorflow implemented with keras module [link](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/applications/efficientnet.py) and the mobilenetV3 model in torchvision [link](https://github.com/pytorch/vision/blob/master/torchvision/models/mobilenetv3.py). Then I built efficientnet models [Test9_efficientNet](https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_classification/Test9_efficientNet/model.py) and the conversion weight script [trans_weights_to_pytorch.py](https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_classification/Test9_efficientNet/trans_weights_to_pytorch.py).
If you think it's useful a little bit, I hope you can add efficientnet models to torchvision as soon as possible.

**Comment by pmeier** [comment]
Hey @WZMIAOMIAO. I've skimmed #980 and as far as I understood the problem is not the implementation, but rather the training. If you have more insights or ressources, I suggest you get in touch with the other participants in the discussion.

Anyway, since there already is an issue for this, lets keep the discussion there.
