### ISSUE TITLE
Windows CPU build missing on PyPI?

### ISSUE THREAD

**Issue by 1enn0** [pytorch/vision#3436]
## 🐛 Bug

Is there a reason the CPU build of `torchvision` is not pushed to PyPI anymore?

## To Reproduce

1. `pip install torch==1.7.1 torchvision==0.8.2 torchaudio==0.7.1`

Output:
```
Collecting torch==1.7.1
  Downloading torch-1.7.1-cp38-cp38-win_amd64.whl (184.0 MB)
     |████████████████████████████████| 184.0 MB 201 kB/s
ERROR: Could not find a version that satisfies the requirement torchvision==0.8.2
ERROR: No matching distribution found for torchvision==0.8.2
```

## Expected behavior

CPU build of `torchvision` is installed.

## Environment

 - OS: Windows
 - Python version: 3.8.6

## Additional context

`torchvision` used to be pushed to PyPI ([up until v0.5.0](https://pypi.org/project/torchvision/0.5.0/#files)) and I'm wondering why this isn't the case anymore. I'm aware the standard/recommended way of installing is through [the pytorch.org index](https://download.pytorch.org/whl/torch_stable.html). However, the main `torch` package (CPU only) is being pushed to PyPI, so I'm wondering whether it is inteded that both `torchvision` and `torchaudio` are not or if it's just a bug?

I could not find any helpful recent information on this, only some discussions around PyPI binary size contraints (mainly [this](https://github.com/pytorch/vision/issues/1774) and [this](https://github.com/pytorch/pytorch/issues/24310#)). I understand this is a problem for the CUDA builds but for the CPU build I really do not see any issue (e.g. `torchvision` v0.5.0 is 1.2 MB).

Does anybody have some insight as to why this is happening?

cc @peterjc123 @nbcsm @guyang3532 @maxluk @gunandrose4u @smartcat2010 @mszhanyi

**Comment by pmeier** [comment]
Also cc @seemethere

**Comment by 1enn0** [comment]
The Windows binaries started to be uploaded to PyPI as of [`torchvision` 0.9.0](https://pypi.org/project/torchvision/0.9.0/#files).
