### ISSUE TITLE
[docs] Usage example missing for torchvision.utils.draw_bounding_boxes

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/vision#3449]
https://pytorch.org/vision/master/utils.html?highlight=draw_bounding_boxes#torchvision.utils.draw_bounding_boxes

Return type is not described.

Also, it says: ` If filled, Resulting Tensor should be saved as PNG image.`. What does word `filled` refer to? Where would it be `saved`? To some file path? Or encoded into the output tensor?

**Comment by oke-aditya** [comment]
Nice points @vadimkantorov . We recently added these utils and they are bit on the rough edge.
We have these TODO points in #3364 . I wanted to add this PR after #3330 . @datumbox  Since it will take time to add segmentation mask utility. Should I quickly patch #3364 ?

**Comment by datumbox** [comment]
@oke-aditya Apologies for the delay. I'm currently OOO... 

@fmassa Thoughts on how we could unblock Oke on his open PR or how to proceed?
