### ISSUE TITLE
add the pretrained resnext101_64x4d model

### ISSUE THREAD

**Issue by tangjiuqi097** [pytorch/vision#3485]
## 🚀 Feature

add the pretrained resnext101_64x4d model

## Motivation

In object detection, the resnext101_64x4d is a widely used backbone.
But the torchvision model only provide the resnext101_32x8d pretrained models.
If we want to use the resnext101_64x4d in object detection, it cannot be smoothly to change.

**Comment by oke-aditya** [comment]
Hello. @tangjiuqi097 . The discussion for adding new models is in #2707. Feel free to comment there.
I will add this to the list.
