### ISSUE TITLE
utils.save_image fails when passing list of images

### ISSUE THREAD

**Issue by mseitzer** [pytorch/vision#349]
utils.save_image fails when passing in a list of images, as the code tries to call .cpu on the list. 
Passing in a list should be possible according to the function's documentation.

**Comment by alykhantejani** [comment]
@mseitzer thanks - this looks like a bug. Can you send a PR? If not I will try and get to it at some point this week

**Comment by yannadani** [comment]
@alykhantejani Facing the same issue. Can send a PR if you are still not on it.

**Comment by alykhantejani** [comment]
@yannadani thanks, that would be great!
