### ISSUE TITLE
utils.make_grid should not return tensors of dimension 2 or 3 without normalizing them

### ISSUE THREAD

**Issue by mseitzer** [pytorch/vision#350]
When passing in a single image of dimensionality 2 or 3 to utils.make_grid, the function currently returns this image, without normalizing it (but it should, according to the function's documentation).
This is also problematic as utils.save_image calls utils.make_grid to normalize its images.

**Comment by alykhantejani** [comment]
Hi @mseitzer,

The d[ocs for make grid ](http://pytorch.org/docs/master/torchvision/utils.html#torchvision.utils.make_grid)and save image both specify `Normalize=False` by default. You can change this by passing `Normalize=True` to the function.

**Comment by mseitzer** [comment]
Hi @alykhantejani,

what I tried to say is that even when passing `normalize=True`, tensors of dimensionality 2 or 3 are not normalized. This is due to an early return, see https://github.com/pytorch/vision/blob/c9b8914528f70fc8444a913a0934a0e44bff67c1/torchvision/utils.py#L37-L42

I would consider this a bug.

**Comment by alykhantejani** [comment]
Ah ok, yes this looks like a bug. I'll try and fix this and the other utils one this week. Thanks for reporting!
