### ISSUE TITLE
Sphinx is pinned to 1.7.4, the other domain libraries use 2.4.4

### ISSUE THREAD

**Issue by mattip** [pytorch/vision#3511]
## 📚 Documentation

It would be nice to update sphinx, going all the way to the latest 3.5.1 would improve things like search.

See docs/requirements.txt

**Comment by mthrok** [comment]
> going all the way to the latest 3.5.1 would improve things like search.

Do you know if the lates sphinx work?
torchaudio did not pin the version previously and I think I used the latest Sphinx which caused rendering issue.

https://github.com/pytorch/audio/pull/972

**Comment by fmassa** [comment]
I would be ok changing the pinned version to a more recent one.

We pinned it in https://github.com/pytorch/vision/pull/1479 because of a bug sphinx 1.8, and it doesn't look like that issue has been fixed yet

**Comment by mattip** [comment]
Fwiw, only torchvision and torchtext try to use googleanalytics in the sphinx-generated documentation (pytorch and torchaudio do not use it). In torchtext they [require it](https://github.com/pytorch/text/blob/v0.9.0-rc5/docs/requirements.txt#L2) to be pip installed but do not [activate it in the conf.py](https://github.com/pytorch/text/blob/v0.9.0-rc5/docs/source/conf.py#L36). Are you sure you need the data it provides?

**Comment by fmassa** [comment]
@mattip having more fine-grained statistics on what the users are most interested in the documentations is definitely helpful, although as of now our documentation pages are very large so we probably only get information like `datasets` / `transforms`, and not `datasets.Caltech101`.

@brianjo thoughts on enabling googleanalytics more broadly?

**Comment by brianjo** [comment]
Can we take GA code out of the conf.py and just add it to the template like this? https://www.ericholscher.com/blog/2009/apr/5/adding-google-analytics-sphinx-docs/ 
We could then unpin sphinx?

**Comment by NicolasHug** [comment]
@brianjo yes I think this should work (#3660) and in fact this could probably be included directly in the pytorch theme https://github.com/pytorch/pytorch_sphinx_theme/issues/109 so that all domains could benefit from this
