### ISSUE TITLE
torchvision docs link expired on Get Started page.

### ISSUE THREAD

**Issue by ain-soph** [pytorch/vision#3520]
## 📚 Documentation
As the new version 0.8.0 updates the doc link from https://pytorch.org/docs/stable/torchvision to https://pytorch.org/vision/stable/ .  
But the link at the `get started` page is not modified. Please fix it.  
(Actually the torchvision links in most tabs are wrong and still the old one. Only the links in Tutorial and Docs tabs are correct.)  
(Especially, on a 404 page (say https://pytorch.org/docs/123456), the torchvision link is not correct.)
<img src="https://user-images.githubusercontent.com/13214530/110227899-e1b28a00-7eca-11eb-9226-4a41e14f32f9.png" alt="image" width="500"/>

<img src="https://user-images.githubusercontent.com/13214530/110227904-ebd48880-7eca-11eb-82bc-492a90f0a760.png" alt="image" width="500"/>

**Comment by ain-soph** [comment]
Actually it might be better to transfer issue to [pytorch/pytorch.github.io](https://github.com/pytorch/pytorch.github.io/issues)

**Comment by fmassa** [comment]
Thanks for opening this issue! We need to get this fixed.

cc @brianjo can you have a look?

**Comment by brianjo** [comment]
On it. This should fix the issue. https://github.com/pytorch/pytorch.github.io/pull/609

Thanks Ren!  @ain-soph

**Comment by fmassa** [comment]
Thanks @brianjo and @ain-soph !
