### ISSUE TITLE
Add Docs for AutoAugment methods.

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#3527]
## 📚 Documentation

Add documentation for AutoAugment,
[AutoAugmentation](https://pytorch.org/blog/pytorch-1.8-new-library-releases/#stable-autoaugment) was added as a stable feature in the latest 0.9 release.

I think we are missing the docs on transforms page for both [master](https://pytorch.org/vision/master/transforms.html) as well as [0.9 docs](https://pytorch.org/vision/0.9/transforms.html)

I think the following needs to be added.

- [ ] A small note and description as done in the [release page](https://github.com/pytorch/vision/releases/tag/v0.9.0)
- [ ] Autodoc the methods in [`torchvision/transforms/autoaugment.py`](https://github.com/pytorch/vision/blob/v0.9.0/torchvision/transforms/autoaugment.py) file.
- [ ] Also add a `__all__`in above file. I think only [AutoAugment](https://github.com/pytorch/vision/blob/01dfa8ea81972bb74b52dc01e6a1b43b26b62020/torchvision/transforms/autoaugment.py#L127) and [AutoAugmentPolicy](https://github.com/pytorch/vision/blob/01dfa8ea81972bb74b52dc01e6a1b43b26b62020/torchvision/transforms/autoaugment.py#L11) are supposed to be added.

I can send a PR for this. Do let me know!

**Comment by datumbox** [comment]
@oke-aditya Good catch! 

I should have done this when I sent the original PR. Could you please send a PR to fix your points?

Note that `AutoAugmentPolicy` is also supposed to be public (I edited your issue in place to indicate this).

**Comment by oke-aditya** [comment]
Great. Let me send a PR for master.
