### ISSUE TITLE
Port remaining dataset tests to new architecture

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#3531]
## 🚀 Feature

Port remaining dataset tests to new architecture.

## Motivation

#3402 added new infrastructure for dataset tests. In a number of follow-up PRs tests for datasets were added that previously weren't tested. The following datasets still use the old test architecture:

- `ImageNet`
- `WIDERFace`
- `CityScapes`
- `SVHN`
- `Places365`
- `STL10`

## Pitch

Port the remaining dataset tests to the new architecture.

cc @pmeier

**Comment by prabhat00155** [comment]
All the aforementioned tests have been ported to the new test framework.
