### ISSUE TITLE
Update release on Conda and pip

### ISSUE THREAD

**Issue by napsternxg** [pytorch/vision#356]
The latest release 0.2.0 is not available on Conda or Pip. @soumith 's channel has conda release of 0.2.0 for only osx, but the linux and other releases are not updated.

**Comment by alykhantejani** [comment]
Hi @napsternxg, 

The releases are in preparation, and the links will be up shortly. cc @soumith who might have a better idea on the timeline

**Comment by alykhantejani** [comment]
Hi @napsternxg this is now released. You can install by doing:
```
conda install torchvision -c pytorch
```

Note: the channel has changed from `soumith` to `pytorch`

**Comment by napsternxg** [comment]
Thanks a lot.
