### ISSUE TITLE
Update datasets URLs

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#3569]
## 🚀 Feature

Update dataset URLs.

## Motivation

Our [download tests](https://github.com/pytorch/vision/runs/2111140426) have identified a number of dataset URLs that are no longer up to date. They are listed in the `warnings summary` section:

## Pitch

We should update them.

cc @pmeier

**Comment by oke-aditya** [comment]
Hi @pmeier I would be happy to send PR :smile:  (but would leave for any newer contributor)

**Comment by pmeier** [comment]
That would be great, go ahead!
