### ISSUE TITLE
Unable to install torchvision nightly version

### ISSUE THREAD

**Issue by zhiqwang** [pytorch/vision#3598]
## 🐛 Bug

Use following script to install PyTorch and TorchVision version, but `pip` cannot collect torchvision nightly version correctly.

```shell
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
```

Finally, it directed to install the torch 1.8.0 and torchvision 0.9.0.

## To Reproduce

1. `pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`

It collect torchvision 0.9.0 as below:

![image](https://user-images.githubusercontent.com/4210061/112244966-065c7f00-8c8b-11eb-92db-b853959b210e.png)

## Expected behavior

`pip` can collect nightly version.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): nightly version
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): `pip`
 - Build command you used (if compiling from source): N/A
 - Python version: python3.7
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information:

## Additional context

I'm using GitHub Actions, and you can check the workflow [here](https://github.com/zhiqwang/yolov5-rt-stack/runs/2180747313#step:4:22).

**Comment by fmassa** [comment]
Thanks for the report! 

This should be fixed with https://github.com/pytorch/vision/pull/3599
