### ISSUE TITLE
Imagenet dataloader error: RuntimeError: The archive ILSVRC2012_devkit_t12.tar.gz is not present in the root directory or is corrupted.

### ISSUE THREAD

**Issue by seyeeet** [pytorch/vision#3602]
## 🐛 Bug

I am using pytorch 1.8.0 and torchvision 0.9.
I am trying to use the pretrained models from pytorch and evaluate them on imagenet val data. That should be fairly straightforward, but I am getting stuck on the dataloader.
I downloaded the imagenet and the folder structure that I have is like this:
```
/media/SSD2/ILSVRC/
                |----Annotation
                |----ImageSets
                |----Data
                      |----CLS-LOC
                               |----test
                               |----train
                               |----val
                                      |----ILSVRC2012_val_00000009.JPEG
                                      |----ILSVRC2012_val_00000010.JPEG
                                      |----...
```
I tried `datasets.ImageNet`, based on [pytorch](https://pytorch.org/vision/stable/datasets.html#imagenet)  where it says to use the following

```
imagenet_data = torchvision.datasets.ImageNet('path/to/imagenet_root/')
data_loader = torch.utils.data.DataLoader(imagenet_data,
                                          batch_size=4,
                                          shuffle=True,
                                          num_workers=args.nThreads)
```
I changed the path_to_imagenet_to `/media/SSD2/ILSVRC/` like this

 `torchvision.datasets.ImageNet('/media/SSD2/ILSVRC/',split='val',download=False)` 
but I get this error:
```
RuntimeError: The archive ILSVRC2012_devkit_t12.tar.gz is not present in the root directory or is corrupted. You need to download it externally and place it in /media/SSD2/ILSVRC/.
```
Is it a bug or I am doing something wrong?

cc @pmeier

**Comment by pmeier** [comment]
Hey @seyeeet, this data structure looks not familiar. How did you download the data? `ImageNet` expects an image folder structure. That means within the `train` and `val` should be class folders which contain the images. 

If you have the archive, I suggest you prepare the like this:

```python
from torchvision.datasets.imagenet import parse_devkit_archive, parse_train_archive, parse_val_archive

root = "/path/to/folder/of/archives"
parse_devkit_archive(root)
parse_train_archive(root)
parse_val_archive(root)
```

Afterwards you can simply do `ImageNet(root, split=...)`.

Let me know if does not solve your problem.

**Comment by seyeeet** [comment]
I download it from the official imagenet website.
The structure was the main issue, I changed it to the following format and it is working fine. Thanks
```
/media/imagenet/
                |----train
                      |----n01440764
                      |----...
                |----val
                      |----n01440764
                      |----... 
```
