### ISSUE TITLE
`packaging/windows/cuda101.bat` not used anymore?

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#3617]
Following https://github.com/pytorch/vision/pull/3399#discussion_r604090472 , looks like `packaging/windows/cuda101.bat` is not used anymore. If that's indeed the case, we should remove it.

cc @seemethere

**Comment by peterjc123** [comment]
@fmassa Not just `packaging/windows/cuda101.bat`. More files could be deleted, including 
- packaging/windows/
  - cpu.bat
  - cuda101.bat
  - cuda102.bat
  - cuda92.bat
  - templates
  - old
- packaging/conda/
- packaging/windows/internal
  - Most of them could be deleted, will list them later
