### ISSUE TITLE
Missing doc for `torchvision.get_video_backend`

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#3633]
## 📚 Documentation

I think torchvision has a function which can [get_video_backend](https://github.com/pytorch/vision/blob/37eb37a836fbc2c26197dfaf76d2a3f4f39f15df/torchvision/__init__.py#L87).

But sadly it is not documented (perhaps intended ?)

But we do have docs for [get image backend ](https://pytorch.org/vision/master/#torchvision.get_image_backend)
and I think it might be useful to add for `get_video_backend` too.

cc @bjuncek

**Comment by NicolasHug** [comment]
Addressed by https://github.com/pytorch/vision/pull/3643
