### ISSUE TITLE
make_grid function description is puzzling 

### ISSUE THREAD

**Issue by oneTaken** [pytorch/vision#365]
`make_grid` doc is [here](http://pytorch.org/docs/0.3.0/torchvision/utils.html#torchvision.utils.make_grid), 
```
torchvision.utils.make_grid(tensor, nrow=8, padding=2, normalize=False, range=None, scale_each=False, pad_value=0)
```
Should `nrow` means the number of row?
But in the code, it means the number of column.
I got the counterintuitive result when I saved the image.
Besides, should the doc add just one more sentence to describe the situation when 
`B/nrow != B//nrow`?
We know that would pads missing image with 0. But it's known by experiment. 
It also might be `drop_last`, right?

**Comment by fmassa** [comment]
It is indeed a misleading name, but it means the number of images in a row.
I don't know if dropping the images that don't fit in the `B % nrow` from the grid is a good thing to have though, and the user can himself just remove the elements himself if he wants.

What do you think?

**Comment by oneTaken** [comment]
Yeah, the code is good and useful. 
If someone want to `drop_last`, he could code himself.
The `the number of images in a row` is the same as `the number of column`. 
It's hard to connect the param `nrow` to the meaning `the number of images in a row`, but not `the number of rows`.
Right?

**Comment by fmassa** [comment]
I agree that this is misleading. I don't know of a good way of deprecating the current behavior in favor of the misleading one. Maybe for next release we can make a breaking change and modify its behavior to be `number of rows`.
@alykhantejani what do you think?

**Comment by alykhantejani** [comment]
I also agree `nrows` is a misleading name. Perhaps `ncols` would be better. As it's a kwarg we can add `ncols` and just deprecate `nrows` by showing a warning and finally removing it in version 0.3?

**Comment by fmassa** [comment]
While the naming is unfortunate, we have improved the documentation of the function, so I think this can be closed.
