### ISSUE TITLE
Avoid pandas dependency for CelebA dataset

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#3650]
The CelebA dataset has a runtime dependency on `pandas`. Since all we need is `pandas.read_csv`, it would be interesting to see if we can replace `pandas.read_csv` by just the builtin `csv` module. The mergability of the PR would depend on how ugly / complex the code becomes... :)

cc @pmeier

**Comment by pmeier** [comment]
Yes, that bothered me for a long time. Never enough to fix it though :innocent: The tests also manage without `pandas`. Go ahead @carolineechen.
