### ISSUE TITLE
Caching disabled on AnchorGenerator

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#3667]
## 🐛 Bug

Currently the caching mechanism of AnchorGenerator is completely disabled because the Cache dictionary is wiped every time at the end of forward:

https://github.com/pytorch/vision/blob/e61747438522e2d5a92b0b7836754be1a7eb9017/torchvision/models/detection/anchor_utils.py#L156-L157

The clear statement was introduced at #1657 to solve a memory leak reported at #1689. 

Before providing a solution, I think it's worth to:
1. Measure the speed benefit of caching. This should be done by measuring the speed of AnchorGenerator both individually and while being used by a detection model to assess its true impact.
2. Validate that the memory leak is still present by measuring precisely the size of the cache in AnchorGenerator. The best way to do this would be to pass through it a sample of a real-world dataset like coco.

After having the above we could decide how to solve the bug. Here are a few proposed options:
1. Remove the clear statement from forward, if the benchmarks show that the AnchorGenerator has no significant memory issues.
2. Remove the caching completely, if the benchmarks show that is does not offer a material speed improvement (for example improving by over 5% the speed of end-to-end image prediction).
3. Replace the cache with an LRU cache, if the benchmarks show that the memory leak exists and the caching is beneficial. Note that we need to ensure that the LRU cache is compatible with JIT.

**Comment by prabhat00155** [comment]
I used the script shared in https://github.com/pytorch/vision/issues/1689 to verify the memory usage with and without caching and didn't see much difference:
```
import os
import gc
import random

import torch
import psutil
from torchvision.models.detection import fasterrcnn_resnet50_fpn

process = psutil.Process(os.getpid())
model = fasterrcnn_resnet50_fpn(pretrained=True)
# model.eval() # Gives no issues

for i in range(10):
    size = random.randint(700, 900)
    images = torch.rand([1, 3, size, 800]) 
    # images = torch.rand([1, 3, size, size]) # Gives no issues
    targets = [{'boxes': torch.tensor([[ 10., 20., 30., 40.]]), 'labels': torch.tensor([1])}]
    model(images, targets)
    gc.collect()
    print("Current memory: ", process.memory_info()[0] / float(2**20))
```
Without caching(current version):
```
Current memory:  1134.390625
Current memory:  1203.33984375
Current memory:  1223.8828125
Current memory:  1231.9921875
Current memory:  1543.68359375
Current memory:  1546.71875
Current memory:  1571.2265625
Current memory:  1580.12109375
Current memory:  1580.51171875
Current memory:  1580.7890625
```
With caching(by commenting out clear()):
Try 1:
```
Current memory:  1171.6171875
Current memory:  1242.02734375
Current memory:  1562.94921875
Current memory:  1592.4140625
Current memory:  1600.921875
Current memory:  1609.3125
Current memory:  1622.9140625
Current memory:  1622.953125
Current memory:  1638.8515625
Current memory:  1649.53125
```
Try 2:
```
Current memory:  1119.1328125
Current memory:  1467.59765625
Current memory:  1748.96875
Current memory:  1759.48828125
Current memory:  1772.94140625
Current memory:  1793.87890625
Current memory:  1805.3515625
Current memory:  1810.6953125
Current memory:  1811.0859375
Current memory:  1811.21484375
```

I also tried comparing the time to run AnchorGenerator forward() using this script(in Juypyter notebook):
```
size = random.randint(700, 900)
images = torch.rand([10, 3, size, 800])
sizes = [(size, 800)] * 10
    
image_list = ImageList(images, sizes)
features = torch.rand([3, 128, 32, 32])
```
```
%%timeit

anchor_gen = AnchorGenerator(
        sizes=((16, 32, 64, 128, 256, 512),),
        aspect_ratios=((0.5, 1.0, 2.0),)
    )
anchors = anchor_gen(image_list, [features])
```
Without caching(current version):
```
648 µs ± 92.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
With caching(by commenting out clear()):
```
642 µs ± 66.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
There doesn't seem to be any significant difference in speed.

Note: I am running these on my laptop, so there could be other processes affecting the results.

**Comment by datumbox** [comment]
@prabhat00155 Thanks a lot for the detailed benchmarks! Since I spotted this bug, I was inclined to remove caching as it makes the code more complex. Can't say I changed my mind after reading your analysis... I propose to remove the caching mechanism completely.

@fmassa @NicolasHug thoughts?

**Comment by NicolasHug** [comment]
```py
%%timeit

anchor_gen = AnchorGenerator(
        sizes=((16, 32, 64, 128, 256, 512),),
        aspect_ratios=((0.5, 1.0, 2.0),)
    )
anchors = anchor_gen(image_list, [features])
```

I'm wondering if the above properly assesses the caching mechanism. From what I understand the cache is useful across calls to `forward` but the snippet above will only call `forward` once per `AnchorGenerator` instance.

Should this be instead, e.g.:

```py
%%timeit
anchor_gen = AnchorGenerator(
        sizes=((16, 32, 64, 128, 256, 512),),
        aspect_ratios=((0.5, 1.0, 2.0),)
    )

for _ in range(1000):
	anchors = anchor_gen(image_list, [features])  # cache hits for the next 999 calls
```

**Comment by prabhat00155** [comment]
> Regarding the timing benchmark,
> 
> ```python
> %%timeit
> 
> anchor_gen = AnchorGenerator(
>         sizes=((16, 32, 64, 128, 256, 512),),
>         aspect_ratios=((0.5, 1.0, 2.0),)
>     )
> anchors = anchor_gen(image_list, [features])
> ```
> 
> I'm wondering if the above properly assesses the caching mechanism. From what I understand the cache is useful across calls to `forward` but the snippet above will only call `forward` once per `AnchorGenerator` instance.
> 
> Should this be instead, e.g.:
> 
> ```python
> %%timeit
> anchor_gen = AnchorGenerator(
>         sizes=((16, 32, 64, 128, 256, 512),),
>         aspect_ratios=((0.5, 1.0, 2.0),)
>     )
> 
> for _ in range(1000):
> 	anchors = anchor_gen(image_list, [features])  # cache hits for the next 999 calls
> ```
> 
> ?

Doesn't timeit call the cell multiple times(1000 by default)?

**Comment by NicolasHug** [comment]
Yes but it will create 1000 `AnchorGenerator` instances and call forward once on each of them. There won't be any cache hit since the cache hits can only happen when forward is called (at least) twice on the same instance, as far as I understand

**Comment by prabhat00155** [comment]
> Yes but it will create 1000 `AnchorGenerator` instances and call forward once on each of them. There won't be any cache hit since the cache hits can only happen when forward is called (at least) twice on the same instance, as far as I understand

Yeah, that's true. I should move instantiating AnchorGenerator out of this cell.

**Comment by NicolasHug** [comment]
> I should move instantiating AnchorGenerator out of this cell.

I'm not sure this is still what we want: this will give you an average over 1000 runs where the cache will be hit 999 times except for the first time.

In fact if the caching is super effective %timeit  will actually detect that the first run took much longer than the rest and give you a warning.

**Comment by prabhat00155** [comment]
I do see an improvement with caching(after removing self._cache.clear()).
With caching:
```
337 µs ± 14.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
Without caching:
```
526 µs ± 20.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by NicolasHug** [comment]
I get a similar 2X speed up with caching:

```py
%%timeit
anchor_gen = AnchorGenerator(
        sizes=((16, 32, 64, 128, 256, 512),),
        aspect_ratios=((0.5, 1.0, 2.0),)
    )

for _ in range(1000):
	anchors = anchor_gen(image_list, [features])
```

`357 ms ± 21.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

vs

`658 ms ± 54.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

**Comment by prabhat00155** [comment]
Similar results with the script @NicolasHug suggested:
With caching:
```
313 ms ± 14 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Without caching:
```
567 ms ± 41.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by datumbox** [comment]
Thanks both. 

Good spot for finding the benchmark issue @NicolasHug.

It would be useful to finally measure how much the performance changes during inference for end-to-end predictions. In other words, assume we are making predictions on a mobile device (cpu). How much time does it take on average to produce one prediction with and without the caching (after some burn in period)?

The reason I'm proposing to measure also this is to assess whether this double speed up makes actually a difference for a model such as the `fasterrcnn_mobilenet_v3_large_320_fpn`. 

@prabhat00155 I wonder if you could run a modified version of the following so that we could get comparable numbers on the same machine?
```python
model = fasterrcnn_mobilenet_v3_large_320_fpn(pretrained=True)
model.eval()

images = torch.rand([1, 3, 700, 800]) 
model(images) # populate cache once

# TODO: measure avg time with and without caching for the following loop
for i in range(1000):
    model(images)
```

**Comment by NicolasHug** [comment]
> The reason I'm proposing to measure also this is to assess whether this double speed up makes actually a difference for a model such as the fasterrcnn_mobilenet_v3_large_320_fpn.

+1 to assess how impactful the caching is in real-world scenarios.

If caching is proven useful, the safest solution might be to change the cache to an LRU cache as suggested in https://github.com/pytorch/vision/pull/1657#discussion_r356555134. The max_size of the cache could be configurable as a constructor argument?

**Comment by prabhat00155** [comment]
I don't see any difference in the numbers with `fasterrcnn_mobilenet_v3_large_320_fpn`. Here is what I did:
```
model = fasterrcnn_mobilenet_v3_large_320_fpn(pretrained=True)
model.eval()

images = torch.rand([1, 3, 700, 800]) 
model(images) # populate cache once
```
1. Capture using timeit:
```
%%timeit -n 10

model(images)
```
With caching:
```
84.4 ms ± 854 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
Without caching:
```
85.7 ms ± 2.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
2. Loop
```
%%timeit

for i in range(1000):
    model(images)
```
With caching:
```
1min 33s ± 770 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Without caching:
```
1min 28s ± 468 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by datumbox** [comment]
Thanks for providing the new benchmarks. So overall, the caching seems to reduce the Anchor generation time by almost half, nevertheless this step is short and does not have a material effect on the execution time of predictions. 

There are two options here:
1. Replace the dictionary with an LRU cache so that there are no memory leaks or awkward calls to clear it.
2. Remove the caching completely to simplify the code.

Personally, I would go with option 2. Caching does not currently work and does not provide a lot of value.

**Comment by prabhat00155** [comment]
> Thanks for providing the new benchmarks. So overall, the caching seems to reduce the Anchor generation time by almost half, nevertheless this step is short and does not have a material effect on the execution time of predictions.
> 
> There are two options here:
> 
> 1. Replace the dictionary with an LRU cache so that there are no memory leaks or awkward calls to clear it.
> 2. Remove the caching completely to simplify the code.
> 
> Personally, I would go with option 2. Caching does not currently work and does not provide a lot of value.

Makes sense, thanks. I'll create a PR for this(option 2).

**Comment by fmassa** [comment]
Hi,

Thanks for the benchmarks @prabhat00155 !
Back when I added caching I remember seeing improvements for training / evaluation, but it is indeed good to re-evaluate the improvements with latest PyTorch.

One thing that I see was missing in the benchmarks is to perform the benchmarking using CUDA, which would give a different perception of how the caching improves things.

Another thing which can be handy for benchmarking code in PyTorch is to use [`torch.utils.benchmark`](https://pytorch.org/docs/stable/benchmark_utils.html?highlight=benchmark#module-torch.utils.benchmark), which comes with its own version of `Timer` that is CUDA-aware.

**Comment by prabhat00155** [comment]
@fmassa Do you have the benchmarking scripts that you used?

**Comment by prabhat00155** [comment]
I re-ran the script on devgpu with similar observation.
```
model_cuda = fasterrcnn_mobilenet_v3_large_320_fpn(pretrained=True).cuda()
model_cuda.eval()

images_cuda = torch.rand([1, 3, 700, 800]).cuda()
model_cuda(images_cuda) # populate cache once
```
Measure time for the following cell:
```
%%timeit
# TODO: measure avg time with caching for the following loop
for i in range(1000):
    model_cuda(images_cuda)
```
With caching:
```
21.1 s ± 2.33 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Without caching:
```
21.3 s ± 2.45 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
In comparison, here are the CPU results(on the same machine):
With caching:
```
38.1 s ± 698 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Without caching:
```
38.1 s ± 609 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by fmassa** [comment]
@prabhat00155 note that performing benchmarking on the GPU requires adding synchronization points, otherwise the results might not be reliable.

This can be done via `torch.cuda.synchronize()` after the function call.

That's why the `Timer` from `torch.utils.benchmark` is handy because it takes care of this for you

**Comment by prabhat00155** [comment]
I used `torch.utils.benchmark` to measure the time and it seems to be similar to the previously measured time.
```
model_cuda = fasterrcnn_mobilenet_v3_large_320_fpn(pretrained=True).cuda()
model_cuda.eval()
image_cuda = torch.rand([1, 3, 700, 800]).cuda()
model_cuda(image_cuda) # populate cache once

def inference(model, image):
    for _ in range(1000):
        model(image)
    
t_gpu = benchmark.Timer(
    stmt='inference(model_cuda, image_cuda)',
    setup='from __main__ import inference',
    globals={'model_cuda': model_cuda, 'image_cuda': image_cuda})

t_gpu.timeit(10)
```
With caching: 21.29 s
Without caching: 20.16 s

**Comment by datumbox** [comment]
@prabhat00155 Thanks for all the thorough checks.

I think the measurements so far are aligned with our knowledge that the majority of the time is being spent on convolutions and post-processing. Thus the optimizations in this class, though they do have measurable effect when studied in isolation, they don't practically affect the execution time during inference. I don't believe we have measured the effects during training, but I'm not sure we will get any different results there either.

Personally I think there is reasonable ground to remove the mechanism since currently does not have any effect due to the bug. As a result, I'll approve #3745 but I recommend getting a more broad agreement before merging.

**Comment by fmassa** [comment]
Thanks for the checks @prabhat00155 !

I second @datumbox , let's get the caching removed.

**Comment by datumbox** [comment]
@prabhat00155 Do you want to keep this ticket open for also removing [this](https://github.com/pytorch/vision/pull/3745/files#r622030928) or you would like to raise a new issue? Whichever you prefer. :)
