### ISSUE TITLE
Master Documentation is broken at places

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#3681]
## 📚 Documentation

The master is built with latest sphinx so there are few places where docs aren't nice. E.g. [ops master](https://pytorch.org/vision/master/ops.html) vs [ops 0.9](https://pytorch.org/vision/0.9/ops.html)

What's broken.

- [ ] Almost everywhere Type hinting in functions, which for in built dtypes such as `str`, `int`, `float`
E.g. [EMNIST Docs](https://pytorch.org/vision/master/datasets.html#emnist)

- [X] ~VGG Docs for [papers](https://pytorch.org/vision/master/models.html#torchvision.models.vgg11). The link for paper isn't rendered well.~ That's actually not related to the new shpinx and it was already bad on master. #3684 Fixes the links

Possibly this is because of the upgrade to Sphinx 3.5.4. Maybe some other version might render it well?
Possible fixes are in [this](https://stackoverflow.com/questions/40071573/python-3-sphinx-doesnt-show-type-hints-correctly) stackoverflow QA

**Comment by NicolasHug** [comment]
Thanks for the report, yeah I noticed that too. This seems related to the theme,
I'll reach out to the theme team on Monday and see what we can do

**Comment by NicolasHug** [comment]
The paper links are unrelated to the sphinx version (but thanks for noticing!)

Another discrepancy that I noticed is that the "Parameters", "Returns" sections etc now have a different and more bulky rendering: [0.9](https://pytorch.org/vision/0.9/datasets.html#torchvision.datasets.CIFAR10) vs [master](https://pytorch.org/vision/master/datasets.html#torchvision.datasets.CIFAR10)

I tend to have a preference for the "old" one but maybe that was made on purpose: all of torchaudio, torchtext and pytorch docs use the "new" bulky rendering.

**Comment by NicolasHug** [comment]
I think we can close this now than #3652  / https://github.com/pytorch/vision/pull/3685 have been merged. Thanks @oke-aditya !
