### ISSUE TITLE
[docs] Interpolation modes are not rendered

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/vision#3690]
Members are not listed/rendered, they are however present in the sources: https://pytorch.org/vision/master/_modules/torchvision/transforms/functional.html#InterpolationMode

![image](https://user-images.githubusercontent.com/1041752/115265337-6a158300-a137-11eb-9d30-c4e171119233.png)

**Comment by oke-aditya** [comment]
Hey @vadimkantorov can you send a PR for this fix?

It should probably be a line stating

```
Available interpolation methods are "nearest", "bilinear" "bicubic" "box" "hamming" and "lanczos".
```

It should probably be a simple edit over [here](https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional.py#L23)
