### ISSUE TITLE
CircleCI on Mac is flaky

### ISSUE THREAD

**Issue by prabhat00155** [pytorch/vision#3696]
I have seen a number of tests on Mac failing with this [error](https://app.circleci.com/pipelines/github/pytorch/vision/7547/workflows/ed3a21b4-852e-40a1-880b-41664b584277/jobs/524923):
```
OSError: dlopen(/Users/distiller/project/env/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.dylib, 10): no suitable image found.  Did find:
	/Users/distiller/project/env/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.dylib: mach-o, but wrong architecture
	/Users/distiller/project/env/lib/python3.9/site-packages/torch/lib/libtorch_global_deps.dylib: mach-o, but wrong architecture
```
This seems to be related to PyTorch.

cc @seemethere

**Comment by fmassa** [comment]
cc @seemethere this seems like an issue with the PyTorch OSX packages, and it has been failing for a few days already.

Do you have any ideas of what it might be?

**Comment by prabhat00155** [comment]
This has been fixed.
