### ISSUE TITLE
VOCSegmentation -- RuntimeError: Dataset not found or corrupted. You can use download=True to download it

### ISSUE THREAD

**Issue by seyeeet** [pytorch/vision#3707]
## 🐛 Bug

I have downloaded the VOC Pascal Segmentation dataset and have it as following format:

```
/VOCdevkit
└── VOC2012
    ├── Annotations
    ├── ImageSets
    │   └── Segmentation
    ├── JPEGImages
    ├── SegmentationObject
    └── SegmentationClass
```
I am using the latest torch/torchvision version which is torch 1.7.1 and its corresponding torchvision.
when I want to use the VOCSegmentation dataloader I get the following error:

```
import torch
import torchvision
dataset = torchvision.datasets.VOCSegmentation(root='/path/VOCdevkit/', year='2012', image_set='trainval', download=False)
```
```
Error:
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-a979806cab30> in <module>
      1 import torch
      2 import torchvision
----> 3 dataset = torchvision.datasets.VOCSegmentation(root='/path/VOCdevkit/', year='2012', image_set='trainval', download=False)

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/torchvision/datasets/voc.py in __init__(self, root, year, image_set, download, transform, target_transform, transforms)
    103         if not os.path.isdir(voc_root):
    104             raise RuntimeError('Dataset not found or corrupted.' +
--> 105                                ' You can use download=True to download it')
    106 
    107         splits_dir = os.path.join(voc_root, 'ImageSets/Segmentation')

RuntimeError: Dataset not found or corrupted. You can use download=True to download it
```

cc @pmeier

**Comment by NicolasHug** [comment]
The line you report is different from the one in the error, in particular the `root` param:

`dataset = torchvision.datasets.VOCSegmentation(root='/path/VOCdevkit', year='2012', image_set='trainval', download=False)`

vs

`----> 3 dataset = torchvision.datasets.VOCSegmentation(root='/path/VOCdevkit/VOC2012/', year='2012', image_set='trainval', download=False)`

So there seem to be an inconsistency here.

Also I think you should just pass `/path` (provided that `/path` actually exists)

**Comment by pmeier** [comment]
Plus, 

> I am using the latest torch/torchvision version which is torch 1.7.1 and its corresponding torchvision

is not correct. `torch==1.8.1` / `torchvision==0.9.1` is the current stable release. We did some work on VOC for that release. Of course this might not be the root of the problem.

**Comment by seyeeet** [comment]
@pmeier correct I did not have the latest version. I updated my pytorch/torchvision and have the latest (1.8.1/0.9.1) version now. but still the error happens

@NicolasHug that was just a typo. I corrected it, I still get the error. I tried root as both `/path/VOCdevkit/VOC2012/` and `/path/VOCdevkit/` and both of the generate error.

**Comment by NicolasHug** [comment]
> I tried root as both /path/VOCdevkit/VOC2012/ and /path/VOCdevkit/ and both of them generate error.

Did you try `/path` as suggested above?

**Comment by seyeeet** [comment]
nah, let me try that and get back to you :p

**Comment by seyeeet** [comment]
It actually solved the issue!! Thanks a lot for your help, the solution was to do it with just `path`...
