### ISSUE TITLE
OSError on linux builds

### ISSUE THREAD

**Issue by prabhat00155** [pytorch/vision#3716]
The following error seen in linux builds:
```
OSError: libmkl_intel_lp64.so.1: cannot open shared object file: No such file or directory
```
[binary_linux_conda_py3.9_cpu](https://app.circleci.com/pipelines/github/pytorch/vision/7640/workflows/2c078a6b-a4d4-438f-b70f-40ff26046445/jobs/534190)
[binary_linux_conda_py3.9_cu102](https://app.circleci.com/pipelines/github/pytorch/vision/7640/workflows/2c078a6b-a4d4-438f-b70f-40ff26046445/jobs/534198)
[binary_linux_conda_py3.9_cu111](https://app.circleci.com/pipelines/github/pytorch/vision/7640/workflows/2c078a6b-a4d4-438f-b70f-40ff26046445/jobs/534137)

cc @seemethere

**Comment by vfdev-5** [comment]
@datumbox I think this issue can be closed as it was fixed by https://github.com/pytorch/builder/pull/750

**Comment by datumbox** [comment]
Thanks!
