### ISSUE TITLE
This should be a comment

### ISSUE THREAD

**Issue by christopher-beckham** [pytorch/vision#373]
https://github.com/pytorch/vision/blob/03d2068abb813016e016f96d029e6d6cc5542aaf/torchvision/models/resnet.py#L20

**Comment by alykhantejani** [comment]
@christopher-beckham yup, looks like a mistake. Please can you send a PR?

**Comment by christopher-beckham** [comment]
Actually, my bad, I just realised "" can also count as a docstring. So perhaps this is merely a formatting inconsistency...
