### ISSUE TITLE
Details on pre-training of torchvision models

### ISSUE THREAD

**Issue by spurra** [pytorch/vision#3746]
I realize there is a closed issue on this topic here: https://github.com/pytorch/vision/issues/666

The issue has been opened in 2018. I have not found any documentation on how the models of torchvision are pre-trained, therefore I am opening another issue. Is the above answer still valid? Are the models still trained according to https://github.com/pytorch/examples/tree/master/imagenet ?
Specifically, I would like to know the details on the image size and data transformation used.

Thanks!

**Comment by datumbox** [comment]
Have a look on the [documentation](https://github.com/pytorch/vision/blob/master/docs/source/models.rst) and on the [readme](https://github.com/pytorch/vision/tree/master/references/classification). You will find hyper-params and script references along with detailed accuracies etc.

I'll close the issue to keep things neat but if you have more questions feel free to reopen.

**Comment by spurra** [comment]
Thanks for the rapid response @datumbox 
I found the image size to be 224 and that standardization with imagenet statistics was used (according to [the doc](https://github.com/pytorch/vision/blob/master/docs/source/models.rst). The [readme](https://github.com/pytorch/vision/tree/master/references/classification) you've sent contains ResNext, but unfortunately does not mention ResNet which I'm interested in (forgot to specify, my bad!). Would you happen to know the exact data augmentation pipeline used for the pretrained ResNet models found in torchvision? Or are these the same as in the readme you've sent?

**Comment by datumbox** [comment]
We use the same standardization and size in all models unless explicitly specified otherwise. As far as I recall the only model that deviates is InceptionV3 that uses a different input size (299x299). See:

https://github.com/pytorch/vision/blob/8317295c1d272e0ba7b2ce31e3fd2c048235fc73/references/classification/train.py#L85

**Comment by spurra** [comment]
Great, that's all the info I need. Thanks again @datumbox !
