### ISSUE TITLE
Remove _has_warned attribute from detection models

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#3752]
## 🚀 Feature
Several detection models make use of an attribute `_has_warned` which was originally used by JIT to avoid throwing the same warning multiple times:

https://github.com/pytorch/vision/blob/9778d2675ed33627c30fe2537911f5a4128433bd/torchvision/models/detection/retinanet.py#L373-L374

https://github.com/pytorch/vision/blob/9778d2675ed33627c30fe2537911f5a4128433bd/torchvision/models/detection/retinanet.py#L554-L556

JIT should now be able to handle this automatically without the need of this variable. Thus we should remove the specific variable and confirm that calling forward multiple times on a JIT-scripted model produces a single warning. If that's indeed the case, we can remove it from all places:
- [ ] RetinaNet
- [ ] GeneralizedRCNN
- [ ] SSD (pending merge at #3403)

**Comment by prabhat00155** [comment]
If I remove the `if` check from line [554](https://github.com/pytorch/vision/blob/9778d2675ed33627c30fe2537911f5a4128433bd/torchvision/models/detection/retinanet.py#L554-L556), I see the warning appear every time forward() is invoked. Here is what I did:
```
model = retinanet_resnet50_fpn(pretrained=True)
model.eval()
img = torch.rand([1, 3, 512, 512])
model(img)
for p in model.parameters():
    p.requires_grad_(False)
scripted_model = torch.jit.script(model, img)
for _ in range(10):
    img_test = torch.rand([3, 512, 512])
    scripted_model([img_test])
```
This prints the warning 10 times

**Comment by prabhat00155** [comment]
If I remove the `if` check from line 554, I see the warning appear every time forward() is invoked. Here is what I did:
```
model = retinanet_resnet50_fpn(pretrained=True)
model.eval()
img = torch.rand([1, 3, 512, 512])
model(img)
for p in model.parameters():
    p.requires_grad_(False)
scripted_model = torch.jit.script(model, img)
for _ in range(10):
    img_test = torch.rand([3, 512, 512])
    scripted_model([img_test])
```
This prints the warning 10 times

**Comment by datumbox** [comment]
Thanks for the investigation @prabhat00155! 

Sounds like it's not fixed yet on the TorchScript side and can't remove it. I'll be closing the issue and we can revisit on the future once it's patched.
