### ISSUE TITLE
[CircleCI] test_video_model is failing with segm fault

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#3765]
## 🐛 Bug

Currently, linux gpu tests are failing with segm fault:

```
test/test_models.py::test_video_model[dev1-r2plus1d_18] Fatal Python error: Segmentation fault
```
- https://app.circleci.com/pipelines/github/pytorch/vision/7810/workflows/cf6e0187-8a29-49d3-95ed-167531fb6ed0

This probably hides more failures seeing locally:
```
FAILED test/test_functional_tensor.py::CUDATester::test_gaussian_blur - AssertionError: tensor(226., device='cuda:0') not less than or equal to 1.0 : (3, 3), [0.5, 0.5]                    
FAILED test/test_functional_tensor.py::CUDATester::test_pad - RuntimeError: The following operation failed in the TorchScript interpreter. 
```

cc @seemethere @bjuncek

**Comment by NicolasHug** [comment]
@vfdev-5 if that's OK I'll close in favor of https://github.com/pytorch/vision/issues/3702 which was reported before

**Comment by vfdev-5** [comment]
@NicolasHug OK for me, sorry, I haven't seen your issue when searched for "CI" label.
