### ISSUE TITLE
Unable to get segmented mask output image

### ISSUE THREAD

**Issue by shubhamkotal** [pytorch/vision#3772]
.

**Comment by fmassa** [comment]
Hi,

There is not enough information in the issue for us to be able to help.

Can you post an example image showing what you are getting? Also, do you get correct predictions on some of the training images?

**Comment by shubhamkotal** [comment]
Corrected, Thanks

**Comment by NicolasHug** [comment]
@shubhamkotal I think something went wrong during the editing, your original message now doesn't show anything (it's a single dot)

**Comment by oke-aditya** [comment]
Somehow I ended up here and could reach back original message

@shubhamkotal 

```
After successfully training the model I am unable to get the segmented mask image as model output. Instead, I am getting an image as output with small white dots on black background. Unable to understand why I am getting white dots instead of proper mask segmented image as output.
Please suggest me needful to overcome the issue.
```

You can have a look at at gallery examples in the master documentation. It provides a nice way to plot segmentation outputs.
Also note that the utility `utils.draw_segmentation_masks()` might be available from next release!

**Comment by NicolasHug** [comment]
Specifically please see https://pytorch.org/vision/master/auto_examples/plot_visualization_utils.html#sphx-glr-auto-examples-plot-visualization-utils-py

Without further we're unable to help more (the original message is still a single dot), so I'll close this issue. Feel free to re-open with more background information.
