### ISSUE TITLE
Possible for Compose to inherit from list?

### ISSUE THREAD

**Issue by versatran01** [pytorch/vision#378]
Hi I was wondering if the Compose class could inherit from a list instead of just an object.

It would be nice for Compose to behave like a list or even better, an nn.Sequential, so when you print it, it displays the list of transforms with parameters.

Currently, it just shows up like torchvision.transforms.transforms.Compose, which is not very informative.

**Comment by alykhantejani** [comment]
@versatran01 we could make it extend `list` although I'm not sure we want the other functionality that comes with this i.e. `pop`, `clear`, `count`, `sort` etc.

Instead we could just add a `__repr__` to `Compose` that returns `str(self.transforms)`? Can you send a PR, if not I will try and get to this later today/tomorrow.

Thanks!
