### ISSUE TITLE
ToTensor confuse me with the way it takes input

### ISSUE THREAD

**Issue by MohamedAliRashad** [pytorch/vision#3782]
So the `ToTensor` class of `to_tensor` function takes input in the dimension of (H, W) while PIL has it's images dimension be (W, H).
Why is this transpose ?

cc @vfdev-5

**Comment by vfdev-5** [comment]
PIL.Image.size reports (W, H) and not (H, W), see https://pillow.readthedocs.io/en/stable/handbook/concepts.html?highlight=size#size

As tensor we need to have B, C, H, W format thus it may seem that there is a transpose.

**Comment by datumbox** [comment]
+1 on @vfdev-5 answer, this is the reason.

I'll close the issue to keep things neat but please feel free to reopen if you still have issues.

**Comment by MohamedAliRashad** [comment]
@vfdev-5 
That's exactly what i am asking, PIL grayscale image has its shape to be [W, H] … the `F.to_tensor` function takes input image with shape [H, W, C] and outputs tensor with shape [C, H, W].

if i entered the image without change it will see the Width as the Height and the Height as the Width, This is what confuses me

**Comment by NicolasHug** [comment]
I think that what @vfdev-5 is saying is that while PIL.Image.size reports (W, H), PIL images are still represented as `H, W` arrays or `H, W, C`. For the shape, we just put the `C` in the beginning instead of at the end when converting to tensor.

```py
In [1]: import numpy as np

In [2]: from PIL import Image

In [3]: import torchvision.transforms as T

In [4]: a = np.random.randint(0, 10, (2, 4), dtype=np.uint8)

In [5]: pil_img = Image.fromarray(a)

In [6]: t = T.ToTensor()(pil_img)
/Users/nicolashug/dev/vision/torchvision/transforms/functional.py:136: UserWarning: Legacy tensor constructor is deprecated. Use: torch.tensor(...) for creating tensors from tensor-like objects; or torch.empty(...) for creating an uninitialized tensor with specific sizes. (Triggered internally at  /Users/distiller/project/conda/conda-bld/pytorch_1617466503169/work/torch/csrc/utils/tensor_new.cpp:476.)
  img = torch.ByteTensor(torch.ByteStorage.from_buffer(pic.tobytes()))

In [7]: np.asarray(pil_img)
Out[7]:
array([[1, 2, 1, 0],
       [7, 0, 9, 6]], dtype=uint8)

In [8]: t * 255
Out[8]:
tensor([[[1., 2., 1., 0.],
         [7., 0., 9., 6.]]])
```
