### ISSUE TITLE
RandomCrop

### ISSUE THREAD

**Issue by zhly0** [pytorch/vision#379]
I use the function to crop the input image, but It seems useless,because when I set RandomCrop(140,120),the input shape seems to be 140x140(it seems padding the image to 140x140),but when set RandomCrop(120,140),the input shape become 120x120,for this function is height must equal to width?

**Comment by vabh** [comment]
The way you are using `RandomCrop`, in the first instance, is equivalent to `RandomCrop(size=140, padding=120)`. If you want a specific sized crop you have to give the dimensions as a sequence, such as `RandomCrop(size=(140, 120))`

If you do not give a sequence, you will get a square crop, like you observe.

**Comment by alykhantejani** [comment]
@vabh is correct. Closing for now, if you run into other issues please feel free to comment on this issue or open another one @zhly0

**Comment by zhly0** [comment]
Thanks! my mistake!
