### ISSUE TITLE
Remove libjpeg version pinning

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#3795]
We temporarily pinned the libjpeg version to `<=9b` in #3787 to fix some windows CI jobs. It would be good to remove the pinning. Chances are, the issue will magically resolve in the future?

**Comment by farleylai** [comment]
Unlikely, the type change to `size_t` is what it is supposed to be since the argument `outsize` indeed should represents the platform-dependent size variable. Therefore, the strategy to deal with platform-dependent types should be made clear. Any elaboration?
