### ISSUE TITLE
Build failure with latest ffmpeg master caused by deprecated/removed attributes

### ISSUE THREAD

**Issue by prabhat00155** [pytorch/vision#3805]
Building torchvision from source with latest ffmpeg(installed from source) throws a number of errors:

- [x] [pict attribute](https://github.com/FFmpeg/FFmpeg/blob/75c39692923a203b04efe7ee46d767f0057eac3b/libavcodec/avcodec.h#L2696)
```
/Users/prabhatroy/Documents/pytorch/repos/vision/torchvision/csrc/io/decoder/util.cpp:52:25: error: no member named 'pict' in 'AVSubtitleRect'
          s += sizeof(y.pict.linesize[i]);
                      ~ ^
```
The reason is that ffmpeg's AVSubtitleRect's [pict attribute](https://github.com/FFmpeg/FFmpeg/blob/75c39692923a203b04efe7ee46d767f0057eac3b/libavcodec/avcodec.h#L2696) was deprecated in 3.0 and removed in the latest master.

- [x] [av_frame_get_best_effort_timestamp](https://github.com/FFmpeg/FFmpeg/blob/0c7dc6105224cd199b8e966bc76aafaeaacb2061/libavutil/frame.h#L605)
```
/Users/prabhatroy/Documents/pytorch/repos/vision/torchvision/csrc/io/decoder/stream.cpp:235:19: error: use of undeclared identifier 'av_frame_get_best_effort_timestamp'
    header->pts = av_frame_get_best_effort_timestamp(frame_);
                  ^
1 error generated.
```
av_frame_get_best_effort_timestamp() was deprecated in `ffmpeg 4.0` and removed from the latest master.

We need to update its usage in torchvision.

cc @bjuncek

**Comment by bjuncek** [comment]
In addition to above here are few other things to consider changing (this list will be updated)


# Low (warnings and incorrect usage)
[av_register_all](https://ffmpeg.org/doxygen/3.4/allformats_8c_source.html#l00390)

**Comment by bjuncek** [comment]
Since most of these have been closed I'm closing the issue.

**Comment by prabhat00155** [comment]
Reopening as some changes had to be reverted.

**Comment by bjuncek** [comment]
Closing this since you fixed reverted changes :)
