### ISSUE TITLE
Add title to the make_grid

### ISSUE THREAD

**Issue by seyeeet** [pytorch/vision#3821]
## 🚀 Feature
Can we have an option to add title to each grid in the make_grid? or it would be so difficult/slow?
## Motivation
basically it will helps to identify the grids by a name

cc @fmassa @vfdev-5

**Comment by seyeeet** [comment]
@vfdev-5 Thanks for following up on this.
hmmm is the dictionary of grids already possible? is there any place I can look into it more?

So they way that I was thinking was like this:
so the user can define a list of titles where the length of the list the same as number of batches in the tensor, for example if have a tensor `BxCxHxW`, then I can have `['T-1','T-2'...,'T-N']` where `T-i` is the i_th title for `i_th` batch and length of that list is `B`, 
hmmm if someone defines the number of rows( e.g. `R`), then it may become tricky on how to show the titles, i guess the easiest  solution for when we have number of rows defined is to add every `R` titles from the list, or something similar to it

**Comment by NicolasHug** [comment]
I think we should stop adding features to `make_grid`.

In terms of plotting it does nothing more than what matplotlib or other well-established plotting libraries can do, and we should encourage users to rely on them. It also has an unconventional API: `nrow` isn't the number of rows but the number of images per row... In other words it's the number of columns.

If we keep on adding new features and parameters we'll end up turning `make_grid` into a rendering engine and a matplotlib clone (or a subset of it) and we probably don't want that

@seyeeet I'm still unclear on what you're trying to do but I think that matplotlib will probably be a better option here. Perhaps you can look  at the `plot` function in https://pytorch.org/vision/master/auto_examples/plot_transforms.html#sphx-glr-auto-examples-plot-transforms-py to see how one could plot grids of images with titles?
