### ISSUE TITLE
torchvision C++ compiling 

### ISSUE THREAD

**Issue by swordnosword** [pytorch/vision#3822]
1. quesion:

When I trying to compile torchvision from source in c++ language,  the terminal thow erros:
In file included from /home/pc/anaconda3/include/python3.8/pytime.h:6:0,
                 from /home/pc/anaconda3/include/python3.8/Python.h:85,
                 from /media/pc/data/software/vision-0.9.0/torchvision/csrc/vision.cpp:4:
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:647:30: error: stray ‘\343’ in program
   const std::vector<IValue>& slots() const {
                                               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:647:30: error: stray ‘\200’ in program
   const std::vector<IValue>& slots() const {
                                               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:647:30: error: stray ‘\200’ in program
   const std::vector<IValue>& slots() const {
                                               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:647:30: error: stray ‘\343’ in program
   const std::vector<IValue>& slots() const {
                                              ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:647:30: error: stray ‘\200’ in program
   const std::vector<IValue>& slots() const {
                                               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:647:30: error: stray ‘\200’ in program
   const std::vector<IValue>& slots() const {
                                               ^
In file included from /media/pc/data/software/libtorch/include/c10/core/DispatchKey.h:6:0,
                 from /media/pc/data/software/libtorch/include/torch/library.h:61,
                 from /media/pc/data/software/vision-0.9.0/torchvision/csrc/vision.cpp:6:
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:835:12: error: stray ‘\343’ in program
       obj->slots().size() == 1,
               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:835:12: error: stray ‘\200’ in program
       obj->slots().size() == 1,
               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:835:12: error: stray ‘\200’ in program
       obj->slots().size() == 1,
               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:835:12: error: stray ‘\343’ in program
       obj->slots().size() == 1,
               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:835:12: error: stray ‘\200’ in program
       obj->slots().size() == 1,
               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:835:12: error: stray ‘\200’ in program
       obj->slots().size() == 1,
               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:853:12: error: stray ‘\343’ in program
       obj->slots().size() == 1,
               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:853:12: error: stray ‘\200’ in program
       obj->slots().size() == 1,
               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:853:12: error: stray ‘\200’ in program
       obj->slots().size() == 1,
               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:853:12: error: stray ‘\343’ in program
       obj->slots().size() == 1,
               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:853:12: error: stray ‘\200’ in program
       obj->slots().size() == 1,
               ^
/media/pc/data/software/libtorch/include/ATen/core/ivalue_inl.h:853:12: error: stray ‘\200’ in program
       obj->slots().size() == 1,
               ^

2. enviroment:
 libtorch: 1.8.1
 vision: 0.9.1
 cmake: 3.19.6
 gcc: 7.5.0
 python: 3.8.5
 system: Ubuntu 18.04

3. compile code
 cmake -DCMAKE_PREFIX_PATH=/media/pc/data/software/libtorch -DCMAKE_INSTALL_PREFIX=/media/pc/data/software/torchvision/install -DCMAKE_BUILD_TYPE=Release -DWITH_CUDA=ON ..

Thanks~！

**Comment by datumbox** [comment]
@swordnosword It looks like this might be an issue caused by the encoding of characters (see [[1]](https://askubuntu.com/questions/272741/how-to-fix-compilation-errors-that-mention-stray-342-and-stray-200) and [[2]](https://stackoverflow.com/questions/43268151/error-stray-342-stray-200-stray-234-in-c-compiling)).

**Comment by swordnosword** [comment]
@datumbox I just doownloaded the source code and chaged nothing.

**Comment by swordnosword** [comment]
@datumbox I have compiled successfully in docker image with python 3.6.9, it seems like we can solve this problem by lower the python version.
Thanks any way!
