### ISSUE TITLE
Why does RandomErasing transform aspect ratio use log scale

### ISSUE THREAD

**Issue by jxu** [pytorch/vision#3825]
See from https://github.com/pytorch/vision/commit/06a5858b3b73d62351456886f0a9f725fddbb3fe the aspect ratio is chosen randomly from a log scale

I didn't see this in the original paper? And in the reference implementation. 

https://github.com/zhunzhong07/Random-Erasing/blob/c699ae481219334755de93e9c870151f256013e4/transforms.py#L38

**Comment by jxu** [comment]
Mathematically it does make more sense for a log scale. Maybe this implementation difference should be noted

**Comment by datumbox** [comment]
@jxu Hi! Checkout the discussion that happens on PR https://github.com/pytorch/vision/pull/3344 where this was introduced. We ended up updating it after doing experiments and discussing it with one of the original authors.

I'm going to close the issue to keep things clean but please feel free to reopen if you have more questions.

**Comment by jxu** [comment]
Yes I see now, thanks for the response.
