### ISSUE TITLE
Speed regression on keypointrcnn_resnet50_fpn unit-test

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#3829]
There seems to be a significant slowdown on the `keypointrcnn_resnet50_fpn` unit-test on macOS. Currently it's our [slowest test](https://app.circleci.com/pipelines/github/pytorch/vision/8076/workflows/88c81b16-a831-40bc-9ae2-75aa8b2f8fe5/jobs/576520):
```
============================= slowest 20 durations =============================
151.74s call     test/test_models.py::test_detection_model[dev0-keypointrcnn_resnet50_fpn]
```

At the time of raising this ticket, our CI is toasted on macOS so, it's worth confirming the issue after it returns back to greener pastures.

cc @seemethere

**Comment by fmassa** [comment]
Hum, interesting.

My first guess would be that maybe this is due to torchscript now performing fusion on CPU, which was previously disabled by default for CPU and only happened on CUDA

**Comment by datumbox** [comment]
Should not we see the same significant deterioration on the other versions of fasterrcnn?

**Comment by fmassa** [comment]
In principle yes, although there are some different codepaths in keypoint rcnn for the evaluation which might be the culprit there.

But we should check if it's a slowdown due to execution speed (in which case it's pretty bad) or in the torchscript compilation (which is less of an issue I would say)

**Comment by datumbox** [comment]
There is no regression issue on the method. See https://github.com/pytorch/vision/pull/3847#issuecomment-842504468 for detailed findings.
