### ISSUE TITLE
[Feature Request] Adding Descriptions for Dataset objects

### ISSUE THREAD

**Issue by vishwakftw** [pytorch/vision#383]
I would like to propose this feature, taking into account that generally a dataset object returns this:

```python
>>> import torchvision as tv
>>> tv.datasets.<NAME>(root=ROOT_LOCATION)
<torchvision.datasets.<OBJECT_NAME> at <address>
```

I hope that this feature will be able to do this:
```python
>>> tv.datasets.<NAME>(root=ROOT_LOCATION)
Dataset <NAME> 
    Number of datapoints:
    Root location:
    Transforms (if any):
    Target Transforms (if any):
```

Let me know what you think, and I can issue a PR accordingly.

**Comment by soumith** [comment]
looks good to me, go ahead with the PR.

**Comment by alykhantejani** [comment]
seems like a good idea +1 from me
