### ISSUE TITLE
VOCDetection load error: No route to host

### ISSUE THREAD

**Issue by Seonghoon-Yu** [pytorch/vision#3830]
I used torch.utils.datasets.VOCDetection, but there was error message
how can i address this error?

There was no error when I used it a month ago.

train_ds = VOCDetection(path2data, year='2007', image_set='train', download=True)

![image](https://user-images.githubusercontent.com/75726938/118208621-0fefaf80-b4a2-11eb-8ce9-99875d02383d.png)

cc @pmeier

**Comment by datumbox** [comment]
It seems that the [server](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar) that hosts the dataset is unreachable.

**Comment by pmeier** [comment]
The VOC server is pretty unstable and we refrained from testing the download due to regular breakages. @Seonghoon-Yu You will have to try later, since there is nothing we can do about it.

**Comment by Seonghoon-Yu** [comment]
Thanks datumbox, pmeier!
Now, there is nothing to do.
