### ISSUE TITLE
io.read_image returns different tensors for the same image

### ISSUE THREAD

**Issue by zhai-EE** [pytorch/vision#3844]
## 🐛 Bug

torchvision.io.read_image return different tensors for the same greyscale image. 

### The image which causes the error
The greyscale image which causes the error is as following :

![class01](https://user-images.githubusercontent.com/41221813/118388959-fe510800-b659-11eb-8f90-9e45f4ded26b.png)
(Saving this image from here can also reproduce the bug, although It's originally from the [omniglot dataset](https://github.com/brendenlake/omniglot) , under omniglot/python/one-shot-classification/run01/training/class01.png)

### Code
Naming the image as "class01.png" and then running the following code can reproduce the bug.
```
import torchvision

f = "class01.png"
img_1 = torchvision.io.read_image(f)
img_2 = torchvision.io.read_image(f)
diff = img_1 - img_2
print(diff.nonzero(as_tuple=True))
```
### Output:
```
(tensor([0, 0, 0,  ..., 0, 0, 0]), tensor([  0,   0,   0,  ..., 104, 104, 104]), tensor([ 13,  27,  55,  ..., 102, 103, 104]))
```
### Analyzation:
-  `diff ` is not a zero tensor, which implies that img_2 is not same as img_1, but img_1 and img_2 represent the same image.
-  The output of diff.nonzero(as_tuple=True) is random, which cahnges at different runs. This means there is some random mechanism in `torchvision.io.read_image`, which is unexpected.

### Conclusion:
  There is a bug inside `torchvision.io.read_image`, which causes random output when reading an image.
## Expected behavior
To show you what the correct output should be like, I change the above code to the following one:
(Note that`diff=img_1 - img_1`now.)
```
import torchvision

f = "class01.png"
img_1 = torchvision.io.read_image(f)
img_2 = torchvision.io.read_image(f)
diff = img_1 - img_1 #The changed line
print(diff.nonzero(as_tuple=True))
```
It outputs:
```
(tensor([], dtype=torch.int64), tensor([], dtype=torch.int64), tensor([], dtype=torch.int64))
```

## Environment

PyTorch version: 1.8.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 家庭中文版
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.3.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] numpydoc==1.1.0
[pip3] torch==1.8.1
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
[conda] cudatoolkit               10.2.89              h74a9793_1    defaults
[conda] mkl                       2021.2.0           haa95532_296    defaults
[conda] mkl-service               2.3.0            py38h2bbff1b_1    defaults
[conda] mkl_fft                   1.3.0            py38h277e83a_2    defaults
[conda] mkl_random                1.2.1            py38hf11a4ad_2    defaults
[conda] numpy                     1.20.1           py38h34a8a5c_0    defaults
[conda] numpy-base                1.20.1           py38haf7ebc8_0    defaults
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1    defaults
[conda] pytorch                   1.8.1           py3.8_cuda10.2_cudnn7_0    pytorch
[conda] torch                     1.8.1                    pypi_0    pypi
[conda] torchaudio                0.8.1                      py38    pytorch
[conda] torchvision               0.9.1                py38_cu102    pytorch

**Comment by prabhat00155** [comment]
@zhai-EE Thanks for reporting this, I was able to reproduce this on my setup. I'll try to debug it tomorrow.

**Comment by fmassa** [comment]
cc @andfoy who has worked on the PNG reading support, and @datumbox who enhanced it with support for different modes.

This seems like a high-priority issue to get fixed

**Comment by andfoy** [comment]
I'll take a look at it!

**Comment by fmassa** [comment]
@andfoy I believe @prabhat00155 is also looking at it, can you sync with him on Slack?
