### ISSUE TITLE
The headers or library files could not be found for zlib

### ISSUE THREAD

**Issue by gauss-clb** [pytorch/vision#385]
When compiling source code using `sudo python3 setup.py install` on ubuntu16.04, the error occurs.

```python
setuptools.sandbox.UnpickleableException: RequiredDependencyException('The headers or 

library files could not be found for zlib, a required dependency when compiling Pillow from source.

Please see the install instructions at:   https://pillow.readthedocs.io/en/latest/installation.html',)
```

How to fix it?

**Comment by alykhantejani** [comment]
hmm strange. The install of pillow should in turn install zlip. Can you install zlib with `apt-get install zlib` and try again

**Comment by gauss-clb** [comment]
I try to use `pip install torchvision`, it works.

**Comment by Jouy** [comment]
try this . 
https://github.com/python-pillow/Pillow/issues/3438
