### ISSUE TITLE
video datasets (UCF101, Kinetics400) download error (downloading nothing)

### ISSUE THREAD

**Issue by sejongpyo** [pytorch/vision#3854]
I'm trying to get some video datasets. I followed the documentation but  keep getting an error.

`from torchvision.datasets import UCF101
from torchvision.datasets import Kinetics400
ucf_data_dir = "./data"
ucf_label_dir = "./ucfTrainTestlist"

ucf = UCF101(root = ucf_data_dir, annotation_path = ucf_label_dir, frames_per_clip = frames_per_clip,
           step_between_clips = step_between_clips)
kin = Kinetics400(root = ucf_data_dir, frames_per_clip = frames_per_clip,
           step_between_clips = step_between_clips)
`
![image](https://user-images.githubusercontent.com/68941421/118649005-f9d54c80-b81d-11eb-8fb9-55128ee85b4b.png)

How to fix this?

cc @pmeier

**Comment by pmeier** [comment]
Hey @sejongpyo. What exactly do you mean by 

> I'm trying to get some video datasets.

? It seems your iteration does nothing which might be a result of no data available in `ucf_data_dir` and `ucf_label_dir`. How are these directories structured?

**Comment by sejongpyo** [comment]
> Hey @sejongpyo. What exactly do you mean by
> 
> > I'm trying to get some video datasets.
> 
> ? It seems your iteration does nothing which might be a result of no data available in `ucf_data_dir` and `ucf_label_dir`. How are these directories structured?

`ucf_data_dir` is just a empty folder. Isn't the root path meaning that i'm going to save the dataset? And, `ucf_label_dir` has ucfTrainTestlist which consist of .txt files of UCF101 dataset.

**Comment by pmeier** [comment]
> Isn't the root path meaning that i'm going to save the dataset?

Nope. `torchvision.datasets` provides wrappers around datasets so they can be easily used from PyTorch. Most datasets have `download=True` flag in case you don't already have the files locally. Unfortunately neither `UCF101` nor `Kinetics400` support download as of now. For `Kinectis` #3680 will probably land soon and add exactly this. 

You can download the `UCF101` dataset [here](https://www.crcv.ucf.edu/data/UCF101/UCF101.rar). If you want to see this functionality from within `torchvision`, we are happy to accept a PR adding this.

**Comment by sejongpyo** [comment]
> Unfortunately neither `UCF101` nor `Kinetics400` support download as of now. For `Kinectis` #3680 will probably land soon and add exactly this.
> 
> You can download the `UCF101` dataset [here](https://www.crcv.ucf.edu/data/UCF101/UCF101.rar).
Thank you for your help!
