### ISSUE TITLE
Dataset target datatypes vary between Datasets

### ISSUE THREAD

**Issue by Coolnesss** [pytorch/vision#388]
For example, when using `torchvision.datasets.MNIST`, the targets are returned as type `int`:
```python
>>> torchvision.datasets.MNIST('./data', train=True)
<torchvision.datasets.mnist.MNIST object at 0x7feb5af89860>
>>> ds = torchvision.datasets.MNIST('./data', train=True)
>>> ds[0]
(<PIL.Image.Image image mode=L size=28x28 at 0x7FEB5AF89C18>, 5)
>>> type(ds[0][1])
<class 'int'>
```

But when using the SVHN dataset, they are returned as `numpy.int64`:

```python
>>> ds = torchvision.datasets.SVHN('./data', split='train')
>>> ds[0]
(<PIL.Image.Image image mode=RGB size=32x32 at 0x7FEB5AF89C18>, 1)
>>> type(ds[0][1])
<class 'numpy.int64'> 
```

A minor issue, I'm sure, but one nevertheless. This is because it's possible to turn a list of `int` into `torch.LongTensor`, but not `numpy.int64`:

```python
>>> torch.LongTensor([1,2,3])

 1
 2
 3
[torch.LongTensor of size 3]

>>> torch.LongTensor([np.int64(1),np.int64(2)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: tried to construct a tensor from a int sequence, but found an item of type numpy.int64 at index (0)

```

**Comment by vishwakftw** [comment]
For the issue with different datatypes in different datasets, MNIST is a pickled object when downloaded from source, whereas SVHN is stored as a `.mat` file, and uses `scipy.io` to load it. `scipy` uses `numpy` and hence the returned value is of type `numpy.int64`.

**Comment by Coolnesss** [comment]
@vishwakftw You're probably correct, but I still think the torchvision API should be consistent in the returned datatype.

**Comment by alykhantejani** [comment]
we could probably cast the numpy.int64's into regular ints cc @fmassa wdyt?

**Comment by Coolnesss** [comment]
I could draft a PR if you're interested. Could have a look at the other datasets as well, make sure they're consistent.

**Comment by alykhantejani** [comment]
@Coolnesss that'd be great - thanks!

**Comment by Coolnesss** [comment]
@alykhantejani Please have a look at https://github.com/pytorch/vision/pull/389 :)
