### ISSUE TITLE
libtorchvision.so does not exist

### ISSUE THREAD

**Issue by Pnikam** [pytorch/vision#3937]
I am installing C++ API for torchvision.
I got the following error:
set_target_properties Can not find target to add properties to:
  TorchVision::TorchVision

So, I coppied TorchVisionTargets.cmake and TorchVisionTargets-release.cmake from CMakeFiles/Export/Share/cmake/TorchVision to the build folder containing TorchVisionConfig.cmake.

Now I am getting the following error:
CMake Error at /path/libtorch/share/cmake/TorchVision/vision/build/TorchVisionTargets.cmake:70 (message):
The imported target "TorchVision::TorchVision" references the file

     "path/libtorch/share/cmake/lib/libtorchvision.so"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

I am working on a non-GPU machine. Do I need a GPU machine? If not, then how can I resolve this?

**Comment by prabhat00155** [comment]
I assume you were following the steps from [here](https://github.com/pytorch/vision#c-api). Which step is failing? Are you using the latest master?

**Comment by Pnikam** [comment]
I am able to configure torchvision for cake. Actually, i am trying to deploy detectron2 models using torchscript. At that time, while configuring the dependencies, I am getting the above errors for torchvision.

**Comment by prabhat00155** [comment]
@Pnikam Were you able to build(`make install`) torchvision successfully with the steps I pointed above? Could you list down the steps you are using to deploy detectron2 models using torchscript so that I can reproduce the error?
cc @bmanga

**Comment by Pnikam** [comment]
@prabhat00155 Yes, I have built torchvision successfully. Then I tried to configure cmake for detectron2 from cmake-gui and added all the required paths therein. And I got stuck at the above errors.

**Comment by bmanga** [comment]
@Pnikam  can you report the cmake invocation that you use to build detectron2? You need to append the location of your installed torchvision to the CMAKE_PREFIX_PATH variable or set the TORCHVISION_DIR one.

**Comment by Pnikam** [comment]
@bmanga I used the following command for cmake invocation:
cmake -DCMAKE_PREFIX_PATH=/path/libtorch ..
Then I was suggested to add TorchVisionConfig.cmake path, so I entered the following command:
cmake -DTorchVision_DIR=/path/TorchVision/build

**Comment by bmanga** [comment]
Can you try the following steps and report back?
* Configure torchvision also specifying an install directory : `cmake -DCMAKE_INSTALL_PREFIX=/path/to/torchvision/ [...]`
* `make install`
* When configuring detectron2, use: `cmake -DCMAKE_PREFIX_PATH=/path/to/libtorch;/path/to/torchvision [...]`

**Comment by Pnikam** [comment]
- After running : `cmake -DCMAKE_INSTALL_PREFIX=/path/to/torchvision/` , I got following warning:

```
CMake Warning at CMakeLists.txt:73 (add_library):
  Cannot generate a safe runtime search path for target torchvision because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libpng16.so.16] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/admin1/miniconda3/lib

  Some of these libraries may not be found correctly.

```
But generating was done successfully.

- After running `make install `: Built target torchvision successfully

- After running `cmake -DCMAKE_PREFIX_PATH=/path/to/libtorch;/path/to/torchvision` , got following error again:
```CMake Error at /path/to/torchvision/build/TorchVisionConfig.cmake:50 (include):
CMake Error at /path/to/torchvision/build/TorchVisionConfig.cmake:50 (include):

  include could not find load file:

    /path/to/torchvision/build/TorchVisionTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)


CMake Error at /path/to/torchvision/build/TorchVisionConfig.cmake:59 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  TorchVision::TorchVision
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
See also "/path/detectron2/tools/deploy/CMakeFiles/CMakeOutput.log".
See also "/path/detectron2/tools/deploy/CMakeFiles/CMakeError.log".
CMake Error at /path/to/torchvision/build/TorchVisionConfig.cmake:50 (include):
  include could not find load file:

    /path/to/torchvision/build/TorchVisionTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)


CMake Error at /path/to/torchvision/build/TorchVisionConfig.cmake:59 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  TorchVision::TorchVision
Call Stack (most recent call first):
  CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!
See also "/path/detectron2/tools/deploy/CMakeFiles/CMakeOutput.log".
See also "/path/detectron2/tools/deploy/CMakeFiles/CMakeError.log".
```

**Comment by bmanga** [comment]
> CMake Error at /path/to/torchvision/build/TorchVisionConfig.cmake:50 (include):
> 
>   include could not find load file:
> 
>     /path/to/torchvision/build/TorchVisionTargets.cmake

I think the problem could be related to the fact that you seem be using the build directory and not the install directory.

**Comment by Pnikam** [comment]
@bmanga Yes. I was giving wrong path. Solved issue. Thank You.
