### ISSUE TITLE
Batch size of the training recipes on multiple GPUs

### ISSUE THREAD

**Issue by talcs** [pytorch/vision#3938]
## ❓ Questions and Help

In the README file that describes the recipes of training the classification models, under the references directory, it is stated that the models are trained with batch-size=32 on 8 GPUs. 

Does it mean that:
- the whole batch-size is 32 and each GPU gets only 4 images to process at a time?
- OR each GPU gets 32 images to process at a time, meaning that the global batch-size is actually 256?

Thanks.
Tal

**Comment by prabhat00155** [comment]
I would think it's images per gpu. Looking at the [detection example](https://github.com/pytorch/vision/blob/882e11db8138236ce375ea0dc8a53fd91f715a90/references/detection/train.py#L62), it says total batch size is n_gpu x batch_size.
Also, the data loader created in the [classification example](https://github.com/pytorch/vision/blob/882e11db8138236ce375ea0dc8a53fd91f715a90/references/classification/train.py#L151) is set with batch size of 32(or whatever is passed by the user).

**Comment by datumbox** [comment]
As @prabhat00155 correctly said, we define the batch size per GPU to be 32 and since we use 8 GPUs our total batch size is 256. Closing the issue to keep things tidy but feel free ro reopen if you have more questions.
