### ISSUE TITLE
Port test/test_transforms.py to pytest

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#3945]
Currently, most tests in [test/test_transforms.py](https://github.com/pytorch/vision/blob/master/test/test_transforms.py) rely on `unittest.TestCase`. Now that we support `pytest`, we want to remove the use of the `unittest` module.

For a similar issue see https://github.com/pytorch/vision/issues/3956

### Instructions

There are many tests in this file, so I bundled them in multiple related groups below. If you're interested in working on this issue, please comment below with "I'm working on `<group X>`, `<group Y>`, etc..." so that others don't pick the same tests as you do. Feel free to pick as many groups as you wish, but please don't submit more than 2 groups per PR in order to keep the reviews manageable. Before picking a group, make sure it wasn't picked by another contributor first. Thanks!!

### How to port a test to pytest

Porting a test from `unittest` to pytest is usually fairly straightforward. For a typical example, see https://github.com/pytorch/vision/pull/3907/files:

- take the test method out of the  `Tester(unittest.TestCase)` class and just declare it as a function
- Replace `@unittest.skipIf` with `pytest.mark.skipif(cond, reason=...)`
- remove any use of `self.assertXYZ`.
  - Typically `assertEqual(a, b)` can be replaced by `assert a == b` when a and b are pure python objects (scalars, tuples, lists), and otherwise we can rely on `assert_equal` which is already used in the file.
  - `self.assertRaises` should be replaced with the `pytest.raises(Exp, match=...):` context manager, as done in https://github.com/pytorch/vision/pull/3907/files. Same for warnings with `pytest.warns`
  - `self.assertTrue` should be replaced with a plain `assert`
- When a function uses for loops to tests multiple parameter values, one should use`pytest.mark.parametrize` instead, as done e.g. in https://github.com/pytorch/vision/pull/3907/files.
- It may make sense to keep related tests within a single class. For example here, the tests in group A could be grouped into a `TestToPILImage` class, the tests in group N could be in `TestPad`, etc. Not all groups need a dedicated class though, it's on a case-by-case basis.

CC @ShrillShrestha and @zhiqwang in case you're interested in this too :)

-----

### Groups:

- [x] Groups A: https://github.com/pytorch/vision/pull/3959
  - `test_1_channel_ndarray_to_pil_image`
  - `test_1_channel_tensor_to_pil_image`
  - `test_2_channel_ndarray_to_pil_image`
  - `test_2_channel_tensor_to_pil_image`
  - `test_2d_ndarray_to_pil_image`
  - `test_2d_tensor_to_pil_image`
  - `test_3_channel_ndarray_to_pil_image`
  - `test_3_channel_tensor_to_pil_image`
  - `test_4_channel_ndarray_to_pil_image`
  - `test_4_channel_tensor_to_pil_image`
  - `test_ndarray_bad_types_to_pil_image`
  - `test_tensor_bad_types_to_pil_image`
- [x] Group B  https://github.com/pytorch/vision/pull/3985
  - `test_accimage_crop`
  - `test_accimage_pil_to_tensor`
  - `test_accimage_resize`
  - `test_accimage_to_tensor`

- [x] Group C  https://github.com/pytorch/vision/pull/3984
  - `test_affine`
  - `test_random_affine`

- [x] Group D https://github.com/pytorch/vision/pull/3981
  - `test_autoaugment`
  - `test_center_crop`
  - `test_center_crop_2`
  - `test_color_jitter`

- [X] Group E https://github.com/pytorch/vision/pull/4026
  - `test_convert_image_dtype_float_to_float`
  - `test_convert_image_dtype_float_to_int`
  - `test_convert_image_dtype_int_to_float`
  - `test_convert_image_dtype_int_to_int`
  - `test_convert_image_dtype_int_to_int_consistency`

- [X] Group F https://github.com/pytorch/vision/pull/3966
  - `test_pil_to_tensor`
  - `test_to_tensor`
  - `test_to_tensor_with_other_default_dtypes`

- [x] Group G https://github.com/pytorch/vision/pull/3981
  - `test_five_crop`
  - `test_ten_crop`
  - `test_max_value`
  - `test_linear_transformation`

- [X] Group H https://github.com/pytorch/vision/pull/3964
  - `test_random_apply`
  - `test_random_choice`
  - `test_random_order`

- [x] Group I https://github.com/pytorch/vision/pull/3972
  - `test_random_crop`
  - `test_random_erasing`
  - `test_random_rotation`
  - `test_randomperspective`
  - `test_randomperspective_fill`

- [X] Group J #3952
  - `test_randomresized_params`
  - `test_resize`

- [X] Group K https://github.com/pytorch/vision/pull/3957
  - `test_rotate`
  - `test_rotate_fill`
  - `test_gaussian_blur_asserts`
  - `test_lambda`

- [X] Group L https://github.com/pytorch/vision/pull/3971
  - `test_random_horizontal_flip`
  - `test_random_vertical_flip`
  - `test_normalize`
  - `test_normalize_3d_tensor`
  - `test_normalize_different_dtype`

- [X] Group M  https://github.com/pytorch/vision/pull/3962
  - `test_to_grayscale`
  - `test_random_grayscale`

- [x] Group N #3954
  - `test_pad`
  - `test_pad_raises_with_invalid_pad_sequence_len`
  - `test_pad_with_mode_F_images`
  - `test_pad_with_non_constant_padding_modes`
  - `test_pad_with_tuple_of_pad_values`

- [X] Group O  https://github.com/pytorch/vision/pull/3955
  - `test_random_invert`
  - `test_random_posterize`
  - `test_random_solarize`
  - `test_random_adjust_sharpness`
  - `test_random_autocontrast`
  - `test_random_equalize`

- [x] Group P  #3950
  - `test_adjust_brightness`
  - `test_adjust_contrast`
  - `test_adjust_gamma`
  - `test_adjust_hue`
  - `test_adjust_saturation`
  - `test_adjust_sharpness`
  - `test_adjusts_L_mode`

cc @pmeier

**Comment by saswatpp** [comment]
I am working on group P. 
I'll try to send PR soon. :)

**Comment by ShrillShrestha** [comment]
Thanks for mentioning @NicolasHug. I will try working on Group O.

**Comment by zhiqwang** [comment]
Thanks for mentioning @NicolasHug :) I will try working on Group A.

**Comment by AnirudhDagar** [comment]
Hi @NicolasHug, I'd like to work on Group I and J.
I'll try to send a PR soon!

**Comment by pmeier** [comment]
@NicolasHug I can help review. Just ping me.

**Comment by Dbhasin1** [comment]
hi @NicolasHug, I'll try working on Group N

**Comment by DevPranjal** [comment]
Hey @NicolasHug, I will try working on Group F.

**Comment by sahilg06** [comment]
Hi @NicolasHug, I will try working on Group K.

**Comment by artifiitr** [comment]
Hi @NicolasHug, I will try working on Group E.

**Comment by harishsdev** [comment]
For b,c,d,g groups i will raise PR

**Comment by NicolasHug** [comment]
Thanks @harishsdev! please make sure to submit at most 2 groups per PR to keep the review  manageable :)

**Comment by Ishan-Kumar2** [comment]
Hi @NicolasHug, I will try working on Group M.

**Comment by sahilg06** [comment]
@NicolasHug  in function **test_rotate_fill** Do I need to parameterize any variable as there are 2 for loops but 1 is dependent on the other. Please guide.

**Comment by NicolasHug** [comment]
Ah, I wish we could have covariant parametrization! This is a common struggle.
In the case of `test_rotate_fill` parametrizing only over `modes` should be good enough!

**Comment by NicolasHug** [comment]
Seems like most groups have been taken already, thanks everyone for your interest! I've created another similar issue for those who are interested: https://github.com/pytorch/vision/issues/3956

**Comment by sahilg06** [comment]
@NicolasHug but 2nd for loop requires list of nums_bands which depends upon modes list. So we have to define modes list inside the function even if we do parametrization. So is that okay?

**Comment by NicolasHug** [comment]
Ah I missed that.

If I understand the logic correctly here, we should be able to remove this last for loop and just hardcode `wrong_num_bands` to `num_bands + 1`.

Basically, `set(nums_bands) - {num_bands}` is always 1 when num_bands is 3 and always 3 when num_bands is 1.
What's important is that `wrong_num_bands` is different from `num_bands`, I don't think we really care about the **exact** value.

**Comment by harishsdev** [comment]
PR Raised for 

Group B

test_accimage_crop
test_accimage_pil_to_tensor
test_accimage_resize
test_accimage_to_tensor
 Group C

test_affine
test_random_affine

**Comment by vivekkumar7089** [comment]
Hi, @NicolasHug  I'd like to work on Group H.
I'll try to send a PR soon!!

**Comment by vivekkumar7089** [comment]
Hi, @NicolasHug  I'd like to work on Group L.
I'll try to send a PR soon!!

**Comment by harishsdev** [comment]
Hi all,I am working only on Group G,Group D

please take initiate to raise PR for Group B,Group C

**Comment by AnirudhDagar** [comment]
@harishsdev no worries, I can send in a PR if you are not working on them anymore.

**Comment by Ishan-Kumar2** [comment]
Hi @AnirudhDagar are you working on both B and C? I can help with one.

**Comment by AnirudhDagar** [comment]
Sure @Ishan-Kumar2! I was about to start with B, but let me know the one you prefer. I'll take the other. :))

**Comment by Ishan-Kumar2** [comment]
Okay @AnirudhDagar you can continue with B, I'll try C.

**Comment by NicolasHug** [comment]
All done! Thank you so much everyone for your help!!
