### ISSUE TITLE
Port test/test_functional_tensor.py to pytest

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#3956]
Currently, most tests in [test/test_functional_tensor.py](https://github.com/pytorch/vision/blob/master/test/test_functional_tensor.py) rely on `unittest.TestCase`. Now that we support `pytest`, we want to remove the use of the `unittest` module.

### Instructions

There are many tests in this file, so I bundled them in multiple related groups below. If you're interested in working on this issue, please comment below with "I'm working on `<group X>`, `<group Y>`, etc..." so that others don't pick the same tests as you do. Feel free to pick as many groups as you wish, but please don't submit more than 2 groups per PR in order to keep the reviews manageable. Before picking a group, make sure it wasn't picked by another contributor first. Thanks!!

### How to port a test to pytest

Porting a test from `unittest` to pytest is usually fairly straightforward. For a typical example, see https://github.com/pytorch/vision/pull/3907/files:

- take the test method out of the  `Tester(unittest.TestCase)` class and just declare it as a function
- Replace `@unittest.skipIf` with `pytest.mark.skipif(cond, reason=...)`
- remove any use of `self.assertXYZ`.
  - Typically `assertEqual(a, b)` can be replaced by `assert a == b` when a and b are pure python objects (scalars, tuples, lists), and otherwise we can rely on `assert_equal` which is already used in the file.
  - `self.assertRaises` should be replaced with the `pytest.raises(Exp, match=...):` context manager, as done in https://github.com/pytorch/vision/pull/3907/files. Same for warnings with `pytest.warns`
  - `self.assertTrue` should be replaced with a plain `assert`
- When a function uses for loops to tests multiple parameter values, one should use`pytest.mark.parametrize` instead, as done e.g. in https://github.com/pytorch/vision/pull/3907/files.
- It may make sense to keep related tests within a single class. For example here, the tests in group A could be grouped into a `TestToPILImage` class, the tests in group N could be in `TestPad`, etc. Not all groups need a dedicated class though, it's on a case-by-case basis.
- **Important**: a lot of these tests rely on `self.device` because they need to be run on both CPU and GPU. For these, use the `cpu_and_gpu()` from `common_utils` instead, e.g.:

https://github.com/pytorch/vision/blob/f7b4cb0438702f67cf71cdd7dd8057fc377fb816/test/test_functional_tensor.py#L845-L846

and you can just replace `self.device` by `device` in the test

CC @saswatpp as promised!

----

- [X] Group A https://github.com/pytorch/vision/pull/3977
  - `test_assert_image_tensor`  - parametrize over (func, arg)
  - `test_vflip`
  - `test_hflip`
  - `test_crop`  -- parametrize over test_configs

(EDIT: oops, I initially named both groups below `Group B`. Renamed into B1 and B2)

- [x] Group B1
  - `test_hsv2rgb`
  - `test_rgb2hsv`
  - `test_rgb_to_grayscale`  -- parametrize over num_output_channels
  - `test_center_crop`
  - `test_five_crop`
  - `test_ten_crop`

- [x] Group B2 https://github.com/pytorch/vision/pull/3974
  - `test_pad` -- parametrize over dt, pad configs
  - `test_resized_crop`

- [x] Group C https://github.com/pytorch/vision/pull/3974
  This one might be a bit tricky. It will require some parametrization, and we should probably split each sub-method like `_test_affine_all_ops`, `_test_affine_rect_rotations` etc. into a single test function (or method, if you decide to bundle them into a `TestAffine` class, which would probably make sense).
  - `test_affine`

- [x] Group D https://github.com/pytorch/vision/pull/3983
  Parametrize over data, dt, a, e, f, (and maybe c if there's no issue)
  We should split this test into multiple one, for example the `self.assertWarnsRegex` should be in a separate test
  - `test_rotate`

- [X] Group E https://github.com/pytorch/vision/pull/3977
   parametrize over tensor, dt, ksize, sigma
  - `test_gaussian_blur` 

cc @pmeier @vfdev-5

**Comment by saswatpp** [comment]
Thank you @NicolasHug ! I will try to add a PR for Group B and C.

**Comment by sahilg06** [comment]
@NicolasHug, I will try working on group  A and E

**Comment by zhiqwang** [comment]
@NicolasHug, I will try working on Group D.

**Comment by sahilg06** [comment]
Hi @NicolasHug, in the function **test_gaussian_blur** in group E, tensor depends upon **small image tensor** and **large** **image tensor** and the depend upon the **device**. So How to parameterize tensor because I have to parameterize device also? please guide!

and 1 more question
which is the better way to parameterize
1)`test_configs = [
            (1, 2, 4, 5),   # crop inside top-left corner
            (2, 12, 3, 4),  # crop inside top-right corner
            (8, 3, 5, 6),   # crop inside bottom-left corner
            (8, 11, 4, 3),  # crop inside bottom-right corner
        ]
@pytest.mark.parametrize('top,left,height,width', test_configs)`


2) `@pytest.mark.parametrize('top,left,height,width', [
            (1, 2, 4, 5),   # crop inside top-left corner
            (2, 12, 3, 4),  # crop inside top-right corner
            (8, 3, 5, 6),   # crop inside bottom-left corner
            (8, 11, 4, 3),  # crop inside bottom-right corner
        ])`

**Comment by NicolasHug** [comment]
> So How to parameterize tensor because I have to parameterize device also? please guide!

We can probably parametrize over a new `image_size` parameter, like so:

```py
@parametrize('image_size', ('small', 'large'))
def test_gaussian_blur(image_size, ...):
    if image_size == 'small':
        tensor = torch.from_numpy(
            np.arange(3 * 10 * 12, dtype="uint8").reshape((10, 12, 3))
        ).permute(2, 0, 1).to(device)
    else:
        tensor = torch.from_numpy(
            np.arange(26 * 28, dtype="uint8").reshape((1, 26, 28))
        ).to(device)
```
>  which is the better way to parameterize

I prefer the second way, unless `test_configs` can/should be re-used somewhere else.

**Comment by saswatpp** [comment]
@NicolasHug in Group C you mentioned that we should 'split' the sub-method into a 'single' function. I couldn't understand what you meant by that. And Since you have Split B into B1 and B2, let me take only B2 and someone in the community can take over B1.

**Comment by NicolasHug** [comment]
Sorry if that's not clear, basically I mean that instead of having a single function `test_affine` as is the case right now, we should have multiple test functions like `test_affine_all_ops`, `test_affine_rect_rotations`, etc.

**Comment by sahilg06** [comment]
@NicolasHug this code is giving me error
```
with pytest.raises(Exception) as context:
        func(tensor, *args)

    assert 'Tensor is not a torch image.' in str(context.exception)
```
[
<img width="862" alt="Screenshot 2021-06-05 at 21 03 02" src="https://user-images.githubusercontent.com/59660566/120896961-85821200-c641-11eb-8a6b-f5a08da33a07.png">
](URL)

also I tried to write str(context) instead of str(context.exception) it followed with other errors

<img width="1439" alt="Screenshot 2021-06-05 at 21 06 21" src="https://user-images.githubusercontent.com/59660566/120897033-e7db1280-c641-11eb-9cfd-05bd18d48508.png">
<img width="1424" alt="Screenshot 2021-06-05 at 21 05 59" src="https://user-images.githubusercontent.com/59660566/120897034-ead60300-c641-11eb-9312-8c9e2597ac31.png">

**Comment by NicolasHug** [comment]
I think you can just convert this into

```py
with pytest.raises(Exception, match='Tensor is not a torch image'):
        func(tensor, *args)
```

**Comment by sahilg06** [comment]
it is still giving the last 2 error for function five_crop() and center_crop(). actually some exception of positional arguments is occurring in these two functions which is not matching to "Tensor is not a torch image" 
<img width="1233" alt="Screenshot 2021-06-05 at 21 38 15" src="https://user-images.githubusercontent.com/59660566/120897954-65a11d00-c646-11eb-8a5c-2b85e8592a0d.png">

**Comment by NicolasHug** [comment]
Could you please submit a PR? It will be easier to see what's going on

**Comment by harishsdev** [comment]
@NicolasHug  I am working on B1

**Comment by NicolasHug** [comment]
Thanks a lot for your interest @harishsdev but before working on B1, I would kindly ask that we first finish your work in https://github.com/pytorch/vision/pull/3975 as you're already working on 4 different groups. The CI is still failing there as the tests seem to loop indefinitely. As I already asked, please a) split the PR into 2 PRs and b) run the tests locally to avoid such issues. Don't hesitate to ask for specific help. Thanks!

**Comment by vivekkumar7089** [comment]
@NicolasHug , I wanted to work on the port for group B1. @harishsdev ,  if it is fine with you :)

**Comment by harishsdev** [comment]
@vivekkumar7089 please continue with B1

**Comment by NicolasHug** [comment]
Looks like we're done with this file, thank you so much everyone for your help!!
I'll close this issue, for those who are interested I opened a similar issue in https://github.com/pytorch/vision/issues/3987
