### ISSUE TITLE
division by zero in make_grid

### ISSUE THREAD

**Issue by sniklaus** [pytorch/vision#397]
I occasionally see a division by zero from the following line.

https://github.com/pytorch/vision/blob/704404928d7ec610add4ea40f36bb1e74f899d91/torchvision/utils.py#L55

This is actually not surprising since `min` can be equal to `max` if all values are the same. However, what is surprising that it only seems to happen with CUDA tensors.

``` python
torchvision.utils.make_grid(tensor=torch.zeros(2, 3, 4, 4), normalize=True) # works
torchvision.utils.make_grid(tensor=torch.zeros(2, 3, 4, 4).cuda(), normalize=True) # fails
```

Are divisions by zero handled differently depending on whether or not the tensor is a CUDA tensor? Thanks!

**Comment by sniklaus** [comment]
I just noticed hat while the non-CUDA version does not throw an exception, it ends up having `nan` in the result.

**Comment by sniklaus** [comment]
Thank you!

**Comment by fmassa** [comment]
Thanks for reporting the issue!
