### ISSUE TITLE
cannot import module torchvision.transforms.TenCrop

### ISSUE THREAD

**Issue by jiqiujia** [pytorch/vision#398]
I use python2 and torchvision=0.2.0

**Comment by AkhilPunia** [comment]
Same problem here. I beleive they have renamed it now. Similar problem with .Resize earlier it was .Scale

**Comment by fmassa** [comment]
That is weird, `TenCrop` is present in torchvision 0.2.0, and has not been renamed. Can you verify that you are indeed using `torchvision` 0.2.0 by printing `torchvision.__version__`?

**Comment by jiqiujia** [comment]
I think it's weird too. I change to python3.5 and now it's ok. For python2, one computer work while another doesn't. I really use torchvision of 0.2.0

**Comment by jiqiujia** [comment]
It's ok now. I just found I use 0.1.9 actually. Sorry for wasting your time.
