### ISSUE TITLE
It seems that transforming PIL.Image to tensor by transforms.ToTensor is not working correctly?

### ISSUE THREAD

**Issue by kresle** [pytorch/vision#399]
I had problems when using transforms.ToTensor() to a float PIL Image.
And then I checked the codes, which are:
```
    # handle PIL Image
    if pic.mode == 'I':
        img = torch.from_numpy(np.array(pic, np.int32, copy=False))
    elif pic.mode == 'I;16':
        img = torch.from_numpy(np.array(pic, np.int16, copy=False))
    else:
        img = torch.ByteTensor(torch.ByteStorage.from_buffer(pic.tobytes()))
    # PIL image mode: 1, L, P, I, F, RGB, YCbCr, RGBA, CMYK
    if pic.mode == 'YCbCr':
        nchannel = 3
    elif pic.mode == 'I;16':
        nchannel = 1
    else:
        nchannel = len(pic.mode)
    img = img.view(pic.size[1], pic.size[0], nchannel)
```
In the float mode, 4 bytes are required for each pixel. Thus the buffer would return a bytes array whose size is HxWxCx4.
The code `img = img.view(pic.size[1], pic.size[0], nchannel)` should be only capable of handling the HxWxC size.

It is right?

**Comment by fmassa** [comment]
Yes, seems that you are right.
I've sent a fix in https://github.com/pytorch/vision/commit/9b526dbc8adb091b4c588ef1599f7c3f2e040cdc , thanks for opening the issue!
