### ISSUE TITLE
Documentation is not being built for tags

### ISSUE THREAD

**Issue by mattip** [pytorch/vision#3997]
## 🐛 Bug

The circleci build workflow for tags should be building and pushing a version of the documentation, but is not. Compare this [nightly build](https://app.circleci.com/pipelines/github/pytorch/vision/8598/workflows/3778280a-74a5-457a-b355-794095e70cf4) which has build_docs and upload_docs steps, to this [tag build]( https://app.circleci.com/pipelines/github/pytorch/vision/8532/workflows/c8ca8bb0-76df-423f-8ac3-76f0b8e6dab6) which only has `binary_win*` builds.

I think the problem is in the `regereate.py` script where it only adds a `master` filter for windows, which triggers a `tag` filter as well:
https://github.com/pytorch/vision/blob/0013d9314cf1bd83eaf38c3ac6e0e9342fa99683/.circleci/regenerate.py#L40-L50

So the only builds that get the `tag` filter are the windows ones.

This is the same script for text and audio as well, so whatever fix is done here should be done for them as well.

**Comment by mthrok** [comment]
Hi @mattip

Thanks for raising this. BTW, after the fix, do we still need to manually update the version selector?

**Comment by mattip** [comment]
> do we still need to manually update the version selector?

Yes.

**Comment by mattip** [comment]
Docs are now being built. There are still some quirks: see #4754
