### ISSUE TITLE
Unable to build torchvision on Windows (installed torch from source and it is running)

### ISSUE THREAD

**Issue by thesigmaguy** [pytorch/vision#4001]
## ❓ Questions and Help

I have installed torch successfully in my PC via source, but I am facing this issue while installing the torchvison. I don't think I can install torchvision via pip as it is re-downloading the torch.

Please help me to install it

TIA
i used `python setup.py install`
```
Building wheel torchvision-0.9.0a0+01dfa8e
PNG found: True
Running build on conda-build: False
Running build on conda: True
JPEG found: True
Building torchvision with JPEG image support
FFmpeg found: True
Traceback (most recent call last):
  File "C:\Users\dhawals\repos\build_binaries\vision\setup.py", line 472, in <module>
    ext_modules=get_extensions(),
  File "C:\Users\dhawals\repos\build_binaries\vision\setup.py", line 352, in get_extensions
    platform_tag = subprocess.run(
  File "C:\Users\dhawals\miniconda3\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\dhawals\miniconda3\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\dhawals\miniconda3\lib\subprocess.py", line 1356, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\dhawals\miniconda3\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\dhawals\miniconda3\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by datumbox** [comment]
@thesigmaguy This is the error that you get if the gcc compiler is not found in the following line:
https://github.com/pytorch/vision/blob/f87ce881e84388daf30905732f8286b8f49e9001/setup.py#L365

I would recommend confirming that the gcc compiler is installed on your system. If not you could install it via conda. For more info on how to install TorchVision from source have a look on our [guide](https://github.com/pytorch/vision/blob/master/CONTRIBUTING.md).

I'll close the ticket to keep things tidy but feel free to reopen if you face more issues.

**Comment by thesigmaguy** [comment]
But gcc is for Linux based systems. I am using MSVC Windows system. How can I solve that?

**Comment by datumbox** [comment]
@andfoy Do you happen to know if the project can be compiled with ffmpeg support on Windows using a gcc setup [like this](https://stackoverflow.com/a/52879565)? Our CI does not currently supports it but I wonder if you have tried it. 

@thesigmaguy Is it crucial for you to have ffmpeg support? If not you can try disabling it by overwriting the following var to false: 
https://github.com/pytorch/vision/blob/f87ce881e84388daf30905732f8286b8f49e9001/setup.py#L348

**Comment by thesigmaguy** [comment]
I installed mingw (I don't have Ninja installed, I don't see it as requirement). Still there is a strange error I see without much detail.
```
C:\Users\dhawals\repos\build_binaries\vision\torchvision\csrc\io\image\cpu\encode_jpeg.cpp(77): error C2664: 'void jpeg_mem_dest(j_compress_ptr,unsigned char **,size_t *)': cannot convert argument 3 from 'unsigned long *' to 'size_t *'
C:\Users\dhawals\repos\build_binaries\vision\torchvision\csrc\io\image\cpu\encode_jpeg.cpp(77): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
C:\Users\dhawals\miniconda3\Library\include\jpeglib.h(979): note: see declaration of 'jpeg_mem_dest'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

I checked the commit log and found that size_t can be fixed via `git checkout 851b623` Also my conda env already had the jpeg installed strangely. I uninstalled it. then ran a clean setup and install.

It worked.

Though the checkout was to may 7th, torchvision version installed on mine seem to be `0.10.axxxx` Will it cause any issues?

**Comment by datumbox** [comment]
Awesome, thanks for confirming.

The `size_t` is an unrelated headache as you said. You can read more about it here https://github.com/pytorch/vision/pull/3777#issuecomment-832656199. The fix that you quoted is a workaround and we still look for a better fix.

The version should not be an issue. Just make sure you pull the latest master and install the pytorch from nightly as described in our contribution guide.

**Comment by andfoy** [comment]
I don't know if we should setup a CI that runs a build using MinGW and not MSVC?

**Comment by fmassa** [comment]
@andfoy PyTorch only builds CI with MSVC, so we should probably keep MSVC as well.

I think we might have some parts in our setup.py for video which might not work well on Windows, we should double-check that
