### ISSUE TITLE
Our CUDA tests don't run on CircleCI Windows

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#4006]
The Windows GPU unittest workflows don't support cuda.

This can be seen in https://github.com/pytorch/vision/pull/4005 where the `unittest_windows_gpu_py3.8` workflow indicates that `torch.cuda.is_available()` returns False: https://app.circleci.com/pipelines/github/pytorch/vision/8793/workflows/0d3c21ce-7657-4388-b637-7361f318c441/jobs/638628

SSH-ing into one of those machines shows that the driver is too old:

```
python -c "import torch; print(torch.cuda.is_available())"
False
C:\Users\circleci\project\env\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 10010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:115.)
  return torch._C._cuda_getDeviceCount() > 0
```

@fmassa, who to ping for this? I suspect that all the other domains CI will be affected (EDIT: [yes](https://app.circleci.com/pipelines/github/pytorch/audio/6259/workflows/581f28d9-c15c-4e7c-8354-5a83b5455401/jobs/231534)), and possibly those of pytorch?

cc @seemethere

**Comment by fmassa** [comment]
cc @malfet @seemethere could anyone in your team recommend the best way forward with re-enabling those Windows CUDA tests?

**Comment by malfet** [comment]
@fmassa, you simply need to install latest driver before running the tests, by calling something similar to
https://github.com/pytorch/pytorch/blob/master/.circleci/scripts/windows_cuda_install.sh
Since CUDA drivers are backward compatible it's OK to download say 11.3 and only install `Display.Driver` component of it
