### ISSUE TITLE
python_type_check CI is broken: missing stubs for requests module

### ISSUE THREAD

**Issue by AnirudhDagar** [pytorch/vision#4009]
## 🐛 Bug

The `python_type_check` CI is failing since mypy can't find library stubs for requests module used [here](https://github.com/pytorch/vision/blob/befbe1b372e7c028a7b4cb2155110fbae708038e/torchvision/datasets/utils.py#L204) .
This can be seen in the [failed tests](https://app.circleci.com/pipelines/github/pytorch/vision/8800/workflows/971b988a-2245-4aa7-acdf-97af0a38afe2/jobs/639205) for the recent [commit](https://github.com/pytorch/vision/commit/e4c56081ded40403bc3b53ff73ed819d6a46f33e) by @prabhat00155 (although those changes are completely unrelated to this) and on some other PRs like #4008 (edit: and #4010) 

## Pitch
A simple fix would be to install them with `python3 -m pip install types-requests` or to avoid something like this happening later we should just run `mypy --install-types` to install all the missing stubs.

**Comment by AnirudhDagar** [comment]
After digging up a bit more, I found that this sudden appearance due to the [mypy 0.900](https://github.com/python/mypy/releases/tag/v0.900) release today.

According to the docs:
> Starting in mypy 0.900, most third-party package stubs must be installed explicitly. This decouples mypy and stub versioning, allowing stubs to updated without updating mypy. This also allows stubs not originally included with mypy to be installed. Earlier mypy versions included a fixed set of stubs for third-party packages.

cc @NicolasHug @pmeier

**Comment by NicolasHug** [comment]
reopening as #4011 is just a quick band aid

**Comment by AnirudhDagar** [comment]
Should I go ahead with a PR for this one @NicolasHug?

**Comment by NicolasHug** [comment]
yes @AnirudhDagar , thanks!

**Comment by AnirudhDagar** [comment]
Closing this now, fixed with #4014.
