### ISSUE TITLE
Error with hashlibmd5() on FIPS Compliant Systems

### ISSUE THREAD

**Issue by ahamedt** [pytorch/vision#4057]
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

I am working with the CIFAR10 dataset and when I try to utilize torchvision.datasets.CIFAR10 to download the dataset (and then make a data loader for it after), I get a ValueError: [digital envelop routines: EVP_DigestInit_ex] disabled for fips. I have been told that the main issue lies in the fact that the routine for calling the dataset to download also called the method hashlib.md5(), which raises an error on FIPS compliant systems (which is what I'm required to work on). Is there any way to remedy this issue? 

## Code example

import torch
import torchvision
from torchvision import datasets, transforms
transform= transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))])
batch_size=4
train_dataset = datasets.CIFAR10(root='./data', train=True, download=True, transform = transform)
trainloader = torch.utils.data.Dataloader(train_dataset, batch_size = batch_size, shuffle=True, num_workers=2)

Stack Trace:
Note this is an abridged version of the stack trace:

train_dataset = datasets.CIFAR10(root='./data', train=True, download=True, transform = transform)
File <otherpathstuff>/torchvision/datasets/cifar.py line 65 in __init__: self.download()
File <otherpathstuff>/torchvision/datasets/cifar.py line140 in download : if self._check_integrity()
File <otherpathstuff>/torchvision/datasets/cifar.py line 135 in _check_integrity: if not check_integrity(fpath,md5(
File <otherpathstuff>/torchvision/datasets/utils.py in line 67 in check_integrity: return  check_md5(fpath,md5)
File <otherpathstuff>/torchvision/datasets/utils.py in line 59 in check_md5: return md5 == calculate_md5(fpath, **kwargs)
File <otherpathstuff>/torchvision/datasets/utils.py in line 51 in calculate_md5: md5 = hashlib.md5()
ValueError: [digital envelop routines: EVP_DigestInit_ex] disabled for fips

## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
Pytorch
- How you installed PyTorch (conda, pip, source):
pip 
- Build command you used (if compiling from source):N/A
- OS: Linux 
- PyTorch version: 1.8.1
- Python version: 3.8.6
- CUDA/cuDNN version: N/A
- GPU models and configuration: N/A
- GCC version (if compiling from source):N/A
- CMake version:2.8.12.2
- Versions of any other relevant libraries:

cc @fmassa @vfdev-5 @pmeier

**Comment by pmeier** [comment]
Hey @ahamedt, unfortunately there is no official way around this. If the resource has a checksum attached

https://github.com/pytorch/vision/blob/5d93a87f5799e720240a5eab7f3b2424dbabad11/torchvision/datasets/cifar.py#L32

we will always check it after the download for security reasons

https://github.com/pytorch/vision/blob/5d93a87f5799e720240a5eab7f3b2424dbabad11/torchvision/datasets/cifar.py#L143

---

We are currently in the process of designing a new dataset API which should make this easier in the future. In the mean time I suggest you use this workaround:

```python
import unittest.mock

from torchvision import datasets

with unittest.mock.patch("torchvision.datasets.utils.check_md5", return_value=True):
    dataset = datasets.CIFAR10(..., download=True)
```

and then use whatever data loader you want to use. Note that this will now accept any file with the correct file name regardless of the checksum. Thus, you are now responsible for manually checking if everything is in order before you use this snippet.
