### ISSUE TITLE
Bug report: changing .utils to .hub

### ISSUE THREAD

**Issue by AndreasHNielsen** [pytorch/vision#4069]
Hi
I was looking at the code from the pretrained models of Resnets.
https://pytorch.org/vision/stable/_modules/torchvision/models/resnet.html
I came across the package loading, importing the load_state_dict_from_url from **.utils**. I believe this should be **.hub**

Documentation below:
https://pytorch.org/docs/stable/_modules/torch/hub.html#load_state_dict_from_url

This might just be a simple case of not updating the code

cc @brianjo @mruberry @ailzhang @fmassa @vfdev-5 @pmeier @ezyang

**Comment by NicolasHug** [comment]
Thanks for the report @AndreasHNielsen . From https://github.com/pytorch/vision/pull/4070#pullrequestreview-684837690:

> we rely on the .utils file internally so that we can replace load_state_dict_from_url with a custom implementation that works on our internal system.

Since we can't really import from `hub` directly, I'll close the issue
