### ISSUE TITLE
transforms.ToPILImage(): pic should be Tensor or ndarray

### ISSUE THREAD

**Issue by dshahrokhian** [pytorch/vision#408]
I am trying to convert a torch.FloatTensor, representing a 8-bit greyscale, to a PIL image (I am fairly new to pytorch). Whenever I do this, I get the following error:

````
pic should be Tensor or ndarray. Got <class 'torch.FloatTensor'>
````

I don't understand why is this an issue, since FloatTensor is a type of Tensor.

Best,
Dani

**Comment by alykhantejani** [comment]
Hi @dshahrokhian, 

All images in torchvision have to be represented as 3-dimensional tensors of the form [Channel, Height, Width]. I'm guessing your float tensor is a 2d tensor (height x width). For example, this works:

```python
import torch
import torchvision.transforms.functional as F
a = torch.FloatTensor(1, height, width)
a = F.to_pil_image(a)
```

(i.e. yours needs to be a [1, Height, Width] shaped tensor).

Although this error message sucks, I will open a ticket to improve that

**Comment by alykhantejani** [comment]
Issue opened in #409

**Comment by CalinTimbusLucian** [comment]
Hello.
While implementing a CustomDataset, I realised I was getting this error because in the transform list, Transform.ToTensor() was the first. Make sure that other transformations(such as rescale) are done on the PIL image, not on the tensor(you do this by setting the ToTensor() transformations the last in the transformations list).

**Comment by fmassa** [comment]
@CalinTimbusLucian yes, [in the documentation](https://pytorch.org/docs/stable/torchvision/transforms.html) we split the transforms in those that operate on `Tensors` and those that operate on `PIL Image`, and `Rescale` is one that operates on `PIL Image`.

**Comment by praateekmahajan** [comment]
Similarly have this

> TypeError: pic should be Tensor or ndarray. Got <class 'numpy.ndarray'>.

**Comment by JupiLogy** [comment]
> 
> 
> Similarly have this
> 
> > TypeError: pic should be Tensor or ndarray. Got <class 'numpy.ndarray'>.

Making the ndarray a 3d array allows it to be transformed, and then we can turn that back to a 2d tensor after the transform. A suggestion:
```
temp_array = np.zeros(np.append(np.asarray((1)), np.shape(my_array)))
temp_array[0] = my_array
temp_tensor = torchvision.transforms.ToTensor()(temp_array)
my_tensor = temp_tensor[0]
```

**Comment by SatyamGaba** [comment]
> Hello.
> While implementing a CustomDataset, I realised I was getting this error because in the transform list, Transform.ToTensor() was the first. Make sure that other transformations(such as rescale) are done on the PIL image, not on the tensor(you do this by setting the ToTensor() transformations the last in the transformations list).

Can we use ToPILImage(object) as the first transformation in a custom dataloader?
