### ISSUE TITLE
Unnecessary call .clone() in box_convert function

### ISSUE THREAD

**Issue by developer0hye** [pytorch/vision#4091]
https://github.com/pytorch/vision/blob/d391a0e992a35d7fb01e11110e2ccf8e445ad8a0/torchvision/ops/boxes.py#L183-L184

We can just return boxes without .clone().

What's this purpose?

**Comment by tflahaul** [comment]
Pretty sure it's a choice of design as `box_convert` (and many other functions) are not meant to be inplace and should therefore always return a new tensor. Worth checking though.

**Comment by NicolasHug** [comment]
Thanks for the report @developer0hye . Indeed this is by design, as noted by @tflahaul and in the PR, we always copy the boxes to avoid surprises and to have a consistent interface.

**Comment by developer0hye** [comment]
@tflahaul  @NicolasHug 

Thanks for your review!
