### ISSUE TITLE
whats diff in this code ```try....except```

### ISSUE THREAD

**Issue by jaffe-fly** [pytorch/vision#4104]
https://github.com/pytorch/vision/blob/d1ab583d0d2df73208e2fc9c4d3a84e969c69b70/torchvision/_internally_replaced_utils.py#L13

![image](https://user-images.githubusercontent.com/49515380/123214308-a24f8e00-d4f9-11eb-90fc-6deddf8e3926.png)

except code also use torch.hub,its same as try code!!!

why do like this?

**Comment by oke-aditya** [comment]
I think this because of internal FB usage of torchvision.
Have a look at #4072

```
# Don't remove this file and don't change the imports of load_state_dict_from_url
# from other files. We need this so that we can swap load_state_dict_from_url with
# a custom internal version in fbcode.
```

Note that this file is `_` file so it is for internal use and not exposed as API.

**Comment by jaffe-fly** [comment]
thanks
