### ISSUE TITLE
Hi, why rate is two times with paper

### ISSUE THREAD

**Issue by flystarhe** [pytorch/vision#4105]
https://github.com/pytorch/vision/blob/d1ab583d0d2df73208e2fc9c4d3a84e969c69b70/torchvision/models/segmentation/deeplabv3.py#L32

```
n. In the
end, our improved ASPP consists of (a) one 1×1 convolution
and three 3 × 3 convolutions with rates = (6, 12, 18) when
output stride = 16 (all with 256 filters and batch normalization), and (b) the image-level features, 
```

**Comment by voldemortX** [comment]
@flystarhe FYI, this could have something to do with stride.  The torchvision deeplab (if I remember correct) has output stride 8.

**Comment by flystarhe** [comment]
@voldemortX Thanks.
