### ISSUE TITLE
Support pngs with more than 8 bits

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#4107]
We support 1-bit pngs and 8-bits pngs, but we explicitly don't support 16-bits or 32-bits pngs (see https://github.com/pytorch/vision/issues/3613). It would be good to add support for those images.

**Comment by saswatpp** [comment]
Hi @NicolasHug Can I take this issue/enhancement? I hope this is not super urgent because I have to take time to understand internals before coming up with a design and a PR.

**Comment by NicolasHug** [comment]
Thanks for your interest in this issue @saswatpp , it isn't super urgent, don't worry.

I'm not sure how difficult this one could be though, it's the kind of thing that can either be a matter of adding a few lines of code... or a few hundreds. However note that it will definitely involve some C++ coding, so it's good to have prior experience with C++.

Perhaps @andfoy has a better idea of the expected difficulty here?

**Comment by NicolasHug** [comment]
@saswatpp just FYI I started working on this in #4657
