### ISSUE TITLE
Add support for Caltech-UCSD Birds-200-2011 dataset 

### ISSUE THREAD

**Issue by shakeebmurtaza** [pytorch/vision#4128]
## 🚀 Feature
I want to add support for [**Caltech-UCSD Birds-200-2011**](http://www.vision.caltech.edu/visipedia/CUB-200-2011.html) dataset  in **torchvision.datasets**.

## Motivation and Pitch

A lot of people are using **Caltech-UCSD Birds-200-2011** dataset for the evaluation of their proposed models. According to [**paperswithcode.com**](https://www.paperswithcode.com/dataset/cub-200-2011) 787 papers employed this dataset since 2017 and these numbers are growing. So, I want to add support for this data in the datasets library.

cc @fmassa @vfdev-5 @pmeier

**Comment by xiaoyuan0203** [comment]
Can this issue be closed because of #5154 ?
