### ISSUE TITLE
Hey, after changing the segmention.py script, has anyone tested the backbone using Mobilenetv3_large as deeplabv3? When I start the train.py script, I throw the error shown in the screenshot:

### ISSUE THREAD

**Issue by GalSang17** [pytorch/vision#4134]
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)
[
![image](https://user-images.githubusercontent.com/49866330/123753767-ca216600-d8ec-11eb-88a5-81a4374ca9f2.png)
](url)

**Comment by NicolasHug** [comment]
Hi @GalSang17 , please note that raw text is always preferred to screenshots, which are often hard to read, and don't allow any copy/pasting.

Also,  could you please provide a minimal reproducing example with code and imports, so we can try to reproduce your errors? It's very hard to help without knowing the exact code that you ran.

**Comment by GalSang17** [comment]
> Hi @GalSang17 , please note that raw text is always preferred to screenshots, which are often hard to read, and don't allow any copy/pasting.
> 
> Also, could you please provide a minimal reproducing example with code and imports, so we can try to reproduce your errors? It's very hard to help without knowing the exact code that you ran.

Hey, the problem I'm looking at is something like this, TorchVision if I install it using PIP or Conda, The directory/home/yangyang/miniconda3 / envs/deep/lib/python3.8 / site - packages/torchvision/models/segmentation/segmentation. _ in py The _all__ attribute does not contain 'deeplabv3_mobilenet_v3_large', 
![image](https://user-images.githubusercontent.com/49866330/123772283-4ec8b000-d8fe-11eb-82c1-7ab05dcf7f96.png)

so how should I import and use the modified Segmentation.py in Vision? I tried Python setup.py install to compile it. But it throws an error and the compile fails

**Comment by NicolasHug** [comment]
Please avoid screenshots.

Also, please show the output of 

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

as asked in the issue template.

**Comment by GalSang17** [comment]
Hi, thank you very much for your answer. I have tried the method of Importing Lightly version mentioned in README.rst, and it can be successfully compiled and passed, and the training can also work normally. My current information about my environment is as follows:

PyTorch version: 1.10.0.dev20210629+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.13.2
Libc version: glibc-2.27

Python version: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2070

Nvidia driver version: 460.80
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] torch==1.10.0.dev20210629+cu102
[conda] numpy                     1.21.0                   pypi_0    pypi
[conda] torch                     1.10.0.dev20210629+cu102          pypi_0    pypi

But I use Torch1.7.1 and TorchVision0.8.2. How do I specify the version I want at compile time? The Lightly installation always seems to import the latest version

**Comment by GalSang17** [comment]
> Please avoid screenshots.
> 
> Also, please show the output of
> 
> ```
> wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
> # For security purposes, please check the contents of collect_env.py before running it.
> python collect_env.py
> ```
> 
> as asked in the issue template.

Hi, thank you very much for your answer. I have tried the method of Importing Lightly version mentioned in README.rst, and it can be successfully compiled and passed, and the training can also work normally. My current information about my environment is as follows:

PyTorch version: 1.10.0.dev20210629+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.13.2
Libc version: glibc-2.27

Python version: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2070

Nvidia driver version: 460.80
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] torch==1.10.0.dev20210629+cu102
[conda] numpy                     1.21.0                   pypi_0    pypi
[conda] torch                     1.10.0.dev20210629+cu102          pypi_0    pypi

But I use Torch1.7.1 and TorchVision0.8.2. How do I specify the version I want at compile time? The Lightly installation always seems to import the latest version

**Comment by fmassa** [comment]
Hi @GalSang17 

You are using an older version of torchvision, you'll need at least 0.9.1 or 0.10.0 to get the new segmentation models.

You can get them installed with pip or conda following the installation instructions in https://pytorch.org/get-started/locally/
I would recommend you check with the lightly repo to see why it is picking PyTorch 1.7.1 and not the latest one.

I believe we've answered your question, and as such I'm closing this issue, but let us know if you find other problems

**Comment by GalSang17** [comment]
> Hi @GalSang17
> 
> You are using an older version of torchvision, you'll need at least 0.9.1 or 0.10.0 to get the new segmentation models.
> 
> You can get them installed with pip or conda following the installation instructions in https://pytorch.org/get-started/locally/
> I would recommend you check with the lightly repo to see why it is picking PyTorch 1.7.1 and not the latest one.
> 
> I believe we've answered your question, and as such I'm closing this issue, but let us know if you find other problems

Thank you. I see what the problem is
