### ISSUE TITLE
RandomHorizontalFlip and RandomHorizontalFlip with configurable probability

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#414]
Hi,

just wondering whether it could be better to make flip probability configurable [here](https://github.com/pytorch/vision/blob/master/torchvision/transforms/transforms.py#L334) and [here](https://github.com/pytorch/vision/blob/master/torchvision/transforms/transforms.py#L353) ?

Thanks

**Comment by fmassa** [comment]
Yes, I believe this can be an option that can be added, with default value 0.5.

**Comment by alykhantejani** [comment]
Closing as this was merged in #417
