### ISSUE TITLE
Avoid view in no_grad mode in GeneralizedRCNNTransform.batch_images

### ISSUE THREAD

**Issue by beat-buesser** [pytorch/vision#4153]
## 🚀 Feature
Thank you very much for this great project! I'm one of the maintainers of the [Adversarial Robustness Toolbox (ART)](https://github.com/Trusted-AI/adversarial-robustness-toolbox) and `torchvision` has been very useful for ART.

## Motivation

ART has a lot of tools for adversarial machine learning that require the gradients of the loss at the model input and in the case of this issue for `torchvision.models.detection.fasterrcnn_resnet50_fpn`. Since `torchvision>=0.8` we are observing the following RunTimeError when calculating loss gradients towards the input tensor, which prevents us from using `torch>=1.7` for the related tools in ART:
```python
        batch_shape = [len(images)] + max_size
        batched_imgs = images[0].new_full(batch_shape, 0)
        for img, pad_img in zip(images, batched_imgs):
>           pad_img[: img.shape[0], : img.shape[1], : img.shape[2]].copy_(img)
E           RuntimeError: A view was created in no_grad mode and is being modified inplace with grad mode enabled. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

.../python3.7/site-packages/torchvision/models/detection/transform.py:224: RuntimeError
```

## Pitch

Would it be possible to change https://github.com/pytorch/vision/blob/ef711591a5db69d36f904ab5c39dec13627a58ad/torchvision/models/detection/transform.py#L223-L224
into
```python
for i in range(batched_imgs.shape[0]):
    batched_imgs[i][: images[i].shape[0], : images[i].shape[1], : images[i].shape[2]].copy_(images[i])
```
to avoid the RunTimeError?

If yes, I would be happy to open a pull request with the proposed solution.

**Comment by NicolasHug** [comment]
For ref, a minimal reproducing example is

```py
import torch
from torchvision.models.detection.transform import GeneralizedRCNNTransform

t = GeneralizedRCNNTransform(min_size=10, max_size=20, image_mean=[0, 0, 0], image_std=[1, 1, 1])
img = torch.rand(10, 3, 4, 5, requires_grad=True)
t(img)[0]
```


I think the proposed changes are reasonable, but it does raise the question of whether torchvision should support `requires_grad` for inputs in general. If this is a desired feature, we might need to introduce dedicated tests for all transforms / ops / models...
Thoughts @fmassa?

**Comment by bjuncek** [comment]
Might just be my 2 cents, but I think it's fairly reasonable to expect the inputs to require grad by default - it's IMHO easy enough to wrap the operations that don't need it with `torch.no_grad` or detach them if one doesn't need them or wants to save on performance.

**Comment by beat-buesser** [comment]
Hi @NicolasHug and @fmassa Did you have a chance to further consider this issue? We would be happy to help with contributions.

**Comment by fmassa** [comment]
@beat-buesser I'm happy to change the implementation in torchvision to support this.

**Comment by NicolasHug** [comment]
@fmassa WDYT of my comment above?

> I think the proposed changes are reasonable, but it does raise the question of whether torchvision should support requires_grad for inputs in general. If this is a desired feature, we might need to introduce dedicated tests for all transforms / ops / models...

**Comment by datumbox** [comment]
You need this to support adversarial applications.

**Comment by JCSadeghi** [comment]
I have also encountered this issue since `torchvision>=0.8`. If anyone has a workaround for computing the gradient of the RCNN with respect to the input I would be grateful if you could share it.

**Comment by beat-buesser** [comment]
@fmassa Thank you very much. I'm happy to sign up for this issue and I'll try to open a pull request soon.

**Comment by beat-buesser** [comment]
Hi @NicolasHug and @fmassa What do you think about PR #4327 for this issue?

**Comment by datumbox** [comment]
@beat-buesser sorry for the delay. I'm going to merge in a bit.

**Comment by beat-buesser** [comment]
Hi @datumbox Thank you very much! And no worries at all, I see you have lot of other pull requests going on in parallel.
