### ISSUE TITLE
size mismatch at Vgg16 in torchvision

### ISSUE THREAD

**Issue by NaJaeMin7** [pytorch/vision#416]
```
from torchvision import models
...
dataloader for CIFAR10
...

model = models.vgg16(False)

for epoch in range(80):
    for i, (images, labels) in enumerate(train_loader):
        images = Variable(images.cuda())
        labels = Variable(labels.cuda())
        optimizer.zero_grad()
        outputs = resnet(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        if (i + 1) % 100 == 0:
            print("Epoch [%d/%d], Iter [%d/%d] Loss: %.4f" % (epoch + 1, 80, i + 1, 500, loss.data[0]))
...

```
-----------------------------------------------------------------------------
 When I run this codes.. this error occured.

>  -> RuntimeError: size mismatch at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:243

 When I print(model) , There is a 25088 input size of FC layer...
 I tried to change this parameter from 25088 to 512, there is no error but training is not works well.
So I think this input size of FC layer is the problem..
 What can I do in this situation?
 Thanks in advance;

print(model) results :

>    ...
>    (classifier): Sequential(
>     (0): Linear(in_features=25088, out_features=4096)
>     (1): ReLU(inplace)
>     (2): Dropout(p=0.5)
>     (3): Linear(in_features=4096, out_features=4096)
>     (4): ReLU(inplace)
>     (5): Dropout(p=0.5)
>     (6): Linear(in_features=4096, out_features=1000)
>     )

**Comment by fmassa** [comment]
The models in torchvision are configured for training on ImageNet images, so they expect large image sizes (224 x 224) and thus the fully-connected layers are not adapted for cifar images.

You need to change at least one other thing in the model for it to work with cifar10, which is the number of output classes, which should be 10 instead of 1000.

For reference on model implementations that work well on cifar, you can have a look at https://github.com/kuangliu/pytorch-cifar/blob/master/models/vgg.py

**Comment by NaJaeMin7** [comment]
Thank you for your comment.
but I actually changed output class 1000 to 10 for CIFAR10.
Here are my codes. 
`
class Vgg16(nn.Module):
    def __init__(self, num_classes=10):
        super(Vgg16, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.Conv2d(64, 64, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.MaxPool2d(kernel_size=2, stride=2, dilation=1),

            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.Conv2d(128, 128, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.MaxPool2d(kernel_size=2, stride=2, dilation=1),

            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.Conv2d(256, 256, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.Conv2d(256, 256, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.MaxPool2d(kernel_size=2, stride=2, dilation=1),

            nn.Conv2d(256, 512, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.Conv2d(512, 512, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.Conv2d(512, 512, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.MaxPool2d(kernel_size=2, stride=2, dilation=1),

            nn.Conv2d(512, 512, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.Conv2d(512, 512, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.Conv2d(512, 512, kernel_size=3, padding=1),
            nn.ReLU(True),
            nn.MaxPool2d(kernel_size=2, stride=2, dilation=1)
        )
        self.classifier = nn.Sequential(
            nn.Linear(512*7*7, 4096),
            nn.ReLU(True),
            nn.Dropout(),
            nn.Linear(4096, 4096),
            nn.ReLU(True),
            nn.Dropout(),
            nn.Linear(4096, num_classes)
        )

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1)
        x = self.classifier(x)
        return F.softmax(x)
    
    
model = Vgg16()

# print(model)
# optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
optimizer = optim.Adam(model.parameters(), lr=0.01)
criterion = nn.CrossEntropyLoss()


if torch.cuda.device_count() > 0:
    # os.environ["CUDA_VISIBLE_DEVICES"]= '0'
    print("USE", torch.cuda.device_count(), "GPUs!")
    model = nn.DataParallel(model)
else:
    print("USE ONLY CPU!")

if torch.cuda.is_available():
    model.cuda()


def train(epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        if torch.cuda.is_available():
            data, target = Variable(data.cuda()), Variable(target.cuda())
        else:
            data, target = Variable(data), Variable(target)
        optimizer.zero_grad()
        output = model(data)
        # loss = F.nll_loss(output, target)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % 10 == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.data[0]))

`

**Comment by fmassa** [comment]
Now the model looks fine (the print that you sent in the first message had 1000 as the number of classes). This model takes some time to get to good performances, if it doesn't work well try checking the link I sent you in the first message, as the authors claim good results with their model (which is a bit smaller than the model that you are using)

**Comment by NaJaeMin7** [comment]
Thanks for your help.
I checked the link you sent me, so I found that the only difference between two codes is input size of the first FC layer ( nn.Linear(512*7*7, 4096) ) 
Most of  the vgg codes take 512*7*7 as input but when I tried to take this parameter, there is 'size mismatch error' .  
nn.Linear(512,4096) doesn`t make any error ,but not works fine.

**Comment by fmassa** [comment]
Most of VGG takes 512 * 7 * 7 because they expect the input size to be 224x224, but cifar images are much smaller. Try scaling the cifar images so that they are 224x224 and you'll see that standard VGG16 will work fine.
