### ISSUE TITLE
RGB to B&W as weighted sum of tensors

### ISSUE THREAD

**Issue by Dsantra92** [pytorch/vision#4163]
## 🚀 Feature

Converting a multi-channel image to grayscale usually means some weighted sum over all channels to a single channel. I am opening this issue to request a feature for users to optionally mention the weights for converting a multi-channel image to grayscale.

## Motivation

I came across this [Twitter thread](https://twitter.com/_brohrer_/status/1413834607863140357?s=20) where there many interesting comments about why always doing the mean should not be the norm. Here are some interesting links from the thread that convinced me to open this issue:
- [Useful Color Equations](https://e2eml.school/convert_rgb_to_grayscale.html)
- [Article on converting an RGB Image to Grayscale](http://www.brucelindbloom.com/index.html?Math.html)

## Pitch

Currently, the `Grayscale` module only allows you to define the number of channels. As mentioned earlier, there might be some cases where the user might need to mention explicitly the weights of each channel. So I am asking for the definition for `Grayscale` to be extended from
```python
torchvision.transforms.Grayscale(num_output_channels=1)
```
to 
```python
torchvision.transforms.Grayscale(num_output_channels=1, weights=[0.333, 0.333, 0.333])
```
where weights can be a list, tuple for tensor and must add up to 1.

**Comment by NicolasHug** [comment]
Thanks for opening the issue @Dsantra92 

We don't use the mean in torchvision, we use `(0.2989 * r + 0.587 * g + 0.114 * b)` as in the tweet you linked to:

https://github.com/pytorch/vision/blob/8541c214740f9cfaf2e60ad1579faf6f4af1257b/torchvision/transforms/functional_tensor.py#L143-L147

Are there other aggregation that you think would make sense?

**Comment by pmeier** [comment]
@Dsantra92 

> doing the mean should not be the norm

It is actually the other way around: unless the images are not intended for human consumption, averaging over the channels should be done in exceptional cases. The weights that we are using are not arbitrary, but are the default weights used for RGB -> GS conversions everywhere. These weights are chosen to get the best possible impression for human observers.

**Comment by NicolasHug** [comment]
I'll close the issue, @Dsantra92  please don't hesitate to re-open if you identify further aggregations that you think should be supported.
