### ISSUE TITLE
Can't import private function

### ISSUE THREAD

**Issue by sightdata-root** [pytorch/vision#4192]
Hello, 

I'm trying to import the private function `_box_inter_union` from [torchvision.ops.boxes](https://pytorch.org/vision/stable/_modules/torchvision/ops/boxes.html#box_iou)

When i try from `torchvision.ops.boxes import _box_inter_union` I get:
`ImportError: cannot import name '_box_inter_union' from 'torchvision.ops.boxes' (C:\ProgramData\Anaconda3\lib\site-packages\torchvision\ops\boxes.py)`

The result of `print(dir(torchvision.ops.boxes))` returns:
```
['Tensor', 'Tuple', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'batched_nms', 'box_area', 'box_iou', 'clip_boxes_to_image', 'nms', 'remove_small_boxes', 'torch', 'torchvision']
```

In general, how can I access the private functions from torchvision packages?

**Comment by sightdata-root** [comment]
Documentation on [torchvision.ops.boxes](https://pytorch.org/vision/stable/_modules/torchvision/ops/boxes.html#box_iou) is out of date, there is no function called _box_inter_union

**Comment by oke-aditya** [comment]
Hello @sightdata-root `_box_inter_union` is a `_` function. it's not exposed to the user as part of API.
And hence not added to documentation.

Also you are using an old torchvision which does not have this method. This method was added recently in 0.9.x I think.
Can post  `print(torchvision.__version__)` ?

If you really want to use this method then explicitly import from the file. Not from `torchvision.ops`

```
from torchvision.ops.boxes import `_box_inter_union`

NOT
from torchvision.ops import `_box_inter_union`

```

**Comment by NicolasHug** [comment]
Hi @sightdata-root , as @oke-aditya you probably have an outdated version, please make sure to update torchvision.
Also, this function is private: you should avoid using it, as we might break it in the future without notice. I'll close the issue, please feel free to re-open if there are further issues
