### ISSUE TITLE
Add a `pytest.ini`

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#4194]
## 🚀 Feature

Add a `pytest.ini`.

## Motivation

IMO, the default `pytest` configuration is horrible and leads to enormous tracebacks that carry almost no information. [Example](https://app.circleci.com/pipelines/github/pytorch/vision/9503/workflows/395d34f3-1f69-4c04-bfed-fff13e77f403/jobs/702140/tests#failed-test-0)

## Pitch

Let's add a `pytest.ini` to the root of the project configuring the output to a more usable state. We can use [PyTorch core as base](https://github.com/pytorch/pytorch/blob/master/pytest.ini).

## Alternatives

If we for some reason do not want to add this for everyone, we still should add the appropriate flags to our CI runs.

cc @seemethere @pmeier

**Comment by NicolasHug** [comment]
Sounds good to me, thanks for raising this. One thing that I found a bit annoying is the docstring printing, which can be really long for functions like `assert_close`.
Do you want to submit a PR @pmeier ?
