### ISSUE TITLE
`pil_to_tensor` returns non-contiguous tensor

### ISSUE THREAD

**Issue by aaronzs** [pytorch/vision#4199]
## To Reproduce

```python
from PIL import Image
from torchvision.transforms.functional import pil_to_tensor

pic = Image.open("3_channel_pic.png")
pil_to_tensor(pic).is_contiguous()
# False
```

## Expected behavior

`.contiguous()` is recommended to be used after `.permute()`, so that

1. consistent behavior with `to_tensor()`;
2. increase computational efficiency

cc @vfdev-5

**Comment by datumbox** [comment]
I believe this would require copying the memory here:
https://github.com/pytorch/vision/blob/993325dd82567f5d4f28ccb321e3a9a16984d2d8/torchvision/transforms/functional.py#L168

I think the original implementation was written to avoid this. Any thoughts @vfdev-5 ?

**Comment by vfdev-5** [comment]
Yes, `img.permute((2, 0, 1))` returns non-contiguous tensor and avoids data copy. Here is a discussion on why keeping channels last memory format here: https://github.com/pytorch/vision/pull/2092#discussion_r408955401

**Comment by datumbox** [comment]
@aaronzs I believe the above addresses the issue, so to keep things tidy I'm closing the ticket. If you still have concerns feel free to reopen.
