### ISSUE TITLE
fatal error: c10/cuda/CUDAGuard.h

### ISSUE THREAD

**Issue by waduhekx** [pytorch/vision#4217]
when i try to install vision-0.5.0 on jetson nano,which was alleady installed Archiconda3,python3.6,torch1.4
then got an error as following:

jetbot-desktop:~/vision-0.5.0$ sudo python3 setup.py install
[sudo] password for jetbot: 
fatal: not a git repository (or any of the parent directories): .git
Building wheel torchvision-0.5.0a0
running install
running bdist_egg
running egg_info
writing torchvision.egg-info/PKG-INFO
writing dependency_links to torchvision.egg-info/dependency_links.txt
writing requirements to torchvision.egg-info/requires.txt
writing top-level names to torchvision.egg-info/top_level.txt
reading manifest file 'torchvision.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'torchvision.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
copying torchvision/version.py -> build/lib.linux-aarch64-3.6/torchvision
running build_ext
building 'torchvision._C' extension
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/jetbot/vision-0.5.0/torchvision/csrc -I/usr/local/lib/python3.6/dist-packages/torch/lib/include -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c /home/jetbot/vision-0.5.0/torchvision/csrc/vision.cpp -o build/temp.linux-aarch64-3.6/home/jetbot/vision-0.5.0/torchvision/csrc/vision.o -O0 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -std=c++11
In file included from /home/jetbot/vision-0.5.0/torchvision/csrc/DeformConv.h:6:0,
                 from /home/jetbot/vision-0.5.0/torchvision/csrc/vision.cpp:8:
/home/jetbot/vision-0.5.0/torchvision/csrc/cuda/vision_cuda.h:2:10: fatal error: c10/cuda/CUDAGuard.h: No such file or directory
 #include <c10/cuda/CUDAGuard.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
(nanodet) jetbot@jetbot-desktop:~/vision-0.5.0$ export CUDA_ROOT=/usr/local/cuda-10.0/
(nanodet) jetbot@jetbot-desktop:~/vision-0.5.0$ export PATH=$CUDA_ROOT:$CUDA_ROOT/bin:/usr/local/bin:$PATH
(nanodet) jetbot@jetbot-desktop:~/vision-0.5.0$ source ~/.bashrc
jetbot@jetbot-desktop:~/vision-0.5.0$ conda activate nanodet
(nanodet) jetbot@jetbot-desktop:~/vision-0.5.0$ sudo python3 setup.py install
fatal: not a git repository (or any of the parent directories): .git
Building wheel torchvision-0.5.0a0
running install
running bdist_egg
running egg_info
writing torchvision.egg-info/PKG-INFO
writing dependency_links to torchvision.egg-info/dependency_links.txt
writing requirements to torchvision.egg-info/requires.txt
writing top-level names to torchvision.egg-info/top_level.txt
reading manifest file 'torchvision.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '__pycache__' found under directory '*'
warning: no previously-included files matching '*.py[co]' found under directory '*'
writing manifest file 'torchvision.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
copying torchvision/version.py -> build/lib.linux-aarch64-3.6/torchvision
running build_ext
building 'torchvision._C' extension
aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/jetbot/vision-0.5.0/torchvision/csrc -I/usr/local/lib/python3.6/dist-packages/torch/lib/include -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.6m -c /home/jetbot/vision-0.5.0/torchvision/csrc/vision.cpp -o build/temp.linux-aarch64-3.6/home/jetbot/vision-0.5.0/torchvision/csrc/vision.o -O0 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -std=c++11
In file included from /home/jetbot/vision-0.5.0/torchvision/csrc/DeformConv.h:6:0,
                 from /home/jetbot/vision-0.5.0/torchvision/csrc/vision.cpp:8:
/home/jetbot/vision-0.5.0/torchvision/csrc/cuda/vision_cuda.h:2:10: fatal error: c10/cuda/CUDAGuard.h: No such file or directory
 #include <c10/cuda/CUDAGuard.h>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

thank u to watch this, but how can i solve this?
appreciate your reply!

**Comment by fmassa** [comment]
Hi,

This issue seems to arise from a version incompatibility between your PyTorch and torchvision version. I would ensure that you are indeed using the corresponding matching versions.

Also, if you can use latest PyTorch/torchvision, it would probably be better as well.

Given that this is probably a version incompatibility mismatch, I'm closing this issue, but let us know if you have further questions
