### ISSUE TITLE
RCNN series will report errors

### ISSUE THREAD

**Issue by xushilin1** [pytorch/vision#4242]
## 🐛 Bug

torch 1.8.1+cu111，torchvision 0.9.1+cu111

RCNN series（faster rcnn and mask rcnn） will report errors like this
![image](https://user-images.githubusercontent.com/13896300/127963832-750d37f5-6e61-4fc8-8a91-a064cf6ce243.png)

i think the root of the problem is here
`torchvisino/models/detection/_utils.py:58`
![image](https://user-images.githubusercontent.com/13896300/127964142-e0ca7754-7871-4164-ab7d-f7493cd06db3.png)
perm1 is absolutely right and perm2 is absolutely wrong, it is out of range negative.numel()
This problem will 100% recurring.
When I try it in this way， it’s ok
![image](https://user-images.githubusercontent.com/13896300/127964630-059d0337-c662-49de-86ed-d18d2bad7d1b.png)

**Comment by vmoens** [comment]
Thanks for this. Can you give us a minimal code example?

**Comment by vladserkoff** [comment]
this should be fixed in pytorch 1.9 https://github.com/pytorch/pytorch/issues/59756
