### ISSUE TITLE
VOCDetection cannot be downloaded

### ISSUE THREAD

**Issue by filiprejmus** [pytorch/vision#4243]
## 🐛 Bug

Trying to get any instance of the VOCDetection dataset throws  "URLError: <urlopen error [Errno 113] No route to host>"
At the same time http://host.robots.ox.ac.uk/pascal/VOC/ is not reachable. Perhaps the issue is there

## To Reproduce

1. Try to create an instance of the Dataset using torchvision.datasets

from torchvision.datasets import VOCDetection
train_data = VOCDetection('/VOC_dataset', '2007', 'train', download=True)

OSError: [Errno 113] No route to host
URLError: <urlopen error [Errno 113] No route to host>

## Expected behavior

Should create an instance of the dataset.

## Environment

Google Collab

 - PyTorch / torchvision Version: 1.9.0+cu102 / 0.10.0+cu102
 - OS:  Google Collab
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): Google Collab pre install
 - Build command you used (if compiling from source): -
 - Python version: 3.7.11

## Additional context

The Dataset hosting website is down, so I expect this can be fixed by pulling the data from a Mirror instead

cc @pmeier

**Comment by pmeier** [comment]
Yeah, the VOC download server is fairly unstable. In fact, it is the only dataset that we outright skip in our download tests:

https://github.com/pytorch/vision/blob/d7fa36f221cb2ff670cd4267b83a801cece52522/test/test_datasets_download.py#L444-L447

Is there an official mirror for VOC?

**Comment by filiprejmus** [comment]
http://host.robots.ox.ac.uk/pascal/VOC/
here's an official mirror hosted by Oxford University

**Comment by pmeier** [comment]
This is the source we are using:

https://github.com/pytorch/vision/blob/759c5b6dc2dfe46735bf724839f815b5cd79af09/torchvision/datasets/voc.py#L15-L56

A mirror would contain the same files, but in a different location.

**Comment by filiprejmus** [comment]
http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar
http://host.robots.ox.ac.uk/pascal/VOC/voc2011/VOCtrainval_25-May-2011.tar
http://host.robots.ox.ac.uk/pascal/VOC/voc2010/VOCtrainval_03-May-2010.tar
http://host.robots.ox.ac.uk/pascal/VOC/voc2009/VOCtrainval_11-May-2009.tar
http://host.robots.ox.ac.uk/pascal/VOC/voc2008/VOCtrainval_14-Jul-2008.tar
http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtrainval_06-Nov-2007.tar
http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar

**Comment by pmeier** [comment]
@filiprejmus I'm not sure where you are going with this. The links you posted are the ones we are currently using as I have shown in my comment above. So if the download of the VOC dataset does not work, these links are the ones that are "broken".

We can't really do anything about that, since we do not host the dataset. Thus, I'm closing this.

If you find an official mirror, i.e. the same files but on a different server, feel free to reopen so we can integrate that into our implementation.
