### ISSUE TITLE
Checksum mismatch for pytorch::torchvision-0.10.0-py39_cu111

### ISSUE THREAD

**Issue by LukasZhornyak** [pytorch/vision#4261]
Conda throws a ChecksumMismatchError when trying to install pytorch::torchvision-0.10.0-py39_cu111. This issue persists even with the workaround command mentioned in #4071.

Considering that there have been no downloads of the package since it was updated 4 days ago, I'm guessing I'm not alone in this issue.

**Comment by theairbend3r** [comment]
Yes, I'm getting the same error  (Ubuntu 18, CUDA 11.2).

To reproduce the error - 
```
conda create --name my-env python=3
conda activate my-env
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch
```

Following's the error- 
```
ChecksumMismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/pytorch/linux-64/torchvision-0.10.0-py39_cu102.tar.bz2'.
  download saved to: /home/akshaj/miniconda3/pkgs/torchvision-0.10.0-py39_cu102.tar.bz2
  expected md5: 52fb22d2035ac4d8209af52741987076
  actual md5: 9c90cbee72e70083ff912b574c01759f
```

**Comment by seemethere** [comment]
What's weird is that I can't actually reproduce with a fresh machine, is it possible for you to clear your cache using `conda clean -a` and see if that resolves your issue?

**Comment by seemethere** [comment]
I've gone ahead and deleted the old packages and the hash mismatch appears to have been resolved, feel free to re-open the issue if still persists, see https://github.com/pytorch/pytorch/issues/63006#issuecomment-896174963
