### ISSUE TITLE
ImportError: cannot import name '_NewEmptyTensorOp' from 'torchvision.ops.misc'

### ISSUE THREAD

**Issue by sagnik1511** [pytorch/vision#4264]
## ImportError

1. Git clone the repository of [SOLQ](https://github.com/megvii-research/SOLQ)
2. Update the dataset you want to use.
3. Update the data paths in the file SOLQ/datasets/coco.py
4.  RUn the bash file **configs/r50_solq_train.sh**

## Expected behavior

It should now show the error and move further to run the SOL-Q model.

## Environment

PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7.11 (default, Jul  3 2021, 18:01:19)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0+cu102
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.10.0
[pip3] torchvision==0.10.0+cu102
[conda] Could not collect

## Additional context

When running the script  ```!bash configs/r50_solq_train.sh``` it, shows ImportError like shown below :
``` 
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    import datasets
  File "/content/SOLQ/datasets/__init__.py", line 13, in <module>
    from .coco import build as build_coco
  File "/content/SOLQ/datasets/coco.py", line 23, in <module>
    from util.misc import get_local_rank, get_local_size
  File "/content/SOLQ/util/misc.py", line 36, in <module>
    from torchvision.ops.misc import _NewEmptyTensorOp
```

**Comment by fmassa** [comment]
Hi,

This was a private function that has since been removed in torchvision, as its use is not needed anymore.

I would encourage you to open an issue in the SOLQ repo to get them to use latest versions of PyTorch / torchvision.
In particular, [this part of the codebase](https://github.com/megvii-research/SOLQ/blob/058dd08959f2f80619c92cb341b6bccba5a20127/util/misc.py#L489-L508) (which was based off of DETR) is not needed anymore as this has been fixed with latest version of PyTorch.

Let us know if you need any other help on what's needed to fix SOLQ in the original repo.

cc @alcinos we might want to fix DETR repo to handle latest versions of torchvision maybe

**Comment by sagnik1511** [comment]
Thanks @fmassa, for responding. I'll surely do what you told. I was thinking to update those with ```torch.empty()```. Can you suggest if that might help or not?

**Comment by fmassa** [comment]
@sagnik1511 there is no need anymore for the `_NewEmptyTensorOp` in the codebase, as it was used only for the `interpolate` function.

The fix IMO is to replace the old interpolate implementation with
```python
interpolate = torch.nn.functional.interpolate
```
as it now properly supports tensors with 0 in its batch dimension

**Comment by sagnik1511** [comment]
Thank you @fmassa  :)
