### ISSUE TITLE
deform_conv2d, CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#4269]
## 🐛 Bug

Opening a new issue for the bug reported here, I could reproduce as well on nighlty build:
https://github.com/pytorch/vision/issues/2598#issuecomment-896921180

Thanks to @Queuecumber

```
1.10.0.dev20210726+cu111 0.11.0a0+c51f8c1
Total memory used before DFC call: 5.321267579510999%
Traceback (most recent call last):
  File "repro_vision_2598.py", line 58, in <module>
    test_out = dfc(test_in, test_offset)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1060, in _call_impl
    return forward_call(*input, **kwargs)
  File "repro_vision_2598.py", line 40, in forward
    res = deform_conv2d(input=x, offset=offset, weight=self.weight, stride=_pair(self.stride), padding=_pair(self.padding), dilation=_pair(self.dilation), mask=mask)
  File "/vision/torchvision/ops/deform_conv.py", line 89, in deform_conv2d
    return torch.ops.torchvision.deform_conv2d(
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
```

## Environment

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0):
 - OS (e.g., Linux):
 - How you installed PyTorch / torchvision (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Queuecumber** [comment]
Great so what's our next course of action? It seems like it's a weird one to debug

**Comment by vfdev-5** [comment]
One of the options is to pass the code with cuda-gdb and see where exactly it is failing. Seeing the large size numbers maybe we fall to the same issue with the number of kernels: https://github.com/pytorch/vision/issues/2598#issuecomment-678311172

**Comment by Queuecumber** [comment]
Does that edit mean you figured out the problem?

**Comment by vfdev-5** [comment]
Not exactly, just found an error message and the place where it fails. 

@ngimel could you please hint where the issue can in the code ?

**Comment by ngimel** [comment]
Tbh, this looks like OOM - when memory is near limit, then sometimes instead of OOM various cuda API errors are thrown. I cannot repro "Warp illegal address" even with cuda-gdb, only cublas handle error.

**Comment by Queuecumber** [comment]
I highly doubt it's OOM, I can run this on an A100 with `bs=23` and I get the error, pytorch reports a 15% max memory usage after successful run at `bs=22`. It's possible pytorch's instrumentation doesn't account for memory used by whatever this op does though, would be good if we had a surefire way to measure it. But I have a hard time believing one op with these smallish inputs is using 32GB of video memory. 

If you guys need someone from cuda/cublas team I can probably arrange it

**Comment by Queuecumber** [comment]
Updated full script:

```
from typing import Any

import torch
from torch.nn import Conv2d, LeakyReLU
from torch.nn.modules.utils import _pair
from torchvision.ops import DeformConv2d, deform_conv2d


class ModulatedDeformConvPack(DeformConv2d):
    def __init__(self, *args, offset_channels, deformable_groups: int = 1, post_activation: Any = None, **kwargs):
        super(ModulatedDeformConvPack, self).__init__(*args, **kwargs)

        self.deformable_groups = deformable_groups

        self.conv_offset = Conv2d(
            offset_channels,
            self.deformable_groups * 3 * self.kernel_size[0] * self.kernel_size[1],
            kernel_size=self.kernel_size,
            stride=_pair(self.stride),
            padding=_pair(self.padding),
            dilation=_pair(self.dilation),
            bias=True,
        )

        self.init_offset()

        self.post_activation = post_activation()

    def init_offset(self):
        self.conv_offset.weight.data.zero_()
        self.conv_offset.bias.data.zero_()

    def forward(self, x, m):
        out = self.conv_offset(m)
        o1, o2, mask = torch.chunk(out, 3, dim=1)
        offset = torch.cat((o1, o2), dim=1)
        mask = torch.sigmoid(mask)
        res = deform_conv2d(input=x, offset=offset, weight=self.weight, stride=_pair(self.stride), padding=_pair(self.padding), dilation=_pair(self.dilation), mask=mask)

        if self.post_activation is not None:
            res = self.post_activation(res)

        return res


a=torch.randn(1,1,device="cuda")
torch.mm(a,a)

device = torch.device("cuda")

bs = 23

test_in = torch.randn(bs, 160, 256, 256, device=device)
test_offset = torch.randn(bs, 64, 256, 256, device=device)
dfc = ModulatedDeformConvPack(160, 64, 3, 1, 1, offset_channels=64, deformable_groups=8, post_activation=LeakyReLU).to(device)

print(f"Total memory used before DFC call: {(torch.cuda.max_memory_allocated() / torch.cuda.get_device_properties(device).total_memory) * 100}%")

test_out = dfc(test_in, test_offset)

print(f"Total memory used after DFC call: {(torch.cuda.max_memory_allocated() / torch.cuda.get_device_properties(device).total_memory) * 100}%")

print(test_out.cpu()[0, 0, 0, 0])
```

Error on A100 with plenty of memory:

```
error in deformable_im2col: an illegal memory access was encountered
Traceback (most recent call last):
  File "torchvision_bug.py", line 59, in <module>
    test_out = dfc(test_in, test_offset)
  File "/home/mehrlich/.cache/pypoetry/virtualenvs/fvr-Na3ppcxf-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "torchvision_bug.py", line 38, in forward
    res = deform_conv2d(input=x, offset=offset, weight=self.weight, stride=_pair(self.stride), padding=_pair(self.padding), dilation=_pair(self.dilation), mask=mask)
  File "/home/mehrlich/.cache/pypoetry/virtualenvs/fvr-Na3ppcxf-py3.8/lib/python3.8/site-packages/torchvision/ops/deform_conv.py", line 89, in deform_conv2d
    return torch.ops.torchvision.deform_conv2d(
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

Please verify that the update I made to the script matches what you were doing

**Comment by ngimel** [comment]
I still couldn't repro it on a 16 GB card (was getting honest OOMs), but I thinks what's happening is when `columns` are allocated, https://github.com/pytorch/vision/blob/7d52be76c8eaf02b12338afe0822396ab3547fe2/torchvision/csrc/ops/cuda/deform_conv2d_kernel.cu#L1079-L1080, for bs=23 the number of elements is more than `2**31` (217055232, to be exact), and the im2col kernel is using int32 addressing, so some address computations are overflowing. The fix would be to either make the kernel templated and use int64 index computation when necessary, or instead of limiting `n_parallel_ings` to const `kMaxParallelImgs` compute `n_parallel_imgs` in such a way so the `columns` has fewer than `2**31` elements.

**Comment by vfdev-5** [comment]
Thanks a lot for investigating the issue @ngimel !
I retried on RTX8k with 48GB and nvidia-smi reported 14GB max mem usage. Also confirm that the numel of `columns` is 2170552320 which is larger than 2 ** 31.

I can try to draft a PR with the fix.

**Comment by fmassa** [comment]
Thanks for the help investigating the problem @ngimel !

@vfdev-5 both solutions seem fine with me

**Comment by vfdev-5** [comment]
@Queuecumber we merged a fix for this bug, could you please check it tomorrow (~ in 24h from this message) on your use-case once nightlies are built: `conda install pytorch torchvision cudatoolkit=11.1 -c pytorch-nightly -c nvidia` (https://pytorch.org/get-started/locally/) . Thanks

**Comment by Queuecumber** [comment]
Seems to be working, thanks a lot for the fix and sorry for my late reply
