### ISSUE TITLE
I want to convert model resnet to onnx, how to do?

### ISSUE THREAD

**Issue by xinsuinizhuan** [pytorch/vision#4276]

**Comment by oke-aditya** [comment]
Hi ! I think you can have a look at documentation in these two links

1. [Export PyTorch model to ONNX and run using ONNX runtime](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html)

2. [Export torchvision model to ONNX.](https://pytorch.org/docs/stable/onnx.html)

You can write a very similar code for Resnet too.

**Comment by NicolasHug** [comment]
Thanks for the reply @oke-aditya 
@xinsuinizhuan I'll close the issue, feel free to reopen if you have more specific questions

**Comment by xinsuinizhuan** [comment]
I am so sorry, my modle is resnet50, then i want to convert to onnx。I look the uper two papers，but still can't convert. Could provide a conver .py file?
