### ISSUE TITLE
Error when padding PIL image in mode P

### ISSUE THREAD

**Issue by npmhung** [pytorch/vision#4310]
## 🐛 Bug

F.pad(Image.fromarray(np.zeros((300,300))).convert('P'), (3,3))

## Expected behavior

TypeError: an integer is required (got type tuple)

## Environment

 - PyTorch / torchvision Version (e.g., 1.0 / 0.4.0): 1.9.0/ 0.10.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch / torchvision (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.11
 - CUDA/cuDNN version: 11.1.74
 - GPU models and configuration: GTX 1080 Ti
 - Any other relevant information:

**Comment by npmhung** [comment]
I created a conda virtual environment and still had the same issue.

**Comment by npmhung** [comment]
Ok, I figured it out. 
Only the Pillow 8.3.0 has this problem.

8.2.0 is good.

**Comment by datumbox** [comment]
Thanks for reporting. Pillow 8.3.0 has issues and it's currently excluded from our builds. See #4146.
