### ISSUE TITLE
Hidden torch.flatten block in ResNet module

### ISSUE THREAD

**Issue by 1paragraph** [pytorch/vision#4312]
## 🐛 Bug

This bug arise when last 2 layers (avg pool and fc) are changed to nn.Identity

## To Reproduce

import torch
import torch.nn as nn
import torchvision

resnet = torchvision.models.resnet18()
resnet.avgpool = nn.Identity()
resnet.fc = nn.Identity()

img = torch.randn([1,3,256,256])

resnet(img).shape

**Result:** torch.Size([1, 32768])

**Expected result:** torch.Size([1, 8, 8, 512])

## Additional context

https://github.com/pytorch/vision/blob/main/torchvision/models/resnet.py
line 243 to delete

**Comment by datumbox** [comment]
@1paragraph Try overwriting the forward method or building a Sequential model by combining the parts of the ResNet you want to use (from conv1 to layer4).

I'm closing the issue as I believe I addressed it. If you have more questions, feel free to reopen. :)
