### ISSUE TITLE
Timeline for v0.9.2 release

### ISSUE THREAD

**Issue by waytrue17** [pytorch/vision#4329]
## ❓ Questions and Help
Our product relies on torch1.8.2 and hence vision0.9.2. Although we are able to build it against v0.9.2-rc2, it would be better to use the released version. Could someone share some info/status about the v0.9.2 release? Thanks
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by NicolasHug** [comment]
@malfet I'm not sure, but it looks like you're the one who pushed the [0.9.2-rc1 and 0.9.2-rc2 tags](https://github.com/pytorch/vision/tags). Were you planning on releasing a 0.9.2 version of torchvision?

**Comment by gkowarzyk** [comment]
I just [commented on this here](https://github.com/pytorch/pytorch.github.io/issues/828#issuecomment-941370876).

This has also been a problem for us.

**Comment by gkowarzyk** [comment]
Hello @malfet , 
I just checked to see if the tag 0.9.2 has been added to `torchvision`, but it doesn't seem to be added yet (I only see the `0.9.2-rc1` and `0.9.2-rc2` tags). Would it be possible to add them please? Thanks in advance!
