### ISSUE TITLE
Torchvision visualization utilities typo

### ISSUE THREAD

**Issue by aromm** [pytorch/vision#4334]
## 📚 Documentation

Hi there! In the [visualization utilities](https://pytorch.org/vision/stable/auto_examples/plot_visualization_utils.html#sphx-glr-auto-examples-plot-visualization-utils-py) documentation, I believe there is a typo. In [this line](https://github.com/pytorch/vision/blob/5ef75d7bc666c9af3dd05b62b075df4c23ca467c/gallery/plot_visualization_utils.py#L346) we say the model is _less_ confident about the dog detection, despite the dog detection having a score of `.9987` and the person detections having scores `~0.7`. I might be wrong on the semantics, but I think of a high score as high confidence, right?

Happy to submit a PR changing "less" -> "more". Thanks!
Anthony

**Comment by NicolasHug** [comment]
Thanks for the report @aromm , you are correct it should be "more". we'll be happy to review your PR!

**Comment by NicolasHug** [comment]
Fixed in https://github.com/pytorch/vision/pull/4340, thanks!
