### ISSUE TITLE
TORCHVISION.TRANSFORMS documentation typo

### ISSUE THREAD

**Issue by puhuk** [pytorch/vision#4336]
### 📚 The doc issue

In this document, there are some minor issues regarding typo.
https://pytorch.org/vision/stable/transforms.html
(file location: https://github.com/pytorch/vision/blob/main/docs/source/transforms.rst)

1) In the 4th paragraph,
implicitely -> implicitly 

2) In 6th paragraph,
illustate -> illustrate

### Suggest a potential alternative/fix

1) In the 4th paragraph,
implicitely -> implicitly 

2) In 6th paragraph,
illustate -> illustrate

**Comment by NicolasHug** [comment]
Thanks for the report @puhuk , would you be interested in submitting a PR for these?

**Comment by puhuk** [comment]
> Thanks for the report @puhuk , would you be interested in submitting a PR for these?

Sure let me submit PR

**Comment by NicolasHug** [comment]
Closing now that #4337 is merged, thanks!
