### ISSUE TITLE
[v0.10.1] Release Tracker

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#4343]
This is a master issue to track which PRs should be cherry-picked for the 0.10.1 release, and follows PyTorch's criteria https://github.com/pytorch/pytorch/issues/58518.

## Cherry-Pick Criteria

Only low-risk changes may be cherry-picked from master:

- Fixes to regressions against the most recent minor release (e.g. 1.8 for 1.9 release; see module: regression issue list)
- Critical fixes for: silent correctness, backwards compatibility, crashes, deadlocks, (large) memory leaks
- Fixes to new features introduced in the most recent minor release (e.g. 1.8.1 for 1.9 release)
- Test/CI fixes
- Documentation improvements
- Compilation fixes or ifdefs required for different versions of the compilers or third-party libraries
- Release branch specific changes (e.g. change version identifiers)

## Cherry-Pick Process
Ensure your PR has landed in master. This does not apply for release-branch specific changes (see Cherry-Pick criteria).

Create (but do not land) a PR against the release branch.

### Details
Make a request below with the following format:

- Link to landed master PR (if applicable):
- Link to release branch PR:
- Criteria Category:

**Comment by datumbox** [comment]
- Link to landed master PR: #4288
- Link to release branch PR: #4344
- Criteria Category: Compilation fix

**Comment by cprobert-insitro** [comment]
Hi @datumbox @fmassa - I noticed that `0.10.1` builds are [showing up in the `pytorch/torchvision` anaconda channel](https://anaconda.org/pytorch/torchvision/files), but looks like they still have the `jpeg <= 9b` requirement:

<img width="926" alt="Screen Shot 2021-09-22 at 12 21 10 PM" src="https://user-images.githubusercontent.com/43685110/134408081-bf38c70a-fc71-4f7a-bb93-c652b031e53f.png">

I wanted to ask if this is intended given that #4344 is nominated for inclusion in `0.10.1` above? I would be hugely appreciative if there is any way this fix could be included in the `0.10.1` builds to release the `jpeg <= 9b` pin.

**Comment by datumbox** [comment]
@cprobert-insitro Unfortunately the cherrypick was not merged before the release of `0.10.1`. We are triaging to see what we can do. Note a branch new release (`0.11`) will be due in couple of weeks so the patch will definitely be in there.
