### ISSUE TITLE
Minor Typo in Example Gallery 

### ISSUE THREAD

**Issue by saswatpp** [pytorch/vision#4350]
### 📚 The doc issue

In the Gallery Example regarding `Tensor Transforms and JIT`, we have the following typo:

```
Since the model is scripted, it can be easily dumped on disk **an** re-used
```

### Suggest a potential alternative/fix

Replace `an` with `and`

**Comment by datumbox** [comment]
@saswatpp Thanks for reporting it. Would you be happy to send a PR that corrects this?

**Comment by saswatpp** [comment]
Sure, will do in a moment.

**Comment by NicolasHug** [comment]
Closed by https://github.com/pytorch/vision/pull/4352

**Comment by saswatpp** [comment]
@NicolasHug @datumbox Also wanted to know if there is any issue that would be okay to work on right now. I intend to contribute actively.

**Comment by NicolasHug** [comment]
Thanks for your interest in contributing @saswatpp ! We will keep you in mind if we can think of something relevant. Meanwhile please don't hesitate to check the repo for issues with the help-wanted tag if you haven't already :)

https://github.com/pytorch/vision/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
