### ISSUE TITLE
Migrate Docs from master to main

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#4356]
### 📚 The doc issue

Inorder to view the latest docs Users should NOT navigate to https://pytorch.org/vision/master/index.html

but instead navigate to

https://pytorch.org/vision/main/index.html

This happens because Main is not visible in the version selector, 
![image](https://user-images.githubusercontent.com/47158509/131960015-b4cd6748-0ab0-4a2d-b5d3-695aaec9ccff.png)

### Suggest a potential alternative/fix

Simple fix is to edit https://github.com/pytorch/vision/blob/gh-pages/versions.html#L21  
To include main instead of master.
Note that this is in the gh-pages (deployed over GitHub) branch.

I can probably send a PR!

**Comment by NicolasHug** [comment]
Thanks a lot for noticing @oke-aditya 

> Simple fix is to edit https://github.com/pytorch/vision/blob/gh-pages/versions.html#L21

Yes but I think we should try to fully migrate the docs by doing something similar to what was done in https://github.com/pytorch/audio/pull/1676

in particular there are a few additional occurrences of "master" that we need to change, and the current `master` directory should be deleted and re-created to just be a symlink to `main`.

Would you like to send a PR for this?

**Comment by NicolasHug** [comment]
FYI @parmeet as I think you'll have to do the same for torchtext

**Comment by oke-aditya** [comment]
Sure @NicolasHug. I will send a PR. I will accommodate all the above changes just like pytorch/audio

**Comment by NicolasHug** [comment]
Closing, thanks a lot @oke-aditya for bringing this to our attention!
