### ISSUE TITLE
Replace copied createIndex/loadRes/evaluate in references/*/coco_eval.py by calls to original functions + contextlib.redirect_stdout to suppress prints

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/vision#4368]
### 🚀 The feature

Motivation for the copies is only removing prints. In Python 3 this can easily be achieved by using https://docs.python.org/3/library/contextlib.html?highlight=context#contextlib.redirect_stdout around calls to evaluate/loadRes

### Motivation, pitch

Less code to maintain, less code for users to copy-paste/read/understand (since currently references code is invited to be simple scaffolding for users to copy and modify)

### Additional context
Also, `import torch._six` could be eliminated

cc @datumbox

**Comment by vadimkantorov** [comment]
`utils.mkdir(...)` could also be replaced by `os.makedirs(..., exist_ok = True)`

**Comment by datumbox** [comment]
Though our reference scripts might be updated soon and moved on a separate repo, cleaning up their code now might be worth doing. I would be happy to review a PR that removes the extra code we currently maintain. :)

**Comment by fmassa** [comment]
I agree with @vadimkantorov here that we can simplify a bunch of stuff.

For reference, this is what we did in DETR, which was initially copy-pasted from torchvision, but cleaned up to apply those improvements mentioned by Vadim.

https://github.com/facebookresearch/detr/blob/main/datasets/coco_eval.py

**Comment by vadimkantorov** [comment]
@fmassa Probably even `evaluate` method could go and the original one can be used (with stdout redirects if wanted)

**Comment by fmassa** [comment]
@vadimkantorov there were some slight differences in `evaluate`, see https://github.com/facebookresearch/detr/blob/eb9f7e03ed8e2ed2cd55528989fe7df890bc3fc0/datasets/coco_eval.py#L248-L252

But with proper modifications it could be moved out indeed

**Comment by vadimkantorov** [comment]
So I think:
https://github.com/facebookresearch/detr/blob/eb9f7e03ed8e2ed2cd55528989fe7df890bc3fc0/datasets/coco_eval.py#L51 :
`img_ids, eval_imgs = evaluate(coco_eval)` could be replaced by `coco_eval.evaluate(); evalImgs = np.asarray(coco_eval.evalImgs).reshape(-1, len(coco_eval.params.areaRng), len(coco_eval.params.imgIds))`

And then custom `evaluate()` could go.

Does it make sense @fmassa?

**Comment by fmassa** [comment]
@vadimkantorov yes, I think so, and that's what @prabhat00155 did in #4453, thanks for raising this up!

**Comment by vadimkantorov** [comment]
Maybe also simplify synchronize_between_processes, create_common_coco_eval and merge into a single 
```python
    def synchronize_between_processes(self):
        for iou_type, coco_eval in self.coco_eval.items():
            self.eval_imgs[iou_type] = np.concatenate(self.eval_imgs[iou_type], 2)

            all_img_ids = utils.all_gather(self.img_ids)
            all_eval_imgs = utils.all_gather(self.eval_imgs[iou_type])

            merged_img_ids = np.array([s for p in all_img_ids for s in p])
            merged_img_ids, idx = np.unique(merged_img_ids, return_index=True)
            merged_eval_imgs = np.concatenate(all_eval_imgs, 2)
            merged_eval_imgs = merged_eval_imgs[..., idx]

            coco_eval.evalImgs = list(merged_eval_imgs.flatten())
            coco_eval.params.imgIds = list(merged_img_ids)
            coco_eval._paramsEval = copy.deepcopy(coco_eval.params)

```
