### ISSUE TITLE
Error (403:Forbidden error) while downloading the weights of pointpillar model

### ISSUE THREAD

**Issue by Sri20021** [pytorch/vision#4371]
I find the 403: Forbidden error when trying to download the weights of the model through the link: https://storage.googleapis.com/open3d-releases/model-zoo/pointpillars_kitti_202012171738utc.pth
I am unable to download the file even through the browser
Request you to take a look and correct it. Thanks

**Comment by NicolasHug** [comment]
Could you please indicate where this URL comes from? I don't see any reference to it in torchvision's codebase

**Comment by Sri20021** [comment]
@NicolasHug Sorry, by mistake raised this issue in this forum. I was supposed to raise it in Open3D forum. Sorry!
