### ISSUE TITLE
Original Implementation of the GoogLeNet

### ISSUE THREAD

**Issue by niuqun** [pytorch/vision#438]
Dear all, do you have the original GoogLeNet trained on ImageNet? I think I need the original one in the 2015 paper rather than latter improved versions. Thanks!

**Comment by vadimkantorov** [comment]
i have one at https://github.com/vadimkantorov/metriclearningbench (without additional branch)

**Comment by niuqun** [comment]
@vadimkantorov Thank you! I will check it later.
