### ISSUE TITLE
Video support in torchvision

### ISSUE THREAD

**Issue by prabhat00155** [pytorch/vision#4392]
This is to keep track of the major work items for video support in TorchVision in this half.

- [x] Building torchvision with ffmpeg.
- [x] Updating the documentation to clearly state the steps to use video api.
- [x] Benchmarking performance.
- [x] [Video GPU Decoding](https://github.com/pytorch/vision/issues/2439)

**Comment by vadimkantorov** [comment]
It would be nice that ffmpeg support features two README items/examples:
1. How to install a working torchvision + ffmpeg combination from conda
2. How to compile torchvision from sources with ffmpeg (with two ffmpeg options: one is installable from conda; another is ffmpeg also built from sources in the most basic variant, for decoding it should be enough)

**Comment by bjuncek** [comment]
Regarding benchmarking:
I've done the first steps towards it in this [repo](https://github.com/bjuncek/video_reader_benchmark).

The main for me are that:
1) in straight-up video reading, it is not obviously clear that GPU decoding is actually faster than CPU decoding [1]. In chat with people, it seems like there is benefit of GPU decoding in end-to-end pipelines where decoded frames can be directly consumed by the GPU. But that raises the questions whether we can actually support this bc our transforms are afaik done on CPUs, so you'd not gain much. Similar things have been observed by Mike from pyAV as well in their docs [2]

![test](https://user-images.githubusercontent.com/6318056/135487200-7fdbfed0-38f0-47d9-85d1-3d296fb60afa.png)

2) As with our VideoReader and older `read_video` APIs, each come with their set of advantages and trade-offs. You can simply check the `demo.ipynb` in the repo above to see that different readers have a different approach to how the API should look like. It is also useful to note that some libraries (namely decord), actually count on the _approximations_ in order to implement the VideoReader API that allowes getting of the _k_-th frame. Many filetypes (for example stock HMDB51 videos) do not contain `extradata` metadata; when approximating number of frames, we found that up to 4% of the frames can be missed/duplicated in these situations. 




[1] note, these comparisons were done on the machine with above-average CPU and what used to be quite competitive GPU. Running it on different hardware would probably provide more results. 

[2] https://pyav.org/docs/develop/overview/about.html : see section "Unsuported features"

**Comment by vadimkantorov** [comment]
(I think there is also a push for more and more transforms supporting GPU and relying on just PyTorch ops)

**Comment by vadimkantorov** [comment]
+ from my experience this is a very bad idea of having anything relying on getting exactly kth frame. because this depends heavily on the decoder, its queue implementation, and on its handling of missing frames / pts (some decoder may choose to fill in missing frames, some decoders may not do it). I was bitten by it exacty when dealing with HMDB. From what I understood, the only quasi-reliable addressing when dealing with real-world video is time in seconds that's tied to more reliable pts addressing in frame structures

**Comment by prabhat00155** [comment]
> for the ffmpeg command with the output yuv file, I think we're comparing: `Read encoded file from disk -> decode on cpu -> write to disk` to: `Read encoded file from disk -> copy to gpu -> decode -> copy (larger, full frames) to cpu -> write to disk`

Yes, that's correct. This includes the time taken to copy frames between gpu and system memory.

> Concretely, an actual ML pipeline for some classification model might look like:
> `read encoded file -> decode on cpu -> copy full frames to GPU -> perform image transforms on frames -> run through GPU model -> copy a "class" back to CPU.` vs: `Read encoded file -> copy (smaller encoded file) to GPU -> perform image transforms on frames -> run through GPU model -> copy a "class" back to CPU.`
> 
> In this later example I'd guess that the second path (GPU) might be faster. It's using accelerated hardware for the decoding but also doing _less_ total IO than the CPU-decoding path.
> 

To test this, we would need to add a prototype to torchvision. pyAV doesn't support hardware accelerated decoding. I am looking at https://github.com/NVIDIA/VideoProcessingFramework, but haven't managed to successfully build it yet.

**Comment by prabhat00155** [comment]
Video decoding benchmarking results using ffmpeg APIs(for CPU decoding) and NVDECODE APIs(for GPU decoding). Please note that the total time includes the time to save the output. This would add extra copy time on GPUs from cuda memory to system memory.
```
<pre ccp_infra_version="3" ccp_infra_timestamp="1635810149520" ccp_infra_user_hash="3945756865" ccp_infra_copy_id="1367eb71-a4f5-44aa-92f6-766a2a16d5e3" data-ccp-timestamp="1635810149520" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

  |   |   |   | Total time(in sec; includes saving the decoded file) |   |   |   |   |   |   |   |   |   | Total time(averaged over 5 runs) |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Videos | Source | Size | Duration(in sec) | CPU |   |   |   |   | GPU |   |   |   |   | CPU | GPU | CPU/GPU
8hFYAVhnAg4_000001_000011.mp4 | kinetics | 5.6M | 10 | 1.785 | 1.998 | 2.089 | 2.018 | 2.093 | 1.217 | 1.46 | 1.465 | 1.71 | 1.479 | 1.9966 | 1.4662 | 1.361751
5bljAEyjYvQ_000000_000010.mp4 | kinetics | 131K | 2 | 0.045 | 0.052 | 0.051 | 0.049 | 0.047 | 0.891 | 0.99 | 0.861 | 0.894 | 0.874 | 0.0488 | 0.902 | 0.054102
4nWUEQXQ0xA_000000_000010.mp4 | kinetics | 969K | 10 | 0.334 | 0.424 | 0.391 | 0.379 | 0.393 | 0.976 | 1.004 | 1.035 | 1.073 | 1.107 | 0.3842 | 1.039 | 0.369779
ARb0rBemhFE_000025_000035.mp4 | kinetics | 783K | 10 | 0.251 | 0.29 | 0.29 | 0.286 | 0.29 | 0.99 | 0.988 | 1.001 | 1.613 | 1.675 | 0.2814 | 1.2534 | 0.224509
m6YMDxAWigs_000024_000034.mp4 | kinetics | 4.8M | 10 | 1.608 | 1.863 | 1.844 | 1.899 | 1.953 | 1.232 | 1.628 | 1.516 | 1.506 | 1.463 | 1.8334 | 1.469 | 1.24806
7GOB1u0scWw_000426_000436.avi | kinetics | 39M | 10 | 0.822 | 0.954 | 0.959 | 0.966 | 0.925 | 1.406 | 1.326 | 1.288 | 1.27 | 1.36 | 0.9252 | 1.33 | 0.695639
LzHGPWvaJQc_000300_000310.avi | kinetics | 12M | 10 | 0.443 | 0.631 | 0.581 | 0.584 | 0.628 | 1.244 | 1.311 | 1.299 | 1.305 | 1.252 | 0.5734 | 1.2822 | 0.4472
SOX5yA1l24A.mp4 | torchvision | 548K | 11 | 0.208 | 0.212 | 0.215 | 0.207 | 0.212 | 1.004 | 0.998 | 1.036 | 1.909 | 1.116 | 0.2108 | 1.2126 | 0.173841
R6llTwEh07w.mp4 | torchvision | 844K | 10 | 0.225 | 0.246 | 0.244 | 0.248 | 0.245 | 0.94 | 1.006 | 1.024 | 1.187 | 0.979 | 0.2416 | 1.0272 | 0.235202
eFcpy2RClJQ.mp4 | activityNet200 | 201M | 671 | 77.222 | 87.814 | 88.754 | 88.112 | 85.684 | 23.21 | 34.748 | 38.418 | 33.593 | 39.309 | 85.5172 | 33.8556 | 2.52594
YtgiDWEY_1A.mp4 | activityNet201 | 185M | 755 | 89.533 | 98.141 | 99.615 | 98.524 | 96.795 | 29.681 | 37.863 | 43.796 | 37.704 | 42.618 | 96.5216 | 38.3324 | 2.518016
6I1aP4O04R8.mp4 | activityNet202 | 159M | 235 | 35.331 | 39.912 | 39.082 | 38.037 | 41.12 | 9.055 | 14.921 | 15.148 | 14.629 | 14.559 | 38.6964 | 13.6624 | 2.832328
b993qWuMRBA.mp4 | activityNet203 | 136M | 490 | 57.163 | 59.643 | 60.459 | 61.423 | 56.652 | 15.277 | 22.102 | 20.854 | 21.967 | 23.326 | 59.068 | 20.7052 | 2.85281
aOzMA2rpWEw.mp4 | activityNet204 | 131M | 537 | 71.548 | 77.7 | 74.405 | 77.082 | 66.621 | 20.55 | 36.669 | 28.855 | 32.263 | 35.359 | 73.4712 | 30.7392 | 2.390147
BYLxSOPFOuc.mp4 | activityNet205 | 109M | 489 | 61.188 | 67.753 | 63.722 | 67.886 | 67.289 | 16.754 | 33.892 | 31.693 | 32.624 | 26.356 | 66.029 | 28.2638 | 2.336169
H-5nHSHwFOk.mp4 | activityNet206 | 103M | 745 | 60.307 | 72.364 | 69.774 | 69.524 | 67.753 | 23.277 | 34.641 | 40.04 | 39.048 | 34.187 | 67.9444 | 34.2386 | 1.984439
16725zS5kVM.mp4 | activityNet207 | 90M | 236 | 30.448 | 36.014 | 36.461 | 33.78 | 33.947 | 9.245 | 15.928 | 12.849 | 14.812 | 15.01 | 34.13 | 13.5688 | 2.515329
lPCl1ZYH2xI.mp4 | activityNet208 | 90M | 360 | 36.563 | 40.204 | 43.145 | 43.745 | 40.404 | 13.312 | 23.461 | 22.668 | 19.566 | 23.482 | 40.8122 | 20.4978 | 1.991053
QWRGRAod0no.mp4 | activityNet209 | 81M | 227 | 26.017 | 28.443 | 29.581 | 31.116 | 30.407 | 7.905 | 13.332 | 11.269 | 12.424 | 13.135 | 29.1128 | 11.613 | 2.506915

</pre>
```

**Comment by prabhat00155** [comment]
The following table does not include the time to save the decoding output.
```
Videos                        | Source         |Size  |Duration(in s)|CPU(in s)|GPU(in s)| CPU/GPU
----------------------------- | -------------- | ---- | ------------ | ------- | ------- | ---------
8hFYAVhnAg4_000001_000011.mp4 | kinetics       | 5.6M | 10           | 1.5692  | 1.2692  | 1.236369367
5bljAEyjYvQ_000000_000010.mp4 | kinetics       | 131K | 2            | 0.0412  | 0.873   | 0.047193585
4nWUEQXQ0xA_000000_000010.mp4 | kinetics       | 969K | 10           | 0.2952  | 0.9698  | 0.304392658
ARb0rBemhFE_000025_000035.mp4 | kinetics       | 783K | 10           | 0.2076  | 0.9226  | 0.225016258
m6YMDxAWigs_000024_000034.mp4 | kinetics       | 4.8M | 10           | 1.382   | 1.1076  | 1.247742867
7GOB1u0scWw_000426_000436.avi | kinetics       | 39M  | 10           | 0.715   | 1.0718  | 0.667102071
LzHGPWvaJQc_000300_000310.avi | kinetics       | 12M  | 10           | 0.3814  | 1.0092  | 0.377923107
SOX5yA1l24A.mp4               | torchvision    | 548K | 11           | 0.1534  | 0.9325  | 0.164504021
R6llTwEh07w.mp4               | torchvision    | 844K | 10           | 0.2022  | 0.9728  | 0.207853618
eFcpy2RClJQ.mp4               | activityNet200 | 201M | 671          | 63.504  | 14.4204 | 4.403761338
YtgiDWEY_1A.mp4               | activityNet200 | 185M | 755          | 71.7632 | 23.8412 | 3.01004983
6I1aP4O04R8.mp4               | activityNet200 | 159M | 235          | 29.9866 | 6.1586  | 4.86906115
b993qWuMRBA.mp4               | activityNet200 | 136M | 490          | 44.984  | 11.729  | 3.835280075
aOzMA2rpWEw.mp4               | activityNet200 | 131M | 537          | 56.4512 | 18.4192 | 3.064801946
BYLxSOPFOuc.mp4               | activityNet200 | 109M | 489          | 50.603  | 15.8836 | 3.185864665
H-5nHSHwFOk.mp4               | activityNet200 | 103M | 745          | 45.6914 | 15.9778 | 2.859680306
16725zS5kVM.mp4               | activityNet200 | 90M  | 236          | 26.4814 | 5.6624  | 4.676709522
lPCl1ZYH2xI.mp4               | activityNet200 | 90M  | 360          | 27.526  | 8.1726  | 3.368083596
QWRGRAod0no.mp4               | activityNet200 | 81M  | 227          | 20.776  | 4.7256  | 4.396478754
```

**Comment by prabhat00155** [comment]
The following only measures the time taken in decoding on both CPU and GPU. GPU decoding is much faster across the board.
<img width="1660" alt="Screenshot 2021-11-12 at 00 07 36" src="https://user-images.githubusercontent.com/7043157/141386640-84444419-3f95-455f-8d3e-ca4cb8e22cde.png">

**Comment by prabhat00155** [comment]
The following measures the time taken in decoding(just measures the time spent in decoding operation) whole videos. GPU again performs much better the CPU.
<img width="1730" alt="Screenshot 2021-11-12 at 15 01 45" src="https://user-images.githubusercontent.com/7043157/141487971-6ecc5ed1-30a9-4e5e-ab25-2549d3f17c0c.png">

*Green colour in the last column shows the GPU is faster than CPU.

**Comment by bjuncek** [comment]
These look great; just for clarification, how come are the number on kinetics so much different now than in the tables from 10 days ago. What have changed?
(to clarify, I still get similar numbers to the tables above, i.e. around 20% improvement over single-threaded cpu decoding on h264x-high with decord)

![image](https://user-images.githubusercontent.com/6318056/141537309-f82f0a38-927e-4610-9bb5-4ccf0bde4237.png)

**Comment by prabhat00155** [comment]
> These look great; just for clarification, how come are the number on kinetics so much different now than in the tables from 10 days ago. What have changed? (to clarify, I still get similar numbers to the tables above, i.e. around 20% improvement over single-threaded cpu decoding on h264x-high with decord)
> 
> ![image](https://user-images.githubusercontent.com/6318056/141537309-f82f0a38-927e-4610-9bb5-4ccf0bde4237.png)

@bjuncek The last two tables only measure the time taken in decoding operation. The tables I reported previously measured the time taken by the C++ program to execute which includes the time taken to read the input file, cuda initialisation, copy from system memory to cuda memory, etc.

**Comment by yuzhms** [comment]
Which version of ffmpeg should be used? I try ffmpeg4.2.3 from conda, but there is no bsf.h. Using ffmpeg 4.3
.x encounter segmentation fault.  https://github.com/pytorch/vision/issues/3367#issue-805041843

**Comment by prabhat00155** [comment]
Are you using GPU decoding? If not, you don't really need `bfs.h`.
Also, last time I tried, I was able to build with latest ffmpeg from conda-forge: `conda install -c conda-forge ffmpeg` with Python 3.8, without any issues.

**Comment by yuzhms** [comment]
Thanks for your reply. I want to use GPU decoding, so I need `bfs.h` .  I try the same `conda install -c conda-forge ffmpeg` with Python 3.8, but it has segmentation fault.
Could you share the full building script or a Docker image which has already installed the gpu decoding version of torchvision? 

Many thanks!

**Comment by yuzhms** [comment]
It works well when using single worker. and the segmentation fault only happens when the number of workers > 0. Have you done such testing?

**Comment by prabhat00155** [comment]
@yuzhms GPU decoding would only work with worker = 0. By the way, I am curious to know how are you testing this.

**Comment by yuzhms** [comment]
So me build is fine. I got it. 

But worker =0 with GPU decoding is slower than worker=16 with CPU decoding. What is the meaning of this new feature? Do you have plan to extend GPU decoding to worker>0?

I do not test this separately. Actually, I am using pyslowfast (https://github.com/facebookresearch/SlowFast) doing some action recognition research, and I write a decoder using the new VideoReader API. I tested the training speed based on that.

**Comment by prabhat00155** [comment]
Yes, you are right. I had compared CPU decoding with worker=10 vs GPU decoding with worker=0 and CPU decoding was faster. GPU decoding would need to support multiple workers to improve the speed. You are welcome to contribute.

**Comment by yuzhms** [comment]
Thanks anyway. Perhaps you should mention this point in the documentation, otherwise people will expect it works for multiple workers.

**Comment by prabhat00155** [comment]
We haven't yet added a reference script that uses the new API. Once we do that, we should definitely add this information in the documentation for the reference script.
