### ISSUE TITLE
cmake_windows_gpu job fails

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#4440]
### 🐛 Describe the bug

The cmake_windows_gpu job on latest main started [failing](https://app.circleci.com/pipelines/github/pytorch/vision/10521/workflows/d7d80f03-bef3-4e0f-a587-bc274097ed25/jobs/798806) with:
```
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 (found version "10.1") 
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin/nvcc.exe
-- Caffe2: CUDA toolkit directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1
CMake Error at C:/tools/miniconda3/Lib/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:42 (message):
  PyTorch requires CUDA 10.2 or above.
Call Stack (most recent call first):
  C:/tools/miniconda3/Lib/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  C:/tools/miniconda3/Lib/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:17 (find_package)
```

It seems that despite defining CUDA10.2 below, something setups 10.1 on the paths:
https://github.com/pytorch/vision/blob/c1ddb93c43cd9f620594fdf1a4ba07ff3e518282/.circleci/config.yml#L1704-L1707

This version mismatch was probably always there but the 10.1 version check and enforcement was probably introduced on PyTorch recently because this job [passed yesterday](https://app.circleci.com/pipelines/github/pytorch/vision/10489/workflows/4d0aa7a2-be25-49f2-b3f8-03a23726d6f3/jobs/796095).

### Versions

latest main a2b4c652e1a0c8678e951c6c50174615d6ba101f

**Comment by seemethere** [comment]
You need to upgrade this job to CUDA 10.2 were no longer supporting CUDA 10.1

**Comment by datumbox** [comment]
@seemethere My question was, shouldn't this be using already CUDA 10.2? See below:
https://github.com/pytorch/vision/blob/c1ddb93c43cd9f620594fdf1a4ba07ff3e518282/.circleci/config.yml#L1704-L1707
