### ISSUE TITLE
Question:  FFmpeg dependency

### ISSUE THREAD

**Issue by rwmajor2** [pytorch/vision#4446]
Sorry, I am little bit of a newbie on this subject.  I notice at Torchvision 0.9+ that ffmpeg >= 4.2 is a hard dependency for Linux conda distributions.  At Torchvision <= 0.8.2, this was not a dependency.  We all know ffmpeg licensing and the other dependencies it pulls in is problematic in some scenarios.

Question 1:  Is it possible to build Torchvision for Linux without ffmpeg?  What breaks?
Question 2:  If I manually alter the .bz2 file from Anaconda.org to remove the ffmpeg dependency, what breaks?

Any other suggestions?

**Comment by prabhat00155** [comment]
ffmpeg is not a hard dependency. You can build torchvision from source without ffmpeg on any platform. If you wish to use the video APIs with `video_reader` backend, only then do you need to build torchvision with ffmpeg.

**Comment by rwmajor2** [comment]
Thanks @prabhat00155.  That answers a huge question for me.  Follow up question.  I can download the .bz2 file from Anaconda.org and modify the info/index.json to remove the ffmpeg dependency?  Is this effectively the same as building from source without ffmpeg?  Or will I run into stability problems with torchvision?

```json
{
  "arch": "x86_64",
  "build": "py37_cu111",
  "build_number": 0,
  "depends": [
    "cudatoolkit >=11.1,<11.2",
    "ffmpeg >=4.2",       <-- Remove this line
    "jpeg >=9b",
    "libpng",
    "numpy >=1.11",
    "pillow >=4.1.1",
    "python >=3.7,<3.8.0a0",
    "pytorch 1.8.1"
  ],
  "license": "BSD",
  "name": "torchvision",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1616645473952,
  "version": "0.9.1"
}
```

**Comment by vadimkantorov** [comment]
Also, hard Python constrain on `<3.8.0a0`. @malfet Seems like recurring problems on not allowing Python3.9? Related: https://github.com/pytorch/vision/issues/4240

**Comment by prabhat00155** [comment]
> Thanks @prabhat00155. That answers a huge question for me. Follow up question. I can download the .bz2 file from Anaconda.org and modify the info/index.json to remove the ffmpeg dependency? Is this effectively the same as building from source without ffmpeg? Or will I run into stability problems with torchvision?
> 
> ```json
> {
>   "arch": "x86_64",
>   "build": "py37_cu111",
>   "build_number": 0,
>   "depends": [
>     "cudatoolkit >=11.1,<11.2",
>     "ffmpeg >=4.2",       <-- Remove this line
>     "jpeg >=9b",
>     "libpng",
>     "numpy >=1.11",
>     "pillow >=4.1.1",
>     "python >=3.7,<3.8.0a0",
>     "pytorch 1.8.1"
>   ],
>   "license": "BSD",
>   "name": "torchvision",
>   "platform": "linux",
>   "subdir": "linux-64",
>   "timestamp": 1616645473952,
>   "version": "0.9.1"
> }
> ```

ffmpeg is not a hard dependency. You can just install torchvision without installing ffmpeg. You just need pytorch and numpy. This is what I need to do to install torchvision using conda:
```
conda install pytorch torchvision cpuonly -c pytorch
pip install numpy
```
If you downloaded the package from anaconda.org, then you could do the following:
```
conda install pytorch -c pytorch
pip install numpy
conda install torchvision-0.10.0-py38_cpu.tar.bz2 
```

**Comment by prabhat00155** [comment]
> Also, hard Python constrain on `<3.8.0a0`. @malfet Seems like recurring problems on not allowing Python3.9? Related: #4240

This constraint is specific to the file downloaded from anaconda. There are different files for different python versions as you can see [here](https://anaconda.org/pytorch/torchvision/files). The above download seems to be for Python 3.7.
Are you facing any issues installing torchvision for Python 3.9?

**Comment by prabhat00155** [comment]
@rwmajor2 Were you able to build torchvision?

**Comment by prabhat00155** [comment]
@rwmajor2 I am closing this issue. Feel free to reopen this if you have any more questions.
