### ISSUE TITLE
Use torchrun instead of the deprecated torch.distributed.launch

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#4450]
`torch.distributed.launch` is deprecated in favour of `torchrun`.

We should update the various references README.md to use `torchrun` instead. The migration guide is documented [here](https://pytorch.org/docs/master/elastic/run.html#transitioning-from-torch-distributed-launch-to-torchrun) - since we already read everything from the env variables, all we need to do is to change

```py
python -m torch.distributed.launch --use_env  ...
```

into

```py
torchrun ...
```

(i.e. remove the `--use_env` flag, which is the default in torchhub)

The files that need an update are:

- https://github.com/pytorch/vision/tree/main/references/classification
- https://github.com/pytorch/vision/tree/main/references/detection
- https://github.com/pytorch/vision/tree/main/references/segmentation
- https://github.com/pytorch/vision/tree/main/references/video_classification

**Comment by vadimkantorov** [comment]
With `torchrun`, how does it select the Python distribution? Sometimes there is obsolete system's `python -> python2`

**Comment by NicolasHug** [comment]
> With torchrun, how does it select the Python distribution? Sometimes there is obsolete system's python -> python2

The same way the distribution gets selected when one does `python`, which is the current way that we call `python -m torch.distributed.launch`: it will pick the first `python` executable file that's in the `$PATH`.

> This is also funny, that torchrun migration direction goes in reverse to pip ... -> python -m pip ... official Python's recommendation

It's related but slightly different. The reason `python -m pip` is recommended over `pip` is because there might be a `pip` executable in the `$PATH` that's related to a different Python version than the version of `python`. Like `pip` is actually related to a python2 while your `python` command actually runs python3.

In all cases (tochrun or python -m), the first `python` in the `$PATH` is used, so there's no discrepancy here.
