### ISSUE TITLE
Pytorch with cuda11.1 could't be downloaded in CI.

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/vision#4458]
### 🐛 Describe the bug

@seemethere , 
the PR https://github.com/pytorch/vision/pull/4082 removed the -c conda-forge.
![image](https://user-images.githubusercontent.com/16190118/134324142-9577eba2-20d7-4ced-a4d0-af3710e9eb39.png)

After the change,  I found that torch with cu11.1 couldn't be downloaded via 
conda install -y -c "pytorch-${UPLOAD_CHANNEL}" "pytorch-${UPLOAD_CHANNEL}"::pytorch "${cudatoolkit}" pytest.

Is it expected?

### Versions

after #4082

**Comment by prabhat00155** [comment]
Are you trying to install pytorch on cuda 11.1? You can try: `conda install pytorch cudatoolkit=11.1 -c pytorch-nightly -c nvidia`

**Comment by mszhanyi** [comment]
The link is 
https://app.circleci.com/pipelines/github/pytorch/vision/10705/workflows/25d6740c-6c8a-42fd-8cbf-7a54222ebb38/jobs/816118

```
Installing PyTorch with cudatoolkit=11.1
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=11.1

Current channels:

  - https://conda.anaconda.org/pytorch-nightly/win-64
  - https://conda.anaconda.org/pytorch-nightly/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
```

**Comment by prabhat00155** [comment]
I see. Looks like you need conda-forge on windows.

**Comment by prabhat00155** [comment]
Closing this issue, PR merged: https://github.com/pytorch/vision/pull/4475.
