### ISSUE TITLE
List of issues related to video

### ISSUE THREAD

**Issue by prabhat00155** [pytorch/vision#4459]
This issue is to track all the video related bugs.
- [ ] https://github.com/pytorch/vision/issues/4430
- [ ] https://github.com/pytorch/vision/issues/4429
- [ ] https://github.com/pytorch/pytorch/issues/65000

**Comment by prabhat00155** [comment]
FYI @bjuncek

**Comment by bjuncek** [comment]
Closed, superseeded by #5720
