### ISSUE TITLE
Add minimum image size to models page

### ISSUE THREAD

**Issue by logankilpatrick** [pytorch/vision#4462]
## 📚 Documentation

I am trying to test a bunch of different models from: https://pytorch.org/vision/stable/models.html. However, it is not clear if there are other changes that need to be made to my code like changing the image size in the transformation. Adding in a note on the image size under each model would be very helpful here!

**Comment by NicolasHug** [comment]
Thanks for reporting the issue @logankilpatrick , you're right, this kind of information would be helpful.

I believe there has been some related discusion recently in https://github.com/pytorch/vision/issues/3921, so I'll close this one to avoid duplicates if you don't mind. You are more than welcome to contribute on the other thread!
