### ISSUE TITLE
Support grayscale image-like tensors for adjust_contrast and adjust_saturation functions

### ISSUE THREAD

**Issue by VinhLoiIT** [pytorch/vision#4466]
### 🚀 The feature

The following functions in `functional_tensor.py` should be updated to work with single-channel image-like tensor, i.e. `(1, H, W)`.
1. `adjust_contrast`. Similar implementation in Pillow is:
```python
    enhancer = ImageEnhance.Contrast(img)
    img = enhancer.enhance(contrast_factor)
```
2. `adjust_saturation`. Similar implementation in Pillow is:
```python
    enhancer = ImageEnhance.Color(img)
    img = enhancer.enhance(saturation_factor)
```

### Motivation, pitch

When updating the documentation, I discovered some transform functions that work well on one channel PIL image (image with `mode='L'`), yet they only support 3-channel tensors as in #4457.

Therefore, I think it is necessary to re-check and implement those functions to provide a similar result as in transforming PIL images.

Also, after solving this issue, we can further enable users to use `AutoAugment` and similar classes to work with grayscale image tensors. Currently, grayscale pillow images can use these augmentations without errors, but not with single-channel image tensors, i.e. `(1,H,W)`

cc @vfdev-5 @datumbox

**Comment by VinhLoiIT** [comment]
Currently, while scanning through the source code for test cases, I find that the test cases for `adjust_contrast` is defined as follows:

```python
@pytest.mark.parametrize('device', cpu_and_gpu())
@pytest.mark.parametrize('dtype', (None, torch.float32, torch.float64))
@pytest.mark.parametrize('config', [{"contrast_factor": f} for f in [0.2, 0.5, 1.0, 1.5, 2.0]])
def test_adjust_contrast(device, dtype, config):
    check_functional_vs_PIL_vs_scripted(
        F.adjust_contrast,
        F_pil.adjust_contrast,
        F_t.adjust_contrast,
        config,
        device,
        dtype
    )
```

which is essentially linked to the `check_functional_vs_PIL_vs_scripted` function that it tests only on 3 channels image-like tensors:

```python
def check_functional_vs_PIL_vs_scripted(fn, fn_pil, fn_t, config, device, dtype, tol=2.0 + 1e-10, agg_method="max"):

    script_fn = torch.jit.script(fn)
    torch.manual_seed(15)
    tensor, pil_img = _create_data(26, 34, device=device)  # this creates 3 channels only
    batch_tensors = _create_data_batch(16, 18, num_samples=4, device=device)
    ...
```

So, I wonder that some functions, which are documented as they support 1 or 3 channels, are tested on 1 channel tensors or not? For example, `adjust_brightness` is one of those functions.

Please correct me if I'm wrong so that I can further create a PR for this.

cc @datumbox

**Comment by datumbox** [comment]
@VinhLoiIT Thanks for digging into this. Yes you are right, we test only for 3 channels and obviously that's not great. 

A PR that improves the situation in this direction is very welcome.

**Comment by vfdev-5** [comment]
@datumbox @VinhLoiIT I can help or guide also with this issue/feature request.

**Comment by vfdev-5** [comment]
@VinhLoiIT I submitted a draft PR on how to enhance the gray images support for `adjust_contrast`. I think something similar can be done for `adjust_saturation`. Once, we figure out all hidden issues (if there are) with `adjust_contrast` and merged my PR, if you would like to submit another one for  `adjust_contrast` it would be awesome !

**Comment by VinhLoiIT** [comment]
> @VinhLoiIT I submitted a draft PR on how to enhance the gray images support for `adjust_contrast`. I think something similar can be done for `adjust_saturation`. Once, we figure out all hidden issues (if there are) with `adjust_contrast` and merged my PR, if you would like to submit another one for `adjust_contrast` it would be awesome !

Thank you, with a glance through the `functional_tensor.py` file, I have found these two related functions as below:
- `adjust_contrast`
- `adjust_saturation`

I guess that this issue is because of the `rgb_to_grayscale` method calls, which could be done without converting, i.e. broadcasting. However, I think we have to write some test cases for this. I've had some struggles with the tensor-pillow comparison and your PR is really helpful. Do I have to create a PR for this repo or your fork?

**Comment by vfdev-5** [comment]
@VinhLoiIT yes, I agree with you about `rgb_to_grayscale` and that we can bypass it if input image is gray.
I think you can checkout this branch: https://github.com/vfdev-5/vision/tree/add-gray-support-adjust_contrast and submit a PR to this repo: pytorch/vision. After the first PR has been merged you can update your branch to `main` and I think we will be good.

**Comment by VinhLoiIT** [comment]
Sure I'll do. I'll create a PR soon.

**Comment by vfdev-5** [comment]
@VinhLoiIT the PR was merged you can just fork from pytorch/vision:main and not bother with my fork

**Comment by VinhLoiIT** [comment]
I've created a PR, please kindly have a look.
