### ISSUE TITLE
[Feature Request] Add EfficientNetV2

### ISSUE THREAD

**Issue by bratao** [pytorch/vision#4468]
### 🚀 The feature

Implement EfficientNetV2

https://arxiv.org/abs/2104.00298

"A new family of convolutional networks that have faster training speed and better parameter efficiency than previous models. Our experiments show that EfficientNetV2 models train much faster than state-of-the-art models while being up to 6.8x smaller. "

### Motivation, pitch

It´s a new version of a popular model that was just implemented in torch vision.

### Alternatives

There are some implementations on the Web, 
https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/efficientnet.py

https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_classification/Test11_efficientnetV2/model.py

cc @datumbox

**Comment by datumbox** [comment]
Thanks @bratao. I agree it's worth considering adding them. I've added the model on the following issue that tracks all the model additions #2707. I'll close this one to keep things tidy. Let's continue the discussion on the other thread.
