### ISSUE TITLE
STL dataset returns test fold if fold is misspecified

### ISSUE THREAD

**Issue by reynoldscem** [pytorch/vision#447]
If you miss-spell, or otherwise pass an invalid fold to the STL dataset it will set the data and labels to that of the test set.

Can be seen here:

https://github.com/pytorch/vision/blob/fa377c47d0f444f9497678b6641b360cb665f8f9/torchvision/datasets/stl10.py#L75

Other datasets appear to raise a `ValueError` in their constructor when passed an invalid fold:
https://github.com/pytorch/vision/blob/fa377c47d0f444f9497678b6641b360cb665f8f9/torchvision/datasets/mnist.py#L202

Would be good to do so for STL-10 also.

**Comment by fmassa** [comment]
Agree, it would be good to improve that. Would you mind sending a PR?

**Comment by reynoldscem** [comment]
Will do!

**Comment by reynoldscem** [comment]
@fmassa PR here:

https://github.com/pytorch/vision/pull/449

**Comment by soumith** [comment]
fixed via https://github.com/pytorch/vision/pull/449
