### ISSUE TITLE
Windows CI failing

### ISSUE THREAD

**Issue by prabhat00155** [pytorch/vision#4483]
https://app.circleci.com/pipelines/github/pytorch/vision/10734/workflows/d1dec21d-0d67-4a8d-8510-94e6a8627228/jobs/819033

Failure seems to be coming from pytorch.
```
File "C:\tools\miniconda3\lib\site-packages\torch\__init__.py", line 138, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\tools\miniconda3\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies
```

cc @peterjc123 @nbcsm @guyang3532 @maxluk @gunandrose4u @mszhanyi @seemethere

**Comment by malfet** [comment]
Seems to have caused by PyTorch update, I guess we'll see after the next nightly.

**Comment by malfet** [comment]
This is a regression caused by https://github.com/pytorch/pytorch/pull/62175 or its reland https://github.com/pytorch/pytorch/pull/65608 (both of the PRs are reverted at the moment), which introduced cudart64_102.dll and cupti64_102.dll dependency to libtorch_cpu.so, see screenshot below:
![image](https://user-images.githubusercontent.com/2453524/134784583-edf1eb2f-28b9-4795-b934-d9ab10c3c6ec.png)

Should fix itself once nightly builds no longer attempt to build with CUPTI (or package it correctly)

**Comment by peterjc123** [comment]
@malfet Just curious why torch_cpu.dll depends on the CUDA libs? Doesn't this sound a bit weird?

**Comment by cloudhan** [comment]
OK, shit happens, AGAIN. The reason is quite simple, conda have seperate (AGAIN) packaging logic.

**Comment by cloudhan** [comment]
@malfet You are take the wrong screenshot.

### **My PR is perfectly fine. The problem goes to CI environment. Either your builder or your conda package.**

The https://app.circleci.com/pipelines/github/pytorch/vision/10734/workflows/d1dec21d-0d67-4a8d-8510-94e6a8627228/jobs/819033 mentioned the pytorch package with version `py3.8_cuda11.1_cudnn8_0`

The dependent pacakge `cudatoolkit=11.1`
```powershell
conda install cudatoolkit=11.1 -c conda-forge
ls $env:CONDA_PREFIX\Library\bin | %{ $_.Name } | sls cu
```
shows
```
cublas64_11.dll
cublasLt64_11.dll
cudadevrt.lib
cudart64_110.dll
cufft64_10.dll
cufftw64_10.dll
cupti64_2020.2.1.dll        # <--- This is the library that is missing, see blow.
curand64_10.dll
cusolver64_11.dll
cusolverMg64_11.dll
cusparse64_11.dll
```

`$env:Path` is perfectly set by conda.
![image](https://user-images.githubusercontent.com/1279292/134793308-4a6eb97c-0e97-4431-8bfc-c9c998b43bdf.png)

inspecting into https://anaconda.org/pytorch-nightly/pytorch/1.11.0.dev20210925/download/win-64/pytorch-1.11.0.dev20210925-py3.8_cuda11.1_cudnn8_0.tar.bz2. The package with version `dev20210924` is missing from the conda channel, so `dev20210925` is used.

![image](https://user-images.githubusercontent.com/1279292/134793375-394ac9d7-8b61-46f8-88a2-9863362678a4.png)

`cupti64_2020.2.1.dll` is provided by the `cudatoolkit=11.1`
`cupti64_2020.2.0.dll` is required by the `torch_cpu.dll`

**Comment by cloudhan** [comment]
The problem boils down to why conda package `cudatoolkit=11.1` package `cupti64_2020.2.1.dll`.

For everyone's information.
![图片](https://user-images.githubusercontent.com/1279292/134795451-8de4941c-25f4-4adb-8a2a-04d4c239560f.png)

**Comment by cloudhan** [comment]
Version mismatch comes from https://github.com/conda-forge/cudatoolkit-feedstock/blob/593837933a3e5cdbb5aed422fbea948f29e27f9e/recipe/meta.yaml#L144 and https://github.com/pytorch/builder/blob/3e2535a2b346a00f775140285a07cdf456dda136/windows/internal/cuda_install.bat#L116

**Comment by mszhanyi** [comment]
Theoretically, (Major.Minor.Update) update  change shouldn't change the interface.

**Comment by cloudhan** [comment]
@mszhanyi  But what if nvidia release cuda 11.1.2 with `cupti64_2020.2.2.dll` and then conda package update the `cudatoolkit==11.1`

**Comment by mszhanyi** [comment]
> @mszhanyi But what if nvidia release cuda 11.1.2 with `cupti64_2020.2.2.dll` and then conda package update the `cudatoolkit==11.1`

There isn't 11.1.x after 11.2
