### ISSUE TITLE
torchvision.transforms Images are incorrect

### ISSUE THREAD

**Issue by MaxVanDijck** [pytorch/vision#4486]
### 📚 The doc issue

All the example astronaut images on https://pytorch.org/vision/stable/transforms.html show the same pad transform as shown:

![image](https://user-images.githubusercontent.com/50382570/134827438-51b4bdc3-d373-47e1-a71b-eb4ec6202340.png)

![image](https://user-images.githubusercontent.com/50382570/134827446-b538d3db-e55b-4a33-becf-b6855e30dd35.png)

![image](https://user-images.githubusercontent.com/50382570/134827461-840bf56c-cb35-463a-a9e5-7d6077c5a208.png)

### Suggest a potential alternative/fix

Images should be changed to images that show the correct transforms

**Comment by NicolasHug** [comment]
Thanks for the report @MaxVanDijck 

The things you're showing aren't supposed to represent the specfic image transformations, they are just thumbnails that link to the example where each transformation is illustrated in more details.

I don't think sphinx-gallery supports having different thumbnails for different backlinks, that would involve a lot of manual work that we would prefer to avoid anyway. We can however change the thumbnail to make it more obvious https://sphinx-gallery.github.io/stable/configuration.html#choosing-the-thumbnail-image. I'm  not sure which one would be best though. Perhaps the GrayScale image one, as it's bigger? (https://pytorch.org/vision/stable/auto_examples/plot_transforms.html#grayscale)

If you have a better idea we're all ear :)
Feel free to submit a PR as well if you're interested!

**Comment by MaxVanDijck** [comment]
Maybe rather than showing one specific transform we can use another image that makes it clearer that it is linking to the gallery? Such as a larger image with multiple different transforms shown for example one like so:

![Untitled](https://user-images.githubusercontent.com/50382570/135005258-5135fe6d-c533-4c22-bc9a-4100406a27e9.png)

Using:
https://sphinx-gallery.github.io/stable/configuration.html#providing-an-image-for-the-thumbnail-image

**Comment by NicolasHug** [comment]
That sounds great @MaxVanDijck !

**Comment by NicolasHug** [comment]
@MaxVanDijck just making sure, would you like to submit a PR for this, or are you OK for us to let someone else grab it? We're not in a rush so if you want to do it we can definitely wait a few days if needed

**Comment by MaxVanDijck** [comment]
@NicolasHug You can let anyone grab this issue!

**Comment by kingyiusuen** [comment]
I'd like to give this a try!
