### ISSUE TITLE
Replace uses of `apex.amp` with PyTorch's amp in references

### ISSUE THREAD

**Issue by fmassa** [pytorch/vision#4509]
Some reference scripts have added support for AMP via APEX a couple of years ago, see https://github.com/pytorch/vision/blob/4bf608633f9299aeda61b08ae126961acaadec22/references/classification/train.py#L17 for one example

PyTorch [now natively supports AMP in the `torch.cuda.amp` namespace](https://pytorch.org/docs/stable/amp.html?highlight=amp#module-torch.cuda.amp), so we should use PyTorch's AMP instead of apex for simplicity.

The replacement needs to happen on the following scripts:
- [x] Classification
- [x] Detection #4933
- [x] Segmentation #4994
- [ ] [Video Classification](https://github.com/pytorch/vision/blob/main/references/video_classification/train.py)

cc @datumbox

**Comment by datumbox** [comment]
Do you know if manually installing apex from the repo will still be needed? Cause if this step is removed it would be great.

**Comment by fmassa** [comment]
We won't need to install apex anymore, and everything will be handled by PyTorch now. We only used apex for amp in the reference scripts

**Comment by prabhat00155** [comment]
The name of the argument is [apex](https://github.com/pytorch/vision/blob/5f0edb97b46e5bff71dc19dedef05c5396eeaea2/references/classification/train.py#L388). Now that we are going to use Pytorch's amp for mixed precision training, should we update this or keep it for BC?

**Comment by datumbox** [comment]
@prabhat00155 I don't think it's a problem to change the name. We don't have any models that actually use it for training and BC on the references is not our primary focus anyway. My view is that it's fine to update it.

**Comment by fmassa** [comment]
I second @datumbox comment, let's just change the argument name -- note that the reference scripts are not part of our API

**Comment by kbozas** [comment]
I am interested in the Video Classification bit.

**Comment by datumbox** [comment]
Sounds good @kbozas. Feel free to add me as a Reviewer on your upcoming PR.
