### ISSUE TITLE
Generate colors from random color palette in draw_bounding_boxes

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#4528]
### 🚀 The feature

The current default white color looks bad. Maybe we can generate colors from palette as we do in drawing masks?

### Motivation, pitch

It should be simple tweak to `_generate_color_palette` to pass num_boxes and get a List of RGB values. Instead of List[Tensor]. The fix is simple and that can be passed to get RGB colors.

### Alternatives

Users can anyway use `color="white"` to get white boxes.

### Additional context

It's simple issue and good-first. We can probably wait for some new contributor :smiley:  to join.

**Comment by gessha** [comment]
I can take this if that's okay.

**Comment by oke-aditya** [comment]
I'm glad that you want to take it. 
Just need a green signal from the maintainers @NicolasHug @datumbox

**Comment by NicolasHug** [comment]
Thanks for the proposal @oke-aditya and @gessha for volunteering.

That sounds good to me, we should just make sure that the same color is generated for all boxes with the same label.

**Comment by oke-aditya** [comment]
Well I'm not sure how we would ensure that same color is generated for all boxes with same label.
My thoughts were to generate color palette equal to number of boxes. And then we simply pick ith color from the palette.

We don't keep consistency of randomly generating same color for same label in drawing segmentation masks too.

**Comment by NicolasHug** [comment]
> Well I'm not sure how we would ensure that same color is generated for all boxes with same label.

We can generate num_labels colors and then assign one color per label. Obviously we don't need to do that if `labels` isn't specified

> We don't keep consistency of randomly generating same color for same label in drawing segmentation masks too.

True but `draw_segmentation_masks` doesn't accept a label anyway, as it probably doesn't need one.

**Comment by oke-aditya** [comment]
Great, I think it should be feasible with some refactor. As of now we plot each bbox and then the labels separately.

@gessha feel free to send a PR!

**Comment by ABD-01** [comment]
Yes, I can if no one's working on it.

I guess the main change involved will be here
https://github.com/pytorch/vision/blob/a75dc89abbbb233469d1dbe2ee00ee012dd70522/torchvision/utils.py#L203-L204
Just to make the variable `colors` be a list returned from [`_generate_color_palette`](https://github.com/pytorch/vision/blob/a75dc89abbbb233469d1dbe2ee00ee012dd70522/torchvision/utils.py#L303), right?

**Comment by oke-aditya** [comment]
Yes and use the colors the generated from the palette in draw_bounding_boxes. 

Create colors upto num_labels. 

Map each label to a color. (This is automatically done)

Since labels is a list and generated color palette is also a list. Both have the same length. 
(As we generated colors equal to num_labels)

Use these colors to draw boxes.
