### ISSUE TITLE
Base class for models

### ISSUE THREAD

**Issue by kazhang** [pytorch/vision#4569]
### 🚀 The feature

Introduce a base class for all TorchVision models. The base class defines common interfaces and attributes.

### Motivation, pitch

We can track the model instantiation similar to [dataset instantiation](https://github.com/pytorch/vision/blob/5f0edb97b46e5bff71dc19dedef05c5396eeaea2/torchvision/datasets/vision.py#L36).
We can also define a `reset_parameters` interface to address #3410.

### Alternatives

Adding logging and `reset_parameters` to each of the models manually. The approach is not future proof, we might forget to do that for new models.

cc @datumbox

**Comment by datumbox** [comment]
I think it's a reasonable idea that will provide structure on the API of models. I assume only the main classes of the models will implement this API, not submodules like `Bottleneck` etc, right? Another thing that might worth clarifying in this RFC is how `reset_parameters` will work for models that contain backbones (such as detection and segmentation).

**Comment by vadimkantorov** [comment]
In my opinion, if there's not much functionality that's best inherited (e.g. `reset_parameters` could even be introduced as an empty method on Modules since it's so core and frequent or just be used with duck typing), it's better to keep the inheritance as simple as possible since users are reading this code as example for their own models, so it's best to avoid making it more complex unless absolutely necessary/helpful.

**Comment by kazhang** [comment]
I agree that we should avoid unnecessary inheritance so that the implementation is more readable. I open this issue to gather generic functionalities that should be applied to all models. 

**should submodules implement the `reset_parameters` method?**
I hope not, the submodules are usually constructed before the main class, even if they implement the `reset_parameters`, their initialization will be reset by the `reset_parameters` of main class, unless we introduce extra complexity to either
* check if a submodule has been initialized and filter if so. 
* Alternatively, iterate through submodules and check if it has `reset_parameters`, if not, use the default initialization.

Is there a need to initialize the submodule differently in real world? otherwise, I would recommend only the main class should implement the `reset_parameters` method.
**models with backbones**
I think backbone is equivalent to submodule.

**Comment by kazhang** [comment]
Let's close this issue for now until we find strong enough feature set to be added to a generic top-level class.
