### ISSUE TITLE
the layer1's stride should be set to 2?

### ISSUE THREAD

**Issue by PanXiebit** [pytorch/vision#457]
https://github.com/pytorch/vision/blob/5b75a277423dd455df05b9789689c5414b334daf/torchvision/models/resnet.py#L106  

I think the layer1's step size should be set to 2, the original feature map size changed from 112 to 56, and if set to 1, then there is no shrtcut in layer1, because the options of the shortcut: if stride != 1 or self.inplanes != planes * block.expansion:

**Comment by fmassa** [comment]
There is indeed a difference between the implementations in the original resnet paper and the one in torchvision, but it's not at the place you mentioned.
Indeed, the original resnet model has the varying stride in the 1x1 convolution, while our [implementation has it in the 3x3 convolution](https://github.com/pytorch/vision/blob/mase/torchvision/models/resnet.py#L64), see discussion in https://github.com/pytorch/vision/issues/191.
I'm closing this issue in favour of #191 , but feel free to comment if you think that something else than what is discussed in #191 should be changed
