### ISSUE TITLE
TORCHVISION REFERENCE disappeared in http://pytorch.org/docs/0.3.1

### ISSUE THREAD

**Issue by acgtyrant** [pytorch/vision#458]
Even the master version has the TORCHVISION REFERENCE.

**Comment by fmassa** [comment]
Thanks for the report. @chsasank do you know what happened here?

**Comment by chsasank** [comment]
To diagnose this, we need to see jenkin build logs. But I can't somehow open http://build.pytorch.org.

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
