### ISSUE TITLE
Always download MNIST from PyTorch mirror

### ISSUE THREAD

**Issue by equaeghe** [pytorch/vision#4634]
### 🐛 Describe the bug

Torchvision by default downloads MNIST [from the original server](http://yann.lecun.com/exdb/mnist/). The owner there explicitly requests

> Please refrain from accessing these files from automated scripts with high frequency. Make copies!

Currently, MNIST is already available on the PyTorch mirror: see https://github.com/pytorch/vision/pull/3544 and https://github.com/pytorch/vision/issues/3549. It seems that the polite thing to do is to never download from the original server.

### Versions

Collecting environment information...
PyTorch version: 1.9.0a0+gitd69c22d
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Gentoo/Linux (x86_64)
GCC version: (Gentoo 11.2.0 p1) 11.2.0
Clang version: 12.0.1
CMake version: version 3.20.5
Libc version: glibc-2.33

Python version: 3.9 (64-bit runtime)
Python platform: Linux-5.14.12-gentoo-b-x86_64-AMD_Ryzen_7_PRO_4750U_with_Radeon_Graphics-with-glibc2.33
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] numpydoc==1.1.0
[pip3] torch==1.9.0a0+gitd69c22d
[pip3] torchvision==0.10.0a0
[conda] Could not collect

cc @pmeier

**Comment by NicolasHug** [comment]
> > Furthermore, AFAIK the author only authorized us to use the mirror in case the original server is unavailable for some reason.
> 
> Oh, that seems like strange restriction. I've seen MNIST elsewhere and didn't realize the author might claim some kind of database right, as that is not mentioned on their website. But if this is the case I understand the current approach.

I think this is the key bit here. If we don't have permission to put our mirror first, then there isn't much we can do.

But *if* we're allowed to, I would agree that it would be something good to consider. While we (the torchvision package) "only" downloads such datasets a few times a day, the fact that we're exposing such API will necessarily increase the number of download by a lot, just because we're making it very easy and convenient to do so.
