### ISSUE TITLE
Multi pretrained weights: Cleanups and Refactoring

### ISSUE THREAD

**Issue by jdsgomes** [pytorch/vision#4652]
Candidates:
- [x] Reduce code duplication on model builders by refactoring. For example potentially push the weigh loading mechanism in the private builder methods currently inherited from `torchvision.models`. Also we could provide a `pretrained` deprecation method.
- [x] Review recipe links and ensure they are accurate for all Community Contributed models. Check if possible for some of them to remap their training process to our current ref scripts.
- [x] Decide how quantized models will link to their unquantized versions.
- [x] Naming conventions:
  - The name of the `Weights` base `Enum` class and the naming convention of the inheriting classes. Also make sure that all classes are aligned with the model builder names. How are we going to handle `_` in names (for example on inception_v3 and the resnext models)?
  - The name of the `WeightEntry` data class.
  - The name of `Weights.verify()` method (because it does more than just verification).
  - The names of the enum values; also their styles (all capital?). Example: `ImageNet1K_RefV1`
  - Currently the `_RefV1` of one model doesn't have to be `_RefV1` of another model. For example [ResNet](https://github.com/pytorch/vision/blob/18cf5ab1c1307e9d0e1b1e4d26ce9c45e04f8376/torchvision/prototype/models/resnet.py#L86-L91) vs [RegNets](https://github.com/pytorch/vision/blob/18cf5ab1c1307e9d0e1b1e4d26ce9c45e04f8376/torchvision/prototype/models/regnet.py#L110-L115) use different recipes with the same enum value. In other cases, we skip `_RefV1` and go directly to `_RefV2`, for example the [WideResNet50 weights](https://github.com/pytorch/vision/blob/18cf5ab1c1307e9d0e1b1e4d26ce9c45e04f8376/torchvision/prototype/models/resnet.py#L211-L222). Is this a problem?
- [x] Decide the signature of `models._api.get_weight()` and make it public. Ensure it's torchhub-friendly.

cc @datumbox @pmeier @bjuncek @NicolasHug

**Comment by jdsgomes** [comment]
Just opening the discussion here regarding the naming for `Weights` and `WeightEntry`. As This classes store metadata about weights and how they were generated (recipe + transforms) rather than the actual weights so I think we could try to find a better name.

Having said that I'm struggling to find a much better name, but want to leave some suggestions for discussion:
- PretrainedModelEnum and PretrainedModel
- PretrainedModel and PretrainedModelEntry
- Weights and WeightsInfo

Open for more suggestions. Naming IS hard :)

**Comment by jdsgomes** [comment]
Inside the `Weights` class we have a `verify` method that has some side effects depending on the input parameter. I suggest to change this to `build` or `create` it would be clear that we are trying to build an object from a string or from another object of the same type (in this case it will be an identity function). And this builder would throw an exception if the arguments were invalid.

**Comment by datumbox** [comment]
I had an offline discussion with @NicolasHug and we discussed the following optimizations:

1. For the Weights classes, keep using necessary capitalzation to help readability such as Res**N**e**X**t to be aligned with bibliography but ensure this is consistent across the codebase (for example `VisionTransformer_B_32Weights` => `ViT_B_32Weights`)
2. Use underscore where they are on the builder. For example `InceptionV3Weights => Inception_V3Weights`
3. Rename classes `Weights => WeightsEnum`, `WeightEntry => Weights`
4. Rename values `ImageNet1K_Community => ImageNet1K_V1`, `ImageNet1K_RefV2 =>  ImageNet1K_V2` 
5. Make get_weight work using the fully qualified name and expose it publicly get_weight and filter it from tests
6. Implement the `default` mechanism using Enum aliases (`default = ImageNet1K_RefV2`)
