### ISSUE TITLE
Improve transforms

### ISSUE THREAD

**Issue by Oktai15** [pytorch/vision#466]
Hi there!

At this moment, ```torchvision``` is so poor; in particular, transforms. It really restricts our ability for data augmentation. However, people have already done a few nice libraries for it. For instance:
https://github.com/mdbloice/Augmentor (already has compatibility with PyTorch)
https://github.com/aleju/imgaug

What about contact with authors and merged these great jobs to ```torchvision.transforms```?

**Comment by Oktai15** [comment]
@fmassa, okay, thanks, it will cool :) Actually, I strongly recommend to look at this libraries instead of write new code, but, of course, you know better :)

By the way, don't forget about segmentation!

**Comment by fmassa** [comment]
Don't worry, I won't forget about instance segmentation :-)

**Comment by Oktai15** [comment]
@fmassa sorry for offtop: I would like to notice that first provided library uses excellent way to transform two or more images. All transforms take list of images rather than just one image like transform in ```torchvision```. For example:

```
def perform_operation(self, images):
#init random values
for image in images:
    augmented_images.append(do(image))
return augmented_images
```
I suppose it's great idea ^^

**Comment by fmassa** [comment]
It's indeed much simpler in some cases, but also more restrictive in more general setups.

For the record, this is something that has been bugging me for a long time, see https://github.com/pytorch/vision/issues/9 and https://github.com/pytorch/vision/issues/230 for some context.

In many cases, you don't want to pass all transforms to all data (no color augmentation for segmentation masks for example), and the approach you mentioned doesn't easily allows that (without making the API overly complex).

**Comment by nnop** [comment]
The codes of [`imaug` ](https://github.com/aleju/imgaug) is somehow far more complicated.

**Comment by fmassa** [comment]
@nnop yes, I saw `imaug` and agree that it is very complex. I would rather have a simpler API, even if it requires having to write a bit more code.
