### ISSUE TITLE
Document the default data proprocessing

### ISSUE THREAD

**Issue by jhostetler** [pytorch/vision#468]
For example, torchvision MNIST is scaled to [0,1], whereas the standard MNIST dataset is in [0, 255]. This is not mentioned in the documentation, which instead just links to the original MNIST page, suggesting that the dataset is in the format described on that page. Similarly, standard CIFAR is in [0, 255] but torchvision CIFAR is in [-1, 1].

**Comment by fmassa** [comment]
All the datasets in torchvision that you mentioned do not have any pre-processing.
Both the datasets you have mentioned are in the range 0-255, and the dataset returns them as PIL Images.
What might be different is the pre-processing that is specific to an example that you have seen, which is independent of torchvision.

For the pre-trained models that we provide, we specify the pre-processing that we perform in the docs.
