### ISSUE TITLE
why transforms.RandomRotation is not working?

### ISSUE THREAD

**Issue by ToTheBeginning** [pytorch/vision#470]
I install torchvision through conda, the version is 0.2, and the pytorch vision is 0.4

When i apply transforms.RandomRotation operation on image, then the errors occur
`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-8c2081e16199> in <module>()
----> 1 img = trans_rot(img)

/home/wyz/anaconda2/lib/python2.7/site-packages/torchvision/transforms/transforms.pyc in __call__(self, img)
    635         angle = self.get_params(self.degrees)
    636 
--> 637         return F.rotate(img, angle, self.resample, self.expand, self.center)
    638 
    639 

/home/wyz/anaconda2/lib/python2.7/site-packages/torchvision/transforms/functional.pyc in rotate(img, angle, resample, expand, center)
    550         raise TypeError('img should be PIL Image. Got {}'.format(type(img)))
    551 
--> 552     return img.rotate(angle, resample, expand, center)
    553 
    554 

TypeError: rotate() takes at most 4 arguments (5 given)`

as far as i know, the other ops are normal.

**Comment by fmassa** [comment]
For posteriority, `rotate` requires PIL 4.0 or greater. We might want to enforce that in our setup.py.
