### ISSUE TITLE
Missing docs for functional transforms

### ISSUE THREAD

**Issue by karandwivedi42** [pytorch/vision#476]
Couldn't find them in pytorch docs (http://pytorch.org/docs/master/torchvision/transforms.html).

**Comment by fmassa** [comment]
Indeed, looks like the link is not present in https://github.com/pytorch/vision/blob/master/docs/source/transforms.rst

**Comment by vishwakftw** [comment]
I have found a fix for this, and will issue a PR soon. @fmassa
