### ISSUE TITLE
Some models warn about `nn.init.kaiming_normal`

### ISSUE THREAD

**Issue by moskomule** [pytorch/vision#479]
Hi, some models such as DenseNet warn because they use `nn.init.kaiming_normal` etc.  If you don't care about the backward compatibility, I can send a PR soon.

**Comment by fmassa** [comment]
Hey,
Yes, please, send a PR. There is no problem with backwards compatibility, because both the `nn.init.kaiming_normal` and `nn.init_kaiming_normal_` are exactly the same functions

**Comment by fmassa** [comment]
This has been fixed by #481
