### ISSUE TITLE
How to monitor and when to retrain the object detection model in production?

### ISSUE THREAD

**Issue by IamExperimenting** [pytorch/vision#4802]
I recently moved regression model to production and I’m monitoring the model drift and data drift using statistical tests, based on their distributions i retrain the model. 

Could you please tell me how to monitoring the object detection model and detect drifts ? 

Do you use statistical test to detect drifts? If yes, how do you do that? And which value you as an input to detect?

Please guide me? Even if you could provide any relevant article also would help me

Thanks in advance😊

**Comment by oke-aditya** [comment]
Can you have a look at [Torchdrift](https://torchdrift.org/)?

**Comment by IamExperimenting** [comment]
Can we monitor the object detection model drift using torchdrift? 

If yes, which value we should use?

I did a transition from tensorflow to PyTorch and I'm finding bit challenging to get the relevant articles.

**Comment by oke-aditya** [comment]
Sorry @IamExperimenting I don't know if it can be applied to object detection. My intuition is that it should be feasible.

Can you ask the maintainers of torchdrift over GitHub https://github.com/TorchDrift/TorchDrift

**Comment by NicolasHug** [comment]
> can ask over https://discuss.pytorch.org/?

This :)

Sorry, this is a question that's not directly related to torchvision, the  https://discuss.pytorch.org/ is the preferred channel for that
