### ISSUE TITLE
Verify the threshold input for `solarize()` and add a test

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#4818]
### 🚀 The feature

The `solarize()` method receives a `threshold` which is currently not asserted based on the image type:
https://github.com/pytorch/vision/blob/d367a01a18a3ae6bee13d8be3b63fd6a581ea46f/torchvision/transforms/functional_tensor.py#L876-L886

Ideally we should assert it. It's upper bound depends on the image type (1.0 for float and 255 for uint8) similar to:
https://github.com/pytorch/vision/blob/d367a01a18a3ae6bee13d8be3b63fd6a581ea46f/torchvision/transforms/functional_tensor.py#L858

Along with the assertion we should add a unit-test to ensure that if the threshold is over the permitted value it will fail.

### Motivation, pitch

Due to the missing assertion, we didn't spot a bug at the configuration of AutoAugment methods. See #4805.

cc @vfdev-5 @datumbox @pmeier

**Comment by puhuk** [comment]
Can I take this

**Comment by pmeier** [comment]
@puhuk Sure, go ahead! Ping me or @datumbox on the PR for review.
