### ISSUE TITLE
[feature request] Batched scale boxes given original reference image size and target image size 

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/vision#4834]
### 🐛 Describe the bug

This is a frequently needed utility to bring back computed detections to a common / original coordinate frame.

### Versions

N/A

**Comment by datumbox** [comment]
@vadimkantorov we appreciate for proposal. 

Could you please resubmit it as a "feature request" as opposed to "bug"? Our Github forms adapt to the type of issue you submit and this one is currently missing the necessary fields that help us triage the request. Please try to include as much information as possible to make the feature request self-explanatory. This can help other open-source contributors tackle it and potentially us prioritize it.

Closing, this one as it's of the wrong issue type, looking forward to your new one. Thanks!
