### ISSUE TITLE
Batched box scale

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/vision#4835]
### 🚀 The feature

Frequent utility in postprocessing box detections:
```python
def batched_box_scale(boxes, image_shape, target_image_shape):
  fx = target_image_shape[..., -1] / image_shape[...., -1]
  fy = target_image_shape[..., -2] / image_shape[..., -2]
  return boxes * torch.stack([fx, fy, fx, fy], dim = -1).to(boxes.device)
```

### Motivation, pitch

This is a frequently needed utility to bring back computed detections to a common / original coordinate frame.

cc @vfdev-5 @datumbox

**Comment by fmassa** [comment]
Hi @vadimkantorov 

This is planned with the revamp of the transforms. The RFC is in https://github.com/pmeier/torchvision-datasets-rework/pull/1 , and we are starting to integrate it in https://github.com/pytorch/vision/pull/4721

Let us know what you think about it

**Comment by vadimkantorov** [comment]
What do you mean by transforms? For me, this kind of utilities have nothing to do with augmentations. Probably, I misunderstand the term

**Comment by fmassa** [comment]
I meant this will be handled by
```python
# boxes is a custom object that is defined in #4721
boxes : BBox

# then the transforms will know how to resize them
T.resize(boxes, (50, 20))
```

**Comment by vadimkantorov** [comment]
I only hope that there will also be functions accepting bare tensors - this would be more versatile and not require buying into new abstractions for porting existing code bases

**Comment by fmassa** [comment]
@vadimkantorov new abstractions with transforms are in #4861

I hope they will be useful and would encourage users to use them
