### ISSUE TITLE
Provide complete filepath to is_valid_file in make_dataset rather than only the filename

### ISSUE THREAD

**Issue by kotchin** [pytorch/vision#4871]
### 🚀 The feature

(First issue/feature request, tried my best to follow the guidelines, apologies if I missed something).

In `torchvision.datasets.folder.make_dataset`, we are given the option to use `is_valid_file` (or `extensions`).

My feature request is to allow `is_valid_file` to get the whole path to the file rather than just the filename.

### Motivation, pitch

Currently, if we wish to use `is_valid_file`, we can only act on the filename without getting the whole path to the file, which means it's currently particularly tricky to open the file and verify whether it meets certain criteria and decide whether it's valid.

Perhaps this was not the intended function initially, but it seems there's an opportunity of improving the possibilities of `is_valid_file` by providing it the whole path rather than just the filename. 

My exact implementation idea would be the following:
Replace the following snippet:
```
for root, _, fnames in sorted(os.walk(target_dir, followlinks=True)):
            for fname in sorted(fnames):
                if is_valid_file(fname):
                    path = os.path.join(root, fname)
                    item = path, class_index
                    instances.append(item)
```
with:
```
for root, _, fnames in sorted(os.walk(target_dir, followlinks=True)):
            for fname in sorted(fnames):
            path = os.path.join(root, fname)
                if is_valid_file(path):
                    item = path, class_index
                    instances.append(item)
```

This change might break retro-compatibility for users who make use of `is_valid_file`, however their fix would be particularly simple as they could add the following line in their `is_valid_file` function:
`root, fname= os.path.split(path)` where `path` is the variable for `is_valid_file` and they could continue using `fname` in their function (or however they've named it) as previously.

### Additional context

One example of how this could be useful is if one wants to use pictures which are meeting certain resolution, channels, or other criteria, in a configurable way, where the criteria could be coded in the `is_valid_file` function, without having to delete or move files.

**Comment by NicolasHug** [comment]
Thanks for the feedback @kotchin ,

I feel like this might actually be a bug - according to the docstring, `is_valid_file` should receive the entire path, not just a truncated name

> is_valid_file (callable, optional): A function that takes path of a file and check if the file is a valid file (used to check of corrupt files) both extensions and is_valid_file should not be passed.

@pmeier thoughts?

**Comment by kotchin** [comment]
Thank you for the quick response @NicolasHug 

Indeed, there's a mismatch between the documentation and the implementation. If the decision ends up being to stick to the documentation with the path, I would be happy to attempt submitting a first PR with the above suggested correction.

**Comment by NicolasHug** [comment]
Good catch @kotchin , yes it looks like we should revert #3902

**Comment by pmeier** [comment]
Thanks @kotchin for the report. I missed that when signing off the PR. Revert seems reasonable given that the perf boost was minimal in the first place.

**Comment by kotchin** [comment]
Thanks. Could you please advise me on the next step? Is there any action for me to take for the change to be merged and [https://github.com/pytorch/vision/pull/4885](https://github.com/pytorch/vision/pull/4885) and this issue to be closed? Thank you.

**Comment by datumbox** [comment]
@kotchin You are good to go. Just merged. We were all waiting for the final test to run. Sometimes the CI is slow :)

**Comment by kotchin** [comment]
I'm new to public and open github projects; I noticed that the PR includes private information.
How may I avoid this in the future?
And is there a way to remove it from this PR?
Apologies if I just noticed it. Thank you for your help.

**Comment by pmeier** [comment]
When you set up `git` you need to configure a name and and e-mail. They will always be included in a commit. 

> How may I avoid this in the future?

Set this to some public information.

> And is there a way to remove it from this PR?

Nope. The only way to do that would be to `force` push our `main` branch back to before your commit was merged in and apply all the other changes afterwards. This is very destructive and I'm fairly certain that this is not going to happen.

**Comment by kotchin** [comment]
> Set this to some public information.
In fact my question was not what I should set it to, but how to remove it completely. 
When I look at the exact code changes, I see that there's my account appearing (which is fine) but it also specifies "co-authored by", and when I look at all other commits by all other members, this mention simply does not exist. Could you please help me understand how to achieve that? Thank you for your help.

**Comment by pmeier** [comment]
The commit you pushed included this information: https://github.com/pytorch/vision/pull/4885/commits/6f825951964d48b3c247a1f3063da1b9d91ebc27. It seems the email you used for that, was not recognized by GitHub. So when we merged the PR, GitHub assumed that the other of the PR is the main author and all other authors are assumed to be co-authors. To resolve this in the future, you can link your email in the email settings here on GitHub.

That being said, AFAIK it is not possible to use `git` without supplying a name and an email. For the name you can simply supply and alias and use some nonsense data for the email. Doing the latter will probably prevent you from linking it to GitHub though.
