### ISSUE TITLE
Add Inception V2, Inception V4, Inception Resnet V2 in models

### ISSUE THREAD

**Issue by wanghan0501** [pytorch/vision#490]
Why not add Inception V2, Inception V4, Inception Resnet V2 in models？？

**Comment by VibAltekar** [comment]
I'd love to give this a shot! Is anybody already working on this?

**Comment by karandwivedi42** [comment]
@VibAltekar do go through the discussion here if you want to add a new model: https://github.com/pytorch/vision/issues/321#issuecomment-341820560

**Comment by fmassa** [comment]
Contributions are welcome!
Ideally, we would like the models to be trained on PyTorch using the `examples/imagenet` script.

**Comment by setuc** [comment]
We are working on developing the models for pytorch. we will make a pull request when done. Is there a need for pre-trained weights as well for such networks?

**Comment by HaleTom** [comment]
This may be partially addressed by Add inceptionv4 pretrained model https://github.com/pytorch/vision/pull/43/
