### ISSUE TITLE
Remove the note of needing scipy in GoogleNet and Inception

### ISSUE THREAD

**Issue by oke-aditya** [pytorch/vision#4919]
### 📚 The doc issue

I think after merging #4256 We should update the docs to indicate scipy isn't needed. As I see in the code base models/googlenet.py and models/inception.py we use torch and not scipy.

### Suggest a potential alternative/fix

Fix the note by removing the line regarding scipy.

Inception
https://github.com/pytorch/vision/blob/main/docs/source/models.rst#inception-v3

GoogleNet
https://github.com/pytorch/vision/blob/main/docs/source/models.rst#googlenet

It's a good first issue. Probably some new contributor would be interested.

**Comment by Carlosbogo** [comment]
Hi, I would be interested in helping with this

**Comment by datumbox** [comment]
@Carlosbogo there was already a PR what wasn't linked to this ticket by a different user. :(

**Comment by Carlosbogo** [comment]
Oh no problem then, I'm glad that it got solved.

**Comment by WathikAhmed** [comment]
Solved? close issue.

**Comment by oke-aditya** [comment]
Not yet. Once the linked PR is merged maintainers will.
