### ISSUE TITLE
Clean up `pandas` references from repo

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#4928]
### 🐛 Describe the bug

Python Pandas are no longer an optional dependency of torchvision's dataset. Still there are a few references of them on configuration and CI files. More specifically it should be removed from:
https://github.com/pytorch/vision/blob/5f0edb97b46e5bff71dc19dedef05c5396eeaea2/.github/workflows/tests-schedule.yml#L35-L36

and 
https://github.com/pytorch/vision/blob/5906d5908032ff8aa905d94fb97eb36482e51731/mypy.ini#L105-L107

Note that we should leave the `./scripts` folder unmodified. These scripts are there utilities that are not nor considered part of the library.

### Versions

Latest master f676f9404ab6062f81cfe92a5c516f90198fd99f

**Comment by Carlosbogo** [comment]
Hi, I would be glad to help with this

**Comment by datumbox** [comment]
You got it @Carlosbogo! :)
