### ISSUE TITLE
Pretrained Efficientnet B1 - B7 apparent performance missmatch

### ISSUE THREAD

**Issue by bjfranks** [pytorch/vision#4936]
### 🐛 Describe the bug

Hi,

a hopefully minimal working example of my issue:

```python
import torch
import torchvision
from torchvision import transforms
import torchvision.models as models
import numpy as np

preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
imagenet_data = torchvision.datasets.ImageNet(root='/to/imagenet/folder', transform=preprocess, split='val')

batch_size = 100
data_loader = torch.utils.data.DataLoader(imagenet_data,
                                          batch_size=batch_size,
                                          num_workers=20,
                                          pin_memory=True)
numbatches = len(imagenet_data)/float(batch_size)

model = models.efficientnet_b7(pretrained=True)

activations = []
labels = []
model.eval()
model.cuda()

with torch.no_grad():
    for num,(image,label) in enumerate(data_loader):
        print('{:.2f}%'.format(100*num/numbatches), end='\r')
        image=image.cuda()
        activations += [model(image).cpu()]
        labels += [label]
    print('{:.2f}%'.format(100.0))

activations = np.concatenate([activation.numpy() for activation in activations])
labels = np.concatenate([label.numpy() for label in labels])
top_x=activations.argsort(axis=1)[:,::-1]
k_occurence=np.concatenate([np.where(x==y)[0] for x,y in zip(top_x,labels)])
accuracies = np.array([len(np.where(k_occurence<=k)[0])/float(len(imagenet_data)) for k in range(1000)])
print(accuracies[0], accuracies[4])
```

I dont seem to be able to reproduce the performance of Efficientnet B1 - B7. For B0 I am close, but B1-B7 are nowhere near what they should be according to [torchvision.models](https://pytorch.org/vision/0.11/models.html) .

B0 0.77684 0.93594
B1 0.77610 0.93596
B2 0.77776 0.9374
B3 0.78544 0.94366
B4 0.79272 0.94524
B5 0.73146 0.90948
B6 0.74408 0.91858
B7 0.73926 0.9157

### Versions

Collecting environment information...
PyTorch version: 1.10.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.3 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.10

Python version: 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-55-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 10.1.168
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti
GPU 8: GeForce RTX 2080 Ti
GPU 9: GeForce RTX 2080 Ti

Nvidia driver version: 430.26
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl-service               2.0.2            py37h7b6447c_0
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] numpy                     1.16.4           py37h7e9f1db_0
[conda] numpy-base                1.16.4           py37hde5b4d6_0
[conda] numpydoc                  0.9.1                      py_0

**Comment by datumbox** [comment]
This is likely because you are not using the right interpolation and validation resize/crop-size. Have a look [here](https://github.com/pytorch/vision/tree/1de53bef2d04c34544655b0c1b6c55a25e4739fe/references/classification#efficientnet) on how you need to run the model using our reference scripts to reproduce the accuracies.

**Comment by bjfranks** [comment]
Ahh, that worked better, B7 with 0.83916 0.96758. That is certainly alot closer and might just be some minor local variability. Perhaps this should be added to the documentation on EfficientNet like it has been for Inception. Thanks in any case.
