### ISSUE TITLE
VGG Models in Pytorch

### ISSUE THREAD

**Issue by soulslicer** [pytorch/vision#494]
Good day,

I note that Pytorch has the VGG models from the paper here:

https://github.com/pytorch/vision/blob/master/torchvision/models/vgg.py

Can I ask on what dataset were these trained on..or if they were gotten from the original authors? This is because the VGG11 model for example was not released, yet there exists a model here?

**Comment by fmassa** [comment]
All the VGG models were trained on ImageNet using the the scripts provided in https://github.com/pytorch/examples/tree/master/imagenet
