### ISSUE TITLE
conversion to coco format changes bboxes in dataset

### ISSUE THREAD

**Issue by noreen-walker** [pytorch/vision#4943]
### 🐛 Describe the bug

I'm following the object detection tutorial [here](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html) which uses the coco evaluation metrics.

It uses `convert_to_coco_api` in  https://github.com/pytorch/vision/blob/main/references/detection/coco_utils.py to convert a dataset to coco format.

But when the bounding boxes are preloaded into memory in a dataset (i.e. not generated on the fly like in the tutorial) this conversion changes them in place. So the dataset gets modified unexpectedly.
 I think it happens here :
[`bboxes[:, 2:] -= bboxes[:, :2]`](https://github.com/pytorch/vision/blob/1deb2ec22796350801aea44a000e4669cbf2fe1c/references/detection/coco_utils.py#L160)
and could be fixed by doing a copy first.

### Versions

not applicable

**Comment by Marentor** [comment]
Thanks for the fix.
Can confirm after copy code works perfectly.

**Comment by vfdev-5** [comment]
Let's close this issue as solved, feel free to open a new issue if any related problem appear.
