### ISSUE TITLE
[minor feature] move tranforms.RandomCrop.get_params to functional

### ISSUE THREAD

**Issue by karandwivedi42** [pytorch/vision#495]
For uniformity.
```python
	# before
    i, j, h, w = transforms.RandomCrop.get_params(x, [224, 224])
    x = TF.crop(i, j, h, w)
	# after
    i, j, h, w = TF.get_random_crop_params(x, [224, 224])
    x = TF.crop(i, j, h, w)

```
or
```python
x = TF.random_crop(x, [224, 224])
```
I can PR if it's a go-ahead from any maintainer.

**Comment by vfdev-5** [comment]
@karandwivedi42 can you explain more, please, what kind of uniformity you speak ?

**Comment by karandwivedi42** [comment]
Disclaimer: It's a very nit-picking issue and I am fine closing this issue.

Current code:
```
from torchvision import transforms # have to import this just for get_params
import torchvision.transforms.functional as TF
def transform_train(x):
    i, j, h, w = transforms.RandomCrop.get_params(x, [224, 224])
    x = TF.crop(i, j, h, w)
	...
```

What I would like:
```
import torchvision.transforms.functional as TF
def transform_train(x):
    x = TF.random_crop(x, [224, 224])
	...
# When I don't need i,j,h,w but still prefer using functional transforms instead of Compose
```

**Comment by fmassa** [comment]
I see your point @karandwivedi42 .
We have tried keeping all randomness outside of the functional interface.
While being a bit more verbose, I think it still gives a bit more flexibility to have the result of random transforms being a separate entity, specially if you are planning on applying the same random transforms to different inputs.

Thus, I'm not sure we would be adding a functional version of `random_crop` for the moment.
While I'm not 100% happy with the current `get_params`, I think I still prefer it to adding randomness in the functional interface.

I'm closing the issue, but feel free to comment if you think we should do things differently
