### ISSUE TITLE
ImageIO as an Image (and Video) backend

### ISSUE THREAD

**Issue by FirefoxMetzger** [pytorch/vision#4968]
I have a fairly small question: Has ImageIO been considered as a potential backend for torchvision? If so, what is the current consensus on that? If not, would it be a cool thing to have?

I'm using ImageIO for most of my computer vision related work and so are others in my lab. This made me wonder if this is done elsewhere too and - if so - if it would make sense to integrate ImageIO into the existing torchvision pipeline.

---

**Sidenote**

For those that haven't heard of [ImageIO](https://github.com/imageio/imageio) before, the idea of the library is to allow you to `imread("my_image.[png, tiff, cr2, ...]")` and it _just works_ no matter the [file format](https://imageio.readthedocs.io/en/stable/formats/index.html) or [source](https://imageio.readthedocs.io/en/stable/getting_started/requests.html) (filesystem, remote HTTP/FTP, webcam, ...). It does so by maintaining a zoo of backends (I/O libraries that work with image data) and it exposes them under one common API. Similar to what torchvision is currently doing. 

What's nice about ImageIO is that its focus is solely on IO, which means that it can potentially replace an existing `mylib.io` module and make maintenance easier. I don't know if this aspect is relevant or desirable for torchvision, but I think that it is at least interesting so I figured I should mention it here, too.

**Comment by datumbox** [comment]
@FirefoxMetzger Thanks for the proposal.

TorchVision offers its own IO methods because it enables us to achieve speed optimizations and support endpoints that can be used outside of Python. The users can use IO libraries of their choice though. For example you could read the image using ImageIO and then create a Tensor from the numpy array using `to_tensor()`.

**Comment by FirefoxMetzger** [comment]
Thanks for the reply @datumbox 

> [...] and support endpoints that can be used outside of Python.

Does that mean I can write a C program that uses torch and have it use pillow to load images? I didn't know that was possible, but it sounds pretty cool.

> The users can use IO libraries of their choice though.

I second that. I mainly wanted to ask if there is interest in adding ImageIO as a backend alongside pillow, libpng, etc. I didn't find any previous discussions on this, so I thought I simply start a new issue and ask. If adding ImageIO isn't a good idea, e.g., because it doesn't have a C-API and that is a requirement, then that's the answer. 

> which means that it can potentially replace an existing mylib.io module and make maintenance easier.

Reading this a few days later, I wish I hadn't brought it up 😆 It sounds like I am proposing to replace `torchvision.io`, whereas I am really thinking about adding to it. 

Don't get me wrong, I'd love to see the python ecosystem converge on one common I/O API for images. That way, we can have an easier time creating readers/parsers for new formats, and we can also avoid repeatedly writing modules whose sole job is to unify the API of various format-specific I/O libraries. I do realize, however, that that is the idealist in me talking.

**Comment by datumbox** [comment]
> Does that mean I can write a C program that uses torch and have it use pillow to load images? I didn't know that was possible, but it sounds pretty cool.

Not pillow but you can use the C++ native image IO methods. Note that the API is not considered public/stable so there are no BC guarantees.

>  That way, we can have an easier time creating readers/parsers for new formats, and we can also avoid repeatedly writing modules whose sole job is to unify the API of various format-specific I/O libraries.

I get it and you are right. The thing TorchVision offers GPU accelerated decoding and other goodies that we couldn't find easily elsewhere. Moreover by having our own IO, we get the option to apply optimizations that normally we couldn't do. We still build upon libraries like libpng and libjpeg though. But I agree there are definitely pros/cons between adopt vs offer something new.
