### ISSUE TITLE
Remove workarounds in tests that are no longer flaky due to stable sort

### ISSUE THREAD

**Issue by jdsgomes** [pytorch/vision#4970]
In the #4767 PR we enabled stable sort in the NMS op kernel. This can potentially resolve some of  the flakiness seen in the tests can be resolved, for instance:

https://github.com/pytorch/vision/blob/f093d0821194ed55f80f4764cf56e744f9217533/test/test_models.py#L658-L672

We should investigate if this is the case, and potentially adjust the the expected values of the tests if required. 

cc @NicolasHug @pmeier @datumbox

**Comment by datumbox** [comment]
Unfortunately switching to stable sort is not enough to defeat the flakiness of the tests. The flakiness will be resolved by avoiding initializing the models from random weights and using noise as input. These will be addressed later in the half.

My investigation at https://github.com/pytorch/vision/pull/5573#issuecomment-1062890652 shows that we can't remove the workarounds at the moment, so I'll close the issue as nofix.
