### ISSUE TITLE
CI binary_libtorchvision_ops_ios job broken

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#5010]
### 🐛 Describe the bug

The CI jobs for libtorchvision_ops on IOS started [failing](https://app.circleci.com/pipelines/github/pytorch/vision/12996/workflows/660c9572-9bf9-4ab7-8543-9dd16ae22cc8/jobs/1035541) with:
```
Error: undefined method `bottled?' for #<Dependency: "pkg-config" [:build]>
Do not report this issue until you've run `brew update` and tried again.
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/delegate.rb:83:in `all?'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:282:in `block in check_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:281:in `each'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:281:in `partition'
/usr/local/Homebrew/Library/Homebrew/upgrade.rb:281:in `check_installed_dependents'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:233:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

cc @seemethere @husthyc @tao

### Versions

Latest main 65cdaeaba83366381b8e7b9fd9850b7c0ca5e636

**Comment by datumbox** [comment]
Related to https://github.com/pytorch/pytorch/issues/69065#issue-1066773545

**Comment by malfet** [comment]
Re-run should fix it, but we probably should get rid of Homebrew update step altogether

**Comment by datumbox** [comment]
Thanks, I confirm it's [fixed](https://app.circleci.com/pipelines/github/pytorch/vision/12996/workflows/660c9572-9bf9-4ab7-8543-9dd16ae22cc8/jobs/1037993) now.
