### ISSUE TITLE
Can you add  the inception-resnetv2？

### ISSUE THREAD

**Issue by 453606803** [pytorch/vision#5036]
## Motivation

inception-resnetv2 is also a network with high accuracy, but there is no pytorch version

**Comment by datumbox** [comment]
Thanks @453606803. The inception-resnet family has been proposed again in the past at #3899. Given you ask for the V2 version, I've updated our list at #2707 where we keep track of the requested models. 

I'm going to close this ticket to avoid duplicates, let's continue our discussion on the #2707.
