### ISSUE TITLE
Different data and label names in torchvision.datasets

### ISSUE THREAD

**Issue by morawi** [pytorch/vision#505]
I gave Cifar10, Cifar100, and SVHN torchvision.datasets a go, and after loading the train_set and test_set, the data labels’ identifiers are different across datasets:

To get the labels in Cifar10 and Cifar100
test_set.test_labels
train_set.train_labels
also, the data is called
test_set.test_data
train_set.train_data

In SVHN, the situation is different (and I think more accurate)
test_set.labels
train_set.labels
and the data is called
test_set.data
train_set.data

I think the naming needs to be consistent.

**Comment by jramapuram** [comment]
Had the same query earlier, however it technically shouldn't matter as you can permute the data or the labels with `transforms` or `target_transforms` whatever the underlying members are.

**Comment by fmassa** [comment]
So, what happens is that the `DataSet` API only specifies that `__getitem__` and `__len__` should be implemented, and all the rest is up to the user.
Thus, while we could try to enforce that for some particular datasets that will hold true (for those that can be fully loaded in memory and that are split in two tensors, for example), that's not going to be the case everywhere.

Changing the naming now would be a backwards-incompatible change for old users, and I'm not 100% sure that it would be worth breaking peoples code.

Ideally, you shouldn't rely on those "internal" fields.
