### ISSUE TITLE
Add minimum input image size to the model meta-data

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#5199]
### 🚀 The feature

Related to issues #4462 and #3921. It would be great to add the minimum supported input size in the model's meta-data, so that it's programmatically accessible. 

Here is what needs to be done:
1. Add a `min_size` attribute to the Image Classification (quanitzed and non-quantized) and Video Classification [model meta-data](https://github.com/pytorch/vision/blob/b5aa0915fe16e82ee4c24919032b4e7afae3ae1b/torchvision/prototype/models/alexnet.py#L20-L25). Note that we can use information introduced by #3944 to populate this data and follow the same approach for estimating the sizes for new architectures added after the PR (RegNets, EfficientNet, ViT etc). 
2. Modify the [meta-data verification unit-test](https://github.com/pytorch/vision/blob/b5aa0915fe16e82ee4c24919032b4e7afae3ae1b/test/test_prototype_models.py#L99) to confirm that all models have the field.

**Comment by f-parfenov** [comment]
Hello, 
Week 2 Meta Camper here. I wondered whether I could do this task as a level 3 task as I would like to discover more about this project?

**Comment by datumbox** [comment]
@f-parfenov Welcome! You got it! Let's catch up on the details. There are a few thing you need to setup on your environment before tackling it but it's doable.
