### ISSUE TITLE
Dependency issues on TorchVision v0.11 release branch

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#5235]
### 🐛 Describe the bug

Rerunning the CI tests on top of the `release/0.11` branch leads to the following failures (see #5234):
- All the `cmake_*` jobs fail with `PackagesNotFoundError: pytorch=1.10.1`: [example](https://app.circleci.com/pipelines/github/pytorch/vision/14157/workflows/d1597a5d-acc7-4adf-b4ac-8bc31ad9a9bd/jobs/1139308)
- All the `unittest_*_py3.6` jobs fail with `Failed building wheel for av`: [example](https://app.circleci.com/pipelines/github/pytorch/vision/14157/workflows/3f738e6a-ba4b-4895-bc0b-734b03f43a8f/jobs/1139346)

### Versions

`release/0.11` branch - 34395c75ec6756204eea7b9a3a1ded93980e37bd

cc @seemethere

**Comment by seemethere** [comment]
These make sense considering we prune versions of torch on conda when we release new release candidates

**Comment by seemethere** [comment]
cmake issues are most likely resolved by https://github.com/pytorch/vision/pull/5239

**Comment by seemethere** [comment]
Looks like av issues are related to a release that was done at the end of the year that no longer has support for python 3.6.

Pinning the AV dependency to `8.0.3` should resolve this.

**Comment by seemethere** [comment]
> Looks like av issues are related to a release that was done at the end of the year that no longer has support for python 3.6.
> 
> Pinning the AV dependency to `8.0.3` should resolve this.

Resolved by https://github.com/pytorch/vision/pull/5240

**Comment by datumbox** [comment]
@seemethere Thanks for the patches. I confirm that all the CI issues are now addressed by your 2 PRs and the cherrypick we brought. All tests pass, see #5243.
