### ISSUE TITLE
[feature request] Derive all transforms classes from nn.Module?

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/vision#5236]
### 🚀 The feature

Currently it's already the case for most transform classes, except T.Compose / T.RandomChoice (these could probably be derived from nn.Sequential / nn.ModuleList). This also would not break any compat, and improve consistency and composability (sometimes only nn.Modules are accepted as parts of other existing models)

### Motivation, pitch

N/A

cc @vfdev-5 @datumbox @bjuncek

**Comment by datumbox** [comment]
@vadimkantorov You are right to say that. There is a handful of them that don't derive from it and the reason is mainly that they might not be JIT-scriptable and that might break BC. I think there is a lot of merit to make all classes inherit from nn.Module. The new Transforms API is the place to address it (see [here](https://github.com/pytorch/vision/blob/main/torchvision/prototype/transforms/_transform.py#L12)).

**Comment by vadimkantorov** [comment]
T.Compose probably is scriptable, the rest probably too if we migrate from `random.` to using torch random functions?

**Comment by vfdev-5** [comment]
@vadimkantorov have you seen discussion from this PR (https://github.com/pytorch/vision/pull/2645), why classes like `T.Compose` were not derived from nn.Module etc ? TLDR, keep BC with previous versions.

**Comment by vadimkantorov** [comment]
Thanks for the reference! I tried to understand why deriving from nn.Sequential would existing some code, but I couldn't since the discussion is quite dispersed there.

**Comment by vfdev-5** [comment]
> Thanks for the reference! I tried to understand why deriving from nn.Sequential would existing some code, but I couldn't since the discussion is quite dispersed there.

First point is that we can not do basic thing like: `T.Compose([T.Resize(200), lambda x: x * 0.5, my_transform_plain_function])` as lambda functions are not `nn.Module` and then `T.Compose` being inherited from `nn.Module` or `nn.Sequential` wont accept that. 
To solve this we have to wrap all callables non-nn-modules with something from torchvision.

Next, if we wrap these custom functions by something then user can lose the access to its possible attributes etc. Imagine,
`t = T.Compose([T.Resize(200), MyCustomTransform(*args, **kwargs)])` and `t.transforms[1].call_custom_method(...)`. This wont be possible if we do not do some `__getattr__` magic...

**Comment by vadimkantorov** [comment]
Thanks for explaining! Now I see!

My proposal would be:
* support https://github.com/pytorch/pytorch/issues/51782 for core
* support https://github.com/pytorch/pytorch/issues/55457 or introduce a separate TupleSequential (hopefully in core :))
* update examples / docs for old-style examples to use TupleSequential instead of Compose
* deprecate Compose at the same time of when new-style data pipes (using dicts instead of tuples) are mature and recommended

**Comment by vadimkantorov** [comment]
Maybe RandomChoice is more safe for conversion to nn.ModuleList, as it's not as old class

**Comment by vadimkantorov** [comment]
Is there now a nn.Sequential/nn.ModuleList-derived TupleSequential? Or what is the format of instances in proto? Are they now all dicts? Is there now also a nn.Module-derived T.Lambda wrapper?
