### ISSUE TITLE
Vectorize box decoding in FCOS model

### ISSUE THREAD

**Issue by jdsgomes** [pytorch/vision#5247]
### 🚀 The feature

The for loop in `torchvision/models/detection/fcos.py:80` can probably be vetorized.

```python
        pred_boxes = [
            self.box_coder.decode_single(bbox_regression_per_image, anchors_per_image)
            for anchors_per_image, bbox_regression_per_image in zip(anchors, bbox_regression)
        ]
```

### Motivation, pitch

Simplify/speedup the execution

**Comment by abhi-glitchhg** [comment]
Can I try this?

**Comment by datumbox** [comment]
@abhi-glitchhg absolutely! Thanks for offering to help.
