### ISSUE TITLE
LambdaDataset?

### ISSUE THREAD

**Issue by kohr-h** [pytorch/vision#525]
I'm wondering if this is of interest to the torchvision community: a dataset defined with two functions. It would look like this:

```python
wrapped_dset = # some dataset

def data(i):
    return wrapped_dset[i][0]

def target(i):
    return data(i)[:, ::2, ::2]  # downsample on the fly

dset = LambdaDataset(data_func=data, target_func=target, length=len(wrapped_dset))
```

It could be super-handy to combine datasets, switch out the target like above, etc., without having to write a separate class.

**Comment by vfdev-5** [comment]
@kohr-h actually, as I understand a `Dataset` is just an iterable with length, so a dataset corresponding to your `LambdaDataset` is just 
```python
dset = [(data(i), target(i)) for i in range(len(wrapped_dset))]
```
So, the 👍  of `LambdaDataset` is that it is already an instance of `Dataset`. 
Could you please provide more use-cases where it can be used ?

**Comment by fmassa** [comment]
I'm not sure we would want to add it to `torchvision` though, as it is not really specific to image data.

Also, while it might look that it is sort of generic, it also imposes a restriction that there are only two objects that are returned (which can be tuples or dict, but still).

In the end, I'm not sure that the benefits it brings compensate the extra complexity.

I'm closing this, but please feel free to comment if you disagree.

**Comment by kohr-h** [comment]
> I'm not sure we would want to add it to torchvision though, as it is not really specific to image data.

It's not specific to to images, that's true.



> Also, while it might look that it is sort of generic, it also imposes a restriction that there are only two objects that are returned (which can be tuples or dict, but still).

Good point there. It would be better to have just one function `draw` or so which returns the tuple or whatever you like.



> In the end, I'm not sure that the benefits it brings compensate the extra complexity.

I'm thinking mainly of on-the-fly sample generation. The list approach by @vfdev-5 works as well, of course, but you may not want to have all the data lying around at once. A generator fixes that but misses the `__len__` attribute. So in plain Python you would write a small custom iterator class, which would be doing the exact same thing as a `LambdaDataset`, only in `__iter__` instead of `__getitem__`.



> In the end, I'm not sure that the benefits it brings compensate the extra complexity.

I guess the benefit would be providing the iterator boilerplate so the user only has to write a function (a bit like the [`LambdaLR`](https://github.com/pytorch/pytorch/blob/5a3f7810f8d23b733d7e9b167348b873c2d9fdf1/torch/optim/lr_scheduler.py#L53), but that one has much more boilerplate, admittedly).
If you think that's not enough to add code, I'm okay with that.

**Comment by kohr-h** [comment]
Yeah, I tried to bring forth the best arguments, but they're not really that strong. And I understand the reasons against it.

**Comment by fmassa** [comment]
Thanks for the understanding @kohr-h 
But there might be other places that such a functionality might be desired, for example as a third-party package?
