### ISSUE TITLE
Bug in package torchvision.models.quantization: `TypeError: __init__() missing 2 required positional arguments: 'inplanes' and 'planes'`

### ISSUE THREAD

**Issue by mohrez86** [pytorch/vision#5255]
### 🐛 Describe the bug

The constructor of the class [QuantizableBasicBlock](https://github.com/pytorch/vision/blob/main/torchvision/models/quantization/resnet.py#L23) in the module `torchvision/models/quantization/resnet.py` only has the two parameters `*args` and `**kwargs`. Thus, instantiating an object of `QuantizableBasicBlock` by passing no inputs should be possible. However, making an object of this class with no inputs results in the following run-time error.

```
Traceback (most recent call last):
  File "/home/moe/vision/test_mohrez/test_found.py", line 5, in test_models_quantization_resnet
    obj = QuantizableBasicBlock()
  File "/home/moe/vision/torchvision/models/quantization/resnet.py", line 27, in __init__
    super(QuantizableBasicBlock, self).__init__(*args, **kwargs)
TypeError: __init__() missing 2 required positional arguments: 'inplanes' and 'planes'
```

# To reproduce

Running the following test reproduces the error.

```
from torchvision.models.quantization.resnet import QuantizableBasicBlock

def test_models_quantization_resnet():
    obj = QuantizableBasicBlock()
```

# Reason

I think the reason behind this run-time error is that the constructor of the class `QuantizableBasicBlock` passes the inputs (received through `*args` and `**kwargs`) to the constructor of its base class [BasicBlock](https://github.com/pytorch/vision/blob/4bf6c6e4b4cf2dea9c7f9952aa30d5820ab8ae33/torchvision/models/resnet.py#L60).

Since `BasicBlock` has two positional arguments `inplanes` and `planes` (with no default values), `BasicBlock` complains if `inplanes` and `planes` are not included in `*args` or `**kwargs`.

# Possible fix

I can think of one way to fix it (if it is a bug). Changing the signature of the constructor of `QuantizableBasicBlock` as shown in the following can be a fix since in this way, instantiating `QuantizableBasicBlock` without these mandatory positional arguments won't be possible.

```
class QuantizableBasicBlock(BasicBlock):
    def __init__(self, inplanes: int, planes: int, *args: Any, **kwargs: Any) -> None:
        super(QuantizableBasicBlock, self).__init__(inplanes, planes, *args, **kwargs)
```

# Other

I have found several instances of this case within the source code. If it is something interesting, I can open one issue for each module that has it.

### Versions

Collecting environment information...
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-46-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.931
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.1
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchvision==0.11.0a0+e7ec7e2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] mypy                      0.931                    pypi_0    pypi
[conda] mypy-extensions           0.4.3                    pypi_0    pypi
[conda] numpy                     1.21.2           py38h20f2e39_0  
[conda] numpy-base                1.21.2           py38h79a1101_0  
[conda] pytorch                   1.10.1          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.1               py38_cu113    pytorch
[conda] torchvision               0.11.0a0+e7ec7e2           dev_0    <develop>

**Comment by datumbox** [comment]
@mohrez86 Thanks for reporting.

I don't think this is a bug but rather an expected behaviour of the idiom we use. The current quantization approach (possibly is going to change on the near future) requires wrapping existing modules with extra bits necessary for quantization. Instead of redefining all arguments in the constructors and duplicating code, the `*args` shortcut is used. 

Though not the most friendly idiom that I would replicate in the entire code-base outside of quantization, it's something that allowed us to avoid lots of duplicate code. Keep in mind that blocks like `QuantizableBasicBlock` are in a quazi-private state in the code (aka not defined in `__all__`, though these semantics of these are not fully defined at the moment). So their use requires a bit more understanding, via looking on the source-code. The good thing is, the Quantization approach changes with the use of FX, so hopefully all this extra boilerplate code will go away on the future.

I'm going to close the issue to keep things tidy but feel free to reopen if you think otherwise.
