### ISSUE TITLE
I can't download the densenet pre-train models by the link

### ISSUE THREAD

**Issue by jianwu585218** [pytorch/vision#529]
I got some trouble in load pre-train models.
I can't download the densenet  pre-train models by the link,such as:
model_urls = {
    'densenet121': 'https://download.pytorch.org/models/densenet121-a639ec97.pth',
    'densenet169': 'https://download.pytorch.org/models/densenet169-b2777c0a.pth',
    'densenet201': 'https://download.pytorch.org/models/densenet201-c1103571.pth',
    'densenet161': 'https://download.pytorch.org/models/densenet161-8d451a50.pth',
}
By the way ,I'm in china,is this the reason for this?

**Comment by vfdev-5** [comment]
Just checked the first file:
```
wget --spider https://download.pytorch.org/models/densenet121-a639ec97.pth
Spider mode enabled. Check if remote file exists.
--2018-06-06 14:04:54--  https://download.pytorch.org/models/densenet121-a639ec97.pth
Resolving download.pytorch.org (download.pytorch.org)... 13.32.182.16, 13.32.182.123, 13.32.182.230, ...
Connecting to download.pytorch.org (download.pytorch.org)|13.32.182.16|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32342954 (31M) [application/x-www-form-urlencoded]
Remote file exists.
```
-> Remote file exists

**Comment by fmassa** [comment]
You are probably blocked by the chinese firewall.
