### ISSUE TITLE
Runtime error in clip_sampler.py: RuntimeError: Default process group has not been initialized.

### ISSUE THREAD

**Issue by mohrez86** [pytorch/vision#5292]
### 🐛 Describe the bug

Creating an object of the class [DistributedSampler](https://github.com/pytorch/vision/blob/main/torchvision/datasets/samplers/clip_sampler.py#L10) while not passing anything to either of the two parameters `num_replicas` or `rank` results in the following runtime error. However, passing values other than `None` (e.g., `num_replicas=2` and `rank=0`) does not result in the following runtime error (see the passing test [test_distributed_sampler_and_uniform_clip_sampler](https://github.com/pytorch/vision/blob/main/test/test_datasets_samplers.py#L63)).

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../anaconda3/envs/pytorchnightcpu/lib/python3.8/site-packages/torchvision/datasets/samplers/clip_sampler.py:50: in __init__
    num_replicas = dist.get_world_size()
../../anaconda3/envs/pytorchnightcpu/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:865: in get_world_size
    return _get_group_size(group)
../../anaconda3/envs/pytorchnightcpu/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:323: in _get_group_size
    default_pg = _get_default_group()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def _get_default_group():
        """
        Getting the default process group created by init_process_group
        """
        if not is_initialized():
>           raise RuntimeError(
                "Default process group has not been initialized, "
                "please make sure to call init_process_group."
            )
E           RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

../../anaconda3/envs/pytorchnightcpu/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:427: RuntimeError


============================== 1 failed in 2.02s ===============================

Process finished with exit code 1
```

# Reason

In the constructor of the class `DistributedSampler`, the default values of `num_replicas` and `rank` are `None`. If any of these two parameters are `None`, the constructor of `DistributedSampler` calls the function [dist.get_world_size()](https://github.com/pytorch/vision/blob/main/torchvision/datasets/samplers/clip_sampler.py#L50) or [dist.get_rank()](https://github.com/pytorch/vision/blob/main/torchvision/datasets/samplers/clip_sampler.py#L54), both of which produce the error mentioned above.

# To reproduce

Any of the three following test cases reproduce the runtime error. These tests must be placed inside the [test package](https://github.com/pytorch/vision/tree/main/test) since they require the module [common_utils.py](https://github.com/pytorch/vision/blob/main/test/common_utils.py).

The following test does not provide `num_replicas` which makes it `None`.
```
from torchvision.datasets.samplers import UniformClipSampler, DistributedSampler
from torchvision.datasets.video_utils import VideoClips
from common_utils import get_list_of_videos

def test_clip_sampler_distributed_sampler_1():
    tmpdir = "."
    video_list = get_list_of_videos(tmpdir, num_videos=3, sizes=[25, 25, 25])
    video_clips = VideoClips(video_list, 5, 5)
    clip_sampler = UniformClipSampler(video_clips, 3)

    distributed_sampler = DistributedSampler(
        clip_sampler,
        rank=0,
        group_size=3,
    )
```

The following test does not provide `rank` which makes it `None`.
```
from torchvision.datasets.samplers import UniformClipSampler, DistributedSampler
from torchvision.datasets.video_utils import VideoClips
from common_utils import get_list_of_videos

def test_clip_sampler_distributed_sampler_2():
    tmpdir = "."
    video_list = get_list_of_videos(tmpdir, num_videos=3, sizes=[25, 25, 25])
    video_clips = VideoClips(video_list, 5, 5)
    clip_sampler = UniformClipSampler(video_clips, 3)

    distributed_sampler = DistributedSampler(
        clip_sampler,
        num_replicas=2,
        group_size=3,
    )
```

The following test does not provide `rank` and `num_replicas` which makes them `None`.
```
from torchvision.datasets.samplers import UniformClipSampler, DistributedSampler
from torchvision.datasets.video_utils import VideoClips
from common_utils import get_list_of_videos

def test_clip_sampler_distributed_sampler_3():
    tmpdir = "."
    video_list = get_list_of_videos(tmpdir, num_videos=3, sizes=[25, 25, 25])
    video_clips = VideoClips(video_list, 5, 5)
    clip_sampler = UniformClipSampler(video_clips, 3)

    distributed_sampler = DistributedSampler(
        clip_sampler,
        group_size=3,
    )
```

# Suggestion

[This example](https://pytorch.org/docs/master/notes/ddp.html#example) demonstrates how the default process group should be initialized. However, even without initializing it, this class should work since this exception is raised only if `num_replicas` or `rank` are `None`. Isn't it better to change the default values of these two parameters to something other than `None` (e.g., `num_replicas=2` and `rank=0`)? In this way, not passing them to the constructor `DistributedSampler` does not produce an error.

### Versions

Collecting environment information...
PyTorch version: 1.11.0.dev20220122
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.13.0-27-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.1
[pip3] torch==1.11.0.dev20220122
[pip3] torchaudio==0.11.0.dev20220122
[pip3] torchvision==0.12.0.dev20220122
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch-nightly
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.21.2           py38h20f2e39_0  
[conda] numpy-base                1.21.2           py38h79a1101_0  
[conda] pytorch                   1.11.0.dev20220122     py3.8_cpu_0    pytorch-nightly
[conda] pytorch-mutex             1.0                         cpu    pytorch-nightly
[conda] torchaudio                0.11.0.dev20220122        py38_cpu    pytorch-nightly
[conda] torchvision               0.12.0.dev20220122        py38_cpu    pytorch-nightly

**Comment by datumbox** [comment]
> However, even without initializing it, this class should work since this exception is raised only if num_replicas or rank are None.

@mohrez86 Thanks for bringing this up.

We use the specific pattern because that's the recommended way from PyTorch Core. See their [DistributedSampler](https://pytorch.org/docs/master/_modules/torch/utils/data/distributed.html#DistributedSampler) for example. As mentioned in the tutorial you linked, the process group needs to be initialized prior using any distributed features. Since the specific sampler needs to know about distributed features such as world size and rank, distributed needs to be initialized.

Given we use a pattern from PyTorch core, I don't think proposals related to it should be discussed here but instead open directly a ticket on core. I'm going to close the ticket to keep things tidy, but if you still have concerns feel free to reopen. Cheers!
