### ISSUE TITLE
add a requirement.txt file to install libs

### ISSUE THREAD

**Issue by aryanraj2713** [pytorch/vision#5314]
### 🐛 Describe the bug

```
$pip freeze > requirements.txt
```
this will add a requirements.txt file

```
$pip install -r requirements.txt
```
for users to install dependents mentioned in file

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

**Comment by oke-aditya** [comment]
Hi ! @aryanraj2713 I think creating `requirements.txt` is not the best option for packages such as torchvision.
One major reason is it depends on pytorch and cuda configuration. Binaries are different for cuda, rocm and cpuonly. Also requirements is not flexible enough to handle all such use-cases.

Also installation instructions are very clear over the docs page `https://pytorch.org/`
And for people who want to install from source, check the [contributing.md](https://github.com/pytorch/vision/blob/main/CONTRIBUTING.md) guide.

**Comment by aryanraj2713** [comment]
> Hi ! @aryanraj2713 I think creating `requirements.txt` is not the best option for packages such as torchvision. One major reason is it depends on pytorch and cuda configuration. Binaries are different for cuda, rocm and cpuonly. Also requirements is not flexible enough to handle all such use-cases.
> 
> Also installation instructions are very clear over the docs page `https://pytorch.org/` And for people who want to install from source, check the [contributing.md](https://github.com/pytorch/vision/blob/main/CONTRIBUTING.md) guide.

Is there a conda install package possible for the issue @oke-aditya

**Comment by oke-aditya** [comment]
Yes you can install torchvision with conda. Also conda is recommended way of installing torchvision .
Instructions are available over https://pytorch.org/

E.g. for CUDA 11.3
```
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
```

**Comment by aryanraj2713** [comment]
> Yes you can install torchvision with conda. Also conda is recommended way of installing torchvision . Instructions are available over https://pytorch.org/
> 
> E.g. for CUDA 11.3
> 
> ```
> conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
> ```

ohh thanks

**Comment by pmeier** [comment]
Hey @aryanraj2713, I think your question was answered by @oke-aditya. Thus, I'm closing this issue. Feel free to re-open if you don't think this is the case.
