### ISSUE TITLE
[Explanation] Why do we need this condition in the ResNet?

### ISSUE THREAD

**Issue by Constannnnnt** [pytorch/vision#532]
In the ResNet model, I see this conditional statement "self.inplanes != planes * block.expansion", referenced in the following image.

<img width="520" alt="screen shot 2018-06-20 at 14 37 39" src="https://user-images.githubusercontent.com/11689533/41641429-d6c569ae-7497-11e8-866f-f9c14b9a189b.png">

I am confused with this statement. From the original paper, it tells that in `Conv3_1, Conv4_1, Conv5_1`, we need to do downsampling in each layer. Since block.expansion is set to 1 and 4 in basicblock and bottleneck respectively, which indicates that "self.inplanes != planes" and "self.inplanes != 4 * planes" respectively, these two inequalities are always true according to the ResNet architecture and we only need to decide whether we need to do downsampling based on the value of stride. i.e. whether `stride = 2` or not. 

Can someone explain it to me? Am I missing something here?

**Comment by Constannnnnt** [comment]
I

**Comment by fmassa** [comment]
This is just a way of factoring out the structure of resnet in a simple way.

In ResNet, every conv3x3 layer in block has the same number of channels. If we change the number of channels, that's because we are going to a new block, so it requires downsampling.

**Comment by monghimng** [comment]
For anyone who is still confused, OP is correct that starting at the transition between conv2 and conv3 (for naming scheme, see page 5 of the original Resnet paper) , the condition

`stride != 1`

is enough to detect a dimension change (halving width and height while doubling channel). However, at the beginning of conv2, there is a 3x3 max pooling, which made the input channel count to be some weird numbers. Therefore, the second condition is to detect this and bring the channel count to power of 2.

**Comment by rsomani95** [comment]
Am I correct in assuming that the `if` conditional mentioned by OP is only meant for `ResNet {50, 101, 152}` and _doesn't_ apply to `ResNet {18, 34}` since `kernel_size=1` (highlighted in light red) is only implemented in the larger ResNets as per this figure from the paper:

<img width="1231" alt="Screenshot 2019-07-03 at 8 40 38 PM" src="https://user-images.githubusercontent.com/17111474/60603181-ddb79600-9dd2-11e9-99f4-a1f4a537a621.png">
