### ISSUE TITLE
More details to the dataset documentation page

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#5321]
Our current [dataset documentation page](https://pytorch.org/vision/main/datasets.html#caltech) just lists the available datasets alphabetically.

Let's try to organize this page into subsections like 

- Classification datasets
- Segmentation dataset
- Detection dataset
- Optical Flow dataset
- Video dataset
- etc.

Some datasets may belong to more than one category. As a first step, let's list them in each category they belong to. If a pattern arises we may create a new section like "classification and detection dataset" in the future.

**Comment by pmeier** [comment]
The list above is mixing two concepts: task and data type. While classification, segmentation, detection, and optical flow are tasks, video datasets describe the data type while being classification datasets.

I don't have a better way to structure them and TensorFlow is structuring them in a [similar way](https://www.tensorflow.org/datasets/catalog/overview).
