### ISSUE TITLE
[layers] Layers branch building fails due to CPP extensions

### ISSUE THREAD

**Issue by tonyf** [pytorch/vision#534]
Building the layers branch is failing. 

> building 'torchvision._C' extension
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_CUDA -I/home/tonyfrancisv/vision/torchvision/csrc -I/home/tonyfrancisv/.local/share/virtualenvs/vision-SNqDYWG8/lib/python3.5/site-packages/torch/lib/include -I/home/tonyfrancisv/.local/share/virtualenvs/vision-SNqDYWG8/lib/python3.5/site-packages/torch/lib/include/TH -I/home/tonyfrancisv/.local/share/virtualenvs/vision-SNqDYWG8/lib/python3.5/site-packages/torch/lib/include/THC -I/usr/local/cuda/include -I/usr/include/python3.5m -I/home/tonyfrancisv/.local/share/virtualenvs/vision-SNqDYWG8/include/python3.5m -c /home/tonyfrancisv/vision/torchvision/csrc/vision.cpp -o build/temp.linux-x86_64-3.5/home/tonyfrancisv/vision/torchvision/csrc/vision.o -DTORCH_EXTENSION_NAME=torchvision._C -std=c++11
> cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
> In file included from /home/tonyfrancisv/.local/share/virtualenvs/vision-SNqDYWG8/lib/python3.5/site-packages/torch/lib/include/pybind11/pytypes.h:12:0,
>                  from /home/tonyfrancisv/.local/share/virtualenvs/vision-SNqDYWG8/lib/python3.5/site-packages/torch/lib/include/pybind11/cast.h:13,
>                  from /home/tonyfrancisv/.local/share/virtualenvs/vision-SNqDYWG8/lib/python3.5/site-packages/torch/lib/include/pybind11/attr.h:13,
>                  from /home/tonyfrancisv/.local/share/virtualenvs/vision-SNqDYWG8/lib/python3.5/site-packages/torch/lib/include/pybind11/pybind11.h:43,
>                  from /home/tonyfrancisv/.local/share/virtualenvs/vision-SNqDYWG8/lib/python3.5/site-packages/torch/lib/include/torch/torch.h:6,
>                  from /home/tonyfrancisv/vision/torchvision/csrc/cpu/vision.h:2,
>                  from /home/tonyfrancisv/vision/torchvision/csrc/nms.h:2,
>                  from /home/tonyfrancisv/vision/torchvision/csrc/vision.cpp:1:
> <command-line>:0:33: error: expected initializer before ‘.’ token
> /home/tonyfrancisv/.local/share/virtualenvs/vision-SNqDYWG8/lib/python3.5/site-packages/torch/lib/include/pybind11/detail/common.h:212:47: note: in definition of macro ‘PYBIND11_CONCAT’
>  #define PYBIND11_CONCAT(first, second) first##second
>                                                ^
> /home/tonyfrancisv/vision/torchvision/csrc/vision.cpp:6:1: note: in expansion of macro ‘PYBIND11_MODULE’
>  PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
>  ^
> /home/tonyfrancisv/vision/torchvision/csrc/vision.cpp:6:17: note: in expansion of macro ‘TORCH_EXTENSION_NAME’
>  PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
>                  ^
> <command-line>:0:33: error: expected initializer before ‘.’ token
> /home/tonyfrancisv/.local/share/virtualenvs/vision-SNqDYWG8/lib/python3.5/site-packages/torch/lib/include/pybind11/detail/common.h:171:51: note: in definition of macro ‘PYBIND11_PLUGIN_IMPL’
>      extern "C" PYBIND11_EXPORT PyObject *PyInit_##name()
>                                                    ^
> /home/tonyfrancisv/vision/torchvision/csrc/vision.cpp:6:1: note: in expansion of macro ‘PYBIND11_MODULE’
>  PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
>  ^
> /home/tonyfrancisv/vision/torchvision/csrc/vision.cpp:6:17: note: in expansion of macro ‘TORCH_EXTENSION_NAME’
>  PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
>                  ^
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by ahirner** [comment]
This is related to a `PYBIND11_MODULE` [issue](https://github.com/pytorch/extension-cpp/issues/13), fixed in pytorch master.
FWIW, the current layer branch compiled for me after #540.

**Comment by fmassa** [comment]
Closing after #540 
Note that you might need PyTorch compiled from master
