### ISSUE TITLE
USPS

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#5352]
cc @pmeier @bjuncek

**Comment by lezwon** [comment]
@pmeier I'd like to take up this issue.

**Comment by lezwon** [comment]
@pmeier I have a minor blocker I'm confused about. I'm considering using `from torchdata.datapipes.iter.Decompressor` to decompress the dataset. But I get an `ImportError` while trying to use it. I see it is used in the MNIST dataset [here](https://github.com/pytorch/vision/blob/297e2b8746d32b46d20b0e6a6f867fde65e50e8d/torchvision/prototype/datasets/_builtin/mnist.py#L9) . Any idea how to import it?

**Comment by lezwon** [comment]
@pmeier mind having a look at this?
