### ISSUE TITLE
[Pretrained model request] Inception v1 pretrained model in pytorch

### ISSUE THREAD

**Issue by Naman-ntc** [pytorch/vision#537]
In torchvision pretrained models there are a few (impactful) models that are absent from package like inception v1 and etc.

For my work I specifically need a inception v1 as the base model.

Is it possible to add it to the package. I believe for research purposes it is still important for comparing performances etc.

**Comment by ekagra-ranjan** [comment]
@fmassa This can be closed with reference to #678.

**Comment by soumith** [comment]
closed via #678
