### ISSUE TITLE
Remove option for specific interpolation mode and antialias for segmentation kernels

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#5370]
We typically use nearest interp mode for segmenation masks resize and there is no antialias option for nearest mode. I think we can remove `antialias` argument.

_Originally posted by @vfdev-5 in https://github.com/pytorch/vision/pull/5323#discussion_r796574572_

cc @vfdev-5 @datumbox @bjuncek

**Comment by datumbox** [comment]
Yes correct. masks are a geographical positioning of class Ids. We can't do any math operation that includes averaging or numeric functions on these pixel values. We can do only nearest-interpolation logic.

**Comment by pmeier** [comment]
Closed in #5407.
