### ISSUE TITLE
Building docs with `make html-noplot` ignores sphinx options

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#5388]
The command currently looks like this:

https://github.com/pytorch/vision/blob/97eddc5d6a83a9bf620070075ef1e1864c9a68ac/docs/Makefile#L26-L27

Not that `ASPHINXOPTS` is non-existent and thus we build without any options. Replacing this with `SPHINXOPTS`

https://github.com/pytorch/vision/blob/97eddc5d6a83a9bf620070075ef1e1864c9a68ac/docs/Makefile#L9

leads to a warning of sphinx gallery (see sphinx-gallery/sphinx-gallery#913) which in turn stops the build in its tracks through our `-W` usage. 

If we don't want these options for `html-noplot`, I suggest we remove the `ASPHINXOPTS` substitution. Otherwise, we should probably wait for them to fix this.

**Comment by NicolasHug** [comment]
I think I made a typo with this `ASPHINXOPTS`, happy to remove.

A  temporary workaround to have a fast build while still erroring on warnings is to do 

```
EXAMPLES_PATTERN="transforms" make html
```

which will just build the transforms example, causing the images to be present and removing the offending warning.

But the CI will build with the plots as a last resort.

**Comment by pmeier** [comment]
> I think I made a typo with this `ASPHINXOPTS`, happy to remove.

Remove `$(ASPHINXOPTS)` or remove the `A`?

**Comment by NicolasHug** [comment]
remove `ASPHINXOPTS`
