### ISSUE TITLE
How about adding more advanced models (mobile net, DPN, etc) in vision ?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [pytorch/vision#543]
Mobile net, DPN, SE-ResNeXt are useful in image classification.  I wonder whether you guys have a plan adding these models.

**Comment by vfdev-5** [comment]
There is also a [repository with pretrained recent architecture models](https://github.com/Cadene/pretrained-models.pytorch) which contains DPN, SE-ResNeXt.
HTH

**Comment by fmassa** [comment]
We have added resnext and mobilenet. I'm closing this issue and concentrating the discussion in #645
