### ISSUE TITLE
[feature request]- torchvision.transforms.ColorJitter Enhancement

### ISSUE THREAD

**Issue by neherh** [pytorch/vision#545]
Currently, the ColorJitter function only takes in a single float value for the parameters brightness, contrast, saturation and hue. The value is chosen uniformly from [max(0, 1 - brightness), 1 + brightness] (minus hue). What would improve this function is to be able to set your min and max bounds by inputting a tuple for each parameter.

**Comment by yaox12** [comment]
I'm working on it

**Comment by vishwakftw** [comment]
I think this can be closed now.
