### ISSUE TITLE
No module named 'torchvision.models.optical_flow'

### ISSUE THREAD

**Issue by aja9675** [pytorch/vision#5516]
### 🐛 Describe the bug

Attempting to follow: [https://pytorch.org/vision/master/auto_examples/plot_optical_flow.html#estimating-optical-flow-using-raft]( https://pytorch.org/vision/master/auto_examples/plot_optical_flow.html#estimating-optical-flow-using-raft)

Results in:
AttributeError: module 'torchvision.models' has no attribute 'optical_flow'

### Versions

Collecting environment information...
PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 26 2021, 20:14:08)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.4.152
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 960
GPU 1: NVIDIA GeForce RTX 3060

Nvidia driver version: 470.103.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.2
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] pytorch3d==0.6.1
[pip3] torch==1.10.2+cu113
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.11.3+cu113
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] numpydoc                  0.9.2                      py_0

**Comment by pmeier** [comment]
This module is only present in `torchvision >= 0.12.*`, for which don't have a stable release yet. You are viewing the "master" documentation, which corresponds to our `main` branch. Two possible ways out here:

1. Build `torch` and `torchvision` from source or install them from our nightly releases.
2. Wait for another week, since `torchvision == 0.12.0` is tentatively scheduled to be released on the 10th of March.

**Comment by aja9675** [comment]
Got it. Thank you.

**Comment by kmtm** [comment]
Is there an updated release date for 0.12.0? Also looking for optical flow functionality.

**Comment by pmeier** [comment]
> Looks like https://pypi.org/project/torchvision/ is out of date! Managed to install 0.12.0 via pip.

Yeah that is kinda unfortunate. We only updated the README in #5612, which was only merged after the release. We should probably update the table on the release branch. cc @malfet 

> Curious, though, if there is any advantage to waiting for the next release.

We recently revamped our model weight loading. This shouldn't affect the training result though. cc @datumbox @NicolasHug to be sure.

**Comment by datumbox** [comment]
> Looks like https://pypi.org/project/torchvision/ is out of date! 

Could you provide more information about this? Does it mean that we have issues with 0.12 for specific platform/python/cuda conbinations?

Since Friday I've been investigating an anomaly on our downloads stats. We observe a signifiant number of downloads for v0.11.3 still, which is very abnormal because usually these go down immediately after the release. This could be the reason we observe this.

**Comment by pmeier** [comment]
I think the comment refers to the compatibility table in the README. In the `0.12.0` release that is shown on PyPI, `0.11.3` is listed as latest release. But, yeah, worth checking.
