### ISSUE TITLE
Port `transforms.Pad` to `prototype.transforms`

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#5521]
cc @vfdev-5 @datumbox @bjuncek

**Comment by lezwon** [comment]
@pmeier I'd like to take up this issue.

**Comment by datumbox** [comment]
@lezwon Give us a bit more time to iron out some final changes on the API? This is mainly to avoid requiring too many change from you on the PR. Happy to ping you once we are done, what you think?

@pmeier Could you please mark the tracked issues as blocked until we finalize the aforementioned changes? For any PR that is outstanding, we should try and merge. Happy to chat offline too to see what's the best course of action.
