### ISSUE TITLE
Port `transforms.RandomVerticalFlip` to `prototype.transforms`

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#5524]
cc @vfdev-5 @datumbox @bjuncek

**Comment by federicopozzi33** [comment]
Hi @pmeier,

I'd like to work on this issue.

**Comment by pmeier** [comment]
Go ahead! 

Just as a heads-up: in the light of https://github.com/pytorch/vision/issues/5520#issuecomment-1061920594 we want to put a hold on community contributions for now. We agreed we can special case this port, since you already did #5523 and this is very similar. If you are up for it, we will happily ping you when the hold is lifted for other transforms.
