### ISSUE TITLE
Port `transforms.LinearTransformation` to `prototype.transforms`

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#5538]
cc @vfdev-5 @datumbox @bjuncek

**Comment by yassineAlouini** [comment]
@pmeier Out-of-curiosity, is any help needed for this feature or does it require too much knowledge/not advised for new contributors? :thinking:

**Comment by pmeier** [comment]
The removal of the "help wanted" label is explained in https://github.com/pytorch/vision/issues/5520#issuecomment-1061920594. In addition, https://github.com/pytorch/vision/issues/5336#issuecomment-1080586735 also applies. Thus, at this time, it is probably not a good idea to start. This has nothing to do with the knowledge / experience though. I'm happy to assign you as soon we have ironed out the problems.

If you are looking at ways to contribute, you might also have a look at [all issues tagged with the "help wanted" label](https://github.com/pytorch/vision/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22). That being said, please be aware that we (`torchvision` maintainers) are experiencing a heavy internal "load" at the moment that takes a lot of our time. I'm not saying this to discourage contributions, but rather as explanation why reviews might take some time.

**Comment by yassineAlouini** [comment]
Thanks for the details and the pointers @pmeier.
I think I found something to contribute in the meantime. 
Please let me know once things are a bit "lighter" on your side and you have more time. :ok_hand:
