### ISSUE TITLE
accimage not installed in CI skipping a number of tests

### ISSUE THREAD

**Issue by prabhat00155** [pytorch/vision#5541]
Context: Internal tests are failing on `test_transforms.py::TestAccImage::test_accimage_crop` with the following error:
```
AttributeError: 'accimage.Image' object has no attribute 'getbands'
```
It points to the following function:
```
def get_dimensions(img: Any) -> List[int]:
        if _is_pil_image(img):
>           channels = len(img.getbands())
E           AttributeError: 'accimage.Image' object has no attribute 'getbands'
```
from `functional_pil.py` which was added in this https://github.com/pytorch/vision/pull/5487.

cc @pmeier

**Comment by pmeier** [comment]
Could you link a CI run so I can see where we need to install it?

**Comment by prabhat00155** [comment]
@pmeier Added some context to this issue. This error was not caught by our CI. Also, looks like `conda install -c conda-forge accimage` from https://github.com/pytorch/accimage#installation doesn't work, so not sure how we would add this to CI.

**Comment by pmeier** [comment]
I'll have a look.

**Comment by NicolasHug** [comment]
This [comment](https://github.com/pytorch/vision/issues/268#issuecomment-775158609) from @fmassa seems to suggest that we actually don't support accimage anymore

> We don't have Travis (nor accimage) tests anymore, closing this.

That being said, we still claim on our README that accimage is part of the supported backends. Let's wait for @fmassa 's insights before we decide to fully remove it, or actually tests against it.
