### ISSUE TITLE
Migrate detection reference transforms to `torchvision.prototype.transforms`

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#5542]
In our detection references we have a couple of transformations that can handle images and bounding boxes simultaneously:

- [x] [`RandomPhotometricDistort`](https://github.com/pytorch/vision/blob/e836b3d8baf8cbfdd18fcc872631962345a65689/references/detection/transforms.py#L227) #5663
- [x] [`RandomZoomOut`](https://github.com/pytorch/vision/blob/e836b3d8baf8cbfdd18fcc872631962345a65689/references/detection/transforms.py#L164) #5551
- [x] [`RandomIoUCrop`](https://github.com/pytorch/vision/blob/e836b3d8baf8cbfdd18fcc872631962345a65689/references/detection/transforms.py#L77) @vfdev-5 https://github.com/pytorch/vision/pull/6401
- [x] [`ScaleJitter`](https://github.com/pytorch/vision/blob/e836b3d8baf8cbfdd18fcc872631962345a65689/references/detection/transforms.py#L287) @pmeier #6411
- [x] [`FixedSizeCrop`](https://github.com/pytorch/vision/blob/90dace8dbce9d59a4216a91c1d1ac6302ce3080f/references/detection/transforms.py#L331) @pmeier #6417
- [x] [`RandomShortestSize`](https://github.com/pytorch/vision/blob/90dace8dbce9d59a4216a91c1d1ac6302ce3080f/references/detection/transforms.py#L406) #6418
- [x] [`SimpleCopyPaste`](https://github.com/pytorch/vision/blob/6ca9c76adb6daf2695d603ad623a9cf1c4f4806f/references/detection/transforms.py#L543) @vfdev-5 https://github.com/pytorch/vision/pull/6451

They never made it into `torchvision.transforms` since have a different call signature than all other transforms there. Now that `torchvision.prototype.transforms` support simultaneous transforming of multiple types, we can migrate them.

cc @vfdev-5 @datumbox @bjuncek

**Comment by vfdev-5** [comment]
Closing this tracker as done
