### ISSUE TITLE
Downloading the kinetics dataset

### ISSUE THREAD

**Issue by sahilg06** [pytorch/vision#5564]
### 🐛 Describe the bug

Not able to download the kinetics dataset through **torchvision.datasets.Kinetics** class.

I used the following command
`ds = torchvision.datasets.Kinetics(root='ktest',frames_per_clip=100, num_classes='600', split='val', download=True, num_download_workers=1000, num_workers=2)`

it shows the following error after sometime
<img width="969" alt="Screenshot 2022-03-07 at 21 05 55" src="https://user-images.githubusercontent.com/59660566/157187963-d03fc992-5d8e-401f-a484-5a47c5cd3e86.png">

I was able to get rid of this error by finding and replacing **spaces** with **%20** in the k600_val_path.txt
But still few URLs were not working.

### Versions

<img width="993" alt="Screenshot 2022-03-08 at 13 01 19" src="https://user-images.githubusercontent.com/59660566/157188277-512be488-f0e9-4a38-b5c1-085e9696406d.png">

cc @pmeier

**Comment by sahilg06** [comment]
@pmeier @bjuncek I think we can add 
`line = str(line).replace(" ", "%20")` after this [line](https://github.com/pytorch/vision/blob/d8654bb0d84fd2ba8b42cd58d881523821a6214c/torchvision/datasets/kinetics.py#L183)  to get rid of the above bug.
May I initiate a pull request doing that?
Thanks!

**Comment by sahilg06** [comment]
Also, according to the code of [_make_ds_structure](https://github.com/pytorch/vision/blob/d8654bb0d84fd2ba8b42cd58d881523821a6214c/torchvision/datasets/kinetics.py#L191-L224) class
[This](https://github.com/pytorch/vision/blob/d8654bb0d84fd2ba8b42cd58d881523821a6214c/torchvision/datasets/kinetics.py#L84) url should be of CSV file containing all the details but instead its a txt file, which produces error while using the Kinetcis class.
Here is the error
<img width="940" alt="Screenshot 2022-03-08 at 14 24 55" src="https://user-images.githubusercontent.com/59660566/157202164-7b7fbe92-4817-4af7-aff2-611d79fbfbba.png">

**Comment by bjuncek** [comment]
Hi @sahilg06 -- the above URL fix seams reasonable to me. 
If you can send a PR with the fix, I can review it and test it out on Friday (I'm off due to ECCV :)). 


Regarding the `.csv` vs `.txt`, I don't know how this issue creeped in, but if I'm not mistaken [this](https://github.com/pytorch/vision/blob/d8654bb0d84fd2ba8b42cd58d881523821a6214c/torchvision/datasets/kinetics.py#L84) should just be changed to `.csv`? (at least that works for me)

If that's the case, feel free to just send everything in a single PR and I'll take a look at it tomorrow or on Friday. 
Thanks!!!

**Comment by sahilg06** [comment]
Hi @bjuncek, 
Sure, I will send the PR.
But for the 2nd issue(.csv vs .txt), https://s3.amazonaws.com/kinetics/600/annotations/train.csv or https://s3.amazonaws.com/kinetics/600/annotations/test.csv doesn't work, perhaps just changing .txt with .csv will not work

**Comment by bjuncek** [comment]
So train and val are .txt but the test is .csv 




I’ll try to send a PR to upstream CVDF to see if we can change that — otherwise we can just have an annoying special case for test I guess.

**Comment by sahilg06** [comment]
Actually, I didn't know that **split** argument supports '**test**' before you told me because in the [docs ](https://pytorch.org/vision/main/generated/torchvision.datasets.Kinetics.html#torchvision.datasets.Kinetics) its mentioned that **split** supports only **train** and **val**. So I guess '**test**' should also be added there.

And according to the [code](https://github.com/pytorch/vision/blob/d0dede0e09d6d72253080cb366742a270f0ea8cd/torchvision/datasets/kinetics.py#L212-L216) they expect "youtube_id", "time_start", "time_end" in the .csv file.
But even if for the train and val dataset there is a **.txt** file, that file doesn't contain enough info (like youtube id, time_start, time_end, etc) to make that code work for the Kinetics600 dataset.

see, **train.txt** for kinetics600 looks like this
<img width="901" alt="Screenshot 2022-03-10 at 13 24 34" src="https://user-images.githubusercontent.com/59660566/157614461-04557afc-79d3-4e86-8322-0b80c4eebe4f.png">

So according to me, for Kinetics400, everything is good.
and For Kinetics600, it will only work for test data.  Train and val files should be completely changed.
Thanks!

**Comment by sahilg06** [comment]
@bjuncek May you please review the above PR and merge it?

**Comment by sahilg06** [comment]
@bjuncek these are the required files for kinetics 600 I guess
[train.csv](https://github.com/pytorch/vision/files/8255695/train.csv)
[validate.csv](https://github.com/pytorch/vision/files/8255698/validate.csv)

**Comment by bjuncek** [comment]
As for the K600 files, I'm double checking with Joao what's the deal about the different file format.
Thanks for generating these -- we might need to use them after all

**Comment by pmeier** [comment]
Just to clear some confusion for someone else reading this thread: When @bjuncek talks about "Joao", he doesn't mean @jdsgomes, but rather Joao Carreira operating under @kinetics-cvdf. The links were updated in https://github.com/cvdfoundation/kinetics-dataset/commit/48a523ea10ad9d286e4f6f2895910fc4737e1ac5.
