### ISSUE TITLE
_find_classes() underperforming for large numbers of classes

### ISSUE THREAD

**Issue by da-wad** [pytorch/vision#557]
When training with large (>10^5) numbers of classes (Ref. https://arxiv.org/abs/1805.01978) the _find_classes() method is sloooow. Replacing the first line with: `classes = [d.name for d in os.scandir(dir) if d.is_dir()]` works correctly for me and is a lot faster (see Python docs: https://docs.python.org/3/library/os.html#os.listdir ). Thought others might appreciate this...

**Comment by soumith** [comment]
thanks a lot. would you be kind enough to open a PR for this (with a if python3 guard)

**Comment by soumith** [comment]
closed via #559
