### ISSUE TITLE
How to calculate the parameters in torchvision.transforms.Normalize(mean, std)

### ISSUE THREAD

**Issue by xiexu666** [pytorch/vision#558]
I have load my own image dataset , but don't know how to calculate the mean and std
`train_data=torchvision.datasets.ImageFolder('F:/trainData',transform=transforms.Compose(
                                                                        [
                                                                            transforms.Scale(256),
                                                                            transforms.RandomCrop(224),
                                                                            transforms.ToTensor()
                                                                        ]))`

**Comment by xiexu666** [comment]
I find the result in [http://forums.fast.ai/t/image-normalization-in-pytorch/7534/7](url)

**Comment by soumith** [comment]
you can simply run some of the dataset you have through computing mean and standard deviation.
