### ISSUE TITLE
RandomGrayscale fails for grayscale tensor inputs

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#5581]
#1505 added `rgb_to_grayscale` to tensor images and #2586 aligned it with the PIL op. It was missed that the PIL op is a no-op if the input is already grayscale, whereas the tensor op fails:

```py
>>> image_tensor = torch.rand(1, 16, 16)
>>> F.rgb_to_grayscale(image_tensor)
TypeError: Input image tensor permitted channel values are [3], but found 1
>>> image_pil = F.to_pil_image(image_tensor)
>>> F.rgb_to_grayscale(image_pil)
<PIL.Image.Image image mode=L size=16x16 at 0x7F8181384A10>
```

As the name as well as the docstring

https://github.com/pytorch/vision/blob/d0dede0e09d6d72253080cb366742a270f0ea8cd/torchvision/transforms/functional.py#L1231-L1232

imply, this transform should only handle RGB inputs so that shouldn't be an issue.

The problem is that the `RandomGrayscale` transform relies on the no-op behavior:

https://github.com/pytorch/vision/blob/d0dede0e09d6d72253080cb366742a270f0ea8cd/torchvision/transforms/transforms.py#L1613-L1616

```py
>>> transform = transforms.RandomGrayscale(p=1.0)
>>> transform(image_tensor)
TypeError: Input image tensor permitted channel values are [3], but found 1
>>> transform(image_pil)
<PIL.Image.Image image mode=L size=16x16 at 0x7F23E5B4E850>
```

Note the docstring is conflicting here:

https://github.com/pytorch/vision/blob/d0dede0e09d6d72253080cb366742a270f0ea8cd/torchvision/transforms/transforms.py#L1586-L1587

https://github.com/pytorch/vision/blob/d0dede0e09d6d72253080cb366742a270f0ea8cd/torchvision/transforms/transforms.py#L1595-L1596

BC compatible fix would be to patch `RandomGrayscale` to be an explicit no-op for grayscale inputs. 

cc @vfdev-5 @datumbox

**Comment by datumbox** [comment]
@pmeier I agree that's a problem. I think we should update `rgb_to_grayscale` for tensors to be no-op if a grayscale image is provided. Are we going to copy or not?

**Comment by vfdev-5** [comment]
PIL does a copy as well if modes are same:
https://github.com/python-pillow/Pillow/blob/92c26a77ca53a2bfbd8804f009c6c8755d0e5a43/src/PIL/Image.py#L945-L946

**Comment by pmeier** [comment]
The PIL op is even more permissive:

https://github.com/pytorch/vision/blob/d0dede0e09d6d72253080cb366742a270f0ea8cd/torchvision/transforms/functional_pil.py#L361-L362

For `num_output_channels == 1`, it converts an arbitrary color space to grayscale. Maybe this is why the names of the ops are also not aligned:

https://github.com/pytorch/vision/blob/d0dede0e09d6d72253080cb366742a270f0ea8cd/torchvision/transforms/functional_tensor.py#L145

https://github.com/pytorch/vision/blob/d0dede0e09d6d72253080cb366742a270f0ea8cd/torchvision/transforms/functional_pil.py#L357

Thus, aligning both ops is more complicated and requires a design like #5567. I'm not eager to port this back. 

Maybe we can only fix this on `RandomGrayscale` as proposed above?

**Comment by datumbox** [comment]
I think fixing `rgb_to_grayscale` is more inlined with the way the new API works. Thoughts?

**Comment by datumbox** [comment]
I think it's a good time to resolve this issue.

I read again what was discussed and my initial feeling is that Ideally I would like to align the two low-level kernels to behave the same (do the no-op) rather than outsourcing this handling to the RandomGrayscale transform. I could be wrong though and the other solution might be preferable for reasons I don't see currently. 

@pmeier and @vfdev-5 could you please weight the pros/cons, align and make a proposal?

**Comment by pmeier** [comment]
Both `F.to_grayscale` and `F.rgb_to_grayscale` will be deprecated in favor of `F.convert_color_space`. The implementation is roughly

```py
def rgb_to_grayscale(inpt: Any, num_output_channels: int = 1) -> Any:
    output = convert_color_space(
        inpt,
        color_space=features.ColorSpace.GRAY,
        old_color_space=features.Image.guess_color_space(inpt) if isinstance(inpt, torch.Tensor) else None,
    )
    if num_output_channels == 3:
        output = convert_color_space(
            inpt,
            color_space=features.ColorSpace.RGB,
            old_color_space=features.ColorSpace.GRAY,
        )
    return output
```

This will align the behavior for PIL and tensor images to be a no-op in case the input is already a grayscale image. That is in line with what `F.convert_color_space` does:

https://github.com/pytorch/vision/blob/c6a715c7b967086d105fe8de5d50fe0c82ea3b5a/torchvision/prototype/transforms/functional/_meta.py#L106-L110

https://github.com/pytorch/vision/blob/c6a715c7b967086d105fe8de5d50fe0c82ea3b5a/torchvision/prototype/transforms/functional/_meta.py#L162-L163

In that sense my vote is out to align these deprecated kernels. 

I don't have a strong opinion on whether or not we want to backport this to the current stable API. On one hand we are not ready to migrate to the new API meaning we leave a known bug. On the other hand, no one ever complained about it and I only found it while writing the new transform. Given that it is not a silent bug, I would also be ok to leave it.

**Comment by datumbox** [comment]
I think the misalignment between the PIL and Tensor kernel is a bug. We always aimed to ensure that Tensor kernels behave the same as PIL kernels and we have a bunch of unit-tests to ensure that this was the case. I think this fell through the cracks.

I agree we should fix the bug by aligning the kernels. I think the plan is the same but I would phrase it differently and connect it less with the new API:
- Align the 2 kernels on `F` stable. Aka ensure that tensor does a no-op in case it's already grayscale
- Adjust the new API to reflect the above behaviour for `rgb_to_grayscale()`. I agree that the specific method will be deprecated in favour of the more generic `convert_color_space()` but still worth aligning the two to ensure a smooth BC transition between the APIs.

I think we are fully aligned but let me know if you have any concerns or I missed anything.
