### ISSUE TITLE
`adjust_brightness` gives different results for batched vs single transform for small, grayscale images

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#5595]
```py
import torch
from torchvision.transforms import functional as F

# most likely arbitrary, could reproduce for every seed in range(1000)
torch.manual_seed(0)

# has to be > 1
batch_size = 2
# has to be == 1
num_channels = 1
# has to be small, < 256 in my experiments
height, width = 16, 18
# has to be != 1.0
sharpness_factor = 0.5

image_batch = torch.rand(batch_size, num_channels, height, width)

torch.testing.assert_close(
    F.adjust_sharpness(image_batch, sharpness_factor=sharpness_factor).split(1),
    [F.adjust_sharpness(image, sharpness_factor=sharpness_factor) for image in image_batch.split(1)],
    atol=0,
    rtol=0,
)
```

```
AssertionError: Tensor-likes are not equal!

Mismatched elements: 49 / 288 (17.0%)
Greatest absolute difference: 5.960464477539063e-08 at index (0, 0, 1, 3)
Greatest relative difference: 1.306851127832126e-07 at index (0, 0, 1, 6)
```

This bug is currently hidden by our test suite, since https://github.com/pytorch/vision/pull/4480/commits/33ff26590ac973f4a682e3d7a13c4044991ac118 in #4480 introduced a **global** `atol` on our equality checks:

https://github.com/pytorch/vision/blob/090d8237d30befeb2326aad628ca80757adfea81/test/common_utils.py#L140

With that, 

https://github.com/pytorch/vision/blob/a8bde78130fd8c956780d85693d0f51912013732/test/test_functional_tensor.py#L836

passes 

https://github.com/pytorch/vision/blob/a8bde78130fd8c956780d85693d0f51912013732/test/common_utils.py#L194-L198

although it shouldn't. See #5586 for failing CI runs if we revert to `atol=0`.

---

My best guess to what is happening is that there is an algorithm change depending on image shape in 

https://github.com/pytorch/vision/blob/090d8237d30befeb2326aad628ca80757adfea81/torchvision/transforms/functional_tensor.py#L841

The `sharpness_factor != 1.0` is only relevant because for `sharpness_factor == 1.0`, the result of the convolution is not used in the output:

https://github.com/pytorch/vision/blob/090d8237d30befeb2326aad628ca80757adfea81/torchvision/transforms/functional_tensor.py#L259

Here `ratio == sharpness_factor` and `img2 == conv2d(...)`.

cc @vfdev-5 @datumbox @pmeier

**Comment by datumbox** [comment]
Thanks for documenting. Do we need to use `atol=0`? I'm trying to understand if the difference matters of it's a rounding error. Why `rtol=0, atol=1e-6` is not enough?

**Comment by datumbox** [comment]
Thanks for documenting. Do we need to use `atol=0`? I'm trying to understand if the difference matters of it's a rounding error. Why `rtol=0, atol=1e-6` is not enough?

**Comment by NicolasHug** [comment]
I've also observed the batch size to result in differences in model outputs when working on RAFT, which in turn **significantly** affected the reported epe.
 
Here the `~e-7` error isn't really significant for float32, so there's probably not much we can (or should) do about it.

But as we discussed offline, we should bring back `assert_equal` to `rtol=0, atol=0`.  If we need more tolerance, we should be using `assert_close`. In general we should probably never be using `assert_equal` on float tensors.

**Comment by pmeier** [comment]
@datumbox 

> Do we need to use `atol=0`?

Depends what you mean:

- "Do we need to use `atol=0` in `assert_equal`?"

Yes. `assert_equal` was specifically added to have an equality check. If we want to allow tolerances, we should use `torch.testing.assert_close` directly. 

- "Do we need to use `atol=0` in the test?"

Nope. I don't know what tolerances are acceptable here, but I agree with @NicolasHug that `atol=1e-6` is probably fine for float32. If you agree, I would switch the test from `assert_equal(...)` to `torch.testing.assert_close(..., atol=1e-6, rtol=0)`.

**Comment by NicolasHug** [comment]
> If you agree, I would switch the test from assert_equal(...) to torch.testing.assert_close(..., atol=1e-6, rtol=0).

Yes :)

**Comment by datumbox** [comment]
@pmeier Apologies, I should have been clearer. My was suggesting that using an `atol=1e-6` should be enough for our use-case and we don't really need to set it to 0.

It seems we are all in agreement here.
