### ISSUE TITLE
doc-models.inception_v3: Add information about expected input size

### ISSUE THREAD

**Issue by sauercrowd** [pytorch/vision#560]
While using the pretrained inception v3 model I wasnt aware that the input size has to be 299x299, as I figured out after a little bit of try and error and searching.

I hope I didn't miss something in the docs, but if not it might make sense to add a small note in the models.inception_v3 doc that the expected tensor size is different for this model.

**Comment by fmassa** [comment]
This is currently "documented" in https://github.com/pytorch/vision/blob/master/torchvision/models/inception.py#L77, but I agree that it would be better to have it more visible in the official documentations.
Could you send a PR improving the documentation?

**Comment by sauercrowd** [comment]
Sure, I take that!

**Comment by ekagra-ranjan** [comment]
@fmassa I think this can be closed :)

**Comment by sauercrowd** [comment]
I'll close it 👍
