### ISSUE TITLE
`F.pad` is broken for PIL images and `fill: str`

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#5627]
On the surface `F.pad` for PIL images seems to support str arguments for `fill`:

https://github.com/pytorch/vision/blob/053e7ebd1b50b7a506cfd6e2389043ec05414b1c/torchvision/transforms/functional_pil.py#L157-L158

Internally though, it calls `_parse_fill`

https://github.com/pytorch/vision/blob/053e7ebd1b50b7a506cfd6e2389043ec05414b1c/torchvision/transforms/functional_pil.py#L304-L308

which in most cases relies on fill being numeric. Thus, actually passing a string doesn't work although PIL supports it.

```py
>>> image = PIL.Image.fromarray(torch.randint(0, 256, (256, 256, 3), dtype=torch.uint8).numpy())
>>> F.pad(image, 128, fill="black")
ValueError: invalid literal for int() with base 10: 'black'
>>> PIL.ImageOps.expand(image, border=128, fill="black")
<PIL.Image.Image image mode=RGB size=512x512 at 0x7FA4DD37FBD0>
```

This traces back to #2284 and specifically to

https://github.com/pytorch/vision/blob/37a0d8d68ab2c537d2cda1136d0366874d2fad5f/torchvision/transforms/functional.py#L334-L337

which will makes no sense for `fill: str`. 

Given that #2284 was included from `0.7.0` upwards and we haven't gotten any report yet, my guess is that the functionality is not really used. Since we want to deprecate `fill: str` anyway (https://github.com/pytorch/vision/pull/5621#discussion_r827271131), I would opt to simply remove all mentions of it. Thoughts?

cc @vfdev-5 @datumbox

**Comment by datumbox** [comment]
That's indeed a very convenient bug. We should remove it rather than fix it, I agree. Nevertheless we should consider removing/deprecating string colours from the transforms not only for pad but also for all other transforms as these won't be compatible with the new API for non-PIL images.

**Comment by pmeier** [comment]
In total are two mentions of `fill: str` in `transforms`

https://github.com/pytorch/vision/blob/053e7ebd1b50b7a506cfd6e2389043ec05414b1c/torchvision/transforms/transforms.py#L403

https://github.com/pytorch/vision/blob/053e7ebd1b50b7a506cfd6e2389043ec05414b1c/torchvision/transforms/transforms.py#L598

https://github.com/pytorch/vision/blob/9edd22c8a07a8c99324a73ec4dd6c553e2c8d410/torchvision/transforms/functional.py#L451

https://github.com/pytorch/vision/blob/9edd22c8a07a8c99324a73ec4dd6c553e2c8d410/torchvision/transforms/functional_pil.py#L157-L158

The only "non-pad" reference is on `RandomCrop`, which internally also use `F.pad` and thus is also broken.

**Comment by datumbox** [comment]
How about random erasing's value?
https://github.com/pytorch/vision/blob/9edd22c8a07a8c99324a73ec4dd6c553e2c8d410/torchvision/transforms/transforms.py#L1653-L1654

I suspect that string is not really supported there so worth checking.

There might be more like this. Worth having a deep check on the code to config these are the only references.

**Comment by pmeier** [comment]
Good catch. I only looked for `fill`. I'll have another look.

**Comment by pmeier** [comment]
Looking again for all `str` mentions, the only additional mention of a `str` representing a numeric value is `RandomErasing` as you found. Still, `value: str` is actually not correct here. It should be `value: Literal["random"]`:

https://github.com/pytorch/vision/blob/9edd22c8a07a8c99324a73ec4dd6c553e2c8d410/torchvision/transforms/transforms.py#L1653-L1656
