### ISSUE TITLE
ImportError: libcupti.so.10.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#5635]
### 🐛 Describe the bug

Multiple `binary_linux_conda_*_cu*` jobs are currently [failing](https://app.circleci.com/pipelines/github/pytorch/vision/15843/workflows/88805119-e3fc-4009-9ff2-5344feb6d36c/jobs/1281404) on the latest main with the following error:
```
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import torch
  File "/opt/conda/conda-bld/torchvision_1647515141078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/torch/__init__.py", line 199, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcupti.so.10.2: cannot open shared object file: No such file or directory
```

Seems like a missing dependency problem. Same applies for `libcupti.so.11.3` [here](https://app.circleci.com/pipelines/github/pytorch/vision/15840/workflows/9a49502e-3f15-454d-b302-cdf86f7d3a4e/jobs/1281138).

### Versions

Latest main branch 39772ec

**Comment by malfet** [comment]
Thank you for reporting. Likely caused by the change that makes cupti a dynamic dependency. 
cc: @ezyang

**Comment by ezyang** [comment]
We can switch back to statically linking cupti as well, I just need to do what malfet suggested when I changed the defaults anyway!

**Comment by malfet** [comment]
@ezyang imo we should just bundle cupti into the conda package

**Comment by isaak-willett** [comment]
Hej @malfet I'm facing the same issue with my build system, error below
```bash
/home/ubuntu/.cache/bazel/_bazel_ubuntu/8de0a1069de8d166c668173ca21c04ae/execroot/com_lyft_avsoftware/bazel-out/k8-fastbuild/bin/src/chronos/tasks/feed_task_cuda_test.runfiles/com_lyft_avsoftware/src/chronos/tasks/feed_task_cuda_test: 

error while loading shared libraries: libcupti.so.11.0: cannot open shared object file: No such file or directory
```
To clarify I build my own pytorch and vision distros using our internal cuda == 11.0, lately when upgrading from torch 1.9 -> 1.12 and vision 1.10 -> 1.13 this same error has been coming up. Do you know if there has been any torch/vision internal change to the linking between those two versions that would effect this?
