### ISSUE TITLE
[enhancement] computer vision and bounding box detection

### ISSUE THREAD

**Issue by isalirezag** [pytorch/vision#565]
it would be really useful to have some functions like this:
http://chainercv.readthedocs.io/en/stable/reference/visualizations.html

**Comment by fmassa** [comment]
I'm working on a Object Detection and Instance Segmentation library that will be open-sourced, and will contain functionalities like those that you mentioned.

I'm closing this issue as it's being tracked by https://github.com/pytorch/vision/issues/425 and https://github.com/pytorch/vision/issues/440

Thanks!
