### ISSUE TITLE
imagenet22k trained model weights

### ISSUE THREAD

**Issue by tstandley** [pytorch/vision#5650]
### 🚀 The feature

Add an argument to make loading imagenet22k weights as painless as loading imagenet1k pretrained weights.

### Motivation, pitch

Since most people using pretrained models will just use a torchvision.models model, it'd be great if it were easy to specify to use an imagenet22k or at least greater than 1k model when such weights are available. Features obtained from models trained with more classes do much better on downstream tasks. Also, these models are better when fine-tuned. I think a large portion of the user-base is leaving performance on the table by using the default imagenet1k trained weights.

cc @datumbox

**Comment by datumbox** [comment]
@tstandley Thanks for the proposal.

This should already be supported by the upcoming [Multi-weight support API](https://pytorch.org/blog/introducing-torchvision-new-multi-weight-support-api/). Among other things, it will allow us to make available weights trained on different datasets. 

The work to migrate to main TorchVision is currently on-going and you can keep track of its progress at #5618. We aim to land this on main torchvision in a couple of weeks.

I'm going to close the issue to keep things tidy but feel free to reopen if you have more comments or concerns!

**Comment by tstandley** [comment]
Thanks, @datumbox!
BTW, do you plan to have 22k weights available for any of the models? I don't believe they are available currently. I've noticed that features from networks trained on imagenet22/21k are far superior. But I bet they'd be even better if they had been trained using your new training recipe.

**Comment by datumbox** [comment]
@tstandley We can certainly look into it now that we have a mechanism to load them. Note that we've already started adding weights from larger datasets (see #5793). I recommend starting a new issue because this one was more about making it possible to load other weights; this way we can check how much interest there is from the community and act accordingly.
