### ISSUE TITLE
Does torchvision nightly support rocm 5.0 Linux?

### ISSUE THREAD

**Issue by xiaoyu-work** [pytorch/vision#5658]
### 🚀 The feature

I couldn't find Linux version torchvision in https://download.pytorch.org/whl/nightly/rocm5.0/torch_nightly.html. Does vision nightly support rocm 5.0 Linux? If not, any reason it doesn't? Can we add support for this?

### Motivation, pitch

Our image needs torchvision on Linux for ROCM 5.0

cc @jeffdaily @jithunnair-amd

**Comment by jithunnair-amd** [comment]
Thanks for reporting this issue @xiaoyu-work ... we will be filing a PR for this shortly, stay tuned!

**Comment by xiaoyu-work** [comment]
Hi @jithunnair-amd, any update on this?

**Comment by xiaoyu-work** [comment]
Closed as torchvision nightly added rocm 5.0 Linux support now.
