### ISSUE TITLE
`cmake_linux_gpu` fails with libcudnn.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#5678]
### 🐛 Describe the bug

The `cmake_linux_gpu` job is currently [failing](https://app.circleci.com/pipelines/github/pytorch/vision/16056/workflows/6211a9c5-772a-4cc9-97e7-e61ce888c388/jobs/1299847) with the following error message:
```
OSError: libcudnn.so.8: cannot open shared object file: No such file or directory
```

Looks like a dependency issue on CUDA. The issue first appeared couple of days ago and persists across nightlies. 

### Versions

latest main

cc @seemethere

**Comment by pmeier** [comment]
Seems no longer to be the case: https://app.circleci.com/pipelines/github/pytorch/vision/16195/workflows/16ec8058-6884-4aab-90ff-6c6a8a111017/jobs/1312141
