### ISSUE TITLE
transforms.Lambda fails on class functions

### ISSUE THREAD

**Issue by qbilius** [pytorch/vision#570]
`transforms.Lambda` appears to fail when a function that is passed to it is a class function:

```python
import torchvision

class MyClass(object):

    def my_transform(self, img):
        return img

def my_transform(img):
    return img

t = MyClass()

print('Pure function works')
torchvision.transforms.Lambda(my_transform)
print('Class function fails')
torchvision.transforms.Lambda(t.my_transform)
```
Output:
```
Pure function works
Class function fails
Traceback (most recent call last):
  File "test_pytorch.py", line 17, in <module>
    torchvision.transforms.Lambda(t.my_transform)
  File "/braintree/home/qbilius/libs/miniconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 279, in __init__
    assert isinstance(lambd, types.LambdaType)
AssertionError
```

My understanding it that `isinstance(lambd, types.LambdaType)` is not the best way to check if something is a function or not. Rather, `callable` or `__call__` [should be used](https://stackoverflow.com/a/624939).

I could submit a quick PR if that seems like a good solution.

**Comment by vfdev-5** [comment]
@qbilius Just wonder if you use a class to define a transformation, why not to use it directly:
```
transform = [
    MyClass(*args, **kwargs),
   ToTensor()
]
```
where your class defines `__call__` method to execute a transformation on the input like it is done for other transformation...

**Comment by vfdev-5** [comment]
IMO, it would be better to have modularity instead of a single class that can make everything...
otherwise, you can use it like this too:
```python
torchvision.transforms.Lambda(lambda x: t.my_transform(x))
```
I think the change of `torchvision.transforms.Lambda` to check if it is a callable does not make sense, because a transform is a callable, so call it directly:
```python
import numpy as np

class A:
    
    def my_tr(self, x):
        print("transform x")
        return np.zeros((11, 12, 3))

a = A()    

t = Compose([
    a.my_tr,
    ToTensor()
])
```

What do you think ?

**Comment by vfdev-5** [comment]
Glad that you can adopt a more simple solution :)

Concerning lambdas, I think the idea is similar to pythonic lambda expressions:
```python
t = Lambda(lambda img: img**2)
```
More realistic example, can be found even in torchvision with ColorJitter, where lambdas allows to wrap a function with initialization: 
```python
t = Lambda(lambda img: F.adjust_contrast(img, contrast_factor))
``` 
I agree with you that this can look artificial. 

PS. if you think that there is an answer to your question you can close the issue and reopen it if there's still something missing.

**Comment by qbilius** [comment]
Thanks for your kind help!
