### ISSUE TITLE
torchvision.utils.draw_bounding_boxes set font_size

### ISSUE THREAD

**Issue by haozhihang123** [pytorch/vision#5725]
### 🚀 The feature

font_ The size setting must be specified at the same time as the font to be valid, otherwise it is invalid.
I think utils.py in torchvision Line 239 can be improved.Make font settings and font size settings separate.
utils.py Line 239:
"txt_font = ImageFont.load_default() if **font is None** else ImageFont.truetype(font=font, size=font_size)"

### Motivation, pitch

Improve the experience of torchvision.draw_bounding_boxes

**Comment by oke-aditya** [comment]
If I understand correctly, You want `font_size` to work for default font right? 
But I believe the PIL Does not have this functionality to load default font with a given font size

See https://github.com/python-pillow/Pillow/issues/2695

**Comment by haozhihang123** [comment]
Thank you. I see.

**Comment by pmeier** [comment]
Given that this is just a small utility that we provide and `PIL` does not have this option, I don't think there is much that we can do for now. Still, thanks for the request @haozhihang123 and @oke-aditya for linking the relevant issue!

**Comment by oke-aditya** [comment]
Although one way is to Have a default font from torchvision side and not rely on OS. Which would allow to set `font_size`

I won't recommend this fix. As the current API works. 

It might be wiser to throw a warning if user supplies `font_size` without specifying font.

**Comment by pmeier** [comment]
> It might be wiser to throw a warning if user supplies `font_size` without specifying font.

Yes, that is indeed a good change. Whenever user input gets ignore for any reason, we should warn about it. @oke-aditya do you want to send a PR?

**Comment by oke-aditya** [comment]
I believe some new contributor could take this. As it's a good first issue :) 

(Of course I can submit a PR. But will feel more happy to see a new contributor)

**Comment by oke-aditya** [comment]
feel free to have a go
