### ISSUE TITLE
No py37 builds on conda

### ISSUE THREAD

**Issue by jayanthkoushik** [pytorch/vision#574]
Though the website states torchvision, and torchvision-cpu can be installed on python 3.7 with conda, the actual builds do not exist, and trying to install triggers a python downgrade.

    $ conda info  # output filtered
     active environment : None
          conda version : 4.5.9
         python version : 3.7.0.final.0
               platform : linux-64
             user-agent : conda/4.5.9 requests/2.19.1 CPython/3.7.0 Linux/2.6.32-696.20.1.el6.x86_64 centos/6.9 glibc/2.12
    $ conda install -c pytorch torchvision # output filtered
    The following NEW packages will be INSTALLED:
        torchvision:          0.2.1-py36_1                        pytorch
    The following packages will be DOWNGRADED:
        python:               3.7.0-hc3d631a_0                            --> 3.6.6-hc3d631a_0

**Comment by soumith** [comment]
thanks for the report. I've fixed this for torchvision now. Fixing it for torchvision-cpu in an hour or so.

**Comment by soumith** [comment]
fixed now for both `torchvision` and `torchvision-cpu`
