### ISSUE TITLE
Has Fashion-MNIST been removed?

### ISSUE THREAD

**Issue by jayurbain** [pytorch/vision#575]
Has Fashion-MNIST been removed? I'm using torchvision 0.2.0

# Download and load the training data
trainset = datasets.FashionMNIST('F_MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-6b2c8515f4fb> in <module>()
      7                                 transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
      8 # Download and load the training data
----> 9 trainset = datasets.FashionMNIST('F_MNIST_data/', download=True, train=True, transform=transform)
     10 trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)
     11 

AttributeError: module 'torchvision.datasets' has no attribute 'FashionMNIST'

**Comment by soumith** [comment]
it's still there, and it's definitely part of `0.2.0`. https://github.com/pytorch/vision/blob/v0.2.0/torchvision/datasets/__init__.py#L15

Maybe you have a botched install? Try reinstalling `torchvision`?

**Comment by jayurbain** [comment]
Thank you. My error. I was using the wrong envirpnment
