### ISSUE TITLE
Support loading image in color in vision/torchvision/datasets/caltech.py

### ISSUE THREAD

**Issue by YEthYuan** [pytorch/vision#5795]
### 🚀 The feature

Currently, the function in this class could only load the greyscale pictures (please check lines 86 and 199). However, people would always use them in color. Could you please consider adding an option to let the function return images in color? Maybe you could consider adding .convert("RGB") to the current Image.open() function. 

### Motivation, pitch

I'm currently using this dataset to train my model and prefer to load the images in color but not just greyscale pictures. 

### Alternatives

```
        img = PIL.Image.open(os.path.join(self.root,
                                      "101_ObjectCategories",
                                      self.categories[self.y[index]],
                                      "image_{:04d}.jpg".format(self.index[index])))

        # self.color is the new option to let user choose whether to load greyscale pictures or RGB pictures
        img = img.convert("RGB") if self.color == "RGB" else img  
```
Hope the code above could better illustrate my proposal

cc @pmeier @YosuaMichael

**Comment by pmeier** [comment]
> Currently, the function in this class could only load the greyscale pictures (please check lines 86 and 199)

That is not true:

```py
>>> dataset = Caltech101(".")
>>> image, _ = dataset[0]
>>> image.mode
RGB
```

However, you are right that these datasets do not convert to RGB before returning the image. Unfortunately, that would be BC breaking change. Thus, IMO the easiest way for you is to add a custom transform:

```py
class ToRGB:
    def __call__(self, image):
        return image.convert("RGB") if image.mode != "RGB" else image
```

You can use it like `dataset = Caltech101(..., transform=ToRGB())`. If you already have a transform, you can chain them with a `torchvision.transforms.Compose`.

We are currently revamping our datasets and the new ones will also make no assumptions on the colorspace so you will always have to do something like this yourself.

**Comment by YEthYuan** [comment]
Thank you for your suggestion, I will correct my code!
