### ISSUE TITLE
Error in loading pretrained SqueezeNet Model

### ISSUE THREAD

**Issue by soumendukrg** [pytorch/vision#580]
I recently installed the latest stable releases of pytorch 0.4.1 and torchvision 0.2.1 through anaconda. I tried running squeezenet1_0 and 1_1, however loading the pretrained network **(torchvision.models.squeezenet1_1(pretrained=True))** always failed with the following error.

```
/home/min/a/ghosh37/.conda/envs/5.2.0/soumendu/lib/python3.7/site-packages/torchvision-0.2.1-py3.7.egg/torchvision/models/squeezenet.py:94: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
/home/min/a/ghosh37/.conda/envs/5.2.0/soumendu/lib/python3.7/site-packages/torchvision-0.2.1-py3.7.egg/torchvision/models/squeezenet.py:92: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
Traceback (most recent call last):
  File "val1000.py", line 271, in <module>
    a = TrainModel(i)
  File "val1000.py", line 124, in __init__
    self.model = models.squeezenet1_1(pretrained=True)
  File "/home/min/a/ghosh37/.conda/envs/5.2.0/soumendu/lib/python3.7/site-packages/torchvision-0.2.1-py3.7.egg/torchvision/models/squeezenet.py", line 129, in squeezenet1_1
  File "/home/min/a/ghosh37/.conda/envs/5.2.0/soumendu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 704, in load_state_dict
    load(self)
  File "/home/min/a/ghosh37/.conda/envs/5.2.0/soumendu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 699, in load
    state_dict, prefix, local_metadata, strict, missing_keys, unexpected_keys, error_msgs)
  File "/home/min/a/ghosh37/.conda/envs/5.2.0/soumendu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 667, in _load_from_state_dict
    if key.startswith(prefix):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
Its works fine with **torchvision.models.squeezenet1_1(pretrained=False)**

I have another version of torchvision 0.2.0, it runs properly in that for both cases. Has the code been changed recently or has there been any change in the saved model? Please advise.

**Comment by fmassa** [comment]
I just tried it and it works fine for me.

Could you try deleting the cache from `~/.torch/models`, update PyTorch and torchvision and try again?

**Comment by jansenicus** [comment]
It is reproducible by running the examples 'FINETUNING TORCHVISION MODELS' provided  in the [pytorch tutorials](https://pytorch.org/tutorials/beginner/finetuning_torchvision_models_tutorial.html)
with the following version:
torch==0.4.1
torch.vision==0.2.1
the following warnings occured:
```
/home/bri/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/models/squeezenet.py:94: 
UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
/home/bri/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/models/squeezenet.py:92: 
UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
```

**Comment by fmassa** [comment]
The user-warning is normal and has been fixed in torchvision master, but did you encounter the error again?

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
