### ISSUE TITLE
Zero-initialized head weights in VisualTransformer 

### ISSUE THREAD

**Issue by mbanani** [pytorch/vision#5804]
I noticed that the weights of the head linear layer seem to be zero initialized by default [here](https://github.com/pytorch/vision/blob/3fa2414866f69a5ba541bb27a94963df01d9bd06/torchvision/models/vision_transformer.py#L236). I wasn't sure if this was a mistake or if there's a reason why it's zero initialized. Other implementations I saw used normal or truncated normal initialization. 

cc @datumbox @vfdev-5

**Comment by datumbox** [comment]
Thanks for reporting @mbanani. This looks like a mistake indeed. 

@mannatsingh @sallysyw Do you have any thoughts on whether this is a bug? Is the initial intention to zero only the bias and leave the weights on the default initialisation scheme?

**Comment by mannatsingh** [comment]
The zero initialization follows Classy. I had followed the original paper which also zero inits the kernel - https://github.com/google-research/vision_transformer/blob/main/vit_jax/models_vit.py#L297.

So Torchvision isn't alone in doing the zero weight init - there's classy (https://github.com/facebookresearch/ClassyVision/blob/main/classy_vision/heads/vision_transformer_head.py#L75) and pycls (https://github.com/facebookresearch/pycls/blob/main/pycls/models/vit.py#L294-L295) which also do the same thing.

**Comment by mbanani** [comment]
Thanks for following up. I am very curious, do you have any intuition to why zero-initialization makes sense here?

**Comment by mannatsingh** [comment]
I don't have a good intuition for this - I don't think it is needed though, you can init the weights for the linear layer with non-zero initialization and it should work okay!

**Comment by datumbox** [comment]
@mannatsingh thanks a lot for all the references!

@mbanani given the above, I would say that it's just an implementation detail. Given its location, this shouldn't cause issues on the training (we've trained multiple variants of this and we always managed to get much higher accuracies than those on the original paper). If this is a problem for your use-case, you can just overwrite the initialization of the last layer directly.

I'm going to close the ticket as I believe we answered the original question. If that's not correct, please feel free to reopen. Thanks!
