### ISSUE TITLE
Feature Request : Calculation of hog on RGB images

### ISSUE THREAD

**Issue by 22shivangi** [pytorch/vision#582]
Hi Team,

Is it possible for you to implement the histogram of oriented gradients to extract features from RGB images?
Currently, I am loading data using torchvision data loaders and doing these calculations in python. This slows down things a bit. It would be great if you could add this as a feature in torchvision itelf. It would save a lot of compute time. :)

**Comment by varunagrawal** [comment]
Why not do this in OpenCV? They have an efficient implementation that you can then convert to a Tensor object from numpy.

**Comment by fmassa** [comment]
I agree with @varunagrawal , it is very efficient to convert torch tensors to numpy arrays and back, so that you can use OpenCV or any other library to perform that.

That being said, HOG images usually lose a lot of information that is very useful to have for deep networks.
