### ISSUE TITLE
Pad to target size

### ISSUE THREAD

**Issue by BeFranke** [pytorch/vision#5829]
### 🚀 The feature

A Transform similar to torchvision.transforms.Pad that pads to a target size (i.e. height and width).

### Motivation, pitch

Many datasets provided by torchvision have images with different resolutions. In order to create a batch, the images need to have the same size, therefore this transform would come in handy and increase the user-friendlyness of torchvision.

cc @vfdev-5 @datumbox

**Comment by pmeier** [comment]
`CenterCrop` is already doing that:

```py
import torch
from torchvision.transforms import CenterCrop

torch.manual_seed(1234)
transform = CenterCrop([32, 32])

for _ in range(5):
    size = torch.randint(1, 64, (2,)).tolist()
    image = torch.empty(3, *size)

    print(size, transform(image).shape[-2:])
```

```
[7, 40] torch.Size([32, 32])
[22, 48] torch.Size([32, 32])
[36, 44] torch.Size([32, 32])
[7, 61] torch.Size([32, 32])
[8, 31] torch.Size([32, 32])
```

Its behavior has two branches:
1. If the image is larger than the target size, we take the middle segment
2. If the image is smaller than the target size, we pad it

**Comment by BeFranke** [comment]
Thank you very much, I didn't know about this!
