### ISSUE TITLE
error: can't copy 'build\lib.win-amd64-3.7\pyd': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#5830]
### 🐛 Describe the bug

The CI jobs [unittest_windows_gpu_py3.7](https://app.circleci.com/pipelines/github/pytorch/vision/16740/workflows/20601594-11bc-41b8-b409-a5e65518d60a/jobs/1356410) and [unittest_windows_cpu_py3.7](https://app.circleci.com/pipelines/github/pytorch/vision/16740/workflows/20601594-11bc-41b8-b409-a5e65518d60a/jobs/1356437) fail with:
```
error: can't copy 'build\lib.win-amd64-3.7\pyd': doesn't exist or not a regular file
```

### Versions

Main branch has been failing since 53c853282697819df2d756f5d30911fb9cf20cf3

cc @seemethere

**Comment by seemethere** [comment]
This one doesn't look related to upstream changes since the file it's trying to copy comes from torchvision itself and not upstream torch

**Comment by atalman** [comment]
Looks like the error happended in nightly between April 16 and 17. It happens during the linking:

Good linker string: 
/OUT:build\lib.win-amd64-3.7\torchvision\_C.pyd /IMPLIB:C:\Users\circleci\project\build\temp.win-amd64-3.7\Release\Users\circleci\project\torchvision\csrc\ops\autograd\_C.lib

Linker string with error:
/OUT:build\lib.win-amd64-3.7\torchvision\pyd /IMPLIB:C:\Users\circleci\project\build\temp.win-amd64-3.7\Release\Users\circleci\project\torchvision\csrc\ops\autograd\pyd.lib

Looks like some Global variable is not set correctly

**Comment by malfet** [comment]
I suspect it's caused by https://github.com/pypa/setuptools/issues/3219
Which is easily verifiable by pinning `setuptools` to say 58.0.4, which I'm doing in https://github.com/pytorch/vision/pull/5868

**Comment by atalman** [comment]
Yes looks like you are correct setuptools is the problem
