### ISSUE TITLE
Revamping our classification models docs

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#5833]
We're re-writing our models docs to make them clearer, simpler, and to properly document the [upcoming multi-weight API](https://pytorch.org/blog/introducing-torchvision-new-multi-weight-support-api/). This issue is about **adding docs for the classification models.**

Perhaps this is something @oke-aditya @YosuaMichael @lezwon @zhiqwang  would be interested in :) ?

Our latest new docs are currently [here](https://output.circle-artifacts.com/output/job/5578549b-3bfa-4059-abfa-a608ef52b36c/artifacts/0/docs/models_new.html) (this link is likely outdated by the time you look at it, but it doesn't matter; the skeleton is there). We created a separate section that will eventually be merged into the main one. We have documented a few models, but most of them are still missing. The list of models that still need docs is listed below. If you'd like to participate, please comment below with a message saying "I'm working on XYZ" where XYZ is a model, so that others don't pick the same as you do. To keep things simple, please submit one PR per model, but feel free to contribute more than one model.

### How to write docs for a model

Note: below are detailed instructions. This makes it look more complicated than it actually is. Don't be scared!

A great place to start is to look a the changes in [this PR that documents SqueezeNet](https://github.com/pytorch/vision/pull/5832/files). You'll need to do exactly the same for your model:

- Create a new `.rst` file in https://github.com/pytorch/vision/tree/main/docs/source/models. The file should [look like this](https://raw.githubusercontent.com/pytorch/vision/main/docs/source/models/squeezenet.rst), with a link to the original paper, and a list of the corresponding model builders. It should also mention the base model class and link to the `.py` file where it is defined.
- Update the list in https://github.com/pytorch/vision/blame/main/docs/source/models_new.rst to link to this new file (without the `.rst` suffix). Please keep the list alphabetically sorted
- Update the docstring of each new model builder, similarly to [this one](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/squeezenet.py#L162-L182).
    - there is a 1:1 mapping between a model builder and a Weight enum. For example, the docstring of [squeezenet1_0](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/squeezenet.py#L159) makes direct references to [SqueezeNet1_0_Weights](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/squeezenet.py#L128).
    - don't forget the [autoclass](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/squeezenet.py#L181-L182) directive in the docstring. This will auto-generate documentation for the Weight enums. You don't need to understand how this is done, but if you're curious, it's done [here](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/docs/source/conf.py#L299).

To build the docs locally, please look at our [contributing guide](https://github.com/pytorch/vision/blob/main/CONTRIBUTING.md#documentation). You won't need to worry about the gallery example, **so always use `make html-noplot`** instead of `make html` to save time.

Please don't hesitate to ping us if you need any help / guidance or if you have any question!

----

Classification models that need docs are:

- [X] Alexnet - https://github.com/pytorch/vision/pull/5886
- [X] ConvNeXt - https://github.com/pytorch/vision/pull/5869
- [X] Inception v3 - https://github.com/pytorch/vision/pull/5924
- [X] DenseNet - https://github.com/pytorch/vision/pull/5878
- [X] EfficientNet -  https://github.com/pytorch/vision/pull/5854
- [X] EfficientNet v2 - https://github.com/pytorch/vision/pull/5864
- [X] GoogLeNet - https://github.com/pytorch/vision/pull/5885
- [x] MNASNet - https://github.com/pytorch/vision/pull/5920 
- [X] MobileNet v2 -  https://github.com/pytorch/vision/pull/5899
- [X] MobileNet v3 - https://github.com/pytorch/vision/pull/5908
- [x] RegNet - https://github.com/pytorch/vision/pull/5856
- [X] ResNext - https://github.com/pytorch/vision/pull/5871
- [X] ShuffleNet v2 - https://github.com/pytorch/vision/pull/5921
- [x] VisionTransformer - https://github.com/pytorch/vision/pull/5856
- [X] Wide ResNet - https://github.com/pytorch/vision/pull/5907

**Comment by YosuaMichael** [comment]
This is great @NicolasHug ! 
I would like to try adding doc for `RegNet` and `VisionTransformer`.

**Comment by datumbox** [comment]
Great initiative to split into bite-sized chunks. :)

Tagging a few more regulars in case they are interested in helping: @xiaohu2015 @abhi-glitchhg @frgfm @yassineAlouini

**Comment by lezwon** [comment]
Hey @NicolasHug, I'd like to start off with densenet.

**Comment by oke-aditya** [comment]
I will take MobileNets :) v2 v3

**Comment by abhi-glitchhg** [comment]
I would like to take `ResNext`.

**Comment by zhiqwang** [comment]
I would like to take `ShuffleNet v2`

**Comment by xiaohu2015** [comment]
I would like to take `VisionTransformer`.

**Comment by abhi-glitchhg** [comment]
@xiaohu2015 I think @YosuaMichael  has already picked `VisionTransformer`.

**Comment by xiaohu2015** [comment]
> @xiaohu2015 I think @YosuaMichael has already picked `VisionTransformer`.

Ok, I choose another model ConvNeXt

**Comment by datumbox** [comment]
@yassineAlouini It's yours! :)

Note that EfficientNet V1 and V2 are implemented on the same class (EfficientNet). On the documentation we want to document them separately because they are 2 different papers.

**Comment by frgfm** [comment]
Hi @NicolasHug @datumbox, thanks for the tag 🙂
I'm on holidays until next Monday, I'll take a look at what's left then! Great idea to improve the doc by the way 🙌

**Comment by yassineAlouini** [comment]
> @yassineAlouini It's yours! :)
> 
> Note that EfficientNet V1 and V2 are implemented on the same class (EfficientNet). On the documentation we want to document them separately because they are 2 different papers.

Thanks. Should I work on both documentations then? Or at least start with EfficientNet? :thinking:

**Comment by NicolasHug** [comment]
@yassineAlouini sure, feel free to do both!

**Comment by NicolasHug** [comment]
You can just reference this one!

**Comment by yassineAlouini** [comment]
Since previous MRs have been merged, I can work on `GoogLeNet` doc if it is available. :ok_hand:

**Comment by NicolasHug** [comment]
Please pick as many as you'd like @yassineAlouini :)

**Comment by yassineAlouini** [comment]
Next: `Alexnet`.

**Comment by abhi-glitchhg** [comment]
I would take `Wide Resnet`

**Comment by frgfm** [comment]
Alright I'm back 😁 
Anyone wants to lend me one of those models? @oke-aditya mind if I take MobileNetV3 while you handle MobileNetV2 for instance? 🙏

**Comment by oke-aditya** [comment]
Sure Take v1. I'm back too.  Was sick :(

**Comment by NicolasHug** [comment]
Thank you so much everyone who participated so far, your help is greatly appreciated!

For those who would like to pick more models, I just opened this new issue to document the rest of the models (semantic segmantation and object detection) https://github.com/pytorch/vision/issues/5897

**Comment by frgfm** [comment]
Sad to hear this @oke-aditya :/ Happy to take care of V3 as well while I'm at it if you want!

**Comment by oke-aditya** [comment]
I Will take care of v3, slowly getting back to work. :)

**Comment by zhiqwang** [comment]
Hi @NicolasHug , Sorry for delay, I will finish `ShuffleNetV2` by tomorrow.

**Comment by NicolasHug** [comment]
No rush @zhiqwang :)

**Comment by jdsgomes** [comment]
I will work on the MNASNet - seems to be the last one

**Comment by yassineAlouini** [comment]
@NicolasHug Shouldn't the `GoogLeNet` be checked in the list? :thinking: Asking so that no one does the job again. :smile:

**Comment by NicolasHug** [comment]
Looks like we're all done! Thank you so much everyone for your help <3 !

**Comment by yassineAlouini** [comment]
Next is object detection/segmentation I guess? :thinking: @NicolasHug

**Comment by NicolasHug** [comment]
@yassineAlouini  I think we took care of that in https://github.com/pytorch/vision/issues/5897 

The only remaining docs are the ones for the classification Quantized models. https://github.com/pytorch/vision/tree/main/torchvision/models/quantization. I think I'll create another issue for these ones soon, let me know if you'd be interested!

**Comment by yassineAlouini** [comment]
@NicolasHug I see, that's great. I am interested in helping. :ok_hand:
