### ISSUE TITLE
return_layers problem about fasterrcnn_mobilenet_v3_large_fpn

### ISSUE THREAD

**Issue by WZMIAOMIAO** [pytorch/vision#5838]
### 🐛 Describe the bug

There may be a problem with the setting of return_layers in fasterrcnn_mobilenet_v3_large_fpn.  If the default setting is used, the resolution  of collected feature map is the same. As a result, the effect of detecting small targets will become worse.
https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/detection/backbone_utils.py#L225-L226
test code:
```python
import torch
from torchvision.models.detection import fasterrcnn_mobilenet_v3_large_fpn
model = fasterrcnn_mobilenet_v3_large_fpn(pretrained_backbone=False)
img = torch.randn(1, 3, 224, 224)
outputs = model.backbone(img)
[print(f"{k} shape: {v.shape}") for k, v in outputs.items()]
```
output:
```
0 shape: torch.Size([1, 256, 7, 7])
1 shape: torch.Size([1, 256, 7, 7])
pool shape: torch.Size([1, 256, 4, 4])
```
`feauture map: 0` and `feature map: 1` have same resolution(`7x7`).

may need to change:
```
returned_layers = [num_stages - 2, num_stages - 1]
```
to:
```
returned_layers = [num_stages - 3, num_stages - 1]
```

output:
```
0 shape: torch.Size([1, 256, 14, 14])
1 shape: torch.Size([1, 256, 7, 7])
pool shape: torch.Size([1, 256, 4, 4])
```

### Versions

```
PyTorch version: 1.10.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro P620
Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.3
[pip3] torch==1.10.0+cpu
[pip3] torchaudio==0.10.0+cpu
[pip3] torchvision==0.11.1+cpu
[conda] numpy                     1.21.3                   pypi_0    pypi
[conda] torch                     1.10.0+cpu               pypi_0    pypi
[conda] torchaudio                0.10.0+cpu               pypi_0    pypi
[conda] torchvision               0.11.1+cpu               pypi_0    pypi
```

cc @datumbox @YosuaMichael

**Comment by datumbox** [comment]
@WZMIAOMIAO Thanks for reporting.

I agree with you that the 2 stages provide the same resolution size. We should note that the specific variant is not described on the MobileNetV3 paper but rather was created to boost TorchVision's efforts for better mobile support for detection tasks. Back when we were doing the experiments, we found using the specific two returned layers beneficial, hence why it is kept like this. This can be overwritten by passing a different `returned_layers` param. 

If you are looking for the canonical implementation for detection described on MobileNetV3, then have a look on the `ssdlite320_mobilenet_v3_large` variant. This one performs model surgery to ensure we provide the stages described on the paper:
https://github.com/pytorch/vision/blob/11bd2eaa6d6976129836b329b01d1300babddcc9/torchvision/models/detection/ssdlite.py#L132-L134

**Comment by WZMIAOMIAO** [comment]
Wow, It's amazing. Have you published relevant papers? I want to learn.

**Comment by datumbox** [comment]
I don't think the specific work is publishable (aka has enough substance to make it worth while). From memory and my notes, the specific layers were selected by experimentally checking various configurations and selecting the one that yielded the best result for the speed we had in mind. On the other hand, the work on SSDlite is fully aligned with the paper, see MobileNetV3 [section 6.3](https://arxiv.org/pdf/1905.02244.pdf).

I'm going to close the issue because I believe I answered the question. If you have more, please don't hesitate to reopen.

**Comment by WZMIAOMIAO** [comment]
thank you!
