### ISSUE TITLE
 Revamping our semantic segmentation and object detection models docs #5833 

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#5897]
Sister issue (for classification models): https://github.com/pytorch/vision/issues/5833

We're re-writing our models docs to make them clearer, simpler, and to properly document the [upcoming multi-weight API](https://pytorch.org/blog/introducing-torchvision-new-multi-weight-support-api/). This issue is about adding docs for the detection and segmentation models.

Our latest new docs are currently [here](https://output.circle-artifacts.com/output/job/69c86c41-3a9e-4b76-aec0-1fc50c36f5f0/artifacts/0/docs/models_new.html) (this link is likely outdated by the time you look at it, but it doesn't matter; the skeleton is there). We created a separate section that will eventually be merged into the main one. We have documented a few models, but most of them are still missing. The list of models that still need docs is listed below. If you'd like to participate, please comment below with a message saying "I'm working on XYZ" where XYZ is a model, so that others don't pick the same as you do. To keep things simple, please submit one PR per model, but feel free to contribute more than one model.

### How to write docs for a model

Note: below are detailed instructions. This makes it look more complicated than it actually is. Don't be scared!

A great place to start is to look a the changes in [this PR that documents SqueezeNet](https://github.com/pytorch/vision/pull/5832/files). You'll need to do exactly the same for your model:

- Create a new `.rst` file in https://github.com/pytorch/vision/tree/main/docs/source/models. The file should [look like this](https://raw.githubusercontent.com/pytorch/vision/main/docs/source/models/squeezenet.rst), with a link to the original paper, and a list of the corresponding model builders. It should also mention the base model class and link to the `.py` file where it is defined.
- Update the models list in https://github.com/pytorch/vision/blame/main/docs/source/models_new.rst to link to this new file (without the `.rst` suffix). Please keep the list alphabetically sorted
- Update the docstring of each new model builder, similarly to [this one](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/squeezenet.py#L162-L182).
    - there is a 1:1 mapping between a model builder and a Weight enum. For example, the docstring of [squeezenet1_0](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/squeezenet.py#L159) makes direct references to [SqueezeNet1_0_Weights](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/squeezenet.py#L128).
    - don't forget the [autoclass](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/squeezenet.py#L181-L182) directive in the docstring. This will auto-generate documentation for the Weight enums. You don't need to understand how this is done, but if you're curious, it's done [here](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/docs/source/conf.py#L299).
    - don't forget to document the `**kwargs` parameter. Usually these are passed to the base class, but if they don't do anything, just document them as `**kwargs: unsued.`

To build the docs locally, please look at our [contributing guide](https://github.com/pytorch/vision/blob/main/CONTRIBUTING.md#documentation). You won't need to worry about the gallery example, **so always use `make html-noplot`** instead of `make html` to save time.

Please don't hesitate to ping us if you need any help / guidance or if you have any question!

------

Semantic segmentation:

- [X] FCN with Resnet (101 and 50) -  #5915
- [X] LRASPP - https://github.com/pytorch/vision/pull/5923

Object Detection:

- [X] FCOS -  #5901
- [X] FasterRCNN - https://github.com/pytorch/vision/pull/5918
- [X] MaskRCNN - https://github.com/pytorch/vision/pull/5900
- [ ] SSD300
- [X] SSDLite320 - https://github.com/pytorch/vision/pull/5917

**Comment by abhi-glitchhg** [comment]
I can work on `FasterRCNN`

**Comment by frgfm** [comment]
Happy to take care of `MaskRCNN` 👍

**Comment by xiaohu2015** [comment]
I can work on FCOS

**Comment by oke-aditya** [comment]
I will take LRASPP

**Comment by frgfm** [comment]
I'll take FCN & SSDLite to finish this then :)

**Comment by NicolasHug** [comment]
Thanks a lot everyone! `SSD300` is still up for grabs if anyone would like to do it

**Comment by puhuk** [comment]
@NicolasHug Hi I am doing with SSD. Could you wail till today:)

**Comment by NicolasHug** [comment]
Oops sorry @puhuk I missed your comment above! Please take your time, no rush :)

**Comment by NicolasHug** [comment]
Thank you very much for your help everyone !!
