### ISSUE TITLE
HTTP 500 when using torchvision.OxfordIIITPet(download=True)

### ISSUE THREAD

**Issue by SmallSquare** [pytorch/vision#5925]
### 🐛 Describe the bug

Got HTTP 500 when using `torchvision.OxfordIIITPet(download=True)`
It also happened in another Oxford dataset `torchvision.Flowers102`

I tested it on different networks but it does not work now.

```
HTTPError: HTTP Error 500: Internal Server Error
```

Other datasets work fine.

### Versions

PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.4
Libc version: glibc-2.26

Python version: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.11.0+cu113
[pip3] torchaudio==0.11.0+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.12.0
[pip3] torchvision==0.12.0+cu113
[conda] Could not collect

cc @pmeier @YosuaMichael

**Comment by ellisbrown** [comment]
+1

**Comment by pmeier** [comment]
Given that they are all hosted on https://www.robots.ox.ac.uk and you got an `Internal Server Error` it is likely that their server just failed for some time. As of now, everything is operational for me again. @SmallSquare @ellisbrown could you check if the same is true on your end?

**Comment by SmallSquare** [comment]
> Given that they are all hosted on https://www.robots.ox.ac.uk and you got an `Internal Server Error` it is likely that their server just failed for some time. As of now, everything is operational for me again. @SmallSquare @ellisbrown could you check if the same is true on your end?

Thank you for your reply. It works for me now. 😊
