### ISSUE TITLE
A problem related to FFmpeg when building from source.

### ISSUE THREAD

**Issue by ray-twelve** [pytorch/vision#5928]
### 🐛 Describe the bug

Hello
I am trying to build torchvision from source in order to use video_reader with gpus enabled.

I started a fresh instance on ec2 with ubuntu deep learning AMI.

First, I created a conda environment and installed pytorch and etc. with 
conda install pytorch==1.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge

And then I cloned the torchvision from github and checked out to release/0.11 branch to match the versions.

Finally, I tried to install it by python setup.py install but faced some error messages.

ERROR MESSAGES:

/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:21:36: error: use of enum ‘AVLockOp’ without previous declaration
 int ffmpeg_lock(void** mutex, enum AVLockOp op) {
                                    ^~~~~~~~
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp: In function ‘int ffmpeg::{anonymous}::ffmpeg_lock(void**, int)’:
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:24:10: error: ‘AV_LOCK_CREATE’ was not declared in this scope
     case AV_LOCK_CREATE:
          ^~~~~~~~~~~~~~
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:24:10: note: suggested alternative: ‘AV_LOG_TRACE’
     case AV_LOCK_CREATE:
          ^~~~~~~~~~~~~~
          AV_LOG_TRACE
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:27:10: error: ‘AV_LOCK_OBTAIN’ was not declared in this scope
     case AV_LOCK_OBTAIN:
          ^~~~~~~~~~~~~~
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:27:10: note: suggested alternative: ‘CLOCK_TAI’
     case AV_LOCK_OBTAIN:
          ^~~~~~~~~~~~~~
          CLOCK_TAI
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:30:10: error: ‘AV_LOCK_RELEASE’ was not declared in this scope
     case AV_LOCK_RELEASE:
          ^~~~~~~~~~~~~~~
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:30:10: note: suggested alternative: ‘AV_LOG_VERBOSE’
     case AV_LOCK_RELEASE:
          ^~~~~~~~~~~~~~~
          AV_LOG_VERBOSE
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:33:10: error: ‘AV_LOCK_DESTROY’ was not declared in this scope
     case AV_LOCK_DESTROY:
          ^~~~~~~~~~~~~~~
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:33:10: note: suggested alternative: ‘AV_LOG_ERROR’
     case AV_LOCK_DESTROY:
          ^~~~~~~~~~~~~~~
          AV_LOG_ERROR
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp: In lambda function:
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:206:5: error: ‘av_lockmgr_register’ was not declared in this scope
     av_lockmgr_register(&ffmpeg_lock);
     ^~~~~~~~~~~~~~~~~~~
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp: In member function ‘virtual bool ffmpeg::Decoder::init(const ffmpeg::DecoderParameters&, ffmpeg::DecoderInCallback&&, std::vector<ffmpeg::DecoderMetadata>*)’:
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:280:33: error: invalid conversion from ‘const AVInputFormat*’ to ‘AVInputFormat*’ [-fpermissive]
       fmt = av_find_input_format(fmtName);
             ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp: In member function ‘int ffmpeg::Decoder::getFrame(size_t)’:
/home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:509:27: warning: ‘void av_init_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
   av_init_packet(&avPacket);
                           ^
In file included from /home/ubuntu/anaconda3/envs/myenv5/include/libavcodec/avcodec.h:45:0,
                 from /home/ubuntu/vision/torchvision/csrc/io/decoder/defs.h:12,
                 from /home/ubuntu/vision/torchvision/csrc/io/decoder/seekable_buffer.h:3,
                 from /home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.h:5,
                 from /home/ubuntu/vision/torchvision/csrc/io/decoder/decoder.cpp:1:
/home/ubuntu/anaconda3/envs/myenv5/include/libavcodec/packet.h:506:6: note: declared here
 void av_init_packet(AVPacket *pkt);
      ^~~~~~~~~~~~~~
error: command '/usr/bin/gcc' failed with exit code 1





### Versions

Collecting environment information...
PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.22.4
Libc version: glibc-2.27

Python version: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-1072-aws-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] torch==1.10.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] mkl                       2022.0.1           h06a4308_117
[conda] pytorch                   1.10.1          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch

**Comment by pmeier** [comment]
What version of `ffmpeg` are you building against? cc @bjuncek

**Comment by ray-twelve** [comment]
when I type ffmpeg -version it says 9c33b2f. It doesn't seem a valid version. I installed via conda 
(conda install -c conda-forge ffmpeg)

 ffmpeg -version
ffmpeg version 9c33b2f Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 9.3.0 (crosstool-NG 1.24.0.133_b0863d8_dirty)

**Comment by pmeier** [comment]
According to the [feedstock](https://github.com/conda-forge/ffmpeg-feedstock) the current version is `5.0.1`. We only added compatibility for `ffmpeg>5` in #5644, which hasn't made its way into a tagged release yet. To be able to build `torchvision==0.11.0`, you probably need to `conda install -c conda-forge 'ffmpeg<5'`. Could you try and report back?

As a side note, you should `git checkout v0.11.2` if you use `torch==0.10.1` (see our [compatibility table](https://github.com/pytorch/vision#installation)). I'm not aware of any incompatibilities between `torchvision==0.11.0` and `torch==0.10.1`, but better safe than sorry.

**Comment by ray-twelve** [comment]
Thanks,

I have tried conda install -c conda-forge 'ffmpeg<5' and also checked out v0.11.2.

When I tried python setup.py install, It seems okay and the compilation process was successfully done.

At the first try, I faced CUDA version mismatch between torch and torchvision. So I exported CUDA_PATH and CUDA_HOME in order to specify the right version and it seems to be working!

Thank you!
