### ISSUE TITLE
Torchvision import leads to OpenCV imshow freeze

### ISSUE THREAD

**Issue by Flova** [pytorch/vision#5940]
### 🐛 Describe the bug

Showing an image using OpenCV leads to the program getting stuck (100% CPU) without showing the image if torchvision is imported.

```python
import numpy as np
import cv2

import torchvision
cv2.imshow("debug", np.zeros((128,128,3), dtype=np.uint8))   # Frezzes at this line if torchvision is imported
cv2.waitKey(1)
```

Expected result: The image is displayed and the program finishes.

### Versions

PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-37-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 470.103.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] pytorchvideo==0.1.5
[pip3] torch==1.11.0
[pip3] torch-summary==1.4.5
[pip3] torchvision==0.12.0
[conda] Could not collect

**Comment by Flova** [comment]
I don#t know why it is not listed there, but OpenCV is also installed in the venv. I checked the path and the version is not from the system.

Version:
```python
import cv2
cv2.__version__
4.5.5
```

**Comment by Flova** [comment]
Displaying an image before the import leads to them being displayed also after the import.

**Comment by pmeier** [comment]
Thanks for the report. I can't reproduce in a clean `conda` environment. Could you try the following where `main.py` contains the snippet you posted above?

```shell
$ conda create -n tv-5940 -y python=3.8
$ conda activate tv-5940
$ pip install torch torchvision opencv-python
$ python main.py
```

Does the error persist?

**Comment by juhan** [comment]
I did come across the `cv2.imshow` freeze as well, but it seems to be kind of interaction between `torchvision` and `pytorchvideo`. The way to reproduce in Ubuntu 20.04 / Python 3.8:

```bash
$ python3 -m venv testenv
$ . testenv/bin/activate
(testenv) $ pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Requirement already satisfied: torch in ./lib/python3.8/site-packages (1.11.0+cu113)
Requirement already satisfied: torchvision in ./lib/python3.8/site-packages (0.12.0+cu113)
Requirement already satisfied: torchaudio in ./lib/python3.8/site-packages (0.11.0+cu113)
Requirement already satisfied: typing-extensions in ./lib/python3.8/site-packages (from torch) (4.2.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./lib/python3.8/site-packages (from torchvision) (9.1.0)
Requirement already satisfied: numpy in ./lib/python3.8/site-packages (from torchvision) (1.22.3)
Requirement already satisfied: requests in ./lib/python3.8/site-packages (from torchvision) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./lib/python3.8/site-packages (from requests->torchvision) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in ./lib/python3.8/site-packages (from requests->torchvision) (2.0.12)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in ./lib/python3.8/site-packages (from requests->torchvision) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.8/site-packages (from requests->torchvision) (2021.10.8)
(testenv) $ # or the CPU version: pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
(testenv) $ # or the nightly CUDA version: pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cu113

(testenv) $ pip3 install opencv-contrib-python
Requirement already satisfied: opencv-contrib-python in ./lib/python3.8/site-packages (4.5.5.64)
Requirement already satisfied: numpy>=1.14.5; python_version >= "3.7" in ./lib/python3.8/site-packages (from opencv-contrib-python) (1.22.3)
```
In this environment the above script reported by @Flova runs fine. Now when installing pytorchvideo

```bash
(testenv) $ pip install pytorchvideo
Requirement already satisfied: pytorchvideo in ./lib/python3.8/site-packages (0.1.5)
Requirement already satisfied: networkx in ./lib/python3.8/site-packages (from pytorchvideo) (2.8)
Requirement already satisfied: fvcore in ./lib/python3.8/site-packages (from pytorchvideo) (0.1.5.post20220504)
Requirement already satisfied: av in ./lib/python3.8/site-packages (from pytorchvideo) (9.2.0)
Requirement already satisfied: iopath in ./lib/python3.8/site-packages (from pytorchvideo) (0.1.9)
Requirement already satisfied: parameterized in ./lib/python3.8/site-packages (from pytorchvideo) (0.8.1)
Requirement already satisfied: termcolor>=1.1 in ./lib/python3.8/site-packages (from fvcore->pytorchvideo) (1.1.0)
Requirement already satisfied: numpy in ./lib/python3.8/site-packages (from fvcore->pytorchvideo) (1.22.3)
Requirement already satisfied: tqdm in ./lib/python3.8/site-packages (from fvcore->pytorchvideo) (4.64.0)
Requirement already satisfied: tabulate in ./lib/python3.8/site-packages (from fvcore->pytorchvideo) (0.8.9)
Requirement already satisfied: yacs>=0.1.6 in ./lib/python3.8/site-packages (from fvcore->pytorchvideo) (0.1.8)
Requirement already satisfied: Pillow in ./lib/python3.8/site-packages (from fvcore->pytorchvideo) (9.1.0)
Requirement already satisfied: pyyaml>=5.1 in ./lib/python3.8/site-packages (from fvcore->pytorchvideo) (6.0)
Requirement already satisfied: portalocker in ./lib/python3.8/site-packages (from iopath->pytorchvideo) (2.4.0)
```
The same script gets stuck by hogging a single core of the CPU 100% and not even accepting `SIGINT` signals. Note that when commenting out the `import torchvision`, the script works fine. So there is some kind of interference between torchvision and pytorchvideo happening in the background which breaks things.


When uninstalling pytorchvideo, the `cv2.imshow` works again with `import torchvision` present in the script.

Tested it with torch nightly as well. Same behaviour.

**Comment by pmeier** [comment]
Thanks for the extra information @juhan! I can reproduce the error now by also installing `pytorchvideo`:

```shell
$ conda create -n tv-5940 -y python=3.8
$ conda activate tv-5940
$ pip install torch torchvision opencv-python pytorchvideo
$ python main.py
```

**Comment by NicolasHug** [comment]
Can you try to `import torch` before importing torchvision:

```py
import torch
import torchvision
```

?

IIRC `import torch` does some magic symbol resolution which might be needed here?

**Comment by pmeier** [comment]
Can narrow it down to [`PyAV`](https://github.com/PyAV-Org/PyAV):

```shell
$ conda create -n tv-5940 -y python=3.8
$ conda activate tv-5940
$ pip install torchvision opencv-python av
$ python main.py
```

The error goes away for `av<9`. Since [`pytorchvideo` does not require a specific version](https://github.com/facebookresearch/pytorchvideo/blob/9368f308d4a4619a76554cbef15b6b85ca6d0f88/setup.py#L55) you can use this as a quick workaround.

**Comment by pmeier** [comment]
The problem is unrelated to `torchvision`:

```py
# main.py
import numpy as np
import cv2
import av

cv2.imshow("debug", np.zeros((128,128,3), dtype=np.uint8))
cv2.waitKey(1)
```

```shell
$ conda create -n tv-5940 -y python=3.8
$ conda activate tv-5940
$ pip install numpy opencv-python av
$ python main.py
```

The reason you are seeing this is that as a side effect of `import torchvision` also `import av` happens:

https://github.com/pytorch/vision/blob/62740807c18e68bb0acd85895dca527f9a655bd5/torchvision/__init__.py#L6

https://github.com/pytorch/vision/blob/62740807c18e68bb0acd85895dca527f9a655bd5/torchvision/io/__init__.py#L35

https://github.com/pytorch/vision/blob/62740807c18e68bb0acd85895dca527f9a655bd5/torchvision/io/video.py#L17

This should be reported to respective projects. Given that `av<9` does not have this problem, maybe the `ffmpeg` version got upgraded and is now clashing with `cv2`?

**Comment by Flova** [comment]
So you suggest that I should open an issue for the repo of `av` and `pytorchvideo`?

**Comment by pmeier** [comment]
`pytorchvideo` has also nothing to do with this other than pulling in the `av` dependency. As you can see in https://github.com/pytorch/vision/issues/5940#issuecomment-1117546474 you need neither `torchvision` nor `pytorchvideo` to reproduce the behavior. 

I would start by reporting to `av` and probably also to `opencv-python`. My best guess is that this is related to a mismatch of the `ffmpeg` versions that they ship. But this is best answered by someone actually knowing the internals.

**Comment by Flova** [comment]
Okay. I thought, about `pytorchvideo` so they maybe pin the dependency to `av` <9 but `av` itself seems definitely the most important to me.

**Comment by pmeier** [comment]
You can of course also report to them so they can decide for themselves. The don't hard-depend on `opencv-python` and I'm guessing this is why they (presumably) haven't seen this issue. Still, they have it in their dev requirements so it still might be of interest.

**Comment by jlaine** [comment]
I'm not sure this issue is going anywhere, OpenCV and AV both vendor a bunch of libraries, notably FFmpeg and some X11 libraries. I suspect there is a conflict somewhere, and I don't really see how two unrelated projects are going to coordinate.

**Comment by pmeier** [comment]
@jlaine I'm fine with that result. We established that this is not on us and since we don't officially depend or support `cv2` this shouldn't be that common anyway. I just wanted to make sure the "offending" projects are aware of this issue. Whether or not they fix it (or if it is fixable at all) is their decision.

If someone wants both libraries at the same time, they should probably use a `conda` env to avoid clashing binary versions.

**Comment by jlaine** [comment]
Sure, let's at least try to understand which library is clashing, we may be able to work around this with some SONAME mangling.

**Comment by ypy0318** [comment]
> Can narrow it down to [`PyAV`](https://github.com/PyAV-Org/PyAV):
> 
> ```shell
> $ conda create -n tv-5940 -y python=3.8
> $ conda activate tv-5940
> $ pip install torchvision opencv-python av
> $ python main.py
> ```
> 
> The error goes away for `av<9` cc @bjuncek. Since [`pytorchvideo` does not require a specific version](https://github.com/facebookresearch/pytorchvideo/blob/9368f308d4a4619a76554cbef15b6b85ca6d0f88/setup.py#L55) you can use this as a quick workaround.

Thank you very much! Saved my day!

**Comment by rebelzion** [comment]
what a pesky bug, saved my day
