### ISSUE TITLE
typing_extensions is only needed for python < 3.8

### ISSUE THREAD

**Issue by hubutui** [pytorch/vision#5942]
### 🚀 The feature

specify the dep typing_extensions is only needed for python < 3.8

### Motivation, pitch

specify the dep typing_extensions is only needed for python < 3.8

### Additional context

According to https://github.com/pytorch/vision/search?q=typing_extensions, torchvision only uses `typing_extensions.Literal`, which is available since python 3.8, see also [this](https://docs.python.org/3/library/typing.html).
we only need to change [setup.py](https://github.com/pytorch/vision/blob/22400011d6a498ecf77797a56dfe13bc94c426ca/setup.py) and replace `typing_extensions` with something like `typing_extensions; python_version<"3.8"`.

ref issue https://github.com/archlinuxcn/repo/issues/2762

**Comment by pmeier** [comment]
In case the syntax is unknown, this conditional dependency is a [environment marker specified in PEP508](https://peps.python.org/pep-0508/#environment-markers).

**Comment by pmeier** [comment]
Within our code we need to do something like

```py
if sys.version_info >= (3, 8):
    from typing_extensions import Literal
else:
    from typing import Literal
```

**Comment by NicolasHug** [comment]
> Within our code we need to do something like
> 
> ```python
> if sys.version_info >= (3, 8):
>     from typing_extensions import Literal
> else:
>     from typing import Literal
> ```

Any chance we can avoid that? This is going to be a headache.

I'm not sure I completely understand the original issue here. We test torchvision on 3.7-3.10 and we're not hitting any of these related issues.

Also the original post suggests

> typing_extensions is only needed for python < 3.8

But the condition is the other-way around?

> if sys.version_info >= (3, 8):
>     from typing_extensions import Literal

**Comment by NicolasHug** [comment]
> there is also no harm from using them from the backport package. This is why we also don't see issues in CI

Thanks Philip, that's were I'm confused: if there is no harm in using the backport, what is the actual cause of the original issue? Perhaps @hubutui can help me understand :) ?

**Comment by hubutui** [comment]
Hmm, it seems there is no need to fix this issue. I think I could simply update the dep when I create pkg for ArchLinux.

**Comment by bass2549** [comment]
>

**Comment by SvenDS9** [comment]
You dropped support for python 3.7 in the nightly build and removed `typing_extension` as a dependency. So this issue can be closed?
