### ISSUE TITLE
mobilenet_v2 module forward panic when batch is one

### ISSUE THREAD

**Issue by wangqiim** [pytorch/vision#5955]
### 🐛 Describe the bug

mobilenet_v2 module forward panic when batch is one.
`test_panic.py`
```python
import torch
from torchvision.models.mobilenet import mobilenet_v2

net = mobilenet_v2()
x = torch.rand(1, 3, 32, 32)
y = net(x)

```

`backtrace`
```
Traceback (most recent call last):
  File "test_panic.py", line 51, in <module>
    y = net(x)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torchvision/models/mobilenet.py", line 142, in forward
    x = self.features(x)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torchvision/models/mobilenet.py", line 69, in forward
    return self.conv(x)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 81, in forward
    exponential_average_factor, self.eps)
  File "/home/wq/miniconda3/envs/torch/lib/python3.7/site-packages/torch/nn/functional.py", line 1652, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 576, 1, 1])
```

### Versions

Collecting environment information...
PyTorch version: 1.2.0
Is debug build: False
CUDA used to build PyTorch: 10.0.130
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.17

Python version: 3.7.11 (default, Jul 27 2021, 14:32:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-62-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 450.102.04
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: No

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0a0+6b959ee
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.0.130                      0
[conda] mkl                       2021.3.0           h06a4308_520
[conda] mkl-service               2.4.0            py37h7f8727e_0
[conda] mkl_fft                   1.3.0            py37h42c9631_2
[conda] mkl_random                1.2.2            py37h51133e4_0
[conda] numpy                     1.20.3           py37hf144106_0
[conda] numpy-base                1.20.3           py37h74d4b33_0
[conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchvision               0.4.0                py37_cu100    pytorch

cc @datumbox

**Comment by pmeier** [comment]
The error message

> Expected more than 1 value per channel when training, got input size torch.Size([1, 576, 1, 1])

refers to the fact that the model reduced to input image to a single "pixel" and has nothing to do with the batch size. 32 pixels is simply to small to work with `mobilenet_v2`. If you increase the image by a single pixel everything works fine:

```
import torch
from torchvision.models.mobilenet import mobilenet_v2

net = mobilenet_v2()
x = torch.rand(1, 3, 33, 33)
y = net(x)
```

In case you need to work with images that are 32 pixels, I would suggest you use `torchvision.transforms.Pad(1)` in your data pipeline.

**Comment by wangqiim** [comment]
> The error message
> 
> > Expected more than 1 value per channel when training, got input size torch.Size([1, 576, 1, 1])
> 
> refers to the fact that the model reduced to input image to a single "pixel" and has nothing to do with the batch size. 32 pixels is simply to small to work with `mobilenet_v2`. If you increase the image by a single pixel everything works fine:
> 
> ```
> import torch
> from torchvision.models.mobilenet import mobilenet_v2
> 
> net = mobilenet_v2()
> x = torch.rand(1, 3, 33, 33)
> y = net(x)
> ```
> 
> In case you need to work with images that are 32 pixels, I would suggest you use `torchvision.transforms.Pad(1)` in your data pipeline.

Make sense, But if I set batch is two, it work well. I don't think inconsistent results should be produced when changed batch.
```python
import torch
from torchvision.models.mobilenet import mobilenet_v2

net = mobilenet_v2()
x = torch.rand(2, 3, 33, 33) # batch is two
y = net(x)
```

**Comment by pmeier** [comment]
[`nn.BatchNorm2d`](https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm2d.html) computes the normalization across all dimensions except the channel dimension, i.e 0, 2, and 3. If we look at the error message again

> torch.Size([1, 576, 1, 1])

You see that the total number of elements in all three dimensions combined is still 1. Thus, anything that increases the number of elements in any of these dimensions will get rid of the warning. That can happen by either increasing the batch size giving you `(2, 576, 1, 1)` or increasing the input size giving you `(1, 576, >1, >1)`.

That being said, it makes little sense to run a model that includes BatchNorm layers if you want to train without batches.

**Comment by wangqiim** [comment]
> [`nn.BatchNorm2d`](https://pytorch.org/docs/stable/generated/torch.nn.BatchNorm2d.html) computes the normalization across all dimensions except the channel dimension, i.e 0, 2, and 3. If we look at the error message again
> 
> > torch.Size([1, 576, 1, 1])
> 
> You see that the total number of elements in all three dimensions combined is still 1. Thus, anything that increases the number of elements in any of these dimensions will get rid of the warning. That can happen by either increasing the batch size giving you `(2, 576, 1, 1)` or increasing the input size giving you `(1, 576, >1, >1)`.
> 
> That being said, it makes little sense to run a model that includes BatchNorm layers if you want to train without batches.

Make sense!  Thank you!
