### ISSUE TITLE
Document ResNet architecture tweak

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#5964]
Since we're revamping our docs, we might want to point out that our ResNet implementation slightly differs from the original one:

https://github.com/pytorch/vision/blob/970ba3555794d163daca0ab95240d21e3035c304/torchvision/models/resnet.py#L107:L111

We have this as a comment  in the code but it's worth documenting in the docs as well as `.. note::` IMHO

**Comment by datumbox** [comment]
Another good example of a post-paper optimization adopted in the code-base. I agree we should document this clearly on our new documentation. I was thinking that perhaps the best place to put the note is at the [ResNet doc](https://github.com/pytorch/vision/blob/main/docs/source/models/resnet.rst). What do you think @NicolasHug?

**Comment by NicolasHug** [comment]
I agree we should add it to the main resnet page. But because some users might land directly on one of the [builder's page](https://pytorch.org/vision/main/models/generated/torchvision.models.resnet18.html#torchvision.models.resnet18) without going from the main Resnet one, I feel like we should also document this in the docstrings. Either by duplicating the same text, or perhaps by just adding a reference to the `.. note`.

**Comment by datumbox** [comment]
Sounds good to me.

**Comment by puhuk** [comment]
Can I send PR with this? 
If so, should I send another PR for docstring? (`https://pytorch.org/vision/main/models/generated/torchvision.models.resnet18.html#torchvision.models.resnet18`)

**Comment by NicolasHug** [comment]
@puhuk sure, thanks! I think we should be able to tackle all this in a single PR
