### ISSUE TITLE
Revamping our Quantized models docs

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#5987]
We're re-writing our models docs to make them clearer, simpler, and to properly document the [upcoming multi-weight API](https://pytorch.org/blog/introducing-torchvision-new-multi-weight-support-api/). This issue is about **adding docs for the Quantized classification models.**

Our latest new docs are currently [here](https://output.circle-artifacts.com/output/job/8ce072c6-4b16-4aa9-9055-b6f19635d4af/artifacts/0/docs/models_new.html#quantized-models) (this link is likely outdated by the time you look at it, but it doesn't matter; the skeleton is there). We created a separate section that will eventually be merged into the main one. We have documented a few models, but most of them are still missing. The list of models that still need docs is listed below. If you'd like to participate, please comment below with a message saying "I'm working on XYZ" where XYZ is a model, so that others don't pick the same as you do. To keep things simple, please submit one PR per model, but feel free to contribute more than one model.

### How to write docs for a model

Note: below are detailed instructions. This makes it look more complicated than it actually is. Don't be scared!

A great place to start is to look a the changes in [this PR that documents SqueezeNet](https://github.com/pytorch/vision/pull/5832/files). You'll need to do exactly the same for your model:

- Create a new `.rst` file in https://github.com/pytorch/vision/tree/main/docs/source/models. The file should [look like this](https://raw.githubusercontent.com/pytorch/vision/main/docs/source/models/squeezenet.rst), with a link to the original paper, and a list of the corresponding model builders. It should also mention the base model class and link to the `.py` file where it is defined.
- Update the list in https://github.com/pytorch/vision/blame/main/docs/source/models_new.rst to link to this new file (without the `.rst` suffix). Please keep the list alphabetically sorted
- Update the docstring of each new model builder, similarly to [this one](https://github.com/pytorch/vision/blob/64b1e279d7963c923bd453de07589a25cb6e8d03/torchvision/models/quantization/googlenet.py#L144-L172).
    - there is a 1:1 mapping between a model builder and a Weight enum. For example, the docstring of [squeezenet1_0](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/squeezenet.py#L159) makes direct references to [SqueezeNet1_0_Weights](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/squeezenet.py#L128). **For Quantized models there might be more weights for a single model builder, check the link above!**
    - don't forget the [autoclass](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/torchvision/models/squeezenet.py#L181-L182) directive in the docstring. This will auto-generate documentation for the Weight enums. You don't need to understand how this is done, but if you're curious, it's done [here](https://github.com/pytorch/vision/blob/e8cb0bacd86c49e67a7e1a5f83c6da866bc451cf/docs/source/conf.py#L299).

To build the docs locally, please look at our [contributing guide](https://github.com/pytorch/vision/blob/main/CONTRIBUTING.md#documentation). You won't need to worry about the gallery example, **so always use `make html-noplot`** instead of `make html` to save time.

Please don't hesitate to ping us if you need any help / guidance or if you have any question!

----

Quantized models that need docs are:

- [x] Inception - https://github.com/pytorch/vision/pull/6005
- [x] MobileNetV2 - https://github.com/pytorch/vision/pull/6004
- [X] MobileNetV3 - https://github.com/pytorch/vision/pull/6016
- [x] ResNet - https://github.com/pytorch/vision/pull/6012
- [x] ResNeXt - https://github.com/pytorch/vision/pull/6032
- [X] ShuffleNetV2 - https://github.com/pytorch/vision/pull/6028

**Comment by NicolasHug** [comment]
CC @yassineAlouini as you were intersted!

**Comment by datumbox** [comment]
@NicolasHug good call, let's get those final models done and add any remaining info. :)

Since our next release is not too far away and we got lots of work to do still on the documentation, I'll be cheeky and tag some of our good usual suspects in case they can give us a hand and get this done faster: @oke-aditya @lezwon @zhiqwang @abhi-glitchhg @xiaohu2015 @frgfm. Don't feel obliged, just a ping in case you have time.

**Comment by zhiqwang** [comment]
Hi @NicolasHug and @datumbox ,

I would like to take `ShuffleNet v2`.

**Comment by xiaohu2015** [comment]
I can take `ResNet`

**Comment by abhi-glitchhg** [comment]
I can work on `MobileNetV3`.

**Comment by yassineAlouini** [comment]
`Inception` if it is still available. :ok_hand:

**Comment by lezwon** [comment]
I'll take up `MobileNetV2`

**Comment by frgfm** [comment]
Shoot I arrived to late this time 😅
Let me know if one of you cannot do his part in the end!

**Comment by datumbox** [comment]
@frgfm This the open-source version of music chairs: Ping more contributors than tickets and see what happens. 😄 😆 

In all seriousness thanks for responding and no worries. We are very lucky to have you all supporting us like this. We got many more improvements on the pipeline coming up that we could use your help. Thanks for the support!

**Comment by NicolasHug** [comment]
@frgfm actually I forgot Resnext and it' still up for grabs!  Would you like to take it?

**Comment by datumbox** [comment]
@zhiqwang @frgfm We are aiming to finalize the models by mid week to start preparing for the release. Let us know if you need any help with the PRs for ShuffleNetV2 and ResNeXt. If you are busy no worries, just let us know and we will pick it up or finish any incomplete PRs you might got. Thanks!

**Comment by zhiqwang** [comment]
Hi @datumbox , I can work for `ShuffleNetV2` tomorrow .

**Comment by abhi-glitchhg** [comment]
Also  i believe resnext was partially done in #6012 , I can finish the remaining part.

**Comment by frgfm** [comment]
Happy how the musical chairs ended up haha
I'll take ResNext gladly :)

**Comment by datumbox** [comment]
Wow I think we are done! Thanks a lot for the help!

**Comment by NicolasHug** [comment]
<3 Thank you!
