### ISSUE TITLE
Can not download CIFAR10 data because [SSL: CERTIFICATE_VERIFY_FAILED] -SSL certificate has expired

### ISSUE THREAD

**Issue by AIVenture0** [pytorch/vision#6007]
### 🐛 Describe the bug

2022/5/12 around 10 pm.

I am trying to download the __CIFAR10__ using torch vision. __Certificate expired__.

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,download=True, transform=transform)

The Error Raise: :disappointed:

'''
raise URLError(err)                                                                
urllib.error.URLError: <urlopen error __[SSL: CERTIFICATE_VERIFY_FAILED]__ :pout: certificate verif certificate verify failed: certificate has expired (_ssl.c:997).
'''

### Versions

PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: GeForce RTX 2060
Nvidia driver version: 456.81
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.22.1
[pip3] torch==1.11.0+cu113
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect

cc @pmeier @YosuaMichael

**Comment by pmeier** [comment]
Sounds like a server error. I just tested https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz and works fine. Could you retry to see if they already fixed it?

**Comment by AIVenture0** [comment]
My Code to fetch the data 

"""
# Download and load the MNIST training data
trainset = datasets.MNIST("MNIST_data/",download = True,
                            train = True,transform=transform)

trainset = datasets.CIFAR100("cifar_data",download=True,
                            train= True,transform = transform)

""

Worked with MNIST but not with  __CIFAR10__ and __CIFAR100__. Previously I have done this multiple time, it worked.  Now since last 2 days it didn't.

**Comment by AIVenture0** [comment]
### Issue Got resolved :  turning off SSL verification

Code

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

Found the Similar issue #5039
