### ISSUE TITLE
Question about center-ness branch in FCOS

### ISSUE THREAD

**Issue by WZMIAOMIAO** [pytorch/vision#6034]
Hi, thank you for your great work. I'm learning FCOS these days. I find some differences about position of center-ness between code and paper. In paper(https://arxiv.org/abs/1904.01355), the center-ness branch is put together with the classification branch. 
![image](https://user-images.githubusercontent.com/31005897/168759441-07ea8b54-3fe8-43aa-bd0e-8c05067b1547.png)

But in the code, the center-ness and regression branches are put together.
https://github.com/pytorch/vision/blob/a1232c212d7cf84806189910ba83bc36bcea916c/torchvision/models/detection/fcos.py#L202-L233

Could you tell me why? thanks.

**Comment by datumbox** [comment]
@zhiqwang @xiaohu2015 @jdsgomes Could you give a reply on this since you know the technique inside-out?

**Comment by xiaohu2015** [comment]
@WZMIAOMIAO Hi, you can read the updated paper (https://arxiv.org/pdf/2006.09214.pdf). The center-ness branch added on regression branch can get better result.

**Comment by WZMIAOMIAO** [comment]
> @WZMIAOMIAO Hi, you can read the updated paper (https://arxiv.org/pdf/2006.09214.pdf, page6 note). The center-ness branch added on regression branch can get better result.
> 
> ```
> This is different from our conference version which positions the
> center-ness on the classification branch, but it has been shown that
> positioning it on the regression branch can obtain better performance.
> ```

Wow, that is great, Thank you.

![image](https://user-images.githubusercontent.com/31005897/168766887-1409082a-fa46-4861-bb07-a7c3d8b4f5bc.png)

**Comment by WZMIAOMIAO** [comment]
It is suggested to update the paper link in the description document.
https://github.com/pytorch/vision/blob/a1232c212d7cf84806189910ba83bc36bcea916c/torchvision/models/detection/fcos.py#L682

**Comment by datumbox** [comment]
Yes that might be a good idea, thanks for flagging. We should probably highlight both papers. You want to bring a PR?

**Comment by WZMIAOMIAO** [comment]
This is my honor.

**Comment by datumbox** [comment]
@WZMIAOMIAO No, definitely ours for helping us improve the documentation.

Reopening the ticket until the PR lands. Feel free to tag me on the PR for reviews. Thanks a lot for the help!
