### ISSUE TITLE
`unittest_*_py3.10` job failing due to numpy issues

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#6045]
### 🐛 Describe the bug

TorchVision's `unittest_linux_cpu_py3.10` started [failing](https://app.circleci.com/pipelines/github/pytorch/vision/17706/workflows/0f05c7e0-988b-4ddb-af32-608cb4da03a2/jobs/1434070/steps) with numpy issues:
```
___________________ ERROR collecting test/test_cpp_models.py ___________________
Traceback (most recent call last):
  File "/root/project/test/test_cpp_models.py", line 55, in <module>
    class Tester(unittest.TestCase):
  File "/root/project/test/test_cpp_models.py", line 56, in Tester
    image = read_image1()
  File "/root/project/test/test_cpp_models.py", line 33, in read_image1
    x = F.pil_to_tensor(image)
  File "/root/project/torchvision/transforms/functional.py", line 205, in pil_to_tensor
    img = torch.as_tensor(np.array(pic, copy=True))
RuntimeError: Could not infer dtype of numpy.uint8
___________________ ERROR collecting test/test_transforms.py ___________________
Traceback (most recent call last):
  File "/root/project/test/test_transforms.py", line 596, in <module>
    class TestToPil:
  File "/root/project/test/test_transforms.py", line 654, in TestToPil
    (torch.Tensor(4, 4, 1).uniform_().numpy(), "F"),
RuntimeError: Numpy is not available
=============================== warnings summary ===============================
torchvision/models/detection/anchor_utils.py:63
  /root/project/torchvision/models/detection/anchor_utils.py:63: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xe (Triggered internally at  /opt/conda/conda-bld/pytorch_1652857844824/work/torch/csrc/utils/tensor_numpy.cpp:68.)
    device: torch.device = torch.device("cpu"),
```

Edit: Originally it seemed that only linux CPU was failing but later as more nightlies become available other py3.10 jobs failed such as [unittest_linux_gpu_py3.10](https://app.circleci.com/pipelines/github/pytorch/vision/17719/workflows/584585e0-0141-48f8-8e36-76e6b9eb6cba/jobs/1434870/steps) and [unittest_macos_cpu_py3.10](https://app.circleci.com/pipelines/github/pytorch/vision/17719/workflows/584585e0-0141-48f8-8e36-76e6b9eb6cba/jobs/1434833/steps).

### Versions

Started on nightly 20220518

cc @seemethere

**Comment by atalman** [comment]
This could be related to this PR https://github.com/pytorch/pytorch/pull/77476 changes introduced during May 17 nightly
https://github.com/pytorch/pytorch/commit/bd39de2c81914193d2248dc6c756dda46934b6ec

**Comment by atalman** [comment]
This issue should be fixed by: https://github.com/pytorch/builder/pull/1036 will confirm that this is resolved before closing

**Comment by atalman** [comment]
Closing this test succeded:
https://app.circleci.com/pipelines/github/pytorch/vision/17720/workflows/f765b0a2-0a0d-40a4-a1ac-cf46c9c6bed0/jobs/1437092
