### ISSUE TITLE
Difference from KaimingHe's  bottleneck implementation

### ISSUE THREAD

**Issue by zhydong** [pytorch/vision#606]
I found the `strike` parameter of a `Bottleneck` was on the conv1 layer in KaimingHe's version of ResNet. Here is the `Bottleneck` that is implemented on `pytorch/vision`.
```
class Bottleneck(nn.Module):
    expansion = 4
    def __init__(self, inplanes, planes, stride=1, downsample=None):
        super(Bottleneck, self).__init__()
        self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=1, bias=False)
#should be:
        #self.conv1 = nn.Conv2d(inplanes, planes, kernel_size=1, stride=stride, bias=False)
        self.bn1 = nn.BatchNorm2d(planes)
        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=stride,
                               padding=1, bias=False)
#should be:
       # self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=1,
                         padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(planes)
        self.conv3 = nn.Conv2d(planes, planes * self.expansion, kernel_size=1, bias=False)
        self.bn3 = nn.BatchNorm2d(planes * self.expansion)
        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample
```
Codes below is from [KaimingHe's ResNet github](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-50-deploy.prototxt)
```
layer {
	bottom: "res2c"
	top: "res3a_branch2a"
	name: "res3a_branch2a"
	type: "Convolution"
	convolution_param {
		num_output: 128
		kernel_size: 1
		pad: 0
		stride: 2
		bias_term: false
	}
}
```
In ResNet paper, the author said:

> (B) The projection shortcut in Eqn.(2) is used to match dimensions (done by 1×1 convolutions)

Therefore, the first `1×1` conv layer in a bottleneck should be responsible for increasing dimension, and the `3×3` conv layer, whose stride should always be one, is used to extract features of input as much as possible.

So I think the `pytorch/vision` version of ResNet is wrong.

**Comment by vfdev-5** [comment]
Maybe related to #191

**Comment by fmassa** [comment]
This is indeed the same as #191, so I'm closing this in favor of the other issue.
