### ISSUE TITLE
ONNX CI worflow is broken

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#6069]
Failure is visible since this morning: https://app.circleci.com/pipelines/github/pytorch/vision/17824/workflows/63ed118f-e479-47e5-91c1-2f0805ce2e5a/jobs/1443424

```
RuntimeError: Unsupported: ONNX export of operator prim::device, output type is not `_C.DeviceObjType`.. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

The last commit before the weekend b969cca783cfe6c1009b7bf60609e28d83c973a6 did not have this failure. Thus, I'm guessing we only have look for the nightlies of the 21th and 22th for possible offenders.

cc @neginraoof @seemethere

**Comment by pmeier** [comment]
The offender should be between pytorch/pytorch@d1bb420fb1087d680b7ad526536e14acbc2f18bf and pytorch/pytorch@fbc417b67d9fd51354512643d9f335bd inclusive. 

The only PR that references ONNX is pytorch/pytorch#77423, but that seems unrelated.

**Comment by pmeier** [comment]
I bisected and it turns out pytorch/pytorch#77423 is the culprit after all @justinchuby @BowenBao

**Comment by pmeier** [comment]
pytorch/pytorch@0d76299ff782224810b997d99f8af490cd96eede made it into the [branch cut](https://github.com/pytorch/pytorch/tree/v1.12.0-rc1) and thus we need to resolve before the release.

**Comment by justinchuby** [comment]
Updated:

- https://github.com/pytorch/pytorch/pull/78085

**Comment by justinchuby** [comment]
> I bisected and it turns out [pytorch/pytorch#77423](https://github.com/pytorch/pytorch/pull/77423) is the culprit after all @justinchuby @BowenBao

pytorch/pytorch#77423 was reverted and relanded as pytorch/pytorch#77448. Just for reference

**Comment by pmeier** [comment]
Fix worked! https://app.circleci.com/pipelines/github/pytorch/vision/17866/workflows/49b2a6cf-c54e-4c21-8a0d-a477e70c884f/jobs/1446667

Thanks @justinchuby!
