### ISSUE TITLE
getting Hash Error while dowloading resent model 

### ISSUE THREAD

**Issue by arpitvw** [pytorch/vision#607]
code--> model_ft = models.resnet50(pretrained=True)
error  message --> RuntimeError: invalid hash value (expected "19c8e357", got "0c160fe3aca6a7808c727f78cbb125a2162611023bbde7d9c8df33e2ec23c8ed")

 ######################### Full error : ########################################

Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to C:\Users\arpit14276/.torch\models\resnet50-19c8e357.pth
98.5%

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-49c0f08393a8> in <module>()
----> 1 model_ft = models.resnet50(pretrained=True)
      2 num_ftrs = model_ft.fc.in_features
      3 model_ft.fc = nn.Linear(num_ftrs, 2)
      4 
      5 model_ft = model_ft.to(device)

C:\ProgramData\Anaconda3\lib\site-packages\torchvision\models\resnet.py in resnet50(pretrained, **kwargs)
    186     model = ResNet(Bottleneck, [3, 4, 6, 3], **kwargs)
    187     if pretrained:
--> 188         model.load_state_dict(model_zoo.load_url(model_urls['resnet50']))
    189     return model
    190 

C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\model_zoo.py in load_url(url, model_dir, map_location)
     62         sys.stderr.write('Downloading: "{}" to {}\n'.format(url, cached_file))
     63         hash_prefix = HASH_REGEX.search(filename).group(1)
---> 64         _download_url_to_file(url, cached_file, hash_prefix)
     65     return torch.load(cached_file, map_location=map_location)
     66 

C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\model_zoo.py in _download_url_to_file(url, dst, hash_prefix)
     94         if digest[:len(hash_prefix)] != hash_prefix:
     95             raise RuntimeError('invalid hash value (expected "{}", got "{}")'
---> 96                                .format(hash_prefix, digest))
     97         shutil.move(f.name, dst)
     98     finally:

RuntimeError: invalid hash value (expected "19c8e357", got "0c160fe3aca6a7808c727f78cbb125a2162611023bbde7d9c8df33e2ec23c8ed")

**Comment by fmassa** [comment]
I have just run the exact same command as you, but everything worked fine.
I suspect that your download failed in the middle.
Can you try deleting the downloaded file (which should be in `~/.torch/models`) and try again?

**Comment by parrykhai** [comment]
yeah, I got the same error, but when I ran the command again it worked...

**Comment by fmassa** [comment]
This error is probably due to a corrupted download, deleting the old file and running the code again should fix it.

As there has been no more activity for more than 1 year, I'm closing this issue.
