### ISSUE TITLE
Error with training Faster R-CNN with new torchvision=0.12

### ISSUE THREAD

**Issue by pengwenyu** [pytorch/vision#6119]
### 🐛 Describe the bug

Hi, I am using faster r-cnn to train our own COCO datasets. However, when I pass the arguments to the train.py, it shows me the error. I checked the source code of faster rcnn and there is no weights argument. Could you please help me fix this issue?
Creating data loaders
Using [0, 0.5, 0.6299605249474366, 0.7937005259840997, 1.0, 1.2599210498948732, 1.5874010519681994, 2.0, inf] as bins for aspect ratio quantization
Count of instances per bin: [5952]
Creating model
Traceback (most recent call last):
  File "train.py", line 288, in <module>
    main(args)
  File "train.py", line 200, in main
    weights=args.weights, weights_backbone=args.weights_backbone, num_classes=num_classes, **kwargs
  File "/home/liulab/anaconda3/envs/py37/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 396, in fasterrcnn_resnet50_fpn
    model = FasterRCNN(backbone, num_classes, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'weights'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 21833) of binary

### Versions

PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.2 LTS (x86_64)
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.7.13 (default, Mar 29 2022, 02:18:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-142-generic-x86_64-with-debian-stretch-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1660 Ti
Nvidia driver version: 460.27.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py37h7f8727e_0  
[conda] mkl_fft                   1.3.1            py37hd3c417c_0  
[conda] mkl_random                1.2.2            py37h51133e4_0  
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] numpy-base                1.21.5           py37hf524024_2  
[conda] pytorch                   1.11.0          py3.7_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.11.0               py37_cu113    pytorch
[conda] torchvision               0.12.0               py37_cu113    pytorch

**Comment by oke-aditya** [comment]
Hi @pengwenyu  
The reference scripts are tested on latest main branch. The feature to use weights is available in nightlies and is under prototype and not released into stable yet.

To train models from reference scripts, please use nightlies or build torchvision from source.

**Comment by NicolasHug** [comment]
Alternatively you can:

- use the training references of the previous version - but that might not give you the latest improvements
- wait a few days for the upcoming 0.13 version of torchvision  :)

I think @oke-aditya properly explained the reason for the error, so I'll close the issue. Feel free to re-open if you have further questions

**Comment by pengwenyu** [comment]
> Hi @pengwenyu The reference scripts are tested on latest main branch. The feature to use weights is available in nightlies and is under prototype and not released into stable yet.
> 
> To train models from reference scripts, please use nightlies or build torchvision from source.

I am using the new nightly version but still fail. This is my new version:
1.13.0.dev20220608+cu113
And the error message is the same:

model = FasterRCNN(backbone, num_classes, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'weights'
