### ISSUE TITLE
How to timing 'model.to(device)' correctly?

### ISSUE THREAD

**Issue by husterdjx** [pytorch/vision#6124]
I am using pytorch's api in my python code to measure time for different layers of resnet152 to device(GPU, V-100).However, I cannot get a stable result.
Here is my code:
```python
import torch.nn as nn
device = torch.device('cuda:3' if torch.cuda.is_available() else 'cpu')
model = torchvision.models.resnet152(pretrained=True)

def todevice(_model_, _device_=device):
    T0 = time.perf_counter()
    _model_.to(_device_)
    torch.cuda.synchronize()
    T1 = time.perf_counter()
    print("model to device %s cost:%s ms" % (_device_, ((T1 - T0) * 1000)))

model1 = nn.Sequential(*list(resnet152.children())[:6])
todevice(model1)
```
When I use the code to test at different time, I can always get different answers, some of them are ridiculous, even to `200ms`.
Also, there are 4 GPU(Tesla V100) in my lab, I don't know whether other extra GPUs will affect my result.
Could you tell me how to timing `model.to(device)` correctly? Is there anything wrong with my code or my lab environment?

**Comment by vfdev-5** [comment]
@husterdjx please check https://pytorch.org/tutorials/recipes/recipes/benchmark.html 
If you want to get stable times, you may need to run measures multiple times. Another point, the first time you call any cuda op, it will create a context and allocate some memory on GPU, you may want to remove this time from measurements...

**Comment by NicolasHug** [comment]
Hi @husterdjx ,
For  user questions that are not directly related to torchvision, please prefer this channel: https://discuss.pytorch.org/

Other than that your benchmark looks reasonable to me, like @vfdev-5 you might want to compute averages over multiple executions
