### ISSUE TITLE
CI is toasted

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#6138]
From [bf1914c](https://github.com/pytorch/vision/pull/5009/commits/bf1914c61622cd6f0aa9ec7f38552f350507ec53) on main branch:

```
$SRC_DIR/torchvision/csrc/ops/quantized/cpu/qnms_kernel.cpp:2:10: fatal error: ATen/native/quantized/affine_quantizer.h: No such file or directory
    2 | #include <ATen/native/quantized/affine_quantizer.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Because torch core renamed `affine_quantizer.h` into `AffineQuantizer.h`.

This will eventually be fixed by https://github.com/pytorch/vision/pull/6133. The irony is that some jobs are relying on the nightly from today while some other jobs are still relying on nightlies from yesterday where the changes from core haven't propagated. So these jobs are red on https://github.com/pytorch/vision/pull/6133.

I guess we'll have to wait till tomorrow to merge https://github.com/pytorch/vision/pull/6133  and get our green CI back.

cc @seemethere

**Comment by malfet** [comment]
We can add a script to create a symlink from one to another, if header is not available (Or `#include` one from another), but this is bad. Wonder if change on core were marked as BC breaking?

**Comment by seemethere** [comment]
Doesn't appear so, https://github.com/pytorch/pytorch/pull/77037

**Comment by malfet** [comment]
To copy-paste a comment from https://github.com/pytorch/vision/pull/6133 : jobs that are broken depend on torchdata, which nightly build failed yesterday, so it forces torch nightly installation prior to that change.

**Comment by dzdang** [comment]
@malfet Sorry, just saw this. yeah, I think in retrospect, I should've marked the PR as bc-breaking. sorry about that (wasn't aware of existent projects that depended on the header file that wasn't part of the pytorch and fbcode codebase). do we need to revert the PR, or proceed with the solution above?

**Comment by malfet** [comment]
Also, looks like M1 CI is somehow affected by this as well:
```
2022-06-08T19:28:17.4266160Z /Users/ec2-user/runner/_work/vision/vision/torchvision/csrc/ops/quantized/cpu/qnms_kernel.cpp:2:10: fatal error: 'ATen/native/quantized/AffineQuantizer.h' file not found
2022-06-08T19:28:17.4267120Z #include <ATen/native/quantized/AffineQuantizer.h>
2022-06-08T19:28:17.4267400Z          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-06-08T19:28:17.4267580Z 1 error generated.
```

**Comment by malfet** [comment]
> @malfet Sorry, just saw this. yeah, I think in retrospect, I should've marked the PR as bc-breaking. sorry about that (wasn't aware of existent projects that depended on the header file that wasn't part of the pytorch and fbcode codebase). do we need to revert the PR, or proceed with the solution above?

@dzdang I guess it's a question of whether we have any public facing tutorials/docs talking about AffineQuantizer, etc

**Comment by dzdang** [comment]
@malfet  We don't. I took a look at `qnms_kernel.cpp`, and I don't think I saw any dependencies in it that would require #include that header file. maybe we can just remove the #include?

**Comment by vfdev-5** [comment]
> maybe we can just remove the #include?

Removed the include and can confirm that torchvision compiles and test_ops.py::test_qnms are passing.

**Comment by NicolasHug** [comment]
https://github.com/pytorch/vision/pull/6141 merged, closing. Thanks everyone.
