### ISSUE TITLE
Unable to build CUDA version in a docker environment without nvidia GPU

### ISSUE THREAD

**Issue by yaadhavraajagility** [pytorch/vision#6160]
### 🐛 Describe the bug

I am currently trying to build torchvision with CUDA on a docker container without nvidia drivers running, but the cuda runtime installed.

However, when i try to run the setup script via:
```
BUILD_TORCH=ON \
       CMAKE_SHARED_LINKER_FLAGS="-L/usr/local/cuda-11.7/lib64 -lcusolver -lcusparse" \
       CMAKE_EXE_LINKER_FLAGS="-L/usr/local/cuda-11.7/lib64 -lcusolver -lcusparse" \
       PYTHON_EXECUTABLE=/usr/local/bin/python \
       CUDA_HOME=/usr/local/cuda-11.7 \
       CMAKE_CUDA_COMPILER=/usr/local/cuda-11.7/bin/nvcc \
       CMAKE_CUDA_RUNTIME_LIBRARY=Static \
       USE_CUDA=1 \
       USE_CUDNN=1 \
       CMAKE_BUILD_TYPE=Release \
       EXTRA_CAFFE2_CMAKE_FLAGS="(-DATEN_NO_TEST=ON)" \
       TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
       TORCH_CUDA_ARCH_LIST="7.5 8.6+PTX" \
       FORCE_CUDA=1 \
       python3 setup.py bdist_wheel
```

I get the warning that no CUDA runtime is found `No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'`

Is the only way to build torchvision inside a docker container to have an  active GPU with nvidia drivers installed? That seems problematic

### Versions

PyTorch version: 1.11.0a0
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (GCC) 11.2.0
Clang version: Could not collect
CMake version: version 3.22.0
Libc version: glibc-2.27

Python version: 3.10.4 (main, Jan  1 2000, 08:00:00) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-117-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.11.0a0+gitunknown
[pip3] torchvision==0.12.0a0
[conda] Could not collect

**Comment by NicolasHug** [comment]
The error is raised here in torch core:

https://github.com/pytorch/pytorch/blob/44764f131b040a41a6dcf1304bb635c574bf5a3b/torch/utils/cpp_extension.py#L106-L107

Given 

>  [pip3] torch==1.11.0a0+gitunknown

>  Is CUDA available: False

I would assume that your installation of pytorch core doesn't support CUDA, and thus this is probably not related to torchvision directly.

**Comment by snowMan108** [comment]
Did you check cuda version corresponding with pytorch?
