### ISSUE TITLE
Mask R-CNN Patent Use

### ISSUE THREAD

**Issue by jpsimen** [pytorch/vision#6225]
Hello,

Can you confirm that the Mask R-CNN implementation in Torchvision was authorized by Facebook? Maybe @fmassa? This would give us at ZEISS and possibly many other users of your code some peace of mind.

I'm asking because the Mask R-CNN model is patented by Facebook Inc., but Facebook/Meta is not officially mentioned as contributor or copyright owner in the pytorch/vision repository. 

Thank you in advance.
Jan

**Comment by datumbox** [comment]
@jpsimen This repo (PyTorch/TorchVision) is indeed maintained by Meta/Facebook and the code is released under the permissive MIT license. Does this address your concern?

**Comment by HolgerStreidl** [comment]
Thanks @datumbox for your feedback. The thing is:

- Meta/Facebook seems to own a patent for the Mask R-CNN model
- PyTorch/TorchVision includes an implementation of the Mask R-CNN model
- PyTorch/TorchVision is licensed under the [BSD-3-Clause](https://github.com/pytorch/vision/blob/main/LICENSE) which does not include an explicit patent grant though one may interpret its wording as to be an implicit license grant.

How can users of PyTorch/TorchVision be sure that Meta/Facebook might not ask one day for a patent licensing fee for the Mask R-CNN model?

Thanks a lot for your help in clarifying this.
