### ISSUE TITLE
n classes in ConvNeXt model 

### ISSUE THREAD

**Issue by jrsykes** [pytorch/vision#6239]
### 🐛 Describe the bug

HI,

I'm trying to train a ConvNeXt tiny model as a binary classifier by loading the model architecture and pretrained weights from torchvision.models.

I use the following two lines of code to load the model and change the number of output nodes:

>num_classes=2
model_ft = models.convnext_tiny(weights=ConvNeXt_Tiny_Weights.DEFAULT)
model_ft.classifier[2].out_features = num_classes

And when I print this layer of the mode I get:

>print(model_ft.classifier[2])

>Linear(in_features=768, out_features=2, bias=True)

This suggests that the change had been made. However, when I train the model, the output has dimensions of 42 x 1,000. _i.e. batch_size_ x n classes in ImageNet:

>batch_size=42
outputs = model(inputs)
print(outputs.size())

>torch.Size([42, 1000])

Any thoughts on how solve this problem?

Cheers,
Jamie

p.s. it seems like the issue might be that the number of classes is hard coded as 1000 in:
pytorch/vision/tree/main/torchvision/models/convnext.py
Lines 90:100

>class ConvNeXt(nn.Module):
def init(
self,
block_setting: List[CNBlockConfig],
stochastic_depth_prob: float = 0.0,
layer_scale: float = 1e-6,
num_classes: int = 1000,
block: Optional[Callable[..., nn.Module]] = None,
norm_layer: Optional[Callable[..., nn.Module]] = None,
**kwargs: Any,
) -> None:

### Versions

Pytorch version: 1.13.0.dev20220624
Python 3.8

**Comment by datumbox** [comment]
@jrsykes Thanks for the question.

I'm afraid you are trying to modify the wrong parameter:
```
model_ft.classifier[2].out_features = num_classes
```

This doesn't change the number of classes, just the informational attribute in the node. The recommended way to do this would be to replace the `model_ft.classifier[2]` layer with a new Linear layer that matches your number of classes.

I'm going to close the issue as I believe I've answered your question. If I didn't feel free to reopen.
