### ISSUE TITLE
Probable missing argument for swin transformer

### ISSUE THREAD

**Issue by artest08** [pytorch/vision#6247]
Hello, 

When I inspect the swin transformer codes in the original swin repo, mmdetection or detectron2, I have noticed that there is a parameter called `drop_path_rate` which I cannot see in the in the torchvision repo. Maybe, I am overlooking. Is there a similar parameter and is it an important parameter? 

Thanks in advance

cc @datumbox

**Comment by datumbox** [comment]
@artest08 Thanks for the question. We support the `stochastic_depth_prob` which is exactly the parameter you are looking for. 

I'll close the issue because I believe I answered the question. If you have more or face issues please feel free to reopen it.
