### ISSUE TITLE
bug: Random Erasing transform get_params return (y, x, h, w, v)

### ISSUE THREAD

**Issue by EijiNAKATSUGAWA** [pytorch/vision#6267]
### 🐛 Describe the bug

Just typo of `RandomErasing` transform function `get_params` return in forward https://github.com/pytorch/vision/blob/main/torchvision/transforms/transforms.py#L1732-L1760. `x` and `y` are opposite as shown below:

```
    def forward(self, img):
        """
        Args:
            img (Tensor): Tensor image to be erased.
        Returns:
            img (Tensor): Erased Tensor image.
        """
        if torch.rand(1) < self.p:

            # cast self.value to script acceptable type
            if isinstance(self.value, (int, float)):
                value = [self.value]
            elif isinstance(self.value, str):
                value = None
            elif isinstance(self.value, tuple):
                value = list(self.value)
            else:
                value = self.value

            if value is not None and not (len(value) in (1, img.shape[-3])):
                raise ValueError(
                    "If value is a sequence, it should have either a single value or "
                    f"{img.shape[-3]} (number of input channels)"
                )

            y, x, h, w, v = self.get_params(img, scale=self.scale, ratio=self.ratio, value=value)
            return F.erase(img, y, x, h, w, v, self.inplace)
        return img
```

### Versions

https://github.com/pytorch/vision/releases/tag/v0.13.0

**Comment by NicolasHug** [comment]
@EijiNAKATSUGAWA I'm not sure I understand the issue.

Are you concerned mostly about the naming of these variables? In torchvision (x, i) denote vertical coordinates while (y, j) denote horizontal coordinates.

**Comment by EijiNAKATSUGAWA** [comment]
@NicolasHug thanks for the reply and terribly sorry that I didn’t know the definition of `x` and `y` stands for. I thought `x` was horizontal, and `y` was vertical coordinates. 

Really sorry for my misunderstanding, and let me close this issue. Thank you so much!!
