### ISSUE TITLE
distance_box_iou() and complete_box_iou() don't work if both sets don't have the same number of boxes

### ISSUE THREAD

**Issue by senarvi** [pytorch/vision#6317]
### 🐛 Describe the bug

`*box_iou()` functions should return a matrix of results for every possible pair (box1, box2), where box1 is a box from `boxes1` and box2 is a box from `boxes2`. `box_iou()` and `generalized_box_iou()` work this way, i.e. if `boxes1` is an Nx4 matrix and `boxes2` is an Mx4 matrix, the result is an NxM matrix. The recently added `distance_box_iou()` and `complete_box_iou()` don't work if there aren't as many boxes in `boxes1` and `boxes2`.

```python
import torch
from torchvision.ops import box_iou, generalized_box_iou, distance_box_iou, complete_box_iou

N = 5
M = 6
boxes1 = torch.rand((N, 4))
boxes2 = torch.rand((M, 4))
print(box_iou(boxes1, boxes2).shape)  # torch.Size([5, 6])
print(generalized_box_iou(boxes1, boxes2).shape)  # torch.Size([5, 6])
print(distance_box_iou(boxes1, boxes2).shape)  # RuntimeError
print(complete_box_iou(boxes1, boxes2).shape)  # RuntimeError
```

When running the above code, `distance_box_iou()` and `complete_box_iou()` will fail with a `RuntimeError`. The output is below:

```
torch.Size([5, 6])
torch.Size([5, 6])
Traceback (most recent call last):
  File ".../test.py", line 10, in <module>
    print(distance_box_iou(boxes1, boxes2).shape)  # RuntimeError
  File ".../lib/python3.9/site-packages/torchvision/ops/boxes.py", line 361, in distance_box_iou
    diou, _ = _box_diou_iou(boxes1, boxes2)
  File ".../lib/python3.9/site-packages/torchvision/ops/boxes.py", line 378, in _box_diou_iou
    centers_distance_squared = (_upcast(x_p - x_g) ** 2) + (_upcast(y_p - y_g) ** 2)
RuntimeError: The size of tensor a (5) must match the size of tensor b (6) at non-singleton dimension 0
```

This is not caught by the unit tests, because there's no such case where there's a different number of boxes in the two sets.

The problem is in [`_box_diou_iou()`](https://github.com/pytorch/vision/blob/main/torchvision/ops/boxes.py#L378). It looks like `iou` and `diagonal_distance_squared` are calculated for every possible pair (by adding an empty dimension), but `centers_distance_squared` is not.

_As a side note, I personally feel it's confusing that these functions produce the output for every possible pair. By convention, PyTorch functions produce element-wise results. For example, `torch.add(boxes1, boxes2)` only works if `boxes1` and `boxes2` contain the same number of boxes. If you want a pair-wise addition, you can easily call `torch.add(boxes1[:, None, :], boxes2)`. The fact that `*box_iou()` functions produce pair-wise results makes the implementation complicated. And the only way to get element-wise results is calling `box_iou(boxes1, boxes2).diagonal()`, which is inefficient._

### Versions

PyTorch version: 1.12.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1650 Ti with Max-Q Design
Nvidia driver version: 516.59
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] pytorch-lightning==1.6.5
[pip3] pytorch-lightning-bolts==0.2.5
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.12.0+cu113
[pip3] torchmetrics==0.6.0
[pip3] torchtext==0.12.0
[pip3] torchvision==0.13.0+cu113
[conda] Could not collect

**Comment by senarvi** [comment]
I would think that the fix is:

```python
centers_distance_squared = (_upcast(x_p[:, None] - x_g) ** 2) + (_upcast(y_p[:, None] - y_g) ** 2)
```

**Comment by senarvi** [comment]
There's also another point in [`complete_box_iou()`](https://github.com/pytorch/vision/blob/main/torchvision/ops/boxes.py#L334) with a similar bug. I think it can be fixed like this:

```python
aspect_gt = torch.atan(w_gt / h_gt)
aspect_pred = torch.atan(w_pred / h_pred)
v = (4 / (torch.pi**2)) * torch.pow((aspect_gt - aspect_pred[:, None]), 2)
```

**Comment by oke-aditya** [comment]
Hi @senarvi nice to see you here.
Hmm agreed, it might have been overlooked with implementing and testing. cc @datumbox should we fix this up? I can go ahead with it.

> As a side note, I personally feel it's confusing that these functions produce the output for every possible pair. By convention, PyTorch functions produce element-wise results. For example, torch.add(boxes1, boxes2) only works if boxes1 and boxes2 contain the same number of boxes. If you want a pair-wise addition, you can easily call torch.add(boxes1[:, None, :], boxes2). The fact that *box_iou() functions produce pair-wise results makes the implementation complicated. 

The reason why these are implemented to work as is because most detection operators need to calculate for all set of boxes. And  this is what other repos used (E.g. DETR, etc)

> And the only way to get element-wise results is calling box_iou(boxes1, boxes2).diagonal(), which is inefficient.

The case where we need only the diagonal elements is for calculation of losses. (Are you trying to do loss = 1 - box_iou.diagonal()). We do have an optimized version for calculating the loss. See
https://github.com/pytorch/vision/blob/main/torchvision/ops/_utils.py#L87

**Comment by abhi-glitchhg** [comment]
Thanks for reporting this. 
You are correct.

As you mentioned, the implementation was not tested on Boxes of different shapes. [there was some discussion on adding tests ] https://github.com/pytorch/vision/pull/5786#discussion_r858670266 


I think my implementation of CIOU was incorrect.  We checked implementation with boxes of size (1,4)  only https://github.com/pytorch/vision/pull/5776#pullrequestreview-956086666 and missed other cases. After your report, I again went through the code and checked for other cases, and the implementation seems incorrect. 
 
 ```python
 import torch
from torch import Tensor

from torchvision.ops import complete_box_iou_loss, complete_box_iou

N = 3
M = 3
boxes1 = torch.rand((N, 4))
boxes2 = torch.rand((M, 4))
 
 print(complete_box_iou(boxes1,boxes2))
 ```
 This function printed something like this:
 
 ```bash 
tensor([[ 1.6245e-02, -6.2233e-01, -3.7137e-01],
        [-1.4704e-01, -2.6185e+00, -2.2598e+01],
        [-1.2049e-01, -7.8739e-01, -7.8428e-01]])
 ```
 
 But The actual output should be something like 
 code : 
 ```python
container = []
for a in boxes1:
  for b in boxes2:
    container.append(1-complete_box_iou_loss(a,b))
torch.stack(container).reshape((3,3))
 ```
 Output
```bash
tensor([[  0.0162,  -0.0941,  -0.2408],
        [ -1.8978,  -1.2573, -10.8161],
        [ -0.3790,  -0.9598,  -0.7843]])
``` 

After applying your suggestions, the outputs match. 



Would you like to send pr to fix this? Also, I think we need more robust tests for bounding boxes, so we do not miss such cases.

**Comment by oke-aditya** [comment]
I think we are off somewhere in cIoU calculation. The loss seems to be correct.

Minimal code to reproduce. cc @datumbox @abhi-glitchhg 

```
>>> N = 5
>>> M = 5
>>> import torch, torchvision
>>> boxes1 = torch.rand((N, 4))
>>> boxes2 = torch.rand((M, 4))
>>> c_iou1 = 1 - torchvision.ops.complete_box_iou(boxes1, boxes2)
>>> c_iou2 = torchvision.ops.complete_box_iou_loss(boxes1, boxes2)
>>> c_iou1
tensor([[1.8451e+00, 1.1579e+00, 1.0234e+00, 1.0280e+00, 1.0084e+00],
        [1.7826e+00, 1.2285e+00, 1.0052e+00, 1.0792e+00, 1.0068e+00],
        [1.8545e+00, 1.3682e+00, 9.6855e+03, 1.0792e+00, 1.0115e+00],
        [1.8545e+00, 1.7379e+00, 9.6855e+03, 1.0792e+00, 1.0115e+00],
        [1.8363e+00, 1.1980e+00, 1.0061e+00, 1.0496e+00, 1.0115e+00]])
>>> c_iou2
tensor([1.8451, 1.2285, 1.0115, 1.0792, 1.0114])
>>> 

```


Samething I think for dIoU.

```
>>> d_iou1 = 1 - torchvision.ops.distance_box_iou(boxes1, boxes2)
>>> d_iou2 = torchvision.ops.distance_box_iou_loss(boxes1, boxes2)
>>> d_iou2
tensor([1.1527, 1.2257, 1.0087, 1.0792, 1.0114])
>>> d_iou1
tensor([[1.1527e+00, 1.1551e+00, 1.0206e+00, 1.0280e+00, 1.0084e+00],
        [1.0902e+00, 1.2257e+00, 1.0025e+00, 1.0792e+00, 1.0068e+00],
        [1.1621e+00, 1.3654e+00, 9.6855e+03, 1.0792e+00, 1.0114e+00],
        [1.1621e+00, 1.7351e+00, 9.6855e+03, 1.0792e+00, 1.0115e+00],
        [1.1440e+00, 1.1952e+00, 1.0033e+00, 1.0496e+00, 1.0115e+00]])
>>> 
```

**Comment by datumbox** [comment]
@senarvi Thanks for pointing this out. This is a bug.

To ensure BC and alignment with previous `*_box_iou()` methods, we needed to maintain the NxM feature. Note that the equivalent loss methods should be doing element-wise calculations to be efficient, so any bug fix shouldn't be making the losses to estimate extra unnecessary info. This is something that was discussed on the original PRs. 

@oke-aditya @abhi-glitchhg @yassineAlouini Anyone interested in patching this?

**Comment by oke-aditya** [comment]
I will patch this :smile:

**Comment by datumbox** [comment]
@oke-aditya Thanks! Please send a PR and update the tests accordingly to capture these issues going forwards.

**Comment by senarvi** [comment]
> The case where we need only the diagonal elements is for calculation of losses. (Are you trying to do `loss = 1 - box_iou.diagonal()`). We do have an optimized version for calculating the loss. See https://github.com/pytorch/vision/blob/main/torchvision/ops/_utils.py#L87

Exactly. Thanks @oke-aditya , I hadn't noticed the loss functions.

I'm curious if there are other differences, apart from the fact that `_loss_inter_union()` produces element-wise results. I can see two differences:
	
* `_box_inter_union()` upcasts the box coordinates before calculating the box and intersection areas. `_loss_inter_union()` does not. Is this intentional?
* `_box_inter_union()` uses `clamp(min=0)` to make sure that the intersection is zero if the boxes don't intersect. `_loss_inter_union()` explicitly checks that the width and the height are positive. Does this make `_loss_inter_union()` more stable? (I don't see how.)

**Comment by oke-aditya** [comment]
> _box_inter_union() upcasts the box coordinates before calculating the box and intersection areas. _loss_inter_union() does not. Is this intentional?

We do upcast in losses. But we upcast non float as we don't currently support int dtype for losses. This is intentional.

See https://github.com/pytorch/vision/blob/main/torchvision/ops/ciou_loss.py#L48 
and https://github.com/pytorch/vision/blob/ec0e9e127ab1d6f2c91eb07ad638fa359063d546/torchvision/ops/diou_loss.py#L48


> _box_inter_union() uses clamp(min=0) to make sure that the intersection is zero if the boxes don't intersect. _loss_inter_union() explicitly checks that the width and the height are positive. Does this make _loss_inter_union() more stable? (I don't see how.)

Both are `_` functions and aren't exposed as such for use, so we don't guarantee BC in either.
All the added losses and ops are stable.  (I hope I'm right @datumbox ?)

I also think that the loss shouldn't be zero if the boxes don't intersect. I think that's correct as a loss function should help to find the intersection. While Plain IoU (box_iou) should of course be 0 as boxes don't intersect.

**Comment by senarvi** [comment]
Got it. You upcast them already earlier.

I was just curious if there were any functional differences, because there are many differences in how the code is written, but apparently not. (I did spot one additional `eps` in [`_diou_iou_loss()`](https://github.com/pytorch/vision/blob/main/torchvision/ops/diou_loss.py#L67)).

Thanks for the clarification!

**Comment by oke-aditya** [comment]
Yeah for all the losses we support the eps parameter of course to avoid zero division error.

**Comment by yassineAlouini** [comment]
@oke-aditya happy to review once the code is ready. 👌 
Thanks in adavance for the fix.

**Comment by vadimkantorov** [comment]
> Yeah for all the losses we support the eps parameter of course to avoid zero division error.

Or could alternatively set that in this case iou is assumed 0 (which in practice makes sense for 0-area boxes)

**Comment by alexandre-dang** [comment]
Also I don't know if it's intended but distance_box_iou can return negative numbers, in the case where 2 boxes doesn't touch at all. I know it's in the formula but at the same time it breaks a lot of things and I wonder if it should be caped at 0

**Comment by datumbox** [comment]
@alexandre-dang Given it's on the formula our implementation needs to produce the right values. For specific use-cases where the user needs it strictly positive, they can do it outside of the method.

**Comment by oke-aditya** [comment]
AFAIK it's intended. That's the rationale behind generalized iou and other other iou methods such as distance and complete. 

Giving negative values gives a better feedback to neural network (when used as loss) and as a metric is more relevant.

That's the advantage over vanilla box iou.
