### ISSUE TITLE
Deep copy models with create_feature_extractor produces different parameters

### ISSUE THREAD

**Issue by ys-zong** [pytorch/vision#6352]
### 🐛 Describe the bug

When I define a model using the new feature create_feature_extractor and then deep copy the model, the parameters of the original model and the new models are different.

Here is an example:

```python
from torchvision.models.feature_extraction import create_feature_extractor
import torch.nn as nn
import torchvision
import copy

class cusResNet18(nn.Module):    
    def __init__(self, n_classes, pretrained = True):
        super(cusResNet18, self).__init__()
        self.resnet = torchvision.models.resnet18(pretrained=pretrained)
        self.resnet.fc = nn.Linear(512, n_classes)
        
        self.avgpool = self.resnet.avgpool
        
        self.returnkey_avg = 'avgpool'
        self.returnkey_fc = 'fc'
        self.body = create_feature_extractor(
            self.resnet, return_nodes={'avgpool': self.returnkey_avg, 'fc': self.returnkey_fc})

    def forward(self, x):
        outputs = self.body(x)
        return outputs[self.returnkey_fc], outputs[self.returnkey_avg].squeeze()
    
model = cusResNet18(n_classes=1)
copied_model = copy.deepcopy(model)

print(len(list(model.parameters())), len(list(copied_model.parameters())))
```

The output is `62 124`.

If printing out the named_parameters, the differences are from the defined self.body.
```python
print(dict(model.named_parameters()).keys(), dict(copied_model.named_parameters()).keys())
```
I'm wondering why there is a difference after using deepcopy and how can I deepcopy a model that has the create_feature_extractor feature inside?

### Versions

torch==1.10.2
torchvision==0.11.3

**Comment by datumbox** [comment]
@ys-zong Thanks for reporting.

I believe this is due to the way FX works. Instead of posting my answer here and then inviting the PyTorch Core engineers to have a look, I will post on your original issue. This is only to simplify back and forth. :)
