### ISSUE TITLE
Adding ADE20K to TorchVision built-in dataset

### ISSUE THREAD

**Issue by kswain98** [pytorch/vision#6381]
### 🚀 The feature, motivation and pitch

Hi! Is it possible to add the ADE20K dataset to the TorchVision built-in dataset? Since the Sun and Places dataset is already available it would be great to have ADE20K which has annotated images that cover the scene categories from the SUN and Places database.

**Comment by malfet** [comment]
Moved from pytorch to torchvision

**Comment by datumbox** [comment]
I agree this dataset is important to be added. We have a separate tracker for this issue at #5200. Closing this as it's a duplicate but let's continue our discussion there.
