### ISSUE TITLE
[proto] Port detection transforms from reference

### ISSUE THREAD

**Issue by vfdev-5** [pytorch/vision#6393]
Transforms to port from [detection references](https://github.com/pytorch/vision/blob/main/references/detection/transforms.py) :

- [ ] RandomIoUCrop (@vfdev-5)
- [ ] ScaleJitter
- [ ] FixedSizeCrop
- [ ] RandomShortestSize
- [ ] SimpleCopyPaste

cc @vfdev-5 @datumbox @bjuncek @pmeier

**Comment by pmeier** [comment]
Duplicate of #5542.
