### ISSUE TITLE
torchvision.transforms.Normalize returning incorrect data

### ISSUE THREAD

**Issue by eric435** [pytorch/vision#642]
torchvision.transforms.Normalize is not returning the expected mean or std data.

```
x = Compose([ToTensor(),Normalize(mean=[0.485, 0.456, 0.406],
                                    std=[0.229, 0.224, 0.225])])(sources[0])

for i in [0,1,2]:
    print("Mean: " + str(x[i].mean()))
    print("STD: " + str(x[i].std()))
```

returns:
Mean: 1.7498891182031873
STD: 0.8045230472500627
Mean: 1.8374540507305848
STD: 0.8500865676496933
Mean: 1.9036868254619304
STD: 0.836965250131352

I've triple checked the input data, in fact:

```
x = ToTensor()(sources[0])

for i in [0,1,2]:
    print("Mean: " + str(x[i].mean()))
    print("STD: " + str(x[i].std()))
```

returns:
Mean: 0.8857246291297787
STD: 0.18423577883089282
Mean: 0.8675897274610334
STD: 0.19041939873105573
Mean: 0.8343295072505721
STD: 0.18831717499762937

**Comment by eric435** [comment]
Ok, I believe this is my mistake. Mean and STD passed in should correspond to my input tensor, and Normalize will give me a tensor with a 0 mean and std of 1. The arguments are not target mean and std, but input mean and std.

**Comment by soumith** [comment]
yep, you are correct. If that wasn't clear from the docs we really apologize. Do consider sending a patch to improve the docs if that's the case.
