### ISSUE TITLE
Cannot install from git using pip

### ISSUE THREAD

**Issue by vedantroy** [pytorch/vision#6426]
### 🐛 Describe the bug

I'm trying to install torchvision from source following this thread: https://github.com/pytorch/vision/issues/3283.
I tried doing `pip install 'git+https://github.com/pytorch/vision.git@v0.13.0'`, but it gives me the error:

```
Collecting git+https://github.com/pytorch/vision.git@v0.13.0
  Cloning https://github.com/pytorch/vision.git (to revision v0.13.0) to /tmp/pip-req-build-32tizbmz
  Running command git clone --filter=blob:none --quiet https://github.com/pytorch/vision.git /tmp/pip-req-build-32tizbmz
  Running command git checkout -q da3794e90c7cf69348f5446471926729c55f243e
  Resolved https://github.com/pytorch/vision.git to commit da3794e90c7cf69348f5446471926729c55f243e
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/vedant/miniconda3/envs/video-rec/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/vedant/miniconda3/envs/video-rec/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/vedant/miniconda3/envs/video-rec/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-8an9cnsq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-8an9cnsq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-8an9cnsq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 482, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-8an9cnsq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-43-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080 Ti
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] torch==1.12.1+cu116
[pip3] torchdata==0.4.1
[pip3] torchvision==0.13.1
[conda] numpy                     1.23.2                   pypi_0    pypi
[conda] torch                     1.12.1+cu116             pypi_0    pypi
[conda] torchdata                 0.4.1                    pypi_0    pypi
[conda] torchvision               0.13.1                   pypi_0    pypi
(video-rec) √ video-recommendation %

**Comment by NicolasHug** [comment]
Hi @vedantroy , does it work with `pip install --no-build-isolation` ?

**Comment by vedantroy** [comment]
@NicolasHug That seems to do the trick! For some reason, torchvision is not detecting my FFMPEG and I don't know why though. I did `conda install 'conda-forge::ffmpeg<4.3'`, which should give me ffmpeg 4.2

**Comment by NicolasHug** [comment]
On the ffmpeg side, perhaps @bjuncek @jdsgomes  will have some input?

**Comment by vedantroy** [comment]
> On the ffmpeg side, perhaps @bjuncek @jdsgomes will have some input?

Sounds good! I have also tried compiling ffmpeg from source, but that didn't help. Maybe there's a way to tell `torchvision` to use a local ffmpeg directory?

**Comment by NicolasHug** [comment]
> Maybe there's a way to tell torchvision to use a local ffmpeg directory?

Looks like we have a hard-coded logic for that:

https://github.com/pytorch/vision/blob/c0ba3ec86aff2f19044cf710b0d1a2364dad8f75/setup.py#L394-L397


So maybe you can try to tweak that (you'll have to download the repo locally though, not install it from `git+...`. Or perhaps also play with `LD_PRELOAD` or `LD_LIBRARY_PATH` to point to the ffmpeg `.so` files that you have build locally?

**Comment by vedantroy** [comment]
> > Maybe there's a way to tell torchvision to use a local ffmpeg directory?
> 
> Looks like we have a hard-coded logic for that:
> 
> https://github.com/pytorch/vision/blob/c0ba3ec86aff2f19044cf710b0d1a2364dad8f75/setup.py#L394-L397
> 
> So maybe you can try to tweak that (you'll have to download the repo locally though, not install it from `git+...`. Or perhaps also play with `LD_PRELOAD` or `LD_LIBRARY_PATH` to point to the ffmpeg `.so` files that you have built locally?

If I use a local ffmpeg installation, will torchvision be dynamically or statically linked. Basically, can I remove the local installation afterwards or do I need to keep it?

**Comment by vedantroy** [comment]
Ohhh, I see the issue is that using python 3.9 is bad with torchvision. I would suggest a error message / hard exit instead of setting `has_ffmpeg = False`.

**Comment by vedantroy** [comment]
Nevermind, still having compilation errors for the video stuff, see: https://github.com/pytorch/vision/issues/6430
