### ISSUE TITLE
Question of why FCOS uses AnchorGenerator

### ISSUE THREAD

**Issue by interactivetech** [pytorch/vision#6429]
@xiaohu2015  @zhiqwang Thanks for the amazing work! I was wondering why was FCOS implemented using AnchorGenerator when it's an anchor free detector? I looked at other implementations [AdelaiDet](https://github.com/aim-uofa/AdelaiDet), [Original FCOS implementation](https://github.com/tianzhi0549/FCOS), and these implementations dont use anchors. Any intuition or benefits  for using anchors would be helpful to understand, as I am planning to implement FCOS using the Torchvision implementation. 

Thank you in advance for your time!

**Comment by datumbox** [comment]
Thanks for the question @interactivetech.

As @jdsgomes explained previously, FCOS is indeed anchor-free. The anchor generator is only used as an implementation trick to compute in each (x, y) position the centerness score. There are many other ways to generate those boxes but one was to just reuse the existing anchor-generator utility. This was purely to avoid creating another utility to do the job.

I'm going to close the issue as I believe this answers the question, but feel free to reopen if you have more questions. Also other can add more details if necessary :)

**Comment by zhiqwang** [comment]
In other words, anchor free doesn't mean it doesn't use anchors at all, it just has more flexibility when doing boxes encoding and decoding.
