### ISSUE TITLE
How to train Inceptionv3 model with high-resolution images (ex. 512x512, 2048x2048)? 

### ISSUE THREAD

**Issue by hongyiyu** [pytorch/vision#644]
I'd like to train the Inceptionv3 model with high-resolution images like 512x512.
As I know, the Inceptionv3 is designed to work with variable size of images.
However, if I train it with images which is not 299x299 size, it return with errors like:
`size mismatch, m1: [8 x 19200], m2: [768 x 1000]`

It's looks like have some problem with this line.

if self.training and self.aux_logits:
    aux = self.AuxLogits(x)`
         
https://github.com/pytorch/vision/blob/62cbf0bfd73c3a258e722cd3b468269c5b07b579/torchvision/models/inception.py#L108

Anybody can help me? 

Thanks a lot in advance

**Comment by fmassa** [comment]
Hi,

The issue is that we have a fixed `avg_pool2d` in https://github.com/pytorch/vision/blob/master/torchvision/models/inception.py#L117 instead of a global avg pooling.

The solution for now is to copy-paste the implementation and modify that line to use a `F.adaptive_avg_pool2d(x, (1, 1))`.

**Comment by hongyiyu** [comment]
@fmassa 
Thank you for your reply.
It seems like also need to modify the class InceptionAux
https://github.com/pytorch/vision/blob/master/torchvision/models/inception.py#L297
I want to make the kernel_size of conv1 adatively to output 1x1x768 size. However, I tried several ways, all give me errors.
Do you have any ideas?

**Comment by fmassa** [comment]
No, it looks like you'd need to change https://github.com/pytorch/vision/blob/master/torchvision/models/inception.py#L304 to be `F.adaptive_avg_pool2d(x, (5, 5))`, or something like that.

**Comment by hongyiyu** [comment]
@fmassa

I saw someone change the auxlogits part as the following line to make the inception available for variable image size. 
https://github.com/ncoudray/DeepPATH/blob/master/DeepPATH_code/01_training/xClasses/inception/slim/inception_model.py#L257
https://github.com/ncoudray/DeepPATH/blob/master/DeepPATH_code/01_training/xClasses/inception/slim/inception_model.py#L321

I think there are three available choices, first the L117 should change to `F.adaptive_avg_pool2d(x, (1, 1))`, then:
1. change the L304 to `F.adaptive_avg_pool2d(x, (5, 5))` as you said,
2. add a line `F.adaptive_avg_pool2d(x, (1, 1))` below L308 `x = self.conv1(x)`
https://github.com/pytorch/vision/blob/master/torchvision/models/inception.py#L308
3.  change the kernel_size of conv1 in auxlogits adatively to output 1x1x768 size

which one do you think is most reasonable?

Thanks.

**Comment by fmassa** [comment]
I think I'd follow option 1.

**Comment by ekagra-ranjan** [comment]
I guess this can be closed due to #744.
