### ISSUE TITLE
Windows CI jobs failing on main

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#6466]
### 🐛 Describe the bug

The CI is [failing](https://app.circleci.com/pipelines/github/pytorch/vision/19615/workflows/469aca17-ed45-412b-a8f9-d37fab17091e/jobs/1588913) across all Windows jobs with the following error:
```
UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: pkgs/main
  channel url: https://repo.anaconda.com/pkgs/main
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

It looks like an anaconda issue.

### Versions

latest main branch

cc @peterjc123 @nbcsm @guyang3532 @maxluk @gunandrose4u @mszhanyi @seemethere

**Comment by malfet** [comment]
Looks like a CircleCI configuration issue, let me try to re-run and if it fails will file a support ticket against them

**Comment by malfet** [comment]
And looks like re-run moves it a bit further, see https://app.circleci.com/pipelines/github/pytorch/vision/19615/workflows/469aca17-ed45-412b-a8f9-d37fab17091e/jobs/1590017

**Comment by datumbox** [comment]
@malfet might have also been temporary. It was failing the last 5 hours or so but the last commit on main seems green. I think we can close the issue?

**Comment by malfet** [comment]
Kicked re-runs, closing the issue, but will open a followup against pytorch/pytorch
