### ISSUE TITLE
[Enchancement] Provide some API of generate unique color by class id

### ISSUE THREAD

**Issue by jinfagang** [pytorch/vision#647]
My situation we need generate a color for visualization. But it is very unconvenient to write that helper function every time. If it can be provide into torch vision, that would be very helper.

If there already exist such api, pls let me know

**Comment by fmassa** [comment]
Can't you use matplotlib or something like that for generating the colors following a colorspace?

**Comment by jinfagang** [comment]
It can. but not such convenient whenever comes to the circumstances of visualize something such as detection box or tracking id box or segmentation mask etc.

**Comment by fmassa** [comment]
I'll think about adding something like that in torchvision.
In the meantime, you could [use something like this](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/demo/predictor.py#L239-L245) to get the color for each class id.

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
