### ISSUE TITLE
transforms.ColorJitter is producing different results every time run the program

### ISSUE THREAD

**Issue by nodegin** [pytorch/vision#652]
Hello, here is my small program:

```py
import torch
import torchvision
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

mean = [0.5, 0.5, 0.5]
std  = [0.5, 0.5, 0.5]
transform = transforms.Compose([
  transforms.Resize((280, 280)),
  transforms.CenterCrop((224, 224)),
  transforms.ColorJitter(brightness = 2),
  transforms.ToTensor(),
  transforms.Normalize(mean, std),
])

data_test_img = datasets.ImageFolder(root = './dataset/test',
                                     transform = transform)
data_loader_test_img = torch.utils.data.DataLoader(dataset = data_test_img,
                                                   batch_size = 1,
                                                   shuffle = False)

image, label = next(iter(data_loader_test_img))
img = torchvision.utils.make_grid(image)
img = img.numpy().transpose((1, 2, 0))
img = img * std + mean

plt.imshow(img)
plt.show()
```

First run:
<img width="752" alt="screenshot 2018-11-03 at 6 21 52 pm" src="https://user-images.githubusercontent.com/8536244/47950965-5ee53180-df95-11e8-921d-3796a8c372d4.png">

Second run:
<img width="752" alt="screenshot 2018-11-03 at 6 21 56 pm" src="https://user-images.githubusercontent.com/8536244/47950967-63114f00-df95-11e8-97fd-a12a2cabd977.png">

Third run:
<img width="752" alt="screenshot 2018-11-03 at 6 22 00 pm" src="https://user-images.githubusercontent.com/8536244/47950973-6a385d00-df95-11e8-9e97-285a8b959177.png">

Python 3.7.0
Torch 0.4.1
Vision 0.2.1

**Comment by nodegin** [comment]
How can I set the probability for ColorJitter transform? Or is there any way to change the brightness in transforms.Compose chain

**Comment by fmassa** [comment]
The arguments in the `ColorJitter` correspond to the ranges in which the values will be sampled, see https://github.com/pytorch/vision/blob/master/torchvision/transforms/transforms.py#L781-L811

If you want more fine-grained control over the color transformations, you can use the [functional interface as in here](https://github.com/pytorch/vision/blob/master/torchvision/transforms/transforms.py#L781-L811).

Let us know if you have more questions.
