### ISSUE TITLE
Add support for CMYK -> RGB in `decode_jpeg()`

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#6538]
Asking for a CYMK jpeg file to be converted to RGB by `decode_jpeg()` currently results in the following error:

```py
from torchvision.io import read_file, decode_jpeg, ImageReadMode

path = "test/assets/fakedata/logos/cmyk_pytorch.jpg"
decode_jpeg(read_file(path), mode=ImageReadMode.RGB)  # ImageReadMode.UNCHANGED would work
```

```p
RuntimeError: Unsupported color conversion request
```

This is an important feature to support because the ImageNet dataset has ~20 CMYK images, which means we currently cannot decode ImageNet files with `decode_jpeg()`: we have to rely on PIL.

According to this comment in our code there should be a way to support this:
https://github.com/pytorch/vision/blob/9b432d074a1c078eaae2023d301093e49e9954c2/torchvision/csrc/io/image/cpu/decode_jpeg.cpp#L120-L124

**Comment by tmabraham** [comment]
bumping this, had this issue with imagenet just now
