### ISSUE TITLE
bug in transforms.py

### ISSUE THREAD

**Issue by fenneishi** [pytorch/vision#6547]
### location:
https://github.com/pytorch/vision/blob/112accf95631660d55fc3761e8133f1c4bc6ae89/torchvision/transforms/transforms.py#L631
### fix:

`if h + 1 < th or w + 1 < tw:`  ==>`if h < th or w < tw:`

cc @vfdev-5 @datumbox

**Comment by datumbox** [comment]
@fenneishi thanks for reporting.

@vfdev-5 I see this was introduced at #2816. For `h=100, th=101` this will lead to `101<101` which seems wrong. Do you remember if there was a specific reason for adding the +1s or you think it's a bug?

**Comment by vfdev-5** [comment]
Yes, it is a bug. The condition `if h + 1 < th or w + 1 < tw:` was derived wrongly from`torch.randint(0, h - th + 1, size=(1,))` as we need to generate a random int value. `h - th + 1` is the upper non-inclusive boundary.

It should be `h - th + 1 >= 2` -> `h + 1 >= th + 2` -> `h >= th + 1` or `h > th`. We also need to take into account that `h == th`. Thus, obviously correct condition is `if h < th: raise error`

**Comment by fenneishi** [comment]
thanks
