### ISSUE TITLE
Unsupervised Images Dataset?

### ISSUE THREAD

**Issue by devforfu** [pytorch/vision#660]
How do you think, would it be reasonable to have an "unsupervised" mode for [`DatasetFolder`](https://github.com/pytorch/vision/blob/master/torchvision/datasets/folder.py#L54) class? Now it expects each image to sit in its own folder but sometimes I would like to just load a bunch of images from the unlabelled test set, like:
```python
dataset = DatasetFolder(path, loader=open_image, unsupervised=True)
image = dataset[i]  # or maybe (image, None), or (image, -1)
```

**Comment by fmassa** [comment]
Hi,

I believe we can always create a folder with a single folder in it (for example via symlinks if we don't want to copy the data), which makes it possible to use `DatasetFolder` straight away.

Would that be a solution? It would return `(image, 0)`, which you can discard

**Comment by fmassa** [comment]
Or a very basic implementation:
```python
import os
import glob

class BunchOfImagesDataset(object):
    def __init__(self, folder, transforms=None):
        self.folder = folder
        self.files = glob.glob(os.path.join(folder, '*.jpg'))
    
    def __getitem__(self, idx):
        ...
    def __len__(self):
        return len(self.files)
```

I think that the proposed solutions are simple enough, so that it might not be necessary to add one more level of complexity.
