### ISSUE TITLE
entropy of a tensor

### ISSUE THREAD

**Issue by isalirezag** [pytorch/vision#662]
can we have feature enhancement that we can compute the entropy of a tensor, the similar way that we can do it for mean, std, etc?

**Comment by fmassa** [comment]
So you want a feature that normalizes the tensor by its entropy, is that right?
Or do you want a function that computes the entropy of a tensor?

**Comment by isalirezag** [comment]
I would like  a tensor that compute the entropy of tensor. well, saying that, it is good if that function can compute the entropy in different ways, meaning that we can define a dimension and compute the entropy based on that, e.g. channel wise, etc
I think as soon as we can compute the entropy, normalizing it should not be too difficult, right?

**Comment by fmassa** [comment]
I believe this would be more suited to maybe `pytorch/contrib`, as it is not really vision-specific. Can you maybe open an issue there?

**Comment by isalirezag** [comment]
sure :)
