### ISSUE TITLE
Details about how pretrained models are trained?

### ISSUE THREAD

**Issue by sebgao** [pytorch/vision#666]
Hi, would there be some details about how pretrained models are trained, especially for ResNet? Are they trained according to the original paper or not?

**Comment by fmassa** [comment]
Hey,

We are looking into adding more information (including the training scripts) for how the models were trained.

For resnets (and almost all other models in torchvision), they have been trained with the [`examples/imagenet`](https://github.com/pytorch/examples/tree/master/imagenet) implementation.
