### ISSUE TITLE
Add a function to remove degenerate boxes

### ISSUE THREAD

**Issue by Quintulius** [pytorch/vision#6664]
### 🚀 The feature

This function would filter boxes where x2 <= x1 or y2 <= y1

### Motivation, pitch

Degenerate boxes are filtered in at least two places in the current torchvision code:

* https://github.com/pytorch/vision/blob/f725901dde5bc996fe3d4e163f4d4e7d53720146/torchvision/prototype/transforms/_augment.py
* https://github.com/pytorch/vision/blob/96dbada4d588cabbd24ab1eee57cd261c9b93d20/references/detection/transforms.py

This could be refactored, a function ```remove_degenerate_boxes``` could be added in ```ops.boxes``` and exposed publicaly.

### Additional context

If relevant I would be happy to work on it !

**Comment by datumbox** [comment]
@Quintulius We are currently working on our Transforms V2 API and have two transforms you can use are: [ClampBoundingBoxes](https://github.com/pytorch/vision/blob/main/torchvision/prototype/transforms/_meta.py#L63) and [RemoveSmallBoundingBoxes](https://github.com/pytorch/vision/blob/main/torchvision/prototype/transforms/_misc.py#L152). The first ensures that x1<=x2, y1<=y2 and the other one can remove boxes based on a threshold size. Both classes are prototypes (hence only available on nightly build), nevertheless we have checked the API and confirmed it produces the same accuracy as the stable transforms and those available on references. Concerning an operator to remove tiny boxes we already have one on stable, check [remove_small_boxes()](https://github.com/pytorch/vision/blob/main/torchvision/ops/boxes.py#L115).

If you want to give the new Transforms API a go, have a look on the updated references at #6433. We would love to get your feedback!
