### ISSUE TITLE
[prototype] Should we make `prototype.transforms._utilis.py` public?

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#6737]
### 🚀 The feature

A large number of utility methods such as `query_bounding_box`, `has_any`, `has_all` etc are being used regularly by our new Transform Classes but are not exposed publicly to the users. We should discuss which of them we want to expose publicly, to assist Transform authoring on the new API.

### Motivation, pitch

While users start developing transforms using the new API, they would be forced to write quite some extra code to achieve basic tasks like checking the provided input types, ensuring the spatial size is consistent across all items etc. Currently all these methods are private because they live in the `_utils.py` private module and they are not exposed via `__init__.py`. This is likely to push users of the new API to use private methods in their code or force them to write a lot of extra duplicate code to do basic operations.

### Alternatives

We can leave the methods private (or even prefix them with `_`, though this seems an overkill because they are not exposed via any public module) and let users write their own utilities.

cc @vfdev-5 @bjuncek @pmeier

**Comment by pmeier** [comment]
Maybe I haven't expressed it before, but I was always in favor of having these public just for the reason you described: without them, we are making it harder for users to write custom transforms. That will hinder adoption and that is the last thing I want.

**Comment by datumbox** [comment]
@pmeier I agree with your points. There are numerous methods we use for our standard transform authoring that start with `_` while others dont. I think some of them are marked with `_` incorrectly.

Can you bring a PR that removes the `_` from the methods you favour to make public? We won't make them public now (they are in a private module and not exposed) but it will become clearer what's the proposal.

**Comment by pmeier** [comment]
Just to understand you correctly: an prefixed `_` should mean "this should not be exposed" while everything else will be either exposed or is a candidate for which we need to decide later?

**Comment by datumbox** [comment]
Correct. One example I had in mind is the `_isinstance` utility method that is probably extremely useful to expose. I'm sure the `_` here was put to avoid the conflict with the builtin method (so we need a better name), but looking at the `_utilis.py` I don't see a clear proposal to what could be public and what is definitely private. This is probably low-priority now as we first want to get feedback from users concerning the existing transforms and then let them do authoring (once the API is stable) but it's good to mark it on our backlog.

**Comment by pmeier** [comment]
Closed in #6989.
