### ISSUE TITLE
Redundant code in to_tensor()

### ISSUE THREAD

**Issue by AdeelH** [pytorch/vision#676]
The following code (lines 84-87) in the definition of `to_tensor()` ([link](https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional.py#L84)) seems to first convert to HWC format and then immediately to CHW and that too using 2 calls to `transpose()` instead of calling `view()` or `reshape()`. Is there any reason for this?

```
    img = img.view(pic.size[1], pic.size[0], nchannel)
    # put it from HWC to CHW format
    # yikes, this transpose takes 80% of the loading time/CPU
    img = img.transpose(0, 1).transpose(0, 2).contiguous()
```

**Comment by fmassa** [comment]
Hi,

There is a difference between doing `view().permute()` and `view()` alone, and that boils down to how the memory is represented.

Here is a simple example illustrating why the current way of doing can't be replaced by a single `view`

```python
img = torch.arange(18)
img1 = img.view(3, 3, 2).permute(2, 0, 1)
img2 = img.view(2, 3, 3)
print(img1)
print(img2)
```
which gives (as expected) different results
```python
tensor([[[ 0,  2,  4],
         [ 6,  8, 10],
         [12, 14, 16]],

        [[ 1,  3,  5],
         [ 7,  9, 11],
         [13, 15, 17]]])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
```
