### ISSUE TITLE
AttributeError: module 'torchvision.transforms' has no attribute 'AugMix'

### ISSUE THREAD

**Issue by HaithemH** [pytorch/vision#6764]
### 🐛 Describe the bug

AttributeError: module 'torchvision.transforms' has no attribute 'AugMix' 

### Versions

AttributeError: module 'torchvision.transforms' has no attribute 'AugMix'

**Comment by datumbox** [comment]
Please check the version of TorchVision that you are using. Chances are you are using an older version. I'm closing this issue as it doesn't contain sufficient information for us to investigate the problem. I recommend if the issue persists to open a new one with all the required info. Thanks!
