### ISSUE TITLE
Local Grayscale Patch Replacement for Data Augmentation 

### ISSUE THREAD

**Issue by Mohit-robo** [pytorch/vision#6766]
### 🚀 The feature

Motivation: https://arxiv.org/ftp/arxiv/papers/2101/2101.08783.pdf

As proposed in the above-linked paper, this PR is for `Local Grayscale Patch Replacement`.
This transformation technique was initially proposed for `person reidentification`.
This transformation technique creates a `grayscale patch of size: mentioned area and aspect ratio`, as shown in the image below.
 
This technique has some base motivation taken from `RandomErasing`, one such transformation technique. 

![1](https://user-images.githubusercontent.com/82194525/195681516-1fe12772-7462-4cfa-86f7-68f29004431c.png)

### Motivation, pitch

I am currently working with Person reidentification, as an approach to make the dataset more robust and varied, some transformations were applied to the data. `Local Grayscale Patch Replacement` is one such transformation technique proposed, about which direct implementation is not available. 
This could help in the direct implementation of the technique.

cc @vfdev-5 @datumbox

**Comment by datumbox** [comment]
Thanks @Mohit-robo for the proposal.

We are always on the look out for implementing new promising techniques. I had a look on the paper and though the implementation of the Transform seems straight forward (thanks for the references, I agree that it would share commonalities with RandomErasing), the paper has only 1 citation (perhaps it's too new). I would recommend to give it a bit more time to get more traction and reassess. In the mean time, you could implement this transform yourself (perhaps have a look at the new Transforms API) and make it available via your repo. If the transform gets traction, we can certainly discuss upstreaming it to TorchVision. What do you think?

**Comment by Mohit-robo** [comment]
Thanks for the PR review, makes sense to me what you think, this works completely for me. Will surely have a look at Transforms API.
