### ISSUE TITLE
Pad PIL.Image with P mode is broken.

### ISSUE THREAD

**Issue by hubutui** [pytorch/vision#677]
It seems that torchvision don't consider PIL.Image mode 'P', see https://pillow.readthedocs.io/en/3.0.x/handbook/concepts.html#concept-modes. `torchvision.transforms.Pad` simply create numpy array from PIL.Image object and pad, and convert back to PIL.Image. And only RGB & grayscale image mode could be transformed properly.
`torchvision.transforms.Pad` on palette PIL.Image object give me wrong result, output image is all black.

**Comment by fmassa** [comment]
Fixed via https://github.com/pytorch/vision/pull/683
