### ISSUE TITLE
Problem using torch in sphinx gallery

### ISSUE THREAD

**Issue by joacorapela** [pytorch/vision#6792]
### 🐛 Describe the bug

I am failing trying to run a simple Python script, using PyTorch code, with sphinx-gallery. After having tried multiple versions of this script, I always get nonsense errors related to PyTorch tensors. However, the different versions of this script I have tried worked well when invoked from the command line.

Initially I thought it was a sphinx-gallery problem, and I opened an [issue](https://github.com/sphinx-gallery/sphinx-gallery/issues/1036) in their repository. But yesterday I realized that it could be a PyTorch problem, as I always get nonsense errors related to PyTorch tensors. I have also noticed that torchvision uses sphinx-gallery, so I am hoping that someone here has experienced a similar problem, and can advise me on how to solve it. Please refer to the previous issue for details.

Many thanks, Joaquin

### Versions

Collecting environment information...
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.7.13 (default, Mar 29 2022, 02:18:16)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-46-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] gpytorch==1.2.1
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==1.10.2
[pip3] torchvision==0.11.0a0
[conda] _pytorch_select           0.2                       gpu_0
[conda] blas                      1.0                         mkl
[conda] cpuonly                   1.0                           0    pytorch
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] gpytorch                  1.2.1                    pypi_0    pypi
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py37h7f8727e_0
[conda] mkl_fft                   1.3.1            py37hd3c417c_0
[conda] mkl_random                1.2.2            py37h51133e4_0
[conda] numpy                     1.21.5           py37h6c91a56_3
[conda] numpy-base                1.21.5           py37ha15fc14_3
[conda] pytorch                   1.10.2          cpu_py37hfa7516b_0
[conda] torchvision               0.11.3          cpu_py37h164cc8f_0

**Comment by pmeier** [comment]
> I am failing trying to run a simple Python script, using PyTorch code, with sphinx-gallery. After having tried multiple versions of this script, I always get nonsense errors related to PyTorch tensors. However, the different versions of this script I have tried worked well when invoked from the command line.

Could you be more specific? What code are you running? What are the errors?

**Comment by joacorapela** [comment]
Thanks for your reply @pmeier. I have just solved this problem. It was unrelated to PyTorch.

The problem was that my sphinx configuration file ``conf.py`` contained a line ``autodoc_mock_imports = ["torch"]`` that at one point I added to avoid import errors. I removed this line and everything works fine now.
