### ISSUE TITLE
cmake workflows fail on Windows

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#6794]
Since yesterday or more specifically since `pytorch=1.14.0.dev20221017` the CMake workflows are failing on Windows. For example: https://app.circleci.com/pipelines/github/pytorch/vision/21251/workflows/cb54fe99-650c-4084-9717-639ee6b20032/jobs/1724374

The command that is failing is the [installation of PyTorch core](https://app.circleci.com/pipelines/github/pytorch/vision/21217/workflows/6248dffe-c930-48bd-8415-f108e53dd9f0/jobs/1722001?invite=true#step-103-328):

```
$ conda install -yq pytorch=1.14.0.dev20221018 pytorch-mutex=1.0=cpu numpy -c nvidia -c pytorch-nightly
[...]
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch=1.14.0.dev20221018 -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python=3.7
```

If I interpret this right, it seems that the nightly requires `Python>=3.8` although we are running on 3.7.

The day before everything worked fine:

```
$ conda install -yq pytorch=1.14.0.dev20221016 pytorch-mutex=1.0=cpu numpy -c nvidia -c pytorch-nightly
[...]
## Package Plan ##

  environment location: C:\tools\miniconda3

  added / updated specs:
    - numpy
    - pytorch-mutex==1.0=cpu
    - pytorch=1.14.0.dev20221016


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.0                   |              mkl           6 KB
    intel-openmp-2021.4.0      |    haa95532_3556         2.2 MB
    mkl-2021.4.0               |     haa95532_640       114.9 MB
    mkl-service-2.4.0          |   py37h2bbff1b_0          49 KB
    mkl_fft-1.3.1              |   py37h277e83a_0         135 KB
    mkl_random-1.2.2           |   py37hf11a4ad_0         216 KB
    numpy-1.21.5               |   py37h7a0a035_3          25 KB
    numpy-base-1.21.5          |   py37hca35cd5_3         4.4 MB
    pytorch-1.14.0.dev20221016 |      py3.7_cpu_0       139.1 MB  pytorch-nightly
    pytorch-mutex-1.0          |              cpu           3 KB  pytorch-nightly
    typing_extensions-4.3.0    |   py37haa95532_0          42 KB
    ------------------------------------------------------------
                                           Total:       261.0 MB
```

Given that this only happens on Windows and couldn't find any commit that introduces the 3.8 requirement in core, this seems like a bug to me.

cc @seemethere

**Comment by YosuaMichael** [comment]
@pmeier I just ran CI Test on https://github.com/pytorch/vision/pull/5009 and it seems to pass the cmake for windows now.

**Comment by pmeier** [comment]
Let's wait for the first PR to be merged into `main` that also passes. If that is the case, we can close.

**Comment by pmeier** [comment]
All good on 7a62a545ce76f43ccc5cfe0009131f7db14ae7b5.
