### ISSUE TITLE
single channel images transform error

### ISSUE THREAD

**Issue by soumith** [pytorch/vision#68]
please add the following after line 78 (the for loop)

```for i in range(len(data)):
            data[i] = transforms.Compose([
                    transforms.ToPILImage(),
                    # Transformations
                    transforms.ToTensor(),
                ])(data[i])
```

in the MNIST example code (https://github.com/pytorch/examples/blob/master/mnist/main.py) and run it.
Reported by @adithyap

**Comment by ncullen93** [comment]
just curious.. is the plan to keep transforms such as RandomCrop, HorizontalFlip, etc only working on PIL images, or would you prefer *Tensor support as well?

Also, are you open to adding new transforms such a rotations, shearing, etc .. or are these already supported elsewhere?

Would be willing to contribute in these areas.

**Comment by alykhantejani** [comment]
@soumith I don't think this is an issue anymore since #54 was merged?

**Comment by fmassa** [comment]
Yes, I think this is fixed now. Thanks for pointing this out @alykhantejani !
