### ISSUE TITLE
ToTensor aliases input data and operations like Normalize work in-place

### ISSUE THREAD

**Issue by jatentaki** [pytorch/vision#680]
`ToTensor` aliases input data and operations like `Normalize` work in-place, which leads to a nasty footgun when implementing one's own data loaders with the data residing in RAM - as training progresses, the dataset becomes more and more "normalized" which is difficult to debug. Also, the fact that the current implementation of `datasets.MNIST` doesn't display this behavior seems to depend on an (arguably buggy) implementation detail of `PIL.Image`, as I argue in my answer to [this](https://stackoverflow.com/questions/53652015/unexpected-increase-in-validation-error-in-mnist-pytorch/53696375) stackoverflow question.

I propose that the in-place operation is at least made explicit in docs on `Normalize`, or (a breaking change) make it work out of place by default and add a `inplace` flag.

**Comment by soumith** [comment]
we should make Normalize out of place by default

**Comment by fmassa** [comment]
After `TensorIterator` was merged in PyTorch, an approach like https://github.com/pytorch/vision/pull/519 now is as efficient as the multiple for loops

**Comment by vishwakftw** [comment]
This can be closed now, since #699 has been merged.
