### ISSUE TITLE
Jetson torch1.9.0 torchvison0.10.0 python  setup.py install           error

### ISSUE THREAD

**Issue by YinZhang98** [pytorch/vision#6815]
### 🐛 Describe the bug

virtual AVCodec* findCodec(AVCodecParameters* params)

### Versions

![image](https://user-images.githubusercontent.com/33601373/197343935-1e2c998c-2d8d-42bd-a81d-fa6476e9ef28.png)
toch1.8,1.7 has the same error

**Comment by pmeier** [comment]
What version of `ffmpeg` / `av` / ... are you compiling against?

**Comment by YinZhang98** [comment]
> What version of `ffmpeg` / `av` / ... are you compiling against?

Thanks. I solved this problem because of ninja and ffmpeg
