### ISSUE TITLE
create_feature_extractor and get_graph_node_names should have a concrete_args argument

### ISSUE THREAD

**Issue by Tal-Golan** [pytorch/vision#6817]
### 🚀 The feature

Add a concrete_args argument to `tv.models.feature_extraction.create_feature_extractor` and `.get_graph_node_names`. The argument would be passed to torch.fx's trace().

### Motivation, pitch

Currently, one cannot use the torchvision feature extractor on modules whose forward method receives control-flow-affecting arguments. This limitation can be removed by passing the `concrete_args` keyword argument to all calls of .trace(). For example:
`
    train_tracer.trace(model.train(), concrete_args=concrete_args)
`

### Alternatives

Alternatively, one can edit the target module to eliminate the control-flow affecting arguments.

### Additional context

MRE:
```
import torch
from torchvision.models.feature_extraction import get_graph_node_names

class MyNet(torch.nn.Module):
    def forward(self, x, flag=True):
        return x if flag else x + 1

my_net = MyNet()
train_nodes, eval_nodes = get_graph_node_names(my_net)
```
This raises `TraceError: symbolically traced variables cannot be used as inputs to control flow`.

After the modification,  this following code will successfully run:
```
train_nodes, eval_nodes = get_graph_node_names(my_net, concrete_args={flag:True})
```

**Comment by Xparx** [comment]
Hello, I am looking into this exact issue. 

My use case is a module dict where I want to pass a key in my forward to determine what layer to use.
Is there a way to work around this?

```
class MyModel(torch.nn.Module):
    def __init__(module_map):

            self.context = nn.ModuleDict({key: (nn.Linear(in_features=in, out_features=out) ) for key, (in, out) in module_map})

           self

    def forward(self, x, key=None):

        if (key is None) or (key not in self.context):
            x = something_else(x)
        else:
            x = self.context[key](x)

        return x
```

In other words can I generate a feature extractor that I can determine the layer I want in?

**Comment by NicolasHug** [comment]
Fixed in https://github.com/pytorch/vision/pull/8393
