### ISSUE TITLE
Don't hardcode 255 unless uint8 is enforced

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#6825]
Across our transformations we sometimes hardcode the value `255`. This is justified if we make sure that point only `torch.uint8` images are allowed, like

https://github.com/pytorch/vision/blob/788ad12e5dcec1dffc7d6311e59a2be2792799b8/torchvision/transforms/functional_tensor.py#L471-L472

However, there are a few instances where uint8 is implied but never enforced:

https://github.com/pytorch/vision/blob/788ad12e5dcec1dffc7d6311e59a2be2792799b8/torchvision/transforms/functional_tensor.py#L266-L267

https://github.com/pytorch/vision/blob/788ad12e5dcec1dffc7d6311e59a2be2792799b8/torchvision/transforms/functional_tensor.py#L778-L779

https://github.com/pytorch/vision/blob/788ad12e5dcec1dffc7d6311e59a2be2792799b8/torchvision/transforms/functional_tensor.py#L852

Instead of hardcoding `255` here, we should either use `_max_value(dtype)` instead or if uint8 is actually required, enforce it.

cc @vfdev-5 @datumbox

**Comment by datumbox** [comment]
Good spot. It's also worth noting that the current stable uses incorrect bounds across methods. The ones that you highlighted use 255 for all integers. On the other hand, `convert_image_dtype` uses different bound depending on their integer type:
https://github.com/pytorch/vision/blob/9f024a6e52e1f9a7a588d743f3f383870ce97fbf/torchvision/transforms/functional_tensor.py#L47-L57

These two need to align. Either we will continue assuming that 255 is the right value for integers, or as you propose we should use the `_max_value(dtype)` everywhere else.

**Comment by pmeier** [comment]
I prefer the behavior of `convert_image_dtype` for two reasons:

1. If we would go for enforcing `[0, 255]` for image dtypes, it makes no sense to use to allow integer dtypes other than `uint8` in the first place. While `float16` or `float64` share the same value range with the default `float32`, their precision varies and thus it makes sense for them to have the same range. However, there is no such effect for integer dtypes. They would have the exact same number of valid values at the cost of increased memory in case of `int{16, 32, 64}`.
2. Changing the behavior of `convert_image_dtype` is BC breaking whereas changing the behavior of the ops mentioned above can be regarded as a bug fix. They were never doing the right thing unless one used uint8 or floating images.

**Comment by pmeier** [comment]
One more thing came to mind: although an edge case at best, by hardcoding `255` we we not only ignore large portions of the range for larger dtypes, we also don't handle the fact that `torch.int8` images can only store `[0, 127]`. For example, with the current implementation `F.posterize(image_int8, bits=4)` is a no-op.
