### ISSUE TITLE
LinearTransformation doc in the wrong place

### ISSUE THREAD

**Issue by themightyoarfish** [pytorch/vision#684]
`LinearTransformation` expects a Tensor and returns one, so it should be moved to the section with Tensor transforms and out of the one for PIL transforms.

**Comment by themightyoarfish** [comment]
For some reason I cannot edit the issue; I now see it actually works on PIL images instead of tensors, so its just the documentation that's wrong.

**Comment by soumith** [comment]
closed via #685
