### ISSUE TITLE
Support all integer and floating point dtypes in prototype transform kernels?

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#6840]
The standard rule for dtype support for images and videos is: 

- All floating point and integer tensors are supported.
- Floating point tensors are valid in the range `[0.0, 1.0]` and integer tensors in `[0, torch.iinfo(dtype).max]` (this is currently under review since there were a few cases, where this was not true or simply not handled. See #6825)

However we have currently two kernels that only support `uint8` images or videos:

- https://github.com/pytorch/vision/blob/c84dbfad97251271a789b252a2a1a52c73f623ff/torchvision/prototype/transforms/functional/_color.py#L373-L375
- https://github.com/pytorch/vision/blob/c84dbfad97251271a789b252a2a1a52c73f623ff/torchvision/transforms/functional_tensor.py#L788-L789

This also holds for transforms v1 so this is not a problem of the new API. 

One consequence of that is that AA transforms are only supported for `uint8` images

https://github.com/pytorch/vision/blob/c84dbfad97251271a789b252a2a1a52c73f623ff/torchvision/transforms/autoaugment.py#L104-L107

since both 

https://github.com/pytorch/vision/blob/c84dbfad97251271a789b252a2a1a52c73f623ff/torchvision/transforms/autoaugment.py#L76-L77

and 

https://github.com/pytorch/vision/blob/c84dbfad97251271a789b252a2a1a52c73f623ff/torchvision/transforms/autoaugment.py#L82-L83

are used.

One possible way of mitigating this to simply have a `convert_dtype(image, torch.uint8)` in the beginning and converting back after computation. 

That is probably needed for `equalize` since we recently switched away from the histogram ops of `torch` towards our "custom" implementation to enable batch processing (#6757). However, this relies on the fact that the input is an integer and in its current form even on `uint8` due to some hardcoded constants.

For `posterize` I think it is fairly easy to provide the same functionality for float inputs directly without going through a dtype conversion first.

cc @vfdev-5 @datumbox @bjuncek

**Comment by datumbox** [comment]
I'm in favour of doing this. It will allow users to cast to float32 first which might be beneficial for cases where the uint8 kernels are slower.

**Comment by datumbox** [comment]
Before closing this ticket, we should make the following proposed optimization on AugMix:
https://github.com/pytorch/vision/blob/e1f464bded7781be85fdf1762c01a7869d3aec97/torchvision/prototype/transforms/_auto_augment.py#L509-L513

**Comment by datumbox** [comment]
@pmeier I think the last thing to consider before closing the ticket is how `AA` can send the right threshold values to posterize when the Image is a float. Aka:
https://github.com/pytorch/vision/blob/e1f464bded7781be85fdf1762c01a7869d3aec97/torchvision/prototype/transforms/_auto_augment.py#L172

Thoughts on this?
