### ISSUE TITLE
I got torchvision=0.2.2.post3 when I install it with pip and python3.11

### ISSUE THREAD

**Issue by wwhio** [pytorch/vision#6842]
### 🐛 Describe the bug

I got torchvision=0.2.2.post3 when I install it with pip and python3.11

```
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
```

### Versions

PyTorch version: 1.13.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-4.15.0-193-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.6.55
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 515.43.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.13.0+cu116
[pip3] torchvision==0.2.2.post3

**Comment by datumbox** [comment]
Thanks for reporting. 

There are currently no 3.11 binaries. The reason you get such an old version is because that's the last available TorchVision release that is pure Python and doesn't have custom C++/CUDA ops. Addition of Python 3.11 will happen a bit later because we need to coordinate it with PyTorch Core. I'll close this issue to keep things tidy but if you have more questions feel free to reopen and post.

**Comment by XuehaiPan** [comment]
PyTorch 1.13 is released with Python 3.11 support.

**Comment by kohtala** [comment]
> PyTorch 1.13 is released with Python 3.11 support.

And torchvision was released the same day 28th Oct, but without Python 3.11 support. @datumbox , can this be reopened since the coordination with pytorch has failed and we have no milestone on which to wait for Python 3.11 support?

**Comment by kohtala** [comment]
@wwhio , perhaps you can reopen this one? Python 3.11 support for torchvision did not come when torch with support was released. I'm not sure if @datumbox even gets any notification on closed issues.

**Comment by Erotemic** [comment]
It would be nice to have this on 3.11 soon.

**Comment by kohtala** [comment]
There is #6959 for this.
