### ISSUE TITLE
`build_docs` fails with `[Makefile:42: html] Hangup`

### ISSUE THREAD

**Issue by datumbox** [pytorch/vision#6875]
### 🐛 Describe the bug

The `build_docs` CI job [fails](https://app.circleci.com/pipelines/github/pytorch/vision/21604/workflows/cab24b60-c4de-4680-ac60-6d89ef6988c4/jobs/1750608) on the latest main with:
```
make: *** [Makefile:42: html] Hangup
```

The job later times out on the CI once the 10-minute time limit is exhausted.

### Versions

Started appearing on 20221031

cc @seemethere

**Comment by pmeier** [comment]
#6598 is the offender @bjuncek @jdsgomes. I'm not sure yet why, but after that commit, building with multiple processes hangs. We do that by default with the `-j` flag:

https://github.com/pytorch/vision/blob/d95fbaf1efd5346a4afcf5b9953df75696432265/docs/Makefile#L9

Removing the multiprocessing like I did in #6884, [resolves the issue](https://app.circleci.com/pipelines/github/pytorch/vision/21648/workflows/96527bb7-408d-4def-b84b-958be0aa0a8f/jobs/1754081).

**Comment by NicolasHug** [comment]
There might be something fishy going on in the `VideoReader` then. Could we try to use it in a multi-processing setting, e.g. with `DataLoader(num_workers>1)`, and see if the lock happens?
