### ISSUE TITLE
does the densenet support gpu memory effecient implement?

### ISSUE THREAD

**Issue by mlinxiang** [pytorch/vision#691]
the densenet team give a efficent implement <https://github.com/gpleiss/efficient_densenet_pytorch/blob/master/models/densenet.py> 
does torchvision merge that and offer pretrained model ?

**Comment by fmassa** [comment]
The efficient implementation from the repo you pointed out should not be difficult to implement: from what I understand, it basically [uses `torch.utils.checkpoint`](https://github.com/gpleiss/efficient_densenet_pytorch/blob/master/models/densenet.py#L38) in the `DenseLayer`. This means that it could probably be added as an extra option, while keeping everything backwards-compatible I'd believe.

**Comment by githubssd** [comment]
I haven't tested it out on pytorch 1.0, but if you want to implement then I think @fmassa told everything.

**Comment by ekagra-ranjan** [comment]
@fmassa Can I take this up?

**Comment by soumith** [comment]
@ekagra-ranjan sure. Make sure everything is backwards-compatible.

**Comment by ekagra-ranjan** [comment]
@soumith I haven't seen any code which takes care of backward-compatibility. Can you please guide me with this?

**Comment by soumith** [comment]
you basically have to make sure API calls to the class constructor and forward function work (so if you add any new arguments to a function, they have to come at the end), and old pre-trained models / state_dicts are loadable after the PR.

**Comment by fmassa** [comment]
This was implemented in #797
