### ISSUE TITLE
Check tolerances for prototype transforms kernel reference tests

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#6937]
Restoring the tolerances to

https://github.com/pytorch/vision/blob/f32600b66d9c03682ccd975e442e67c609fd7f0a/test/prototype_transforms_kernel_infos.py#L64-L67

that will be cranked up by #6934 surfaces failures on the following kernels in the reference test:

- [x] `adjust_brightness_image_tensor`
- [x] `adjust_contrast_image_tensor`
- [x] `adjust_gamma_image_tensor`
- [ ] `adjust_hue_image_tensor`
- [x] `adjust_saturation_image_tensor`
- [x] `adjust_sharpness_image_tensor`
- [x] `affine_image_tensor`
- [x] `affine_mask`
- [x] `autocontrast_image_tensor`
- [x] `center_crop_image_tensor`
- [x] `crop_image_tensor`
- [ ] `elastic_image_tensor`
- [ ] `elastic_mask`
- [x] `equalize_image_tensor`
- [x] `five_crop_image_tensor`
- [x] `horizontal_flip_image_tensor`
- [x] `invert_image_tensor`
- [x] `pad_image_tensor`
- [ ] `perspective_image_tensor`
- [x] `perspective_mask`
- [x] `posterize_image_tensor`
- [ ] `resize_image_tensor`
- [x] `resize_mask`
- [ ] `resized_crop_image_tensor`
- [x] `resized_crop_mask`
- [ ] `rotate_image_tensor`
- [x] `rotate_mask`
- [x] `solarize_image_tensor`
- [x] `ten_crop_image_tensor`
- [x] `vertical_flip_image_tensor`

We need to go through each of them to see if there is a systematic problem here. However, this is not reason to "panic" since

1. these kernels are used in the training pipeline and we are seeing no accuracy drop compared to v1
2. these kernels are also tested for consistency against v1 and there everything is fine.

cc @vfdev-5 @datumbox @bjuncek

**Comment by pmeier** [comment]
It seems `adjust_hue` also has quite the difference on v1:

```py
import torch
from torchvision.transforms import functional as F

torch.manual_seed(0)
image = torch.randint(0, 256, (3, 512, 512), dtype=torch.uint8)

actual = F.adjust_hue(image, hue_factor=0.1)

expected = F.pil_to_tensor(F.adjust_hue(F.to_pil_image(image), hue_factor=0.1))

torch.testing.assert_close(actual, expected)
```

```
AssertionError: Tensor-likes are not equal!

Mismatched elements: 335568 / 786432 (42.7%)
Greatest absolute difference: 15 at index (1, 110, 148)
Greatest relative difference: inf at index (0, 31, 485)
```

**Comment by pmeier** [comment]
All the remaining kernels that exhibit these large tolerances, internally use interpolation. Unfortunately for us, the PyTorch ops don't match the interpolation behavior of PIL. Consider the following setup:

```py
import PIL.Image
import PIL.ImageDraw

from torchvision.prototype.transforms import functional as F, InterpolationMode

image_pil = PIL.Image.new("RGB", (256, 256))
draw = PIL.ImageDraw.Draw(image_pil)
draw.ellipse((64, 96, 192, 160), fill=(255, 255, 255))

image_tensor = F.to_image_tensor(image_pil)

size = (233, 147)
abs_diff_images = []
for interpolation in [
    InterpolationMode.NEAREST,
    InterpolationMode.NEAREST_EXACT,
    InterpolationMode.BILINEAR,
    InterpolationMode.BICUBIC,
]:
    resized_image_pil = F.resize(image_pil, size, interpolation=interpolation)
    resized_image_tensor = F.resize(image_tensor, size, interpolation=interpolation)
    abs_diff_images.append(resized_image_tensor.sub(F.to_image_tensor(resized_image_pil)).abs_())
```

This gives this input

![object_input](https://user-images.githubusercontent.com/6849766/203754799-3d91b851-1022-434c-b5c4-6956335ec24d.png)

and the following outputs:

![object_output](https://user-images.githubusercontent.com/6849766/203754818-15f38e1d-e2ad-4e75-bcce-215837171cb9.png)

Except for `NEAREST_EXACT` (second column) there is a slight deviation around the border of the object. In general though, the kernels are comparable.

However, this is not what we do in our test suite. There the generation logic looks more like

```py
import torch

torch.manual_seed(0)
image_tensor = torch.randint(0, 256, (3, 512, 512), dtype=torch.uint8)
image_pil = F.to_image_pil(image_tensor)
```

With this we get this input

![random_input](https://user-images.githubusercontent.com/6849766/203754985-ea325b1c-8b94-4dbd-a047-8c5be36a6b88.png)

and the following outputs:

![random_output](https://user-images.githubusercontent.com/6849766/203755041-de693926-c783-42f4-afe4-9da9c57b850d.png)

Even `EXACT_NEAREST`, which is supposed to aligned with PIL samples one row differently. All other interpolation modes give a completely different result. 

This is the reason we are seeing this crazy required tolerances: the difference is basically another random image.

I thought of four ways to move forward in decreasing order of my preference:

1. Change the input generation for the interpolation ops to objects like the ellipse above rather than random images. Together with `agg_method="mean"` we should get reasonable small differences again. Note that we cannot just set the `atol`, since the difference in the images above is most of the times (and for the `NEAREST` always) 255.
2. Remove the automatic reference tests for these kernels and replace them with handcrafted ones. This will likely mean we lose some "coverage" since we probably don't want to implement an exhaustive parameter tests manually.
3. Remove the reference tests for these kernels. We have verified now that the ops indeed work correctly and unless we touch the core logic, they will continue to do that. Of course this is not safe, since sometimes even innocuous looking changes can have an effect. Plus, there might also be changes to the ops in PyTorch core that affect us, but we never know.
4. Keep the test suite as is. With these high tolerances we have basically have option 3., but with extra flakiness and wasted resources sprinkled in.

Thought?

**Comment by pmeier** [comment]
I've played with option 1 from above. Using an ellipse as object that leaves roughly 10% border on each side, we only need to allow an MAE of 1 for `resize_image_tensor`.

**Comment by pmeier** [comment]
For `elastic_image_tensor` there is no more difference at all.

**Comment by vfdev-5** [comment]
> For `elastic_image_tensor` there is no more difference at all. With these results I'm now strongly in favor of 1.

There is no PIL implementation for elastic, we convert PIL to tensor :) That's why there is no diff

**Comment by pmeier** [comment]
Oh boy, good catch :laughing: Let me try `affine_image_tensor` then.

**Comment by vfdev-5** [comment]
> We should probably delete the reference test for elastic_image_tensor then. It gives us a false sense of security and I walked right into this pitfall.

Sure. There are few others doing a similar trick, like gaussian blur

**Comment by pmeier** [comment]
For `perspective_image_tensor` the required MAE is 2. My point stands :slightly_smiling_face:
