### ISSUE TITLE
Make `box_iou` accept arguments having `x1<=x2` and `y1<=y2`

### ISSUE THREAD

**Issue by sadra-barikbin** [pytorch/vision#6974]
### 🚀 The feature

Currently `torchvision.ops.box_iou` expects arguments to to satisfy `x1<x2` and `y1<y2`, but this could be easily relaxed to accept the cases in which `x1==x2` or `y1==y2`. In those cases, intersection becomes zero and following that, we could return zero.

### Motivation, pitch

To carry the burden of checking input arguments to satisfy `x1<x2` and `y1<y2`.

**Comment by oke-aditya** [comment]
Hi @sadra-barikbin 

Thanks for the request. 

Technically it's not a box when x1==x2 or y1==y2. It's a straight line. And the box_area of such boxes itself is 0. I don't get why user would have such case for IoU?

Also  to improve speed and CUDA async call. We have removed the conditional checks such as x1 >x2 are invalid (degenerate) boxes. 

Let me know your thoughts.

**Comment by sadra-barikbin** [comment]
It's just a corner case that might happen in a few situations. I saw that [cocoapi](https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/common/maskApi.c#L115-L116) handle it but torchvision does not.

**Comment by sadra-barikbin** [comment]
I could make the PR if the request is OK

**Comment by datumbox** [comment]
@oke-aditya's explanation is spot on. We have removed the checks to avoid synchronization as they really slow things down. The method expects valid boxes which just moves the extra check outside in the user code where the caller can assess if it is worth the slowdown.
