### ISSUE TITLE
 Any one here added resnet18 with maskrcnn?

### ISSUE THREAD

**Issue by prayagpawar** [pytorch/vision#6979]
Thanks @SriniMaiya for your comment. Any one here added resnet18 with maskrcnn?
looking for same https://github.com/alexander-pv/maskrcnn_tf2 try this
_Originally posted by @AhmedShahinAI in https://github.com/pytorch/vision/issues/3213#issuecomment-1189798492_

**Comment by pmeier** [comment]
Hey @prayagpawar. For requests like this, please refer to the [user forum](https://discuss.pytorch.org/). For the general discussion, i.e. whether we want to add new models / weights, I feel the thread in #3213 is sufficient. If you disagree, feel free to let me know.
