### ISSUE TITLE
Add Moving MNIST dataset

### ISSUE THREAD

**Issue by tsugumi-sys** [pytorch/vision#6981]
### 🚀 The feature

I would like to add MovingMNIST dataset.

### Motivation, pitch

A lot of people uses Moving MNIST dataset for evaluating their proposed models according to [PaperWithCode](https://paperswithcode.com/dataset/moving-mnist).

### Additional context

I've implemented [Movning MNIST dataset](https://github.com/tsugumi-sys/SAM-ConvLSTM-Pytorch/blob/main/dataset/moving_mnist.py) in my personal project. So I would like to make a PR based on this.

I checked https://github.com/pytorch/vision/issues/3562 and https://github.com/pytorch/vision/pull/2690.

@pmeier @yassineAlouini 
From [this comment](https://github.com/pytorch/vision/pull/2690#issuecomment-1114678355) in https://github.com/pytorch/vision/pull/2690, I might should add to `torchvision/prototype/datasets/_builtin`. So where should I add Moving MNIST dataset ?

cc @pmeier

**Comment by pmeier** [comment]
Hey @tsugumi-sys, sorry for the late reply. Yes, we would accept a PR adding the dataset! Fortunately for this, the prototype datasets are currently on hold and so you can add it to `torchvision.datasets` directly. Meaning, we can probably re-use most of what you already implemented. 

I've skimmed your linked implementation and it seems this is going into the right direction. In https://github.com/pytorch/vision/pull/2690#pullrequestreview-493281279 I had quite a few concerns regarding the first draft of the other PR. Please make sure to address them on yours.
