### ISSUE TITLE
Range compatibility for pytorch dependency

### ISSUE THREAD

**Issue by AlexanderVanEck** [pytorch/vision#6985]
### 🚀 The feature

Currently `torchvision` only ever supports a hard-pinned version of `torch`. f.e. `torchvision==0.13.0` requires`torch==1.12.0` and `torchvision==0.13.1` requires `torch==1.12.1`. It would be easier for users if torchvision wouldn't put exact restrictions on the `torch` version.

### Motivation, pitch

Hello 👋  Thank you for your continued support of `torchvison` we use it frequently and it works great!

In the project I maintain we manage our `torch` version regularly and therefore usually upgrade quickly to a new version when it comes out. However, due to the hard-pinning of `torchvision` we are often waiting for `torchvision` to release a new version before we can use bugfixes in `torch` (or exciting new features).

This raises a few questions:

* Is it important for `torchvision` to always hard-pin a version? 
* Are the upgrades of `torch` version in `torchvision` truly backwards incompatible?
* Could `torchvision` support a range of `torch` versions? (like `torchmetrics` does)

Adding a max range for the `torch` requirement would allow users to upgrade to a new version of torch automatically when it comes out.

**Examples**

`torchvision==0.13.0` could have depended on `torch<1.13` to include all bugfix releases of `torch==0.13.*`.
`torchvision==0.13.1` could have depended on `torch<1.13` to include all bugfix releases of `torch==0.13.*`.

A minimum version may also be appropriate when `torch` adds new APIs that `torchvision` wants to consume.

Your thoughts there would be greatly appreciated! Thank you for your work 🙇‍♂️

**Comment by pmeier** [comment]
> However, due to the hard-pinning of `torchvision` we are often waiting for `torchvision` to release a new version before we can use bugfixes in `torch` (or exciting new features).

Not sure I understand. All PyTorch distributions are released simultaneously with a grace period of a few hours. For example, both `torch==1.12.0` and `torchvision==0.13.0` were released on Jun 28, 2022 and both `torch==1.12.1` and `torchvision==0.13.1` were released on Aug 5, 2022. Can you explain why or what you are waiting for after a `torch` release?

> * Are the upgrades of `torch` version in `torchvision` truly backwards incompatible?

Likely, but not necessarily. Our `main` branch is compatible with the `master` branch from PyTorch core. Meaning, we get to use new features almost instantly, but on the flip side are affected by changes immediately as well.

And this is the only configuration that we test against. We already have a crazy CI matrix and supporting older PyTorch versions would be another multiplier there. And this ignores all the compatibility code that we would need to have internally.

> * Is it important for `torchvision` to always hard-pin a version?

Yes, for the reasons above.

> * Could `torchvision` support a range of `torch` versions? (like `torchmetrics` does)

No, for the reasons above. There is no theoretical restriction here, but that would mean a lot of additional work and costs for little gain.

**Comment by pmeier** [comment]
@AlexanderVanEck I'm going to close this due to inactivity. Feel free to reopen in case if you feel my answer above is not sufficient.

**Comment by AlexanderVanEck** [comment]
That's fine @pmeier . Thank you for the explanation. We'll pay attention to torchvision upgrading the pytorch version carefully going forward and will allow torchvision to dictate the version. 

👌 thanks again!
