### ISSUE TITLE
[MPS] Add support for torchvision::roi_align for MPS backend

### ISSUE THREAD

**Issue by chenxingqiang** [pytorch/vision#6986]
### 🚀 The feature, motivation and pitch

NotImplementedError: The operator 'torchvision::roi_align' is not currently implemented for the MPS device.

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by horsto** [comment]
it would be awesome if this could be implemented soon: +1 from my side!

**Comment by NicolasHug** [comment]
Thank you for adding it @qqaatw !
