### ISSUE TITLE
how can the code 'for _ in range(1, blocks)'  work?

### ISSUE THREAD

**Issue by yaodonggggggg** [pytorch/vision#701]
i'm new to CNN
in the vision/torchvision/models/resnet.py, line 144.
but the blocks' type is class,can you explain how can this code work?thank you

**Comment by fmassa** [comment]
Note that `blocks` in
https://github.com/facebookresearch/maskrcnn-benchmark/pull/69/files#diff-994ea1c02fd7e675924e1add66561d27
is actually a number, the result of `layers[0]` etc in
https://github.com/pytorch/vision/blob/71182bc1ea27652f9952f6d60d8b27e408fc940e/torchvision/models/resnet.py#L109
So the range works as expected.
