### ISSUE TITLE
Installing cpuonly torchvision nightly from conda will get old version of 0.13.1

### ISSUE THREAD

**Issue by YosuaMichael** [pytorch/vision#7022]
When I did:
```
conda install pytorch torchvision torchtext cpuonly -c pytorch-nightly
```

It will install the following torch related package:
```
  pytorch            pytorch-nightly/osx-arm64::pytorch-1.14.0.dev20221208-py3.8_0
  torchdata          pytorch-nightly/osx-arm64::torchdata-0.6.0.dev20221208-py38
  torchtext          pytorch-nightly/osx-arm64::torchtext-0.15.0.dev20221208-py38
  torchvision        pkgs/main/osx-arm64::torchvision-0.13.1-cpu_py38he5d19f7_0
```

Notice that the torchvision version is `0.13.1` which is very old and unexpected for nightly. We expect it to get nightly version.

I notice this issue because it break the unit test on torchmultimodal: https://github.com/facebookresearch/multimodal/actions/runs/3642456735/jobs/6161148527

cc @atalman @seemethere

**Comment by osalpekar** [comment]
I'm aware of this issue. It seems like uploading anaconda binaries from the torchvision repo fails with a rather unclear error. We are, however, able to upload using the same tooling from the test-infra repo. So today's nightlies should be uploaded to the `pytorch-nightly` channel, to unblock any jobs that depend on them. We'll figure out a concrete fix in the meantime.

**Comment by osalpekar** [comment]
The nightlies should be published and a concrete fix is pushed, which should prevent us from having a few day lag in conda nightlies going forward. Closing this issue.

**Comment by YosuaMichael** [comment]
Thanks for the fix @osalpekar !
