### ISSUE TITLE
EfficientNet documentation is (probably) misleading

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#7029]
_Originally reported in https://discuss.pytorch.org/t/error-while-setting-dropout-value-in-efficenet-pytroch-from-the-torch-vision-library/167970_

---

The docstring of `torchvision.models.efficientnet_b0` states:

https://github.com/pytorch/vision/blob/677fc939b21a8893f07db4c1f90482b648b6573f/torchvision/models/efficientnet.py#L772-L775

Looking at the class, the mentioned parameters are

https://github.com/pytorch/vision/blob/677fc939b21a8893f07db4c1f90482b648b6573f/torchvision/models/efficientnet.py#L248-L253

However, the creation function internally hardcodes the first three

https://github.com/pytorch/vision/blob/677fc939b21a8893f07db4c1f90482b648b6573f/torchvision/models/efficientnet.py#L782

leaving only `stochastic_depth_prob`, `num_classes`, and `norm_layer` configurable. Setting one of the others, e.g.

```python
torchvision_models.efficientnet_b0(dropout=0.5)
```

fails with

```
TypeError: _efficientnet() got multiple values for argument 'dropout'
```

I'm not familiar with the model, so I don't know whether the hardcoding is correct or not. If it is, we should fix our docstring to reflect that only some parameters can be configured.

cc @datumbox @ptrblck

**Comment by datumbox** [comment]
The dropout parameter was originally set to the value of the paper. Nevertheless there is no reason to impose such a limitation to the implementation. I've sent a PR to address it. Good spot Philip.
