### ISSUE TITLE
Cannot install any version of torchvision newer than 0.2.2 with for python 3.11

### ISSUE THREAD

**Issue by josiahcoad** [pytorch/vision#7038]
### 🐛 Describe the bug

when trying to install torchvision using pip or conda on my python 3.11, I can not install version newer than 0.2.2.

### Versions

Collecting environment information...
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.11.1 (main, Dec  8 2022, 00:48:11) [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-5.15.49-linuxkit-x86_64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.0
[pip3] torchvision==0.2.2.post3

**Comment by datumbox** [comment]
@josiahcoad The reason why this old version is installed is because we currently don't offer Python v3.11 binaries and because v0.2.2 in the last pure python version of TorchVision (no C++/CUDA kernels). 

@atalman @malfet Can you comment on when v3.11 binaries will become available?

**Comment by vadimkantorov** [comment]
IMO would be nice to delete 0.2.2 completely from conda/pip as it conceals dependency resolving issues: https://github.com/pytorch/vision/issues/7038

This problem happens almost every time a new python version gets released

**Comment by kohtala** [comment]
This duplicates #6842, but it was not resolved. There are now two releases without Python 3.11 support after Torch got 3.11 support.

**Comment by pmeier** [comment]
@vadimkantorov

> IMO would be nice to delete 0.2.2 (and other antique pure-python versions) completely from conda/pip as it conceals dependency resolving issues

Deleting is not an option, but we yanked the releases on PyPI. Meaning, you can still install them explicitly with `pip install torchvision==0.2.2`, but they are excluded from range installs like `pip install torchvision`.

@kohtala 

I've opened #7049 to track progress on adding Python 3.11 support. TL;DR: we are blocked by it not being available in the `defaults` conda channel.
