### ISSUE TITLE
Use `download_and_extract` in SBU dataset

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#7046]
As explained in https://github.com/pytorch/vision/pull/7039#pullrequestreview-1222790159, there is no need to manually extract the archive in the SBU dataset:

https://github.com/pytorch/vision/blob/0dceac025615a1c2df6ec1675d8f9d7757432a49/torchvision/datasets/sbu.py#L99-L103

We should replace that with

https://github.com/pytorch/vision/blob/0dceac025615a1c2df6ec1675d8f9d7757432a49/torchvision/datasets/utils.py#L433

Bonus points if you also check the other datasets, if there are more occurrences of this.

**Comment by deepsghimire** [comment]
I would like to contribute on this issue, is there anything I need to know or consider before starting?

**Comment by pmeier** [comment]
Hey @deepsghimire and thanks for your interest in contributing. 

>  is there anything I need to know or consider before starting?

No, this should be straight forward. Ping me on the PR for review.
