### ISSUE TITLE
functional to_tensor - permute instead of two tranposes

### ISSUE THREAD

**Issue by shaibagon** [pytorch/vision#705]
in the function [`to_tensor(pic)`][1], the loaded pic is transposed from H-W-C to C-H-W, which takes most of the running time.

My question:  
Wouldn't it be a bit more efficient to call `img.permute(0, 1, 2)` instead of calling `transpose` twice?

 [1]: https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional.py#L90

**Comment by surgan12** [comment]
@shaibagon thanks for pointing that out ,
But I ran some tests with

npimg = np.transpose(pic.numpy(), (1, 2, 0))
and
npimg = pic.permute(1, 2, 0).numpy()

and found out that the current implementation is faster .

**Comment by fmassa** [comment]
Hi,

Given that `transpose` is just changing metadata (sizes and strides), it is very fast and should not affect performance significantly.
But I wouldn't mind merging a PR that uses `permute` instead of transpose.

**Comment by shaibagon** [comment]
@surgan12  Thank you for your response and check!

@fmassa in terms of "code readability" I think a single `permute` is better than two `transpose`. However, if as @surgan12 reported `transpose` is faster, then I don't feel a change is justified.

Thank you for reviewing my question.
