### ISSUE TITLE
request: CUDA 11.8 builds

### ISSUE THREAD

**Issue by ConnorBaker** [pytorch/vision#7052]
### 🚀 The feature

CUDA 11.8 adds a number of new features, including support for the new Ada and Hopper architectures. [Much like `torch` has done](https://github.com/pytorch/pytorch/pull/90826), `torchvision` should provide binaries built with CUDA 11.8 to enable use of these new architectures.

### Motivation, pitch

Given the recent addition of CUDA 11.8 workflows to PyTorch (https://github.com/pytorch/pytorch/pull/90826), it would be nice to have matching binary releases for `torchvision`.

### Alternatives

Building from source?

### Additional context

I do not know the project goals, timelines, or the effort involved in adding a workflow to generate CUDA 11.8 builds, so please feel free to close as appropriate!

Thank you all for your work :)

**Comment by johnnynunez** [comment]
They are working on CUDA 12.0 too.
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html
