### ISSUE TITLE
Torchvision nightly version unavailable for Python 3.8 Linux from December 23

### ISSUE THREAD

**Issue by ajindal1** [pytorch/vision#7055]
### 🐛 Describe the bug

Torchvision nightly 0.15.0 had a Python 3.8 for linux released daily till 12/22, but has not been released since then. It can be checked on the pytorch nighly link(https://download.pytorch.org/whl/nightly/cu116/torch_nightly.html). Is there any plan to make this package available for Python 3.8 for Linux?

To Reproduce:
1. Go to https://download.pytorch.org/whl/nightly/cu116/torch_nightly.html
2. Search for torchvision-0.15.0.dev20221226
3. You will not find linux_x86_64.whl files for Python 3.8 (only Python 3.10 is available for Linux right now).

Expected behavior
These files should be available:
torchvision-0.15.0.dev20221226%2Bcu116-cp38-cp38-linux_x86_64.whl

### Versions

# Output from a slightly old image (20221213) for building nightly torch from source
Collecting environment information...
PyTorch version: 1.14.0.dev20221213+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.23.0
Libc version: glibc-2.31

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1070
GPU 1: NVIDIA GeForce GTX 1070

Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] pytorch-lightning==1.6.3
[pip3] torch==1.14.0.dev20221213+cu116
[pip3] torch-nebula==0.15.9
[pip3] torch-ort==1.14.0.dev20221213
[pip3] torchmetrics==0.7.1
[pip3] torchvision==0.15.0.dev20221213+cu116
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] mkl                       2021.4.0                 pypi_0    pypi
[conda] mkl-include               2021.4.0                 pypi_0    pypi
[conda] numpy                     1.22.2                   pypi_0    pypi
[conda] pytorch-lightning         1.6.3                    pypi_0    pypi
[conda] torch                     1.14.0.dev20221213+cu116          pypi_0    pypi
[conda] torch-nebula              0.15.9                   pypi_0    pypi
[conda] torch-ort                 1.14.0.dev20221213          pypi_0    pypi
[conda] torchmetrics              0.7.1                    pypi_0    pypi
[conda] torchvision               0.15.0.dev20221213+cu116          pypi_0    pypi

**Comment by pmeier** [comment]
Due to the [supply chain attack](https://pytorch.org/blog/compromised-nightly-dependency/), some wheels were removed from the indices and thus I can no longer tell if that was the case or not. However, starting from Dec 31, 2022 I see nightly wheels for all currently supported Python versions. For example:

- https://download.pytorch.org/whl/nightly/cu116/torchvision-0.15.0.dev20221231%2Bcu116-cp38-cp38-linux_x86_64.whl
- https://download.pytorch.org/whl/nightly/cu116/torchvision-0.15.0.dev20230103%2Bcu116-cp38-cp38-linux_x86_64.whl

Thus, I'm going to close this. Feel free to re-open in case I missed something.

**Comment by ajindal1** [comment]
@pmeier this issue is coming again, the torchvision nightly binaries for linux are not available for most of the days in the last week, even today. Can you look into this? I am specifically looking for this file: torchvision-0.16.0.dev20230504%2Bcu117-cp38-cp38-linux_x86_64.whl.

**Comment by pmeier** [comment]
We had a [massive CI outage](https://github.com/pytorch/pytorch/issues/100400) the last few days, that is fixed now. Nightly upload was affected and thus we are missing a few wheels on the index. `torchvision-0.16.0.dev20230504%2Bcu117-cp38-cp38-linux_x86_64.whl` is one of them. Here is what made it onto the index:

May 2:

[torchvision-0.16.0.dev20230502+cpu-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502%2Bcpu-cp310-cp310-linux_x86_64.whl)
[torchvision-0.16.0.dev20230502+cpu-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502%2Bcpu-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cpu-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502%2Bcpu-cp311-cp311-linux_x86_64.whl)
[torchvision-0.16.0.dev20230502+cpu-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502%2Bcpu-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cpu-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502%2Bcpu-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cpu-cp39-cp39-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502%2Bcpu-cp39-cp39-linux_x86_64.whl)
[torchvision-0.16.0.dev20230502+cpu-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502%2Bcpu-cp39-cp39-win_amd64.whl)
[torchvision-0.16.0.dev20230502-cp310-cp310-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502-cp310-cp310-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230502-cp310-cp310-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502-cp310-cp310-macosx_11_0_arm64.whl)
[torchvision-0.16.0.dev20230502-cp311-cp311-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502-cp311-cp311-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230502-cp311-cp311-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502-cp311-cp311-macosx_11_0_arm64.whl)
[torchvision-0.16.0.dev20230502-cp38-cp38-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502-cp38-cp38-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230502-cp38-cp38-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502-cp38-cp38-macosx_11_0_arm64.whl)
[torchvision-0.16.0.dev20230502-cp39-cp39-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502-cp39-cp39-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230502-cp39-cp39-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230502-cp39-cp39-macosx_11_0_arm64.whl)

[torchvision-0.16.0.dev20230502+cu117-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230502%2Bcu117-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cu117-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230502%2Bcu117-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cu117-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230502%2Bcu117-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cu117-cp39-cp39-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230502%2Bcu117-cp39-cp39-linux_x86_64.whl)
[torchvision-0.16.0.dev20230502+cu117-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230502%2Bcu117-cp39-cp39-win_amd64.whl)

[torchvision-0.16.0.dev20230502+cu118-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230502%2Bcu118-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cu118-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230502%2Bcu118-cp311-cp311-linux_x86_64.whl)
[torchvision-0.16.0.dev20230502+cu118-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230502%2Bcu118-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cu118-cp38-cp38-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230502%2Bcu118-cp38-cp38-linux_x86_64.whl)
[torchvision-0.16.0.dev20230502+cu118-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230502%2Bcu118-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cu118-cp39-cp39-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230502%2Bcu118-cp39-cp39-linux_x86_64.whl)
[torchvision-0.16.0.dev20230502+cu118-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230502%2Bcu118-cp39-cp39-win_amd64.whl)

[torchvision-0.16.0.dev20230502+cu121-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230502%2Bcu121-cp310-cp310-linux_x86_64.whl)
[torchvision-0.16.0.dev20230502+cu121-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230502%2Bcu121-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cu121-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230502%2Bcu121-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cu121-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230502%2Bcu121-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230502+cu121-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230502%2Bcu121-cp39-cp39-win_amd64.whl)

[torchvision-0.16.0.dev20230502+rocm5.3-cp38-cp38-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/rocm5.3/torchvision-0.16.0.dev20230502%2Brocm5.3-cp38-cp38-linux_x86_64.whl)

May 3:

[torchvision-0.16.0.dev20230503+cpu-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503%2Bcpu-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cpu-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503%2Bcpu-cp311-cp311-linux_x86_64.whl)
[torchvision-0.16.0.dev20230503+cpu-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503%2Bcpu-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cpu-cp38-cp38-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503%2Bcpu-cp38-cp38-linux_x86_64.whl)
[torchvision-0.16.0.dev20230503+cpu-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503%2Bcpu-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cpu-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503%2Bcpu-cp39-cp39-win_amd64.whl)
[torchvision-0.16.0.dev20230503-cp310-cp310-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503-cp310-cp310-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230503-cp310-cp310-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503-cp310-cp310-macosx_11_0_arm64.whl)
[torchvision-0.16.0.dev20230503-cp311-cp311-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503-cp311-cp311-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230503-cp311-cp311-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503-cp311-cp311-macosx_11_0_arm64.whl)
[torchvision-0.16.0.dev20230503-cp38-cp38-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503-cp38-cp38-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230503-cp38-cp38-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503-cp38-cp38-macosx_11_0_arm64.whl)
[torchvision-0.16.0.dev20230503-cp39-cp39-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503-cp39-cp39-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230503-cp39-cp39-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230503-cp39-cp39-macosx_11_0_arm64.whl)

[torchvision-0.16.0.dev20230503+cu117-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230503%2Bcu117-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cu117-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230503%2Bcu117-cp311-cp311-linux_x86_64.whl)
[torchvision-0.16.0.dev20230503+cu117-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230503%2Bcu117-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cu117-cp38-cp38-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230503%2Bcu117-cp38-cp38-linux_x86_64.whl)
[torchvision-0.16.0.dev20230503+cu117-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230503%2Bcu117-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cu117-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230503%2Bcu117-cp39-cp39-win_amd64.whl)

[torchvision-0.16.0.dev20230503+cu118-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230503%2Bcu118-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cu118-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230503%2Bcu118-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cu118-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230503%2Bcu118-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cu118-cp39-cp39-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230503%2Bcu118-cp39-cp39-linux_x86_64.whl)
[torchvision-0.16.0.dev20230503+cu118-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230503%2Bcu118-cp39-cp39-win_amd64.whl)

[torchvision-0.16.0.dev20230503+cu121-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230503%2Bcu121-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cu121-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230503%2Bcu121-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cu121-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230503%2Bcu121-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230503+cu121-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230503%2Bcu121-cp39-cp39-win_amd64.whl)

[torchvision-0.16.0.dev20230503+rocm5.3-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/rocm5.3/torchvision-0.16.0.dev20230503%2Brocm5.3-cp310-cp310-linux_x86_64.whl)
[torchvision-0.16.0.dev20230503+rocm5.3-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/rocm5.3/torchvision-0.16.0.dev20230503%2Brocm5.3-cp311-cp311-linux_x86_64.whl)
[torchvision-0.16.0.dev20230503+rocm5.3-cp39-cp39-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/rocm5.3/torchvision-0.16.0.dev20230503%2Brocm5.3-cp39-cp39-linux_x86_64.whl)

May 4:

[torchvision-0.16.0.dev20230504+cpu-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504%2Bcpu-cp310-cp310-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+cpu-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504%2Bcpu-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cpu-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504%2Bcpu-cp311-cp311-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+cpu-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504%2Bcpu-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cpu-cp38-cp38-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504%2Bcpu-cp38-cp38-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+cpu-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504%2Bcpu-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cpu-cp39-cp39-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504%2Bcpu-cp39-cp39-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+cpu-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504%2Bcpu-cp39-cp39-win_amd64.whl)
[torchvision-0.16.0.dev20230504-cp310-cp310-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504-cp310-cp310-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230504-cp310-cp310-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504-cp310-cp310-macosx_11_0_arm64.whl)
[torchvision-0.16.0.dev20230504-cp311-cp311-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504-cp311-cp311-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230504-cp311-cp311-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504-cp311-cp311-macosx_11_0_arm64.whl)
[torchvision-0.16.0.dev20230504-cp38-cp38-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504-cp38-cp38-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230504-cp38-cp38-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504-cp38-cp38-macosx_11_0_arm64.whl)
[torchvision-0.16.0.dev20230504-cp39-cp39-macosx_10_9_x86_64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504-cp39-cp39-macosx_10_9_x86_64.whl)
[torchvision-0.16.0.dev20230504-cp39-cp39-macosx_11_0_arm64.whl](https://download.pytorch.org/whl/nightly/cpu/torchvision-0.16.0.dev20230504-cp39-cp39-macosx_11_0_arm64.whl)

[torchvision-0.16.0.dev20230504+cu117-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230504%2Bcu117-cp310-cp310-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+cu117-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230504%2Bcu117-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cu117-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230504%2Bcu117-cp311-cp311-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+cu117-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230504%2Bcu117-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cu117-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230504%2Bcu117-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cu117-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu117/torchvision-0.16.0.dev20230504%2Bcu117-cp39-cp39-win_amd64.whl)

[torchvision-0.16.0.dev20230504+cu118-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230504%2Bcu118-cp310-cp310-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+cu118-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230504%2Bcu118-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cu118-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230504%2Bcu118-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cu118-cp38-cp38-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230504%2Bcu118-cp38-cp38-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+cu118-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230504%2Bcu118-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cu118-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu118/torchvision-0.16.0.dev20230504%2Bcu118-cp39-cp39-win_amd64.whl)

[torchvision-0.16.0.dev20230504+cu121-cp310-cp310-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230504%2Bcu121-cp310-cp310-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cu121-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230504%2Bcu121-cp311-cp311-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+cu121-cp311-cp311-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230504%2Bcu121-cp311-cp311-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cu121-cp38-cp38-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230504%2Bcu121-cp38-cp38-win_amd64.whl)
[torchvision-0.16.0.dev20230504+cu121-cp39-cp39-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230504%2Bcu121-cp39-cp39-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+cu121-cp39-cp39-win_amd64.whl](https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230504%2Bcu121-cp39-cp39-win_amd64.whl)

[torchvision-0.16.0.dev20230504+rocm5.3-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/rocm5.3/torchvision-0.16.0.dev20230504%2Brocm5.3-cp310-cp310-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+rocm5.3-cp311-cp311-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/rocm5.3/torchvision-0.16.0.dev20230504%2Brocm5.3-cp311-cp311-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+rocm5.3-cp38-cp38-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/rocm5.3/torchvision-0.16.0.dev20230504%2Brocm5.3-cp38-cp38-linux_x86_64.whl)
[torchvision-0.16.0.dev20230504+rocm5.3-cp39-cp39-linux_x86_64.whl](https://download.pytorch.org/whl/nightly/rocm5.3/torchvision-0.16.0.dev20230504%2Brocm5.3-cp39-cp39-linux_x86_64.whl)

Should be up and working again today. Please open another issue if it is not.
