### ISSUE TITLE
Improve typing of replace_stride_with_dilation for ResNet

### ISSUE THREAD

**Issue by sziem** [pytorch/vision#7061]
I believe the typing of 
`replace_stride_with_dilation: Optional[List[bool]] = None` 
should be changed to  
`replace_stride_with_dilation: Optional[Tuple[bool, bool, bool]] = None` 
for the ResNet class.
https://github.com/pytorch/vision/blob/46b7e27122deb011a3ff09720da9c3787757f7eb/torchvision/models/resnet.py#L175
(or potentially even a more general container)

Typing as tuple would support the runtime checks that check list length later.  The code mentions `tuple` here as well.
https://github.com/pytorch/vision/blob/46b7e27122deb011a3ff09720da9c3787757f7eb/torchvision/models/resnet.py#L186
```
        if replace_stride_with_dilation is None:
            # each element in the tuple indicates if we should replace
            # the 2x2 stride with a dilated convolution instead
            replace_stride_with_dilation = [False, False, False]
        if len(replace_stride_with_dilation) != 3:
            raise ValueError(
                "replace_stride_with_dilation should be None "
                f"or a 3-element tuple, got {replace_stride_with_dilation}"
            )
```

**Comment by oke-aditya** [comment]
This is probably due to incompatibility of JIT with `Union[Tuple[]]` objects and hence the Type Mismatch.
We need to ensure JIT compatibility and hence have opted for `List[]`. This is common across torchvision's codebase.

**Comment by sziem** [comment]
Sounds reasonable. Thought this might have been an overlook, but it seems this was an explicit decision.  Will close :)
