### ISSUE TITLE
Need CUDA 12 support

### ISSUE THREAD

**Issue by devillove084** [pytorch/vision#7066]
### 🚀 The feature

when I use the newest cuda12.0, torch vision is not supported.

### Motivation, pitch

need support cuda 12

**Comment by pmeier** [comment]
So far PyTorch core also doesn't support it although AFAIK it is being worked on. When that patch lands, we will follow suit.

**Comment by KohakuBlueleaf** [comment]
@pmeier I think pytorch nightly already support cuda 12.1
Will torchvision nightly also support cu121?

**Comment by pmeier** [comment]
After #7533 / April 29th we do have nightly builds for CUDA 12.1 now. For example:

https://download.pytorch.org/whl/nightly/cu121/torchvision-0.16.0.dev20230501%2Bcu121-cp311-cp311-linux_x86_64.whl

Installation instructions are not updated on the website yet, but you can get it with

```
pip3 install --pre torch torchvision --index-url=https://download.pytorch.org/whl/nightly/cu121
```
