### ISSUE TITLE
CircleCI workflows are broken due to missing permission

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#7067]
Currently, no CircleCI job is able to run. They fail with

```
Using SSH Config Dir '/home/circleci/.ssh'
git version 2.38.2
Cloning git repository
Cloning into '.'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

exit status 128
```

For example: https://app.circleci.com/pipelines/github/pytorch/vision/22512/workflows/5383f39a-13e8-4b22-a869-a2faa8e3e66a/jobs/1804282

This is most likely related to rotating our secrets in response to https://circleci.com/blog/january-4-2023-security-alert/.

cc @seemethere @malfet @atalman

**Comment by vmoens** [comment]
Had the same problem with RL
Here's what I did:
Go to circleci settings and deactive the ssh key:

Project settings > SSH Keys > Deploy Key
Deactivate it by clicking on the right cross.

Then from our meta OSS tool, re-activate circleci which should be deactivated.

Worked for me, hoping it does for you

cc @NicolasHug

**Comment by NicolasHug** [comment]
Thanks for the tips @vmoens 

@pmeier I just completed the steps above and re-triggered https://github.com/pytorch/vision/pull/5009. Let's see if it works

**Comment by NicolasHug** [comment]
Looks like it worked: https://app.circleci.com/pipelines/github/pytorch/vision/22514/workflows/2f117247-9236-4be3-a950-546c202d0bfd/jobs/1804317

(this one is red but at least it's running). 

Good to close @pmeier ?

**Comment by pmeier** [comment]
Yeah, the failure is related to #7060. So yes, I think we are good. Thanks @vmoens for the instructions and @NicolasHug for acting on them!
