### ISSUE TITLE
ToTensor deadlock in subprocess

### ISSUE THREAD

**Issue by Cathy0908** [pytorch/vision#7068]
### 🐛 Describe the bug

Describe the bug

I load a checkpoint in main process, then I start a subprocess to call `ToTensor` and the subprocess hang forever.

the following codes will reproduce my problem:

```python
import numpy as np
from PIL import Image
from multiprocessing import Process
import torchvision
from torchvision.transforms import ToTensor

a = np.ones((224, 224, 3), dtype=np.uint8)
a = Image.fromarray(a, mode='RGB')
model = torchvision.models.resnet50(True)
p = Process(target=ToTensor(), args=(a,))
p.start()
p.join()
print('end')
```

### Versions

torch version: 1.12.0
torchvision version: 0.13.0

**Comment by NicolasHug** [comment]
I'm unable to reproduce your issue @Cathy0908 . The script properly terminates on my env. Could you please share your env's details, as requested on the issue template?


```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by Cathy0908** [comment]
load a checkpoint in main process, and start a subprocess to call `.permute((2, 0, 1)).contiguous()` and the subprocess hang forever.


```python
import numpy as np
from multiprocessing import Process
import torchvision
import torch


def f():
    a = np.ones((224, 224, 3), dtype=np.uint8)
    img = torch.from_numpy(a)
    img = img.permute((2, 0, 1)).contiguous()
    return img


model = torchvision.models.resnet50(True)
p = Process(target=f)
p.start()
p.join()

print('====end====')
```

**Comment by NicolasHug** [comment]
Thanks for the details @Cathy0908 . From your last snippet, this issue seems unrelated to torchvision as it happens even when it's not imported. I'd recommend 1) checking if you observe the same issue without `torch` =, e.g. `def f(): print("Hello")` and 2) report the issue in https://github.com/pytorch/pytorch/issues if the issue seems to be pytorch-specific
