### ISSUE TITLE
Make hardcoded variables in ResNet Implementation variables.

### ISSUE THREAD

**Issue by CompRhys** [pytorch/vision#7115]
### 🚀 The feature, motivation and pitch

In the Pytorch ResNet there are several hard coded parameters, most importantly `self.inplanes = 64` allowing us to make this a variable would allow for the model to be reduced in size significantly and therefore used in toy examples/testing without such long weight times

**Comment by NicolasHug** [comment]
Thanks for the feature request @CompRhys .

We try to avoid adding new parameters to those classes too liberally, as it can end up in bloated APIs and increases maintenance cost. See e.g. this issue with a similar problem and conclusion https://github.com/pytorch/vision/issues/4297.

In most cases, user needs can be addressed through a little bit of surgery / tweaks. I think the snippet below should cover your use-case by overriding the `inplanes` attribute through a `@property` in a custom child class

```py
class ResNet:

    def __init__(self):
        self.inplanes = 0
        print("In ResNet,", self.inplanes)

class MyResNet(ResNet):

    def __init__(self, inplanes=1):
        super().__init__()
        self._inplanes = inplanes
        # self.inplanes = inplanes
        print("In MyResNet,", self.inplanes)
    
    @property
    def inplanes(self):
        return self._inplanes
    
    @inplanes.setter
    def inplanes(self, v):
        pass

myresnet = MyResNet()
print(myresnet.inplanes)
```

Hope this helps!

**Comment by CompRhys** [comment]
closing based on decision not to add more arguments.
