### ISSUE TITLE
[feature proposal] Adding Gaussian Noise Augmentation to Transforms 

### ISSUE THREAD

**Issue by surgan12** [pytorch/vision#712]
cc: @fmassa

**Comment by fmassa** [comment]
Hi,

Does this mean adding a gaussian noise to the image, like `x + torch.randn_like(x)`?

**Comment by surgan12** [comment]
yep !! @fmassa

**Comment by fmassa** [comment]
Let me think a bit more about this, as this can be achieved in a one-lines with `LambdaTransform`.

**Comment by surgan12** [comment]
Yeah this can be done using lambda transforms, like
``i = torch.zeros(bs,channels, dim1, dim2).data.normal_(mean, std)
But to make things more easy for users , i thought it is good to add this as a part of primitive transforms.

**Comment by surgan12** [comment]
@fmassa what's your take should we do this ?

**Comment by iArunava** [comment]
`t = T.Compose([T.Lambda(lambda x : x + torch.randn_like(x))])`
this works as expected. I think its safe to close this for now and later revisit if requested. Right?

**Comment by dlmacedo** [comment]
I believe randn_like generates uniform distribution... Not Guassian distribution...

**Comment by fmassa** [comment]
@dlmacedo `randn_like` is supposed to generate a gaussian distribution, as it calls `randn`. If that's not the case, it's a bug in PyTorch
