### ISSUE TITLE
Discard  py3.7  tests from CI

### ISSUE THREAD

**Issue by cyyever** [pytorch/vision#7137]
### 🐛 Describe the bug

Recently PyTorch master is dropping py3.7 support. This behaviour causes many failures in CI.

### Versions

Github main

cc @seemethere

**Comment by pmeier** [comment]
We are working on that in #7110. @cyyever Could you elaborate how still supporting 3.7 although core doesn't creates any problems in CI?

**Comment by cyyever** [comment]
The CI tries to fetch torch 2.0 for py3.7 but it fails. I think the quick solution is to disable py3.7 tests temporarily.

**Comment by pmeier** [comment]
Sorry, I think I misunderstood. Do you mean that it causes failures in our (`torchvision`) or PyTorch core CI?

**Comment by cyyever** [comment]
@pmeier  The core library changes cause torchvision tests to fail.
