### ISSUE TITLE
wrong label order when reading images from folders using 'ImageFolder' and can't get correct labels

### ISSUE THREAD

**Issue by JieAI** [pytorch/vision#714]
When I try to load images from folders using datasets.ImagesFolder(), i find the lables' order is not correct as shown in the folder. For example, I have different kinds of images in folders named from 1 to 100, if I use above function to read images and get corresponding labels, of course I will get the images and labels, but the labels for images will become 1, 10, 100, 11, 12, 13 which is not right for corresponding image. The right order should be 1, 2, 3, 4, 5 for corresponding images.
Hope I state the problem clearly and wish you can fix this bug. Thanks.

**Comment by fmassa** [comment]
The label names are sorted as strings.
This means that `['1', '10', '2']` is the correct sorting order according to Python.
You should instead use `class_to_idx` and `classes` to go back and forth between the two representations.
