### ISSUE TITLE
[Feedback] Needs to update Readme for /vision/examples/cpp/hello_world/

### ISSUE THREAD

**Issue by SLchowis** [pytorch/vision#7169]
In the Readme file, nothing mentioned about 
1. Executing the python script to get AI model.
2. Moving AI model (.pt file) to the build folder

Without these steps, if any one just follow the existing readme, they will get "error loading the model"

**Comment by NicolasHug** [comment]
Thanks for the report @SLchowis , indeed these crucial steps seem to be missing. Would you like to submit a PR to update our README instructions?

**Comment by ggold7046** [comment]
Hello,  if you could provide me with the script and the code I can try to update the readme.rst file. 
where should I put those steps ? 
After this one ?  ----> `From source:`
.........

**Comment by ggold7046** [comment]
Hello, if you could provide me with the script and the code I can try to update the readme.rst file.
where should I put those steps ?
After this one ? ----> `from within the build directory, run the following commands:`
.........

**Comment by NicolasHug** [comment]
Closed by https://github.com/pytorch/vision/pull/7963
