### ISSUE TITLE
cmake workflows on Windows fail due to Python 3.7 dependency

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#7180]
CPU: https://app.circleci.com/pipelines/github/pytorch/vision/22939/workflows/787176d2-d6fb-4482-876e-35a6078d00f8/jobs/1819932
GPU: https://app.circleci.com/pipelines/github/pytorch/vision/22939/workflows/787176d2-d6fb-4482-876e-35a6078d00f8/jobs/1819929

This was likely forgotten in #7110.

cc @seemethere @atalman @malfet

**Comment by pmeier** [comment]
It seems we aren't using a custom conda env at all here, but basically rely on whatever is installed on the images:

https://github.com/pytorch/vision/blob/85983a57e8986cf4a9afc34704bbacb9e6206ec9/.circleci/config.yml.in#L9-L20

Since we already have something extra for Windows

https://github.com/pytorch/vision/blob/85983a57e8986cf4a9afc34704bbacb9e6206ec9/packaging/build_cmake.sh#L23-L26

I've tried to explicitly install Python 3.8 there in #7182. However that leads to other issues.

**Comment by malfet** [comment]
Hmm, imo we should fix the workflow or disable it, but keeping it broken does not make sense to me.

**Comment by pmeier** [comment]
TBH, I'm not really sure what the `cmake` workflows even do. And I don't think we even some documentation of that. It should be related to a C++ only build, since we run 

https://github.com/pytorch/vision/blob/9b233d41ad71de768a1714eaeb2ebd4f893688e5/packaging/build_cmake.sh#L109-L111

but in the light of #7106, I'm not sure that is even doing something useful.
