### ISSUE TITLE
Remove usage of scipy.stats.binom_test

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#7201]
It's deprecated. Not super urgent at we only rely on it in the tests.

```
  /work/test/test_transforms.py:1437: DeprecationWarning: 'binom_test' is deprecated in favour of 'binomtest' from version 1.7.0 and will be removed in Scipy 1.12.0.
```

(Also noticed this warning)

```
  /work/ci_env/lib/python3.8/site-packages/scipy/stats/_discrete_distns.py:77: RuntimeWarning: divide by zero encountered in _binom_pdf
```

cc @pmeier

**Comment by pmeier** [comment]
- https://github.com/pytorch/vision/blob/5ea8e013eb1bbfcf321c5c55113a5fa13840dd6c/test/test_ops.py#L1643
- https://github.com/pytorch/vision/blob/5ea8e013eb1bbfcf321c5c55113a5fa13840dd6c/test/test_transforms.py#L1437
- https://github.com/pytorch/vision/blob/5ea8e013eb1bbfcf321c5c55113a5fa13840dd6c/test/test_transforms.py#L1843

**Comment by ggold7046** [comment]
Hi @pmeier, how to proceed on this ?

**Comment by pmeier** [comment]
As the warning implies, the function `scipy.stats.binom_test` is deprecated and scheduled for removal in `scipy==1.12`. Current version is `scipy==1.10` so we have a little time, but we should act on it nonetheless. 

The warning also gives you the upgrade instructions: you only need to replace `binom_test` with `binomtest`.
