### ISSUE TITLE
Revert removal and deprecation of int values for interpolation?

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#7205]
Initially, `torchvision` supported `int`'s for the `interpolation` (or their former equivalent) arguments on our transforms. They were usually not passed directly, but rather as part of the Pillow constants, like `PIL.Image.BILINEAR`.

https://github.com/pytorch/vision/pull/2952#pullrequestreview-524098958 proposed to decouple our transforms from Pillow and this was achieved through the `torchvision.transforms.InterpolationMode` enum introduced later in the same PR. Although, the new enum was used as default value from then on, `int`'s were still supported. Still, the language around them somewhat "soft-deprecated" them:

https://github.com/pytorch/vision/blob/9b5a3fecc72434dbd65148723efe54b28b9728c9/torchvision/transforms/transforms.py#L301

With the release of `Pillow==9.1.0`, they [deprecated the `int` constants](https://pillow.readthedocs.io/en/stable/releasenotes/9.1.0.html#constants) and switched to their own enums as well. In response we introduced support for these enums as well in #5898 and deprecated `int`s in #5974.

Our deprecation was scheduled for removal in the upcoming 0.15 release and was acted upon in #7176.

However, there are two factors we didn't consider there:

1. @NicolasHug pointed out that using ints is still widespread for Meta internal users
2. `Pillow` seemed to have [walked back on their deprecation](https://pillow.readthedocs.io/en/stable/releasenotes/9.4.0.html#constants) in `9.4.0` as well:

   > In Pillow 9.1.0, the following constants were deprecated. That has been reversed and these constants will now remain available.

   This follows python-pillow/Pillow#6537 which acknowledges that the change is too disruptive. However, since removing the enums now would also be BC breaking (python-pillow/Pillow#6684), they just reinstated the former int constants in python-pillow/Pillow@bcdb208fe2365b75c8d87d29783b9cc9f8cb683b

Given that our deprecation just followed `Pillow`'s, I think we can also revert the removal and deprecation. Between `>= 9.1.0` and `< 9.4.0`, `Pillow` never dropped support for `int`'s. Thus, the only issues our users could run into when using `int`'s on that versions is that `Pillow` will emit a deprecation warning. Our default values use our enum anyway

https://github.com/pytorch/vision/blob/539c6e290c172d173f986874d57be857235fbc6a/torchvision/transforms/transforms.py#L315

If we go that route note that we also need add support for `int`'s to our prototype transforms. They don't have that, since we designed with the scheduled removal in mind.

Thoughts?

cc @vfdev-5

**Comment by NicolasHug** [comment]
Thanks for digging the history here Philip.
I'm happy to go for the least disruptive change and put back support for PIL.Image int constants. Since they're here to stay (according to the issue/PR on the PIL repo), we can also remove our warning encouraging users to use our own `InterpolationMode`.

> If we go that route note that we also need add support for int's to our prototype transforms

Good point - although considering how tight our deadline is, I would be fine with leaving that for *after* the release if we have to (if we can do it before, it's even better, but not a blocker)
