### ISSUE TITLE
where can i download  /datasets01/imagenet_full_size/061417/    for train_quantization

### ISSUE THREAD

**Issue by cqray1990** [pytorch/vision#7213]
### 🐛 Describe the bug

where cani download  /datasets01/imagenet_full_size/061417/    for train_quantization

### Versions

where cani download  /datasets01/imagenet_full_size/061417/    for train_quantization

**Comment by NicolasHug** [comment]
Hi @cqray1990 , these defaults on our training references are set to suit our training cluster... they're not necessarily relevant for all users. This folder contains the 1K ImagetNet dataset (1,281,167 training images) which you can download from here https://www.image-net.org/download.php
