### ISSUE TITLE
Modifying densenet weight during transfer learning

### ISSUE THREAD

**Issue by devTeaa** [pytorch/vision#722]
The code on densenet model is copying all weight instead of just the required one when someone tries to do transfer learning and intending to adjust how many layers to freeze, I've found the solution which looks a bit hacks and it ran after loading the model, I've submitted a PR #721  that just allow future work to just modify it however they want without searching or debugging it, it's also throwing a deprecated warning when loading the model

**Comment by fmassa** [comment]
Hi,

As I discussed in #721, I think that it's best to keep it like that for now, and let the users write their own function if they want only parts of the model to be loaded.

I'm closing this issue, but let me know if you disagree
