### ISSUE TITLE
Improve ImageNet documentation

### ISSUE THREAD

**Issue by cemde** [pytorch/vision#7300]
### 📚 The doc issue

The [ImageNet documentation](https://pytorch.org/vision/stable/generated/torchvision.datasets.ImageNet.html#torchvision.datasets.ImageNet)  is quite short and skips a lot of steps on how to use it for the first time. A better description on how to use it would be nice.

 As far as I understand 
1. one has to download `...train.tar`, `...val.tar` and `...test.tar` files
2. one has to download the `task 1 and 2 devkit`
3. one has to unpack these into `train`, `val` and `test` folders respectively.
4. one has to use some shell script to reorganise the folder structure into `val/class_tag/image.jpeg`. For val set or for all sets?

### Suggest a potential alternative/fix

Add instructions:
- Visit [https://www.image-net.org/](https://www.image-net.org/) and download the 2012 train, test and val images for Task 1 and 2.
- In your `/data/ImageNet` folder create subfolders `train`, `val` and `test`.
- Unpack the image `.tar` files for each split.
- Copy the following [link here](link here) shell script into your train, val and test folders, respectively and run them. This will reorganize these folders to be compatible with `torchvision.dataset.ImageFolder` which bases the `ImageNet` class.
- 

cc @pmeier

**Comment by pmeier** [comment]
Thanks @cemde for the suggestions. I agree documentation can be improved. However, I don't think you'll have to do any manual work after the download. As long as the archives you downloaded are in the root folder that you pass to the constructor of the dataset, you should be good. Before we hit the constructor of `ImageFolder`, we call 

https://github.com/pytorch/vision/blob/928b05cad36eadb13e169f03028767c8bcd1f21d/torchvision/datasets/imagenet.py#L57-L65

Meaning all the unpacking and restructuring will be handled for you.

So I guess, the documentation should be something along the lines of

> Download the archives manually and place them in the root directory

Do you want to send a PR for that?

**Comment by MrinalTyagi** [comment]
I would be happy to contribute to this issue incase it is not assigned to anyone :)

**Comment by pmeier** [comment]
Go for it!

**Comment by puhuk** [comment]
@MrinalTyagi Are you going on this issue ? If not, can I take this :)

**Comment by pmeier** [comment]
So far no PR was send. Go ahead if you like.

**Comment by pmeier** [comment]
Fixed in #7503.
