### ISSUE TITLE
BounxingBoxes or BoundingBox

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#7313]
Opening so we don't forget: we should align `ClampBoundingBox` and `Sanitize BoundingBoxes` to both use either plural or singular

**Comment by mpearce25** [comment]
Created a PR that 

> Standardize around singular "Box" as SanitizeBoundingBoxes was the only plural usage while the singular is used for all other classes. 

lmk if it looks good

**Comment by NicolasHug** [comment]
There's nothing that prevents `SanitizeBoundingBoxes` to work on a singular `(4,)` right? We just haven't implemended yet?

**Comment by pmeier** [comment]
> There's nothing that prevents `SanitizeBoundingBoxes` to work on a singular `(4,)` right?

How would the shape look like if you sanitize a `(4,)` bounding box? If you remove all bounding boxes from `(N, 4)`, it becomes `(0, 4)`.

**Comment by NicolasHug** [comment]
Empty tensor?

```
[ins] In [2]: torch.tensor([]).shape
Out[2]: torch.Size([0])
```

**Comment by vfdev-5** [comment]
I would prefer to see everywhere `BoundingBoxes` so that there is no confusion in names

**Comment by NicolasHug** [comment]
We synced offline and keeping singular seems to be OK with everyone. This was addressed in https://github.com/pytorch/vision/issues/7313, thanks for your contribution @mpearce25
