### ISSUE TITLE
RAFT predicts nans for input resolution < 128 x 128

### ISSUE THREAD

**Issue by ChristophReich1996** [pytorch/vision#7338]
### 🐛 Describe the bug

Hi torchvision community,

When running RAFT (small and large) with a resolution smaller than 128 x 128, the predicted flow is nan. This issue occurs both with pre-trained weights and also with random initialization. The error can be reproduced by:

```python
import torch
from torchvision.models.optical_flow import raft_large, raft_small, Raft_Large_Weights, Raft_Small_Weights


def main() -> None:
    # Init models
    raft_large_pre_trained = raft_large(Raft_Large_Weights.C_T_SKHT_K_V1)
    raft_large_random = raft_large()
    raft_small_pre_trained = raft_small(Raft_Small_Weights.C_T_V2)
    raft_small_random = raft_small()
    # Models into eval mode (train also leads to nans)
    raft_large_pre_trained.eval()
    raft_large_random.eval()
    raft_small_pre_trained.eval()
    raft_small_random.eval()
    # Test different resolutions smaller than 128 x 128
    for resolution in [15 * 8, 14 * 8, 13 * 8, 12 * 8, 11 * 8]:
        # Test if output is nan
        input = torch.ones(7, 3, resolution, resolution)
        print(torch.isnan(raft_large_pre_trained(input, input)[-1]).sum())
        print(torch.isnan(raft_large_random(input, input)[-1]).sum())
        print(torch.isnan(raft_small_pre_trained(input, input)[-1]).sum())
        print(torch.isnan(raft_small_random(input, input)[-1]).sum())


if __name__ == "__main__":
    main()
```

This issue occurs since the shape of the correlation volume is `[1350, 1, 1, 1]`. Thus, when computing [grid_sample](https://github.com/pytorch/vision/blob/01ef0a68b6ec00452391251fc16c38e58b92bf07/torchvision/models/optical_flow/_utils.py#L13) a division by zero occurs. I guess, the RAFT architecture does not support resolutions below 128 x 128. Should I open a pull request, checking that the input is 128 x 128 or bigger?

### Versions

PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.14.0-1055-oem-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           140
Model name:                      11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
Stepping:                        1
CPU MHz:                         1800.000
CPU max MHz:                     4800.0000
CPU min MHz:                     400.0000
BogoMIPS:                        3609.60
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       128 KiB
L2 cache:                        5 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l2 invpcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves split_lock_detect dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid movdiri movdir64b fsrm avx512_vp2intersect md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   2.0                           0    pytorch
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] pytorch                   1.12.0              py3.9_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchaudio                0.12.0                 py39_cpu    pytorch
[conda] torchvision               0.13.0                 py39_cpu    pytorch

**Comment by oke-aditya** [comment]
Although I'm not clearly able to recall 6-7 months back I remember discussing something like this with @NicolasHug that the input resolution has to be divisible by 8. And the minimum size has to be 128 (or 64?). 

It's a valid point. I think some other models as well assume input sizes to be divisible by 4. Not sure of this though. 

It would be nice to add this to docs.

**Comment by NicolasHug** [comment]
Thanks for the report @ChristophReich1996 ,

> It would be nice to add this to docs.

It is! :) Although I would agree it's not super obvious to find as it's not directly documented on the docstring and rather on the weights

https://pytorch.org/vision/main/models/generated/torchvision.models.optical_flow.raft_large.html#torchvision.models.optical_flow.Raft_Large_Weights

**Comment by ChristophReich1996** [comment]
I definitely overlooked this ;)

**Comment by ChristophReich1996** [comment]
There is also a comment in the RAFT test also describing the issue
https://github.com/pytorch/vision/blob/b030e9363eab6089cc580725ee703cf2f01f3765/test/test_models.py#L1032-L1035

**Comment by DaWelter** [comment]
Was about to report the same.
I had to debug the raft code to find the issue.
Would be nice to have `assert w>1 and h>1` added to `grid_sample` - or whatever precondition check you find appropriate @NicolasHug . Anyhow, that'd make it pretty obvious what's wrong.

**Comment by NicolasHug** [comment]
Closed by https://github.com/pytorch/vision/pull/7339, thanks all for the reports
