### ISSUE TITLE
setup.py install failing for layers branch 

### ISSUE THREAD

**Issue by YotamNitzan** [pytorch/vision#734]
Hi, 
Trying to install the layers branch from source, in order to use the ROI* features, but installation fails.
(Working on Windows 10 without GPU)

The install script can't find the cuda installation path which I guess is fair since it's not installed. However, I understand torchvision is available for CPU machines and the installing master branch from source does succeed. 

Any help will be appreciated, Thanks !

**Comment by fmassa** [comment]
Hi,

I'd recommend for now [installing `maskrcnn-benchmark`](https://github.com/facebookresearch/maskrcnn-benchmark/), which contains all the layers in the `layers` branch here, but are a bit more maintained.

We will be making C++ layers a first-class citizen in torchvision with its next major release.
