### ISSUE TITLE
Add base class for all transforms

### ISSUE THREAD

**Issue by ValerianRey** [pytorch/vision#7360]
### 🚀 The feature

Would it make sense to have a base class (maybe called `Transform`) for all transforms?

### Motivation, pitch

This way, when we have a parameter `transform` in a function, we could give it this base class as a type hint. For instance, with the hypothetical `Transform` base class, we could have the following type hints in a function that could take any kind of transform as parameter.

```python
def apply_transform(input: Tensor, transform: Transform):
    ...
```

**Comment by pmeier** [comment]
Hey @ValerianRey. We wouldn't do that just for the type hint, but only if the transforms actually share some behavior. Luckily, this is the case for the upcoming `torchvision.transforms.v2` release:

https://github.com/pytorch/vision/blob/af048198f87da11f344ffba37d6962aa78b36218/torchvision/transforms/v2/_transform.py#L15

In the meantime you might use `torch.nn.Module` which applies to most transforms or the generic `typing.Callable`. 

If you want to use the tensor backend, you could refine the type hint to `Callable[[torch.Tensor], torch.Tensor]`. This works for most transforms with noteable exceptions being the type conversions transforms. Finally, you can also alias this type to enable a syntax as you proposed above:

```python
from typing import Callable

from torch import Tensor

Transform = Callable[[Tensor], Tensor]

def apply_transform(input: Tensor, transform: Transform):
    ...
```

As such, I'm closing this. Feel free to re-open in case my response is not sufficient for your use case.

**Comment by ValerianRey** [comment]
Nice I'm glad to see that it's coming in a future version!
Also thanks for the time you used to give me the type hint I needed, I appreciate that!
