### ISSUE TITLE
Windows GPU job failing on model tests due to CUDA OOM issue

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#7380]
Our [Windows GPU test jobs](https://app.circleci.com/pipelines/github/pytorch/vision/23785/workflows/7ec73fe8-a6d2-4040-970a-7146affaa67a/jobs/1847331/tests) are failing a bunch of model tests with OOM:

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 14.85 GiB total capacity; 13.57 GiB already allocated; 46.25 MiB free; 13.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

The resource class is `windows.gpu.nvidia.medium` and it's the only one available for Windows, so we can't increase the instance size to fix those. Might have to manually free some memory, IDK.

cc @pmeier @seemethere

**Comment by pmeier** [comment]
Hopefully, we can move the Windows unittest jobs from CircleCI to GHA soon and circumvent this entirely.
