### ISSUE TITLE
Unknown builtin op: torchvision::roi_align.

### ISSUE THREAD

**Issue by SUSIEE01** [pytorch/vision#7389]
### 🐛 Describe the bug

I’am trying to use `torch.jit.load` to load a model but meet an error as follow.
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_11836\3154094266.py in <module>
      1 # Load torchscript version of model
----> 2 model = torch.jit.load(torchscript_path)

c:\Users\SUSIE\Anaconda3\envs\osr\lib\site-packages\torch\jit\_serialization.py in load(f, map_location, _extra_files)
    160     cu = torch._C.CompilationUnit()
    161     if isinstance(f, str) or isinstance(f, pathlib.Path):
--> 162         cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
    163     else:
    164         cpp_module = torch._C.import_ir_module_from_buffer(

RuntimeError: 
Unknown builtin op: torchvision::roi_align.
Could not find any similar ops to torchvision::roi_align. This op may not exist or may not be currently supported in TorchScript.
:
  File "code/__torch__/torchvision/ops/roi_align.py", line 18
  else:
    rois = unchecked_cast(Tensor, boxes)
  _6 = ops.torchvision.roi_align(input, rois, spatial_scale, output_size[0], output_size[1], sampling_ratio, aligned)
       ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  return _6
'roi_align' is being compiled since it was called from '_multiscale_roi_align'
Serialized   File "code/__torch__/torchvision/ops/poolers.py", line 128
  _30 = "scales and mapper should not be None"
  _31 = __torch__.torchvision.ops.poolers._convert_to_roi_format
  _32 = __torch__.torchvision.ops.roi_align.roi_align
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  _33 = "This Python function is annotated to be ignored and cannot be run"
  _34 = uninitialized(Tensor)
'_multiscale_roi_align' is being compiled since it was called from 'MultiScaleRoIAlign.forward'
Serialized   File "code/__torch__/torchvision/ops/poolers.py", line 19
    _0 = __torch__.torchvision.ops.poolers._filter_input
    _1 = __torch__.torchvision.ops.poolers._setup_scales
    _2 = __torch__.torchvision.ops.poolers._multiscale_roi_align
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    featmap_names = self.featmap_names
    x_filtered = _0(x, featmap_names, )
```

### Versions

Collecting environment information...
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 家庭中文版
GCC version: (tdm64-1) 9.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.7.13 (default, Oct 19 2022, 10:19:43) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to:
GPU models and configuration: GPU 0: NVIDIA GeForce MX150
Nvidia driver version: 516.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=1600
DeviceID=CPU0
Family=205
L2CacheSize=1024
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=1800
Name=Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] pytorch-metric-learning==1.5.1
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h59b6b97_2
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py37h2bbff1b_0
[conda] mkl_fft                   1.3.1            py37h277e83a_0
[conda] mkl_random                1.2.2            py37hf11a4ad_0
[conda] numpy                     1.21.5           py37h7a0a035_3
[conda] numpy-base                1.21.5           py37hca35cd5_3
[conda] pytorch                   1.12.0          py3.7_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-metric-learning   1.5.1                     <pip>
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.0               py37_cu113    pytorch
[conda] torchvision               0.13.0               py37_cu113    pytorch

**Comment by NicolasHug** [comment]
Sorry @SUSIEE01 it's hard to help without knowing the code you tried. The `roi_align` op is jit-scriptable so I assume this is a setup issue on your side. I'll close the issue, feel free to reopen if the problem persists
