### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by LIMr1209** [pytorch/vision#740]
``python
from io import BytesIO
from torchvision import transforms as T
import requests
from PIL import Image
import numpy as np

normalize = T.Normalize(mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])

def data_handle():
    transforms = T.Compose([
        T.Resize(224),
        T.CenterCrop(224),
    ])
    return transforms

def image_loader(url=None, image=None):
    if url:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36'}
        try:
            response = requests.get(url, headers=headers, timeout=5)
        except:
            response = None
        image = Image.open(BytesIO(response.content)).convert('RGB')
    elif image:
        image = Image.open(BytesIO(image)).convert('RGB')
    img1_tensor = data_handle()(image)
    img1_tensor = np.array(img1_tensor,dtype='float32')
    data = np.random.randint(0, 255, size=810240)
    img = data.reshape(422, 640, 3)
    print(img.dtype)
    print(img1_tensor.dtype)
    img1_tensor = T.ToTensor()(img1_tensor)  # 转换成tensor
    # img1_tensor = normalize(img1_tensor)
    img_tensor = T.ToTensor()(img)
    print(img_tensor.dtype)
    print(img1_tensor.dtype)
    print('1')
    #  normalize(img_tensor)
    print('2')
    normalize(img1_tensor)
    # return img_tensor

**Comment by LIMr1209** [comment]
执行到 normalize(img1_tensor) 或者 normalize(img_tensor)  coredump

**Comment by fmassa** [comment]
Hi,

We don't have any C++ code in torchvision at the moment, so the coredump should come frmo a different library. Debugging with GPU or identifying precisely which line gives the core dump would be very helpful in debugging.

I'm closing this for now, but if you have a precise line where the dump happens (and it is inside torchvision) please feel free to re-open the issue.

Thanks!
