### ISSUE TITLE
for RGBA images

### ISSUE THREAD

**Issue by dimrecon** [pytorch/vision#741]
what modifications are to be done in the code for training with RGBA (4 channel ) images. Does the inchannels to be changed from 3 to 4 and the number of classes? Kindly help

**Comment by surgan12** [comment]
Can you be more specific in the problem you are facing .

**Comment by dimrecon** [comment]
ya... my input images are of RGBA format and want to classify this using resnet50 . if i try with pretrained resnet50, wont it consider only the first 3 channels as it was previously trained with RGB images only. so i trained with resnet50 from scratch and changed the no of filters to 4 from 3 and no of classes according to my data. But how can i make this changes when i call resnet from torchvision?

**Comment by surgan12** [comment]
https://github.com/pytorch/vision/blob/ee5b4e82fe25bd4a0f0ab22ccdbcfc3de1b3b265/torchvision/models/resnet.py#L104
Refer to this line .
You can copy the architecture and put num_channels as 4 .

**Comment by dimrecon** [comment]
ya.. i did that and started training a few hrs back but my doubt is if i
want to use a pretrained version , where i have to change?

**Comment by fmassa** [comment]
If you want to use a pre-trained version, you'll need to do some model surgery.
For example, by doing something like
```python
model = models.resnet18(pretrained=True)

with torch.no_grad():
    w = model.conv1.weight
    w = torch.cat([w, torch.full((64, 1, 7, 7), 0.01)], dim=1)
    model.conv1.weight = nn.Parameter(w)
```

and you should choose the way you'd fill the extra lines of the code.

I'm closing the issue, but let me know if you have further questions

**Comment by dimrecon** [comment]
hi,

i changed the no of channels in init function of resnet and trained with pretrained = false and the model got saved. Training and validation works here. But when it comes to testing am facing errors here:

RuntimeError: Error(s) in loading state_dict for ResNet:
	size mismatch for conv1.weight: copying a param with shape torch.Size([64, 3, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 4, 7, 7]).

Could u pls tell what might be the issue here?

**Comment by dimrecon** [comment]
for phase in ['test']:
    print("model")
    model = models.resnet50(pretrained=False)
    model.load_state_dict(torch.load('resnet50_4c.pt'))
    model.eval()

**Comment by dimrecon** [comment]
Cud u pls help urgently

**Comment by fmassa** [comment]
@dimrecon I replied in #751 

Also, in those cases, you might be better asking in the forums
