### ISSUE TITLE
Would be great to support the new PyTorch 2

### ISSUE THREAD

**Issue by Hongbo-Miao** [pytorch/vision#7421]
### 🚀 The feature

It would be great to support the new PyTorch 2 😃

### Motivation, pitch

I tried to upgrade `torch` from 1.13.1 to 2.0.0 and got error

```shell
Because torchvision (0.14.1) depends on torch (1.13.1)
 and convolutional-neural-network depends on torch (2.0.0), torchvision is forbidden.
So, because convolutional-neural-network depends on torchvision (0.14.1), version solving failed.
```

It would be great to support PyTorch 2!

**Comment by Hongbo-Miao** [comment]
Seems torchvision 0.15.1 depends on torch 2.0.0, will test and report back, thanks!

**Comment by Hongbo-Miao** [comment]
Confirmed torchvision 0.15.1 supporting torch 2.0.0. Worth upgrading the readme 😃
<img width="840" alt="image" src="https://user-images.githubusercontent.com/3375461/225467197-8bc03b69-89b8-4d12-9ad4-7fadfd286204.png">

**Comment by NicolasHug** [comment]
Thanks for the reminder @Hongbo-Miao , we'll update the README asap in https://github.com/pytorch/vision/pull/7400
