### ISSUE TITLE
0.15.1 has no aarch64 wheel

### ISSUE THREAD

**Issue by NathanRV** [pytorch/vision#7428]
### 🚀 The feature

pip install "torchvision==0.15.1" on a raspberry pi 4 doesn't work since the aarch64 wheel is missing

### Motivation, pitch

The release of torch 2.0.0 requires torchvision>=0.15.0. However, it is not possible to install it through pip on a rpi 4 as the aarch64 version is missing as seen [here](https://pypi.org/project/torchvision/#files).

**Comment by pmeier** [comment]
@osalpekar We had aarch64 wheels for the last release: https://pypi.org/project/torchvision/0.14.1/#files. Not sure where they came from though. I can't find a public job that builds them. Do you have any insights?

We used manylinux2014 for them, whereas then and now the x86 build are on manylinux1.

**Comment by NicolasHug** [comment]
From what I remember from discussion with @atalman those wheels are built manually. We should also be mindful of this issue with the previous wheels: https://github.com/pytorch/vision/issues/7104

**Comment by NathanRV** [comment]
@malfet Thank you for the reply. However, https://download.pytorch.org/whl/ does not contain aarch64 wheels for version 0.15.1.

**Comment by kennysong** [comment]
Also running into this issue. Has the aaarch64 wheels been published to PyPi yet?

**Comment by malfet** [comment]
@NathanRV there are no real difference between 0.15.0 and 0.15.1 (also 0.15.1 now should be available at the above-mentioned location)

**Comment by pmeier** [comment]
Can confirm the links are now available on our index:

- 3.8: https://download.pytorch.org/whl/torchvision-0.15.1-cp38-cp38-manylinux2014_aarch64.whl
- 3.9: https://download.pytorch.org/whl/torchvision-0.15.1-cp39-cp39-manylinux2014_aarch64.whl
- 3.10: https://download.pytorch.org/whl/torchvision-0.15.1-cp310-cp310-manylinux2014_aarch64.whl
- 3.11: https://download.pytorch.org/whl/torchvision-0.15.1-cp311-cp311-manylinux2014_aarch64.whl

Meaning, you should be able to do `pip install torchvision --extra-index-url=https://download.pytorch.org/whl`.

@malfet are we planning to upload them to PyPI as well? As mentioned above, the `0.14.1` wheels are hosted on PyPI as well.

**Comment by malfet** [comment]
Sorry for the late update, wheels has been promoted to pypi now. Closing.
