### ISSUE TITLE
when run/references/classification/train.py   AttributeError: module 'torchvision.models' has no attribute 'get_model'

### ISSUE THREAD

**Issue by cqray1990** [pytorch/vision#7465]
### 🐛 Describe the bug

AttributeError: module 'torchvision.models' has no attribute 'get_model'

### Versions

AttributeError: module 'torchvision.models' has no attribute 'get_model'

**Comment by NicolasHug** [comment]
@cqray1990 you likely have an old-ish version of torchvision. Update to 0.15 (or IIRC `get_models()` was introduced in 0.13, but I didn't double check).

If you do have 0.15 installed and the issue persists, let us know.
