### ISSUE TITLE
VOCDetection dataset Image.open() is already RGB, delete convert("RGB") to boost performance

### ISSUE THREAD

**Issue by samrere** [pytorch/vision#7478]
### 🐛 Describe the bug

as the title suggests, looks like ```img = Image.open(self.images[index]).convert("RGB")``` in ```___getitem__``` is slowing down the loading performance:
```python
from torchvision.datasets import VOCDetection
from tqdm import tqdm
ds=VOCDetection(root='data', year='2007', image_set='test', download=True)
c=0
for _ in tqdm(ds):
    c+=1
100%|██████████████████████████████████████| 4952/4952 [00:12<00:00, 387.14it/s]
```
and if you delete .convert("RGB"), it will be much faster:
```python
100%|█████████████████████████████████████| 4952/4952 [00:00<00:00, 5167.23it/s]
```
So, if there is no special reason why .convert("RGB") is needed (the default of Image.open is RGB anyways), I suggest delete it.

### Versions

PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          12
On-line CPU(s) list:             0-11
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
CPU family:                      6
Model:                           158
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
Stepping:                        10
CPU max MHz:                     4700.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7399.70
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
Virtualisation:                  VT-x
L1d cache:                       192 KiB (6 instances)
L1i cache:                       192 KiB (6 instances)
L2 cache:                        1.5 MiB (6 instances)
L3 cache:                        12 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; TSX disabled

Versions of relevant libraries:
[pip3] flake8==3.9.2
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.5           py39he7a7128_1  
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] pytorch                   1.12.1          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.1               py39_cu113    pytorch
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchvision               0.13.1               py39_cu113    pytorch

**Comment by NicolasHug** [comment]
@samrere are you sure the difference you're observing isn't due to some caching happening between the different runs?

I'd be very very sad (and surprised) if `img.convert("RGB")` wasn't a no-op if `img` is already RGB

**Comment by samrere** [comment]
Hi @NicolasHug I think so since I restart kernel between runs. should clear caching?

**Comment by pmeier** [comment]
The difference here is that `Image.open(...)` is a lazy operation. It just opens the file and loads the header to identify meta data like the size. Doing `.convert('RGB')` needs to load the actual data and thus you are seeing the actual I/O here.

```
from time import perf_counter

import PIL.Image

path = "test/assets/encode_jpeg/grace_hopper_517x606.jpg"

start = perf_counter()
image_opened = PIL.Image.open(path)
stop = perf_counter()
print(f"Opening image took {(stop - start) * 1e3:.1f} ms")

start = perf_counter()
image_loaded = image_opened.load()
stop = perf_counter()
print(f"Loading opened image took {(stop - start) * 1e3:.1f} ms")

start = perf_counter()
image_opened.convert("RGB")
stop = perf_counter()
print(f"Converting loaded image to RGB took {(stop - start) * 1e3:.1f} ms")

start = perf_counter()
# need to create a new image here, since the values are cached in the old one
PIL.Image.open(path).load()
stop = perf_counter()
print(f"Loading unopened image took {(stop - start) * 1e3:.1f} ms")

start = perf_counter()
# need to create a new image here, since the values are cached in the old one
PIL.Image.open(path).convert("RGB")
stop = perf_counter()
print(f"Converting unopened image to RGB took {(stop - start) * 1e3:.1f} ms")
```

```
Opening image took 5.1 ms
Loading opened image took 2.9 ms
Converting loaded image to RGB took 0.3 ms
Loading unopened image took 2.9 ms
Converting unopened image to RGB took 3.1 ms
```
(The high value just to open the image is just the initial delay of my disk. The same delay is no longer present in the other measurements since it only happens the first time)

As you can see from the last two measurements, `.convert("RGB")` takes roughly 200-300 µs on my system and thus can be considered a no-op. 

Since you need to load the values eventually to do anything with them, removing the `.convert('RGB')` call will just push the work down the line, but won't eliminate it. Meaning, in our case we potentially could replace the conversion with just the loading, but I don't think it will improve performance in a measurable way. 

Plus, we would need to make sure that all images are actually RGB or we will break BC. That sounds weird, but datasets are weird. For example, ImageNet consists of roughly 99% RGB images, with the remaining ones being mostly grayscale and even a few CMYK hiding in there. Dropping the conversion there would mean users get inconsistent output. I don't know how this is for VOC.
