### ISSUE TITLE
this is with reference to the closed session 741#

### ISSUE THREAD

**Issue by dimrecon** [pytorch/vision#751]
hi,

i changed the no of channels in init function of resnet and trained with pretrained = false and the model got saved. Training and validation works here. But when it comes to testing am facing errors here:

RuntimeError: Error(s) in loading state_dict for ResNet:
size mismatch for conv1.weight: copying a param with shape torch.Size([64, 3, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 4, 7, 7]).

Could u pls tell what might be the issue here?
My test code is follows:
for phase in ['test']:
print("model")
model = models.resnet50(pretrained=False)
model.load_state_dict(torch.load('resnet50_4c.pt'))
model.eval()

Cud u pls help me urgently

**Comment by fmassa** [comment]
Your checkpoint is not aligned with the model.

Without knowing exactly what were all the changes you did, difficult to say where the problem is. Did you use `nn.Parameter`?

**Comment by fmassa** [comment]
If you trained your model with `pretrained=False`, then you might be loading the wrong checkpoint, as from the error message it has 3 channels instead of 4.

**Comment by dsd009** [comment]
is there any help as resources for training with RBA images, cudnot findout

**Comment by fmassa** [comment]
@dsd009 no references that I know of for RGBA, but you could have a look at http://saurabhg.web.illinois.edu/pdfs/gupta2014learning.pdf for RGBD images.
