### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by cunjing56** [pytorch/vision#7510]
### 🐛 Describe the bug

this is jetson orin with jetpack 5.1
I want to run yolov5 with pytorch on jetson orin, so i installed pytorch first with PyTorch v2.0.0
https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-ml
https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html
only got this error 
ERROR: Invalid requirement: 'LD_LIBRARY_PATH=/usr/lib/llvm-8/lib:$LD_LIBRARY_PATH'
Hint: It looks like a path. File 'LD_LIBRARY_PATH=/usr/lib/llvm-8/lib:$LD_LIBRARY_PATH' does not exist.
since my $LD_LIBRARY_PATH is empty
I export LD_LIBRARY_PATH=/usr/lib/llvm-8/lib

I guess I have already installed torch properly
`python3
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch 
pring>>> print(torch.__file__)
/home/li/.virtualenvs/pytorchyolo/lib/python3.8/site-packages/torch/__init__.py`

So I run setup torchvision
`sudo apt install -y libjpeg-dev zlib1g-dev
git clone --branch v0.15.1 https://github.com/pytorch/vision torchvision
cd torchvision
sudo python3 setup.py install 
`
but i got
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

why? Is there any resolution?

### Versions

git clone --branch v0.15.1 https://github.com/pytorch/vision torchvision

**Comment by pmeier** [comment]
You ran `python3` to check if `torch` is available, but used `sudo python3` to run the installer. I guess, your Python is only installed for your user and not the superuser. You can try with `sudo python3 -c 'import torch'`. Not sure why you do it in the first place, but I would drop the `sudo` from the installation.

In any case, this is an environment issue and thus not actionable for us.

**Comment by cunjing56** [comment]
> You ran `python3` to check if `torch` is available, but used `sudo python3` to run the installer. I guess, your Python is only installed for your user and not the superuser. You can try with `sudo python3 -c 'import torch'`. Not sure why you do it in the first place, but I would drop the `sudo` from the installation.
> 
> In any case, this is an environment issue and thus not actionable for us.

you are right, it is about sudo and not sudo .
I followed pytorch tutorial to install pytorch and torchvision. I don't know why they pip install torch without sudo, and install torchvision with sudo.
Actually, on jetson orin to install pytorch or torch vision, pip goes very well , don't follow the other words about run setup.py...
