### ISSUE TITLE
Build from source error - librt and ldconfig

### ISSUE THREAD

**Issue by nidjan** [pytorch/vision#7512]
### 🐛 Describe the bug

manjaro latest, build for ROCM error

first 
cannot target librt.a
makefile find librt.a in /usr/lib/x86_64-linux-gnu (ubuntu path) not in /usr/lib/ (manjaro path)
i solved - link librt.a to destination

second
[100%] Linking CXX shared library libtorchvision.so
/usr/bin/ld: CMakeFiles/torchvision.dir/torchvision/csrc/vision_hip.cpp.o (symbol from plugin): в функции «vision::cuda_version()»:
(.text+0x0): повторное определение «vision::cuda_version()»; CMakeFiles/torchvision.dir/torchvision/csrc/vision.cpp.o (symbol from plugin):(.text+0x0): здесь первое определение
collect2: ошибка: выполнение ld завершилось с кодом возврата 1

i dont know, what to do

### Versions

manjaro latest
rocm 1.5.4.1
torch 2.0.0.2

**Comment by NicolasHug** [comment]
Sorry @nidjan , there's just too little information in this issue to know what you tried and what doesn't work. Please take another look at our issue template, which should help you provide an actionable issue report. I'll close this issue for now but feel free to re-open later with a more informative report.
