### ISSUE TITLE
Resize transform applied even if input size equal to desired output size

### ISSUE THREAD

**Issue by ilouzl** [pytorch/vision#7518]
### 🐛 Describe the bug

The functional transform resize, will be applied even if the input image is at the same size like the desired output.

```python
import torch
from torchvision.transforms import functional as F

x = torch.Tensor(1,100,200)
x_resized = F.resize(x, (100,200))
print(id(x), id(x_resized))
```

Yields a different id for the output image

### Versions

PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.3.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.9.12 (main, Apr  5 2022, 01:52:34)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-13.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] torchvision==0.16.0a0+b78d98b
[conda] No relevant packages

cc @vfdev-5

**Comment by vfdev-5** [comment]
@ilouzl thanks for the report, can you please also provide a context on why people would like to resize the input to the same output size ? I mean, why we would like to perform implicitly a no-op with resize using functional API ? It is more simple and explicit not to call `F.resize` if we do not want to resize. What do you think ?

**Comment by ilouzl** [comment]
Sometimes you have a set of images with different sizes, that you want to resize to a desired `osize`, and some of the input data might already be at that `osize`. 
When composing a transform pipeline, I usually use the `Resize` class, without selectively checking image size per every image.
Also, that functional resize API already has a dedicated branching for that situation, but it was implemented incorrectly.
