### ISSUE TITLE
A small question about the default value of RandomResizedCrop

### ISSUE THREAD

**Issue by zhiyong1997** [pytorch/vision#752]
The default value of the "scale" parameter ranges from (0.08, 1.0). Should it be (0.8, 1.0)? I can hardly imagine 8% of an image can be used for training.

**Comment by TheCodez** [comment]
From the paper [Going deeper with convolutions](https://arxiv.org/pdf/1409.4842.pdf):

> Still, one prescription that was verified to work very well after the competition includes sampling
> of various sized patches of the image whose size is distributed evenly between 8% and 100% of the
> image area ...

So this is correct :)

**Comment by fmassa** [comment]
Closing according to @TheCodez comment. Thanks!
