### ISSUE TITLE
DatasetFolder class and external functions

### ISSUE THREAD

**Issue by Giaco90** [pytorch/vision#753]
Hi there,
i noticed that _make_dataset_ and _find_classes_ are not _DatasetFolder_ methods. Is there a particular reason behind this choice? I need to extend DatasetFolder class to manage classes differently and i need to modify them.
(I know that I can assign to _datasets.folder.make_dataset_ and _datasets.folder._find_classes_ new functions but I don't like the solution a lot.)
Thanks.

**Comment by surgan12** [comment]
@Giaco90 As far as I can see the method make_dataset takes a root dir , class to idx, extensions and returns a  list .
This is something very generic and need not be in the class mentioned above.

**Comment by Giaco90** [comment]
@surgan12 Yes, but it is strictly related to DatasetFolder class and class_to_idx has been generated by _find_classes that is a DatasetFolder method (furthermore _find_classes behave like make_dataset so the same consideration should be done for it).
However i agree that it is generic, but at the same time it is related do DatasetFolder (since i can't find other useful occurrences), so maybe it could be passed as a default in the constructor.

Thank for your reply.

**Comment by surgan12** [comment]
@fmassa What do you think on this ?

**Comment by surgan12** [comment]
@vishwakftw, i think this can be closed .

**Comment by vishwakftw** [comment]
@Giaco90 if you think that the issue is resolved, please close it. Thank you.
