### ISSUE TITLE
Migrating download utils to torchdata

### ISSUE THREAD

**Issue by biphasic** [pytorch/vision#7549]
Hello,
following Patrick's [suggestion](https://discuss.pytorch.org/t/why-not-move-torchvision-download-utils-to-torchdata/178885), I'm opening an issue here to discuss if the torchvision maintainers would be open to move the [download utils](https://github.com/pytorch/vision/blob/main/torchvision/prototype/datasets/utils/_resource.py) upstream to torchdata. I'm the maintainer of a [similar package](https://github.com/neuromorphs/tonic) which is modeled after torchvision to a large extent and would benefit greatly from such a move, much like torchaudio/text I would assume. 

cc @pmeier

**Comment by biphasic** [comment]
> prototype datasets are currently on hold

Why is that if I may ask? Is there a place where your team defines a roadmap for torchvision?

> benefits 

The benefit would be not having to rely on torchvision for download utils and torchdata for datapipes, but just torchdata for all of that functionality.  I'm not sure I understand what you mean by saying that the users would have no touching points with torchdata, isn't the goal of torchvision/prototype to use datapipes?

**Comment by NicolasHug** [comment]
Hi @biphasic 

> Why is that if I may ask? Is there a place where your team defines a roadmap for torchvision?

We came to the conclusion that for now, there are more suitable opportunities to improve data-loading speed in torchvision. We might revisit in the future. Re roadmap: we used to disclose those more actively, but recent events have made that difficult. To give you an idea, the rough roadmap for now is to 1) release the transforms V2 work 2) improve data-loading speed via improvements to Resize() 3) revamp video decoding utilities.

Going back to the original goal of this issue: any additional dependency comes with significant maintenance cost, and there's no immediate plan to take a dependency on torchdata. So as @pmeier already it's unlikely that we'll migrate our download functionality to torchdata (on top of the blockers @pmeier already mentioned).

Also @biphasic please note that while our download utils are effectively public, we really don't recommend that you rely on them in your library: those were introduced a long time ago as public but they should have been private from the beginning. We might deprecate and make them private in the future, so please migrate away from them if you can.

Regardless of whether torchvision relies on torchdata for download functionality, there shouldn't be anything preventing you from relying on torchdata on your side? The download functionalities over there are public, so perhaps this is a better alternative for you

**Comment by biphasic** [comment]
Thanks a lot for the clarification @NicolasHug . While I understand that datapipes might not bring a big speed improvement, for me there's a big plus in their API. Would you say then there's a risk of torchdata not being actively developed anymore? In that case I might hold off as well then for the time being

**Comment by NicolasHug** [comment]
> Would you say then there's a risk of torchdata not being actively developed anymore

I don't think this is the case, but let me ping @ejguan and @NivekT who will be better suited to answer that

**Comment by vadimkantorov** [comment]
Related on need of a better / reliable download utility across PyTorch:
- https://github.com/pytorch/pytorch/issues/68320
- https://github.com/pytorch/pytorch/issues/73466
- https://github.com/pytorch/pytorch/issues/91965

**Comment by NicolasHug** [comment]
@biphasic just making sure you saw it: https://github.com/pytorch/data/#torchdata-see-note-below-on-current-status

Since torchdata development is paused, we won't be migrating to torchdata utils anytime soon, so I'll close this issue. Feel free to provide feedback for torchdata on https://github.com/pytorch/data/issues/1196

**Comment by biphasic** [comment]
@NicolasHug thanks a lot for letting me know!
