### ISSUE TITLE
F.to_pil_image broken for CUDA tensors

### ISSUE THREAD

**Issue by surgan12** [pytorch/vision#755]
Since to_pil_image converts tensors to numpy array first, therefore it cannot directly convert cuda tensors to Image .

@fmassa is this something intended ?

### To Reproduce
`import torchvision.transforms.functional as F`
`import torch`
 `p = torch.randn((3,2,3)`
`F.to_pil_image(p.cuda())`

### Resulting Behaviour

`TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
`

**Comment by vishwakftw** [comment]
I feel this is more of a documentation issue. Converting data on backend `x` to another form on backend `y` is not correct.

**Comment by surgan12** [comment]
@vishwakftw , since this function is giving an image .
I feel cuda tensors should be allowed to be directly converted to images .
We can also do by using a copy of the tensor instead of the other option.
What do you say ?

**Comment by surgan12** [comment]
@vishwakftw  should something like this be done :
`pic = pic.clone().cpu()`

**Comment by soumith** [comment]
I dont think we need a clone. `pic.cpu()` should be sufficient. However, as Vishwak said, I am not sure if we should auto-convert a CUDA Tensor to numpy / PIL image, because it might start hiding bugs, especially wrt performance

**Comment by surgan12** [comment]
@soumith , I agree
Bug hiding can be a issue
Thanks !!
