### ISSUE TITLE
Respect torch.use_deterministic_algorithms

### ISSUE THREAD

**Issue by ezyang** [pytorch/vision#7579]
### 🐛 Describe the bug

Some of torchvision's backward CUDA operators (e.g., roi_align_backward) use gpu atomic add, which makes the nondeterministic. It would be great if they were coded to respect use_deterministic. The easy thing to do is just make them warn, but if we can implement a Python version of the function we can also do the same playbook as in https://github.com/pytorch/pytorch/pull/101115

cc @kurtamohler

### Versions

master

**Comment by NicolasHug** [comment]
Could be a way of addressing https://github.com/pytorch/vision/issues/7457

The non-determinism has been around forever - @ezyang is there a time-critical need to fix it now?

**Comment by ezyang** [comment]
I'll submit the patch. I do kind of need it.
