### ISSUE TITLE
ImageNet dataset

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#758]
1. Is there an official source for the ILSVRC-2012 dataset, which is used for the training process of the models contained in `torchvision`? [The documentation](https://pytorch.org/docs/stable/torchvision/datasets.html#imagenet-12) points to the [official ImageNet homepage](http://image-net.org/download-images), but this seems to be unmaintained. I requested access via the form as well as standard email several times in the last three months, but never got answer. I was using an institute email address, which is not freely available as requested by ImageNet team.

2. If the answer to 1. is "no", should we be training the models on ILSVRC-2012 dataset, if the results cannot be reproduced by someone new to the field? Another option could be the ILSVRC-2017 dataset (which AFAIK comprises the ILSVRC-2012 dataset) hosted by the same team on [Kaggle](https://www.kaggle.com/c/imagenet-object-localization-challenge). According to the given timeline this competition is open for another 11 years, which guarantees access to the dataset for at least the same time.

3. Is there a reason, why the dataset that the pretrained models are based on, is not part of the `torchvision` package?  [The documentation](https://pytorch.org/docs/stable/torchvision/datasets.html#imagenet-12) hints that this could be implemented as `ImageFolder` dataset, but I fail to see a reason, why it is not properly predefined. If there is no such reason, I can create a PR to implement this.

**Comment by soumith** [comment]
1. A google search would take you to https://simon32.github.io/2018/01/09/image-net/ who posted the private links. It's not an official source for sure, but the links posted are all from the official website.

3. @fmassa was thinking about doing this, as we need to add class names to some Dataset class. If you send a PR subclassing ImageFolder, and then adding self.class_names, that seems worth it.

**Comment by RicCu** [comment]
Implementing an ImageNet Dataset is related to the discussion at #713. Someone took up that issue, you might want to check in with him about his progress.

**Comment by pmeier** [comment]
@soumith Thanks for the link. I'm curious: what is your search request that leads to this link? I spent quite some time looking for it before I posted this issue, but came out empty-handed.

**Comment by soumith** [comment]
@pmeier I searched for `Download links to ILSVRC2012 `
