### ISSUE TITLE
PyTorch and torchvision versions are incompatible

### ISSUE THREAD

**Issue by Donalcon** [pytorch/vision#7585]
### 🐛 Describe the bug

My project has a dependency that requires torch==1.13.0 (bytetracker). I have installed this version, as well as the versions of torchvision and torch audio compatible with it:
```python
pip install torch==1.13.0+cpu torchvision==0.14.0+cpu torchaudio==0.13.0 --extra-index-url https://download.pytorch.org/whl/cpu
````
The above is backed up by the compatibility matrix in this repo's readme:
```python


torch | torchvision | Python
-- | -- | --
main / nightly | main / nightly | >=3.8, <=3.11
2.0 | 0.15 | >=3.8, <=3.11
1.13 | 0.14 | >=3.7.2, <=3.10
1.12 | 0.13 | >=3.7, <=3.10

```

Why am I still receiving a compatibility error?

RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.

Note: I don't have cuda so cpu version is what I'm after

### Versions

above^^

**Comment by pmeier** [comment]
Could you please run the environment collection script as prompted by the issue template?

**Comment by NicolasHug** [comment]
Do you just need torch or do you also need torchvision? Feel free to ignore both torchvision and torchaudio from the installation command if you just need torch.
