### ISSUE TITLE
Max mode support for roi_align

### ISSUE THREAD

**Issue by rit7897** [pytorch/vision#7595]
### 🚀 The feature

Currently pytorch supports only avg mode, can we have support for max mode also, in torch==1.12.1

After this line

https://github.com/pytorch/vision/blob/fc838add3235d60feaea2251c1979fd253b26a77/torchvision/csrc/ops/cuda/roi_align_kernel.cu#L135

we can have
if mode is max than if (val > maxval) {
maxval = val;
} else output_val += val

### Motivation, pitch

I am building a model which requires max mode support but due to lack of this feature in pytorch i am stuck

**Comment by NicolasHug** [comment]
@rit7897 I have already explained in https://github.com/pytorch/vision/issues/7542#issuecomment-1549469852 that this is out of scope for torchvision.
