### ISSUE TITLE
to_pil_image mutates a 2-d tensor

### ISSUE THREAD

**Issue by surgan12** [pytorch/vision#760]
@fmassa  is this intended ?
I feel this might create a problem if we have a batch of images as 2d tensor and we just want to generate the images by keeping the tensor as it is.

The Problem is here :

 https://github.com/pytorch/vision/blob/22bc44ed76ec314e8c27df1575757d82f2eda0a3/torchvision/transforms/functional.py#L120

Proposed Fix:
Adding inplace option in the args.

**Comment by fmassa** [comment]
@surgan12 this mutation in particular is not expected I'd say. But note that in some cases we might share the storage of the tensor with the PIL image, which could potentially lead to mutation in the original tensor.
Can you just send a PR doing
```python
pic = pic.unsqueeze(0)
```
?

**Comment by surgan12** [comment]
@fmassa  sure !!
