### ISSUE TITLE
Cmake Windows integration 

### ISSUE THREAD

**Issue by atalman** [pytorch/vision#7604]
The PR that address CMake integration fails on GPU builds https://github.com/pytorch/vision/pull/7417

Call stack:
```
Call Stack (most recent call first):
  C:/Jenkins/Miniconda3/envs/py39/Library/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Jenkins/Miniconda3/envs/py39/Library/share/cmake-3.22/Modules/CMakeDetermineCompilerId.cmake:59 (__determine_compiler_id_test)
  C:/Jenkins/Miniconda3/envs/py39/Library/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:298 (CMAKE_DETERMINE_COMPILER_ID)
```

**Comment by atalman** [comment]
Yes this is correct. The CUDA toolkit is on the path and just before the error, cuda is found:
```
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7 (found version "11.7") 
```

**Comment by pmeier** [comment]
We are copying some files from the `extras\\visual_studio_integration\\MSBuildExtensions` folder of the extracted CUDA toolkit to the VS folders:

https://github.com/pytorch/vision/blob/689ff292e57eef932a939f70c20e893dec8f1d2b/packaging/windows/internal/cuda_install.bat#L130-L137

So maybe we just need to copy this to the right path?

While debugging this, I didn't find these files on our image directly, but had to run the CUDA installation manually again. Meaning, if we actually need these files, we likely need to rebuild the AMI.

**Comment by atalman** [comment]
@pmeier , @malfet Ok looks like the issue is exactly that this step failing :
```
xcopy /Y "%SRC_DIR%\temp_build\cuda\visual_studio_integration\CUDAVisualStudioIntegration\extras\visual_studio_integration\MSBuildExtensions\*.*" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations" 
```

The path is correct, when manually copied to:
``
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations
``
build seems to process past this issue. Will try provide a fix for this one.

**Comment by atalman** [comment]
This commit should fix the above issue with CUDA not found: https://github.com/pytorch/vision/pull/7417/commits/9baaf701d890317f74ca529052bce840c6aa5238
