### ISSUE TITLE
Feature Request: enhancing "Illustration of Transforms" docs to have separate sections for geometric-based and photometric-based methods

### ISSUE THREAD

**Issue by minhlong94** [pytorch/vision#7615]
### 🚀 The feature, motivation and pitch

Motivation: I am reading through the [Illustration of transforms](https://pytorch.org/vision/main/auto_examples/plot_transforms.html) page and I notice that they can be further enhanced. I list some proposals below:
- Separate sections for geometric-based methods and photometric-based methods: instead of scanning through the list of transform names and illustrations looking for which one is geometric and photmetric, readers can click to sections like "Geomtric-based methods", and under that section will have the list of transform names for Geomtric methods.
- Better descriptions for some methods: methods like [RandAugment](https://pytorch.org/vision/main/auto_examples/plot_transforms.html#randaugment), [TrivialAugmentWide](https://pytorch.org/vision/main/auto_examples/plot_transforms.html#trivialaugmentwide), and [AugMix](https://pytorch.org/vision/main/auto_examples/plot_transforms.html#augmix) have only a short description with the template `The <method name> transform automatically augments the data.`. I think it can be further enhanced with a one-sentence description like other methods.

### Additional context

I am happy to implement this Feature proposal and submit a Pull Request.

**Comment by pmeier** [comment]
Hey @minhlong94 and thanks for the request. Documentation improvements are always welcome and your suggestions above sound reasonable to me.

If you want to send a PR, you can find the source of the gallery in https://github.com/pytorch/vision/blob/main/gallery/plot_transforms.py. This is rendered by [`sphinx-gallery`](https://sphinx-gallery.github.io/stable/index.html), which uses a mix of code and comments in RST format. If you aren't familiar on the latter, here is a [primer](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html).

**Comment by minhlong94** [comment]
Hi @pmeier , sounds good, I will close this issue here and will submit the PR!

**Comment by pmeier** [comment]
Let's keep this open and let the PR close this automatically upon merge: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
