### ISSUE TITLE
ConvertImageDtype does not work properly in the range (0. 1.)

### ISSUE THREAD

**Issue by mjack3** [pytorch/vision#7619]
### 🐛 Describe the bug

The transformation `torchvision.transforms.ConvertImageDtype(torch.uint8)` does not work correctly with tensors in the range [0.0, 1.0].

If you have a tensor with values in the range [0.0, 1.0] and apply `ConvertImageDtype(torch.uint8)` to them, you would expect to have binary tensors, where values less than 0.5 are rounded to 0, and 1 in the case of values greater than or equal to 0.5. However, this conversion returns a tensor in the range [0, 255]. So, sequences like the following will not return the expected behaviour:

```
...
...
transforms.ToTensor(), # normalized in range [0., 1.]
transforms.ConvertImageDtype(torch.uint8) # Binary tensor
```

### Versions

Pytorch 2.0

**Comment by NicolasHug** [comment]
Thanks for the report @mjack3 .

The docs say:

> Convert a tensor image to the given dtype and scale the values accordingly.

So IMO this is fairly expected - we can't always 100% describe a function's behaviour just by its name. This scaling behaviour is also what users will want to have in 99% of the cases. But do let us know if you think we can make that clearer

**Comment by mjack3** [comment]
In my opinion, this is not to be expected based on the description given. The natural values of decimal values in the range [0.0, 1.0] are simply the values 0 and 1. The natural version of decimal values in the range [0.0, 255.0] are the values between 0 and 255. However, if you consider this behavior is expected, I would add to the description that the value is scaled accordingly in the range [0, 255].

**Comment by NicolasHug** [comment]
I guess it's a matter of convention. I don't think there's a lot of users working with images who would expect `0-1` output when converting from float to uint8. If you know of libraries who do that, I'd be happy to know.

Also from our [docs](https://pytorch.org/vision/main/transforms.html):

> The expected range of the values of a tensor image is implicitly defined by the tensor dtype. Tensor images with a float dtype are expected to have values in [0, 1). Tensor images with an integer dtype are expected to have values in [0, MAX_DTYPE] where MAX_DTYPE is the largest value that can be represented in that dtype.


and [here](https://pytorch.org/vision/main/transforms.html#conversion)

> Beware, some of these conversion transforms below will scale the values while performing the conversion, while some may not do any scaling. By scaling, we mean e.g. that a uint8 -> float32 would map the [0, 255] range into [0, 1] (and vice-versa).

**Comment by mjack3** [comment]
Mmm, ok, it is correctly documented. Thanks
