### ISSUE TITLE
MNIST Dataset gets downloaded but FashionMNIST throws AttributeError

### ISSUE THREAD

**Issue by radhikachavan** [pytorch/vision#763]
Below code throws Attribute Error for FashionMNIST Dataset.
import torch
import torchvision
#import torchvision.datasets as dset
import torchvision.transforms as transforms

train_set = torchvision.datasets.FashionMNIST(
        root='./data/FM'
        ,train=True
        ,download=True
        ,transform=transforms.Compose([transforms.ToTensor()
        ])
)

train_loader=torch.utils.data.DataLoader(train_set)

ERROR:

  File "<ipython-input-40-02974e44d9f7>", line 1, in <module>
    runfile('/RadhikaChavan/Radhika/05MyData/R Programming/Python/FashionMNIST/FashionPyModel.py', wdir='/RadhikaChavan/Radhika/05MyData/R Programming/Python/FashionMNIST')

  File "/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 753, in runfile
    execfile(filename, namespace)

  File "/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "~/Python/FashionMNIST/FashionPyModel.py", line 14, in <module>
    train_set = torchvision.datasets.FashionMNIST(

AttributeError: module 'torchvision.datasets' has no attribute 'FashionMNIST'

However, MNIST works perfectly fine and creates the test.pt and training.pt files.
I have also checked the mnist.py code in torchvision folder > datasets folder and it has the FashionMNIST extending MNIST. 

Please help!

**Comment by fmassa** [comment]
Hi,

I believe the version of torchvision that you have is old and doesn't contain `FashionMNIST`.

We will be releasing a new version of torchvision today, so you'll be able to update your install.

Alternatively, you can also install from source, which would enable you to use it right away

**Comment by radhikachavan** [comment]
Thank you so much.
