### ISSUE TITLE
Please don't push spuriously numbered git tags

### ISSUE THREAD

**Issue by h-vetinari** [pytorch/vision#7650]
Hi!

I help package various pytorch (and many other) packages in conda-forge. We rely on an automated bot to scrape the various repositories to check if new versions have been published, and tags like [`ciflow/default/5009`](https://github.com/pytorch/vision/releases/tag/ciflow%2Fdefault%2F5009) make this much more difficult, because the bot now thinks that a version "5009" of torchvision has been published, and then fails with: 
```
The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '5009' to make sure they exist!

We also found the following errors:

 - could not hash URL template 'https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz'
```

Of course, one could argue that the bot should be(come) smarter, but OTOH, that tag looks pretty spurious AFAICT. Is it really necessary to publish such tags on the main repo? Could you remove them and avoid that going forward? That would be amazing (otherwise we potentially fall far behind with updates, because it takes a human to figure out why the bot has stopped).

CC @NicolasHug

**Comment by NicolasHug** [comment]
CC @pmeier any idea what these tags are?

**Comment by pmeier** [comment]
They are coming a mechanism that is used in PyTorch core to conditionally run CI jobs on PRs. Without going into too much details, whenever you put a `ciflow/*` label onto a PR, e.g. `ciflow/default` on #5009, a bot pushes the corresponding tag to the repo, which ultimately serves as CI trigger. That is quite convoluted, but was the best solution that was found to conditionally trigger CI jobs and have them placed together with the regular ones inside the GH UI.

That being said, there are two things wrong here:

1. The bot should also delete these tags again after the PR is closed or merged, but that doesn't seem to be the case here.
2. We are not using this system (yet).

For now we can safely delete these tags. In the future, if move forward with more conditional CI, e.g. #7507, the conda-forge bot might need to be fixed.

**Comment by pmeier** [comment]
Seems the labels come from a previous test with the bot:

![Screenshot from 2023-06-02 10-51-54](https://github.com/pytorch/vision/assets/6849766/14c44686-81bb-49c1-aacb-b9e27f0e4321)

**Comment by pmeier** [comment]
Deletion mechanism seems to work. I've removed the label from #5009 and the tag is gone now: https://github.com/pytorch/vision/releases/tag/ciflow%2Fdefault%2F5009

**Comment by pmeier** [comment]
I've removed the label from all the open PRs that still had them. All corresponding tags should be gone now.

**Comment by pmeier** [comment]
Closing this for now, since as of now there are no more of the tags in question. However, they might get a comeback if we need this for our CI infrastructure. @h-vetinari I'll give you a ping in that case.
