### ISSUE TITLE
AttributeError: module 'torchvision' has no attribute '__version__'

### ISSUE THREAD

**Issue by yanboliang** [pytorch/vision#7658]
### 🐛 Describe the bug

Building from source code.

### Versions

N/A

**Comment by NicolasHug** [comment]
Hmmm. 

There was probably something wrong during your installation and you hit these lines which ignore an error when setting the `__version__` attribute:

https://github.com/pytorch/vision/blob/657027f3548f20aea7b1c34e26511823b1607145/torchvision/__init__.py#L10-L13


Feel free to reopen an issue with more details about your installation process, and with the details of your environment as requested in the issue template

**Comment by yanboliang** [comment]
The issue is still there, to be clear, I'm building from source code rather than using pip.

**Comment by yanboliang** [comment]
It works now.
