### ISSUE TITLE
What happens if box coordinate < 0 in function `torchvision.ops.nms`

### ISSUE THREAD

**Issue by osirisFdragon** [pytorch/vision#7659]
Hi,
In the document <a>https://pytorch.org/vision/stable/generated/torchvision.ops.nms.html#torchvision.ops.nms</a>, it said `boxes (Tensor[N, 4])) – boxes to perform NMS on. They are expected to be in (x1, y1, x2, y2) format with 0 <= x1 < x2 and 0 <= y1 < y2.`. But what happen if I put the boxes with coordinate less than 0?

**Comment by NicolasHug** [comment]
Basically you shouldn't trust the results if the input isn't in the right format, even though the code may not error.
The code assumes that the input is properly formatted and if it's not it may lead to erroneous comparisons, under/overflows, incorrect IoUs, that kind of stuff
