### ISSUE TITLE
0.2.2 wheel is forcing tqdm==4.19.9

### ISSUE THREAD

**Issue by mitar** [pytorch/vision#766]
So while `setup.py` has code which forces `tqdm==4.19.9` version only on Python 2 and leaves version unforced on Python 3, 0.2.2 package was published with a wheel which is the same for both Python 2 and Python 3 and have `tqdm==4.19.9` version hard-coded. It seems when wheel was made Python 2 was used.

I think that if you have such condition in `setup.py` you have to publish a different wheel for Python 2 and Python 3 and not the same one.

**Comment by surgan12** [comment]
@soumith , just a quick question !
Why are we forcing tqdm==4.19.9 in setup.py for python2 .
Simply adding 'tqdm' is using tqdm==4.28.1 for python3 and tqdm==4.31.1 for python2.

I think we can remove that line .

**Comment by mitar** [comment]
See: https://github.com/pytorch/vision/pull/542

**Comment by surgan12** [comment]
@mitar  I Tried using the  versions mentioned above by me  and no error is showing for me.

**Comment by mitar** [comment]
There is no error. It is just that it forces `tqdm==4.19.9` on Python 3. Which is not what it should be doing. You cannot install any newer version then. So if you have another package which requires a newer version you have a problem (which is what happens in my case).

**Comment by surgan12** [comment]
With error i meant , mentioned in #541 .
And yes you are right the old version will cause some issues.

**Comment by mitar** [comment]
But https://github.com/tqdm/tqdm/issues/548 is not closed?

**Comment by surgan12** [comment]
@mitar , i tested with tqdm==4.31.1 and everything mentioned in #541 was working fine.

**Comment by jgbustos** [comment]
I'd suggest using platform specific dependencies (see https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies and https://www.python.org/dev/peps/pep-0508/) so the downgrade is only forced for Python 2.

**Comment by soumith** [comment]
we'll fix it today.

**Comment by fmassa** [comment]
I think I'll just remove the dependency on tqdm, and use instead the version from pytorch in https://github.com/pytorch/pytorch/blob/13e6326c07cd44ad52db32ac3918eeb79f8230bc/torch/utils/model_zoo.py#L126-L151
