### ISSUE TITLE
[Conda] pillow 9.5.0 incompatible with any torchvision version due to switch from jpeg to libjpeg-turbo

### ISSUE THREAD

**Issue by junpuf** [pytorch/vision#7660]
### 🐛 Describe the bug

Pillow no longer compatible with `torchvision` starting from version 9.5.0 due to issues discussed in https://github.com/conda-forge/libjpeg-turbo-feedstock/issues/28

The core issue was that the `jpeg` conda package was "deprecated" by the conda-forge community and they want all users of `jpeg` to migrate to `libjpeg-turbo`.

### Versions

all torchvision conda package

**Comment by malfet** [comment]
There are no pillow-9.5.0 on Anaconda https://anaconda.org/anaconda/pillow is there?

**Comment by junpuf** [comment]
the default channels is currently ok. But the [conda-forge](https://anaconda.org/conda-forge/pillow) channel has already updated.

**Comment by rymndhng** [comment]
We're seeing this impact our conda environment where we cannot upgrade dependencies b/c we have deps from `conda-forge` that depend on `libjpeg-turbo` and `torchvision` from the `pytorch` channel that depends on jpeg.

I'm wondering if we could unblock this scenario by removing `jpeg` as an explcit `run` dependency. Instead, could the `torchvision` package document & tell users to install `jpeg` or `libjpeg-turbo` into the environment themselves.

**Comment by NicolasHug** [comment]
Quick update on this: for conda builds, we're going to try to make torchvision depend on `libjpeg-turbo` instead of `jpeg` (like PIL). It's something we've been considering for a while anyway.

**Comment by rymndhng** [comment]
@NicolasHug Thanks for moving this along! 

Do you have a timeline for when a new build will be pushed to conda?

**Comment by NicolasHug** [comment]
I believe the next release is planned for early October
