### ISSUE TITLE
Bug in the new version 0.2.2 while loading datasets

### ISSUE THREAD

**Issue by rednithin** [pytorch/vision#769]
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to /home/nithin/Git/Datasets/MNIST/raw/train-images-idx3-ubyte.gz

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-481efeb3c63f> in <module>
      2                      train=True,
      3                      transform=transforms.ToTensor(),
----> 4                      download=True)
      5 test_dataset = dsets.MNIST(root='/home/nithin/Git/Datasets',
      6                      train=False,

~/.conda/envs/ml/lib/python3.7/site-packages/torchvision/datasets/mnist.py in __init__(self, root, train, transform, target_transform, download)
     66 
     67         if download:
---> 68             self.download()
     69 
     70         if not self._check_exists():

~/.conda/envs/ml/lib/python3.7/site-packages/torchvision/datasets/mnist.py in download(self)
    141             filename = url.rpartition('/')[2]
    142             file_path = os.path.join(self.raw_folder, filename)
--> 143             download_url(url, root=self.raw_folder, filename=filename, md5=None)
    144             self.extract_gzip(gzip_path=file_path, remove_finished=True)
    145 

~/.conda/envs/ml/lib/python3.7/site-packages/torchvision/datasets/utils.py in download_url(url, root, filename, md5)
     71             urllib.request.urlretrieve(
     72                 url, fpath,
---> 73                 reporthook=gen_bar_updater(tqdm())
     74             )
     75         except OSError:

TypeError: __init__() missing 1 required positional argument: 'total'

**Comment by fmassa** [comment]
Hi,

Thanks for the bug report. This can be solved for now by installing `tqdm`.
I'll get this fixed, sorry for the trouble!
