### ISSUE TITLE
Download error with CIFAR10/Mnist based on torchvision.datasets

### ISSUE THREAD

**Issue by YunchuZhang** [pytorch/vision#774]
I use Macos and Pytorch 1.0 

My code is here:
import torch
import torchvision
import torchvision.transforms as transforms
transform = transforms.Compose(
[transforms.ToTensor(),
transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=4,
shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=4,
shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

the bug information is:
(.env) zycdeMBP:Downloads zyc$ python3 testtorch.py
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar-10-python.tar.gz
Traceback (most recent call last):
File "testtorch.py", line 9, in 
download=True, transform=transform)
File "/Users/zyc/Downloads/.env/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 63, in init
self.download()
File "/Users/zyc/Downloads/.env/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 150, in download
download_url(self.url, self.root, self.filename, self.tgz_md5)
File "/Users/zyc/Downloads/.env/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 73, in download_url
reporthook=gen_bar_updater(tqdm())
TypeError: init() missing 1 required positional argument: 'total'

**Comment by soumith** [comment]
please uninstall and reinstall torchvision, this is fixed if you do that

**Comment by YunchuZhang** [comment]
Thank you so much
