### ISSUE TITLE
Facing an error while setting up the development environment

### ISSUE THREAD

**Issue by AnimeshMaheshwari22** [pytorch/vision#7775]
Facing this error:
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code

I have the latest build tools installed. 

Grateful for any help on this. Thanks

**Comment by NicolasHug** [comment]
please use the provided template.
