### ISSUE TITLE
The public v2 utils like `query_size` or `query_chw` are untested

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#7785]
If we're going to expose them as public, we need unit tests for them.

**Comment by rwightman** [comment]
@NicolasHug can I prod this up in priority? I've started working with v2 transforms and I need these functions to implement custom transforms that I can combine with the builtin ones... I really don't like having imports from _utils, _geometry, etc in my modules.

**Comment by NicolasHug** [comment]
Hi @rwightman , just to make sure I understand, you need those to be publicly available from `torchvision.transforms.v2`?

**Comment by rwightman** [comment]
@NicolasHug yes, they're needed to make custom v2 transforms that can handle flat inputs in the _get_params

**Comment by NicolasHug** [comment]
OK, sounds good. I exposed anything you might need in https://github.com/pytorch/vision/pull/8670.

Since it's fairly low risk, I'll try to cherry-pick the PR to the release branch so that it's available for you in 0.20 (planned for later this month).

Looking forward to seeing how you use the v2 transforms! LMK if there's anything I can help with.
