### ISSUE TITLE
CIFAR vs. MNIST inconsistent __getitem__

### ISSUE THREAD

**Issue by lsc64** [pytorch/vision#7801]
### 🐛 Describe the bug

I experimented with various targets for learning a model and hacked this into CIFAR10 and MNIST by replacing the target variable. I then noticed that MNIST insists on returning integers while CIFAR doesn't care.  

https://github.com/pytorch/vision/blob/bf03f4edfe8fd7543e98ed9a3771b01ab6c6f062/torchvision/datasets/mnist.py#L138

https://github.com/pytorch/vision/blob/bf03f4edfe8fd7543e98ed9a3771b01ab6c6f062/torchvision/datasets/cifar.py#L111

This issue is quite nit-picky, but they should both either check that they are sure to return integers as targets or they both should not perform that check.

### Versions

```
Versions of relevant libraries:
[pip3] numpy==1.25.0
[pip3] pytorch-lightning==1.9.5
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.6            py39h417a72b_1  
[conda] mkl_random                1.2.2            py39h417a72b_1  
[conda] numpy                     1.25.0           py39h5f9d8c6_0  
[conda] numpy-base                1.25.0           py39hb5e798b_0  
[conda] pytorch                   2.0.1           py3.9_cuda11.7_cudnn8.5.0_0    pytorch
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-lightning         1.9.5                    pypi_0    pypi
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2                py39_cu117    pytorch
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchtriton               2.0.0                      py39    pytorch
[conda] torchvision               0.15.2               py39_cu117    pytorch
```

**Comment by pmeier** [comment]
> but they should both either check that they are sure to return integers as targets or they both should not perform that check.

This is not a check, but rather an actual conversion for MNIST.

MNIST _needs_ to convert to `int`, because we start from a `torch.Tensor` and otherwise we would not get an `int` back, but rather a scalar (0d) tensor.

CIFAR does not have this limitation, since we start from a list of integers in the first place. Thus, a conversion is unnecessary.
