### ISSUE TITLE
Bounding box resize transform

### ISSUE THREAD

**Issue by sadra-barikbin** [pytorch/vision#7827]
### 🚀 The feature

I suggest introducing a new transform for resizing bounding boxes `ResizeBoundingBox(new_canvas_size)`

### Motivation, pitch

In detection task, when image is resized to fit into the model input requirement, there's need to change bounding boxes accordingly as well. Here is an example. Below is the depiction of an image of size (1280,720) and its bounding boxes:
![image](https://github.com/pytorch/vision/assets/22097587/bd8e0657-2ef7-4fc4-abe9-c3dad675b64d)

When it's resized using `transforms.v2.Resize((640,640))` and the bboxes do not get updated accordingly, the result would be:
![image](https://github.com/pytorch/vision/assets/22097587/b730067d-c3a3-4eea-af64-7150e15a7875)

while the desired output is:
![image](https://github.com/pytorch/vision/assets/22097587/615eba62-e286-48b9-8fa2-616ebc3c0bcf)

### Additional context

I'm willing to send a PR for it if it gets accepted.

**Comment by sadra-barikbin** [comment]
A tiny question unrelated to this issue, to not create another one. Isn't better to decrement `category_id` by one when setting `labels` in coco detection wrapper? Since anyway user should do so when wants to use `labels` at least in computing loss. For accessing the unchanged labels, one could add `category_id` to `target_keys` of the `wrap_dataset_for_transforms_v2`.

https://github.com/pytorch/vision/blob/cab01fc1b7c7f0620ab95c6064f2a3fb583e9bee/torchvision/datapoints/_dataset_wrapper.py#L390-L391

**Comment by NicolasHug** [comment]
@sadra-barikbin Can you provide a minimal reproducible example where the bbox weren't resized?

something like this:

```
t = transforms.v2.Resize((640,640))
img, bboxes = t(img, bboxes)
```

should definitely resize and re-locate the bounding boxes.

**Comment by sadra-barikbin** [comment]
@NicolasHug , my bad. Now I see that `Resize` transforms bboxes as well. Could you please answer my above question as well?

**Comment by NicolasHug** [comment]
We have opted to return the datasets largely "as-is" i.e. in the original way it was packaged by their authors to avoid surprises.
