### ISSUE TITLE
celebA RuntimeError: The MD5 checksum of the download file does not match the one on record.

### ISSUE THREAD

**Issue by rudolfwilliam** [pytorch/vision#7850]
### 🐛 Describe the bug

Running

```
from torchvision.datasets import CelebA

data_dir = "./celeba/data"
data = CelebA(root=data_dir, split='train', download=True)
```

yields the error

`RuntimeError: The MD5 checksum of the download file ./celeba/data/celeba/list_landmarks_align_celeba.txt does not match the one on record.Please delete the file and try again.`

Deleting the file and running the code again does not solve the problem.

### Versions

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.7.8 (x86_64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.11)
CMake version: version 3.17.3
Libc version: N/A

Python version: 3.11.3 (main, May 15 2023, 10:43:03) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.4
[pip3] torch==2.0.1
[pip3] torchmetrics==1.0.0
[pip3] torchvision==0.15.2
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h59209a4_43558  
[conda] mkl-fft                   1.3.6                    pypi_0    pypi
[conda] mkl-random                1.2.2                    pypi_0    pypi
[conda] mkl-service               2.4.0                    pypi_0    pypi
[conda] mkl_fft                   1.3.6           py311hdb55bb0_1  
[conda] mkl_random                1.2.2           py311hdb55bb0_1  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] numpy-base                1.25.0          py311h53bf9ac_0  
[conda] pytorch                   2.0.1           cpu_py311he1daf47_0  
[conda] pytorch-lightning         2.0.4                    pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchmetrics              1.0.0                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

cc @pmeier

**Comment by pmeier** [comment]
CelebA is notoriously hard to download since it is hosted on GDrive, which has no API that we can interact with. We are trying to catch common mistakes, but that process is not as robust as I would like it to be. Could you please have a look at the downloaded file and see if it actually contains the data we would expect or something else?

**Comment by pmeier** [comment]
I'm currently getting

```
RuntimeError: The daily quota of the file img_align_celeba.zip is exceeded and it can't be downloaded. This is a limitation of Google Drive and can only be overcome by trying again later.
```

As the error implies, there is nothing we can do about that. There are countless threads on this tracker (rightfully) complaining that they can't download the files. The only solutions are a) wait until the quota is no longer exceeded or b) ask the authors to host the files elsewhere that doesn't have this restriction.

**Comment by rudolfwilliam** [comment]
Thanks for the quick reply! I have been receiving your error for the last three days and today was the first time it showed a different one. I just took a look at the file (`list_landmarks_align_celeba.txt`) and indeed, it seems it does not have the desired content:

`<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>`

**Comment by pmeier** [comment]
```
<h1>We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p>
```

That is a new one :roll_eyes: Let me see if we can guard against it and raise a proper error. 

But in general, my statement from https://github.com/pytorch/vision/issues/7850#issuecomment-1683559793 holds. There is nothing we can do. Other than convincing the author that GDrive is a suboptimal solution to host datasets, you can't do anything but wait until the quota resets. AFAIK, it is unknown when exactly that happens and thus it is impossible to predict at what time of the day your chance for actually getting through is higher.

**Comment by rudolfwilliam** [comment]
All of a sudden, the code ran successfully. I did not do anything other than wait even more time and run again...
