### ISSUE TITLE
Segmentation - Incorrect IoU being printed on master process

### ISSUE THREAD

**Issue by siddharth9820** [pytorch/vision#7915]
https://github.com/pytorch/vision/blob/96950a5cff2cf3ebee1b91cd3fbafe086d54c9c5/references/segmentation/utils.py#L91
The expected behavior of this line is to all-reduce `self.mat` in-place. However, the `reduce_across_all_processes` method creates a copy of the tensor (https://github.com/pytorch/vision/blob/96950a5cff2cf3ebee1b91cd3fbafe086d54c9c5/references/segmentation/utils.py#L297) and runs the allreduce on that copy. Thus self.mat is not updated and the master process prints incorrect IoUs.

I guess this is a potential fix - 

``self.mat = reduce_across_processes(self.mat).to(torch.int64)``

PR - https://github.com/pytorch/vision/pull/7916 attempts to fix this.

**Comment by NicolasHug** [comment]
Fixed in https://github.com/pytorch/vision/pull/7916, thanks for the report and for the fix @siddharth9820
