### ISSUE TITLE
Link to Stanford cars dataset is broken: 404 not found

### ISSUE THREAD

**Issue by jdenholm** [pytorch/vision#7930]
### 📚 The doc issue

The link to the Stanford cars dataset, [here](https://ai.stanford.edu/~jkrause/cars/car_dataset.html), on [this page](https://pytorch.org/vision/stable/generated/torchvision.datasets.StanfordCars.html#torchvision.datasets.StanfordCars), gives a 404 not found.

**Comment by pmeier** [comment]
Duplicate of #7545.
