### ISSUE TITLE
ResNet101 V2 weights accuracy is very low compared to V1 weights

### ISSUE THREAD

**Issue by aviadb** [pytorch/vision#7958]
### 🐛 Describe the bug

Initiating the same ResNet101 model
once with the ResNet101_Weights.IMAGENET1K_V2 and the other time with ResNet101_Weights.IMAGENET1K_V1.

I am testing several images, but also images fetched from the Imagenet training set.
The V2 weights yield in a very low accuracy results compared to V1.

```python
weights = ResNet101_Weights.IMAGENET1K_V2
model = resnet101(weights=weights)
model.eval();
preprocess = weights.transforms()

img = read_image("imgs/n02111889_7198.JPEG") # Example image from training set
T.ToPILImage()(img).show()

batch = preprocess(img).unsqueeze(0)
prediction = model(batch).detach().squeeze(0).softmax(0)
class_id = prediction.argmax().item()
score = prediction[class_id].item()
category_name = weights.meta["categories"][class_id]
print(f"{category_name}: {100 * score:.1f}%")
```

```python
img = read_image("imgs/ILSVRC2012_val_00035585.JPEG") # Another example from training set
T.ToPILImage()(img).show()

batch = preprocess(img).unsqueeze(0)
prediction = model(batch).detach().squeeze(0).softmax(0)
class_id = prediction.argmax().item()
score = prediction[class_id].item()
category_name = weights.meta["categories"][class_id]
print(f"{category_name}: {100 * score:.1f}%")
```
First example:
V2 weights: Samoyed: 86.3%
V1 weights: Samoyed: 98.8%

2nd example:
V2 weights: Samoyed: 89.8%
V1 weights: Samoyed: 99.4%

### Versions

Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 537.13
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
CPU family:                      6
Model:                           158
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        9
BogoMIPS:                        8399.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi ept vpid ept_ad fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves flush_l1d arch_capabilities
Virtualization:                  VT-x
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       128 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        1 MiB (4 instances)
L3 cache:                        8 MiB (1 instance)
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Unknown: Dependent on hypervisor status
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown

Versions of relevant libraries:
[pip3] numpy==1.25.2
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2a0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h213fc3f_46343  
[conda] mkl-service               2.4.0           py311h5eee18b_1  
[conda] mkl_fft                   1.3.6           py311ha02d727_1  
[conda] mkl_random                1.2.2           py311ha02d727_1  
[conda] numpy                     1.25.2          py311h08b1b3b_0  
[conda] numpy-base                1.25.2          py311hf175353_0  
[conda] pytorch                   2.0.1           cpu_py311h6d93b4c_0  
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.2               py311_cu118    pytorch
[conda] torchvision               0.15.2          cpu_py311h6e929fa_0

**Comment by pmeier** [comment]
We claim that the v2 weights improve the acc@1 and acc@5 over the full evaluation set of ImageNet 1k. Meaning, there can very much be individual images where v1 is better than v2. On average though, v2 is an improvement.

Are you seeing this for individual images or in general on larger sets of images as well?

**Comment by aviadb** [comment]
Hi @pmeier ,
I am seeing it for a bunch of images, some are taken from training and validation datasets, and other images.

I will try to reproduce the ACC@1, ACC@5 checks.
Is there a built-in utility function for the extraction of ACC@1, ACC@5 metrics? 
I would like to use the same test

**Comment by pmeier** [comment]
You can run our [reference script](https://github.com/pytorch/vision/tree/main/references/classification) with the

https://github.com/pytorch/vision/blob/0b41ff0b0a08229a10cfe1ca6987b4386d68bd9c/references/classification/train.py#L467

option.

**Comment by NicolasHug** [comment]
> First example:
V2 weights: Samoyed: 86.3%
V1 weights: Samoyed: 98.8%

> 2nd example:
V2 weights: Samoyed: 89.8%
V1 weights: Samoyed: 99.4%


This isn't accuracy, this is "confidence" of the model in its predictions. The distribution over the predicted probabilities is expected to be different across models and just because the max probability is lower for a model doesn't mean it's worse. There are similar discussions in https://github.com/pytorch/vision/issues/7570.
