### ISSUE TITLE
`read_video` produce different output than `read_image`

### ISSUE THREAD

**Issue by MohamedAliRashad** [pytorch/vision#7960]
### 🐛 Describe the bug

The result of `read_video` is not the same of `read_image` with concatenation

```python
import torchvision
import cv2
import tempfile
import torch

video_path = # path to video

# Extract frames using `read_image`
video_tensor1 = []
cap = cv2.VideoCapture(str(video_path))
while True:
    ret, frame = cap.read()
    if not ret:
        break
    with tempfile.NamedTemporaryFile(suffix=".jpg") as f:
        cv2.imwrite(f.name, frame)
        img = torchvision.io.read_image(str(f.name), torchvision.io.ImageReadMode.RGB)[None, ...].float()
        video_tensor1.append(img)
video_tensor1 = torch.cat(video_tensor1)

# Extract frames using `read_video`
video_tensor2 = torchvision.io.read_video(str(video_path))[0].permute(0, 3, 2, 1).float()

# Compare the two tensors
print((video_tensor1 == video_tensor2).all())
```

### Versions

torchvision==0.15.2

**Comment by MohamedAliRashad** [comment]
I discovered that the problem is that the output needs to be flipped
```python
video_tensor2 = torch.flip(torchvision.io.read_video(str(video_path), pts_unit="sec")[0].permute(0, 3, 2, 1).float(), (3,))
```

I still thinks that those operations should be the default.

**Comment by pmeier** [comment]
`read_video` has the parameter `output_format`

https://github.com/pytorch/vision/blob/0b41ff0b0a08229a10cfe1ca6987b4386d68bd9c/torchvision/io/video.py#L241

that you can set to `"TCHW"` to get what you want. `read_image` will always return "CHW":

https://github.com/pytorch/vision/blob/0b41ff0b0a08229a10cfe1ca6987b4386d68bd9c/torchvision/io/image.py#L254

**Comment by MohamedAliRashad** [comment]
@pmeier This returns `TCWH` not `TCHW` which is the reason i added permute.

**Comment by pmeier** [comment]
> This returns `TCWH` not `TCHW`

That is not the case:

```python
import av

from torchvision.io import read_video

path = "test/assets/videos/RATRACE_wave_f_nm_np1_fr_goo_37.avi"

video_tv, *_ = read_video(path, output_format="TCHW", pts_unit="sec")
height, width = video_tv.shape[-2:]  # shape=[..., H, W]
print("torchvision", f"{height=}, {width=}")

video_av = av.open(path)
frame_av = next(video_av.decode())
height, width = frame_av.height, frame_av.width
print("av", f"{height=}, {width=}")
```

```
torchvision height=240, width=560
av height=240, width=560
```

**Comment by pmeier** [comment]
Closing since this seems to be a usage error. @MohamedAliRashad feel free to re-open if you think there is actually a bug here.

**Comment by MohamedAliRashad** [comment]
@pmeier Did you try my script and saw if it works (change the premute and make it `TCHW`) ?

**Comment by pmeier** [comment]
We don't officially support `cv2` and thus also can't provide any support for that. 

As for your script I'm not sure what you want to showcase here. `torchvision.io.read_video(..., output_format="THWC").permute(0, 3, 2, 1)` indeed produces TCWH. But this just comes from the permute that you used. If you want `TCHW` either use it as `output_format` directly or use `permute(0, 3, 1, 2)`.

**Comment by MohamedAliRashad** [comment]
@pmeier the usage of cv2 in my script is only to save frames to dist so `read_image` can read them in its way. the `permute` is there for the problem of dimension ordering. you can remove it and add `output_format` and try the script to see if the output of `read_video` is the same of `read_image`.

**Comment by pmeier** [comment]
There is no point for me to run anything if I don't understand your issue. `torchvision.io.read_video` correctly provides `THWC` by default and `TCHW` if you set `output_format="TCHW"`. `torchvision.io.read_image` always provides `TCHW`. Coming back to your original comment:

> The result of `read_video` is not the same of `read_image` with concatenation

Yes and that is expected. If you want this to be the same, set `output_format="TCHW"` in `read_video`.
