### ISSUE TITLE
Possible mistake in Inception_v3 model

### ISSUE THREAD

**Issue by lijunzh** [pytorch/vision#798]
https://github.com/pytorch/vision/blob/71322cba652b4ba7bcaa7ae5ee86f539d1ae3a2b/torchvision/models/inception.py#L143-L144

This is inconsistent with Figure 5 of the Inception V3 [paper](https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Szegedy_Rethinking_the_Inception_CVPR_2016_paper.pdf).

The correct implementation IMHO should be
```python
self.branch3x3_1 = BasicConv2d(in_channels, 48, kernel_size=1)
self.branch3x3_2 = BasicConv2d(48, 64, kernel_size=3, padding=1)
```

**Comment by TheCodez** [comment]
The model was converted from [TensorFlow](https://github.com/tensorflow/models/blob/master/research/slim/nets/inception_v3.py), so it follows their implementation of the network.

Suprisingly most of the Inception models from TensorFlow seem to differ from the paper definition, see GoogLeNet for another example.

**Comment by lijunzh** [comment]
> Suprisingly most of the Inception models from TensorFlow seem to differ from the paper definition, see GoogLeNet for another example.

That's good to know. Thanks.
