### ISSUE TITLE
ONNX tests fail due to upstream bug

### ISSUE THREAD

**Issue by pmeier** [pytorch/vision#7980]
For example https://github.com/pytorch/vision/actions/runs/6259955045?pr=7979#summary-16997013188

This was introduced in the `1.16.0` release that was published yesterday. See microsoft/onnxruntime#17631

cc @neginraoof @justinchuby @seemethere

**Comment by pmeier** [comment]
From the linked thread it seems that we just need to exclude `1.16.0` from the installed versions.

**Comment by thiagocrepaldi** [comment]
Let's fix vision to use the correct format with https://github.com/pytorch/vision/pull/7982
