### ISSUE TITLE
Skewed aspect ratio distribution for non-symmetrical aspect ratios in RandomResizedCrop.

### ISSUE THREAD

**Issue by mzient** [pytorch/vision#800]
The fix for RandomResizedCrop protects against producing crop windows with incorrect aspect ratio (unless 1:1 ratio is not in range - in which case it may fail in fallback code).

To illustrate I'll use an extreme examples that never swap width and height, as it would make the example harder to interpret.

Ratio range 0.1 to 1 has a mean of 0.55.
Ratio range 1 to 10 has a mean of 5.5.
The expected result is for the two means to be reciprocals.

A proposed solution is to use uniform distribution on a logarithmic scale.
The means will then be:
`exp((log(0.1) + log(1)) / 2) = 0.60653065971`
`exp((log(1) + log(10)) / 2) = 1.6487212707 = 1/0.60653065971`

See PR for a proposed solution: #799

**Comment by fmassa** [comment]
Fixed by https://github.com/pytorch/vision/pull/799
