### ISSUE TITLE
import _portaudio as pa  ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by Ashu-jun** [pytorch/vision#801]
please help me to resolve this issue.
import speech_recognition as sr
import pyaudio

# obtain audio from the microphone
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)
    print("Time is over, THANKS")
try:
   
    print("Google Speech Recognition thinks you said " + r.recognize_google(audio))
except:
    pass

**Comment by fmassa** [comment]
I believe you are in the wrong repo, this is for computer vision.
