### ISSUE TITLE
Transforms.v2 significantly slower than v1.

### ISSUE THREAD

**Issue by yophis** [pytorch/vision#8010]
### 🐛 Describe the bug

Usage of v2 transformations in data preprocessing is roughly three times slower compared to the original v1's transforms.

I benchmarked the dataloader with different workers using following code.
```python
import time

train_dataset = ImageFolder(os.path.join(dataset_path, 'train'), transform=transform)
for i in range(0, 16+2, 2):
    _loader = DataLoader(train_dataset, batch_size=256, pin_memory=True, shuffle=True, num_workers=i)
    start = time.time()
    for _ in range(3):
        for _ in _loader:
            pass
    end = time.time()
    print('Um:', i, 'used up to', end-start, 's')  # 'i' is worker count.
```

For instance, the following transform composition.
```python
import torchvision
import torchvision.transforms as T
import torchvision.transforms.v2 as T2

transform = T2.Compose([
    T2.RandomResizedCrop(size=(224, 224), scale=(0.45, 1.0), ratio=(0.3, 1.7), interpolation=T.InterpolationMode.BICUBIC),
    T2.ToImage(),
    T2.RandomRotation((0, 90), fill=0, interpolation=T.InterpolationMode.BILINEAR),
    T2.RandomHorizontalFlip(p=0.5),
    T2.RandomVerticalFlip(p=0.5),
    T2.RandomPerspective(distortion_scale=0.7, p=0.7, interpolation=T.InterpolationMode.BILINEAR),
    # T.ElasticTransform(alpha=50.0, interpolation=T.InterpolationMode.BILINEAR),
    # T.ColorJitter(brightness=(0.8, 1.2), contrast=(0.8, 1.2), saturation=(0.8, 1.2)),
    T2.ToDtype(torch.float32, scale=True),
    T2.Normalize(mean=[0.4850, 0.4560, 0.4060], std=[0.2290, 0.2240, 0.2250])
    # T.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

```

Resulted in
Um: 0 used up to 106.77883172035217 s
Um: 2 used up to 52.07573485374451 s
Um: 4 used up to 30.727416515350342 s
Um: 6 used up to 30.47186279296875 s
Um: 8 used up to 30.879201412200928 s
Um: 10 used up to 32.75243401527405 s
Um: 12 used up to 30.88376259803772 s
Um: 14 used up to 31.688957929611206 s
Um: 16 used up to 31.99822759628296 s

While transforms v1 yielded only around 9s having workers > 4.

My routinely used CNN training pipeline which usually takes only half an hour, also shot up to 5 hours after switching to transforms.v2.
In addition, all v1 composition with just an addition of following augmix and mixup took 5 hours as well.
```python
mixup = T2.MixUp(num_classes=NUM_FINETUNE_CLASSES)
cutmix = T2.CutMix(num_classes=NUM_FINETUNE_CLASSES)
mixer = T2.RandomChoice([mixup, cutmix])
.
.
.
    f1_metric = MulticlassF1Score(num_classes=NUM_FINETUNE_CLASSES, average='macro', device=device)
    model.train()
    for image, label in train_loader:
        image, label = image.to(device), label.to(device)
        image, label = mixer(image, label)
```

I've experimented several other transform compositions; such as using T2.ToTensor() instead of T2.ToImage() and T2.ToDtype(), different orders, and different combinations. All of them have the same performance problem.

PS.
The code is hosted on a jupyter notebook running on a 16 cores AMD EPYC™ 7713 and a Nvidia A100.
The env information below is collected on the frontend node, there actually is cuda in GPU node I'm using. With Driver Version: 515.65.01 and CUDA Version: 11.7.

### Versions

PyTorch version: 2.2.0.dev20231001+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: SUSE Linux Enterprise Server 15 SP4 (x86_64)
GCC version: (SUSE Linux) 7.5.0
Clang version: 15.0.1  (66f7391d6a03cf932f321b9f6b1d8612ef5f362c)
CMake version: version 3.20.4
Libc version: glibc-2.31

Python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.14.21-150400.24.11_12.0.57-cray_shasta_c-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   48 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          128
On-line CPU(s) list:             0-127
Vendor ID:                       AuthenticAMD
Model name:                      AMD EPYC 7543 32-Core Processor
CPU family:                      25
Model:                           1
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
Stepping:                        1
Frequency boost:                 enabled
CPU max MHz:                     2800.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        5589.64
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca
Virtualization:                  AMD-V
L1d cache:                       2 MiB (64 instances)
L1i cache:                       2 MiB (64 instances)
L2 cache:                        32 MiB (64 instances)
L3 cache:                        512 MiB (16 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.0
[pip3] pytorch-triton==2.1.0+6e4932cda8
[pip3] torch==2.2.0.dev20231001+cu121
[pip3] torchaudio==2.0.2
[pip3] torcheval==0.0.6
[pip3] torchinfo==1.8.0
[pip3] torchtnt==0.2.0
[pip3] torchvision==0.17.0.dev20231001+cu121
[pip3] torchviz==0.0.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h213fc3f_46343  
[conda] mkl-service               2.4.0           py310h5eee18b_1  
[conda] mkl_fft                   1.3.8           py310h5eee18b_0  
[conda] mkl_random                1.2.4           py310hdb19cb5_0  
[conda] numpy                     1.25.0          py310h5f9d8c6_0  
[conda] numpy-base                1.25.0          py310hb5e798b_0  
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch-triton            2.1.0+6e4932cda8          pypi_0    pypi
[conda] torch                     2.2.0.dev20231001+cu121          pypi_0    pypi
[conda] torchaudio                2.0.2               py310_cu118    pytorch
[conda] torcheval                 0.0.6                    pypi_0    pypi
[conda] torchinfo                 1.8.0                    pypi_0    pypi
[conda] torchtnt                  0.2.0                    pypi_0    pypi
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.17.0.dev20231001+cu121          pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi

**Comment by NicolasHug** [comment]
Thanks for the report @yophis 

Could you please provide a minimal reproducing example so that we can easily re-run your experiments? The transforms you provided above only work for V2, not for V1 (typically ToImage() or ToDtype). So it's hard to understand what got compared to what, exactly.

Note that I tried to port your example above the the following below, and I cannot observe any slow-down in V2:

```py
#%%
import torch

import torchvision
import torchvision.transforms.v2 as T2
import torchvision.transforms as T1

def get_transforms(use_v2):
    T = T2 if use_v2 else T1
    transforms = []

    transforms += [
        T.RandomResizedCrop(size=(224, 224), scale=(0.45, 1.0), ratio=(0.3, 1.7), interpolation=T.InterpolationMode.BICUBIC, antialias=True),
        T.RandomRotation((0, 90), fill=0, interpolation=T.InterpolationMode.BILINEAR),
        T.RandomHorizontalFlip(p=0.5),
        T.RandomVerticalFlip(p=0.5),
        T.RandomPerspective(distortion_scale=0.7, p=0.7, interpolation=T.InterpolationMode.BILINEAR),
    ]

    if use_v2:
        transforms += [T.ToDtype(torch.float32, scale=True)]
    else:
        transforms += [T.ConvertImageDtype(torch.float32)]
    
    transforms += [T.Normalize(mean=[0.4850, 0.4560, 0.4060], std=[0.2290, 0.2240, 0.2250])]

    transforms = T.Compose(transforms)
    return transforms

# %%
img = torch.randint(0, 256, size=(3, 256, 256), dtype=torch.uint8)

t1 = get_transforms(use_v2=False)
t2 = get_transforms(use_v2=True)

# %%
%timeit t1(img)
# %%
%timeit t2(img)

# %%

class DS:
    def __init__(self, transforms):
        self.transforms = transforms
    def __getitem__(self, _):
        return self.transforms(torch.randint(0, 256, size=(3, 256, 256), dtype=torch.uint8))
    def __len__(self):
        return 128

from torch.utils.data import DataLoader

dl1 = DataLoader(DS(t1), batch_size=32, num_workers=4)
dl2 = DataLoader(DS(t2), batch_size=32, num_workers=4)
# %%
%timeit list(dl1)
# %%
%timeit list(dl2)
```

**Comment by NicolasHug** [comment]
Also, make sure to follow https://pytorch.org/vision/main/transforms.html#performance-considerations in particular convert to tensor before doing any resizing operation

**Comment by yophis** [comment]
```python
#%%
import torch

import torchvision
import torchvision.transforms.v2 as T2
import torchvision.transforms as T1

# Add ToImage() and switch ConvertImageDtype() to ToTensor()
def get_transforms(use_v2):
    T = T2 if use_v2 else T1
    transforms = [T.RandomResizedCrop(size=(224, 224), scale=(0.45, 1.0), ratio=(0.3, 1.7), interpolation=T.InterpolationMode.BICUBIC, antialias=True)]
    if use_v2:
        transforms += [T.ToImage()]

    transforms += [
        T.RandomRotation((0, 90), fill=0, interpolation=T.InterpolationMode.BILINEAR),
        T.RandomHorizontalFlip(p=0.5),
        T.RandomVerticalFlip(p=0.5),
        T.RandomPerspective(distortion_scale=0.7, p=0.7, interpolation=T.InterpolationMode.BILINEAR),
    ]

    if use_v2:
        transforms += [T.ToDtype(torch.float32, scale=True)]
    else:
        transforms += [T.ToTensor()]
    
    transforms += [T.Normalize(mean=[0.4850, 0.4560, 0.4060], std=[0.2290, 0.2240, 0.2250])]

    transforms = T.Compose(transforms)
    return transforms

# %%
# Use PIL's Image
img = np.random.randint(0, 256, size=(256, 256, 3), dtype=np.uint8)
img = Image.fromarray(img)

t1 = get_transforms(use_v2=False)
t2 = get_transforms(use_v2=True)

# %%
%timeit t1(img)
# %%
%timeit t2(img)

# %%

# Load a image from disk
class DS:
    def __init__(self, transforms):
        self.transforms = transforms
    def __getitem__(self, _):
        # _img = Image.fromarray(np.random.randint(0, 256, size=(256, 256, 3), dtype=np.uint8))
        _img = Image.open('path_to_a_png').convert('RGB')
        return self.transforms(_img)
    def __len__(self):
        return 128

from torch.utils.data import DataLoader

# Enable pin_memory and shuffle
dl1 = DataLoader(DS(t1), batch_size=256, pin_memory=True, shuffle=True, num_workers=4)
dl2 = DataLoader(DS(t2), batch_size=256, pin_memory=True, shuffle=True, num_workers=4)
# %%
%timeit for _ in range(3): list(dl1)
# %%
%timeit for _ in range(3): list(dl2)
```

With a little modification to your code, the timeit result is:
The slowest run took 446.35 times longer than the fastest. This could mean that an intermediate result is being cached.
164 ms ± 393 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
5.44 ms ± 88.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
4.33 s ± 13.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.94 s ± 41 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by yophis** [comment]
Thanks a lot for your helps.
