### ISSUE TITLE
Add support for image_read to take some bytes as an input 

### ISSUE THREAD

**Issue by tchaton** [pytorch/vision#8020]
### 🚀 The feature

Hey there,

For optimisation reasons, I am reading the bytes for a given JPEG image.

I would like to be able to deserialize it using torchvision by providing the bytes directly.

Best,
T.C

### Motivation, pitch

I am encoding several images into a single shard for streaming purposes. Therefore, I can't provide a path to image_read.

### Alternatives

I am using PIL right now and was hoping for speed gains using torchvision

**Comment by NicolasHug** [comment]
Hi @tchaton , I think [`decode_image`](https://pytorch.org/vision/main/generated/torchvision.io.decode_image.html#torchvision.io.decode_image) is what you're looking for. Feel free to re-open if not

**Comment by tchaton** [comment]
Hey @NicolasHug. 

I looked into `decode_image`. This is great in term of raw speed (17 times faster than using PIL) but I would like to be able to use thing slightly differently. 
My images are grouped into one large binary file and I want to read them as fast as possible.

```python
import numpy as np
import torch
from torchvision.io import decode_image
from torchvision.transforms import ToTensor
from time import time
from io import BytesIO
from PIL import Image


t0 = time()
array = np.fromfile("n02110063_14457.JPEG", dtype=np.uint8)
array_torvision = decode_image(torch.from_numpy(array))
print(time() - t0)


t0 = time()
with open("n02110063_14457.JPEG", "rb") as f:
    data = f.read()

inp = BytesIO(data)
array_jpeg = ToTensor()(Image.open(inp))
array_jpeg = (array_jpeg * 255.).to(torch.uint8)
print(time() - t0)

assert torch.equal(array_torvision, array_jpeg)
```

```Out:
0.004034280776977539
0.07298660278320312
```

**Comment by tchaton** [comment]
Hey @NicolasHug, I tried using GPU decoding and this leads to a segmentation fault.

```
t0 = time()
with open("n02110063_14457.JPEG", "rb") as f:
    data = f.read()
array = torch.frombuffer(data, dtype=torch.uint8)
array_torvision = decode_image(array.to("cuda"))
print(time() - t0)
```

**Comment by tchaton** [comment]
Also @NicolasHug, I am not getting the same PyTorch whether I read with PIL or Torchvision. Do you know what I am doing wrong there ?

```python
import numpy as np
import torch
from torchvision.io import decode_jpeg
from torchvision.transforms import ToTensor
from time import time
from io import BytesIO
from PIL import Image
from torchvision.transforms import ToTensor 

with open("n02110063_14457.JPEG", "rb") as f:
    data = f.read()

t0 = time()
with open("n02110063_14457.JPEG", "rb") as f:
    data = f.read()
array = torch.frombuffer(data, dtype=torch.uint8)
array_torvision = decode_jpeg(array)
print(time() - t0)


t0 = time()
img = Image.open("n02110063_14457.JPEG")
array_jpeg = ToTensor()(img)
print(time() - t0)

assert torch.equal(array_torvision, array_jpeg)
```

**Comment by NicolasHug** [comment]
yeaahh... The gpu decoder is still Beta and has a few rough edge-cases (see also https://github.com/pytorch/vision/issues/4378 where it seems to be leaking depending on the CUDA version). Perhaps your best bet is to avoid it for now, or maybe look at https://github.com/itsliupeng/torchnvjpeg
