### ISSUE TITLE
Add support for decoding video from bytes or with offset (begin, end)

### ISSUE THREAD

**Issue by tchaton** [pytorch/vision#8029]
### 🚀 The feature

Similar to [decode_image](https://pytorch.org/vision/main/generated/torchvision.io.decode_image.html#torchvision.io.decode_image), it would be great to support the same mechanism for videos / audios.

### Motivation, pitch

When training in the cloud, it is common practice to binarise or tar files.

Therefore, reading from a file is possible as done within webdataset: https://github.com/webdataset/webdataset/blob/main/webdataset/autodecode.py#L396.

But this adds an overhead and bottleneck training speed. It would be great to support something similar to `image_decode` that takes a tensor but returns the decoded images. Or add `begin, end` offset support to the `read_video`.

Best,
T.C

**Comment by tchaton** [comment]
cc @pmeier @NicolasHug

**Comment by NicolasHug** [comment]
Hi @tchaton , there are the `start_pts` and `end_pts` parameters of `read_video`. Do they do what you need?

We don't have much bandwidth to support the video-decoder code-base ATM unfortunately, and there are a bunch of bugs in these APIs. We've been increasingly directing users to use torchaudio's video decoder instead, as it is more actively maintained https://pytorch.org/audio/stable/generated/torchaudio.io.StreamReader.html#torchaudio.io.StreamReader

**Comment by tchaton** [comment]
Hey [NicolasHug](https://github.com/NicolasHug), unfortunately, `start_pts` and `end_pts` doesn't seem to be what I am looking for. I have 1 big binary file with lot of videos encoded inside. I need to be able to read a single one from that large file.

However, the StreamReader from torch audio seems to support bytes as an input which is very promising. I will give it a try and update you.

Thanks for the pointer !

**Comment by tchaton** [comment]
Ok, this seems to be supported by torchaudio. This is dope ! However, the errors are quite cryptic ahahaha 

<img width="1530" alt="Screenshot 2023-10-12 at 09 59 17" src="https://github.com/pytorch/vision/assets/12861981/5a4a5aa5-8011-468e-b859-4f6fa7264dd4">

**Comment by NicolasHug** [comment]
Great! I'll close the issue then
