### ISSUE TITLE
ImageFolder balancer

### ISSUE THREAD

**Issue by lorenzomassimiani** [pytorch/vision#8048]
### 🚀 The feature

The new feature impacts the file [torchvision/datasets/folder.py](https://github.com/pytorch/vision/blob/main/torchvision/datasets/folder.py).

The idea is to add to the `make_dataset` function a new optional parameter that allows balancing the dataset folder. The new parameter, `sampling_strategy`, can assume the following values: `None` (default), `"oversample"` and `"undersample"`.

|Value| Description|
|---|---|
|`None` | no operation performed on the dataset. This value will be the dafault. |
|`"oversample"`| the dataset will be balanced by adding image path copies of minoritary classes up to the number of the majority class.|
|`"undersample"` | the dataset will be balanced by deleting images path of majority classes up to the number of the minoritary class.|

### Motivation, pitch

While working with an unbalanced dataset, I find extremely useful to balance it at runtime instead of copying/removing images in the filesystem.
After the balanced data folder is defined you can also apply data augmentation when you define the data loader to not use simply image copies and avoid overfitting.

### Alternatives

The implementation can be done in two ways:

1. add the parameter `sampling_strategy` to the `make_dataset` function;
2. define a new class, namely `BalancedImageFolder`, that overwrites the `make_dataset` method in order to define the `sampling` parameter.

We believe that the less impactful way is the first implementation, because, for how the code is currently structured, for overwriting the `make_dataset` method I probably will have to change the structure of the file (because for defining the new `make_balanced_dataset` function I have to copy a lot of code from the original `make_dataset` function, and this is obviously a bad practice).

**Comment by NicolasHug** [comment]
Hi @lorenzomassimiani , thanks for the feature request.

It looks like you're trying to implement a sampling logic. The samplers are typically decoupled from the dataset objects and can instead be [passed as a parameter to the Dataloader](https://pytorch.org/docs/stable/data.html#data-loading-order-and-sampler). Perhaps you can address your use-case by defining a custom Sampler instead?

**Comment by lorenzomassimiani** [comment]
Hi @NicolasHug , thanks for your answer. I will propose a new dedicated sampler for this purpose in the torch repository.
