### ISSUE TITLE
Why in-place operation for ReLU is used in models/examples?

### ISSUE THREAD

**Issue by seungwonpark** [pytorch/vision#807]
Lots of model shown here, e.g. [AlexNet](https://github.com/pytorch/vision/blob/693829121bdc3e26714691f70241c6c01a089457/torchvision/models/alexnet.py), uses in-place operations for `nn.ReLU()` activation.

Howerver, usage of in-place operations are usually discouraged, according to [PyTorch docs.](https://pytorch.org/docs/master/notes/autograd.html#in-place-operations-with-autograd). Is there any reason for using `nn.ReLU(inplace=True)`?

**Comment by fmassa** [comment]
It saves memory.

In-place operations should in general be used with care. The places where we use in-place `ReLU` are safe though.

**Comment by seungwonpark** [comment]
Thank you for responding!

**Comment by songyuc** [comment]
@fmassa , hi, Fancisco,
So, specifically, it will save the GPU memory if I use CUDA, am I right?

**Comment by fmassa** [comment]
@songyuc it will save memory for both CPU and CUDA

**Comment by mrgloom** [comment]
Which cases are not safe?

**Comment by fmassa** [comment]
@mrgloom if you invert the sum with the relu (for pre-activation ResNets) in https://github.com/pytorch/vision/blob/ae228fef1ce176fa3e3949f5db7b6e87a1e33065/torchvision/models/resnet.py#L69-L70 as follows:
```python
out = self.relu(out)
out += identity
```
you have the following error in backward
```python
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [2, 2048, 7, 7]], which is output 0 of ReluBackward1, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**Comment by YueFei0403** [comment]
> @mrgloom if you invert the sum with the relu (for pre-activation ResNets) in
> 
> https://github.com/pytorch/vision/blob/ae228fef1ce176fa3e3949f5db7b6e87a1e33065/torchvision/models/resnet.py#L69-L70
> 
> as follows:
> ```python
> out = self.relu(out)
> out += identity
> ```
> 
> you have the following error in backward
> 
> ```python
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [2, 2048, 7, 7]], which is output 0 of ReluBackward1, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> ```

Hi @fmassa, 

I currently encountered this issue when I was trying to build a ResNet bottleneck block. Can I ask how to  solve it? Thanks!
