### ISSUE TITLE
ROCM binaries aren't built with jpeg support

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#8079]
The jobs started failing on this line:

```
torch.ops.image._jpeg_version() = -1
  File "pytorch/vision/test/smoke_test.py", line 86, in main
    assert torch.ops.image._is_compiled_against_turbo()
AssertionError
```

but the error originates from [this line](https://github.com/pytorch/vision/actions/runs/6689636924/job/18173518851#step:12:260)

> Building torchvision without JPEG image support

This is happening on both `main` **and** on the release branch, so we need to fix this before the bugfix release.

CC @atalman 

cc @jeffdaily @jithunnair-amd

**Comment by jeffdaily** [comment]
#8080 did not fix this.  What are our next steps?

**Comment by jeffdaily** [comment]
Do we need to regenerate the pytorch/manylinux-builder:rocm5.6 image?  Is it a problem in this image?

**Comment by NicolasHug** [comment]
@jeffdaily honestly I'm not sure. Nothing has changed on the torchvision side so the problem likely comes from somewhere else. I have asked our release engineering team to take a look.

**Comment by malfet** [comment]
I guess problem is longstanding, but docker update actually cased an issue. 
@jeffdaily speaking of, do you run any tests on your end after final release candidate has been build?

**Comment by jeffdaily** [comment]
@malfet no, we don't run any tests on our end.  We rely on upstream CI infra in this case.

**Comment by NicolasHug** [comment]
OK, if this is a docker issue then I think we'll have to disable those tests on torchvision until this gets resolved. I'll keep this issue open, LMK if there is any progress on this!

**Comment by NicolasHug** [comment]
OK, looks like the latest Rocm builds + smoke tests are fine on `main` and the release branch now.

Probably fixed by https://github.com/pytorch/builder/pull/1575 ? Thanks a ton @huydhn!
