### ISSUE TITLE
Build torchvision from source failed

### ISSUE THREAD

**Issue by zhy007a** [pytorch/vision#8084]
### 🐛 Describe the bug

I build torchvision v0.13.0 from source following the steps below:
```
$ sudo apt-get install libjpeg-dev zlib1g-dev libpython3-dev libopenblas-dev libavcodec-dev libavformat-dev libswscale-dev
$ git clone https://github.com/pytorch/vision.git
$ git checkout release/0.13
$ cd vision
$ export BUILD_VERSION=0.13.0 
$ python3 setup.py install 
```
And I got an error:
```
/home/vision/torchvision/csrc/ops/quantized/cpu/qnms_kernel.cpp:2:10: fatal error: ATen/native/quantized/affine_quantizer.h: No such file or directory
    2 | #include <ATen/native/quantized/affine_quantizer.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0a0+08820cb0.nv22.07
Is debug build: False
CUDA used to build PyTorch: 11.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (aarch64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, May 26 2023, 14:05:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.10.104-tegra-aarch64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: 
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       4
Vendor ID:                       Nvidia
Model:                           0
Model name:                      ARMv8 Processor rev 0 (v8l)
Stepping:                        0x0
CPU max MHz:                     2035.2000
CPU min MHz:                     115.2000
BogoMIPS:                        62.50
L1d cache:                       512 KiB
L1i cache:                       1 MiB
L2 cache:                        8 MiB
L3 cache:                        4 MiB
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Branch predictor hardening
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm dcpop

Versions of relevant libraries:
[pip3] torch==1.13.0a0+08820cb0.nv22.7
[conda] Could not collect

**Comment by NicolasHug** [comment]
There's an offset between the compatible versions of torch and torchvision: for torchvision 0.13 you'll need torch 1.12. See "older versions" in our readme https://github.com/pytorch/vision
