### ISSUE TITLE
draw_bounding_boxes and save_image  require different input dtype

### ISSUE THREAD

**Issue by SeucheAchat9115** [pytorch/vision#8138]
Hi, when using draw_bounding boxes an image torch.tensor needs to be converted to uint8 dtype because the function expects that dtype. When inserting the image with drawn boxes to save_image, it needs to be converted back to float32 dtype. Can this be changed to easily insert the images to both functions without type conversion?

**Comment by SeucheAchat9115** [comment]
I think I have no capacity to do that.

**Comment by GsnMithra** [comment]
Hey @NicolasHug 

Can you please re-open this issue? I have lined up a new PR #8276 

Thank you!
