### ISSUE TITLE
box_convert should accept values of BoundingBoxFormat as in- and output-format as well as case-insensitive string versions.

### ISSUE THREAD

**Issue by bmmtstb** [pytorch/vision#8190]
### 🚀 The feature

The function torchvision.ops.box_convert() should accept instances of `tv_tensors.BoundingBoxFormat` as well as their respective case-insensitive stringified versions as types for `in_fmt` and `out_fmt`.

And therefore accepting all values of the BoundingBoxFormat-Enum without redefining them in a separate place:
https://github.com/pytorch/vision/blob/ae6b134c6b395d81916ad47c08b5c64373a6afc5/torchvision/ops/boxes.py#L191

### Motivation, pitch

We have some given bounding boxes created with an arbitrary format, potentially unknown to us.
```
bboxes = tv_tensors.BoundingBoxes(torch.rand((10, 4)), canvas_size=(10, 10), format=tv_tensors.BoundingBoxFormat.XYWH)
```
Later in another part of the code we need to have a specific (potentially different) format to continue execution. The easiest way would be to call
```
new_bboxes = box_convert(bboxes, bboxes.format, "XYXY")
```
but that is not possible, because the `box_convert()` function only accepts `str` as input format, not the enum value of `tv_tensors.BoundingBoxFormat` itself and will raise a `ValueError` instead.
[Knowing](https://stackoverflow.com/a/24487545/5889825) that the value of an enum can be retrieved using the `.value` attribute, the above code can be modified to work, but that does not really seem to be the intended solution.
```
new_bboxes = box_convert(bboxes, bboxes.format.value.lower(), "xyxy")
```
First of all, only lower-case values are accepted, which is contrary to the enum values, second if the enum is accepting further formats in the future, there are two separate places that need to be updated.

### Alternatives

There might be a special case when modifying a bbox object, to let `in_fmt` be `None` and use the format of the given bbox, because this box can only have a valid format.

### Additional context

A few more cases that should be valid inputs for the in and out format:

```
in_fmt = "XYXY"
in_fmt = "xyxy"
in_fmt = bboxes.format
in_fmt = BoundingBoxFormat.XYXY
```

**Comment by NicolasHug** [comment]
Thanks for the feature request @bmmtstb. The existence of `box_convert` predates the existence of the `tv_tensors.BoundingBoxes` class, so there are indeed some friction points. We should try to make those interact better, but perhaps[ `torchvision.transforms.v2.functional.convert_bounding_box_format`](https://pytorch.org/vision/main/generated/torchvision.transforms.v2.functional.convert_bounding_box_format.html#torchvision.transforms.v2.functional.convert_bounding_box_format) is what you're looking for?

**Comment by bmmtstb** [comment]
I "solved" it for my own use case using the `format.value.lower()` approach.
I just wanted someone to look into it and whether or not it is planned to be changed. Potentially I will even try to create my first PR for torch myself, iff you think it would be wise to implement this.

**Comment by NicolasHug** [comment]
Thanks @bmmtstb  - we'd love for you to send a PR but before that we just need to make sure that [`convert_bounding_box_format`](https://pytorch.org/vision/main/generated/torchvision.transforms.v2.functional.convert_bounding_box_format.html#torchvision.transforms.v2.functional.convert_bounding_box_format) doesn't already solve your problem - because that's the recommended way to convert `BoundingBoxes` objects, so if it already does the job, there's probably no need to touch the utils from `ops/boxes.py`.

**Comment by bmmtstb** [comment]
Oh, my bad. I think I missunderstand your first message. Yes, `convert_bounding_box_format` does solve my issue, which makes the old `box_convert` obsolete in my opinion.

Funny enough I used the functional already somewhere else and only used `box_convert` in this case because I saw it in the [box-operators](https://pytorch.org/vision/main/ops.html#box-operators), while searching for bbox IoU which requires the boxes to be in a specific format.

**Comment by NicolasHug** [comment]
Thanks for your feedback @bmmtstb . I think your experience suggests that we should update the docs of `box_convert` and point towards `convert_bounding_box_format` for users who need to convert `BoundingBoxes` objects. Would you be interested in sending a PR for that?

**Comment by bmmtstb** [comment]
Within `torchvision.ops.boxes` I added the following warnings:

- [X] `box_convert` to point towards [`torchvision.transforms.v2.functional.convert_bounding_box_format`](https://pytorch.org/vision/main/generated/torchvision.transforms.v2.functional.convert_bounding_box_format.html#torchvision.transforms.v2.functional.convert_bounding_box_format) and [`torchvision.transforms.v2.ConvertBoundingBoxFormat`](https://pytorch.org/vision/main/generated/torchvision.transforms.v2.ConvertBoundingBoxFormat.html#torchvision.transforms.v2.ConvertBoundingBoxFormat)
- [X] `remove_small_boxes` to point towards [`torchvision.transforms.v2.SanitizeBoundingBoxes`](https://pytorch.org/vision/main/generated/torchvision.transforms.v2.SanitizeBoundingBoxes.html#torchvision.transforms.v2.SanitizeBoundingBoxes)
- [X] `clip_boxes_to_image` to point to [`torchvision.transforms.v2.ClampBoundingBoxes`](https://pytorch.org/vision/main/generated/torchvision.transforms.v2.ClampBoundingBoxes.html#torchvision.transforms.v2.ClampBoundingBoxes)
- [X] `box_area` to point to `torchvision.transforms.v2.functional.get_size` but that does not have a documentation (yet) even though it is made public in `__init__`, See
https://github.com/pytorch/vision/blob/f52fd335000fa4d91371e8505749cd7ce9249cf8/torchvision/transforms/v2/functional/__init__.py#L24

---

I could not find new final versions of `masks_to_boxes` (Issue https://github.com/pytorch/vision/issues/8184 or PR https://github.com/pytorch/vision/pull/8194) and all the nms and iou methods. Even though it might be wise to have tv_tensors versions of those too.

**Comment by NicolasHug** [comment]
Thanks a lot for the report and for the PR @bmmtstb !
