### ISSUE TITLE
`pr-labels `job is failing on CI

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#8224]
Our "PR label bot" hasn't been commenting on PRs for a bit. Looks like it's broken https://github.com/pytorch/vision/actions/workflows/pr-labels.yml

```
Run mshick/add-pr-comment@v1
  with:
    message: Hey @NicolasHug!
  
  You merged this PR, but no labels were added. The list of valid labels is available at https://github.com/pytorch/vision/blob/main/.github/process_commit.py
  
    allow-repeats: false
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.12.1/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.1/x64/lib
    GITHUB_TOKEN: ***
Error: Resource not accessible by integration

```

(Note that https://github.com/pytorch/vision/pull/8221 is related but the pr-labels action was broken before this was merged)

**Comment by NicolasHug** [comment]
CC @pmeier in case this is something you have time looking into - but no worries if not

**Comment by Bhavay-2001** [comment]
Hi @NicolasHug, is this a beginner friendly issue? If yes, can I work on this?

**Comment by NicolasHug** [comment]
Hi @Bhavay-2001 unfortunately no, this isn't really beginner friendly

**Comment by Bhavay-2001** [comment]
Hi @NicolasHug, it would be great if you could suggest me some beginner friendly issues to start with. 
Thanks
