### ISSUE TITLE
Update RCNN-family docstrings

### ISSUE THREAD

**Issue by rizavelioglu** [pytorch/vision#8228]
This issue is about docstrings in `MaskRCNN`, `FasterRCNN`, `RegionProposalNetwork` classes. Since it's not a bug, or a documentation (../index.html) issue, I opened a blank issue.

### Issue
- I think the `rpn_score_thresh` argument is wrongly defined in both `MaskRCNN` & `FasterRCNN` docstrings;
https://github.com/pytorch/vision/blob/6f0deb9bccf27ab99e1e5553aa7c6645416c5a34/torchvision/models/detection/mask_rcnn.py#L87-L88
probably because of simple copy/paste from `box_score_thresh` argument, which is correctly defined:https://github.com/pytorch/vision/blob/6f0deb9bccf27ab99e1e5553aa7c6645416c5a34/torchvision/models/detection/mask_rcnn.py#L94-L95
- and the `score_thresh` argument is missing in the `RegionProposalNetwork` docstring:
https://github.com/pytorch/vision/blob/6f0deb9bccf27ab99e1e5553aa7c6645416c5a34/torchvision/models/detection/rpn.py#L158

### Possible fix:
- Update both docstrings in `mask_rcnn.py` and `faster_rcnn.py` for the argument:
```python
"""
rpn_score_thresh (float): only return proposals with an objectness score greater than rpn_score_thresh
"""
```
- And in `rpn.py`, add the following argument inside the docstring:
```python
"""
score_thresh (float): only return proposals with an objectness score greater than score_thresh
"""
```

### Explanation:
Both arguments (`rpn_score_thresh` & `box_score_thresh`) are first passed to `FasterRCNN`:
https://github.com/pytorch/vision/blob/6f0deb9bccf27ab99e1e5553aa7c6645416c5a34/torchvision/models/detection/mask_rcnn.py#L227-L252
where `rpn_score_thresh` is passed to `RegionProposalNetwork`:
https://github.com/pytorch/vision/blob/6f0deb9bccf27ab99e1e5553aa7c6645416c5a34/torchvision/models/detection/faster_rcnn.py#L234-L244
and `box_score_thresh` is passed to `RoIHeads`:
https://github.com/pytorch/vision/blob/6f0deb9bccf27ab99e1e5553aa7c6645416c5a34/torchvision/models/detection/faster_rcnn.py#L259-L269

In `RegionProposalNetwork` (here the `score_thresh` argument is missing in the docstring), `rpn_score_thresh` is used inside `filter_proposals` function to filter proposals based on the **objectness score**:
https://github.com/pytorch/vision/blob/6f0deb9bccf27ab99e1e5553aa7c6645416c5a34/torchvision/models/detection/rpn.py#L271-L284
and the `filter_proposals` function is used during **both training and inference**:
https://github.com/pytorch/vision/blob/6f0deb9bccf27ab99e1e5553aa7c6645416c5a34/torchvision/models/detection/rpn.py#L372
Hence, the docstring should change from: "**during inference**, only return proposals with a **classification** score greater than rpn_score_thresh" to: "only return proposals with an **objectness** score greater than rpn_score_thresh"

---

In `RoIHeads`, `box_score_thresh` is used inside `postprocess_detections`:
https://github.com/pytorch/vision/blob/6f0deb9bccf27ab99e1e5553aa7c6645416c5a34/torchvision/models/detection/roi_heads.py#L707-L708
and the `postprocess_detections` is only executed during inference:
https://github.com/pytorch/vision/blob/6f0deb9bccf27ab99e1e5553aa7c6645416c5a34/torchvision/models/detection/roi_heads.py#L767-L775
Hence, the docstring is correct for `box_score_thresh`.

---

In case my observations are correct, I would be glad to submit a PR.

**Comment by NicolasHug** [comment]
Thanks a lot for the detailed report @rizavelioglu, I think you're 100% correct! We'd love to review your PR. On top of MaskRCNN and FasterRCNN, it looks like this is affecting MaskRCNN as well?
