### ISSUE TITLE
RuntimeError: "nms_kernel" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by troymyname** [pytorch/vision#8241]
### 🐛 Describe the bug

I have posted this question in SO. Please have a look here: [LINK](https://stackoverflow.com/questions/77897091/pytorch-runtimeerror-during-fine-tuning-a-keypoint-detection-network-nms-kerne).

### Versions

PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.11.7 (main, Jan 27 2024, 23:30:42) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA RTX A5000
Nvidia driver version: 537.70
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              40
On-line CPU(s) list: 0-39
Thread(s) per core:  2
Core(s) per socket:  20
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6242R CPU @ 3.10GHz
Stepping:            7
CPU MHz:             3092.249
BogoMIPS:            6184.49
Virtualization:      VT-x
Hypervisor vendor:   Microsoft
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512_vnni flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] cjm-pytorch-utils==0.0.6
[pip3] cjm-torchvision-tfms==0.0.5
[pip3] numpy==1.26.3
[pip3] onnx==1.15.0
[pip3] onnx-simplifier==0.4.35
[pip3] onnxruntime==1.16.3
[pip3] torch==2.1.2
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] Could not collect

**Comment by NicolasHug** [comment]
Sorry @troymyname this is not actionable. There is no code snippet of what might be failing. 

Looking at 

```
  File "/home/.../venv/lib/python3.11/site-packages/torchvision/models/detection/roi_heads.py", line 36, in fastrcnn_loss
    sampled_pos_inds_subset = torch.where(labels > 0)[0]
 ```
 
 it is possible that you're passing incorrect data, but it's impossible to tell without a reproducing example. 

> One particular thing I ran into while solving this is the following GitHub page that talks about running Non-Maximum Suppression (NMS) on GPU; here's the [link](https://github.com/pytorch/vision/issues/392). I am wondering if the problem I am having is related to this

No, that's not related
