### ISSUE TITLE
Dataset Missing Label Components - DTD

### ISSUE THREAD

**Issue by dactylroot** [pytorch/vision#8242]
### 🐛 Describe the bug

The dataset "Describable Textures Dataset" is missing its class labels. It contains numeric identifiers used for running code, but any human-interpretable label is absent.

e.g., if the following list was added to the dataset class, users would have the entire label descriptions according to the dataset originator:

labels = [
                       'banded'
                    ,  'blotchy'
                    ,  'braided'
                    ,  'bubbly'
                    ,  'bumpy'
                    ,  'chequered'
                    ,  'cobwebbed'
                    ,  'cracked'
                    ,  'crosshatched'
                    ,  'crystalline'
                    ,  'dotted'
                    ,  'fibrous'
                    ,  'flecked'
                    ,  'freckled'
                    ,  'frilly'
                    ,  'gauzy'
                    ,  'grid'
                    ,  'grooved'
                    ,  'honeycombed'
                    ,  'interlaced'
                    ,  'knitted'
                    ,  'lacelike'
                    ,  'lined'
                    ,  'marbled'
                    ,  'matted'
                    ,  'meshed'
                    ,  'paisley'
                    ,  'perforated'
                    ,  'pitted'
                    ,  'pleated'
                    ,  'polka-dotted'
                    ,  'porous'
                    ,  'potholed'
                    ,  'scaly'
                    ,  'smeared'
                    ,  'spiralled'
                    ,  'sprinkled'
                    ,  'stained'
                    ,  'stratified'
                    ,  'striped'
                    ,  'studded'
                    ,  'swirly'
                    ,  'veined'
                    ,  'waffled'
                    ,  'woven'
                    ,  'wrinkled'
                    ,  'zigzagged'
                    ]

### Versions

        $ python collect_env.py 
        Collecting environment information...
        PyTorch version: 2.0.1
        Is debug build: False
        CUDA used to build PyTorch: None
        ROCM used to build PyTorch: N/A
        
        OS: macOS 14.2.1 (x86_64)
        GCC version: Could not collect
        Clang version: 15.0.0 (clang-1500.1.0.2.5)
        CMake version: version 3.28.1
        Libc version: N/A
        
        Python version: 3.8.16 (default, Jan  5 2023, 10:15:06)  [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
        Python platform: macOS-14.2.1-x86_64-i386-64bit
        Is CUDA available: False
        CUDA runtime version: No CUDA
        CUDA_MODULE_LOADING set to: N/A
        GPU models and configuration: No CUDA
        Nvidia driver version: No CUDA
        cuDNN version: No CUDA
        HIP runtime version: N/A
        MIOpen runtime version: N/A
        Is XNNPACK available: True
        
        CPU:
        Apple M1
        
        Versions of relevant libraries:
        [pip3] mypy-extensions==1.0.0
        [pip3] numpy==1.24.1
        [pip3] pytorch-lightning==2.0.2
        [pip3] torch==2.0.1
        [pip3] torchaudio==2.0.2
        [pip3] torchmetrics==0.11.4
        [pip3] torchvision==0.15.2
        [conda] Could not collect

**Comment by NicolasHug** [comment]
Hi @dactylroot 

This should be accessible via the `.classes` attribute:

```
[ins] In [3]: ds = DTD(root="/tmp", download=True)

[ins] In [4]: ds.classes
Out[4]: 
['banded',
 'blotchy',
 'braided',
 'bubbly',
...
```

LMK if that's not the case

**Comment by dactylroot** [comment]
That totally IS the case.
