### ISSUE TITLE
Clarify `TVTensor` shapes

### ISSUE THREAD

**Issue by mantasu** [pytorch/vision#8260]
### 📚 The doc issue

[`TVTensor`](https://github.com/pytorch/vision/blob/4c0f44145792adca866a1668a79f2e11ed966491/torchvision/tv_tensors/_tv_tensor.py#L15) is documented as being a subclass of `torch.Tensor` specifically for transforms. Perhaps it could be added that they only constrain the shape of `torch.Tensor`?

For example, I only use the utility functions of `transforms.v2` and, when [`to_image`](https://github.com/pytorch/vision/blob/4c0f44145792adca866a1668a79f2e11ed966491/torchvision/transforms/v2/functional/_type_conversion.py#L11) referred me to [`Image`](https://github.com/pytorch/vision/blob/4c0f44145792adca866a1668a79f2e11ed966491/torchvision/tv_tensors/_image.py#L11), I still had to check the source code to confirm it is just a `torch.Tensor` of shape `(C x H x W)`.

**Comment by NicolasHug** [comment]
Hi @mantasu , we've added the main relevant info about TVTensors in this tutorial https://pytorch.org/vision/main/auto_examples/transforms/plot_transforms_getting_started.html#what-are-tvtensors  which is linked to as the main entrypoint for all things related to TVTensors / TransformsV2. Do you think it already contains the info you were looking for, or should we edit it a bit?

**Comment by mantasu** [comment]
My only suggestion would be to add somewhere that `TVTensors` are just extensions of `torch.Tensor` with specified shape constraints. But it is just a preference and the tutorial already helps a lot, so this could be safely closed~
