### ISSUE TITLE
Add 3.12 CI jobs

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#8293]
The next version should support 3.12 so we should make sure to cover that in our CI jobs. 

Let's also merge https://github.com/pytorch/vision/pull/8119 and https://github.com/pytorch/vision/pull/8280

Just delaying this a bit until https://github.com/pytorch/vision/issues/8292 is managed.

Note: 3.8 removal won't happen before 2.4 https://github.com/pytorch/pytorch/issues/120718

**Comment by hmaarrfk** [comment]
Very excited about this.

I'm not sure if the pytorch deprecation warnings were handled by pytorch itself, but I wanted to point to an obscur error message that we "addressed"

the AST in python 3.12 issues a few warnings to pytorch, so with the strict warning catching of some of the tests, the test suite doesn't pass with 3.12.

We relaxed them with a small patch

https://github.com/conda-forge/torchvision-feedstock/blob/b88453f2b521986e5f3d52ac4e626ccf94046adb/recipe/ignore_python312_deprecation_warnings.patch

```patch
diff --git a/test/test_transforms_v2_refactored.py b/test/test_transforms_v2_refactored.py
index e18beb35a4..142e3f2d43 100644
--- a/test/test_transforms_v2_refactored.py
+++ b/test/test_transforms_v2_refactored.py
@@ -416,7 +416,10 @@ def reference_affine_bounding_boxes_helper(bounding_boxes, *, affine_matrix, new
 
 
 # turns all warnings into errors for this module
-pytestmark = pytest.mark.filterwarnings("error")
+pytestmark = [
+    pytest.mark.filterwarnings("error"),
+    pytest.mark.filterwarnings("ignore::DeprecationWarning"),
+]
 
 
 class TestResize:
```

**Comment by NicolasHug** [comment]
Thanks a lot for the headsup @hmaarrfk , I'm observing the same issue in https://github.com/pytorch/vision/pull/8299. Let's see if https://github.com/pytorch/vision/pull/8299/commits/ffd7bd5c129b2cc4dc0d9c58df3d19134ba83688 can address that.

**Comment by NicolasHug** [comment]
All done in https://github.com/pytorch/vision/pull/8299, we can close this. Thanks @hmaarrfk for the PRs and help with the warnings!
