### ISSUE TITLE
Release 2.3 create release notes for vision, audio and text

### ISSUE THREAD

**Issue by atalman** [pytorch/vision#8323]
Create Draft Release notes to be published during release day:

ETA: M5: External-Facing Content Finalized (4/19/24) <- Draft need to be ready 
M6: Release Day (4/24/24) <- Release day

**Comment by NicolasHug** [comment]
draft release notes are available:

- https://github.com/pytorch/vision/releases
- https://github.com/pytorch/audio/releases
- https://github.com/pytorch/text/releases
