### ISSUE TITLE
torchvision-nightly disappeared from PyPI

### ISSUE THREAD

**Issue by alsrgv** [pytorch/vision#833]
```
$ pip install torchvision_nightly
Collecting torchvision_nightly
--
  | Could not find a version that satisfies the requirement torchvision_nightly (from versions: )
  | No matching distribution found for torchvision_nightly
```

https://pypi.org/project/torchvision-nightly/ shows 404.

**Comment by alsrgv** [comment]
cc @soumith

**Comment by soumith** [comment]
I dont know who was maintaining that package, it was definitely not us.

**Comment by alsrgv** [comment]
Oh, that's interesting. What's the recommended way to install `torch-nightly` + `torchvision`?

**Comment by soumith** [comment]
torch-nightly the usual way, torchvision stable works with torch-nightly. `pip install torchvision --no-deps`.

We dont have torchvision-nightly yet, but torchvision-master can also be `pip install https://github.com/pytorch/vision/archive/master.zip` but it got complicated since 2 days ago, when we merged C++ ops, and we're still figuring out details

**Comment by fmassa** [comment]
Also, note @alsrgv that torchvision master is currently under heavy development, so expect some breaking changes on top of the PRs that have been already merged since the 0.2.2 release.

**Comment by alsrgv** [comment]
@fmassa, thanks for the heads up!

**Comment by lig** [comment]
@soumith btw, this package is mentioned here
https://pytorch.org/get-started/locally/

i.e. choose: Preview (Nightly) / Linux / Pip / Python 3.7 / 10.0
you will get
```
pip install numpy torchvision_nightly
pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html
```

- [ ] Is it ok to use `torchvision` instead of `torchvision_nightly`?
- [ ] Should the instructions be updated?
- [ ] Is it possible to revert `torchvision_nightly` removal from PyPI?

**Comment by soumith** [comment]
I went and looked at some history. `torchvision_nightly` was created and maintained by @stas00
Stas, what happened, why did you delete it?
Do you want us to take over maintainership of it?

**Comment by soumith** [comment]
Stas, others and I discussed it on slack, but I forgot about it until I did a slack search for `torchvision_nightly`

**Comment by soumith** [comment]
also, the slack chat mentions that I was supposed to make it automated, so it's on me and I totally bailed (sorry).

Okay, yea we'll figure out how to auto-push a `torchvision_nightly`

**Comment by stas00** [comment]
Oh, terribly sorry, I had no idea it was still used. I thought I was just cleaning up old files that no longer were used :( I forgot that pypi has that exclusiveness as compared to conda, so I was sure mine was just an old copy.

Yes, please take over it. And if I can be of any help to speed up the recovery please let me know.

Apologies again.

**Comment by stas00** [comment]
@soumith, please let's not drop the ball on this again - please take over this package. Thank you!

**Comment by stas00** [comment]
2 months later with no response - I guess the only way for this to be resolved is for me to remove the package from pypi. Therefore I removed this package from pypi and I'm no longer an owner, so you guys can take over.

**Comment by soumith** [comment]
I pushed the first set of packaging scripts 5 days ago here: https://github.com/pytorch/vision/pull/996
My next step is to hook it up to CircleCI and have auto-push nightlies. I haven't gotten to that step yet.
The whole process was significantly simpler and easier before we introduced C++ ops into torchvision, but after we decided to do so (which was before Apr 13th), it made the whole packaging effort much more complex.

Unfortunately, I am the only release manager across all pytorch repos, along with running a bunch of other things on pytorch, so I am prioritizing as we go. The timeline a bit unfortunate, but it is what it is. if you know anyone interested in and good at packaging, and would like to work on pytorch packaging, let me know ;-)

**Comment by stas00** [comment]
I totally understand, @soumith. The issue for me was a lack of communication - specifically 2 months in waiting and zero followup.  If you were to give me a timeline that were to suite your needs better, I'd have happily waited longer.

And meanwhile, my pypi account was providing a stale package, claiming to be -nightly (which was fine in the fall 2018 when it wasn't changing much), so w/o knowing whether anything will be done about it I made a choice to cut the cord.

The build script I used is here, https://github.com/fastai/fastai/tree/master/builds/custom-pip-builds/torchvision
so it should be easy to push a new release under proper ownership. Just need to automate it to run on a nightly basis.

**Comment by stas00** [comment]
If you're a user that may have stumbled upon this thread before a new `vision-nightly` package gets released and you need a pip install of vision master, do:

`pip install git+https://github.com/pytorch/vision.git`

It'll have the same effect.

**Comment by soumith** [comment]
yes, it was my fault. I didn't think anyone was expecting a response (i misread the situation).

I'll give an ETA this week, and get it to closure by the ETA time.

**Comment by soumith** [comment]
One of the big blockers for this was https://github.com/pytorch/pytorch/issues/19990 which @ezyang has started working on, and that's awesome.

I'm setting the ETA to be October 10th, for no other reason than one of me or @ezyang have bandwidth somewhere after August 8th and before October 10th to work on it.

Out of scope if Windows nightlies.

The work involved is to commit a set .circleci files similar to https://github.com/pytorch/pytorch/tree/master/.circleci that will auto-build and auto-upload every night.

The build matrix here is:

- OSX, Linux
- Python 2.7, 3.5, 3.6, 3.7
- CUDA: cpu, 9.2, 10.1
- conda, pip

Thanks to the last torchvision release and the cleanup @ezyang is doing for the one in 2 weeks, we should have all the build scripts in place without needing to do anymore work.

**Comment by thiagocrepaldi** [comment]
Should this issue be closed? Today users can install torch and torchvision through `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch-nightly`

**Comment by alsrgv** [comment]
Please continue supporting PyPI. Conda is not for everyone :-)

**Comment by thiagocrepaldi** [comment]
> 
> 
> Please continue supporting PyPI. Conda is not for everyone :-)

`pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html` is also available as described at https://pytorch.org/

**Comment by soumith** [comment]
yes, we now have a good release engineer @seemethere , and graduated from arbitrary time donations. we have alarms and smoke tests and stuff in case nightlies stop working.
