### ISSUE TITLE
IMG_EXTENSIONS lost "." for webp

### ISSUE THREAD

**Issue by xialeizhou** [pytorch/vision#835]
```python
#  torchvision/datasets/folder.py
IMG_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.ppm', '.bmp', '.pgm', '.tif', '.tiff', 'webp')
```
 `webp` =>`.webp`

**Comment by surgan12** [comment]
@xialeizhou Thanks for reporting.
Could you send a PR fixing this.

**Comment by Ashok93** [comment]
Can I take this up and send a PR?

**Comment by surgan12** [comment]
@Ashok93 Sure Why not !

**Comment by Ashok93** [comment]
@surgan12 Thanks! Pull request ref https://github.com/pytorch/vision/pull/836

**Comment by fmassa** [comment]
Fixed via #836 
Thanks @Ashok93

**Comment by surgan12** [comment]
@Ashok93  it also has some lint errors .
Can you try and fix them too. ?

**Comment by Ashok93** [comment]
@surgan12 Can you specify the linting issue? I cannot find it and it seems okay.

**Comment by fmassa** [comment]
@surgan12 the linting issues are on my side, no need to fix them now

**Comment by fmassa** [comment]
I'll be fixing the linting issues now
