### ISSUE TITLE
Allow size to equal max_size for resizes on longer edge

### ISSUE THREAD

**Issue by sidijju** [pytorch/vision#8357]
### 🚀 The feature

Allow `max_size == size` in `torchvision.transforms.Resize()`

### Motivation, pitch

`torchvision.transforms.Resize()` does not provide a clean interface for resizing images where the maximum dimension is based off the longer edge.

**Comment by sweber1** [comment]
I would be in favor of exactly this feature as well.
I want to do a resize where I provide the dimension for the longer edge, not the shorter edge.

Did you find another solution, or why did you close the issue immediately?

**Comment by NicolasHug** [comment]
@sweber1 we followed-up with https://github.com/pytorch/vision/issues/8358, this will be available in the next release

**Comment by sweber1** [comment]
> @sweber1 we followed-up with #8358, this will be available in the next release

Ah great, thank you!
