### ISSUE TITLE
Any operation on loaded image segfaults since 0.17.1 on Mac

### ISSUE THREAD

**Issue by twoertwein** [pytorch/vision#8367]
### 🐛 Describe the bug

The following command segfaults on a Mac M2 with torch vision 0.17.1 and 0.17.2 - it works with 0.17.0
`python -c "import torchvision; torchvision.io.read_image('videos/frame0043.jpg', mode=torchvision.io.ImageReadMode.RGB).clone()"`

### Versions

Collecting environment information...
PyTorch version: 2.2.2
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:49:36) [Clang 16.0.6 ] (64-bit runtime)
Python platform: macOS-14.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M2 Pro

Versions of relevant libraries:
[pip3] facetorch==0.5.0
[pip3] numpy==1.26.4
[pip3] torch==2.2.2
[pip3] torchvision==0.17.2
[conda] facetorch                 0.5.0                    pypi_0    pypi
[conda] libopenvino-pytorch-frontend 2024.0.0             hebf3989_4  
[conda] numpy                     1.26.4          py311h7125741_0  
[conda] torch                     2.2.2                    pypi_0    pypi
[conda] torchvision               0.17.2                   pypi_0    pypi

**Comment by atalman** [comment]
@twoertwein could you please post segfault details with stack trace ?

**Comment by twoertwein** [comment]
Something with my conda environment was probably messed up. The segfault went away after removing the conda environment and reinstalling it.
