### ISSUE TITLE
AttributeError: module 'torchvision.transforms' has no attribute 'v2'

### ISSUE THREAD

**Issue by ImahnShekhzadeh** [pytorch/vision#8390]
### 🐛 Describe the bug

I am getting the following error:
> AttributeError: module 'torchvision.transforms' has no attribute 'v2'

### Versions

I am using the following versions:
```python
torch version: 2.2.2, torchvision version: 0.17.2
```

**Comment by NicolasHug** [comment]
Hi @ImahnShekhzadeh , please provide a minimal reproducible example for us to help.
