### ISSUE TITLE
Run all torchvision models in one script.

### ISSUE THREAD

**Issue by leizhenyuan** [pytorch/vision#8394]
### 🚀 The feature

Is there a test script that can run models.

### Motivation, pitch

Hl, i am testing a model migration script from cuda to sycl and i would like to test it on torch vision model set, i would like to know do we have a test script that can run all models in torchvision? like run.py [code](https://github.com/pytorch/benchmark/blob/main/run.py) in torchbenchmark, thanks.

**Comment by NicolasHug** [comment]
Hi @leizhenyuan , there isn't such a script but it should be reasonably easy to port the one you linked to run on torchvision models?
