### ISSUE TITLE
retinanet num_classes includes the background 

### ISSUE THREAD

**Issue by ABCCASa** [pytorch/vision#8432]
### 📚 The doc issue

https://pytorch.org/vision/master/models/generated/torchvision.models.detection.retinanet_resnet50_fpn_v2.html

Hi, I am currently use the retinanet, the documentation says num_classes of retinanet includes the background, but when I look at the source code of RetinaNetClassificationHead, it use a tensor with all zeros to represent background. So do we still need to use index=0 as the background? 
![RetinaNetClassificationHead](https://github.com/pytorch/vision/assets/144005707/f64fdf5c-ac59-4598-bf7f-9af05add3abe)

### Suggest a potential alternative/fix

Maybe num_classes is exclude background?

**Comment by ABCCASa** [comment]
Maybe num_classes is exclude background?

**Comment by NicolasHug** [comment]
Sorry @ABCCASa , I don't understand the question.

> So do we still need to use index=0

What does that refer to?

**Comment by ABCCASa** [comment]
@NicolasHug I mean should we still use index=0 as the background?
for example ["background", "apple", "cat", "bottle", "people"]
or ["apple", "cat", "bottle", "people"]
in faster rcnn the first value should be background, but in retinane maybe not?

**Comment by NicolasHug** [comment]
Does this help: https://github.com/pytorch/vision/issues/4106#issuecomment-1149689846 ?

**Comment by ABCCASa** [comment]
@NicolasHug Yes, Thank you so much.
