### ISSUE TITLE
Add mobilenetv4 support and pretrained models?

### ISSUE THREAD

**Issue by LiYufengzz** [pytorch/vision#8437]
### 🚀 The feature

Google has published the mobilenetv4 model. When will pytorch support it and open the pre-trained model?

### Motivation, pitch

I very much hope to use the latest lightweight backbone

**Comment by ChengpengChen** [comment]
Hi, @LiYufengzz 

I've implemented MobileNetV4 in pytorch, can refer to this. I am trying to reproduce the results though.
https://github.com/ChengpengChen/RepGhostNetV2

The code also provides a comparable backbone, i.e., RepGhostNetV2. Feel free to reach me if you have any concerns.

Thanks

**Comment by LiYufengzz** [comment]
> Hi, @LiYufengzz
> 
> I've implemented MobileNetV4 in pytorch, can refer to this. I am trying to reproduce the results though. https://github.com/ChengpengChen/RepGhostNetV2
> 
> The code also provides a comparable backbone, i.e., RepGhostNetV2. Feel free to reach me if you have any concerns.
> 
> Thanks

Thanks a lot for the reply，I hope you can reproduce the indicators in the paper.

**Comment by NicolasHug** [comment]
Thanks for the feature request @LiYufengzz . We're not planning to add mobiletnetv4 to torchvision so we recommend using third-party implementation like that of @LiYufengzz

**Comment by rwightman** [comment]
`timm` has an (almost) full set of MobileNetV4 weights now https://github.com/huggingface/pytorch-image-models?tab=readme-ov-file#june-12-2024 

Hybrid-large and higher res hybrid-medium still in training.

**Comment by LiYufengzz** [comment]
> `timm` has an (almost) full set of MobileNetV4 weights now https://github.com/huggingface/pytorch-image-models?tab=readme-ov-file#june-12-2024
> 
> Hybrid-large and higher res hybrid-medium still in training.

thanks a lot
