### ISSUE TITLE
cutmix alpha argument in references/classification/transforms.py

### ISSUE THREAD

**Issue by eminorhan** [pytorch/vision#8440]
I believe the `alpha` argument here should be `cutmix_alpha` not `mixup_alpha`: 
https://github.com/pytorch/vision/blob/61d97f41bc209e1407dcfbd685d2ee2da9c1cdad/references/classification/transforms.py#L22

Same issue here as well:
https://github.com/pytorch/vision/blob/61d97f41bc209e1407dcfbd685d2ee2da9c1cdad/references/classification/transforms.py#L24

Just curious: were the pretrained models actually trained using this code? Any chance this might have affected the performance of the pretrained models in any way?

**Comment by NicolasHug** [comment]
Great catch @eminorhan , thanks a lot for the report. Would you like to submit a PR to fix these 2 lines?
