### ISSUE TITLE
Renaming ColorJitter to RandomColorShift or RandomColorJitter

### ISSUE THREAD

**Issue by rasbt** [pytorch/vision#845]
Given the current naming schemes, I find the naming of ColorJitter a bit confusing as it does apply the changes randomly. It would probably be more intuitive to refer to it as RandomColorShift or RandomColorJitter and would suggest renaming it in upcoming PyTorch versions.

**Comment by surgan12** [comment]
@rasbt  , i think ColorJitter  itself signifies the random changes in the brightness, hue of the image.

**Comment by rasbt** [comment]
Hm, yeah, I agree. However, for consistency, I think the "Random" prefix (RandomXXX) like RandomColorShift would be nicer :).

(Please feel free to close if you like.)

**Comment by fmassa** [comment]
I'm not a native English speaker, but I thought that jitter already gave the impression of "random change"?

**Comment by rasbt** [comment]
> but I thought that jitter already gave the impression of "random change"?

Yeah, but since all other classes that involve a random modification are starting with Random, I thought it would be better for consistency. This way, you can easily see all Random* ops in the torchvision module. Like 

- "RandomApply", "RandomChoice", "RandomOrder", "RandomCrop", "RandomHorizontalFlip",
           "RandomVerticalFlip", "RandomResizedCrop", "RandomSizedCrop", "RandomRotation", "RandomAffine", "RandomGrayscale"

Based on these, the naming of ColorJitter is a bit of an outlier, which is why I think changing it to RandomColorShift would be stylistically more pleasing for the sake of consistency :)

**Comment by surgan12** [comment]
> RandomColorShift would be stylistically more pleasing for the sake of consistency :)

@rasbt , i think this we wouldnt mind doing that.

**Comment by surgan12** [comment]
@fmassa should this be closed now ?

**Comment by fmassa** [comment]
Let's close this for now, but if there are more requests to change it to `RandomColorShift`, then why not
