### ISSUE TITLE
M1 jobs are all failing

### ISSUE THREAD

**Issue by NicolasHug** [pytorch/vision#8456]
We moved them to M1 instances 2 days ago and things were fine in the [PR](https://github.com/pytorch/vision/pull/8446) but these jobs have been extremely flaky since then. E.g. the current failures on https://github.com/pytorch/vision/commit/b0f9f7bcbe2dbd6d4deee9558fd025c45c9c6382

- [Conda build](https://github.com/pytorch/vision/actions/runs/9300373500/job/25596247883): 3.9 is passing but all other Python versions are failing on `import torchvision`.
- [Wheel build](https://github.com/pytorch/vision/actions/runs/9300373488/job/25596250992): all job are failing
 
 ```
  import torchvision
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_9300373488/lib/python3.8/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_9300373488/lib/python3.8/site-packages/torchvision/_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_9300373488/lib/python3.8/site-packages/torch/library.py", line 639, in register
    use_lib._register_fake(op_name, func, _stacklevel=stacklevel + 1)
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_9300373488/lib/python3.8/site-packages/torch/library.py", line 139, in _register_fake
    handle = entry.abstract_impl.register(func_to_register, source)
  File "/Users/ec2-user/runner/_work/_temp/conda_environment_9300373488/lib/python3.8/site-packages/torch/_library/abstract_impl.py", line 30, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist
```

- [CMake job](https://github.com/pytorch/vision/actions/runs/9300373482/job/25596228218) failing with same error
- [All unit test jobs](https://github.com/pytorch/vision/actions/runs/9300373480/job/25596231593) failing with same error

----

*Maybe* https://github.com/pytorch/vision/pull/8407 can help? EDIT: NOPE.

---

This is probably related to these compilation warnings we're [observing](https://github.com/pytorch/vision/actions/runs/9300373480/job/25596231593#step:9:492) for every single op?

```
  ld: warning: object file (/Users/ec2-user/runner/_work/vision/vision/pytorch/vision/build/temp.macosx-11.1-arm64-cpython-311/Users/ec2-user/runner/_work/vision/vision/pytorch/vision/torchvision/csrc/ops/autocast/nms_kernel.o) was built for newer macOS version (13.0) than being linked (11.1)
```

It's clear that the installed torch version is for [MacOS 11 ](https://github.com/pytorch/vision/actions/runs/9300373480/job/25596231593#step:9:270) so if torchvision is being compiled on MacOS 13 this might be the cause?

EDIT: NOPE. https://github.com/pytorch/vision/actions/runs/9288139810/job/25565749027?pr=8452 from yesterday has the exact same warnings but it runs fine.

**Comment by malfet** [comment]
@huydhn I guess it has something to do with MacOS runners update.. Let me have a look at what is going on

**Comment by NicolasHug** [comment]
Thanks a lot for looking into this @malfet and @huydhn , I was about to ping you both as I saw some related changes in the PyTorch repo from last week. I've opened https://github.com/pytorch/vision/issues/8478 to keep track of the MPS issue and with more details (I'll close this one if you don't mind as it contains a bit of noise from my investigations above).
