### ISSUE TITLE
Support NumPy 2.0

### ISSUE THREAD

**Issue by jakirkham** [pytorch/vision#8460]
Hi All 👋

NumPy is planning to release 2.0 on June 16th ( https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448 ). NumPy 2.0.0 RC packages for conda & wheels came out at the beginning of April ( https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 )

Also it looks like PyTorch has added NumPy 2.0 support ( https://github.com/pytorch/pytorch/issues/107302 ) as part of 2.3.0

NumPy has put out [a migration guide]( https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide ). More details are in [the release notes]( https://numpy.org/devdocs/release/2.0.0-notes.html )

If torchvision makes use of NumPy's C API (and produces wheels that use it), having a release of torchvision with wheels built against NumPy 2.0.0rc1 would be helpful to ensure NumPy 1 & 2 compatible wheels (as wheels built against NumPy 1 won't be compatible with NumPy 2). More details in [this NumPy 2 ABI doc]( https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-abi-handling )

Also as NumPy is tracking ecosystem support for NumPy 2.0, it would be helpful to share torchvision current support status in issue (with any plans): https://github.com/numpy/numpy/issues/26191

**Comment by rgommers** [comment]
It looks like some testing and fixes are in order indeed (in progress in gh-8461)

> If torchvision makes use of NumPy's C API (and produces wheels that use it)

There should not be such a dependency. `numpy` isn't a build requirement in `pyproject.toml`, and there are no numpy headers being used directly.

**Comment by NicolasHug** [comment]
Thanks a lot for the update @jakirkham and @rgommers .

From https://github.com/pytorch/vision/pull/8461 and https://github.com/pytorch/vision/pull/8465 it looks like there's no more errors with numpy 2.0 (CI is mostly red but the relevant unittests-linux jobs are passing). The only required fix was https://github.com/pytorch/vision/pull/8463. So torchvision 0.19 should be fully compatible.

I also commented on https://github.com/numpy/numpy/issues/26191#issuecomment-2145211468.

**Comment by rgommers** [comment]
Great, thanks @NicolasHug!

**Comment by adamjstewart** [comment]
It looks like numpy 2 is still not supported on Windows? The wheel has an upper bound on numpy.

**Comment by adamjstewart** [comment]
Ah, I found https://github.com/pytorch/vision/pull/8530 and https://github.com/pytorch/vision/issues/8531. Maybe we should reopen this issue?

**Comment by NicolasHug** [comment]
No need to re-open this, we're aware of the problem and we're working on a fix. This is tracked in https://github.com/pytorch/vision/issues/8531 for torchvision and more generally in https://github.com/pytorch/pytorch/issues/131668 for pytorch, as this isn't a torchvision-specific problem.
