### ISSUE TITLE
torchvision.ops.focal_loss missing a -1

### ISSUE THREAD

**Issue by Fchaubard** [pytorch/vision#8519]
### 🐛 Describe the bug

The correct implementation is:

_FL(pt) = −αt(1 − pt)^γ * log(pt)_

but it is implemented [here](https://pytorch.org/vision/main/_modules/torchvision/ops/focal_loss.html) as:

_FL(pt) = αt(1 − pt)^γ * log(pt)_

This results in the optimizer minimizing a negative loss further negative (going the wrong way). 

Simple fix to just negate the loss later.. but it is confusing. Please address by updating:

_loss = alpha_t * loss_

to

_loss = -alpha_t * loss_

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-172-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100 80GB PCIe
Nvidia driver version: 535.154.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      48 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          AuthenticAMD
Model name:                         AMD EPYC 7643 48-Core Processor
CPU family:                         25
Model:                              1
Thread(s) per core:                 2
Core(s) per socket:                 48
Socket(s):                          2
Stepping:                           1
Frequency boost:                    enabled
CPU max MHz:                        2300.0000
CPU min MHz:                        1500.0000
BogoMIPS:                           4600.19
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca
Virtualization:                     AMD-V
L1d cache:                          3 MiB (96 instances)
L1i cache:                          3 MiB (96 instances)
L2 cache:                           48 MiB (96 instances)
L3 cache:                           512 MiB (16 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-47,96-143
NUMA node1 CPU(s):                  48-95,144-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.1.0+cu118
[pip3] torchaudio==2.1.0+cu118
[pip3] torchvision==0.16.0+cu118
[pip3] triton==2.1.0
[conda] Could not collect

**Comment by NicolasHug** [comment]
I think the implementation is correct

https://github.com/pytorch/vision/blob/8f9d810a26f1e3be97e8ec48a214967accdb9016/torchvision/ops/focal_loss.py#L41

The `ce_loss` term corresponds to `-log(p_t)`

Feel free to re-open if I'm missing something

**Comment by Fchaubard** [comment]
Hmm.. ok I am fine either way, but I don't think its working the way you are expecting for some reason. Its hard for me to write up a min example, but in my experiment, if I use CE vs. your Focal Loss vs. -1 * your Focal loss, I get the following:

**CE:**
<img width="177" alt="Screen Shot 2024-07-09 at 10 47 47 PM" src="https://github.com/pytorch/vision/assets/1486915/5ecec335-4d00-4dbe-82f7-31bc782d980a">

**Your Focal Loss:**
![Screen Shot 2024-07-08 at 3 42 49 PM](https://github.com/pytorch/vision/assets/1486915/131d25be-e0bb-4eca-9146-cde538a75f89)

**-1 * Your Focal Loss:**
<img width="763" alt="Screen Shot 2024-07-08 at 3 43 45 PM" src="https://github.com/pytorch/vision/assets/1486915/8e21f194-0b95-4224-85d4-729b83488621">

See code here:
https://github.com/Fchaubard/strange-loop-networks/blob/main/train_right.py
Note line 211 vs. 204:
loss = loss_fn(outputs_flat, microbatch_reward_masks_flat.long())
vs.
loss = -1 * sigmoid_focal_loss(outputs_flat, targets_one_hot, alpha=2.0, gamma=4.0, reduction='mean')
