### ISSUE TITLE
Data used for pretrained model checkpoints

### ISSUE THREAD

**Issue by ginlov** [pytorch/vision#8567]
### 📚 The doc issue

Hi forks,

Now I am working on a research project which works mainly on the theory of deep models.
To support our theory, I would like to know that which dataset (do you you training, validation or testing set when choosing parameters, training and choosing final models) you guys use when training ImageNet.

Thank you

**Comment by NicolasHug** [comment]
Hi @ginlov , we use the standard sets defined by the dataset. You'll find more detail in the README, and for the ground truth feel free to check the code as well https://github.com/pytorch/vision/tree/main/references/classification
