### ISSUE TITLE
RandomPhotometricDistort has undocumented channel shuffle feature

### ISSUE THREAD

**Issue by chadrockey** [pytorch/vision#8570]
### 🐛 Describe the bug

The documentation for RandomPhotometricDistort neither exposes the channel shuffle behavior as a parameter or lists in the description that this is a possibility.

https://pytorch.org/vision/stable/generated/torchvision.transforms.v2.RandomPhotometricDistort.html#torchvision.transforms.v2.RandomPhotometricDistort

I was trying to use this as convince for randomly brightness and contrast operations, but I got unexpected breaking channel swaps as well.

The best course of action could be to expose a boolean true/false parameter on whether to do channel swaps or not.

### Versions

0.19 stable documentation

**Comment by NicolasHug** [comment]
Hi @chadrockey , I'm unable to find where the original implementation of RandomPhotomemtricDistort comes from, but I suspect the one in torchvision closely follows the one from the paper(s), where the channel permutation was solely determined by the `p` parameter.

If you only need brightness and contrast operations, perhaps [ColorJitter](https://pytorch.org/vision/stable/generated/torchvision.transforms.v2.ColorJitter.html#torchvision.transforms.v2.ColorJitter) is what you're looking for?
