### ISSUE TITLE
ImportError: cannot import name 'datapoints' from 'torchvision.prototype'

### ISSUE THREAD

**Issue by Subhankhan41** [pytorch/vision#8595]
### 🐛 Describe the bug

Hi,

I tried from torchvision import data points and also from torchvision.prototype import datapoints, but I am still having ImportError: cannot import name 'datapoints' from 'torchvision' and  ImportError: cannot import name 'datapoints' from 'torchvision.prototype respectively. The rest of things are working fine including from torchvision.prototype import transforms as T. Any idea why it's happening?

from torchvision.prototype import transforms as T
from torchvision.prototype import datapoints

ImportError: cannot import name 'datapoints' from 'torchvision.prototype' (C:\Users\Subhan.Khan\AppData\Local\anaconda3\envs\myconda\Lib\site-packages\torchvision\prototype\__init__.py)

from torchvision.prototype import transforms as T
from torchvision import datapoints

ImportError: cannot import name 'datapoints' from 'torchvision'

### Versions

Hi,

I tried from torchvision import data points and also from torchvision.prototype import datapoints, but I am still having ImportError: cannot import name 'datapoints' from 'torchvision' and  ImportError: cannot import name 'datapoints' from 'torchvision.prototype respectively. The rest of things are working fine including from torchvision.prototype import transforms as T. Any idea why it's happening?

**Comment by NicolasHug** [comment]
Hi @Subhankhan41 
This namespace has been removed a while ago from the prototype area. Refer to the most up to date docs: https://pytorch.org/vision/main/tv_tensors.html
