### ISSUE TITLE
GoogLeNet cannot be loaded -- seems broken

### ISSUE THREAD

**Issue by rasbt** [pytorch/vision#860]
Hi,

it seems like the GoogLeNet cannot be loaded on version 0.2.2.

E.g., 

```python
from torchvision import models
inception = models.inception_v3(pretrained=True)
```

works fine. However, 

```python
googlenet = models.googlenet(pretrained=True)
```

raises a

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-3c92b85a3985> in <module>
----> 1 googlenet = models.googlenet(pretrained=True)

AttributeError: module 'torchvision.models' has no attribute 'googlenet'
```

**Comment by TheCodez** [comment]
@rasbt GoogLeNet is not included in the current release. If you still like to use it you have to install torchvision from source:
`python setup.py install`

Related issue: https://github.com/pytorch/vision/issues/854

**Comment by rasbt** [comment]
Oh nice, thanks! I will close this issue then!
