### ISSUE TITLE
Suitable augmentation of Keras in Pytorch

### ISSUE THREAD

**Issue by jawi289o** [pytorch/vision#8628]
I am reproducing a code (which is in tensorflow/keras) in which the following augmentations are applied.

ImageDataGenerator( zoom_range=0.1, fill_mode='reflect', width_shift_range=0.4, height_shift_range=0.4, rotation_range=90)

Are these augmentations available in Pytorch? I couldn't find them. Any help would be appreciated.

**Comment by NicolasHug** [comment]
Hi @jawi289o. I'm not familiar with `ImageDataGenerator`, but I doubt we have a direct equivalent in torchvision.
