### ISSUE TITLE
Vision Transformer forward function

### ISSUE THREAD

**Issue by isega24** [pytorch/vision#8685]
Hi, torch developers,

I noticed on the implementation of VisionTransformers the following line: 

[https://github.com/pytorch/vision/blob/945bdad7523806b15d3740ce6ace2fced9ef9d3b/torchvision/models/vision_transformer.py#L301C1-L301C20](https://github.com/pytorch/vision/blob/945bdad7523806b15d3740ce6ace2fced9ef9d3b/torchvision/models/vision_transformer.py#L301C1-L301C20)

which, in essence, of a tensor of dimensions (Batch_Size,N_Features,dim_Features) select the first dim_features. I noticed it with the model vit_b_16 with the default weights. The encoder output will be of dimensions [B, 197, 768]. With the line linked, the dimension of the features will be [B,768], which is desired  for a final MLP layer for classification for example.

Is this implementation correct? Or would it be better to add an Adaptive (Average/Max,...) Pooling as in CNNs?

Thank you for your attention

**Comment by NicolasHug** [comment]
Hi @isega24 , 

this line

https://github.com/pytorch/vision/blob/945bdad7523806b15d3740ce6ace2fced9ef9d3b/torchvision/models/vision_transformer.py#L300-L301

corresponds to the selection of the "CLS token", which is a commonly used in classification transformers and comes from previous transformers like BERT (you can lookup BERT CLS token for more info).

This is expected and normal.

**Comment by isega24** [comment]
Thanks for the information, I had no idea why this decision was made.

However, I found [this discussion](https://ai.stackexchange.com/questions/28326/why-class-embedding-token-is-added-to-the-visual-transformer) in stackoverflow describing an improvement if using the not just the CLS token but the whole feature space of ViT with a Global Average Pooling, in case it is helpfull.

Thanks you again for your response

**Comment by NicolasHug** [comment]
Thanks @isega24 

I forgot to link to the original reference for this: you can find mentioned of this token in the original vision transformer paper https://arxiv.org/abs/2010.11929 (e.g. Figure 1)
