### ISSUE TITLE
I am using the torchvision-0.13.1+cu113 version, but it seems that it does not have the datapoints package. How can I solve this issue?

### ISSUE THREAD

**Issue by jiangsu415** [pytorch/vision#8714]
### 🐛 Describe the bug

I am using the torchvision-0.13.1+cu113 version, but it seems that it does not have the datapoints package. How can I solve this issue?

### Versions

I am using the torchvision-0.13.1+cu113 version, but it seems that it does not have the datapoints package. How can I solve this issue?

**Comment by abhi-glitchhg** [comment]
@jiangsu415 torchvision-0.13.1 doesn't have a datapoints module because the datapoints module was introduced in torchvision 0.15. 

You might want to upgrade your environment to  0.15 if you want to use the datapoints module.

Also as Nicolas mentioned, in the later versions it was renamed, so you might want to look at the `tv_tensors` instead of datapoints.

**Comment by eliethesaiyan** [comment]
@abhi-glitchhg , @NicolasHug , @jiangsu415 
I have version 0.20.1 , but i get the  same problem.
```python
0.20.1
Traceback (most recent call last):
  File "/home/elie/gitclones/zcrop/utils.py", line 11, in <module>
    from torchvision import datapoints
ImportError: cannot import name 'datapoints' from 'torchvision' (/home/dude/miniforge3/envs/test/lib/python3.12/site-packages/torchvision/__init__.py)
````
did anything changes? 
When i check also the documentations. 0.20 does not have any documentation about `datapoints`  module

**Comment by abhi-glitchhg** [comment]
Yes, 

Refer to Nicolas' comments above.

https://github.com/pytorch/vision/issues/8714#issuecomment-2460336531

**Comment by NicolasHug** [comment]
I'll close this issue as the original problem has been addressed. @eliethesaiyan , can I ask which resource you used that mentioned `datapoints`?
