### ISSUE TITLE
nms 

### ISSUE THREAD

**Issue by 5464jmy** [pytorch/vision#8729]
### 🐛 Describe the bug

```
template <typename T>
__device__ inline bool devIoU(
    T const* const a,
    T const* const b,
    const float threshold) {
  T left = max(a[0], b[0]), right = min(a[2], b[2]);
  T top = max(a[1], b[1]), bottom = min(a[3], b[3]);
  T width = max(right - left, (T)0), height = max(bottom - top, (T)0);
  using acc_T = at::acc_type<T, /*is_cuda=*/true>;
  acc_T interS = (acc_T)width * height;
  acc_T Sa = ((acc_T)a[2] - a[0]) * (a[3] - a[1]);
  acc_T Sb = ((acc_T)b[2] - b[0]) * (b[3] - b[1]);
  return (interS / (Sa + Sb - interS)) > threshold;
}
```

` T width = max(right - left, (T)0), height = max(bottom - top, (T)0);`
这对反向框不太友好
left > right and top > bottom

**Comment by NicolasHug** [comment]
sorry @5464jmy , not sure what this issue is about

**Comment by 5464jmy** [comment]
` T width = max(right - left, (T)0), height = max(bottom - top, (T)0);`
If you have a given bounding box where `left > right and top > bottom`, it will set its` width and height` to zero. However,we can still calculate valid results from this scenario.
` T width =right - left, height = bottom - top;`can address the issue
