### ISSUE TITLE
[BUG] Found a bug in GoogLeNet. The order of aux1 and aux2 is incorrectly reversed. 

### ISSUE THREAD

**Issue by pblwk** [pytorch/vision#8736]
https://github.com/pytorch/vision/blob/518ee93dbd1469524040e1607a345fff90fa7fcd/torchvision/models/googlenet.py#L174

The order of aux1 and aux2 in line 174 is incorrectly reversed.

**Comment by NicolasHug** [comment]
Fixed in https://github.com/pytorch/vision/pull/8743, thanks for the report and for the fix @pblwk !

**Comment by pblwk** [comment]
Glad to help! : D @NicolasHug
