### ISSUE TITLE
The link of `Flickr30k()` doesn't have a Flickr30k dataset 

### ISSUE THREAD

**Issue by hyperkai** [pytorch/vision#8742]
### 📚 The doc issue

[The link](http://hockenmaier.cs.illinois.edu/8k-pictures.html) of [Flickr30k()](https://pytorch.org/vision/stable/generated/torchvision.datasets.Flickr30k.html) doesn't have a Flickr30k dataset at all and I couldn't find any Flickr30k datasets which suit [Flickr30k()](https://pytorch.org/vision/stable/generated/torchvision.datasets.Flickr30k.html).

![Screenshot 2024-11-24 163654](https://github.com/user-attachments/assets/341329ed-40da-4b2c-8116-c70e4137d672)

**Comment by NicolasHug** [comment]
Hi @hyperkai .

The Flicker30k dataset links to https://bryanplummer.com/Flickr30kEntities/, so it's fairly obvious that it refers to Flicker30k


Perhaps you meant the link from `Flickr8k` (as from the screenshot) which links to https://hockenmaier.cs.illinois.edu/8k-pictures.html.

I believe that link is still reasonably correct:

- see the "8k" part in the URL
- the link directly points to https://hockenmaier.cs.illinois.edu/Framing_Image_Description/KCCA.html where you'll find mention of the 8k dataset. I'm not  entirely sure why that link wasn't used originally, but I hope this is still reasonably clear.
