### ISSUE TITLE
The link of `ImageNet()` doesn't have `ILSVRC2012_img_train.tar` and `ILSVRC2012_img_val.tar`.

### ISSUE THREAD

**Issue by hyperkai** [pytorch/vision#8745]
### 📚 The doc issue

[The link](https://image-net.org/challenges/LSVRC/2012/2012-downloads.php) of [ImageNet()](https://pytorch.org/vision/stable/generated/torchvision.datasets.ImageNet.html) doesn't have `ILSVRC2012_img_train.tar` and `ILSVRC2012_img_val.tar`.

![Screenshot 2024-11-24 214303](https://github.com/user-attachments/assets/bad5670d-0783-4398-8e78-1412ec945b0a)

**Comment by NicolasHug** [comment]
Hi @hyperkai , thanks for the report. Yes, sadly, the original ImageNet dataset has become notoriously difficult to download (you'll find the login form in the linked page). Unfortunately, this isn't something we're able to handle within torchvision directly. Perhaps we could make the Note slightly clearer with that regards. I'll close this issue but if you think we should clarify the note, please do let me know (feel free to submit a PR directly as well!).
