### ISSUE TITLE
`train` parameter should be removed for simplicity

### ISSUE THREAD

**Issue by hyperkai** [pytorch/vision#8785]
### 🚀 The feature

[QMNIST()](https://pytorch.org/vision/stable/generated/torchvision.datasets.QMNIST.html) has `what` and `train` parameter but `what` parameter covers `train` parameter as shown below, so `train` parameter is not necessary:

> Parameters:
> - what (string,optional) – Can be ‘train’, ‘test’, ‘test10k’, ‘test50k’, or ‘nist’ for respectively the mnist compatible training set, the 60k qmnist testing set, the 10k qmnist examples that match the mnist testing set, the 50k remaining qmnist testing examples, or all the nist digits. The default is to select ‘train’ or ‘test’ according to the compatibility argument ‘train’.

> - train ([bool](https://docs.python.org/3/library/functions.html#bool),optional,compatibility) – When argument ‘what’ is not specified, this boolean decides whether to load the training set or the testing set. Default: True.

### Motivation, pitch

 So, `train` parameter should be removed for simplicity.

**Comment by NicolasHug** [comment]
Thanks for the report @hyperkai . I agree the API seems a bit convoluted. I think we'll keep the parametrization as-is, as it's probably not worth breaking existing code. I don't think we'll act on this one, so you don't mind, I'll close this issue.
