### ISSUE TITLE
mismatch between documentation and code in torchvision.transforms.ToTensor

### ISSUE THREAD

**Issue by aosokin** [pytorch/vision#88]
torchvision.transforms.ToTensor documentation says that the numpy.ndarray (H x W x C) is converted to torch.FloatTensor of shape (C x H x W):
`Converts a PIL.Image or numpy.ndarray (H x W x C) in the range
   [0, 255] to a torch.FloatTensor of shape (C x H x W) in the range [0.0, 1.0].`

However, the [code](https://github.com/pytorch/vision/blob/master/torchvision/transforms.py#L41) does not do permute dimensions:
`img = torch.from_numpy(pic)`

Related issue: the documentation says that the np.array normalized to [0, 255] is converted to torch.FloatTensor normalized to [0,1]. This is not happening.

**Comment by alykhantejani** [comment]
Hi @aosokin,

Thanks for raising this, there is a current PR under review that should fix this (#55), also a related issue (#48)

**Comment by alykhantejani** [comment]
#48 has now been merged. 

@aosokin In regards to the second issue, (a np.array in range [0,255] being converted to a FloatTensor in range [0,1]), I believe this is being handled correctly on [this line](https://github.com/pytorch/vision/blob/master/torchvision/transforms.py#L54)

@soumith I think this issue can now be closed
