### ISSUE TITLE
Incorrect ResNext Model

### ISSUE THREAD

**Issue by D-X-Y** [pytorch/vision#880]
In the original resnext model paper (https://arxiv.org/pdf/1611.05431.pdf), the expansion of their bottleneck block is 2 instead of 4.

**Comment by fmassa** [comment]
@szagoruyko could you have a look at this? You've mentioned the expansion 2 in the past for WRN

**Comment by szagoruyko** [comment]
in ResNeXt it is 4 from their code https://github.com/facebookresearch/ResNeXt/blob/master/models/resnext.lua#L86
in ImageNet WRN expansion is 2

**Comment by D-X-Y** [comment]
Yes, but from the paper (Table 1), the expansion of ResNeXt-50 (32×4d) is 2?

**Comment by szagoruyko** [comment]
@D-X-Y torchvision.models.resnext50_32x4d() gives exactly the same model as in table 1. afaik @fmassa implemented it in a such way that the outer bottleneck size is fixed and only the inner can increase / decrease. but the code is a bit confusing yeah.

**Comment by D-X-Y** [comment]
I see, the model is indeed the same. Sorry for my mistake.

**Comment by fmassa** [comment]
@szagoruyko if you see ways of making the implementation less confusing, please let me know!
