### ISSUE TITLE
`CelebA()` accepts `int`, `float` and `complex` type and doesn't return `None` even if empty

### ISSUE THREAD

**Issue by hyperkai** [pytorch/vision#8804]
### 🐛 Describe the bug

[The doc](https://pytorch.org/vision/stable/generated/torchvision.datasets.CelebA.html) of `CelebA()` says `target_type` parameter accepts `str` or `list` and `None` will be returned if empty as shown below:

> Parameters:
> ...
> - target_type (string or [list](https://docs.python.org/3/library/stdtypes.html#list), optional) –
> ...
> Defaults to attr. If empty, None will be returned as target.

But `CelebA()` accepts `int`, `float` and `complex` type and doesn't return `None` even if empty as shown below:

```python
from torchvision.datasets import CelebA

my_data = CelebA(
    root="data",
    target_type=3
)

my_data.target_type # [3]

my_data = CelebA(
    root="data",
    target_type=3
)

my_data.target_type # [3.14]

my_data = CelebA(
    root="data",
    target_type=3+14j
)

my_data.target_type # [(3+14j)]

my_data = CelebA(
    root="data",
    target_type=""
)

my_data.target_type # ['']

my_data = CelebA(
    root="data",
    target_type=[]
)

my_data.target_type # []

my_data = CelebA(
    root="data",
    target_type=["", "", ""]
)

my_data.target_type # ['', '', '']
```

### Versions

```python
import torchvision

torchvision.__version__ # '0.20.1'
```

**Comment by NicolasHug** [comment]
Thanks for the report @hyperkai .

Feel free to submit a PR if you believe those cases should be better handled. I think the way target_type currently works is that the behavior is undefined unless you pass some input that is expected (as it is clearly documented).

Feel free to submit a PR, but I'll close this issue as I don't find it critically relevant to address at this time.
