### ISSUE TITLE
Setting `3` or `3.14` to `target_type` argument of `Caltech101()` gets the indirect error message

### ISSUE THREAD

**Issue by hyperkai** [pytorch/vision#8808]
### 🐛 Describe the bug

Setting `"hello"` to `target_type` argument of [Caltech101()](https://pytorch.org/vision/stable/generated/torchvision.datasets.Caltech101.html) get the direct error message as shown below:

```python
from torchvision.datasets import Caltech101

my_data = Caltech101(
    root="data",
    target_type="hello"
) # Error
```

> ValueError: Unknown value 'hello' for argument target_type. Valid values are {'category', 'annotation'}.

But setting `3` or `3.14` to `target_type` argument of `Caltech101()` gets the indirect error message as shown below:

```python
from torchvision.datasets import Caltech101

my_data = Caltech101(
    root="data",
    target_type=3 # Here
) # Error
```

> TypeError: 'int' object is not iterable

```python
from torchvision.datasets import Caltech101

my_data = Caltech101(
    root="data",
    target_type=3.14 # Here
) # Error
```

> TypeError: 'float' object is not iterable

So, they should return the direct error messages as shown below:

> ValueError: Unknown value 3 for argument target_type. Valid values are {'category', 'annotation'}.

> ValueError: Unknown value 3.14 for argument target_type. Valid values are {'category', 'annotation'}.

### Versions

```python
import torchvision

torchvision.__version__ # '0.20.1'
```

**Comment by NicolasHug** [comment]
Thanks for the report @hyperkai . Feel free to submit a PR to also check for the types. In general what we want to avoid is for users to do the wrong thing, or get unexpected results. If a user passes a float to a parameter that's very obviously not a float, and they get an error (whatever the error might be), then I think that's good enough. We do provide helpful error messages when users pass the wrong string, which IMO is what truly matters here.
