### ISSUE TITLE
Setting the empty list `[]` or tuple `()` to `target_type` argument of `Caltech101()` has the length 8677 but trying to access the element gets error

### ISSUE THREAD

**Issue by hyperkai** [pytorch/vision#8809]
### 🐛 Describe the bug

Setting the empty list `[]` or tuple `()` to `target_type` argument of [Caltech101()](https://pytorch.org/vision/stable/generated/torchvision.datasets.Caltech101.html) has the length 8677 but trying to access the element gets the error as shown below:

```python
from torchvision.datasets import Caltech101

my_data = Caltech101(
    root="data",
    target_type=[] # Here
)

len(my_data) # 8677

my_data[0] # Error

my_data = Caltech101(
    root="data",
    target_type=() # Here
)

len(my_data) # 8677

my_data[0] # Error
```

> IndexError: list index out of range

### Versions

```python
import torchvision

torchvision.__version__ # '0.20.1'
```

**Comment by NicolasHug** [comment]
Thanks for the report @hyperkai . This sounds a lot like https://github.com/pytorch/vision/issues/8808, so I'll close it for the same reason.
