### ISSUE TITLE
No support for multi-channel images

### ISSUE THREAD

**Issue by adamjstewart** [pytorch/vision#882]
Multi-channel images are common in the fields of satellite remote sensing (GIS) and in medical imaging. Many of the multispectral satellites I work with in my research have 8+ spectral bands, not just RGB. Some hyperspectral satellites have as many as 136 spectral bands. Microscopy often involves 4+ channel images as well.

Currently, torchvision relies on the Python Imaging Library (PIL) for all of its transforms. Unfortunately, pillow does not support multi-channel images: https://github.com/python-pillow/Pillow/issues/3160, https://github.com/python-pillow/Pillow/issues/1888

The way I see it, researchers such as myself have 3 options:

1. Fix PIL (unlikely, as https://github.com/python-pillow/Pillow/issues/1888 has been stalled for 3 years now)
2. Fix torchvision (this would involve implementing all of the current transforms by hand using torch Tensors or numpy arrays)
3. Fork torchvision (write all of the transforms we need ourselves)

I'm about to resort to 3 for my research. Do you have any suggestions for users like me?

**Comment by sibowsb** [comment]
I agree that is indeed a common problem in remote sensing, especially hyperspectral imaging.

**Comment by pmeier** [comment]
This is an ongoing discussion (although for some other reasons), which leans to option 2. Recently @fmassa [stated](https://github.com/pytorch/vision/pull/861#issuecomment-487136003):

> [...] I'd rather not rush things just yet

Thus, if I were you, I would go with option 3. for now, but check back regularly for official support.

**Comment by jphdotam** [comment]
I would love for this to be a focus. Not only is it a problem for multi-channel data, but also it causes issue for target transformations for semantic segmentation where a channel is needed for each target.

**Comment by fmassa** [comment]
By the way, in https://github.com/pytorch/vision/pull/1104 we are slowly going to be starting to support PyTorch Tensors for some of the transforms natively in torchvision, so that this won't be an issue anymore

**Comment by adamjstewart** [comment]
According to the v0.8.0 release notes, multi-channel images are now natively supported! Thanks so much for everyone's hard work!!!

**Comment by fmassa** [comment]
Thanks @adamjstewart !

Let us know if you find any issues with it

**Comment by adamjstewart** [comment]
I actually just started a new research project using drone-based hyperspectral imagery (128+ spectral bands), so I'll definitely be testing this feature to the extreme!

**Comment by adiren7** [comment]
@adamjstewart  were you able to train your model with multispectral images ? if yes ,can you please share what did you change in the dataloader ?

**Comment by adamjstewart** [comment]
I actually pivoted away from torchvision for transforms and used [Kornia](https://kornia.readthedocs.io/en/latest/augmentation.html) instead. All transforms in Kornia are done natively on PyTorch Tensors so they support multispectral images and can be run on the GPU.

According to the torchvision docs:

> Most transformations accept both PIL images and tensor images, although some transformations are PIL-only and some are tensor-only.

So it may be possible to do everything you need without ever leaving torchvision.

P.S. If you're working with satellite/plane/drone imagery, you may be interested in [TorchGeo](https://github.com/microsoft/torchgeo). If you're working with medical imagery I can't help you. Those are the two main applications of MSI that I know of.
