### ISSUE TITLE
Ask for elastic transform support

### ISSUE THREAD

**Issue by Usongkam** [pytorch/vision#888]
Elastic transform do well on MNIST and some other image datasets. 

However, it is not supported in torchvision.transforms , which make it difficult for me to compose an ideal transformation.

Could u please add this to torchvision.transforms in next verision ?

**Comment by ekagra-ranjan** [comment]
@fmassa If this is to be added then can I take this up?

**Comment by fmassa** [comment]
@ekagra-ranjan yes, this is on the plans to be added, a PR adding it would be awesome!

**Comment by JLrumberger** [comment]
A PR adding elastic transform got merged today, so this issue and the other PR can be closed I guess.
