### ISSUE TITLE
Densenet for CIFAR

### ISSUE THREAD

**Issue by HanbumKo** [pytorch/vision#896]
Hi all,
I added Densenet model for CIFAR dataset(Densenet_100_12, Densenet_190_40, Densenet_250_24) in my Densenet code. But I don't know how to upload pretrained model file(.pth). How can I deal with this?

**Comment by fmassa** [comment]
Hi,

We are currently not planning on adding support for cifar-style models in torchvision, because they generally do not transfer as well as ImageNet-style models for other tasks.

Thanks anyway!

**Comment by HanbumKo** [comment]
Thanks!
