### ISSUE TITLE
ImportError: cannot import name '_C'

### ISSUE THREAD

**Issue by zacurr** [pytorch/vision#904]
After adding C++ API, I tried to install torchvision both way.

pip install -v .
python setup.py install

Installation is successful.

However, when I import torchvision, I got following error.

(Server Spec: Ubuntu 16.04 , Cuda 10 + cudnn 7 , NVIDIA V100 GPU, PyTorch Nightly (13 May, 2019))

root@1ce2a317b759:/home/etri/Desktop/workspace_zacurr/vision_190513# python -c "import torchvision"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/etri/Desktop/workspace_zacurr/vision_190513/torchvision/__init__.py", line 3, in <module>
    from torchvision import ops
  File "/home/etri/Desktop/workspace_zacurr/vision_190513/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/etri/Desktop/workspace_zacurr/vision_190513/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: cannot import name '_C'

**Comment by fmassa** [comment]
There has probably a problem with your install. Can you try uninstalling torchvision, and reinstall it again?
```
python setup.py clean
python setup.py install
```

**Comment by zacurr** [comment]
sorry, i already installed vision (v0.2.2) and started training model.
Next time, I will try this and leave comment. Thank you.

**Comment by zacurr** [comment]
I tried it on the other server, but I got the same error.

Installation was successful.
Using /opt/conda/lib/python3.6/site-packages
Finished processing dependencies for torchvision==0.2.3a0+9077164

python -c "import torch; print(torch.__version__)" 
>> 1.1.0a0+1615661


but still i got the error 'cannot import name '_C'
I tried python setup.py clean and install again, but the result is the same

python -c "import torchvision" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/etri/Desktop/workspace_zacurr/vision_190516/torchvision/__init__.py", line 3, in <module>
    from torchvision import ops
  File "/home/etri/Desktop/workspace_zacurr/vision_190516/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/etri/Desktop/workspace_zacurr/vision_190516/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: cannot import name '_C'


vision v0.2.2  didn't have this error

**Comment by zacurr** [comment]
under the 'vision' directory,
python -c "impor torchvision" produced import error.
However, under the other directory. it doesn't
Thank you.

**Comment by Space-debug** [comment]
I fixed this error. You could add _C.cpython-36m-aarch64-linux-gnu.so to the file 'torchvision'(it's just for jetson nano)

**Comment by aluds123** [comment]
@Space-debug  Hi, how can I get  "_C.cpython-36m-aarch64-linux-gnu.so" ?
Thank you.

**Comment by Space-debug** [comment]
Please give me your E-mail. I send to you.

**Comment by Space-debug** [comment]
@aluds123

**Comment by xhxhxh11** [comment]
I have the same problem, could you please send it to me by email? Thank you。 sshxhjnu@163.com
