### ISSUE TITLE
Resize the image to have fixed height(width)

### ISSUE THREAD

**Issue by skurzhanskyi** [pytorch/vision#908]
Not sure if I should create an issue but I really didn't find the answer to this question.
In `Resize` we have the possibility either to have both height and width fixed or to get smaller edge fixed. In my task, I need to resize the image to have a fixed height. Is there any way to do this?

**Comment by pmeier** [comment]
If your images are always oriented as portrait (`height > width`) or landscape (`height < width`) you could wait how #897 plays out. If it is accepted, you can set the `bigger` flag for your purpose and be done with it.

Otherwise you could simply calculate the size yourself:
```python
image = ...
new_height = ...

old_width, old_height = pil_image.size
aspect_ratio = old_width / old_height
new_width = round(new_height * aspect_ratio)

transform = Resize(size=(new_height, new_width))
resized_image = transform(image)
```

**Comment by skurzhanskyi** [comment]
Thanks a lot for your swift answer.
I just thought it is an obvious desire to have this possibility like `Resize(224, None)` or something like this.
If calculate simply for every image in dataset, do you suggest to do it in `collate_fn`?

**Comment by pmeier** [comment]
Depends if you want to fiddle with it. If you have a non-default `collate_fn`, go for it. Otherwise I think its easier to simply create a custom `Resize` transform:
```python
import torchvision.transforms.functional as F

class FixedHeightResize(object):
    def __init__(self, height):
        self.height = height

    def __call__(self, img):
        size = (self.height, self._calc_new_width(img))
        return F.resize(img, size)

    def _calc_new_width(self, img):
        old_width, old_height = img.size
        aspect_ratio = old_width / old_height
        return round(self.height * aspect_ratio)
```

**Comment by skurzhanskyi** [comment]
Looks great, thanks a lot for your help.
