### ISSUE TITLE
[Feature Request] models structure for CIFAR10 datasets 

### ISSUE THREAD

**Issue by zhiqwang** [pytorch/vision#913]
The image size of ImageNets dataset is 224x224, which is different from the size of CIFAR10 datasets (32x32). I didn't know is there a plan to modify the networks (ResNet, DenseNet, MobileNet) of ImageNet to adapt the CIFAR10, like this [one](https://github.com/kuangliu/pytorch-cifar)?

**Comment by fmassa** [comment]
There is no current plan to provide Cifar-style models in torchvision.

The models in torchvision have all been implemented following the description in their original papers. But many of those models do not have equivalent descriptions for cifar / mnist.

I believe we will just stick with imagenet-size for now in torchvision, as it covers more cases.
