### ISSUE TITLE
c10/cuda/CUDAGuard.h need CUDA10?

### ISSUE THREAD

**Issue by mathpopo** [pytorch/vision#931]
torchvision/csrc/cuda/vision.h   no c10/cuda/CUDAGuard.h?

i use cuda9.0

**Comment by mathpopo** [comment]
c10/cuda/CUDAGuard.h belong to torch,but i install torch 1.0.0,do not include it ?

**Comment by fmassa** [comment]
torchvision master (and the upcoming 0.3 release) now requires PyTorch 1.1, and doesn't work with PyTorch 1.0
