### ISSUE TITLE
Windows build error [THC/THCNumerics.cuh(190): error: more than one operator ]

### ISSUE THREAD

**Issue by kerry-Cho** [pytorch/vision#936]
**Hi**
**If clone the source and run setuppy, get the following error:**
**What is the problem?**

**Look forward to release 0.2.3 version.**
**Thanks!!!! ^^**

c:/local/Anaconda3-4.1.1-Windows-x86_64/lib/site-packages/torch/include\THC/THCNumerics.cuh(190): error: more than one operator "<" matches these operands:
            built-in operator "arithmetic < arithmetic"
            function "operator<(const __half &, const __half &)"
            operand types are: c10::Half < c10::Half

c:/local/Anaconda3-4.1.1-Windows-x86_64/lib/site-packages/torch/include\THC/THCNumerics.cuh(191): error: more than one operator "<=" matches these operands:
            built-in operator "arithmetic <= arithmetic"
            function "operator<=(const __half &, const __half &)"
            operand types are: c10::Half <= c10::Half

c:/local/Anaconda3-4.1.1-Windows-x86_64/lib/site-packages/torch/include\THC/THCNumerics.cuh(192): error: more than one operator ">" matches these operands:
            built-in operator "arithmetic > arithmetic"
            function "operator>(const __half &, const __half &)"
            operand types are: c10::Half > c10::Half

c:/local/Anaconda3-4.1.1-Windows-x86_64/lib/site-packages/torch/include\THC/THCNumerics.cuh(193): error: more than one operator ">=" matches these operands:
            built-in operator "arithmetic >= arithmetic"
            function "operator>=(const __half &, const __half &)"
            operand types are: c10::Half >= c10::Half

c:/local/Anaconda3-4.1.1-Windows-x86_64/lib/site-packages/torch/include\THC/THCNumerics.cuh(194): error: more than one operator "==" matches these operands:
            built-in operator "arithmetic == arithmetic"
            function "operator==(const __half &, const __half &)"
            operand types are: c10::Half == c10::Half

c:/local/Anaconda3-4.1.1-Windows-x86_64/lib/site-packages/torch/include\THC/THCNumerics.cuh(196): error: more than one operator "!=" matches these operands:
            built-in operator "arithmetic != arithmetic"
            function "operator!=(const __half &, const __half &)"
            operand types are: c10::Half != c10::Half

6 errors detected in the compilation of "C:/Users/A¶´eEn/AppData/Local/Temp/tmpxft_00013484_00000000-8_nms_cuda.cpp4.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 2

**Comment by kerry-Cho** [comment]
**Add Build Flag -D__CUDA_NO_HALF_OPERATORS__ get the following error:**



D:/Git/vision/torchvision/csrc/cuda/ROIAlign_cuda.cu(329): error: no instance of function template "at::cuda::ATenCeilDiv" matches the argument list
            argument types are: (long long, long)
D:/Git/vision/torchvision/csrc/cuda/ROIAlign_cuda.cu(329): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, long)

D:/Git/vision/torchvision/csrc/cuda/ROIAlign_cuda.cu(382): error: no instance of function template "at::cuda::ATenCeilDiv" matches the argument list
            argument types are: (int64_t, long)

D:/Git/vision/torchvision/csrc/cuda/ROIAlign_cuda.cu(382): error: no instance of overloaded function "std::min" matches the argument list

**Comment by kerry-Cho** [comment]
*If build without using CUDA, it will be build without any problem.*

**Comment by fmassa** [comment]
Hi,

You need PyTorch 1.1 or a recent enough nightly.
Torchvision is not compatible with 1.0 or 1.0.1

**Comment by philipNoonan** [comment]
@kerry-Cho 

I had the same error as you with Win10 Cuda10 PyTorch 1.2.0 from source etc. The error was fixed by using 
`set NVCC_FLAGS="-D__CUDA_NO_HALF_OPERATORS__"`
in the terminal before the call to
`python setup.py install`

**Comment by kerry-Cho** [comment]
Hi. 
Check mail later .sorry reply answer.
This issue is a commlie error.
​
That cuda half  operation command.
i don't know do why.
Just that code not usage torchvision
​
if you want compile. That code do  ignore 
​
​
-----Original Message-----
