### ISSUE TITLE
Failed to build from source with 'ImportError: cannot import name '_C'

### ISSUE THREAD

**Issue by noNameForMe1994** [pytorch/vision#940]
I'm trying to install the torchvision from source with command
`python setup.py install`
It was succeed, but when I try to import it with 
`import torchvision`
There is an error with 'ImportError: cannot import name '_C'

```
Traceback (most recent call last): 
  File "<stdin>", line 1, in <module>
  File "/home/zzyu/vision/torchvision/__init__.py", line 1, in <module> 
    from torchvision import models 
  File "/home/zzyu/vision/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/zzyu/vision/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import * 
  File "/home/zzyu/vision/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/zzyu/vision/torchvision/ops/__init__.py", line 1, in <module> 
    from .boxes import nms, box_iou
  File "/home/zzyu/vision/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C 
ImportError: cannot import name '_C' 
```
I'm using Ubuntu 16.04, python 3.6.7 , GCC7.3.0, CUDA 9.0, NVIDIA K80 GPU and Pytorch 1.1

**Comment by noNameForMe1994** [comment]
After trying to reinstall with command 
`python setup.py clean`
`python setup.py install`

The error still exists

**Comment by zacurr** [comment]
#904 
Under the vision directory, it produced import error.
try import torchvision under the other directory.

**Comment by fmassa** [comment]
@noNameForMe1994 can you try changing directories, as pointed out by @zacurr ?

**Comment by D201830280253** [comment]
@noNameForMe1994  have you solved the error? I meet with the same error in google colab and my own computer.

**Comment by fmassa** [comment]
Did you try compiling the library again? There might have been an issue compiling / installing torchvision

**Comment by varunagrawal** [comment]
I may have some input to help debug this. The correspoding `_C.so` file is only created when you run `pip install -e .` so the import works only then.
However that being said, I don't see this issue anymore so it may have been fixed by some update to `setup.py`.

@noNameForMe1994 can you please run `pip install -e .` and try again? Or try again with the latest master?

**Comment by Manoj404667** [comment]
I am also getting the problem in 'import _C' inside the 'import torchvision' in colab. I have tried to upgrade the version for the torch and also run the command 'pip install -e'. You can see the error in the figure below:
![Screenshot from 2019-09-06 11-29-17](https://user-images.githubusercontent.com/41113976/64404488-b2cf1400-d099-11e9-8ec1-4445f7326c85.png)
Can somebody help me?

**Comment by ganleiboy** [comment]
> I am also getting the problem in 'import _C' inside the 'import torchvision' in colab. I have tried to upgrade the version for the torch and also run the command 'pip install -e'. You can see the error in the figure below:
> ![Screenshot from 2019-09-06 11-29-17](https://user-images.githubusercontent.com/41113976/64404488-b2cf1400-d099-11e9-8ec1-4445f7326c85.png)
> Can somebody help me?

You can have a look at this.
https://github.com/pytorch/pytorch/issues/23585

**Comment by fmassa** [comment]
This is an issue with incompatibility between versions of PyTorch and TorchVision. This error in particular should have disappeared in the latest version of TorchVision.

As such, I'm closing this issue, but let me know if you still face issues

**Comment by AyazSaiyed** [comment]
This is because of pytorch version incompatibility , 

**pip install torch==1.3.0**

> These Worked for me .

**Comment by Space-debug** [comment]
> I am also getting the problem in 'import _C' inside the 'import torchvision' in colab. I have tried to upgrade the version for the torch and also run the command 'pip install -e'. You can see the error in the figure below:
> ![Screenshot from 2019-09-06 11-29-17](https://user-images.githubusercontent.com/41113976/64404488-b2cf1400-d099-11e9-8ec1-4445f7326c85.png)
> Can somebody help me?

**Comment by Space-debug** [comment]
Did you sovle it? I met the same issue.

**Comment by fmassa** [comment]
@Space-debug your versions of PyTorch and TorchVision are incompatible.

Please refer to the compatibility table in https://github.com/pytorch/vision#installation
