### ISSUE TITLE
Numpy NMS is as fast as C++ CPU NMS  

### ISSUE THREAD

**Issue by karanchahal** [pytorch/vision#942]
Hello,

I was going through the recent object detection code contributed by @fmassa and saw custom c++ extensions of NMS in the codebase.

 I tried benchmarking how much faster the c++ cpu ops are compared to numpy nms ops.

I discovered that the speed difference is almost negligible in the case of the cpu version. That is the speed of nms of the c++ version is 0.001 ms whereas the speed of the numpy NMS version is 0.003 ms for 1000 anchors.

The code I used for the numpy NMS was contributed by taken from detectron:

```python
# --------------------------------------------------------
# Fast R-CNN
# Copyright (c) 2015 Microsoft
# Licensed under The MIT License [see LICENSE for details]
# Written by Ross Girshick
# --------------------------------------------------------

import numpy as np

def nms(dets, scores, thresh):
    '''
    dets is a numpy array : num_dets, 4
    scores ia  nump array : num_dets,
    '''
    x1 = dets[:, 0]
    y1 = dets[:, 1]
    x2 = dets[:, 2]
    y2 = dets[:, 3]

    areas = (x2 - x1 + 1) * (y2 - y1 + 1)
    order = scores.argsort()[::-1] # get boxes with more ious first

    keep = []
    while order.size > 0:
        i = order[0] # pick maxmum iou box
        keep.append(i)
        xx1 = np.maximum(x1[i], x1[order[1:]])
        yy1 = np.maximum(y1[i], y1[order[1:]])
        xx2 = np.minimum(x2[i], x2[order[1:]])
        yy2 = np.minimum(y2[i], y2[order[1:]])

        w = np.maximum(0.0, xx2 - xx1 + 1) # maximum width
        h = np.maximum(0.0, yy2 - yy1 + 1) # maxiumum height
        inter = w * h
        ovr = inter / (areas[i] + areas[order[1:]] - inter)

        inds = np.where(ovr <= thresh)[0]
        order = order[inds + 1]

    return keep
``` 

Keeping this in mind, can we use this numpy version of the nms instead of the c++ cpu version ?

I benchmarked the cuda version of nms and it gives substantial improvements over the plain cpu version.

If it is too much trouble, I understand. I was just trying to figure out a way to make the code simpler. Thank you for this wonderful repo !

**Comment by fmassa** [comment]
Hi,

We don't have numpy as a hard-dependency of torchvision, so at least we would need to have it be written with PyTorch ops.

Also, could you try benchmarking with more anchors, like 2000 or 6000? I'd expect that the difference would grow bigger.

Given that we already have the ops implemented in C++, and that we will be adding support for the jit mode in the future, and we will be providing pre-compiled binaries for torchvision, I don't think it's really necessary to change the implementation with a slower (and more memory-consuming) implementation written in Python.

**Comment by karanchahal** [comment]
Alright, makes sense
