### ISSUE TITLE
MSBuild casting error

### ISSUE THREAD

**Issue by kerry-Cho** [pytorch/vision#944]
Hi.
casting error when compiling with MSBuild.
occurs in the code below.
I can not push and attach the code.

Also #936  It has not been resolved.
This is not a problem with version 1.1.0.

if ignore that part The build will be.
Thanks

*ROIAlign_cuda.cu*

<code>
line 329 
 dim3 grid(std::min(at::cuda::ATenCeilDiv(output_size, 512L), 4096L));

>  dim3 grid(std::min(at::cuda::ATenCeilDiv(static_cast<"long">(output_size), 512L), 4096L));

line 382
 dim3 grid(std::min(at::cuda::ATenCeilDiv(grad.numel(), 512L), 4096L));

>  dim3 grid(std::min(at::cuda::ATenCeilDiv(static_cast<"long">(grad.numel()), 512L), 4096L));

//////////////

*ROIPool_cuda.cu*

<code>
line 149
dim3 grid(std::min(at::cuda::ATenCeilDiv(output_size, 512L), 4096L));

> dim3 grid(std::min(at::cuda::ATenCeilDiv(static_cast<"long">(output_size), 512L), 4096L));

line 207
dim3 grid(std::min(at::cuda::ATenCeilDiv(grad.numel(), 512L), 4096L));

> dim3 grid(std::min(at::cuda::ATenCeilDiv(static_cast<"long">(grad.numel()), 512L), 4096L));

**Comment by fmassa** [comment]
I see. I might need to add a `int64_t` casting just before `4096L`. Can you try it out and report back if it works for you? If yes, I can update the code with the new casting.

**Comment by kerry-Cho** [comment]
The code below works. 
Thanks ! ^^

<code>
dim3 grid(std::min(at::cuda::ATenCeilDiv(static_cast<int64_t>(output_size), static_cast<int64_t>(512)), static_cast<int64_t>(4096)));

**Comment by fmassa** [comment]
@kerry-Cho can you send a PR that works for your system?
Thanks!

**Comment by kerry-Cho** [comment]
Build Tool : Python 3.5.6 :: Anaconda 4.1.1 (64-bit , VSCode)
OS :            Windows 10 Pro Build Version 17134
Compiler :  Microsoft Visual Studio  2017  Version 15.9.11 
CUDA :      Cuda compilation tools, release 10.0, V10.0.130
Cudnn:      cudnn-10.0-v7.3.1

tell me if  more have the information you need. 
Thanks

**Comment by fmassa** [comment]
@kerry-Cho sending a PR with the fix would be great! :-)

**Comment by kerry-Cho** [comment]
I am INVENIA Corporation. Senior Researcher. Is this the answer Right? ^^....

**Comment by kerry-Cho** [comment]
sent. PR! Thanks

**Comment by fmassa** [comment]
Fixed by https://github.com/pytorch/vision/issues/944 with fixes from @kerry-Cho , thanks a lot!
