### ISSUE TITLE
test_folder is failing on Windows

### ISSUE THREAD

**Issue by peterjc123** [pytorch/vision#948]
Using `assert_equal` on file paths is not robust enough. We have `\\` instead of `/` as the separator in paths on Windows.

**Comment by fmassa** [comment]
@peterjc123 I suppose the error comes from https://github.com/pytorch/vision/blob/249cfbf5fef41ee30f380d895ad451b0d16d2947/test/test_folder.py#L28 ?
Would a fix be to replace
https://github.com/pytorch/vision/blob/249cfbf5fef41ee30f380d895ad451b0d16d2947/test/test_folder.py#L19
with
```python
os.path.join('test', 'assets', 'dataset', 'a', path)
```
and similarly in the line below?
