### ISSUE TITLE
multi-gpu on detection and segmentation

### ISSUE THREAD

**Issue by 1771203081** [pytorch/vision#958]
would you add a function that enable we to train detection model and segmentation model on multi-gpu

**Comment by koenvandesande** [comment]
Why not have a look here: https://github.com/facebookresearch/maskrcnn-benchmark

**Comment by 1771203081** [comment]
> Why not have a look here: https://github.com/facebookresearch/maskrcnn-benchmark

thank you ,but the  maskrcnn-benchmark is complex for me ,..

**Comment by fmassa** [comment]
@1771203081 there is multi-gpu detection and segmentation scripts available in `references/` folder here, see https://github.com/pytorch/vision/tree/master/references

**Comment by fmassa** [comment]
In particular, here is the training script for multi-gpu detection https://github.com/pytorch/vision/blob/master/references/detection/train.py

You can run it with
```python
python -m torch.distributed.launch --nproc_per_node=$NGPU --use_env train.py
```

**Comment by gaussiangit** [comment]
@fmassa How do I train on multi gpu with references/segmentation/train.py script ?

**Comment by fmassa** [comment]
@gaussiangit just run the command I mentioned before
```
python -m torch.distributed.launch --nproc_per_node=$NGPU --use_env train.py
```
it should also work with the segmentation examples
