### ISSUE TITLE
`save_image` adds an offset to images?

### ISSUE THREAD

**Issue by gpleiss** [pytorch/vision#96]
In [the save_image function](https://github.com/pytorch/vision/blob/master/torchvision/utils.py#L53), there's an offset added to images. Assuming that my image tensor has values between 0 and 1, my "pre-save" tensor will have values between 0.5 and 1, resulting in a final PIL image with values between 128 and 255.

This seems like a bug? I'd propose having no offset.
Thanks! :smile:

**Comment by alykhantejani** [comment]
Hi @gpleiss,

Indeed, this has caused some problems. There is already an issue tracking this here #24 with an open PR #41. I suggest continuing to comment on #24/#41 and we close this issue?

**Comment by soumith** [comment]
fixed in master, but still needs range!
