### ISSUE TITLE
Adding DenseNets (and pretrained models) to the models

### ISSUE THREAD

**Issue by gpleiss** [pytorch/vision#97]
It would be awesome to have DenseNet imagenet models (and pretrained versions as well) available in the pytorch model zoo.

We could probably just convert the [existing pretrained torch models](https://github.com/liuzhuang13/DenseNet).

Open to a PR?

**Comment by colesbury** [comment]
Yeah, I think DenseNets would be good. The one thing to keep in mind is that it might be tricky to do the concatenation efficiently

**Comment by farleylai** [comment]
The authors address the memory efficiency in the followup [paper](https://arxiv.org/abs/1707.06990) with underlying shared memory and re-computation on bp. The current pytorch code just uses torch.cat() directly. Any plan to formalize the technique? It is likely densenet based CNNs are going to propsper for other applications.
