### ISSUE TITLE
Add S3 Bucket Dataset

### ISSUE THREAD

**Issue by rcourivaud** [pytorch/vision#970]
Download data from S3 and handle categories like ImageFolder Dataset

**Comment by fmassa** [comment]
I suppose the data format in S3 could be arbitrary? Like a zip with images, or a binary file, etc?

So there is no single S3 bucket dataset that would apply, right?

Instead, having a functionality that easily downloads from S3 might be the most generic approach, and I believe there are already libraries that do that.

**Comment by gm-spacagna** [comment]
I recommend using alluxio and fuse to mount s3 buckets locally.

**Comment by datumbox** [comment]
This issue appears to be stale, so I'm closing it. If you think it should remain open, feel free to reopen it.
