### ISSUE TITLE
Build from Source Error '/usr/local/cuda/lib64' is not a directory

### ISSUE THREAD

**Issue by jordandraper** [pytorch/vision#977]
OS: macOS High Sierra 10.13.6 (17G2307)
Xcode: 10.1 (10B61)
Apple LLVM: 10.0.0
CUDA Toolkit: 10.1 with cuDNN for CUDA 10.1

I successfully built/installed PyTorch from source. Then went to build/install Torch Vision but kept running into this error:

```
ld: warning: -L path '/usr/local/cuda/lib64' is not a directory
ld: library not found for -lcudart
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang++' failed with exit status 1
```
Something about the build is pointing to `'/usr/local/cuda/lib64'` even though the newest CUDA 10.1 installation uses `'/usr/local/cuda/lib'`.

As a fix, I duplicated the `'/usr/local/cuda/lib'` folder, renamed it `'/usr/local/cuda/lib64'` and the build worked.

**Comment by fmassa** [comment]
What command did you use to install `torchvision`?

This might be a problem with our cpp extension picking the wrong directory.

cc @yf225 [this part of the code](https://github.com/pytorch/pytorch/blob/0223d3744ad6d2f5c5b7ba8a1a687c94ae25e56d/torch/utils/cpp_extension.py#L525-L549) might have a limitation that could potentially be fixed

**Comment by jordandraper** [comment]
@fmassa I used `MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py install`

**Comment by fmassa** [comment]
Ok, thanks!

This looks like something that we should fix in PyTorch.

**Comment by DrMechanica** [comment]
I'd like to chime in and say I'm having the same issue here in July. Fixed it by editing the relevant lines in [cpp_extension.py](https://github.com/pytorch/pytorch/blob/0223d3744ad6d2f5c5b7ba8a1a687c94ae25e56d/torch/utils/cpp_extension.py#L525-L549) as mentioned by @fmassa.

**Comment by fmassa** [comment]
@DrMechanica I was about to open an issue in PyTorch when I realized that there was already one open in https://github.com/pytorch/pytorch/issues/16955 .
