### ISSUE TITLE
'fillcolor' accepts tuple

### ISSUE THREAD

**Issue by yepw** [pytorch/vision#981]
According to [here](https://discuss.pytorch.org/t/why-must-fillcolor-be-an-int-torchvision-transforms-randomaffine/46775), we can pass an RGB color (a tuple) or a greyscale color (an int) to `transforms.RandomAffine`. But the [documentation](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.RandomAffine) says the `fillcolor` argument can only be an int. This might need to be updated.

**Comment by fmassa** [comment]
We would gladly accept PRs fixing this!
