### ISSUE TITLE
Importing Mask RCNN in Torchvision 0.2.2

### ISSUE THREAD

**Issue by goyalsaransh97** [pytorch/vision#988]
On running "model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)", I get the error
"AttributeError: module 'torchvision.models' has no attribute 'detection' ". How can I solve this?
I'm using Torchvision 0.2.2 with Pytorch 1.0.2. If needed, how can I upgrade torchvision without changing Pytorch version?

**Comment by pmeier** [comment]
You can't. `torchvision.models.detection` is part of `torchvision` only since version `0.3.0` and this in turn depends on `torch >= 1.1.0`.

**Comment by fmassa** [comment]
What @pmeier mentioned is correct.

torchvision 0.3 requires PyTorch 1.1.0 or newer.

**Comment by surendrallam** [comment]
How to import Faster RCNN model on torchvision 0.2.2.

**Comment by pmeier** [comment]
@surendrallam It is not possible. You need to have `torchvision>=0.3.0`.

**Comment by surendrallam** [comment]
Thanks for your quick reply, but is there a way to load the pytorch models.

Thanks and Regards,
Surendra Allam.

Sent from my iPhone

On 28-Jan-2021, at 7:28 PM, Philip Meier <notifications@github.com> wrote:

﻿

@surendrallam<https://github.com/surendrallam> It is not possible. You need to have torchvision>=0.3.0.

**Comment by pmeier** [comment]
@surendrallam You have to be more specific: what do you actually want to do?

**Comment by fmassa** [comment]
@surendrallam you'll need to update your PyTorch and torchvision installation to use Mask R-CNN, as it relies on custom C++ operators which were not available before the 0.3.0 release.

**Comment by surendrallam** [comment]
I wanted to load pretrained Faster RCNN model and use it, I am working RISC-V arch Unleashed board, where it has availability of Torchvision 0.2.2.

Thanks and Regards,
Surendra Allam.

Sent from my iPhone

On 28-Jan-2021, at 8:28 PM, Philip Meier <notifications@github.com> wrote:

﻿

@surendrallam<https://github.com/surendrallam> You have to be more specific: what do you actually want to do?
