### ISSUE TITLE
 C ++ nn :: conv2d Can you take a look at the problem?

### ISSUE THREAD

**Issue by kerry-Cho** [pytorch/vision#989]
Hi @fmassa 

I think there is an error in the NN module. Can you confirm it?

C ++ nn :: conv2d Can you take a look at the problem?

https://github.com/pytorch/pytorch/issues/21332

**Comment by fmassa** [comment]
Hi,

I replied in the original issue. This seems to be unrelated to torchvision, so I'm closing this issue
